### ISSUE TITLE
sending same invite request twice results in duplicate contacts

### ISSUE THREAD

**Issue by jcalfee** [tutao/tutanota#1]
I may have had a network problem.  I ended up clicking on Send twice.  I had two copies of the invite in the sent folder and duplicate contacts (exact same email address).

**Comment by armhub** [comment]
We close the issue tracker on gibhub because the official issue tracker is here and we do not want to handle two trackers: https://tutanota.uservoice.com/forums/237921-general
If your issue is not listed there, please add it. Thanks!
