### ISSUE TITLE
Printing emails does not work in Windows 10

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1000]
User report:
The file spools, then disappears from the queue without printing and also the Tutanota client suddenly quits.

**Comment by ganthern** [comment]
Also crashes in Win 8.1, even using the microsoft xps document writer.

**Comment by ganthern** [comment]
this seems to have been a bug in the electron 4 beta (https://github.com/electron/electron/pull/15976) and should be resolved with our switch to 4.0.0
