### ISSUE TITLE
Tutanota Should Enable TLS 1.3 and Disable TLS 1.0/TLS 1.1

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [tutao/tutanota#1008]
Originally posted to Reddit @ https://www.reddit.com/r/tutanota/comments/adipes/strict_tls_13_service_option/

> Today Tutanota finally agreed to disable TLS 1.0 and TLS 1.1 on their service after complaints made through Twitter. TLS 1.0 and TLS 1.1 were opening the service to MITM downgrade vulnerabilities in transport encryption, making useless some of the other fancy options Tutanota provides (STARTTLS, DNSSEC, DANE, DMARC, and DKIM).

> I had also been requesting Tutanota provide TLS 1.3 as an option, possibly within a different subdomain for those who prefer it, for example, @ https:// strict . tutanota . com where users with the latest browsers or devices could access it as an option. G-Mail, Google's surveillance state all-seeing-eye e-mail service, offers TLS 1.3, so there is no reason Tutanota cannot provide it. It is a much better option now and for the future.

> I also suggested the Tutanota app to provide an option to only connect via the suggested TLS 1.3 subdomain. The app also needs to provide much more information on how it is connected to the service, as users cannot currently see any details within the app itself. There should be a full diagnostic available within the app, similar to how CloudFlare provides a secure connection check @ https://www.cloudflare.com/ssl/encrypted-sni/ and perhaps Tutanota can enable ESNI as well.

> Below is a screenshot of the transport cipher and encryption settings currently (as of 01/07/2019) offered by the Tutanota mail service.

> ![image](https://user-images.githubusercontent.com/45241958/50778575-4f6fb680-126c-11e9-9e6b-3d97571a2c4a.png)

**Comment by mpfau** [comment]
This is a server side issue and will not be tracked here. TLSv1 will be disabled as planned with the next server release (already implemented).

**Comment by RealDrGordonFreeman** [comment]
This is not only a server side issue. The thread describes the client side app improvement as well.

Should I make a new post for the app suggestions/improvements?

**Comment by mpfau** [comment]
No, it should be discussed on the forum first.

**Comment by RealDrGordonFreeman** [comment]
Okay.
