### ISSUE TITLE
Could not reach server, looks like you are offline. Please try again later.

### ISSUE THREAD

**Issue by vanokg** [tutao/tutanota#1017]
When I localy build and run web client, I can not login.
I tried different browsers like firefox, google-chrome.
![tuta-error](https://user-images.githubusercontent.com/3435030/51016072-1d769100-1599-11e9-8ebe-71f47c665728.png)

I build it and run in docker with nginx.

**Comment by vladimiry** [comment]
A quick guess, make sure you start nginx on `http://localhost:9000` address/port since I presume Tutanota goes with whitelisting policy for CORS requests. You can also run `python -m SimpleHTTPServer 9000` as written in readme file (see 9000 port is used).

**Comment by charlag** [comment]
Yes, it's likely a CORS issue. As said above, you have to either access it using `http://localhost:PORT` or proxy it.
CORS makes things complicated but it's an important security mechanism.

**Comment by kunalnagar** [comment]
@charlag I'm trying to run it via `node make -w prod` as mentioned in `HACKING.md` and getting the same issue when logging in via `http://localhost:9001/login`. Thoughts?

**Comment by charlag** [comment]
There's a slight misconfiguration, try to change this to 9000. We will fix it later.

https://github.com/tutao/tutanota/blob/ba1dcbb8a68a091af86306a151c2ae91cf5c5049/make.js#L45

**Comment by kunalnagar** [comment]
@charlag Thanks that worked. Would you like a PR for this?

**Comment by charlag** [comment]
No, we would like default to actually *not* be 9000, it's sever-side thing we will fix on our own
