### ISSUE TITLE
Selection highlighting is not working properly in IE.  

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#102]
Autofilling the mail address is working but when selecting a different mail adress the previous on ist still highlighted in black -> see picture.
![selecting](https://user-images.githubusercontent.com/31402512/31080508-2d5afee6-a789-11e7-9fa0-33608a44744b.png)

**Comment by bedhub** [comment]
IE is not supported anymore. Does not occur in Edge browser
