### ISSUE TITLE
[Android] Cannot sign in to Tutanota with 2FA from brave android

### ISSUE THREAD

**Issue by IOI-655321** [tutao/tutanota#1025]
I'm trying to sign in to the Tutanota website from android brave, i've tried with and without shields.

I'm using Bitwarden premium to auto fill my details and 2FA code but i also tried to authenticate my android user from a desktop session.  I got unexpected error messages and couldn't login both methods.

Logging into the desktop via bitwarden was fine so the details/2FA are correct.

**Comment by charlag** [comment]
Hi, thanks for reporting!
Could you please provide more details? You type in your login details and then you get 2FA window. You try to type in 2FA or approve login but you get "unexpected error" window, is that correct?

You could also try to manually copy your login details, as autofill is not always working like it should.

**Comment by IOI-655321** [comment]
Yes thats correct.

I tried copying manually and same error, I just cant login.

**Comment by charlag** [comment]
Could you please try to log in in the browser on your phone? Without a way to get an error it is very hard to find the reason

**Comment by IOI-655321** [comment]
Great thanks for the quick work identifying it.

**Comment by charlag** [comment]
Seems like any Chrome-based browser doesn't work (tried DuckDuckGo, Brave, Chrome & Chrome Dev).
It seems like browser is sending us a 'onbeforeunload` event for some reason and we reset our state because we expect page reload.

Doesn't happen in the app or in mobile Firefox or on desktop (Chome Dev or Chromium)
