### ISSUE TITLE
Update Notification is not stating that it's an update for Tutanota

### ISSUE THREAD

**Issue by dosenfleisch** [tutao/tutanota#1034]
When checking mail through desktop application (windows version) a pop up appears asking for permission to update 3.45.2.  3.45.2 of WHAT?  The app doesn't show a version anywhere and the popup doesn't identify the application.  I didn't grant permission even though it tried 2 or 3 times to get me to.

Yet, after closing the app, I checked the software list and there it was....Tutanota 3.45.2.  The application had updated itself without permission.

I have removed this beta software.  It cannot be trusted.

**Comment by ganthern** [comment]
The update notification is asking for permission to install immediately, not for the permission to install at all. There is currently no way to stop the updates after restart - just like in the browser.

Thank you for contributing to the beta.
