### ISSUE TITLE
"could not reach server" issue

### ISSUE THREAD

**Issue by legalwizard** [tutao/tutanota#1043]
Hello!

I can't sign into my tutanota account using an app anymore , which I have been using it for a long time and I haven't had any issues. App version is 2.15.4 (215040) and it is the latest one for my smartphone.
![img_20190118_183951](https://user-images.githubusercontent.com/45292881/51401549-1a147400-1b5c-11e9-9ae9-5972f0960f90.png)
BlackBerry Q10 SQN100-3 
 - OS: [10]
 - Version [10.3.3.2137]

**Comment by charlag** [comment]
Hello
We're sorry, but we don't support old app anymore for technical and security reasons.
You should be able to use the web client using the browser still. Once we add notifications to the web client, it should become even closer to the native app.
