### ISSUE TITLE
Disable insecure encryption options

### ISSUE THREAD

**Issue by ofiqfakj** [tutao/tutanota#1044]
The tutanota website which provides the web client and thus full access to my data does not provide only secure connections. It also provide encryption without PFC and thus is a security issue. Explicetly with quantum computers. You are sending emails to hire up people to make is quantum secure. Please enable PFC-only first. This is really important. https://en.wikipedia.org/wiki/Forward_secrecy

Here a simple check for that: https://tls.imirhil.fr/https/tutanota.com

Here is how it should look like: https://tls.imirhil.fr/https/mailbox.org

Please stop supporting CBC modes.
I think the best would be if you just enable one encryption mode:
ECDHE-RSA-AES256-GCM-SHA384

**Comment by mpfau** [comment]
Your analysis was outdated. Please check the current results:
https://tls.imirhil.fr/https/tutanota.com
