### ISSUE TITLE
Back button useless after clicking mailto link

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1051]
**Describe the bug**
In Firefox, when I click a mailto link, I'm taken to the tutanota web app. Clicking the back button in my browser will never take me back to the original web page I was on.

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser Firefox
 - Version 64.0.2

**Comment by charlag** [comment]
Hello!
Can you please clarify what does it mean that it won't bring you back? When you press back, it opens Tutanota on the wrong page or it doesn't open Tutanota at all and opens some other website?

**Comment by andy5995** [comment]
> Hello!
> Can you please clarify what does it mean that it won't bring you back?

For example, if I am at this page

https://packages.debian.org/stretch/geany

And I click the link on the right -> Maintainers -> Geany packaging team (a mailto link)

In the same tab, I am then taken to https://mail.tutanota.com/mail/LUMgncX-1--1 and a composition window appears in the foreground, the tutanota web interface shows in the background.

I close the composition window by clicking "close".

I click the "back" button in my browser, and the URL showing in my browser becomes https://mail.tutanota.com/mail/LUMgncX-1--1#url=mailto%3Apkg-geany-team%40lists.alioth.debian.org

I click "back" again, and the URL changes slightly to 
https://mail.tutanota.com/mailto#url=mailto%3Apkg-geany-team%40lists.alioth.debian.org

I click "back" once more, and the URL changes back to https://mail.tutanota.com/mail/LUMgncX-1--1 and the composition window reappears. If I were to close it, and hit back, the whole process repeats itself.

To get back to the original page I was viewing (on Debian), I would need to find it in my history.

**Comment by andy5995** [comment]
Oh, it's just a Firefox thing?

I agree that it should use it use a new tab.

I actually prefer the Desktop app but I'm not sure how to get that to activate instead. In my Firefox preferences, for mailto links, it says "Use Tutanota".

My XFCE desktop settings have T-bird set for mail links, but that's apparently being ignored anyway.

**Comment by charlag** [comment]
I would say we influence the problem as well by pushing many paths to the history but I see no other way around it for now. I would just recommend opening mailto in a new tab.

**Comment by andy5995** [comment]
No problem. Though as I mentioned I prefer the desktop client, which means I usually have it open (therefore I wouldn't open the web app as well). I'll just copy and paste. Really I pretty rarely use mailto links anyway. Just wanted to report a potential bug and help out a little. :)
