### ISSUE TITLE
in some cases, not all attachments are saved when "save all" is used

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1055]
**Describe the bug**
Using the desktop app, only 10 of 32 attachments are saved

**To Reproduce**
1. Receive an email with 32 attachments ;)
2. Click on "save all"
3. click "save" as each dialog (for each file) appears
4. After the 10th file is saved, no more dialog boxes appear

**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Desktop: XFCE 4.12
- Version: 3.45.2

**Additional context**
Got an email from my sister with 32 attachments (jpgs), each about 90Kb on average, nothing more than 110Kb and nothing less than 62Kb

After I've saved the 10 files, I can do things normally in the app; there's no freezing or anything unusual after that.

**Comment by ganthern** [comment]
This actually happens in chrome/chromium as well, since it's a limitation imposed by chromium.

**Comment by charlag** [comment]
Doesn't do anything with 15 files (either with default download locaiton or without one)
