### ISSUE TITLE
Unable to copy link url

### ISSUE THREAD

**Issue by ajgraves** [tutao/tutanota#1056]
When right clicking (or control clicking on Mac) a link, you get the option to copy, but it does not copy the URL, it only copies the text of the link. Some links I'd rather not open in the default browser, and the only way to do this is copy the URL and paste it in to the desired browser.

**Comment by charlag** [comment]
Hey!
From your report it's not clear if it's desktop or web client.

**Comment by ajgraves** [comment]
My apologies, this is in the desktop client

**Comment by ganthern** [comment]
This is happening because on MacOs, for _some reason_, electron is selecting the link text on right click, and an empty selection is how we detect that the user wants to copy the URL and not whatever is selected. Go figure.

**Comment by vladimiry** [comment]
Electron provides [linkURL](https://electronjs.org/docs/api/web-contents#event-context-menu) property in `context-menu` callbak, which indicates that right-clicked element is a link. See use example [here](https://github.com/vladimiry/email-securely-app/blob/d8afa5b8a29bb2fae59a9f47457e7366d2756473/src/electron-main/web-content-context-menu.ts#L11).

**Comment by ganthern** [comment]
Thanks, that's going to be useful.
