### ISSUE TITLE
Support plus aliasing

### ISSUE THREAD

**Issue by g17** [tutao/tutanota#1057]
Plus aliasing is a great feature for tagging emails. For my mail address ```me@example.com``` I usually get mails sent to ```me+tag@example.com``` delivered to my ```me@example.com``` inbox. Please add support for plus aliasing to tutanota. Currently such mails are being rejected:

    Diagnostic-Code: smtp; 550 5.7.1 <*********+test@tuta.io>: Recipient address rejected: Recipient not found

Furthermore it would be great to display a corresponding tag label on the UIs (like the one which is displayed for messages from the tutanota team).

**Comment by mpfau** [comment]
Please don't create feature requests on github. 

Besides that, it is impossible to implement this feature as + is a valid character for usernames and accounts have been registered with it already.

**Comment by clescot** [comment]
I'm agree with @g17 , this security feature is very important to track which one has sell your email.
A higher subscription price for this feature makes sense. 
if Accounts already registered with this character  is a problem which cannot be solved, 
you should provide this feature for custom domains at least.
