### ISSUE TITLE
Improved phishing protection

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1065]
Options:
* Let users mark phishing mails and mark those within other mailboxes, too (or remove them)
* Use Honeypots to find and mark spam/phishing mails

**Comment by KitchM** [comment]
This is a great idea.  In lieu of not being able to contact management regarding messages received, I believe this will solve many scam attempts.

**Comment by charlag** [comment]
Closed by 0752204753a904263029fd336ca393a8c2a8a996

**Comment by vitoreiji** [comment]
If I accidentally mark as not phishing I cannot undo this.

**Comment by armhub** [comment]
Error when clicking on email with relative link, like in our invoice notification (Settings -> Payment): Logger.js:91 workerImpl.onerror Uncaught TypeError: Failed to construct 'URL': Invalid URL https://test.tutanota.com/worker.js 1 271553 TypeError: Failed to construct 'URL': Invalid URL
    at MailFacade.value (MailFacade.js:331)
    at checkMailForPhishing (WorkerImpl.js:331)
    at Queue.value (WorkerProtocol.js:126)
    at Queue._transport._transport.onmessage (WorkerProtocol.js:99)
