### ISSUE TITLE
Desktop App Maarked as a "Thread" by Antivirus

### ISSUE THREAD

**Issue by lasscap** [tutao/tutanota#1071]
**Describe the bug**
The antivirus software McAfee marks the desktop app as a threat by putting it into "quarantine" on Windows 7. 

**To Reproduce**
1. Have McAfee installed
2. Download the desktop app for Windows
3. The app is put into "quarantine"

**Expected behavior**
I expected to just use the program and be able to install it normally.

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by ganthern** [comment]
False positives happen, please report this problem to the manufacturer of your antivirus (if they have a procedure for this).

Maybe you can add an exeption for the client.
