### ISSUE TITLE
a new input field is created when typing email address in new contact.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1074]
**Bug in web app**

**Describe the bug**
With every character input in the address field of a contact a new input line is created.

**To Reproduce**
1. Open "new contact" dialog
2. enter characters in email address field

**Comment by charlag** [comment]
Created an issue in mithril repository:
https://github.com/MithrilJS/mithril.js/issues/2365

It's a bug caused by us but could be improved with streams design adjustment

**Comment by charlag** [comment]
Opened a PR for mithril:
https://github.com/MithrilJS/mithril.js/pull/2369
