### ISSUE TITLE
Improvement: Add proxy server option to apps

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [tutao/tutanota#1078]
**App Improvement**

The desktop app (and perhaps all Tutanota apps) should have a separate proxy configuration option built-in so that user's can specify which exact proxy server they would like the app to connect through. This could be HTTP(S) or SOCKS5, with DNS also passed through the proxy.

**Example**

A good example of this type of proxy option would be Mozilla Firefox, which can set a proxy server independently of the operating system across all platforms. 

For desktop, go to Firefox Options --> General --> scroll down to 'Network Settings' --> click 'Settings'. For mobile, go to about:config through the address bar and search for 'proxy' using the config search feature.

**Comment by mpfau** [comment]
Please do not create feature requests on github. You can discuss them on reddit and we will create a feature request if needed.

**Comment by RealDrGordonFreeman** [comment]
Okay.
