### ISSUE TITLE
[iOS] 'UIkit/UIkit.h' file not found

### ISSUE THREAD

**Issue by gfaidley** [tutao/tutanota#1080]
**Bug in mobile app**

**Describe the bug**
When building the iOS client from source I get a "'UIkit/UIkit.h' file not found" error.  This is on line 24 of TUTViewController.m

`#import <UIkit/UIkit.h>`

My guess is that you must be building on a case insensitive file system because the correct name of that file has a capital "K" in both UIKit's. It should read:
`#import <UIKit/UIKit.h>`

**To Reproduce**
1. Try to build from source on a case sensitive file system

**Expected behavior**
Should not get that error

**Screenshots**
<img width="428" alt="screen shot 2019-02-03 at 9 58 32 pm" src="https://user-images.githubusercontent.com/36120988/52189563-ec3b5a80-27fe-11e9-90a4-e032fd3138b0.png">

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by charlag** [comment]
Oh, thanks, we'll fix that (or you can send a pull request if you want)!

**Comment by gfaidley** [comment]
I've never sent a pull request before but now seems like a great time to learn.

**Comment by ganthern** [comment]
this is resolved
