### ISSUE TITLE
Saving contact form removes html tags

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1091]
**Describe the bug**
Structure of additional header and footer html can be destroyed when saving contact form.

**To Reproduce**
1. Edit contact form header in HTML mode and put html tag around the content, e.g. `<center></center>`
2. Edit and safe contact form without changes.
3. Edit contact form and view header in HTML mode.
-> Additional <center> tag has been removed

**Comment by armhub** [comment]
This occurs only for the center tag. It is not supported in HTML 5 any more and therefore stripped from the html. We should accept this.
