### ISSUE TITLE
Link to contact form does not trigger application update

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1092]
**Bug in web app**
When opening a contact form  (<whitelabeldomain>/contactform/test) the service worker does not apply the update of the new client. The update of the new client is only applied when accessing the root of the whitelabel domain. 

worker init time (ms): 293
sw.js:144 SW: being installed
main-boot.js:1 No session to delete
worker.js:1 ws close:  Tue Feb 05 2019 16:26:21 GMT+0100 (Central European Standard Time) closeOption:  terminate state: automatic
worker.js:1 ws state:  terminated
Navigated to https://<customdomain>/?r=contactform%2Ftest
NotificationOverlay.js:38 Registering ServiceWorker
The script resource is behind a redirect, which is disallowed.
Failed to load resource: net::ERR_UNSAFE_REDIRECT
test:1 Uncaught (in promise) DOMException
Promise.then (async)
init @ NotificationOverlay.js:3
(anonymous) @ app.js:21

SearchModel.js:58 worker init time (ms): 373

**Comment by charlag** [comment]
Seems like the client tries to register service worker not from the root but from the `/contactform/name/sw.js`
