### ISSUE TITLE
Configure notifications per folder

### ISSUE THREAD

**Issue by snaggen** [tutao/tutanota#1095]
I subscribe to some mailing lists which receives mail quite frequent, and they are not that important. I normally skim through them once or twice a day. 
However, these mailing lists render the notifications useless since I gets notified constantly. 
For it to be possible to use tutanota as the primary mail client and still read these kind of lists, it must be possible to disable notifications for these mails. 

Having a setting per folder to disable notifications would solve this problem.

**Comment by charlag** [comment]
Please don't open feature requests on Github. I will just say that it is rather complicated task because of the e2e encryption.

**Comment by snaggen** [comment]
Sorry for the feature request here... and I understand that e2e complicates things. But isn't this just a matter of when to do the notification? At some point you decrypt the message, apply rules to move the mail to the proper folder, at that point it should be possible to add some logic to see if the message should trigger a notification or not.
