### ISSUE TITLE
List gestures require too much precision 

### ISSUE THREAD

**Issue by snaggen** [tutao/tutanota#1096]
When I left swipe a mail in a mailbox to delete it, I often fail with the swipe and it doesn't work. I started to investigate why this happens since the mail was swiped so the whole red delete area is visible, but it often bounced back.
It seems that my swipes tend to not be exactly straight, and at the very end of the row the finger leaves the row over the bottom edge (still in a left motion). For the delete to work the finger seems to have to leave the row through the left edge. This is probably a lot more picky than most other apps, since I only experienced it with tutanota.

My expectation is that when I drag the mail to the left so that the whole red delete area is visible and my finger leaves the row in a left motion, the delete action should happen.

**Comment by charlag** [comment]
Hey
Yes, you're right, our gesture detection is not very intelligent right now. I thought that it is only the case when you didn't make enough motion and then moved to another row but your guess is correct: on any movements outside the container the gesture in cancelled.
Thanks for the report, we should fix that.
