### ISSUE TITLE
Mark emails for follow-up

### ISSUE THREAD

**Issue by kimbriggsdotcom** [tutao/tutanota#1103]
- [ ] This is not a feature request. I will request features via email or on the forum.
- [ ] This issue doesn't fit into provided templates.

I apologize, but you need to be more specific than "on the forum".   I have no idea what "the forum" is.  Alternatively, you could provide an actual email address and I would send it there.

Email client should have a way to mark an email as needing a follow-up.  This has been done with flags or stars, for example.  Thank you.

**Comment by charlag** [comment]
Sorry for the confusion, our template is very new.
But to be fair there's even a "contact" page on the website:
https://tutanota.com/contact?page=feature

It was discussed here before:
https://www.reddit.com/r/tutanota/comments/ahrwib/starring_important_emails/eelr2ra/

**Comment by kimbriggsdotcom** [comment]
I really don't care how it's done, but It is fair to say that it is not standard practice to do software development through the Contact link on your homepage.   I hope it can be made less ambiguous for the next person (or me in a year, because I'm old).  Thanks.


Feb 8, 2019, 2:35 AM by notifications@github.com:
