### ISSUE TITLE
Website: Support mail action does not open the mail editor

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1111]
When I click on "contact premium support" on the contact page, I want Tutanota to open a mail editor to send my support request. The website links currently targets `https://mail.tutanota.com?action=supportMail` but could be changed.

An upgrade dialog should be shown, if I am not a premium user.

**Comment by armhub** [comment]
For starter users the mail editor should also be shown.

**Comment by charlag** [comment]
Should not be availabel for free users

**Comment by trentks** [comment]
Hi, 

I have a premium account and this appears to be broken again.

Clicking the target link `https://mail.tutanota.com?action=supportMail` from https://tutanota.com/contact page gets me to log into the webmail, but then does not result in any kind of email writing to support, or anything out of the ordinary. It's a dead-end.
