### ISSUE TITLE
Easy to delete emails by accident, can't undo

### ISSUE THREAD

**Issue by camelCaseSucks** [tutao/tutanota#1115]
**Bug in mobile app**

**Describe the bug**
I can delete emails just by swiping left which is easy to do by accident. Outlook uses this method of deleting emails as well, but after deleting it shows a popup with an undo button for several seconds. Tutanota does not. Swiping deletes emails permanently with no way to undo.

Tutanota should have an undo button, or even better, make swiping left reveal a delete button that I have to press to delete the email. This would prevent me from deleting things by accident in the first place.

 - Device: OnePlus X
 - OS: Lineage 14.1

**Comment by mpfau** [comment]
This is not a bug but a feature request.

**Comment by camelCaseSucks** [comment]
Sorry, I didn't see the "Don’t see your issue here? Open a regular issue." link on the new issue page. Now I see the issue template directs me to https://tutanota.com/contact?page=feature so I assume you don't want feature requests here? Is that why it was marked wontfix or is there some other reason? Should I re-post the issue there? It would be nice if you explained why when closing issues.

**Comment by mpfau** [comment]
Please discuss feature requests with the community on our forum first. We might create a feature request on github afterwards.

Thanks!
