### ISSUE TITLE
Enable TLS 1.3

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [tutao/tutanota#1120]
Add TLS 1.3 to the roadmap.

OpenSSL supported TLS 1.3 cipher suites as of 02/14/2019:

- TLS_CHACHA20_POLY1305_SHA256 
- TLS_AES_256_GCM_SHA384
- TLS_AES_128_GCM_SHA256
- TLS_AES_128_CCM_8_SHA256
- TLS_AES_128_CCM_SHA256

More info: https://wiki.openssl.org/index.php/TLS1.3

**Comment by mpfau** [comment]
This is already part of our server side roadmap.

However, it will take some time till this is implemented. TLSv1.3 is not something that can be simply "enabled". TLSv1.3 implementations are still pretty new. We already investigated a few of them. Some of them currently lack runtime performance while others not yet landed in our linux distribution.
