### ISSUE TITLE
Desktop app freezes after a period of time

### ISSUE THREAD

**Issue by ajgraves** [tutao/tutanota#1121]
I've noticed this on both Windows and Mac. If I leave the app running, usually I notice it if I close the lid overnight on the laptops and let them hibernate. The next morning none of the features of the app are responsive. I can't click on mails or folders, I can't go in to settings, etc. I have to close and re-launch the app. I did not notice this behavior until about 2-3 releases ago.

**Comment by ganthern** [comment]
Can you clarify if you need to restart the whole app to fix this or if you can create new windows that are then responsive?

**Comment by ajgraves** [comment]
> Can you clarify if you need to restart the whole app to fix this freeze or if you can create new windows that are then responsive?

I have not tried to open a new window, I have just closed and re-launched the program. I will try that again after I notice it again. I've taken to not leaving the app open for long periods of time.

**Comment by ganthern** [comment]
That's understandable. Thanks for your help.

**Comment by vladimiry** [comment]
Happened to me on Linux too after computer got out of sleep/hibernate mode.

**Comment by ajgraves** [comment]
I just caught this again. I launched a new window, and that one was responsive once launched. The original window remained frozen, I just closed it though since the new window worked. Still odd behavior though.

**Comment by ganthern** [comment]
> Still odd behavior though.

Definitely. We can't reproduce this yet, but hopefully we get something when we increase the length of the tests.

**Comment by armhub** [comment]
This should be the same issue as #1151 and fixed.

**Comment by ganthern** [comment]
This issue may be a result of chrome's background throttling causing a modal to be activated, but not rendered, therefore blocking all clicks in the page.

**Comment by ajgraves** [comment]
This issue is still occurring on the latest release

**Comment by mpfau** [comment]
The fix has not been released. It is part of https://github.com/tutao/tutanota/milestone/62
