### ISSUE TITLE
TLS 1.2 connections to mail.tutanota.com are being downgraded from AES-256 to AES-128

### ISSUE THREAD

**Issue by RealDrGordonFreeman** [tutao/tutanota#1124]
**`TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` connections are being automatically downgraded to `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`.** 

**Behavior:** 

Connections to mail.tutanota.com are being downgraded from a stronger TLS 1.2 cipher suite to a less strong TLS 1.2 cipher suite, even when a stronger cipher suite is available on the client. This behavior is confirmed on Firefox 65. Clarification is needed if this is a client browser side problem only, or a server side problem, or a combination of both.

**Steps to Reproduce:** 

1. Disable `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` and all other weaker cipher suites in Firefox then reload mail.tutanota.com. The site will load with `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`. 

2. Enable `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` while leaving `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` enabled as well then reload mail.tutanota.com.**The weaker cipher suite will be chosen.**

**Note:** 

This could be a client side browser problem as well because of the initial `ClientHello` message sent by the browser. The server should try to force the highest available cipher suite if possible.

**Update - Server side suite preference ordering:**
 
From [RFC 5246](https://tools.ietf.org/html/rfc5246#section-7.4.1.2):

> The cipher suite list, passed from the client to the server in the ClientHello message, contains the combinations of cryptographic algorithms supported by the client in order of the client's preference (favorite choice first). ...The server will select a cipher suite or, if no acceptable choices are presented, return a handshake failure alert and close the connection.

Cipher Suite Ordering - Apache Example

From Apache mod_ssl documentation @ [apache documentation - mod_ssl - cipher suite directive](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslciphersuite)

> Now where this becomes interesting is that these can be put together to specify the order and ciphers you wish to use. To speed this up there are also aliases (SSLv3, TLSv1, EXP, LOW, MEDIUM, HIGH) for certain groups of ciphers. These tags can be joined together with prefixes to form the cipher-spec. Available prefixes are:
>
>     none: add cipher to list
>     +: move matching ciphers to the current location in list
>     -: remove cipher from list (can be added later again)
>     !: kill cipher from list completely (can not be added later again)

**Comment by RealDrGordonFreeman** [comment]
From [The Man](https://security.stackexchange.com/users/37315/steffen-ullrich) Himself:

> The client sends only what ciphers it supports in the order of their preference. The server then selects one of these ciphers - which means only the server ultimately decides which cipher gets used.
> 
> It is fully up to the server which server gets selected from the offered ones, i.e. the server might take the client preferences in account but might also completely ignore it. In fact, many servers have a configuration option which allows the server to use either the cipher preferred by the client or the cipher preferred by the server.
> 

https://security.stackexchange.com/questions/203684/who-is-responsible-for-choosing-a-tls-cipher-suite-the-client-or-the-server

**Comment by RealDrGordonFreeman** [comment]
@chrlag This issue has not been resolved yet. I think it might be fixed on the server side.

**Comment by RealDrGordonFreeman** [comment]
This issue has not been resolved yet. I think it might be fixed on the server side.

**Comment by mpfau** [comment]
This is not a client side issue and can only be resolved on the server side.

It is currently not an issue as AES-128 and SHA-256 are both safe enough. We currently prioritize between those two algorithms based on runtime performance.

You might disable algorithms in your browser which you don't want to use.

**Comment by RealDrGordonFreeman** [comment]
Okay, thank you.
