### ISSUE TITLE
Is there real desktop application, not an Electron wrap of the existing website

### ISSUE THREAD

**Issue by MahmudOnWeb** [tutao/tutanota#1126]
This is a feature request, because I cannot enter it properly on your website.
Is there a real desktop client, developed from ground up, it is not needed even to be a store application, or the only option is to use the Electron made exe, which is the existing website put in chrome shell or something.

**Comment by charlag** [comment]
Electron app is the only app we provide and it's more than just a website, e.g. it's getting background notifications soon.
