### ISSUE TITLE
Test UI elements with new components

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1127]
- recovery code password dialog should not autofill
- login settings viewer (adding/removing OTP/U2F, session management)
- TextInputDialog (ie folder name)
- TextAreaInputDialog (whitelabel child comment editor ?)
- add domain dialog
- alias management
- password input after sessionexpirederror

header bars:
- legacy download dialog in old safari
- upgrade reminder
- wizard dialog (upgrade/signup/captcha/terms)
- contact form request dialog
- F1 help
- contact form editor
- custom colors dialog
- buy dialog
- email alias / storage options dialog
- sign order processing agreement
- switch subscription
- add domain dialog

**Comment by mpfau** [comment]
Everything seems fine :+1: 

Only testable with app:
* Terms dialog

Not testable:
* legacy download in old safari
* password input for SessionExpiredDialog
