### ISSUE TITLE
Can't connect to server popup on deletion of large folder

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#113]
Service request takes too long without any data transfer which leads to a timeout error.

**Comment by mpfau** [comment]
When deleting a large selection of mails, we start deleting them from the beginning of the list. When deleting all contents of a folder, we start deleting from the end of the list.

Both deletions should start at the beginning. This would also improve the visibility of the progress on the client.

**Comment by armhub** [comment]
Fixed:
* Delete mails from start of list
* Remove mail list selection to avoid loading next mail for each deleted mail
