### ISSUE TITLE
Show information that Tutanota aliases can only be deactivated

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1131]
When adding a Tutanota alias users are not aware that these aliases can not be deleted later but only deactivated. We should show this information.

**Comment by ganthern** [comment]
related: https://github.com/tutao/tutanota/issues/679

**Comment by ganthern** [comment]
https://github.com/tutao/tutanota/commit/b6cdbed03500cf0b3ab30b87c355b1245f0a57c3
