### ISSUE TITLE
No option to "skip" when trying to save attachment that already exists

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1136]
**Describe the bug**
When saving multiple attachments, there's no option to "skip" if a file with that name already exists.

Reproduces each time

**To Reproduce**
1. on an email with multiple attachments, click "save all"
2. If one of the filenames exist, user is presented with "cancel" or "replace" dialog.
3. Clicking cancel will close the dialog, and the user is presented with an option to save that same file, but can't advance to the next file to be saved.

**Expected behavior**
A "skip" and "rename file" option needs to be added.

**Desktop (please complete the following information):**
 - OS: Debian buster/testing
 - XFCE
 - Version 4.12

**Comment by charlag** [comment]
Hey. Thanks for the report.
I would say that if we fail to write one file, we should just continue, whatever the reason is. Then when you cancel that file it should just continue downloading.

**Comment by ganthern** [comment]
You should have a "Cancel" button on the "Save As" dialog itself, that one skips the current file.

We'll still need to improve handling a lot of attachments, though.

**Comment by ganthern** [comment]
closing this specific issue for now due to the availability of skipping the file via "Cancel" on the file dialog
