### ISSUE TITLE
Wrong end of Premium subscription date shown in settings

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1137]
How to reproduce:
1. Unsubscribe from Premium
2. Wait one day
-> End of subscription date shown is wrong ("Subscription: Premium (canceled by <date>)")

Always the current date is shown there because no date is returned from the server.

**Comment by paw-hub** [comment]
This is no longer possible to reproduce, since downgrading is now instant and there is no case where `customer.canceledPremiumAccount` will ever be set to true.
