### ISSUE TITLE
email detected as "unsupported"

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1149]
**Describe the bug**
I wouldn't really say this is a bug, but...

On Feb 10, I received an email with the reply-to address as "noreply@github.com" (Subject: Unsupported mail), however, the contents are apparently from Tutanota:

```
Dear Tutanota user, 

we have received a mail that does not respect internet standards and is currently not supported by Tutanota. 

The unsupported mail has been attached to this notification message and you may be able to open the attached mail with an external mail program like Thunderbird, Outlook or Apple Mail.

Best,
Your Tutanota team.
```

I opened the attached email in Thunderbird, and it's a standard auto-notification of a response from a GitHub ticket.

Normally I just receive replies to GitHub tickets to my tutanota account, as expected.

**To Reproduce**
Unknown

**Expected behavior**
Reception of the email as normal

**Desktop (please complete the following information):**
 - OS: Debian buster/testing
 - XFCE 4.12

**Additional context**
I can forward a copy of the .eml attachment but would like to do so privately. How can I do that? A direct message from [my Mastodon account](https://mastodon.sdf.org/@gravityisforsuckers)? Or email to the tutanota support email?

**Comment by ganthern** [comment]
This happens when we get an error during mail reception from external servers. We are aware that this sometimes happens with github mails (we also have examples) and are working on it.

**Comment by guoyunhe** [comment]
I start to get this kind of errors since last week. It is also from github notification.

**Comment by KainerW** [comment]
I get this from any email from my hosteurope server. this is a bug, not a feature if you ask me.
