### ISSUE TITLE
Add panic button support

### ISSUE THREAD

**Issue by Perflyst** [tutao/tutanota#1152]
### Actual behavior

The Tutanota app does not appear on the list of apps responding to Ripple panic button

### Expected behavior

Tutanota app appearing on the list and having the option to configure behavior. The options could be:

    Hide the app
    Logout from all tutanota accounts
    Erase all offline stored data on the device

Resources

https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button
https://dev.guardianproject.info/projects/panic/wiki

**Comment by Perflyst** [comment]
(Not a bug, it is a feature request)

**Comment by 1anomaly1** [comment]
I'LL NOT USE TUTANOTA'S APP, AND HAVE ALREADY UNINSTALLED FOR BLOCKING USE IF OLD VERSIONS. THE WHOLE POINT OF FOSS IS FREEDOM FROM PROPRIETARY CONTROL OVER OUR APPS. GERMAN DEVELOPMENT FOR THIS APP ARE USURPING THE SPIRIT OF OPEN SOURCE ON PURPOSE, AND SHOULD BE BANNED!!!!! TO ALLOW THESE KIND OF DEVS TO CONTINUE IS EXACTLY THE DIRECTION OF GOOGLE.

**Comment by charlag** [comment]
We don't accept feature requests here, sorry. That's why we have all this ticks and checks.
