### ISSUE TITLE
Changing default delivery does NOTHING

### ISSUE THREAD

**Issue by jennajont** [tutao/tutanota#1153]
**Describe the bug**
Under user settings, email. Change default delivery to "not confidental" for sending emails DOES NOTHING. All emails sent are encrypted.
**To Reproduce**
1. Go to 'user settings, email.'
2. Click on 'Change default delivery to NOT CONFIDENTIAL'
3. Send email. 
4. ALL EMAILS SENT ARE STILL ENCRYPTED.

**Expected behavior**
Changing default delivery to "NOT CONFIDENTIAL" should allow one to send emails NOT ENCRYPTED.

**Desktop (please complete the following information):**
 - OS: [macOS Mojave 10.14.3]
 - Desktop Environment, if applicable (on MAC)
 - Version [e.g. 3.48.1]

**Additional context**
Same behavior with ANY email address; also should work with other Tutanota.* receipients but does not. Default behavior is ALWAYS ENCRYPTED.

**Comment by charlag** [comment]
Hello
The setting you describe is to set *default* behaviour (do we propose to add a password for the new email or not). For external recepients you can always select if it's encrypted or not using the "lock" button near the subject. For internal recepients it's always encrypted.
Please confirm if it clarifies something.

**Comment by jennajont** [comment]
Whether the setting is set to encrypted or not for external recipients, it does not change. I now understand that internal recipients are set to encrypted and that can not be changed. But i have tested with external recipients *without a tutanota.* address* by setting to NOT ENCRYPTED, and the emails are still sent encrypted.

**Comment by charlag** [comment]
Okay, let's confirm it: you sent an email to the external recipient, the lock symbol in mail editor was off (*not* red) and the recipient still received it as encrypted (notification email to open it with a link). Is that correct? Because I cannot reproduce it yet.

**Comment by jennajont** [comment]
That is correct. However, I have just tested it with every known non-tutanota address i can find, and it is working as it should be.
I will say that i deleted all contacts out of my address book before testing it in the event there was some individual setting per contact
that put encryption on an individual basis.

Mark this one solved for the time being, and I will monitor when I send emails. If it happens again, i will repost to the original bug posting.

Many thanks.
