### ISSUE TITLE
Icon not displayed correctly in tray [KDE]

### ISSUE THREAD

**Issue by Izumemori** [tutao/tutanota#1154]
**Describe the bug**
The tray icon is broken on KDE.

**To Reproduce**
1. Be on KDE
2. Install the tutanota desktop client
3. Have it in the tray

**Expected behavior**
Seeing the tutanota logo properly in the tray.

**Screenshots**
![img](https://learning-julia.might-be-super.fun/F5TqdQW.png)

**Desktop:**
 - OS: Arch Linux
 - Desktop Environment: KDE
 - KDE Version: 5.15.2

**Additional context**
I've seen this happen with other electron programs, not sure why it happens but it seems to not directly be an electron issue.

**Comment by snaggen** [comment]
Is it a regular screen or hidpi?

**Comment by Izumemori** [comment]
it's a regular screen, 1080p, no scaling settings

**Comment by charlag** [comment]
@Izumemori hey, thanks for reporting
Is there any way to check if it happens to all Electron apps or only to some of them?

**Comment by Izumemori** [comment]
@charlag I don't think there's any better way than installing a bunch and checking if they have the same problem, I have a few installed. For example:
Discord doesn't have this problem, Google Play Music Desktop Player does have this problem, and tutanota does too.

**Comment by charlag** [comment]
Okay, thatnks; I failed to communicate but you deciphered my message. It does not happen for *some* so it does not happen to *all*.
Would be nice if someone with minimal knowledge of KDE internals could look at it.

**Comment by algv** [comment]
fixed in electron [4.1.2](https://github.com/electron/electron/releases/tag/v4.1.2)

**Comment by charlag** [comment]
We use 4.1.4 - does it mean that it's fixed now?

**Comment by Izumemori** [comment]
Indeed it is:
![](https://i.izumemori.dev/i2v8wSL.png)
Thanks a lot!
