### ISSUE TITLE
Migrate to rollup

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1159]
We know for a long time that SystemJS-Builder is deprecated and we have issues with it (long builds, #906, now we cannot use opaque types from Flow in dist stripts because SystemJS plugins cannot parse that).
Dynamic import was experimental pretty much everywhere until recently but now it's availble in Parcel [1], Webpack [2] and Rollup [3] as well as hot reloading and many other features like preloading modules so there's little reason to roll out our own scripts (which look scary and hard to maintain).

With that we should finally migrate to Babel 7 and `babel-present-env`.

Maybe some of that will improve sourcemaps for Firefox.

[1] https://parceljs.org/code_splitting.html
[2] https://webpack.js.org/guides/code-splitting
[3] https://rollupjs.org/guide/en#code-splitting

We decided to go with rollup for now.

**Comment by charlag** [comment]
- [ ] Test errors in dist coming from native parts
- [ ] Test desktop on all platforms

**Comment by charlag** [comment]
I run LIghthouse on 3.80.4 and 3.80.5 and it looks pretty good:

----

**before**:
First Contentful Paint
0.2 s
Speed Index
0.6 s
Largest Contentful Paint
1.0 s
Time to Interactive
0.5 s
Total Blocking Time
100 ms
Cumulative Layout Shift
0

there was a warning about most of main.js being unused on load


requests:
Resource Type | Requests | Transfer Size
-- | -- | --
Total | 32 | 1,039.7 KiB
Script | 6 | 784.3 KiB
Other | 25 | 254.4 KiB
Document | 1 | 1 KiB
Stylesheet | 0 | 0 KiB
Image | 0 | 0 KiB
Media | 0 | 0 KiB
Font | 0 | 0 KiB
Third-party | 0 | 0 KiB

longest tasks on main thread:
URL | Start Time | Duration
-- | -- | --
/common.js(test.tutanota.com) | 286 ms | 120 ms
/main.js(test.tutanota.com) | 406 ms | 89 ms
/libs.js(test.tutanota.com) | 234 ms | 52 ms


---

**after**:
First Contentful Paint
0.3 s
Speed Index
0.6 s
Largest Contentful Paint
0.9 s
Time to Interactive
0.4 s
Total Blocking Time
0 ms
Cumulative Layout Shift
0

requests:

Resource Type | Requests | Transfer Size
-- | -- | --
Total | 175 | 1,831.6 KiB
Other | 132 | 1,366.1 KiB
Script | 42 | 464.5 KiB
Document | 1 | 1 KiB
Stylesheet | 0 | 0 KiB
Image | 0 | 0 KiB
Media | 0 | 0 KiB
Font | 0 | 0 KiB
Third-party | 0 | 0 KiB

longest tasks on main thread:

URL | Start Time | Duration
-- | -- | --
/RouteChange-9209548f.js(test.tutanota.com) | 358 ms | 52 ms


----

For most metrics it looks much better but there are still a lot of requests. Actually there are around 50, I'm not sure where lighthouse gets the rest from. Looks like favicon is lost?

**Comment by charlag** [comment]
- favicon is missing
 - all translations are fetched and cached by service worker

**Comment by charlag** [comment]
Seems like systemjs indeed uses fetch but it's supported since iOS 10.3, Chrome 42 and Firefox 40 which is anyway roughly what we support

**Comment by charlag** [comment]
@bed found that whitelabel is broken with:
```
Unhandled rejection ReferenceError: Cannot access 'D' before initialization
  at V  defaultTheme (../../src/gui/theme.js:94:33)
  at Object.execute  updateCustomTheme (../../src/gui/theme.js:56:1)
  [original] at i (https://custom.keemail.de/polyfill.js:1:36845)
  [original] at _ (https://custom.keemail.de/polyfill.js:1:36814)
  [original] at https://custom.keemail.de/polyfill.js:1:36755
  [original] at Array.forEach (<anonymous>)
  [original] at _ (https://custom.keemail.de/polyfill.js:1:36725)
  [original] at https://custom.keemail.de/polyfill.js:1:36383
  [original] at c (https://custom.keemail.de/polyfill.js:1:112668)
  [original] at A._settlePromiseFromHandler (https://custom.keemail.de/polyfill.js:1:85572)
  [original] at A._settlePromise (https://custom.keemail.de/polyfill.js:1:86372)
  [original] at A._settlePromise0 (https://custom.keemail.de/polyfill.js:1:87071)
  [original] at A._settlePromises (https://custom.keemail.de/polyfill.js:1:88423)
  [original] at A._fulfill (https://custom.keemail.de/polyfill.js:1:87441)
  [original] at a._resolve (https://custom.keemail.de/polyfill.js:1:92038)
  [original] at a._promiseFulfilled (https://custom.keemail.de/polyfill.js:1:92379)
```

**Comment by johnbotris** [comment]
this error occurs on startup of the windows desktop client

```
(node:8132) UnhandledPromiseRejectionWarning: TypeError: t is not a constructor
    at new exports.DesktopIntegratorWin32 (C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\desktop\DesktopIntegratorWin32-0c5bdf65.js:1:196)
    at C:\Users\flops\AppData\Local\Programs\test Tutanota Desktop\resources\app.asar\desktop\DesktopMain-3db79dff.js:13:209845
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by charlag** [comment]
Yes  it was incorrect import for winreg, I fixed it and will push soon

**Comment by charlag** [comment]
Works on Safari 14 (Catalina)

**Comment by charlag** [comment]
Switching color from login view works in FF but not in Chrome?

**Comment by charlag** [comment]
No, actually it was broken everywhere.
