### ISSUE TITLE
Close session if tab is closed

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#116]
If the browser or tab is closed, the session should be closed automatically. There is no need to click on the logout-button, then.

**Comment by armhub** [comment]
Tested close tab, close browser, reload in the following browsers:
Chrome/Brave on Android: Session only sometimes closed when closing tab
Chrome/Brave on Android: Session not closed when browser is closed
Firefox on Ubuntu: ok
Firefox on Windows: ok
Edge on Windows: ok
Safari on maxOS: Session not closed when browser is closed
Safari on iOS: Session not closed when tab or browser is closed

**Comment by mpfau** [comment]
9c65d38 should have fixed this for Safari on MacOS
