### ISSUE TITLE
[android] darkening background while animation : slow

### ISSUE THREAD

**Issue by PhieF** [tutao/tutanota#1162]
Hi,

This isn't really a bug, just a remark
As a dev I've noticed that darkening backgrounds while animating (for example to make menu appear, etc) can really drop the framerate and I guess it would be better either to keep it bright, or to make it darker in one step, not progressively

Do you see what I mean ?

Thanks for this app :)

**Comment by charlag** [comment]
Hey
Yeah, dropdown menu is laggy but not because of the background. We change properties which cause re-layout like width & height so it's not done on the GPU (unlike most other animations).

7 Mar 2019, 19:19 by notifications@github.com:

**Comment by charlag** [comment]
We'll solve it eventually but I will close it for now. Feel free to send a fix.

**Comment by charlag** [comment]
Another reason may be that your browser tries to resist fingerprinting and throttles some time measurements. It can be solved with more native animation engine.
