### ISSUE TITLE
The Greek letter 'π' is displayed incorrectly with the default font in Windows 7

### ISSUE THREAD

**Issue by ckoul** [tutao/tutanota#1182]
![ss](https://user-images.githubusercontent.com/3018185/54511496-c9ea4000-4959-11e9-9d27-0e4d6a809d20.PNG)

- [x] This is not a feature request. I will request features on the forum or via support (see [contact page](https://tutanota.com/contact?page=feature)).
- [x] This issue doesn't fit into provided templates.

**Comment by charlag** [comment]
Hey
We don't change fonts, we use system ones. I'm not sure it's our fault. Do you have an idea which font is in use and which one could work better?

**Comment by ckoul** [comment]
Looking in my fonts folder I found a Helvetica font which was not installed (directly) by me and did not support the Greek set of characters. I deleted it and now 'π' is shown from the same font as the rest of the characters.

I'll close this report as it is obviously dependent on my installation.
