### ISSUE TITLE
[iOS] Japanese input doesn't work with search field

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1189]
> on App and chromium on iOS(Idk Android) I couldn't input Japanese words correctly.(probably same in languages requiring converting like Chinese and Korean )
> 
> When entering and converting the words, converted words are disappear, as a result not be able to input Japanese words,
> 
> Maybe incremental search is the cause of the problem.
> 
> If I paste from clipboard it will work properly.

**Comment by vitoreiji** [comment]
Could not reproduce, probably solved along with some other fix.
