### ISSUE TITLE
TOTP ist broken - Nitrokey pro

### ISSUE THREAD

**Issue by razzor1984** [tutao/tutanota#119]
Hello, i tried it several times but the "secret" wich is delivered in the setup TOTP process (beta mail Client Web) is crashing the Nitrokey app. 
I have two options in the settings panel for TOTP - Base32 and HEX. The string(secret) which is deliverd should be Base32 or iam mistaken?
Has anybody successfully setup the nitrokey(TOTP) with new Beta Tutanota Client.

best regards 
Razzor

**Comment by mpfau** [comment]
Hi, the secret is Base32. 

This seems to be a problem with the Nitrokey app. Please try using another authenticator app or a yubikey.

**Comment by szszszsz** [comment]
Hi!
Regarding https://github.com/Nitrokey/nitrokey-app/issues/280: `foci mzle sxw2 oxnw bnvk digw ju` is not a valid base32. What format is it then?
cc @techge
