### ISSUE TITLE
Error report pop-up constantly

### ISSUE THREAD

**Issue by paint-rulz** [tutao/tutanota#1191]
**Bug in web app**

**Describe the bug**
Constant error report pop-up, when refresh page, and often when select an email. I've sent in a few reports, but the blank error report pop-up comes up again straight away. 
 
**To Reproduce**
_Steps to reproduce the behavior:_
Refresh page ... happens every time. 
Open an email ... happens often. 

**Expected behavior**
Not expecting error report pop-up all the time; unfortunately making Tutanota really unuseable. 

**Screenshots**
Copy/paste won't work on the error report pop-up, but this is the first paragraph.
![error detail](https://user-images.githubusercontent.com/35760727/54855728-70826800-4cef-11e9-8700-2aff4b9575e5.png)

**Desktop (please complete the following information):**
 - OS: latest Manjaro KDE (Stable), fully updated
 - Browser: latest Waterfox

**Comment by charlag** [comment]
Hi
The error is caused by the 3 things:
1. Waterfox not implementing Promises correctly (because old Gecko was not): https://github.com/MrAlex94/Waterfox/issues/857
2. Waterfox setting userAgent to Firefox 60 in one of the recent versions
3. Us expecting it to not do this two things

We have a workaround for Waterfox and Palemoon but we need to know that it's Waterfox and not Firefox.
Setting your userAgent to Waterfox should help.
Otherwise I recommend to not use it at least for security reasons, I think it's clear that it's impossible to keep up with all the things for such a small browser team.

**Comment by paint-rulz** [comment]
Thank you very much charlag for responding and especially for updating this issue on Waterfox's github. Not sure how to change userAgent, but looking it up.

**Comment by charlag** [comment]
The problem may be silenced with our next search update. Maybe we should just enable our fix for all Firefox 60, real and not.

25 Mar 2019, 11:26 by notifications@github.com:

**Comment by paint-rulz** [comment]
Thanks again charlag ... that sounds great!

**Comment by linuxgirl22** [comment]
Hi again :-) I've just got to checking in about:config, and can see this, but the settings are different to what I expected. 

![different overrides](https://user-images.githubusercontent.com/35760727/55244466-27736c00-5239-11e9-9dff-00ceac367159.png)

**Comment by linuxgirl22** [comment]
I've changed each Firefox word to Waterfox, in the 5 strings, but the error is still happening.

**Comment by charlag** [comment]
We will enable our workaround for all clients which claim that they're Firefox 60. I don't feel good about possibly breaking Firefox ESR just because of the Waterfox mimicking other browsers but I don't see any other way yet.

**Comment by charlag** [comment]
If you can install add-on which can override userAgent for Tutanota it would also fix that.

**Comment by linuxgirl22** [comment]
Thank you very much for responses. :-) Tbh I'm a bit out of my depth. I looked for an add-on, but the only one that seemed okay didn't have a Waterfox option.

**Comment by linuxgirl22** [comment]
A huge thank you; the error isn't happening anymore. Really appreciate your work. :-)
