### ISSUE TITLE
Push notifications reappear infinitely

### ISSUE THREAD

**Issue by malhonen** [tutao/tutanota#1205]
**Bug in web app**

**Describe the bug**
Today, I opened my email using the web client on Chrome and found I have 6 new, unread emails. Chrome showed me 3 identical notifications saying "You have new email". I tried closing them by pressing the X button of the notification window but every time I closed one, a new one appeared in its place immediately. I tried this over 20 times but the notifications would just not go away, and they would stay visible on top of other windows, as well, which was annoying. Finally, I was able to make them disappear by opening all the unread messages in the web client, at which point there were no unread emails left so no reason for notifications.

**To Reproduce**
1. Send yourself several emails from another address.
2. Open Tutanota web client.
3. Try to close the notifications appearing on the screen.

**Expected behavior**
The notifications should disappear and not reappear as you close them.

**Screenshots**
See the attached screenshot for the notifications. I have blurred out my name and email address but otherwise the screen is as it looked like after having already opened two unread messages (now there were 4 left).

**Web client**
 - OS: Windows 8.1
 - Browser Chrome 73.0.3683.86(64 bits)
 - Tutanota App Version 3.48.6
![Tutanota repeated new message](https://user-images.githubusercontent.com/13416974/55567510-541dfc80-56ed-11e9-9199-251aff04e39e.PNG)

**Comment by charlag** [comment]
Hey
I believe that they don't just reappear. Are you sure that it's not just many notifications?
We don't really test on Windows 8 because mainstream support for it ended on January 9, 2018. It might be an older Windows thing but we for sure don't reopen notifications.

**Comment by malhonen** [comment]
Well, I counted 20+ notifications before I stopped counting, so even if it was just many notifications, it was way too many for 6 new emails...

**Comment by charlag** [comment]
@malhonen if it happened only once or only happens on Windows 8 I would close it

**Comment by ganthern** [comment]
Also happens on MacOS.

**Comment by charlag** [comment]
Seems to be fixed now

**Comment by armhub** [comment]
Occurred again in version 3.52.1 on
* Firefox on Windows 10
* Tutanota desktop on Mac OS X 10_13_6

**Comment by armhub** [comment]
Reported by multiple users already for Tutanota Desktop on Mac

**Comment by ganthern** [comment]
It looks like a problem with the updater, so manually downloading and installing the newest version of the client should fix this temporarily (meaning until there's a new version it fails to download).

**Comment by armhub** [comment]
It also occurs in the current version.
After re-install the problem occurs again when emails are started to get received.

**Comment by armhub** [comment]
Moved the Firefox issue to #1371, therefore closing this one.
