### ISSUE TITLE
Rules not processed if in spam whitelist

### ISSUE THREAD

**Issue by snaggen** [tutao/tutanota#1223]
I have a alias for shopping related things,  and that adress recieves a lot of spam like mails. I then filter my mail so that all these mails are moved to a special shopping folder. One sender had their mails marked as spam, so I went in to the settings and whitelisted this sender since I still want the mails. Now, the mails are no longer sent to the shopping folder, but stays in the inbox.

**Comment by charlag** [comment]
Hi, thanks for the report.
Can we clarify please, does it mean that you've added a spam rule for the recipient and now inbox rule does not work? We know that inbox rules don't overlay so I'm just trying to be sure

**Comment by snaggen** [comment]
I first had no spam related rules
I have rules that say if mail adress is my_shopping_alias@tutanota.com then move to "shopping".
With this setup mails to my_shopping_alias@tutanota.com was moved to "shopping", all is fine.

I then got a mail to the my_shopping_alias@tutanota.com adress, sent by and adress, lets say news@internet_retailer.com, that was detected as spam by some default logic, and ended up in the folder "spam". This is fine to, since the mails from that adress is very simmilar to spam, and I just happens to be interested in their products and still want them. 

I then opened the Settings and added a spam rule and defined mail from internet_retailer.com as "Not Spam". 
So now, these mails are not marked as spam any more, success! However, mails from internet_retailer.com to my my_shopping_alias@tutanota.com is not sorted to my "shopping" folder any more, so they end up in my Inbox.
All other mail to my_shopping_alias@tutanota.com is sorted as expected.

So, my guess is that after a mail have a matching spam rule, no filter rules are processed. The expectation is that the spam rules are handled first and separately from the filter rules.

**Comment by charlag** [comment]
Thanks a lot for the elaborate explanation!
That's really weird because spam rules are processed on the server and inbox rules are processed on the client and they shouldn't interfere with each other. We'll check that.

**Comment by snaggen** [comment]
I notice that I have another adress in my spam whitelist where the mails are sorted correctly, however these mails are not equally spam looking so they might not be detected as spam in the first place. So how do the spam whitelist work? Is that on the client or server side? 

New theory, is that mails marked as spam on the server are not sorted in the client, even if they are in the whitelist.

**Comment by charlag** [comment]
Spam rules (and thus whitelisting) are on the server side. We'll check it a little bit later.

**Comment by snaggen** [comment]
Wait.... it might not be spam related at all... I started to examine the mail to see if there are alternative explanations and found that the mails that are not sorted are sent with my adress as bcc. So maybe the real issue is that the Recipient inbox rules are not checked against the BCC field.

**Comment by snaggen** [comment]
Ok, if that is the case I realize the issue is between the chair and the keyboard... I'll investigate on my side and then possibly siltently deletes this issue and pretend it have never happened.

**Comment by charlag** [comment]
Hey, no problem, maybe we should change something to process bcc. Glad to know that the reason is not the spam rules.

**Comment by snaggen** [comment]
Ok, it was my rules that were wrong. In my mind I assumed that the rule To recipient would include CC and BCC, so that I guess could be a usablility improvement. I would suggest something like
"Recipient" (which gets expanded to TO, CC and BCC) 

Then possibly separate possible rules for more fine grained control, for power users. 
"Field To"
"Field CC"
"Field BCC" 

Anyway, closing this thicket since things are working as designed.... and there are no problems with the spam rules, so that is good to know I guess :)
