### ISSUE TITLE
Contributor's guidelines.

### ISSUE THREAD

**Issue by HarryHeights** [tutao/tutanota#1228]
I checked out the community menu. I saw that contributor's guidelines hasn't been done yet. I'd love to help out.

**Comment by charlag** [comment]
Hey!
Indeed, that's one thing missing. We have a HACKING document with some technical things but I guess you have something different in mind. Mind sharing you ideas what should go there?

**Comment by HarryHeights** [comment]
This is a [contributor's guidelines](https://github.com/iamSahdeep/Bop/blob/master/Contributing.md) I wrote for a project. You can check it out and tell me what you think. If it's something like that you seek.

**Comment by charlag** [comment]
Thanks for the example, I checked it out. Unfortunately to tell you how it should look like would be almost the same as writing it ourselves (we don't accept feature requests here e.g., we have special handling of libraries, formatting style is not described by us yet etc etc).
Thanks for the suggestion though, we should revisit this topic in some time.

**Comment by HarryHeights** [comment]
Oh! Alright. No problem.
