### ISSUE TITLE
When selecting multiple messages, previous message opened is always included

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1229]
**Bug in mobile app**

When selecting multiple messages, the previous message that I opened is always included (because it's already highlighted).

**Describe the bug**
I'm not sure this is a bug, but it keeps being an annoying problem for me. Maybe I'm doing something wrong? When I long-press a message header to begin selecting multiple messages for deletion, the previous message I opened is included in the selection queue. I understand that's because it's already highlighted.

**To Reproduce**
1. Open a message, then hit back to go back to your inbox list.
2. Long press a message header (one that's different from the email you opened previously). Now there are 2 items in the selection queue.

1. Open a message
2. Minimize tutanota
3. Maximize tutanota.
4. Hit back to go back to your inbox list.
5. Long press a message header (one that's different from the email you opened previously). Now there are 2 items in the selection queue

**Expected behavior**
The first message added to the selection queue should be the first message that is long-pressed.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J7
 - OS: Android
 - Version 8.1.0

When this happens I hit the "x" at the top to clear the selection queue and start from the beginning.

**Comment by charlag** [comment]
Hi!
Thanks for the writeup. That's how it was intended (more or less - might be accidental and we internalized it). Maybe we should reconsider that, because it doesn't make sense to select the message you just visited.

**Comment by andy5995** [comment]
Thanks!
