### ISSUE TITLE
Is Tutanota down? 

### ISSUE THREAD

**Issue by TobiasDev** [tutao/tutanota#1238]
I've been trying to log into my mail since 7 am this morning, but it keeps saying I'm offline (on my phone), and trying to access the website doesn't even load at the moment. 

Sorry for making a Github issue, but it was the only account I had to contact you. :D

**Comment by charlag** [comment]
It is certainly up. Please check your network. I am able to connect from both mobile and other networks.
Please let us know if you find out something.

**Comment by TobiasDev** [comment]
Hmm, weird. Because everything else works for me, downloading apps, watching netflix, surfing. Hmm, okay, I will look more into this! Thanks for the answer.

**Comment by charlag** [comment]
If you're on VPN, try it out without VPN. You could also check incognito mode in the browser.

**Comment by TobiasDev** [comment]
I'm not on VPN, and I've tried it both on my PC and my phone (with and without Wifi). :( Neither works, so not sure what this is about.

**Comment by TobiasDev** [comment]
"
The connection has timed out

The server at tutanota.com is taking too long to respond.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.
"

I get that it is taking too long to respond. I'm quite confused. This is even when I try just visit tutanota.com. I'm in Germany if that matters to this.

**Comment by charlag** [comment]
This is really weird. Website is on the the same server but if you're in Germany it makes absolutely no sense.
Can you try to ping/traceroute tutanota.com from the command line? I'm really puzzled. Could be something about our hosting.
If you don't want to publish results here please send them to hello@tutao.de and let us know (e.g. here).
Thanks a lot and sorry for whatever is happening there.

**Comment by TobiasDev** [comment]
Okay, sent the email now. Sadly from my gmail (that I'm not really using any longer, but didn't find another way.) :)

**Comment by TobiasDev** [comment]
Okay, seems to be back now! At least it started working for me again. :)

**Comment by mpfau** [comment]
The cause was a routing issue at unitymedia.
