### ISSUE TITLE
Client crashes when logging out on Linux

### ISSUE THREAD

**Issue by pmatarodrigues** [tutao/tutanota#1249]
When executing the **.AppImage** on Linux through the command ./tutanota-desktop-linux.AppImage, the Desktop App is running on the terminal.
After logging out, the client goes all white. When opening the client again, the app still shows the white screen, not being able to do nothing.

**Steps to reproduce the behavior**
1. Download the desktop version for Linux (.AppImage)
2. Open terminal on the correct directory
3. Change permissions to execute (chmod +x tutanota-desktop-linux.AppImage)
4. Execute the app (./tutanota-desktop-linux.AppImage)
5. When logged in, select the logout option.

**Expected behavior**
Tutanota desktop app should simply show the normal login page.

**Screenshots**
Everything is fine until **Logout is clicked**
![Logout menu](https://i.imgur.com/AZ4c3vO.png)
After that, the screen goes all white.
![White page](https://i.imgur.com/0cWAIA6.png)

**Desktop**
 - OS: Linux (Manjaro)
 - Using Cinnamon

**Comment by charlag** [comment]
Hey, thanks for reporting
I encounter it from time to time and F5 helps in such situations. Looks like a bug in Chromium/Electron to be.
Would you mind opening devtools (F12) and check "console" tab for any errors when such an error occurs?
Thanks

**Comment by pmatarodrigues** [comment]
If found out that the error only occurs when opening a second window.
I mean, when I boot the computer and open the client for the first time, there's no error.
If I close the client window, and reopen it or select "New Window", the error occurs.

When the error occurs, the console shows only this error:
**Not allowed to load local resource: file:///tmp/.mount_tutanoS7SZfZ/resources/app.asar/desktop.html/login?noAutoLogin=true**

**Comment by charlag** [comment]
Thanks, seems like it's the same error. We'll look into that.
