### ISSUE TITLE
Flatpak: notificatations are not displayed

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1255]
**Describe the bug**
When running in Flatpak sandbox, no notifications are displayed. It seems like the client receives them (at least it sends confirmation).

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Desktop Environment: Gnome 3.22

Related info:
Sanbox permissions: http://docs.flatpak.org/en/latest/sandbox-permissions-reference.html
Desktop integration: http://docs.flatpak.org/en/latest/desktop-integration.html
Notification portal: http://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Notification

**Comment by x80486** [comment]
I think this should be resolvable just by adding `--talk-name=org.freedesktop.Notifications` to the manifest.

**Comment by charlag** [comment]
It is fixed for some time in flatpak repo
