### ISSUE TITLE
Flatpak: no tray icon

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1256]
Docs mention "status icon":
http://docs.flatpak.org/en/latest/desktop-integration.html#window-decorations

>Status icons are the same concept as the system tray or the taskbar on Windows, or menu bar icons on Mac. These are supported on most Linux distributions, through libappindicator.
>
>A number of Linux distributions don’t show status icons. It is still possible to provide a status icon, and it will be shown in some distributions. However, in order to ensure compatibility, it is recommended to only use status icons in a supplementary manner, and not to rely on them as the only mechanism for providing status information or access to particular features. This includes “minimize to tray” (or equivalent) functionality.

**Comment by snaggen** [comment]
The Skype flatpak (is an electron app)  have working tray icon, if you want a referens project to look at.
