### ISSUE TITLE
Desktop client: Improvements for find in page

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1262]
Proposals to make the find functionality similar to the one in the browser:
* When pressing Ctrl+F always put the cursor into the find field, even if the field is already visible.
* Show the number of found results in the find bar
* Jump to the next found item when pressing <enter> in the find field.

**Comment by ganthern** [comment]
the continue-search-on-enter functionality proves difficult and is still not implemented. issue:  #1280
