### ISSUE TITLE
When rotating to landscape mode the swipe delete action appears in list view

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1263]
Whe rotating the device to landscape mode the delete action of the first row item magically appears. If you switch to normal orientation again the action disappears on iPhone but on iPad the action is still visible.
![Image-1](https://user-images.githubusercontent.com/8296817/57282422-4fae8000-70ad-11e9-9df5-32d7904d16a6.jpg)

**Comment by x80486** [comment]
I was about to create an issue for this one :smirk:

This should be tagged (or title changed) accordingly; I can confirm it also happens on Android :sunglasses:

**Comment by Raklyon** [comment]
Also when sliding one of the message, the delete action "jumps" to the sliding one : put the phone in landscape mode, notice the delete action appear on the first mail, slide the second mail (as if to archive or delete this mail), watch the delete action appear on this mail and disappear on the first one.
Moreover, the delete zone is non-responsive (when pressing it, the mail does not open, however, when pressing the usual display of the mail it opens correctly).
