### ISSUE TITLE
Delivery status notification and read notification

### ISSUE THREAD

**Issue by samip5** [tutao/tutanota#1268]
The email client is missing one of the important aspects of modern email.

The ability to request delivery status notification, and/or read notification when sending the email.
Why is it missing from the form when writing a new email?

**Comment by charlag** [comment]
Hey.
As stated in the issue template, we don't accept feature requests here right now.
We don't track when the email is read.
If we cannot deliver an email, we sent a bounce email to you.
Until very recently all sending was synchronous and only now it became asynchronous.
We will evaluate this suggestion in the future.
