### ISSUE TITLE
Attachments can't be downloaded in Pale Moon browser

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#128]
Anlagen lassen sich übrigens mit aktuellem Browser Pale Moon nicht runterladen. Die Ladeanzeige erscheint und verschwindet. Download  bleibt aus.

**Comment by mpfau** [comment]
Probably related to #112.

**Comment by armhub** [comment]
pdf attachments do not open or download. There is the familiar "please wait" message which then disappears, and then nothing. Pale Moon 27.5.0 32 bit and Windows 7

Can reproduce this behaviour on with Pale Moon 27 on Window 10

Also occured on FireFox ESR 45.9.0.

**Comment by bedhub** [comment]
When I attempt to download attachments on the new app, files do not download. The 'please wait' modal appears and then disappears, without the file downloading. I have to use the old app (app.tutanota.com) to download them. If the old app gets deprecated, I will not be able to access my files. 
I am using Firefox ESR 45.3.0 on an older version of Qubes.

**Comment by bedhub** [comment]
this problem does not occur with Pale Moon 28 anymore.
