### ISSUE TITLE
Complete wake up from hibernate mode takes about 8 mnutes

### ISSUE THREAD

**Issue by vladimiry** [tutao/tutanota#1281]
Browser: Chrome latest.

I get the computer from hibernate mode and see a few incoming emails in the list. I click them and they instantly get "read" status (no bold highlighting anymore). But the unread counter keeps showing the non-zero value for about 8 minutes.

I noticed that after about 7 minutes interface starts to show such offline indicator with no apparent reason (internet connection was ok):

![offline-indication](https://user-images.githubusercontent.com/1560781/58146744-1145c300-7c60-11e9-9942-00ad256e37e5.png)

And then after about 1 minute unread counter resets to 0 value and offline indication disappears. So the complete wake up takes about 8 minutes.

Might be related to https://github.com/tutao/tutanota/issues/1121 issue.

**Comment by charlag** [comment]
Hi, thanks for reporting.
I think it might be somehow related to the fact that we are not notified about the network status until something times out and then we reconnect in about one minute.
If you have logs or some other info to share, we would appreciate that.

**Comment by vladimiry** [comment]
> we are not notified about the network status

I see there is listening for `online` event setup but I guess there may be an issue with the logic of processing this event https://github.com/tutao/tutanota/blob/7dc70d54badc906cf277e1b0d9b4bc2ce654205b/src/misc/WindowFacade.js#L136

Alternatively, if you think that event was not triggered I'd suggest considering setting up something like online status ping stream, like reading the `window.navigator.onLine` value every second or few and then triggering some action if the `onLine` value got changed.

**Comment by charlag** [comment]
I think we have even hybernation detection with setTimeout but I would need to check that.
You can also add a listener in JS console to check if you receive events or not. Maybe you could also explain what is a logic failure there?

**Comment by charlag** [comment]
This should not be the case anymore as we completely changed mechanisms of reconnection.
