### ISSUE TITLE
Same contact is shown twice in mail editor

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1283]
Example contact
Firstname: Doubletest
email address: test@double.com

Search for "doub"

**Comment by x80486** [comment]
...was about to file an issue for this one; pretty annoying this one I would say :rofl:

**Comment by vitoreiji** [comment]
Could not reproduce, probably solved along with some other fix.

**Comment by charlag** [comment]
It's not solved but it's sporadic

**Comment by brshub** [comment]
Cannot reproduce in desktop version 3.84.11.

**Comment by kibhub** [comment]
@charlag I think this issue could be closed.
It looks like partial matching has changed as well, since the original example does not give any search results.

**Comment by wrdhub** [comment]
It looks like this issue has been solved.
