### ISSUE TITLE
[Android] App is using improper LED notification color

### ISSUE THREAD

**Issue by hatch8889** [tutao/tutanota#1287]
Android app lights up notification in RED color, which improperly indicates that something is wrong (e.g. empty battery)

It would be preferable to use a more appropriate color - green, blue or white as do other mail applications.

 - Device: OnePlus 3
 - OS: Android 8.0.0
 - Version OxygenOS 5.0.8

**Comment by charlag** [comment]
Hey
This is a valid feature request and was voices before but we don't accept feature requests here, unfortunately, otherwise it's unmanageable.
Let's discuss it elsewhere. Maybe open a discussion on Reddit on what color people would prefer?
Thanks.
