### ISSUE TITLE
LET ME DOWNLOAD ALL MY EMAIL

### ISSUE THREAD

**Issue by PowerOlive** [tutao/tutanota#1288]
it is opensource?
i can not download all my email?
how?
i can view 100 per move and use my mouse to dowload all the email one by one by hand?
so tutanota do not support imap and pop3 with ssl support and opengpg support?
only for lock down user from 1 eu every user every month?
TUTAO

**Comment by PowerOlive** [comment]
ok they do not want me to move my email...

**Comment by PowerOlive** [comment]
so that they can get 0 eu

**Comment by PowerOlive** [comment]
https://www.google.com/search?q=tutanota+download+emails

**Comment by charlag** [comment]
You can select many emails with shift key and export them all at once. We plan to improve this but encryption makes it harder do download them all at once.

**Comment by PowerOlive** [comment]
it is a german company
and it do not support
GDPR

**Comment by PowerOlive** [comment]
what GDPR you

**Comment by PowerOlive** [comment]
...it sound like german is not in european
