### ISSUE TITLE
does tutanota support gdpr that allow users to download all my data and decrypt myself?

### ISSUE THREAD

**Issue by PowerOlive** [tutao/tutanota#1289]
GDPR
https://en.wikipedia.org/wiki/General_Data_Protection_Regulation
you may know

**Comment by PowerOlive** [comment]
what you are
using github supports
export data right

**Comment by PowerOlive** [comment]
say no tutao
to report tutao
then they allow

**Comment by mpfau** [comment]
You can contact us at hello@tutao.de if you want us to export your personal data.
