### ISSUE TITLE
Respect prefers-color-scheme

### ISSUE THREAD

**Issue by lionirdeadman** [tutao/tutanota#1290]
**Bug in web app**
It doesn't respect `prefers-color-scheme:dark` using the site's dark theme

**To Reproduce**
1. Set browser to dark color scheme
2. Go on website
3. Website uses white theme instead of dark theme

**Expected behavior**
The website uses dark theme when prefers-color-scheme:dark is provided

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser : Firefox
 - Version : 69.0a1

**Additional context**

These links might be useful to implementation :
- https://caniuse.com/#feat=prefers-color-scheme
- https://stuffandnonsense.co.uk/blog/redesigning-your-product-and-website-for-dark-mode
- https://paulmillr.com/posts/using-dark-mode-in-css/

**Comment by charlag** [comment]
Hi
Thanks for the report.
It is more of a feature request and I think browser support is not quite there yet (1.51%). It is a nice thing for someone's pull request. I'll close it for now until we have plans to implement that and will reopen it once its confirmed. Thanks for understanding.
