### ISSUE TITLE
Add archive (or custom move) button

### ISSUE THREAD

**Issue by avrelaun** [tutao/tutanota#1291]
Feature request: Add some "Archive" button to quickly Archive an email, like the Trash button is a shortcut to Move -> Trash.

Even better, provide a way for the user to add custom buttons to quickly move emails to custom folders. This would help implement several zero inbox techniques.

**Comment by avrelaun** [comment]
Sorry, I just saw this was not the place to propose feature requests. You can close this if necessary.

**Comment by charlag** [comment]
No problem, thanks for understanding. On mobile it's available as a gesture but on desktop it's not so simple. We try to keep UI as simple as possible but maybe we should think about improving actions in this regards, thanks for the feedback.
