### ISSUE TITLE
Antivirus does not scan inside zip attachments

### ISSUE THREAD

**Issue by sunny75016** [tutao/tutanota#1293]
When the virus is inside a zip file (which has no password) attached to an incoming email (not encrypted); the Tutanota server does not scan for the virus inside the zip file. This is a significant security risk for a service that claims to be the world's most secure. Please replace your Antivirus or change its configuration. 

- [x] This is not a feature request. I will request features on the forum or via support (see [contact page](https://tutanota.com/contact?page=feature)).
- [x] This issue doesn't fit into provided templates.

**Comment by charlag** [comment]
Hey
I want to point out that, in fact, we don't do any virus scanning. We cannot technically do this for confidential emails and even for non-confidential ones we prefer to not look into them.
Please make sure you don't mistake it for your own antivirus.
