### ISSUE TITLE
App is not compatible with iOS 13

### ISSUE THREAD

**Issue by rex4539** [tutao/tutanota#1297]
**Bug in mobile app**

**Describe the bug**
When the app is launched, the login screen appears for a split second and then the screen goes white.

**To Reproduce**
Launch the app on iOS 13.

**Expected behavior**
App is launched and works as expected.

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13
 - Version 17A5508m

**Comment by iJorgen** [comment]
Hope this issue will be fixed quick... Was going to switch to Tutanota when DKIM/DMARC for Custom Domain is released this week, but now this bug is stopping me ;-)

**Comment by charlag** [comment]
We'll definitely look into it soon but... which beta is this now? Beta 1? They're unusable until August usually

**Comment by rex4539** [comment]
It’s Beta 2 currently.

**Comment by jtb1234** [comment]
I have the same issue. iOS 13 Public Beta 1

**Comment by iJorgen** [comment]
Good news! After installing iOS13/iPadOS13 Public Beta 2 the app now works again for me.

**Comment by rex4539** [comment]
Same here.
