### ISSUE TITLE
Forwarding mail removes embedded image when plain text is enabled

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1299]
- Enable plain text mode in Settings->Email->Formatting
- Forward an email containing an embedded image

**Comment by vitoreiji** [comment]
Should the image be attached or should the mail be sent as HTML?

**Comment by krvermeulen** [comment]
To add to this: this also goes for attachments like PDFs. They are removed from the email when forwarded while the setting is on Plain text. This is not at all visible in the email compose dialogue. In Sent items the email is also shown with the attachment.

**Comment by codingepaduli** [comment]
I've experienced the same issue.

Forwarding an email with PDF attachments, they are removed from the email sent, even if I can see them in the graphical interface.

I think this bug is very severe because it impacts the basic usage of the service.

**Comment by kotelnik** [comment]
I'm also hit by this issue. Forwarding an e-mail with attachments ends up sending it without them. Interestingly Sent folder contains the sent e-mail **with** the attachments which is even more confusing.

Workaround:
1. Click the forward button
2. Save all attachments locally (to disk)
3. Remove all attachments from this mail
4. Attach them back from the disk
5. Send

But it's tedious :)

**Comment by brshub** [comment]
Testing this issue in v3.95.4 and the embedded images are forwarded (and displayed) correctly.
