### ISSUE TITLE
Small add to instructions for building locally

### ISSUE THREAD

**Issue by itoffshore** [tutao/tutanota#13]
Add to the instructions for running the client locally:

```
4.1:         [sudo] npm install -g gulp
4.2:         npm install gulp --save-dev
```

1.9.1 works very well running locally inside an Alpine Linux LXC container under Debian.

**Comment by armhub** [comment]
We close the issue tracker on gibhub because the official issue tracker is here and we do not want to handle two trackers: https://tutanota.uservoice.com/forums/237921-general
If your issue is not listed there, please add it. Thanks!
