### ISSUE TITLE
Default sender not always respected when replying/forwarding emails

### ISSUE THREAD

**Issue by trinitrotoluene** [tutao/tutanota#1301]
This was originally raised in #756 but isn't fixed/regressed in the latest client version.

**Describe the bug**
When receiving an email where the recipient is set to an address that is not **any** of the registered aliases of the inbox, the default sender address is not respected when using reply/forward.

**To Reproduce**
1. Receive a forwarded email (e.g. from GMail)
2. Recipient will be *@gmail.com
3. Ensure your default sender is set to something different from your \<username\>@tutanota.com address.
4. Reply or forward the email.
5. Sender will be \<username\>@tutanota.com, not the email you set as default.

**Expected behavior**
If the recipient of an email is not one of your aliases, replying or forwarding it should respect your default sender preferences.

**Desktop (please complete the following information):**
 - OS: `Windows 10 1903`
 - Client Ver: `v3.52.1`

**Comment by snaggen** [comment]
If you forward a mail from gmail to tutanota, you forward it to a specific e-mail adress like a@tuta.io . I would then expect that adressbook to be used as a the sender adress and not the default. 
This sounds like a very different thing than what is described in the bug you linked.

**Comment by trinitrotoluene** [comment]
You're completely right. My mistake!
