### ISSUE TITLE
Support mail link is dysfunctional

### ISSUE THREAD

**Issue by trentks** [tutao/tutanota#1317]
Same issue as #1111 which has been closed, but I would like to reopen it.

**Comment by charlag** [comment]
Hi
Could you provide some details? Because I checked and it works for me

**Comment by trentks** [comment]
Hi @charlag 

Clicking the target link https://mail.tutanota.com?action=supportMail from https://tutanota.com/contact page gets me to log into the webmail, but then does not result in any kind of email writing to support, or anything out of the ordinary. It's a dead-end.

**Comment by charlag** [comment]
Thank you. Now could you please specify your browser & OS version? Tutanota version would also be good (you can see it in settings).
I assume that you're a premium customer as mentioned in #1111.

**Comment by trentks** [comment]
**Desktop:**

OS: Manjaro 18.0.4, i3 community edition
Browser: Firefox Quantum
Version: 67.0.4 (64-bit)
Tutanota version: 3.52.1

I'm also using 2FA, so clicking the link requires a sign-on followed by a 2FA TOTP auth, then I'm just presented with my mail box and nothing relating to support.

**Comment by trentks** [comment]
Just "refreshed" to 3.55.2 and the  issue persists.

**Comment by trentks** [comment]
Also, my email is on my own domain, if that makes a difference.

**Comment by charlag** [comment]
Thanks. Just tried with two accounts and it works for one of them while doesn't work for another one. We'll look into that.

**Comment by charlag** [comment]
Oh, I'm not the admin of one of them, that might be the reason.

**Comment by charlag** [comment]
Checked multiple times in Firefox, for all premium accounts where user is customer admin it works. Please make sure that you're logging in into your administrator account and not into one of the users created by you.

**Comment by trentks** [comment]
Hi @charlag, thanks for your help

My 'administrator account'... would that be my @tutanota.com account? 

I never did fully understand why I have to have an @tutanota.com account as I won't use it. I just need my personal email domain account, and that should be the primary 'administrator account', is there a way that I can set it so?

In any case, seems a little silly that I should have to use my @tutanota.com account to get support for my @personal.domain account. What if I had myself and another, or a hundred other, people under my @personal.domain accounts---would I have to lodge all support queries to you guys on behalf of, or give out the 'administrator account' credentials to all so that they could get support?

**Comment by trentks** [comment]
I see, I can make my @personal.domain account an administrator by logging into my @tutanota.com account.

I can then unadmin the @tutanota.com account, and 'deactivate' it, it is at this stage that I realise that I've  bought "2 subscriptions", even though I've only been billed for 1---one for my @personal.domain account and one for my @tutanota.com account. It shows I'll be billed 24 euro through to June 2020, then (now) 12 euro after that as I've deactivated the @tutanota.com account. I have of course only been billed 12 euro, so I don't know why it's saying 24 euro. But this is another matter. 

The real issue is that for people to get support, they have to be administrators? Seems like an oversight, no? At the very least it should say that you have to be not only a premium customer, but also be using an administrator account to receive support on the contact webpage.

Thanks for your help again @charlag. My real issue is #1316 of course, but this is probably specific to my account so I'll contact via support email.

Cheers.

**Comment by charlag** [comment]
Glad I could help. It was confusing indeed, maybe it's a bug, I will check details tomorrow

**Comment by charlag** [comment]
@trentks sorry for not reaching back, it completely fell out of my attention. Does this issue still affect you significantly? I think it's not unreasonable that admin should contact us for the payment/account management matters.

**Comment by armhub** [comment]
Seems to be fine this way.
