### ISSUE TITLE
Division in 3 panes -> 2

### ISSUE THREAD

**Issue by ivanperez-keera** [tutao/tutanota#1318]
**Describe the bug**
Currently, the web app is divided in 3 vertical panes: folders/tags, emails, and email content. This takes additional space and adds noise to an already crowded experience.

**To Reproduce**
1. Go to 'https://mail.tutanota.com/mail/'
2. See issue

**Expected behavior**
A way to configure seeing the main email in 2 panes (folders + email content).

**Screenshots**

Current interface:
![Screenshot from 2019-07-08 08-45-26](https://user-images.githubusercontent.com/1162320/60811450-4731fe80-a15d-11e9-97c7-620c7e71a855.png)

Better interface:
![Screenshot from 2019-07-08 08-48-51](https://user-images.githubusercontent.com/1162320/60811451-4731fe80-a15d-11e9-8061-83632ccb5e72.png)

**Desktop (please complete the following information):**
 - OS: Web, Ubuntu 18.04
 - Browser: firefox
 - Version: 67.0.4

**Comment by charlag** [comment]
Hi
I want to mention that we don't accept feature requests here to not overflow bugtracker.
In any case, how would you navigate between mail list and mail viewer then?

**Comment by ivanperez-keera** [comment]
Thanks! Noted.

Since you asked:

Back button/icon (not the browser's).

Both gmail and protonmail move the action bar above the email title, so it makes sense that it be the first icon in that toolbar. In your case, these are the little circular buttons to the very right, and it makes sense to have them there when you are dealing with just one email, but not so much when you select more than one email.

mailbox.org (open-xchange under the hood) implements a separate toolbar under the action toolbar, which semantically makes some sense (but not completely), but takes unnecessary space.

Outlook uses the browser's back button and it's really annoying.

I'd recommend the first option.
