### ISSUE TITLE
Calendar time does not accept not leading zero hour

### ISSUE THREAD

**Issue by nikolayhg** [tutao/tutanota#1319]
**Describe the bug**
If one enters a not leading zero time for a calendar event, e.g. "9:45", then "Invalid time format" is shown.

**To Reproduce**
1. Go to 'Calendar' and add an event
2. Set time of "from" to '9:45' and click "Ok"
4. See error "Invalid time format"

**Expected behavior**
The not leading zero time "9:45" should be accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/14300004/60824112-b1748e80-a1b1-11e9-8f37-b46898099ee2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Desktop Environment: GNOME
 - Tutanota: 3.55.2

**Comment by charlag** [comment]
Hi, thanks for reporting!
Time picker needs a lot of love for sure
