### ISSUE TITLE
Improve time picker

### ISSUE THREAD

**Issue by dantuck** [tutao/tutanota#1324]
**Improvement for all Apps**
Currently all time selection in all apps do not use native time picking but instead shows clear text time.

**To Reproduce**
1. Click to add a new Calender event.
2. Select time input

**Expected behavior**
Use of native time selection. I would suggest using [`<input type="time">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time).

**Screenshots**

![image](https://user-images.githubusercontent.com/473408/60893548-5462f200-a21e-11e9-8065-82b46fb21d24.png)

**Comment by charlag** [comment]
There are argument for and against it. Situation is roughly the same as with date picker.
Native pickers have an advantage of being accessible (I hope).
Unfortunately they look differently in all browsers and cannot be styled. They don't provide dropdown on desktop and don't work at all in Safari [(link)][1].

I would propose to build one on our own and instead and to not rely on browser.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by dantuck** [comment]
I completely understand the arguments against. As far as Safari looks like it will be available for iOS 5.0 and later [ref](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/InputTypes.html).

In regards to the styling I agree that without having the ability to style it there would be a UI consistency issue. What about the proposal to include usability first by using the input type of time and create an additional feature to implement a custom solution to replace the native solution?

**Comment by charlag** [comment]
Or worked on improved picker today and I should finish it soon. We can build something like "native" Android one later.

**Comment by charlag** [comment]
I admit that I was wrong about HTML time picker, it works really well on mobile and we can use it there

**Comment by dantuck** [comment]
That's great news. Glad it is going to work out well.
