### ISSUE TITLE
Support more than one reminder for calendar events

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1331]
As of now, calendar events only support one reminder. It would be great to have a way to place multiple reminders – possibly a fixed number.

> I know you just finished the calendar, but this is the never-ending story so I'm putting more stuff here :rofl:

---

By the way, I noticed there are no other templates in the issue tracker, except for bugs? Is that the intent?

**Comment by charlag** [comment]
This is intentional because we don't accept feature requests here. I will keep it because we wanted to do it anyway.
