### ISSUE TITLE
Calendar reminder at the time the event occurs

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1332]
It would be nice to be able to receive calendar notifications **at the time** the event occurs.

Right now there is nothing else in between `none` and `5 minutes`, I think we should be able to select something like: `0 minutes` or `at the time the event occurs` – or something between those lines :sweat_smile:

**Comment by curious-jim** [comment]
I'd like to see more advanced date/time selector for calendar reminders, not just a list of preselected values
some people need 0 minutes, I'd like to have 4 hours.
should I create another issue (didn't find any open issues about that)?

**Comment by charlag** [comment]
We will consider adding that

**Comment by carlo1601** [comment]
Hello, I agree with @curious-jim, also for me the custom time selector for the reminder is a nice-to-have feature for the calendar.
Thanks!

**Comment by vitoreiji** [comment]
Will be covered by #5712.
