### ISSUE TITLE
Chromium: Sometimes lists in email editor adds additional list item marker

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1335]
The first time after login you create a list in an email editor the typed list item marker (number or *) is kept.

1. Login in to Tutanota and open an email editor
2. Type either "1. " or "* "
-> An html list item marker is created and additionally the typed character is kept

Expected:
Only the list item marker is created

If you create lists afterwards it sometimes works fine, sometimes not.
Only tested in Chromium on Ubuntu.

**Comment by vitoreiji** [comment]
It happens when the line you're creating the list at has a nested `div`, like `<div><div></div></div>`. Looks like a bug in squire. I'll investigate more.

**Comment by vitoreiji** [comment]
As a workaround for now, you can remove all formatting from your signature, or at least from the first line.

**Comment by charlag** [comment]
We found out that it is not, in fact, bug in Squire, it's implemented in `Editor`

**Comment by charlag** [comment]
It works fine for me but I couldn't now reproduce it either (with lists in signature or without) so maybe @armhub can re-test this?

**Comment by armhub** [comment]
I have tested and it is fixed now.
