### ISSUE TITLE
Agenda view for the Calendar

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1337]

**Comment by armhub** [comment]
Event is shown on wrong day in the agenda:
1. Open clean calendar in monthly view
2. Click on tomorrow and create an event.
3. Open the agenda
-> The event is shown in "Today"

**Comment by armhub** [comment]
The agenda currently shows all currently loaded events which my be different depending on which months had been displayed already. We should instead either restrict it to a fixed number, a fixed time period or allow loading more events when scrolling the agenda.
