### ISSUE TITLE
Birthdays of contacts in calendar

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1352]
**AC**
- Each Tuta Contact should have an event at it's birth-date informing the user about their birthday
- If the contact has a complete date (dd-mm-yyyy) show their age at event title
- Birthday calendar should be read-only and permanent (can't be deleted)
- Feature will be available only for New Paid plans

### Test notes
- [ ] All accounts(no matter their subscription plan) have a new default Calendar called Birthdays with a default color (orange)
    - [ ] If it's a free or legacy plan acc, the calendar is disabled by default and show a upgrade wizard if interacted with.
    - [ ] If acc is a new paid plan, the calendar should be active by default.
- [ ] Calendar is read-only
- [ ] User can edit the calendar name and color
- [ ] Contacts birthday events are created every login and rendered every year

**Comment by BJMabbett** [comment]
Any events on a contact's card including birthdays, anniversaries, etc.

**Comment by gio-cefalu** [comment]
It would be nice to have a reminder for a person's birthday.  Maybe a global setting for showing notices for birthday 1 week in advance, 1 day in advance, or on the day of the birthday.  This is a "nice to have" feature but not critical.

**Comment by gimmie7** [comment]
So far this is the only feature I really miss in Tutanota. Would be great if it was implemented soon :)

**Comment by milesgillham** [comment]
Any update on timeline for this feature? As gimmie7 says it's a beloved feature and I believe it should be part of the core functionality.

**Comment by cwoehrer** [comment]
I miss the feature too, it would be very great if this is available soon. Unfortunately, it no longer appears at https://tutanota.com/de/roadmap/, but I still hope that this feature will be pursued.

**Comment by cwoehrer** [comment]
Is there any information on this when it will be implemented? It's been classified as small improvement for a very long time, would love to see this feature coming soon :)

**Comment by ZettaPloom** [comment]
Hope it get on roadmap again

**Comment by gerrix1701** [comment]
Hope this feature will be added soon. It's currently the only reason why I'm not using Tutanota's calendar so far...

**Comment by chrpinedo** [comment]
it would be great to have this feature!
