### ISSUE TITLE
Sending/receiving calendar invitations

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1355]

**Comment by BJMabbett** [comment]
Can these give options for both encrypted and non encrypted (i.e. to non Tutanota users) please?

**Comment by gio-cefalu** [comment]
Just curious on the update for this feature.  I'd also like to second the notion to have both encrypted (within Tutanota) and unencrypted (non-Tutanota users) calendar invites and acceptances, as BJMabbett suggested.

**Comment by charlag** [comment]
It was mostly working but had some roughy edges, there were more pressuring issues so far so it's unfinished. Prototype version simply used email as transmission medium so you get both encrypted and unencrypted invites.

**Comment by gio-cefalu** [comment]
Just checking for an update on this.  Any chance we can see calendar invites sometime soon?

**Comment by charlag** [comment]
Please don't ask here
We started testing it and we will release it this/next week

**Comment by charlag** [comment]
* We need to add EMAIL to attendees/organizer for interop
 * It is possible to add invite to rw shared calendar which should not be allowed, only personal calendars are allowed

**Comment by charlag** [comment]
Calendar event popup does not use `elevated_bg` as background. It's not critical but not nice for the dark theme

**Comment by charlag** [comment]
another issue with dark theme:

![Screenshot from 2020-08-10 11-35-20](https://user-images.githubusercontent.com/3099142/89769550-98998380-dafd-11ea-8551-21522f6a5223.png)

**Comment by armhub** [comment]
I spradically get LockedErrors in an error dialog when the invited user receives the invitation:
`
error LockedErrorname: "LockedError"message: "423: MEMtcwt----0 | DELETE /rest/tutanota/calendareventupdate/MEMibmj----0/MEMtcjK--R-0"data: undefinedstack: "LockedError: 423: MEMtcwt----0 | DELETE /rest/tutanota/calendareventupdate/MEMibmj----0/MEMtcjK--R-0↵    at https://test.tutanota.com/common.js:1:250827↵    at XMLHttpRequest.xhr.onload (https://test.tutanota.com/worker.js:1:664744)"isOperational: true__proto__: TutanotaError
`

**Comment by vitoreiji** [comment]
If the organizer gets a reply while they have the event dialog open, is not updated. If organizer then saves, the old attendance status will be saved (and possibly sent out to invitees if organizer chooses to send updates).

**Comment by vitoreiji** [comment]
External invitees cannot change their minds about replies to confidential invitations.

**Comment by armhub** [comment]
Calendar event is not updated at recipient:
1. Send invitation to one recipient for event 17:00-17:30.
2. Change event time to 17:00-19:00 and send updates. Recipients gets another invitation.
3. Accept initial invitation by recipient -> the event in the calendar shows 17:00-17:30
4. Accept the second invitation by recipient -> the event in the calendar still shows 17:00-17:30

**Comment by vitoreiji** [comment]
I cannot reply to invitations from external users. I can save the event to my calendar but I cannot send my attendance status to the organizer.

**Comment by charlag** [comment]
Empty password leads to an error when inviting

Also approval status check is not handled

**Comment by charlag** [comment]
Auto-sizing does not work when there's not enough space

![error-event](https://user-images.githubusercontent.com/3099142/89791282-61d66400-db23-11ea-980a-daf06a3c885e.png)

**Comment by mpfau** [comment]
see #2196

**Comment by vaf-hub** [comment]
I cannot remove the event from calendar, if I am the only guest

**Comment by armhub** [comment]
Re-testing accepting invites with a changed event date:

* Send invitation to one recipient for event 17:00-17:30.
* Change event time to 17:00-19:00 and send updates. Recipient get another invitation.
* Accept initial invitation by recipient -> the event in the calendar shows 17:00-17:30
* Accept the second invitation by recipient -> BadRequestError

**Comment by vaf-hub** [comment]
Another bug:
1. Create an event and invite a tutanota user as guest. Save.
2. Edit event and add an external guest. Save.
3. Either send out updates or not (it does not matter I think)

Upon saving (after handling the send-out-updates dialog) the encryption lock appears (red) and an error dialog opens: _Please provide an agreed password for each external recipient._
But we also have an uncaught error:
`UserError
Error message: Please provide an agreed password for each external recipient.
Stacktrace:
UserError. Please provide an agreed password for each external recipient.
UserError@https://test.tutanota.com/main.js:1:1328369
value/</<@https://test.tutanota.com/main.js:1:917533
a@https://test.tutanota.com/libs.js:26:74251`

**Comment by charlag** [comment]
@vaf-hub everything besides error dialog is intended, it's fixed in https://github.com/tutao/tutanota/commit/7c62f6e41e1b6714630770bc057f18eb1a2b4aa8 but we didn't merge it yet

**Comment by armhub** [comment]
Another issue: Invitation replies from gmx do not update the calendar event in Tutanota.

**Comment by charlag** [comment]
Tested out content overflow, there's a mistake for a few pixels, need to fix it again. Strange that it worked in one case but not in another.

**Comment by charlag** [comment]
> Re-testing accepting invites with a changed event date:
> 
>     1. Send invitation to one recipient for event 17:00-17:30.
> 
>     2. Change event time to 17:00-19:00 and send updates. Recipient get another invitation.
> 
>     3. Accept initial invitation by recipient -> the event in the calendar shows 17:00-17:30
> 
>     4. Accept the second invitation by recipient -> BadRequestError

This works now, both updating summary and updating time (different cases)

**Comment by armhub** [comment]
Replies from gmx are not parsed correctly. This will be fixed with our next test release.

**Comment by armhub** [comment]
Replies from gmx seem to work fine now.

**Comment by spiritloveroot** [comment]
does this work for ios too?
