### ISSUE TITLE
Sharing private calendars

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1356]

**Comment by armhub** [comment]
* Sharing calendars will be available when ordering the sharing feature
* Calendars can only be shared with Premium/Pro users (own and other customers)
* Administrator can add shared calendars
* Personal and shared calendars can be shared
* Use invitations to invite users to calendars, notify via email
* Show invitations in the calendar view
* Show an info who a shared calendar belongs to
* Share permissions: read, write, invite

**Comment by charlici** [comment]
Hello,
The sharing calendar is an important improvement. 
Is there any approximate release date of this new feature ?
Thanks

**Comment by FDJFDJ** [comment]
Hello,
Also for me 
I'm waiting for this feature before buying a premium account

**Comment by charlag** [comment]
Hi
Foundations are already there but currently we are pretty busy fixing bugs. It won't take too long before the first version but we don't give estimates - it usually doesn't match reality.

**Comment by bedhub** [comment]
### Initial calendar sharing
- [x ] Add option to share personal calendar / send invite
- [ x] Show invitations in the calendar view
- [ ] Accept invites as  premium/pro users
- [ ] Share permissions: read, write, invite
- [ ] Ordering of sharing feature
- [ ] Notify about invites via email
- [ ] Show an info who a shared calendar belongs to
### later
- [ ] Allow administrators to create shared calendars
