### ISSUE TITLE
Add new settings

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1357]
- AM/PM time
- start of the week
- language
- color theme

**Comment by mpfau** [comment]
I guess am/pm should be written lowercase and maybe a whitespace between minutes and am/pm would improve readability

**Comment by bedhub** [comment]
created new issue for handling am/pm styling in TimePicker #1408

**Comment by JimmyCushnie** [comment]
Currently we can only select Sunday or Monday as the day the week starts on. Could there be an option for the other days of the week?

For various reasons my life is organized in Wednesday to Wednesday chunks, it would be great to see that visually by starting the calendar week on Wednesday and ending on Tuesday.
