### ISSUE TITLE
Links in emails have wrong colour

### ISSUE THREAD

**Issue by ondrejfuhrer** [tutao/tutanota#136]
Just tried the new beta and first issue I saw is the colour of links inside emails in dark mode. They don't fit the design and are really hard to read. Update to that would be appreciated.

![screencapture at fri oct 6 13 25 56 cest 2017](https://user-images.githubusercontent.com/10830505/31276035-228bd3f0-aa9a-11e7-82b5-55284bba2ad9.png)

**Comment by mpfau** [comment]
These links have been styled blue (style="color: #003399"). It was our fault but has nothing to do with the dark theme...

**Comment by ondrejfuhrer** [comment]
Hello @mpfau I see that the milestone and issue are closed, but I still see the "wrong" colour there (tested in Safari and Chrome).

**Comment by mpfau** [comment]
@ondrejfuhrer this is a problem of the sent mail. There is nothing we can do, if a css style like "color: #003399" is applied to a link...

**Comment by ondrejfuhrer** [comment]
@mpfau Ah, ok, I get it. Thanks
