### ISSUE TITLE
Allow other senders in DNS spf record

### ISSUE THREAD

**Issue by jpsingleton** [tutao/tutanota#1361]
This issue manifests in the clients but there don't appear to be any recent changes around this area so it looks like a change to the server side validation.

I recently started getting the `CUSTOM_DOMAIN_STATUS_INVALID_DNS_RECORD` error message when adding a custom domain unless the SPF record matches [the docs](https://tutanota.com/howto/#custom-domain) exactly. Previously (~1 month ago) it was more lenient.

I believe the check is too strict, as you may want to add many [SPF mechanisms](https://en.wikipedia.org/wiki/Sender_Policy_Framework#Implementation) to the DNS TXT record. For example, a mailing list provider.

- [X] This is not a feature request. I will request features on the forum or via support (see [contact page](https://tutanota.com/contact?page=feature)).
- [X] This issue doesn't fit into provided templates.

**Comment by armhub** [comment]
This is actually already in the pipeline and should be released next week.

**Comment by jpsingleton** [comment]
OK, I couldn't find this tracked anywhere when I looked. As a workaround until this is shipped, you can set the DNS as required to add the custom domain then change it after to add other senders.

**Comment by armhub** [comment]
Let's keep this issue open to track the status of the implementation.
