### ISSUE TITLE
page navigation (back/forward or alt/cmd + left/right) breaks modals when the mail editor is open

### ISSUE THREAD

**Issue by joakim** [tutao/tutanota#1364]
**Describe the bug**
When navigating text using alt+left in a New mail dialog, the app becomes partly unresponsive (can't close dialog or send mail) and has to be force quit. Sometimes the title of the app changes in strange ways (my email address is repeated). Sometimes the whole app becomes white, and it's only possible to quit (force not necessary). It's a strange bug.

**To Reproduce**
1. Create new mail
2. Enter some text
3. Try to navigate the text using alt+left
4. App crashes in strange ways

**Expected behavior**
The app doesn't crash

**Desktop**
 - OS: MacOS
 - Version 3.55.4

**Additional context**
No such issues in normal web app.

**Comment by ganthern** [comment]
Seems to be related to the fact that alt+left is "one page back" in most browsers and the desktop client is doing something silly with the "are you sure you want to leave this site" prompt that's normally shown when trying to go back during mail authoring.

**Comment by ganthern** [comment]
reproduced for:
3.55.7 @ MacOs 10.13.6
3.55.7 @ Win 10
3.55.7 @ Ubuntu 18.04

**Comment by ganthern** [comment]
This is a general problem in the way we handle page navigation while the mail editor is dirty.

**Comment by bedhub** [comment]
Modals that don't handle back actions:
- Dropdown in header, on mail folder, in contact view ....

**Comment by bedhub** [comment]
- dropdown close now by going back
