### ISSUE TITLE
Improve event selection in  Calendar Agenda view

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1368]
https://github.com/tutao/tutanota/issues/1337#issuecomment-512762872

> The agenda currently shows all currently loaded events which my be different depending on which months had been displayed already. We should instead either restrict it to a fixed number, a fixed time period or allow loading more events when scrolling the agenda.

**Comment by armhub** [comment]
Decision: show one week, no loading of more events because we might try to load infinitely if there are no more events.
