### ISSUE TITLE
white screen when logging out/going back with alt+left

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1382]
**Describe the bug**
sometimes, the desktop client will appear to have crashed with only a white page in the window.

**To Reproduce**
1. open login page
2. log in
3. hit alt + left until the page title becomes "login"

**Additional context**
Workaround: press F5 to reload window

the fix to detect the attempt to load desktop.html/login as a file and redirecting it to desktop.html inexplicably results in a segfault.

**Comment by mpfau** [comment]
still appears for me
