### ISSUE TITLE
[Improvement] Swipe for prev/next email on mobile app

### ISSUE THREAD

**Issue by l0f4r0** [tutao/tutanota#1385]
On the mobie app (at least Android), after viewing an email, one needs to get back to the email list and then select an adjacent email.
It could be handy to allow the user to just swipe left/right (or even up/down) to select the previous email or the next one.

**Comment by mmaster23** [comment]
Has this worked in the past? It was closed in 2019 but I'm running the latest Android build from Google Play Store and I can't swipe to next message using a Samsung S25U

**Comment by l0f4r0** [comment]
Hi @mmaster23, actually I don't know why my suggestion was tagged as completed because it still doesn't work that way for me neither... (Samsung S20 FE with Android 13) ;)

**Comment by mmaster23** [comment]
Looking again at this post, and the dates of the completed tag, I don't think this was ever a thing then. A shame because my entire workflow depends on it. And without my native email client, I don't think I'll adopt Tuta beyond the trial period.

**Comment by paw-hub** [comment]
It is possible that it was broken or removed some time ago. I recommend opening a new issue with repro steps.

**Comment by l0f4r0** [comment]
hi @mmaster23,

> Looking again at this post, and the dates of the completed tag, I don't think this was ever a thing then.

You're probably right. I didn't check the dates and didn't realize it was closed the same day :'D
Maybe Tuta doesn't want GitHub issues for suggestions? I see "*improvement*" GitHub tags nonetheless...

Anyway, all my suggestions now are formalized directly through the app because I know it's correct that way at least (click on the question mark symbol => "Support" => _Choose the applicable section_ => "Feedback/Feature Requests").
The drawback is that the reporting is not public so one doesn't know if it has already been reported, and other users cannot support one's suggestion...
