### ISSUE TITLE
[Improvement] Some UI suggestions

### ISSUE THREAD

**Issue by l0f4r0** [tutao/tutanota#1388]
Some UI improvements:

- allow resizing of columns in the web app
- email filtering (such as display only folders containing new emails)
- email starring
- mark a whole folder as read
- enlarge a little bit the "go to folder" contextual menu (mobile app) because folder names are truncated

**Comment by charlag** [comment]
We don't accept feature requests through github, it would be too much, thanks for unederstanding. Also some of them are already planned.
