### ISSUE TITLE
Calendar – Persistent Notifications

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1389]
I think we need "persistent notifications" for calendar events – read: an e-mail.

We should be able to choose how do we want to get notified: push notification or just an e-mail.

**Comment by charlag** [comment]
The time of alarm is calculated on your device, we don't really want to know the time. We'll consider it later.

**Comment by nikolayhg** [comment]
+1 for **persistent notifications**. Current notifications are unreliable. If the user is not at the computer or his attention is temporarily elsewhere while a notification appears, then the user will miss the notification.

Some kind of persistent notification (visible until closed or deleted), would fix that.

**Comment by nikolayhg** [comment]
@charlag reopen issue?

**Comment by charlag** [comment]
You are looking for #1487

**Comment by nikolayhg** [comment]
yes, thanks!
