### ISSUE TITLE
Calendar today's day incorrect

### ISSUE THREAD

**Issue by miwojc** [tutao/tutanota#1391]
**Bug in web app**

**Describe the bug**
Shows today's date for every month (red circle)

**To Reproduce**
1. Go to tutanota.com and login
2. Click on calendar
3. change view to next or previous month

**Expected behavior**
only current month has today date shown (red circle)

**Screenshots**
![image](https://user-images.githubusercontent.com/32404415/61992059-831ffb80-b059-11e9-8cdf-b3163671022d.png)
![image](https://user-images.githubusercontent.com/32404415/61992065-8a470980-b059-11e9-884f-6836c98e0eba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 0.66.101

**Additional context**
Same issue using mobile app on android phone.

**Comment by armhub** [comment]
The red circle marks the selected day, not the current day. The grey circle marks the current day. Therefore closing this issue. To avoid this confusion we have already planned some improvements: https://github.com/tutao/tutanota/issues/1378
