### ISSUE TITLE
Little wrong translation in spanish calendar

### ISSUE THREAD

**Issue by sobrinojulian** [tutao/tutanota#1399]
In event screen. Reminder: None. It is translated to: Recordatorio: Ningun*a*. The correct translation is: Ninguno.

In spanish nouns have 'sex' depending on how the word ends. For example:
*El* recordatori*o*: Ningun*o* (The reminder: None)
*La* mes*a*: Ningun*a* (The table: None)

Thank you!

**Comment by charlag** [comment]
Hi!
We would like to keep one translation key for now. Do you think it is possible to find such a translation that will fit for all genders?

**Comment by ganthern** [comment]
maybe we could switch to _la notificación_ instead of _el recordatorio_. Not sure how appropriate that is.

**Comment by sobrinojulian** [comment]
Hi!
By [translating None in Google Translate](https://translate.google.com/#view=home&op=translate&sl=en&tl=es&text=none) you can see what I mean about gender specific translations. There is also an explanation about it.
There is only one correct translation and is: "Ninguno". Because "recordatorio" is masculine, (because it ends with the letter 'o').

Another spanglish example might be:
How many "notificaciones" (ends with "es" because plural) do you have? Ninguna. (Since notificacion is female)
How many "recordatorios" (ends with "s" because plural) do you have? Ninguno. (Since recordatorio is masculine).

Its a pity I dont know about linguistics, to explain it better.

**Comment by charlag** [comment]
It's up to translators to define keys which work for multiple genders
