### ISSUE TITLE
"Reply" button does not work for Forwarded mail from an other mail box. 

### ISSUE THREAD

**Issue by anton-petrunin** [tutao/tutanota#14]
"Reply" button  does not work for the forwarded mail from an other mailbox,
the same for "forward" button.

**Comment by bedhub** [comment]
Hello anton-petrunin,

thanks for the hint. I was able to reproduce this error with our client version 1.9.1 when receiving an email as bcc recipient from an external mailbox. I fixed this issue and released the new version 1.9.2.
