### ISSUE TITLE
contact bubbles in the mail editor only show "create contact" if editing a draft, even for known mail addresses

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1402]
**Describe the bug**
contact bubbles in the mail editor only show "create contact" if editing a draft, even for known mail addresses

**To Reproduce**
1. create contact
2. create new mail, choosing the contact in the "to:" field from suggestions. Clicking the bubble will have the "edit contact" action in the dropdown
3. save the draft
4. go to drafts, edit the draft, click the bubble -> only option is to "create contact"

**Expected behavior**
known contacts should have the "edit contact" option

**Comment by brshub** [comment]
Step 4 lists "Edit Contact" and "Remove". Create contact is no longer listed.
