### ISSUE TITLE
TimePicker am/pm style

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1408]
I guess am/pm should be written lowercase and maybe a whitespace between minutes and am/pm would improve readability

**Comment by margaretgorguissian** [comment]
👋 Hi bedhub, can I pick this up as a first issue?

**Comment by charlag** [comment]
@margaretgorguissian please feel free to!
Would be nice if one tested it across OSes & browsers because different systems do it differently and we would like to match how system formats it

**Comment by rdvincent** [comment]
@margaretgorguissian Are you working on this? @charlag why not use the same formatting as is applied in the mail view?

**Comment by charlag** [comment]
@rdvincent because here we actually need to parse these dates back

**Comment by rdvincent** [comment]
@charlag would the formatTime() function from Formatter.js accomplish the task and use the same options/localization as email?

**Comment by charlag** [comment]
@rdvincent it can format it but Formatter is locale dependent and we we are not always able to parse time formatted with it back so in this place we must format it manually, without Formatter.

**Comment by rdvincent** [comment]
I am addressing this by first changing the parseTime() function and its associated tests to be more flexible.
