### ISSUE TITLE
Problem with logging in on mac using keychain

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1409]
> I only use the Mac built-in keychain access, which saves my password of course. It is a desktop program app (but not a dedicated app) on my Mac as I go through Safari. I haven't used the Tutanota save password option so far.
> 
> One thing I must say is that the problem accessing Tutanota is inconsistent: some days I can connect whenever I want, and other days it comes up with the 'too many failed log in attempts' information. 
>

**Comment by charlag** [comment]
Haven't been reported for a while
