### ISSUE TITLE
Cannot scroll folder list in drop down dialog of move mail action

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#141]
I can only select the folders that appear on screen from the Pop up box. I cannot scroll down to other custom folders that I have created. I am using brave browser on android.

The browser is the Android version of Brave. https://play.google.com/store/apps/details?id=com.brave.browser . It is built on Chromium so the bug should replicate in Chrome too.

**Comment by bedhub** [comment]
same on iOS devices
