### ISSUE TITLE
Calendar – Custom Recurrence

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1412]
Not quite a **Bug in web app**

Events recurrence is tied to the date in question, but sometimes it's super-useful to say, for instance: I want this to happen **monthly on the second Saturday**.

**To Reproduce**
1. Go to `Calendar`
2. Click on `Create Event`
3. Click on `Repeating`
4. :sob: There is no option to set that!

**Expected behavior**
Repeating events should occur on the date or on the relative date according to the initial day.

**Comment by charlag** [comment]
We don't submit feature requests here but we want to improve repeating rules in the future. We will create an issue once it's planned, thanks for your interest.

**Comment by x80486** [comment]
Any plans for this one? It should be a mildly simple calculation to say: on a given day or day of the week, and it's pretty useful, sometimes we don't want stuff to happen on a given day, but on a given day of the week.

**Comment by charlag** [comment]
@x80486 feel free to draft an algorithm. This is not a top priority right now but we want it eventually.

**Comment by x80486** [comment]
Super easy, my dear @charlag. You already have the frequency, so you only need an interval and a "discriminator" to specify the events by day or month day...then some cleverness for the edge cases, those months that, for instance, have 5 rows (like the next November) :wink:
