### ISSUE TITLE
Getting an error and app stops working after selecting some languages

### ISSUE THREAD

**Issue by emanuelpina** [tutao/tutanota#1414]
**Bug in web app**

*Introduced in 3.57.3*

**Describe the bug**
Getting an error and app stops working after changing language to Portuguese, Portugal

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Appearence'
3. On 'Language' choose 'Portuguese, Portugal'
4. See error and app stops working

**Desktop:**
 - OS: Windows 10 Pro v1903
 - Browser: Firefox Developer Edition v69.0

**Comment by charlag** [comment]
Workaround for now is to clear site data. We will fix it asap
