### ISSUE TITLE
[MacOS] Cannot verify signature of desktop application

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1416]
As safari automatically extracts and removes the zip file of the desktop application by default users are not able to verify the downloaded file anymore.

**Comment by bedhub** [comment]
We will change to dmg file format with the next release as it is also more convenient to have a dmg file instead of zip file for macOS applications.

3c0d21eeae8fc93209a25fcbee7a81116b0d8a97

**Comment by bedhub** [comment]
zip file is still required for autoupdate:
https://github.com/electron-userland/electron-builder/issues/2199

**Comment by ganthern** [comment]
The description of the verification process was updated to warn MacOs users of this behaviour. We will switch to dmg installers in the future (#1441)

commit: 7192dbf9bcdb0af842466d3887da44704b91c781
