### ISSUE TITLE
[Feature request] 'Snooze' message from inbox

### ISSUE THREAD

**Issue by deepdivingspearo** [tutao/tutanota#1421]
Recently moved from Gmail + Mailspring. Really enjoyed the "snooze" option for messages which hides the message from the inbox for a set period of time. E.g. Snooze till tomorrow, Weekend, next week etc. Be great to see that implemented. Thanks for a fantastic product.
![Screenshot from 2019-08-13 16-57-03](https://user-images.githubusercontent.com/5320692/62952119-6d495f00-bdeb-11e9-8e05-9bc22f990e6f.png)

**Comment by charlag** [comment]
Hi
Sorry but we don't accept feature requests here.
Please take your issue to Reddit or to the support.

**Comment by 4jNsY6fCVqZv** [comment]
@charlag Excuse me, I'm new here. Do not understand your statement. If I look through the issue list, I see a lot of feature requests, some of them are also labeled with "new feature" or "improvement". How is your Workfkow?
