### ISSUE TITLE
Search view: Cannot move mails from different folders to one folder

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1430]
Use case: I want to move all email to or from a receipient to one folder. Use search to find the emails and then select all and move them to a specific folder. The following error message appears:

"This operation can not be executed at the moment because another operation on this folder is still running."

This is happening because we group the different folder operations and we execute them in parallel.

**Comment by Mxchaeltrxn** [comment]
Hi could I take this up as a first issue?

**Comment by charlag** [comment]
@Mxchaeltrxn please try to search for something that is not marked for the next release
