### ISSUE TITLE
Size mismatch for used capacity

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1431]
**Bug in web app**

**Describe the bug**
Under `Settings`, there are two places where users can see the "storage capacity" (or "used storage"): under `User Management` or under `Subscription`.

There is a mismatch for the provided value in question between those views. I don't know if this is an issue with my mailbox (I remember a while back something happened and some e-mails vanished, but later you fixed it and they came back) or if this impacts everyone else.

Third possibility is that I'm interpreting those values incorrectly, but it doesn't look like.

**To Reproduce**
1. Go to `Settings`
1. Click on `Subscription`; read the `Storage Capacity` value
1. Click on `User Management > User Settings`; read the `Used Storage` value
1. Compare :thinking:

**Expected behavior**

Both values should be the very closed, if not the same.

**Screenshots**

![fixed___Screenshot from 2019-08-13 07-20-12](https://user-images.githubusercontent.com/34633617/63066257-305a9680-bed7-11e9-9d4f-c2090d602ef7.png)

![fixed___Screenshot from 2019-08-13 07-20-07](https://user-images.githubusercontent.com/34633617/63066264-38b2d180-bed7-11e9-856f-801fcab16763.png)

**Comment by charlag** [comment]
Hi
The values may differ.
Please write to the support (and mention this issue) and we will provide you with more detailed information.
