### ISSUE TITLE
Doing Ctrl+Z in the composer closes the window

### ISSUE THREAD

**Issue by Gaspacchio** [tutao/tutanota#1434]
**Describe the bug**
When writing a new message, using `Ctrl+Z` shortcut to undo something (like undeleting a word), the whole window disappears and I have to open it again to continue typing.

**To Reproduce**
1. Go to 'New message'
2. Start typing
3. Press `Ctrl+Z`

**Expected behavior**
Keep the window open.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.57.5

**Comment by ganthern** [comment]
Could not reproduce in the current version, please comment if this Issue still persists.

**Comment by Gaspacchio** [comment]
Yupp, still having the issue, I'm up to date with the latest version. Can I launch Tutanota in debug mode or something similar to give you more insight ?

You can find a screen capture of the problem right here:
![tutanota-ctrlz-bug-test](https://user-images.githubusercontent.com/43613824/68196822-6e88c300-ffb9-11e9-96bf-98a0846bb767.gif)

**Comment by ganthern** [comment]
That's weird. If you launch Tutanota from a terminal session (cmd), you can get some output that may shed light on this.

To do so, hit the Windows Key and type cmd, then enter the path to the Tutanota Executable in Quotes (for example "C:\Users\Gaspacchio\AppData\Local\Programs\Tutanota Desktop\Tutanota Desktop.exe"). 
You can get the Path from the shortcut properties from the shortcut you use to launch it (right click -> properties -> target field). Reproduce the Issue and send the output to hello@tutao.de to keep it private (though it shouldn't contain any sensitive data).

Additionally, it may be useful to know 

- what your Keyboard Layout is
- if this problem occurs in any other (Electron-)Apps
- if you have the same issue if using undo from the context (right-click) menu
- if the window is actually closed or if it still appears in the list that's shown if you right-click Tutanotas tray icon on the right side of the task bar (then it's just hidden).

Thanks for your help!

**Comment by Gaspacchio** [comment]
Thanks for your quick response. Here is some more insight:

- Keyboard layout is French (France)
- I would love to test other electron apps, do you have a suggestion ? But, in my memories, this issue seems unique to Tutanota desktop app...
- Using undo does not produce the issue
- The window is not closed, just hidden in the task bar and no content is lost

Mail is sent, good reception on your end 👍

**Comment by ganthern** [comment]
I can't seem to find the mail, did you send it to hello@tutao.de? (not @tutanota.de!). Maybe try to resend, if you put "Gaspacchio" into the subject it will be easier to find.

**Comment by Gaspacchio** [comment]
Done, sent again. Hope you'll find it !

**Comment by ganthern** [comment]
So, I looked at the log and it's completely normal. 

I think there's something going wrong with the locale/langue detection, because the french keyboard has a `Z` where on others there's a `W`, and `Ctrl`+`W` is our hotkey to close the window. Thanks for being so helpful!

**Comment by Gaspacchio** [comment]
Indeed, that's a strange behavior, I would never have had thought of such an issue... I'm glad I helped to improve Tutanota and I hope to see this issue fixed soon!
