### ISSUE TITLE
Mail editor creates mailto and url links in plaintext mode

### ISSUE THREAD

**Issue by guoyunhe** [tutao/tutanota#1435]
Everytime you type something like:

```
My email address is foo@bar.com
```

It is transformed to:

```
foo@bar.com <mailto:foo@bar.com>
```

I have chosen Plain Text email by default. And I don't want any formatting.

I wanted to subscribe to some mail list, which request me to send an email with exact email address to confirm. But this auto formatting failed it all the time.

I am screwed up.

**Comment by charlag** [comment]
Hi
I just tried it out and if I don't add a space or newline after the email address it stays just a text.
We should look into disabling this behaviour in the editor.
