### ISSUE TITLE
There is no ability to change status bar color

### ISSUE THREAD

**Issue by L11R** [tutao/tutanota#1437]
**Bug in mobile app**

**Describe the bug**
So title says enough, as Pro user I can use whitelabel feature to change default theme. But there is no ability to change color of status bar at Android devices.

**Screenshots**
![Screenshot_20190821-121649](https://user-images.githubusercontent.com/5345489/63419512-a1390b80-c40d-11e9-965c-dca27ea1e8cc.png)

**Smartphone (please complete the following information):**
 - Device: BlackBerry Key2
 - OS: Android 8.1
 - Version: 3.57.5

**Comment by charlag** [comment]
Hi
Sorry but we don't accept feature requests here.
We will consider this nonetheless but I think there are some system limitation and we may be limited to the subset only.

**Comment by L11R** [comment]
Sorry, I didn't know.

What system limitation you mean? Android design guidelines? Presets would be also nice.

**Comment by charlag** [comment]
We have to pre-define status bar colors I think, we cannot add them dynamically as far as I know

**Comment by brshub** [comment]
Feature request
