### ISSUE TITLE
Use root key in DKIM check

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#145]
See https://www.reddit.com/r/tutanota/comments/73ss2r/authenticationresults_incorrectly_marking_a_dkim/

**Comment by vitoreiji** [comment]
@armhub The linked reddit post has been deleted. What does this refer to?

**Comment by armhub** [comment]
It is about using the correct trust anchor for DNSSEC. I will close this as we have to take care of it in our new DKIM implementation.
