### ISSUE TITLE
Define the current user TimeZone in Appearance/User Settings

### ISSUE THREAD

**Issue by pierregillon** [tutao/tutanota#1450]
Hi Tutanota team,

First, thanks very much for the great work you do on the email client. It is great, and I really enjoy the features and iterative work you do.

I have a little issue with the web client. I see EN-us dates for emails and calendar events while I would like to see Fr-fr format. I understand the format is read for the device (here my browser) to display the correct date. But for my case, I disabled french format to keep my http request anonymous (part of the best practices to protect privacy while browsing). I am ok to keep this behavior by default, but override can be useful.

So, as a user, 
I would like to explicitly specify my time zone in my user settings
In order to display all dates in the correct format (email dates and calendar events)

Concerning travels, I understand the dates would stay in the format I specified, event if my device is changing (or not) the localization.

Thanks for you work !

Cheers

**Comment by charlag** [comment]
Hi
This is a feature request and it's not accepted here, sorry.
Second, time zone does not influence date format, your selected locale does. You can select locale in settings now and formatting should use it.

**Comment by pierregillon** [comment]
Oups, where should I suppose to request for the feature ? I wanted to change the tag to feature but can't really find where it is.

Time zone influence the date itself, not the format, I agree. I already switched client to french locale and it displays correctly the date (16h36 for example). BUT, the TimeZone used is UTC not UTC+2 (summer vs winter?) which is the expected french date.
A "french date" is a non sense by the way, that's why I need to specify the TimeZone (Paris UTC+2 for example) to have the right date.

For example, I receive an email now, the date is 12h55 but it is 14h55 in my Time zone.

It is a matter of a TimeZone, not a Date format, sorry for the miss explained.

**Comment by charlag** [comment]
As said in README, we ask our users do discuss new features on Reddit.
I would say that Firefox should add exception for resist-fingerprinting. I'm not surw that we really have to do this.
