### ISSUE TITLE
One unread letter

### ISSUE THREAD

**Issue by Geradot** [tutao/tutanota#1451]
Good day. 

A notification about a new incoming message in the Inbox folder hangs in the mail. But he is not there, all letters are read.

The problem is present in all platforms and devices and browsers (include application). 
![Screenshot_2019-08-28-09-52-01-076_de tutao tutanota](https://user-images.githubusercontent.com/16444502/63832742-21b1bc00-c97a-11e9-924e-e51b2437c5b2.png)

**Comment by charlag** [comment]
Hi
Please contact support and they will solve this
