### ISSUE TITLE
[FEATURE] Ability for more accounts in android and linux app and [FEATURE]

### ISSUE THREAD

**Issue by personaingrata** [tutao/tutanota#1452]
#i would love to have more accounts synchronized in the linux and android app because im using more than one tutanota mail account. have i missed something or is it just not possible?

thx in advance

ps: just opened my github account and im no dev, i hope i posted it in the right area. Hello

**Comment by charlag** [comment]
Hi
First of all, we don't accept feature requests on Github (see README), thanks for understanding.
Second, it's duplicate of #903
