### ISSUE TITLE
Earlier events from the current day are visible in the agenda

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1454]
Only currently running and future events shall be shown in the calendar agenda.

**Comment by armhub** [comment]
Let's first discuss if this is actually how we would like to have it.

**Comment by bedhub** [comment]
We changed the behavior to show only future and currently running events in issue #1367. Which events are still visible?

**Comment by bedhub** [comment]
The condition which filters finished events for today is broken and earlier events of today are shown in the agenda view. After discussing with armhub we decided to show all events of today even if the event has already ended.

**Comment by charlag** [comment]
I would love to make this an infinite list of all days which current time marked. Then we don't need to filter out anything anyway.

**Comment by bedhub** [comment]
I agree that this could be an improvement and we can create another issue. To fix this issue i just removed the condition to show all events of today.
