### ISSUE TITLE
Calendar date picker doesn't respect Week Start preference

### ISSUE THREAD

**Issue by biscober** [tutao/tutanota#1455]
**Bug in web app, mobile app, and desktop app**

**Describe the bug**
I have set the Week Start preference under Appearance -> User Settings to Sunday which is the typical week start day in North America.  The calendar reflects this, however when scheduling an event the date picker does not - the week still starts on Monday in the date picker.

**To Reproduce**
1. Set Week Start preference to Sunday
2. Go to calendar and see that Sunday is now the week start day
3. Add an event
4. Click the little calendar button in either the From or To section of the new event window to change the date
5. Notice that the week start is Monday in the picker, even though the preference for Week Start is set to Sunday

**Expected behavior**
The week should start on Sunday in the date picker when the user preference is set for the week to start on Sunday.

**Screenshots**
<img width="622" alt="brave_2019-08-30_11-48-29" src="https://user-images.githubusercontent.com/50845461/64034335-6f662a00-cb1c-11e9-9f82-6fc1061e1064.png">
<img width="693" alt="brave_2019-08-30_11-48-58" src="https://user-images.githubusercontent.com/50845461/64034344-71c88400-cb1c-11e9-86e4-39576dcb6b74.png">
<img width="803" alt="brave_2019-08-30_11-49-30" src="https://user-images.githubusercontent.com/50845461/64034349-755c0b00-cb1c-11e9-88d3-a318296a5d47.png">

**Additional context**
This is an issue on the Desktop app, Android app, and web app.  I don't have an iphone but I assume it's an issue there too.

**Comment by marcosdiasalves** [comment]
Same issue for me. Not fixed yet.

**Comment by papadokolos** [comment]
The exact same issue is happening for me on Tuta Android app.
On Windows desktop app it is okay.
If there is any information I can add to help to resolve the issue, I am willing to.
