### ISSUE TITLE
[Android] "Notification service" notification when cannot reach server

### ISSUE THREAD

**Issue by gpa** [tutao/tutanota#1456]
**Bug in mobile app**

**Describe the bug**
At home I usually have my phone in airplane mode. For the night I also turn wifi off. In the morning there is always this following tutanota notification. It goes away as soon as I turn the wifi back on. I have verified that turning on mobile data instead does not make it go away even though the internet is reachable. I'm also not sure if the notification shows up after a constant amount of time but one has to wait at least 4 hours.

**To Reproduce**
1. turn off wifi and enter airplane mode - although last time I checked the airplane mode wasn't necessary, just no wifi and no mobile data.
2. Keep the phone like this for at least 4 hours.

**Expected behavior**
The notification does not show up.

**Screenshots**
![sc](https://user-images.githubusercontent.com/18526190/64073779-b2eaa080-cca2-11e9-8118-b2ea5418fe20.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung s9+
- OS: Android 9
- Version 3.59.5

**Comment by charlag** [comment]
I could not reproduce it with airplane mode but it can be easily reproduced when there is nominal network but we cannot reach server for some reason (e.g. network is not actually working).
