### ISSUE TITLE
[iOS] vertical scrolling not possible on iPhone

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1460]
with version 3.59.8 vertical scrolling in the mail viewer is not possible when the mail also needs to scroll horizontally.

**Comment by dinoo** [comment]
I am also unable to scroll vertically, I am using the same version (3.59.8) as @bedhub reported.

Device info:
iPhone SE
iOS 12.4

**Comment by charlag** [comment]
Fixed by b38aadec1a7772fcf91007f4ed46c0911c6edef2
