### ISSUE TITLE
Race condition when updating entities

### ISSUE THREAD

**Issue by portstrom** [tutao/tutanota#1466]
If two updates are sent for the same entity, one of them will overwrite the other. This could lead to data loss. One way to solve this would be to have a hash or version number of each entity that must be sent when updating. If the specified version doesn't match the version currently on the server at the time of the update, the update will fail, and the client can handle this as appropriate, for example by showing an error message to the user or fetching the latest version of the entity and applying the update to that version.

**Comment by charlag** [comment]
We are well aware of such a possibility and we avoid trying to update in race.

**Comment by portstrom** [comment]
How can you try to avoid updating in a race?

**Comment by charlag** [comment]
Which race you're running into?
Better solution might be to implement PATCH method

**Comment by portstrom** [comment]
Any modification to any entity is a race.
From [RFC 5789](https://tools.ietf.org/html/rfc5789):
> Collisions from multiple PATCH requests may be more dangerous than PUT collisions because some patch formats need to operate from a known base-point or else they will corrupt the resource.  Clients using this kind of patch application SHOULD use a conditional request such that the request will fail if the resource has been updated since the client last accessed the resource.  For example, the client can use a strong ETag [RFC2616] in an If-Match header on the PATCH request.

**Comment by charlag** [comment]
For cases where race is likely we use server-side synchronization. We are likely to have timestamp on the server but I'm not sure yet that we should do this rejection in all cases.
