### ISSUE TITLE
Integrity against moving field values is not provided

### ISSUE THREAD

**Issue by portstrom** [tutao/tutanota#1468]
The keys and IVs used to authenticate and encrypt a field are independent of the identity of the field. This means the value of one field can moved to another field on the same entity and still pass authentication. To provide integrity, each field should have a different fixed IV (or key).

**Comment by charlag** [comment]
Each value has it's own IV
https://github.com/tutao/tutanota/blob/master/src/api/worker/crypto/CryptoFacade.js#L481

Do I misunderstand you?

**Comment by portstrom** [comment]
Each value has a nonce. The IV is based solely on the nonce, not on the field ID, so a valid authenticated message for once field is also a valid authenticated message for another field of the same entity.

**Comment by charlag** [comment]
Same as #1470
