### ISSUE TITLE
Whitelist to permit image loads

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#147]
<old link removed>

**Comment by armhub** [comment]
Idea:
- store flag on mail to indicate that images are always loaded
- if loaded once the images are always loaded when selecting the email again
- allow adding inbox rule to set the flag on received emails to always load images for specific senders

**Comment by armhub** [comment]
Related to #362

**Comment by olof-nord** [comment]
This is something which I am missing at the moment - every time having to click to load the images is a good default safety feature, but there are a few senders which I trust and would like to have the option to always load.

**Comment by johnbotris** [comment]
# Testing
- [ ] When you receive a mail from someone with inline external images, you are given the option to show images, or always show images from the sender
- [ ] Your choice to trust a sender is remembered across mails/login sessions
- [ ] You can revoke that trust by selecting the option in the more actions dropdown of the mailviewer
- [ ] If a mail's authentication fails, then external images will be blocked even if from a trusted sender

# Regressions testing
- [ ] We refactored IndexedDb usage which touched the Indexer. Make sure that existing search indexes are not destroyed
