### ISSUE TITLE
Various fields of a mail are not authenticated

### ISSUE THREAD

**Issue by portstrom** [tutao/tutanota#1470]
As a secure email service, I hope Tutanota strives to embrace both aspects of security, which are confidentiality and integrity, and not only one of them. Tutanota currently provides no integrity of various fields, such as attachments, body, headers, recipients and time. I suppose there's a technical reason not to encrypt these fields, but even if they're not encrypted, they should still be authenticated with a MAC.

Each field that refers to another entity also needs to authenticate the key of that entity. Otherwise no integrity is provided against swapping one entity with another, for example sending someone a mail with forged attachments and body and then modifying a legitimate mail to insert the forged attachments and body.

With so many fields to authenticate, I think it may be time to give up storing a separate MAC for each field, and instead put all fields into a hash tree and store the final hash only once per entity. This will also provide integrity against reverting a less than complete set of fields to a previous version.

**Comment by charlag** [comment]
Your proposal is not compatible with migration system we have where we convert instances on the fly between old & new versions, depending on the client version.

What is your threat model, why do you need authentication for these fields?

**Comment by portstrom** [comment]
The proposal is that the server sends hashes for all omitted fields. If the server converts an entity to a version with fewer fields, the hashes of the omitted fields will still be sent. The point of using a hash tree instead of just concatenating the hash of each fields is that not all hashes need to be sent if many fields are omitted.

A basic requirement for secure messages is that a middleman can't modify the message. That's why PGP has both encryption and signing. To provide any security, Tutanota would have to provide [key verification](https://github.com/tutao/tutanota/issues/768), signing and signature verification, and make sure there's no way the message can be changed on the server without failing authentication. Even when a message was not delivered as confidential, it should be sealed with a MAC at the moment the client assigns a symmetric key to the message, so the server can't modify it after that point. The way things are now, the server can forge anything, and the client can't detect it.

**Comment by charlag** [comment]
We do not plan to authenticate references currently, we might revisit this in the future
