### ISSUE TITLE
Initial date for new events created from agenda view should be today

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1476]
It is confusing that the initial date is sometime in the future or even in the past.

**Comment by Mxchaeltrxn** [comment]
Hi this seems relatively simple. Could I do this one as a first pull request

**Comment by charlag** [comment]
@Mxchaeltrxn feel free to! It was working before but then one type was changed. It's in the `AgendaView`

**Comment by Mxchaeltrxn** [comment]
@charlag Has this been fixed? I'm unable to reproduce this problem. When I try to set an event in the agenda, it starts off with today's date. 

I noticed that when I make the end time earlier than the start time, the start time doesn't change, which could be improved. Should I make another issue for this?

**Comment by charlag** [comment]
@Mxchaeltrxn to reproduce it, try to select another day in month view and then create an event.
I think this button should always just create event with today's day. Check `CalendarView` for that.

About date/time pickers: no, we decided on this, check #1444
