### ISSUE TITLE
Multiselection actions are not visible in desktop layout with one column

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#1477]
**Describe the bug**
Trash icon isn't visible when selecting multiple emails for deleting

**To Reproduce**
1. Use CTRL+left click to select multiple emails in your inbox
2. no trash icon is visible

**Expected behavior**
There should be a trash icon

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Desktop Environment: XFCE 4.12
 - Version: 3.59.12

**Additional context**
This bug was also in the previous version. I reported it on Mastodon several weeks ago and received a reply that it would be looked into.

**Comment by charlag** [comment]
HI
Could you send a screenshot? To me it works like it should

**Comment by andy5995** [comment]
Here ya go...

![image](https://user-images.githubusercontent.com/16764864/64988872-027bbf80-d892-11e9-8df3-15861f9053d5.png)

But I tried rescaling, made it wider, and that fixes the problem.

**Comment by charlag** [comment]
Ah, I see now, thanks! We should fix this case when it's desktop layout but there's one column

**Comment by andy5995** [comment]
oh.. yeah, maybe reopen the ticket with a new title?

**Comment by charlag** [comment]
I've tried to fix that but there are a lot of special cases (you have one email selected. Should we show actions? And what should we do when you ctrl-click on it?) and it only happens on desktop that I'm not sure we should really spend time on fixing it.

**Comment by andy5995** [comment]
Is there a reason why it couldn't be the same UX as the mobile app, in the case of only column?

Another option is to leave the ticket open for a while, marking it as low-priority.

Regardless of how its handled, I don't need single-column mode so this isn't a problem for me anymore.

**Comment by charlag** [comment]
I described the problem above. It's possible but it's some work. I think it's okay to keep it open.

**Comment by brshub** [comment]
This is still an issue when zoomed in on version 3.84.11 of the desktop client.

**Comment by charlag** [comment]
Not relevant anymore
