### ISSUE TITLE
Calendar notifications went on vacation after device change

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1485]
**Bug in mobile app**

**Describe the bug**
Stopped receiving calendar notifications after (recently) mobile change – email notifications works fine.

**To Reproduce**
1. Have some calendar entries with notifications
2. Change mobile device (or probably log in into another)
3. Wait for an event to happen
4. :scream:

**Expected behavior**
Calendar notifications should behave the same after device/mobile change.

**Smartphone (please complete the following information):**
 - Device: `Nokia 7.1`
 - OS: `Android`
 - Version: `9.x`

**Comment by x80486** [comment]
Probably this one is tricky to hunt down, but I'm just letting it here in case you can figure it out easily.

I solved my problem exporting the calendar, deleting everything, and importing it :rofl: ...that's it, fine for me :sunglasses:

I also remember that I removed the entry for the previous device (in some `Notifications` option under `Settings`. Not sure if that might have caused it.

> Actually, this is one of the issues I proposed the "persistent notifications" option, because even though one might not receive a push notification, there will be an e-mail with it as a proof the event happened.

**Comment by charlag** [comment]
Hi, thanks for the report.
We download all alarms on logging in initially so they *should* be scheduled.
We will try to reproduce it.

For emails notifications we have to schedule them on the server and that's something that we want to avoid (we need to know when the alarm happens for that)

**Comment by x80486** [comment]
OK, that's weird then. Like I said, probably I went into some state that I wasn't unable to receive those. By the way, I think it's super useful to have a "widget" like the one offered with the `Google Calendar`, where you can see what are the upcoming events and so on.

**Comment by charlag** [comment]
@x80486 could you please try again with new versions (3.59.17)? It might be fixed already

**Comment by x80486** [comment]
I think it's fixed. I haven't had any more trouble with this one...although I migrated to Google Calendar, but I'll try again with most of the entries I have, so I get more "action" here.
