### ISSUE TITLE
Show possibility of configuring custom notification email when selecting notification email language

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1486]

**Comment by bedhub** [comment]
Idea: Add a small text under the language selection as a link which provides access to add a custom notification mail.

Proposal: "Configure your own signature!"

After clicking on the link we could either save the draft and open the settings or show the dialog for adding the custom signature directly as an overlay for the mail editor.

**Comment by armhub** [comment]
I think it would be good to also move the language selection dropdown hidden by the expander to the right of the password field. Otherwise probably many users do not discover at all that you can switch the notification email language.

**Comment by vaf-hub** [comment]
Test notes:

- [ ] the sender field is always visible in mail editor. it is split if a secure external mail is being sent on large screens.
- [ ] the notification language dropdown is shown on the right of the sender field or in its own row (depending on screen size). it is always visible when sending secure external mails
- [ ] iff the user is global admin a clickable link is shown below the language dropdown
- [ ] this link opens notavailableforfreedialog for free users, buy whitelabel dialog if not ordered for premium users, or if already ordered the configuration dialog for custom mail notifications
- [ ] after configuring a custom mail notification this new language is immediately available from the maileditor from which the dialog was opened

**Comment by johnbotris** [comment]
The sender field doesn't fill up space horizontally when there is no external recipient. I think this was an issue with the merge however

**Comment by johnbotris** [comment]
The link under the notification email language selector doesn't allow for editing existing custom notifications, i.e. if i have a custom notification for german, it will still be filled in with the default text when i open the custom notification editor

**Comment by vaf-hub** [comment]
For improvements of the edit and add dialogs for custom notification mails a new issue was created: #3059

**Comment by johnbotris** [comment]
The notification email selector flickers when it is appearing
