### ISSUE TITLE
[Question] MTA & STARTTLS support

### ISSUE THREAD

**Issue by barbiehunter** [tutao/tutanota#1488]
![image](https://user-images.githubusercontent.com/38357837/65054897-98851800-d96e-11e9-80ac-9880f4ebfbed.png)
idk if i should be afraid or something, but is there something in planning or something like that? Guess that this might also be good for tutanota (but i'm not sure)

Source: https://starttls-everywhere.org/

**Comment by charlag** [comment]
HI
We will need to check couple of things, thanks for pointing out

**Comment by charlag** [comment]
Since we support MTA-STS now and awaiting inclusion into the policy list, I think this is closed
