### ISSUE TITLE
Settings > Login page is not usable in small screen

### ISSUE THREAD

**Issue by guoyunhe** [tutao/tutanota#1497]
I have a 14 inch laptop with 1280x720@1.5 resolution. This is the screenshot of the Settings > Login page:

![image](https://user-images.githubusercontent.com/5836790/65377720-b9c06e00-dcb8-11e9-8dae-841d8a98b523.png)

In settings pages, the right half part is totally empty, while the left side is crowded. Here is no way to manually change column width. The names of session devices are unreadable.

## Test Notes
- [ ] The active sessions table remains readable when viewed 
  - [ ] with a small window
  - [ ] on mobile
  - [ ] with a medium window (iPad)
  - [ ] with a large window (desktop)
 - [ ] When clicking or tapping on a row in the table, an information dialog appears

**Comment by akaessens** [comment]
The same issue appears in the Android app in portrait mode (F-HD resolution). Even with disabled IPs.

<img width="200" alt="Screenshot_20200619-152926" src="https://user-images.githubusercontent.com/24660231/85137879-25346d80-b242-11ea-9c93-8fb55cfb239c.jpg">
