### ISSUE TITLE
Storing emails locally on the computer

### ISSUE THREAD

**Issue by Piniatas** [tutao/tutanota#1514]
Hello, 

I thought that the tutanota client could store the emails with attachments in an encrypted form so that they could be stored on a pen drive and then opened in the tutanota client. My idea is based on the latest news about improving the tutanota client so that emails take up less space, and I think it could save even more.

**Comment by charlag** [comment]
Hi
Please notice that we don't accept feature requests here.
We have offline mode (#590) planned but there are no plans to implement what you are requesting. We think that being able to access emails from any device is one of the important features of Tutanota.
Maybe when we implement #1440 it will satisfy your needs.
