### ISSUE TITLE
Calendar view does not respect time format preferences

### ISSUE THREAD

**Issue by rdvincent** [tutao/tutanota#1520]
**Bug in web app**

**Describe the bug**
The calendar view does not respect 12/24 hour time preferences.

**To Reproduce**

1. Go to Settings/Appearance/User Settings/Time format
2. Select 12 hour time format
3. Reload the calendar view
4. Times are displayed in 24 hour time.

**Expected behavior**
Times in the calendar should respect the setting

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Chrome
 - Version: 77.0.3865.90

**Comment by charlag** [comment]
Sorry, could not reproduce it. There must be some specific case.

**Comment by rdvincent** [comment]
@charlag Sorry, it was just happening on my system, but it is now formatting correctly. It must be something consistent in the locale settings for my computer.

**Comment by rdvincent** [comment]
@charlag to clarify, what I am seeing is this: when I initially load or reload a URL, the 12/24 setting is ignored, all times are initially displayed in 24 hour time. Switching from email to calendar view will cause the 12/24 setting to be applied correctly when I next visit the view.
