### ISSUE TITLE
Please Keep Flatpaks Up To Date

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [tutao/tutanota#1536]
**Describe the bug**
At the moment Flathub shows version 3.50.10
https://flathub.org/apps/details/com.tutanota.Tutanota
while GitHub shows 3.59.17 as the latest version.
https://github.com/tutao/tutanota/releases

**Expected behavior**
If there is a new GitHub release for the desktop version, a new version should be automatically provided on Flathub.

**Comment by charlag** [comment]
After migrating to the new build system we will update Flatpak. Currently it's "preview".

**Comment by 4jNsY6fCVqZv** [comment]
You mean the new build system is preview or the Flatpak?

**Comment by nicolasmaia** [comment]
Needs to be updated again. Current version on flathub is so old it's literally not usable.

**Comment by ralxxx** [comment]
Current version in Flathub does not work and is not supported anymore.
