### ISSUE TITLE
Can not login with Chromium

### ISSUE THREAD

**Issue by letkan** [tutao/tutanota#1537]
**Bug in web app**

**Describe the bug**
Quite often when I try to log into my account in the browser I get "Could not reach server, looks like you are offline. Please try again later." although I am online.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chromium
 - Version 77.0.3865.90 (Official Build) Arch Linux (64-bit)

While I get the above error in Chromium I can login with Firefox just fine at the same time.

I noticed this bug was reported a few month back but closed without any solution. Please investigate this time, it happens not because the server is down!

**Comment by charlag** [comment]
@letkan hi
it might be a service worker problem or something similar.
Could you open develop tools and check console there, is there anything error-related?

**Comment by letkan** [comment]
Next time this happens I will. Right now it works. Thanks.

**Comment by letkan** [comment]
Here's the log from console
[mail.tutanota.com-1570467100098.log.zip](https://github.com/tutao/tutanota/files/3698586/mail.tutanota.com-1570467100098.log.zip)

**Comment by charlag** [comment]
@letkan I'm sorry, but it's kinda strange log, there's almost no info in it. Is there some better way to copy it or do you see something else?

**Comment by letkan** [comment]
@charlag I'll try to do better next time it happens, I think I unchecked "info" in log.
As I said, it doesn't happen always, a few minutes ago I logged in and there was no problem.

**Comment by charlag** [comment]
@letkan please let us know if you still experience issues

**Comment by letkan** [comment]
> @letkan please let us know if you still experience issues

so far so good.
