### ISSUE TITLE
despite update notification, update of Linux app is not apparent

### ISSUE THREAD

**Issue by cameralibre** [tutao/tutanota#1540]
- [x] This is not a feature request. I will request features on the forum or via support (see [contact page](https://tutanota.com/contact?page=feature)).
- [x] This issue doesn't fit into provided templates. 
(**which** provided templates? If they are provided, please link to them in this section!)

**System:** elementary OS (based on Ubuntu 18.04.2 LTS)
**Tutanota Version:** 3.56.0

I'm receiving persistent notifications that I need to update Tutanota:
![update](https://user-images.githubusercontent.com/15368010/66436852-b7b22980-ea84-11e9-9b29-1c7e21e2013d.png)

I cannot turn these off, so I'm currently unable to use the app. 

The notification does not link to a location where I can download an update.

Instead I went to the Tutanota website - it was not clear where I would find an update:
![no-link-website](https://user-images.githubusercontent.com/15368010/66437674-e3361380-ea86-11e9-9431-9a8275609837.png)

Searching on the FAQ page gave me this link:
![FAQ-search](https://user-images.githubusercontent.com/15368010/66437728-0f519480-ea87-11e9-984d-c83ca9c79162.png)
https://mail.tutanota.com/desktop/tutanota-desktop-linux.AppImage

Unfortunately, the AppImage which that leads to is the exact same version that I already have.

So either the update notification is erroneous, or it is not clear where the newest Linux desktop client can be found. (Please make it easier to find desktop clients anyway!)

Related issue: #1329

**Comment by charlag** [comment]
@cameralibre I tried it out and it seems like you are doing something wrong. Please make sure that all other versions of the app are completely stopped and that you are running the correct file. I tried it out just now and it is correct version.

**Comment by charlag** [comment]
About links to desktop clients: they are in beta, we will make them prominent when they are finished.
