### ISSUE TITLE
signup page not working : getting status 403 (forbidden ) on upgradepriceservice API

### ISSUE THREAD

**Issue by kushang** [tutao/tutanota#1541]
**Bug in web app**

**Describe the bug**
I did install Tutanota [Release 3.60.5](https://github.com/tutao/tutanota/releases/tag/tutanota-release-3.60.5) by following given building steps: https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md

After Running Tutanota web client in local server, when we load it in the browser it lands to the login page. 
When user tries to signup it gives alert "Could not reach the server, looks like you are offline. Please try again later"
But when we try to reach the server using the static url "https://mail.tutanota.com" it is reachable. 
In debug console, Request URL:https://mail.tutanota.com/rest/sys/upgradepriceservice?_body={"_format":"0","campaign":null,"date":null} gets 403 status code.

 
**To Reproduce**
1 Clone the repository: git clone https://github.com/tutao/tutanota.git
2 Switch into the repository directory: cd tutanota
3 Check out the latest web release tag: git checkout tutanota-release-3.60.5
4 Do npm install
5 Build the web part: node dist prod
6 Switch into the build directory: cd build/dist
7 python -m SimpleHTTPServer 9000.
8 Open the  with your favorite browser Firefox or Chrome/Chromium
9 Do signup 

**Expected behavior**
signup process to work

**Screenshots**
![t7](https://user-images.githubusercontent.com/8295536/66460182-fb605f80-ea93-11e9-9796-b91bb681428f.png)

![t6](https://user-images.githubusercontent.com/8295536/66460194-02876d80-ea94-11e9-8050-b4cf522843df.png)

**Desktop (please complete the following information):**
 - OS: Linux 4.4.0-148-generic #174~14.04.1-Ubuntu x86_64
 - Browser Firefox Quantum 66.0.3
 - Tutanote Version  tutanota-release-3.60.5
 - Node version: v10.16.3

**Additional context**
In tutanota/build/dist directory, if we run "node server" instead of "python -m SimpleHTTPServer 9000" if gives module not found error:

Error: Cannot find module '../devtutanota_latest_3.x/tutanota/build/dist/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by kushang** [comment]
@bedhub  Please, could you guide me on this case.

**Comment by charlag** [comment]
@kushang that's because of the CORS rules. Firefox has strict CORS for localhost, in Chromium-based browsers it just works, for Firefox you need to proxy all requests through your own server. There are Javascript servers which do this for you.
