### ISSUE TITLE
Can't run OS X desktop app: "App can't be opened"

### ISSUE THREAD

**Issue by sourceopenNL** [tutao/tutanota#1549]
**Describe the bug**
Tried on Mac OS Catalina 10.15. Just downloaded the zip file from the Tutanota website. Moved the executable to the Application folder. Started it, getting the message "App can't be opened". 

**To Reproduce**
1. Unzip Tutanota desktop app
2. Move app to applications
3. Start app from applications

**Expected behavior**
Expected that the desktop app would open. Didn't try it yet on earlier Mac OS versions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Version: 10.15

**Additional context**
In earlier OS X versions it was possible to control-click on the application and run, if there were any reasons to block the application. This didn't work on Catalina either.

**Comment by charlag** [comment]
Hi
We tested it ourselves on Catalina and it worked for us. Can you provide more details, which mac it is? Maybe try to run it from Downloads?
Thanks

**Comment by sourceopenNL** [comment]
Hi,

Downloaded it from https://mail.tutanota.com/desktop/tutanota-desktop-mac.zip on my 2018 MacBook Air running 10.15. Getting the same error by running in the download folder. In sys pref, security pane I don't get a app blocked message.

Will try to run it later on another device to see what's the difference.

**Comment by sourceopenNL** [comment]
Sorry, having the same issues on a MacPro with Catalina, but can start the app on a Macbook with Mojave (10.14.5). Tried starting from the downloads map too.

**Comment by charlag** [comment]
Did you try to run it with right-click? We've been able to run it.

**Comment by sourceopenNL** [comment]
Right click, open. "The application "Tutanota Desktop" can't be opened.". Opened sys pref, no signs of that the os is blocking something.

**Comment by charlag** [comment]
I created fresh macOS profile and tried there.
Which mac do you have?
I'm not sure it's related to #1550

**Comment by sourceopenNL** [comment]
"Beginning in macOS 10.15, notarization is required by default for all software."
Could be a problem. <10.15 I could right click, open an app and choose "open" when getting the message "is an app you downloaded from the internet". This doesn't work in Catalina for me, and also I'm not getting any messages in de sys. pref. or something.

Just downloaded the ZIP both on a Macbook Pro Retina and a 2013 Macpro on Catalina, having the same issues.

Last test I can do, I am upgrading an Macbook Pro from Mojave to Catalina which already has an install of the desktop app (I just saw it running). Let's see what happens after the upgrade. 

But Notarizing could be the issue because I expected to get the "initial launch dialog" as discussed in #1550

**Comment by charlag** [comment]
Then we should just try notarizing. Thanks for debugging. It's really strange that dialog is different.

**Comment by sourceopenNL** [comment]
Little update. The Mac which already had the app installed is still starting up after upgrading to Catalina. So, a Catalina install without having the app before the upgrade doesn't work, a Mojave install being upgraded and already having the app installed, doesn't give a problem.

**Comment by charlag** [comment]
We've managed to reproduce it, it seems like it's related to macOS unzipping the file in a weird say which breaks symlinks.
@sourceopenNL If you could try to unzip the file with something else (like command line) and tell us if it works, it would be nice.
We might migrate to dmg + zip for updates.

**Comment by sourceopenNL** [comment]
Thanks for the support. Indeed, after downloading the zip and unzipping it in the Terminal, it looks better. Still getting the unidentified message, but I can fix that in the system preferences. So it's indeed working. #1550 would still be great to see. Shall I close this issue?

**Comment by charlag** [comment]
No, please don't. We will implement notarizing for sure.
