### ISSUE TITLE
Cannot load events starting before 1970

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#1567]
To reproduce:

1. Create event starting before 1970
2. Reload the page

Expected:
Event is loaded

Actual:
Event is not loaded

**Comment by sconim** [comment]
Hi,
Is there a solution for this issue yet?
I have a dedicated Birthdays calendar and I find the date import limitation extremely inconvenient. ½ of my events in this specific calendar fall outside the set range (1970). 
Thanks!
