### ISSUE TITLE
[BUG] Email Delete automatic email

### ISSUE THREAD

**Issue by barbiehunter** [tutao/tutanota#1573]
**Describe the bug**
Emails in the trash should be removed/deleted from the trash after 30 days, but I notice that this does not happen. I don't know if I am missing a setting for this or if it is a mistake at tutanota. 

**Expected behavior**
Just have a look where the problem is and try to fix it.

**Screenshots**
![image](https://user-images.githubusercontent.com/38357837/67298221-4003e600-f4eb-11e9-9853-c70ee0c06a61.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Desktop Environment, if applicable Windows
 - Version 17763.832

**Comment by charlag** [comment]
There might be delays depending on how it's batched but they will be (or already are) automatically deleted.
