### ISSUE TITLE
Please make your webapp installable as a WebAPK on Android #PWA

### ISSUE THREAD

**Issue by szaimen** [tutao/tutanota#1575]
Please make your webapp installable as a WebAPK on Android.
Then I could use the Webapp as a native-like App.
See: https://developers.google.com/web/fundamentals/integration/webapks

https://github.com/tutao/tutanota/issues/1574 should probably get implemented first.

**Comment by charlag** [comment]
We don't accept feature requests here.
Native app does more things and does them faster so there's no intent to package as WebAPK right now.
