### ISSUE TITLE
[Android] White navigation bar when using dark theme

### ISSUE THREAD

**Issue by najodleglejszy** [tutao/tutanota#1585]
**Bug in mobile app**

**Describe the bug**
When using the app with the dark theme, the bottom navigation bar stays white, which clashes with the rest of the app's UI.

**To Reproduce**
1. Log out of the account
2. Switch theme to dark

**Expected behavior**
Navigation bar background and icons change colours in order to match the app theme.

**Screenshots**
https://user-images.githubusercontent.com/8598559/67637565-044a9100-f8dc-11e9-9d88-93f549097a25.png

**Smartphone:**
 - Device: Sony Xperia XZ2 Compact
 - OS: Android 9.0
 - Version 3.60.9

**Comment by charlag** [comment]
It's not really a bug but we changed it in the b39a06ff

**Comment by charlag** [comment]
Ah now I see, it's not about status bar, it's not fixed then
