### ISSUE TITLE
Navigating with arrow keys in list not working propertly

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#159]
When navigating through a long list (emails or contacts) by holding down the up or down arrow key the navigation stops after a while and the selected element can't be changed anymore by an additional key press.

**Comment by asteintutao** [comment]
i had a look into it and it happens because the browser starts throttling and the url is not set anymore can be a problem because setUrl is called to often in a short period

**Comment by charlag** [comment]
Duplicate of #666
