### ISSUE TITLE
Default alarm for calendar events

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1591]
It is convenient to have default alarm for calendar events.

Proposed scenario:
0. You set default alarm in calendar settings
1. You open even creation
2. There's an alarm set
3. You can change it if you like

We should take care of old alarms because in this case there would be many of them.

**Comment by Mr-Raian** [comment]
Is there any plan to implement it? 
I think it is crucial to have the default calendar event settings, nowadays every time I create an event I have to change the settings to my liking (reminders before the event, choose the calendar...).

**Comment by ajrio** [comment]
I agree, this is a much desired feature.  Maybe the option to have multiple default alarm settings.

**Comment by charlag** [comment]
After building a prototype there are few points we should address before implementing:

 1. Which instance should it be stored on? It should be a per-user entity
 2. How should the event editor behave? If you open the event editor and change the calendar,  should we change the alarm? Should it depend on whether it is manually changed?

**Comment by wrdhub** [comment]
Made a duplicate (#7216 ), is tracked there.
