### ISSUE TITLE
The new dark theme is rough on the eyes

### ISSUE THREAD

**Issue by ryanpcmcquen** [tutao/tutanota#1593]
Is there any way to leave the old dark theme as a third option? I _strongly_ prefer the original dark theme.

**Comment by charlag** [comment]
We would strongly prefer to avoid having the third theme. Is there anything we could improve in the new dark theme?

**Comment by snaggen** [comment]
Just updated the android app, and on my phone the green is very saturated and bright. Almost like staring in to a light source. It doesn't harmonize well with the other tones, it pops out a little to much.

**Comment by charlag** [comment]
We switched from "#00FFCA" to "#00f9c5" which is milder before the release.
Feel free to propose a better color but keep contrast in mind.

**Comment by snaggen** [comment]
Ok, looking at https://color.review/ the original color have a contrast of 16.1, while the new color have a contrast of 15.3
They state that "AAA requires 7 for text. For headlines and large text the minimum is 4.5.", which I intepret as a contrast of 15-16 is HIGH... so it is not very strange that my first impression was staring in to a light source. 
Using that site, I just toned it down to a contrast of 10 which is still high, but should feel a lot more comfortable. I then get the color value "#00CBA1". 
Now, all my tests were done against a black background, so it should of course be tested against the correct backgrounds and viewed on different devices and sizes.

**Comment by snaggen** [comment]
Looked att the code and it looks like the dark_lighter is "#232323" which makes the color "#00CBA1" have a contrast score of 7.5, which still qualifies for the stricter standard. 
I do not know where the dark_lightest is used, but I didn't see that as a background to the green color so I'm not sure if that is relevant. To have that qualify for AAA, the current green is needed. If so I suggest you use multiple version of the green contrast color.

**Comment by charlag** [comment]
Search in theme.js, all usages are local.
dark_lightest is not used against contrast I think. Your option doesn't look too bad, I would brighten it just a little bit maybe because time in the mail viewer is noticeably harder to read but otherwise it seems fine to me. Thanks.

**Comment by snaggen** [comment]
Took another look and "#00D2A7" is a hint lighter with a contrast of 8 against dark_lighter.

**Comment by ryanpcmcquen** [comment]
Something I loved about the original dark theme, was the use of a grey background instead of a black background. It made the contrast much subtler and less like staring into bright lights.

**Comment by ryanpcmcquen** [comment]
To be honest, the original theme was my favorite dark theme of any app or website I have ever used. I wouldn't change anything about it.

**Comment by charlag** [comment]
@snaggen nice, willing to send a pull request?

@ryanpcmcquen you can still have any theme you want with Whitelabel or with building the app on your own. It's really hard to please everyone with such things and the most dark themes I see around are about as dark - as well as guides https://material.io/design/color/dark-theme.html

**Comment by snaggen** [comment]
I have created a pull request, but I do not have a full dev environment on my laptop so I haven't been able to build and test it on my phone and desktop.
