### ISSUE TITLE
Pinch zoom for iOS

### ISSUE THREAD

**Issue by onelin88** [tutao/tutanota#1595]
**Bug in mobile app**
I know it's possible to zoom in the Tutanota app by double-tapping an area and navigating around but would it be possible to add pinch zoom?

**Describe the bug**
Only 1 level of zoom at the moment.

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: 13.2

**Comment by charlag** [comment]
We do not accept feature requests here
