### ISSUE TITLE
AppImage doesn't create .desktop files

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1602]
There were multiple reports that after starting the app no menu entries are added.
See https://www.reddit.com/r/tutanota/comments/drxl4j/appimage_on_linux_is_unable_to_create_menu_entries/

**Comment by ganthern** [comment]
https://www.electron.build/configuration/appimage

**Comment by bedhub** [comment]
target folder for icons is not created:

Error message: ENOENT: no such file or directory, copyfile '/tmp/.mount_tutano3UDDSR/resources/icons/logo-solo-red.png' -> '/home/<username>/.local/share/icons/hicolor/512x512/apps/tutanota-desktop-test.png'
Stacktrace:
Error: ENOENT: no such file or directory, copyfile '/tmp/.mount_tutano3UDDSR/resources/icons/logo-solo-red.png' -> '/home/<username>/.local/share/icons/hicolor/512x512/apps/tutanota-desktop-test.png'
