### ISSUE TITLE
save zoom factor alongside window dimensions and restore for new windows

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1611]

**Comment by charlag** [comment]
Tried it on Linux with existing installation, it didn't save the zoom factor after the restart

**Comment by charlag** [comment]
Incorrect testing, seems like it is saved after all.

**Comment by marcosdiasalves** [comment]
Facing this bug with MacOS desktop app v.3.122.5. When I open a new windows the zoom level is reset.
