### ISSUE TITLE
app hangs when cancelling printing of an email

### ISSUE THREAD

**Issue by cgalvarez** [tutao/tutanota#1612]
**Describe the bug**
The app hangs if you try to print an email but then you cancel the operating system dialog that opens (without printing).

**To Reproduce**
1. Open any email.
2. Click on '... >> Print'.
3. When the printing dialog appears, click on button 'Cancel'.
4. The app hangs.

**Expected behavior**
The app should not hang and be operative. You can't click anything, even the buttons of the dropdown menu that still shows, belonging to the '...' button.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Linux
 - Desktop Environment: LUbuntu
 - Version: Eoan Ermine 19.10

**Additional context**
Linux desktop client tested on LUbuntu Eoan Ermine 19.10.

**Comment by charlag** [comment]
Could you please specify the browser which you test with?

**Comment by cgalvarez** [comment]
@charlag I tested the desktop client (the Linux AppImage), not the web one :)

**Comment by ganthern** [comment]
Currently not reproducible with Tutanota 3.64.2 and Lubuntu 19.10.

**Comment by charlag** [comment]
I think it should already be fixed, it was probably the same as #1763
