### ISSUE TITLE
Only able to accept login from other devices, no 2FA prompt on login

### ISSUE THREAD

**Issue by xetch** [tutao/tutanota#162]
After enabling 2FA on my account (using a Yubikey NEO), I am no longer able to log in and am locked out of my account now unless I accept the login from other devices (which I'm not logged in on any device or if I am, it's a ghost session) and I am never prompted for any 2FA code or insert key message, nothing. While I anxiously wait for a response from the tutanota team, my curiosity begs the question; is this the intended and default behavior of the 2FA support in tutanota? What's the point in adding my Yubikey if I am just gonna have to accept the login on another logged in device when logged into multiple sessions (mobile, desktop, etc)?

Just in case... I'm using mail.tutanota.com (beta client).

https://tutanota.uservoice.com/knowledgebase/articles/1201942-how-does-two-factor-authentication-2fa-work-in-t wasn't much help.

**Comment by mpfau** [comment]
@xetch What was the problem?
