### ISSUE TITLE
Date Picker Circles Not Centered on Mobile

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#1624]
**Bug in mobile app**

**Describe the bug**

The circles for selecting dates on the calendar date picker aren't properly centered on mobile.

**To Reproduce**

1. Go to 'Calendar'
2. Click on the circle + icon to add an event
3. Select the date picker
4. Circles will be off on the dates

**Expected behavior**

Date should be centered in circle.

**Screenshots**

Here's an example of the issue:

![tuta-screenshot](https://user-images.githubusercontent.com/45246438/68874584-73432a80-06cf-11ea-8e13-c179b274dc33.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 13.2.2
 - Version 3.60.15

**Comment by charlag** [comment]
Thanks for reporting!
