### ISSUE TITLE
Visual Issues on Login Page

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#1625]
**Bug in mobile app**

**Describe the bug**

There are visual inconsistencies/issues on the screen shown when logging into the Tutanota app (mobile + desktop).

The blue/green bar should probably be the same width as the grey box for visual consistency.

The grey box covers the text behind it.

**To Reproduce**

1. Completely close out of app
2. Open app
3. Wait for it to login 

**Expected behavior**

The blue/green box should be the same width as the grey box for consistency.

Grey box should not cover the text behind it.

**Screenshots**

Mobile:

![login-screen](https://user-images.githubusercontent.com/45246438/68875490-ebf6b680-06d0-11ea-9019-b3266bfaa009.png)

**Smartphone (please complete the following information):**

 - Device: iPhone
 - OS: 13.2.2
 - Version 3.60.15 

**Additional context**

Issues with login screen also appear on desktop.

**Comment by charlag** [comment]
Hi
I'm not really sure they should be - they in the different layers after all

**Comment by bobmatyas** [comment]
I thought I'd report it just because it seemed inconsistent with the boxes being a different width and the text underneath being partly visible.

I couldn't tell that they were supposed to be different layers, it doesn't feel like there are any visual indication of that. 

I thought it would look and feel more consistent if the boxes were the same width and the text underneath wasn't partially visible.

**Comment by charlag** [comment]
I don't think this is an issue really, it's a dialog which resides in the higher overlay layer, it's the same for all other progress dialogs (which I'm not a fan of in some situations)
