### ISSUE TITLE
Unadvertised or invisible filtering rules ?

### ISSUE THREAD

**Issue by Ra0EL** [tutao/tutanota#1626]
- [X] This is not a feature request. I will request features on the forum or via support (see [contact page](https://tutanota.com/contact?page=feature)).
- [X] This issue doesn't fit into provided templates.

-----

Hello team,

it seems I cannot receive any email from Turtl Community (Turtl is a tool available at <http://turtlapp.com>). Is this filtered in some way on your side (blacklist, etc.) ?  
I have no issue to send or receive any email from any domain but theirs.

Any insight would be appreciated.
Regards.

**Comment by charlag** [comment]
Please contact support for such cases. We can see that emails for turtlapp are delivered. If you will contact support, please include the email domain they are using (if you know it).
