### ISSUE TITLE
[IOS] Change app which is used to open links

### ISSUE THREAD

**Issue by nikobockerman** [tutao/tutanota#1627]
**Bug in mobile app**
Feature request to allow changing the application used to open web links to be something else than Safari.

**Describe the bug**
I don't use Safari as my main browser my iPad. It would be great if Tutanota would have a setting through which I could select the application that Tutanota launches when I click a link in an email. 

Since iOS/iPadOS doesn't allow user to change default web browser, many applications have app specific setting to allow user to change which web browser is used to open links from the application.

I use Firefox in my iPad. It would be great to be able to open links directly in Firefox instead of having to open them first in Safari and then reopening them in Firefox.

**To Reproduce**
1. Open email with a link to a web page
2. Click on the link
3. See that the web page is opened in Safari

**Expected behavior**
Link is opened in the browser user wants. In my case that would be Firefox.

**Smartphone (please complete the following information):**
 - Device: Ipad Mini 5th generation
 - OS: iPadOS 13.2.2
 - Version 3.60.15

**Comment by charlag** [comment]
@nikobockerman hi. We don't accept feature requests here, sorry. 

Although this issue made me realise that there's *no way to change default browser on iOS*. This is horrible anti-competitive behaviour by Apple. We even changed it to open webpages not in the pop-up window but in the browser and I thought we did it for this reason. We will look into that.

**Comment by nikobockerman** [comment]
No problem. I realized your policy regarding feature requests only after I had created this ticket. After that I also sent an email to support regarding this feature request.

Thanks for looking into this anyway!

**Comment by nikobockerman** [comment]
In case someone still finds their way to this ticket: with iOS 14 and iPadOS 14 the system default browser can finally be changed and Tutanota does the correct thing regarding that setting and opens links in the specified system default browser. So this feature request wouldn't even be needed anymore with iOS/iPadOS 14.
