### ISSUE TITLE
Cannot use the Android back button to go back to inbox when a mail is open on mobile

### ISSUE THREAD

**Issue by szaimen** [tutao/tutanota#1628]
**Bug in web app**

**Describe the bug**
Cannot use the Android back button to go back to inbox when a mail is open on mobile

**To Reproduce**
1. Login to my tutanota account
2. Click on a mail inside the inbox to open it
3. Press Android back button (to go back to inbox)
4. Nothing happens

**Expected behavior**
It should go back to the inbox when pressing the Android back button while a mail is open.

**Screenshots**
I am talking about this button back button:
![sketch1574118012702](https://user-images.githubusercontent.com/42591237/69101319-a1be5e00-0a5f-11ea-9ff5-970a0a3efb71.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - OS: Android 10
 - Browser: Chromium based Browser
 - Version: 78

**Additional context**
The same behavior applies to the left side menu. But on the right side menu it just works.

**Comment by charlag** [comment]
@szaimen 
hi
sorry, I could not reproduce it? Just downloaded the app, logged in, opened email, went back successfully. It might depend on the left menu somehow? Would be nice if you could record a video and send it to hello@tutao.de (maybe comment here when you do)

**Comment by szaimen** [comment]
Thanks for the reply. 
Actually it is working in the android app but not in the webapp so if you login with a mobile chromium based browser on https://mail.tutanota.com

**Comment by charlag** [comment]
Ok, thanks for the clarification. I checked and indeed it doesn't but I don't think that we have to fix it right now as there are navigation buttons inside the app. We may improve it later.

**Comment by szaimen** [comment]
Why not leaving the issue open when this isn't working yet?

**Comment by charlag** [comment]
Because I'm not sure we will invest into fixing it (or rather I'm almost sure we won't in foreseeable future).

**Comment by szaimen** [comment]
Hm 😕
