### ISSUE TITLE
Show different envelope sender for same domain

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1630]
Currently we only show the warning symbol and the envelope sender address if it has a different domain than the header sender address. In order to detect more phishing emails we now also want to show it if the domain is the same.

**Comment by 4jNsY6fCVqZv** [comment]
@armhub Thanks for working on this! Could you please document both improvements in a screenshot?

**Comment by armhub** [comment]
Fixed in 45a7873c.

**Comment by armhub** [comment]
Sorry, I won't create screenshots. You can see it in Tutanota.

**Comment by 4jNsY6fCVqZv** [comment]
The "problem" (and also my luck) in this case is, I don't get such mails under Tutanota, so I have a hard time looking changes up. But I want to understand the feature. Maybe you can document it in your manual?

**Comment by armhub** [comment]
It is documented here: https://tutanota.com/howto/#login (at the bottom). However, there is no screenshot. But you will see a warning symbol right next to the sender address in this case.

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for the hint!

> If the technical sender is different from the header info, Tutanota warns you about this. The differing sender information could be a sign that this mail is coming from a scammer.

But this documentation doesn't include the improvements of this issue yet, because several things are checked now, right?

**Comment by armhub** [comment]
Yes, but the changes are documented above.

**Comment by 4jNsY6fCVqZv** [comment]
thanks again!
