### ISSUE TITLE
Adding inline images in two batches will not send the first batch correctly

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1632]
**To Reproduce**
1. Write a new mail
2. Attach couple of inline images (in the editor bar, not as files)
3. Attach some more
4. Send email

**Expected behavior**
All images are sent. Instead, only the second batch is sent

**Comment by charlag** [comment]
Could not reproduce it now

**Comment by brshub** [comment]
All images are displayed correctly when sent.
