### ISSUE TITLE
No confirmation dialog when removing participant from calendar

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1635]

**Comment by vitoreiji** [comment]
Are you sure you can remove *yourself*? I could not reproduce this.

But yes, removing others has no confirmation dialog. Do you really think we need one?

**Comment by armhub** [comment]
Yes, you can remove yourself if the calendar was shared with you.

I think we definitely need a confirmation dialog. Removing someone from a group is a major operation which will also e.g. include deleting your local search index for that group, so we should make sure this does not happen by accident.

**Comment by charlag** [comment]
fixed by c8ba684

**Comment by mpfau** [comment]
There is still no confirmation dialog if you remove yourself from the calendar. The confirmation dialog when removing a participant is displayed correctly, now.

**Comment by vitoreiji** [comment]
Not quite, the confirmation dialog is displayed when removing an invitation, but not a participant.
