### ISSUE TITLE
Creating a new event in the day/week/month view should use the first day of that view for the event

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1642]
Currently the last selected day is used which is weird if it is not visible in the view.

**Comment by charlag** [comment]
@armhub it always uses current date, not selected date

**Comment by vitoreiji** [comment]
If the first day in the view is in the past, than continue using current date.

**Comment by armhub** [comment]
There are a couple of issues visible when testing:
* The day view can not be shown because of #1899
* In week view the day of the URL is used instead of the first day in the view.
* If the current day is in the view, that day is not used. -> We should use the current day in this case.
