### ISSUE TITLE
'cannot read stopPropagation of null' when pressing Cmd+Left on Mac in the mail editor

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#1652]
related: #1645 , #1622

**Comment by ganthern** [comment]
a949163abcac113210d511818d4aa1afa696b645 prevents the main thread from causing history changes before the editor hat a chance to see `Cmd+Arrow`

7a645c4dfbe54ea699a5ef0da3f98ad0f561ec09 fixes the other cases of the click handler not being passed an event

**Comment by charlag** [comment]
It doesn't close mail editor anymore but it doesn't travel back in history either
