### ISSUE TITLE
accent insensitive word search

### ISSUE THREAD

**Issue by tukiab** [tutao/tutanota#1653]
when i make a search, is it possible to do a case insensitive word search?
sometimes the word is written with accent, but other times is not, and it's important to find both cases at the same time, especially when we can't find results that contain the query as a substring.

**Comment by charlag** [comment]
Hi
currently it's not possible.I guess it would be possible. I will discuss it with others, maybe it was the intent.
I'm not sure we should strip out accents because i's hard to do right.

**Comment by charlag** [comment]
It is not planned to do text processing besides stripping HTML as of now
