### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1654]
Some users complain that the system notification does not go away for minutes. Logs suggest that the problem is in this stacktrace:

```
-26 04:33:18.657 16099 16099 E AndroidRuntime: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11-26 04:33:18.657 16099 16099 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Except that we do call `startForegroundService()` but only in `onCreate()`. My guess is that we `stopForeground()` at some point and than we don't start it again when we get another start command. We should probably do `startForeground()` each time in the start

### Test Notes
 * [ ] test that we still get notifications for mail
 * [ ] notifications for calendar events
 * [ ] notifications open the mailbox when clicked
 * [ ] make sure turning off notifications for tutanota in the android settings works (try different combinations of the channels)

**Comment by ganthern** [comment]
Note: This is currently responsible for 90% of our Crashes and ANRs
