### ISSUE TITLE
Single whole day calendar entry shown on two days

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1655]
How to reproduce:
* Create a whole day event for the 6th of December in agenda view.
Result:
* The agenda shows that event on the 5th and 6th of December
* The monthly view shows the event on the 5th of December
* When opening the event it is only for the 5th of December
* When deleting the event both events disappear from the agenda view.

**Comment by charlag** [comment]
Could not reproduce it easily. There must be a special condition.

**Comment by armhub** [comment]
This issue was accompanied by the strange behavior that all times shown in the agenda view were one our too late in comparison to the times shown when editing the event.

After restarting the device everything is fine again. I will close this issue until we stumble upon it again and have it reproducible.
