### ISSUE TITLE
Rename sharing feature to collaboration feature

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1667]

**Comment by hahub** [comment]
For simplicity I'd call it: Collaboration

**Comment by charlag** [comment]
@armhub @hahub should I change it in Phrase?

**Comment by armhub** [comment]
Sure! Just consider where we should call it "collaboration" or "collaboration feature". And we need to decide on a German term.

**Comment by armhub** [comment]
We decided to keep the name "collaboration feature" resp. "Freigabe-Funktion"
