### ISSUE TITLE
Duplicate calendar entry

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1668]
> Add All day entry, eg. 11.12.2019 - 13.12.2019
> Edit entry
> Change date eg. 11.12.2019 - 11.12.2019
> Save changes
> Entry will duplicate
> After delete duplicate primary entry will also delete
> No profit

**Comment by charlag** [comment]
There must be another event on the 11th (of the example) to reproduce it, works with just any non-all-day event (because it's "after" all-day one).

**Comment by vitoreiji** [comment]
The events are no longer duplicated, but the dates shown in the Edit dialog are wrong (one day before).

**Comment by charlag** [comment]
@vitoreiji it seems to be because of the broken formats in this release
