### ISSUE TITLE
UI layout improvement

### ISSUE THREAD

**Issue by Gaspacchio** [tutao/tutanota#1675]
**Bug in web app**

**Describe the bug**
I really love the new ui layout that you just introduced in release 3.66.2 😍. The bottom left menu is a real improvement. However, while trying it out, I was surprised by the fact that you can access the setting page via this new menu **but you can't go to mail view from the same location**. It's really confusing to have to change focus from **bottom left** to **top right** to switch from setting to mail view.

**To Reproduce**
1. Go to the mail view
2. Click on the bottom left gear icon
3. See UI layout confusion

**Expected behavior**
Add a link to mail view in the new bottom left menu.

**Screenshots**
![Screenshot_2019-12-13 gaspard bariller tutanota com - Tutanota](https://user-images.githubusercontent.com/43613824/70791599-abee2680-1d97-11ea-86d7-833fd2ebcbd5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 71.0

**Additional context**
Thanks for this big UI update, really love it!

**Comment by charlag** [comment]
HI
Glad that you loved the update.
The motivation behind this is that settings is not a commonly used part of the app - it is something like a temporal, modal thing. We wanted to add a "back" button so you can back from the settings to the part of the app you are in but we didn't manage to do it in this release.

Try mobile layout - I hope it will make much more sense why it is structured like that now.

**Comment by Gaspacchio** [comment]
Nice, it was the other suggestion I did not write, thinking it would be harder to implement. Hope to see this feature released one day.

Indeed, the new mobile layout makes a lot of sense. I really think you're on the right track to get it just right!
