### ISSUE TITLE
Delete account if not used in X time.

### ISSUE THREAD

**Issue by gillerby** [tutao/tutanota#1680]
Consider adding an option for the account to be deleted if it is not accessed in X time, with X being 30 days, 90 days, 6 months, or 1 year, for example, so the user can choose.

**Comment by gillerby** [comment]
It's not a bug, don't know why it added it. Sorry.

**Comment by ganthern** [comment]
This also doesn't look like a desktop issue. 

Please reserve the use of this tracker to bug reports and read the README.md on the main page of the repository to find out where you can discuss feature requests.
