### ISSUE TITLE
App doesn't run in tray on Gnome 3.34.2/KStatusNotifierItem

### ISSUE THREAD

**Issue by DanielValahul** [tutao/tutanota#1682]
**Describe the bug**
The app should run in the tray, just as it is configured in its settings. Other apps work fine, for example, Qbitorrent and Steam. Tutanota worked fine on a previous install using this setup too, but I had to reinstall my distro. (Fedora 31)

**To Reproduce**
Steps to reproduce the behavior (On fedora 31):
1. Go to https://extensions.gnome.org/extension/615/appindicator-support/
2. Switch it on
3. Tutanota won't close to tray, or when set to run at startup wont show up in the tray

**Desktop (please complete the following information):**
- Fedora 31
- Gnome 3.34.2

**Comment by charlag** [comment]
Hi
I think Gnome dropped support for tray icons and you need to install extension for that (I think it ships with some distros). The app still runs in background but you don't have tray icon currently.

**Comment by DanielValahul** [comment]
I allready installed the extension, however it seems that tutanota doesn't show up. Steam and qbitorrent both work ok in that they minimize to tray

**Comment by charlag** [comment]
Hi again
To be honest I'm not sure if we can do something about it. It might be fixed by Electron in future releases.
As far as I understand it still runs in background/can reopen your window where you left it but doesn't show the tray icon? Without additional debug info we can't do much.

**Comment by DanielValahul** [comment]
Yes that's all. To be honest it's not a big loss, just that sometimes its more convenient to open it from tray

**Comment by DanielValahul** [comment]
Well out of nowhere it just popped up again.  So it appears to be fine now

**Comment by charlag** [comment]
Well, glad it's fixed
