### ISSUE TITLE
Desktop  application does not recognize zoom factor after restart of computer

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1683]
reported by user. 

"Modify zoom factor of desktop application. The same zoom factor is used when app is closed and opened again but when restarting the device the zoom factor is not restored"

Reported on Mac OS X 10_15_2 

desktop/3.66.2 Chrome/78.0.3904.126 Electron/7.1.3

**Comment by ganthern** [comment]
Upon further inspection, Windows that got their zoom factor set automatically from the config file will not correctly report that zoom factor on being closed, therefore saving a "1" to that field in the config.
