### ISSUE TITLE
Windows (re-)installation aborted

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1686]
> Currently I'm trying to install Desktop version v3.66.2.
When I push the installation file I dopnwladed from the website, the installation starts, but I always get message "Installation Aborted" and it keeps showing that (see attachtment).
![installation aborted](https://user-images.githubusercontent.com/8296817/71088438-b5fc9480-219e-11ea-81ad-3bfd82806650.png)

**Comment by bedhub** [comment]
We are able to reproduce this if there is an existing registry entry pointing to the Uninstaller of an previous installation but the Uninstaller has already been removed.

**Comment by charlag** [comment]
electron-builder changed uninstaller registry key format in https://github.com/electron-userland/electron-builder/commit/7518aee8e1abe0516071b350748e84dc47e35cf7 (v21.1.3).

So the situation is following:
1. v3.60 (or so) creates an registry key `UUID`
2. v3.64 has changed format and uses a registry key `{UUID}`.
3. User uninstalls 3.64. It will delete uninstaller file and registry key `{UUID}` but not `UUID`.
4. We try to install new version which (again) uses key `UUID`. It finds registry key `UUID` and tries to run installer, which is not there anymore.

Note that we couldn't reproduce it purely with upgrades. We could only reproduce it by uninstalling v3.64 manually.

We probably should use one of the NSIS scripts to fix it, either https://github.com/electron-userland/electron-builder/pull/4443#issuecomment-562962960 or something like https://github.com/electron-userland/electron-builder/issues/4092#issuecomment-549735046. Basically we would need to check if there's a registry entry for the new format but no uninstaller file and we should delete registry entry in this case. Users probably cannot fix this on their own.
