### ISSUE TITLE
Impossible set up language from "Automatic" to "English" permanently

### ISSUE THREAD

**Issue by Aneyrin** [tutao/tutanota#1692]
**Impossible set up language from "Automatic" to "English" permanently**

**After next log in Tutanota web app sets language to Automatic**

**To Reproduce**
1. Log in to Tutanota web app
2. Click on 'Appearance.'
3. Scroll down language to '.English' and log out
4. Open your Browser in Private Mode and log in again

**Expected behavior**
Language setting must be set permanently for future logins.

**Comment by charlag** [comment]
The language setting is saved on the device so in incognito it's obviously not available.
