### ISSUE TITLE
Inbox rules for folders issue on Tutanota server side

### ISSUE THREAD

**Issue by Aneyrin** [tutao/tutanota#1693]
**Bug in web app**

**Describe the bug**
Inbox rules for folders don't work on Tutanota server side. Inbox rules working only after you log in in Tutanota web/mobile app

**To Reproduce**
1. Go to 'Inbox rules settings'
2. Set field 'To recepient'
3. Set value to 'any non-tutanota email ID (like example@gmail.com)'. And set up example@gmail.com to redirect all emails to Tutanota email.
4. Set Target folder to EXAMPLE
5. Send email to added email ID (example@gmail.com)
6. Log out from Tutanota
7. Log in to Tutanota
8. You will see email for recipient example@gmail.com in INBOX folder for few seconds but in few secs web/mobile app will put it to EXAMPLE folder according previously added rule

**Expected behavior**
Emails must be stored in destination folder according folder rules. It must work on server side to prevent unnecessary notifications about new email in INBOX.

**Additional context**
Because of this problem you will see undesirable notification about new INBOX email in mobile app. Email will be moved from INBOX to destination folder after mobile app is opened.

**Comment by charlag** [comment]
@Aneyrin no it must not work on the server. We don't have access to most of the encrypted mail content on the server so inbox rules cannot be applied on the server side.
Spam rules on the other hand run on the server and you won't get a notification. Check Global settings.
