### ISSUE TITLE
Application displays error dialog all the time

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#1704]
### Describe the bug

After I open up the application, I always see a dialog to send an error report...and it keeps showing up after every click. I sent it twice to support, but it looks like it's something they don't deal with (I haven't received any response).

> It's been a while (like two / three weeks) since I have this one, but I didn't want to create an issue here thinking that it will go away between releases, because you know, bugs happens...and I was also waiting for support to come back.

### To Reproduce

Steps to reproduce the behavior: N/A

### Expected behavior

There shouldn't be any error message(s).

### Screenshots

![image](https://user-images.githubusercontent.com/34633617/71424439-7c74cf00-265f-11ea-8d0e-80dde3da7bde.png)

### Desktop (please complete the following information):

 - OS: `Linux uplink 4.19.91-1-lts #1 SMP Sat, 21 Dec 2019 16:34:46 +0000 x86_64 GNU/Linux`
 - Browser: `Firefox`
 - Version: `71.0 (64-bit)`

**Comment by charlag** [comment]
Weird, something with database, can you try to disable search index and enable it again?

**Comment by x80486** [comment]
Just tried that: `Settings` > `Email` > `Search mailbox`; turn it to `Activated` and then back to `Deactivated` again. Log out, clear "everything" on the browser...repeated the same operation(s) within `Firefox`.

Finally, I tried with `Opera 65.0.3467.69` and `Chromium 79.0.3945.88`...same thing.

**Comment by charlag** [comment]
This is super weird, maybe you could try sending a log?
It's holiday time so I don't know when we'll get to this. It doesn't happen to us so maybe it's some data on your account that uncovers the error. Sorry about this. Hope you can use the app sometime. Do you remember when it started?

**Comment by x80486** [comment]
I'm aware that it might be something on my side, but I've tested it already in several browsers...not sure what else to try. The web application is completely unusable right now, though it works fine on the mobile.

I sent the first email to support on **December 14th**, so I guess it started about the week before to that date. I can delete and recreate the account if needed. This was the error message at that time:

```shell
Client: Browser
Type: PREMIUM
Tutanota version: 3.66.2
Timestamp (UTC): Sat, 14 Dec 2019 14:44:59 GMT
User agent:
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0
DbError
Error message: IndexedDbTransaction put().onerror SearchIndexMeta
OSes: {"0":"ElementData","1":"GroupMetaData","2":"MetaData","3":"SearchIndex","4":"SearchIndexMeta"}
event:{"isTrusted":true,"type":"error","target":{},"srcElement":{},"currentTarget":{},"eventPhase":2,"bubbles":true,"cancelable":true,"returnValue":true,"defaultPrevented":false,"composed":false,"timeStamp":38510,"cancelBubble":false,"originalTarget":{},"explicitOriginalTarget":{},"NONE":0,"CAPTURING_PHASE":1,"AT_TARGET":2,"BUBBLING_PHASE":3,"ALT_MASK":1,"CONTROL_MASK":2,"SHIFT_MASK":4,"META_MASK":8}
transaction.error:
event.target: {"error":{},"source":{},"transaction":{},"readyState":"done"}
event.target.error: {"name":"ConstraintError","message":"A mutation operation in the transaction failed because a constraint was not satisfied.","code":0,"result":2154168324,"filename":"","lineNumber":0,"columnNumber":0,"stack":"","INDEX_SIZE_ERR":1,"DOMSTRING_SIZE_ERR":2,"HIERARCHY_REQUEST_ERR":3,"WRONG_DOCUMENT_ERR":4,"INVALID_CHARACTER_ERR":5,"NO_DATA_ALLOWED_ERR":6,"NO_MODIFICATION_ALLOWED_ERR":7,"NOT_FOUND_ERR":8,"NOT_SUPPORTED_ERR":9,"INUSE_ATTRIBUTE_ERR":10,"INVALID_STATE_ERR":11,"SYNTAX_ERR":12,"INVALID_MODIFICATION_ERR":13,"NAMESPACE_ERR":14,"INVALID_ACCESS_ERR":15,"VALIDATION_ERR":16,"TYPE_MISMATCH_ERR":17,"SECURITY_ERR":18,"NETWORK_ERR":19,"ABORT_ERR":20,"URL_MISMATCH_ERR":21,"QUOTA_EXCEEDED_ERR":22,"TIMEOUT_ERR":23,"INVALID_NODE_TYPE_ERR":24,"DATA_CLONE_ERR":25}
custom.target: {"error":{},"source":{},"transaction":{},"readyState":"done"}
custom.target.error: {"name":"ConstraintError","message":"A mutation operation in the transaction failed because a constraint was not satisfied.","code":0,"result":2154168324,"filename":"","lineNumber":0,"columnNumber":0,"stack":"","INDEX_SIZE_ERR":1,"DOMSTRING_SIZE_ERR":2,"HIERARCHY_REQUEST_ERR":3,"WRONG_DOCUMENT_ERR":4,"INVALID_CHARACTER_ERR":5,"NO_DATA_ALLOWED_ERR":6,"NO_MODIFICATION_ALLOWED_ERR":7,"NOT_FOUND_ERR":8,"NOT_SUPPORTED_ERR":9,"INUSE_ATTRIBUTE_ERR":10,"INVALID_STATE_ERR":11,"SYNTAX_ERR":12,"INVALID_MODIFICATION_ERR":13,"NAMESPACE_ERR":14,"INVALID_ACCESS_ERR":15,"VALIDATION_ERR":16,"TYPE_MISMATCH_ERR":17,"SECURITY_ERR":18,"NETWORK_ERR":19,"ABORT_ERR":20,"URL_MISMATCH_ERR":21,"QUOTA_EXCEEDED_ERR":22,"TIMEOUT_ERR":23,"INVALID_NODE_TYPE_ERR":24,"DATA_CLONE_ERR":25}
Stacktrace:
DbError. IndexedDbTransaction put().onerror SearchIndexMeta
OSes: {"0":"ElementData","1":"GroupMetaData","2":"MetaData","3":"SearchIndex","4":"SearchIndexMeta"}
event:{"isTrusted":true,"type":"error","target":{},"srcElement":{},"currentTarget":{},"eventPhase":2,"bubbles":true,"cancelable":true,"returnValue":true,"defaultPrevented":false,"composed":false,"timeStamp":38510,"cancelBubble":false,"originalTarget":{},"explicitOriginalTarget":{},"NONE":0,"CAPTURING_PHASE":1,"AT_TARGET":2,"BUBBLING_PHASE":3,"ALT_MASK":1,"CONTROL_MASK":2,"SHIFT_MASK":4,"META_MASK":8}
transaction.error:
event.target: {"error":{},"source":{},"transaction":{},"readyState":"done"}
event.target.error: {"name":"ConstraintError","message":"A mutation operation in the transaction failed because a constraint was not satisfied.","code":0,"result":2154168324,"filename":"","lineNumber":0,"columnNumber":0,"stack":"","INDEX_SIZE_ERR":1,"DOMSTRING_SIZE_ERR":2,"HIERARCHY_REQUEST_ERR":3,"WRONG_DOCUMENT_ERR":4,"INVALID_CHARACTER_ERR":5,"NO_DATA_ALLOWED_ERR":6,"NO_MODIFICATION_ALLOWED_ERR":7,"NOT_FOUND_ERR":8,"NOT_SUPPORTED_ERR":9,"INUSE_ATTRIBUTE_ERR":10,"INVALID_STATE_ERR":11,"SYNTAX_ERR":12,"INVALID_MODIFICATION_ERR":13,"NAMESPACE_ERR":14,"INVALID_ACCESS_ERR":15,"VALIDATION_ERR":16,"TYPE_MISMATCH_ERR":17,"SECURITY_ERR":18,"NETWORK_ERR":19,"ABORT_ERR":20,"URL_MISMATCH_ERR":21,"QUOTA_EXCEEDED_ERR":22,"TIMEOUT_ERR":23,"INVALID_NODE_TYPE_ERR":24,"DATA_CLONE_ERR":25}
custom.target: {"error":{},"source":{},"transaction":{},"readyState":"done"}
custom.target.error: {"name":"ConstraintError","message":"A mutation operation in the transaction failed because a constraint was not satisfied.","code":0,"result":2154168324,"filename":"","lineNumber":0,"columnNumber":0,"stack":"","INDEX_SIZE_ERR":1,"DOMSTRING_SIZE_ERR":2,"HIERARCHY_REQUEST_ERR":3,"WRONG_DOCUMENT_ERR":4,"INVALID_CHARACTER_ERR":5,"NO_DATA_ALLOWED_ERR":6,"NO_MODIFICATION_ALLOWED_ERR":7,"NOT_FOUND_ERR":8,"NOT_SUPPORTED_ERR":9,"INUSE_ATTRIBUTE_ERR":10,"INVALID_STATE_ERR":11,"SYNTAX_ERR":12,"INVALID_MODIFICATION_ERR":13,"NAMESPACE_ERR":14,"INVALID_ACCESS_ERR":15,"VALIDATION_ERR":16,"TYPE_MISMATCH_ERR":17,"SECURITY_ERR":18,"NETWORK_ERR":19,"ABORT_ERR":20,"URL_MISMATCH_ERR":21,"QUOTA_EXCEEDED_ERR":22,"TIMEOUT_ERR":23,"INVALID_NODE_TYPE_ERR":24,"DATA_CLONE_ERR":25}
DbError@https://mail.tutanota.com/common.js:1:259991
value@https://mail.tutanota.com/worker.js:1:432846
value/
```

**Comment by charlag** [comment]
@x80486 there's no need to delete account for sure. Do you create a search index before this error appears or it is just after logging in?
Would also be nice if you gave me some marker to find email in support.

**Comment by x80486** [comment]
I actually never created the **search index**, just the first time it was released (and now again to test this), but since I don't use the "search functionality" it's always disabled.

Are you sure this issue is related with that functionality?

>  Would also be nice if you gave me some marker to find email in support.

I didn't get that :sweat_smile:

**Comment by charlag** [comment]
@x80486 the search index is always created, at least for contacts and users. When you disable mail indexing the database is deleted and index is created again. This is certainly a database error.

It's not trivial to find your email in support, because I don't know which one belongs to you. I need some way to identify it.

**Comment by x80486** [comment]
Hey @charlag, did you have a chance to take a look at this one? Is there anything I can do on my end? The JavaScript is _borked_; all the dynamic functionality is disabled.

**Comment by charlag** [comment]
Hi, I tried to analyze it but it's just impossible to debug it remotely. I got no leads. Did you try disabling inxexeddb completely already?

**Comment by x80486** [comment]
> Did you try disabling inxexeddb completely already?

OK, how do I do that? I can find the IndexDB entries in the **Development Tools** (Firefox), but I don't know how to disable it. If that can do the trick, I'm down for it.

**Comment by charlag** [comment]
Hi,
Sorry, I looked for it but didn't find anything yet. Before there was a way to set `dom.indexedDB.enabled` in abou:config to false

**Comment by charlag** [comment]
@x80486 can I close it or do you still experience it?
