### ISSUE TITLE
Android: Share tweet removes link

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1705]
Share a tweet by email, select Tutanota, email for editing is opended, but the link is missing in the text.

**Comment by ganthern** [comment]
seems to work in 3.98.17:
* select tweet in twitter app
* press it's share button
* share via link
* select tutanota
* tutanota opens. after login (or auto-login) it will create a mail editor and put the link in the text.
* change something and close the mail editor -> draft gets saved
* link works if viewed in the draft folder
