### ISSUE TITLE
Little wrong translation in Italian in the "about" section of the client

### ISSUE THREAD

**Issue by tGstep** [tutao/tutanota#1708]
![immagine](https://user-images.githubusercontent.com/38408500/71528669-35960c00-28e1-11ea-9fd5-3be27456c66c.png)

**_Circa_** should be replaced with _**A riguardo**_ or _**Su di noi**_

**Comment by charlag** [comment]
Please fix it on the Phraseapp:
https://tutanota.com/blog/posts/tutanota-translation-project
