### ISSUE TITLE
Receiving new mail notifications from logged out accounts

### ISSUE THREAD

**Issue by klane293** [tutao/tutanota#1709]
**Describe the bug**
I logged out of my Tutanota account, however I still get "new mail" notifications from this account.
If I click the notification, it will open the desktop app, and ask for my login credentials.

**Expected behavior**
I shouldn't receive notifications from accounts that are logged out.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by armhub** [comment]
It is intended that you receive new email notifications when you are logged out. If you do not want to receive notifications any more for a mailbox please deactivate the notifications in the mail settings.
