### ISSUE TITLE
Calendar: description field does not soft-wrap

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1716]
When the text in the description field becomes long, the text is not soft-wrapped but rather becomes scrollable. I think we need to break text on word in such case.

**Comment by charlag** [comment]
I've found out that we manually set pre-wrap and we set the heigh to the number of newlines. There might be some corner cases where we wanted this horizontal scroll behaviour instead of soft-wrapping. We probably should change it if we don't want this behaviour anywhere or we should add it as a parameter.

**Comment by charlag** [comment]
It *is* possible to wrap manually though so I'm not sure if we should change this.

**Comment by ganthern** [comment]
duplicate of https://github.com/tutao/tutanota/issues/1336
