### ISSUE TITLE
How to totally disable spam filter

### ISSUE THREAD

**Issue by guoyunhe** [tutao/tutanota#1720]
The spam filter is totally useless to me. I have tons of emails from maillists and they are all marked as spam. But when I use Outlook or Gmail, they are in inbox. However, those spam mails are in my inbox. So spam filter actually only makes my life harder... Emails are from hundreds of different addresses and I cannot whitelist everyone by hand.

It would be great to be able to disable spam filter totally. I really don't need it.

**Comment by charlag** [comment]
Hi
this is not the right place to ask questions but you can add wildcard filter (`*`) with NO SPAM

**Comment by guoyunhe** [comment]
Thanks for the tip!

**Comment by TheCrowned** [comment]
(I would still suggest reviewing how the spam filtering works, because same happens to me. I have emails from many trusted recipients all going to spam (to the point that my inbox is empty, and everything is just in spam). This way Tutanota is just useless, sorry!)
