### ISSUE TITLE
HiDPi Scaling, (fractional options within client)

### ISSUE THREAD

**Issue by jarrard** [tutao/tutanota#1722]
This isn't a bug report but a feature request. It would be nice if this client had options to adjust the interface dpi to suit 4k monitors.

**Desktop :**
 - OS: Arch Linux 
 - Desktop Environment: LXQT + xfwm4
 - Version 3.66.5

**Additional context
This feature along with ability to adjust inner window sizes and placement would be great.

**Comment by charlag** [comment]
Hi
This is not the right place for feature requests.
Could you please explain what is missing/not working for you? I think the app already respects system scaling plus you can scale with ctrl+mousewheel.

**Comment by jarrard** [comment]
Oh I didn't know about the Ctrl mouse wheel thing, lol. 

Sorry.
