### ISSUE TITLE
Support different date formats for contacts birth date

### ISSUE THREAD

**Issue by BlackEdder** [tutao/tutanota#1725]
Currently only American style date format is supported for a contacts birthdate (this might be related to default language settings?). Would it be possible to also support other formats? E.g. the official ISO 8601 format: YYYY-MM-DD

**Comment by charlag** [comment]
Hi
It depends on you browser locale (you need EN_GB or another)

**Comment by BlackEdder** [comment]
I appreciate the pointer, but the ISO 8601 format is supposed to be an international format. It would be great if it could be supported independently of browser locale.

Furthermore it is quite common to use en as browser locale even if your not in the US, especially in countries like the Netherlands where most (younger) people prefer to use English GUI over Dutch GUI.

**Comment by charlag** [comment]
Hi
Yes, ISO is international format but not so many people know about it outside of the tech circles. I'm not sure if we can always distinguish between local format and ISO. Contributions are always welcome.

I am such a person who uses English but I use UK locale to get expected time/date formats.

**Comment by MasterInQuestion** [comment]
Refer: https://github.com/orgs/community/discussions/5972#discussioncomment-10730667
    [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) API seems to handle things sensibly enough.

    Not supporting the ISO variant seems unacceptable.
    Even recognizing the various randomly defined local formats wrong: tends to be more acceptable, generally.
