### ISSUE TITLE
Mails disappear from search view when moved

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#1732]
**Describe the bug**
Mails disappear from search view when moved even though the selected "Email folder" is "All"

**To Reproduce**
1. Search some emails in all folders.
2. Select one from the results and move to a different folder.

**Expected behavior**
The email stays in the search results, with a different location.

**Actual behavior**
Email disappears from search results.

## Test Notes
* [ ] Searching for emails/contacts still working
* [ ] When an email is updated by another client, the search receive and applies the update
* [ ] Editing an email from the search works
* [ ] When an email is moved to a folder included on the search it's shown or updated
* [ ] When an email is moved to a folder excluded from the search, it's removed

**Comment by brshub** [comment]
This is still present in the desktop client version 3.84.11.

**Comment by ganthern** [comment]
still reproduces in 3.98.20
