### ISSUE TITLE
Email read via phone doesn't show on laptop.

### ISSUE THREAD

**Issue by tognbee** [tutao/tutanota#1738]
An email opened on my Android phone does not appear in the Inbox of my Win10 PC. A search on the PC finds the email but it still doesn't show in the Inbox.
Logging out, then back in, revealed the hidden email.

**Comment by charlag** [comment]
Hi
Are you sure you didn't need to scroll to the top of the email list? Are you sure network connection was fine?
It might be that downloading update has failed

**Comment by tognbee** [comment]
Absolutely certain that scrolling wasn't required. Search revealed the
message but it still wasn't in the Inbox list.
What does "... downloading update has failed" mean?

**Comment by charlag** [comment]
Maybe network issue prevented us from downloading this email? If you have an idea on how to reproduce it, please let us know.

**Comment by tognbee** [comment]
As mentioned previously, Search found the email. It just didn't show until
I closed and re-opened Tutanota.

**Comment by charlag** [comment]
Yes, downloading of email for search and for list are two different things.

**Comment by charlag** [comment]
I'm sorry but without a way to reproduce it I must close it.
