### ISSUE TITLE
The desktop application is a little hard to use

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [tutao/tutanota#1761]
**System info:**
 - OS: Linux Mint 19.3
 - Desktop Environment: Cinnamon
 - Version: 3.66.7

**Describing the issue**
There is no easy way to delete a messages in your desktop application, so I hope that you could add more features in the future to be able to select messages, then delete them, mark them as read, mark them as spam, or moving them to another folder.

**Comment by charlag** [comment]
There is a way to select multiple messages (with shift/ctrl keys) and there are buttons and shortcuts for all these actions

**Comment by ahmed-elsayed2017** [comment]
The buttons are not available at the inbox page, so I can't use them with multi selection, I can only see them after opening any messages.

Ctrl/shift works fine for selecting multi messages, and I can delete the selected messages by pressing delete from the keyboard. What are the shortcuts for the other actions?

**Comment by charlag** [comment]
I suspect that you are in mobile layout. Press F1 to check shortcuts. This is the wrong place to ask questions.
