### ISSUE TITLE
Unread notification unable to clear

### ISSUE THREAD

**Issue by stelord** [tutao/tutanota#1772]
**Bug in mobile and desktop app**

There is a repeated issue where in both the IOS app and the Linux desktop app there is an unread email notification but no unread emails.

**To Reproduce**

Unknown, irregular behaviour.

**Expected behavior**
The unread notification should clear when emails have been read.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8+
 - OS: Multiple 

**Additional context**

**Comment by stelord** [comment]
![BD71F871-B630-4C1E-B0D2-33487C9DC5FA](https://user-images.githubusercontent.com/8946696/73125548-e4d90800-3f9f-11ea-8543-52a57b54293b.jpeg)
![92E30201-0AB6-4D22-B720-29608D0BD7EE](https://user-images.githubusercontent.com/8946696/73125555-f6baab00-3f9f-11ea-9b55-2ca0b155ec1b.jpeg)

**Comment by charlag** [comment]
Duplicate of #1267
Either scroll till the end of list so that counter can fix itself or contact support if it's not possible.

**Comment by stelord** [comment]
I wish they would help.  They don't seem to care.
