### ISSUE TITLE
Release the apk file here on GitHub

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [tutao/tutanota#1777]
Hello thank you for the great app.

When you release a new version. Can you add the apk file under GitHub releases?
https://github.com/tutao/tutanota/releases

I don't use Google Play Store and F-droid is very slow with recent updates.

Please start with the next version of Tutanota Android and publish the apk file here.

**Comment by charlag** [comment]
![Screenshot_20200129-195836](https://user-images.githubusercontent.com/3099142/73388041-c93c6d00-42d1-11ea-8756-227f91e527ed.png)
