### ISSUE TITLE
Update subscription options

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1778]
* add "Tutanota Teams" subscription for private and business customers
* add sharing feature to Pro subscription
* add sharing features to subscription overview

**Comment by armhub** [comment]
Should be implemented together with #1667.

**Comment by armhub** [comment]
Test hints:
* Order legacy Pro subcription from old client
* Order with promotion
* Order with configured discounts/free features
* Switch between subscriptions
* Switch to higher subscription with additional features ordered already

**Comment by mpfau** [comment]
When upgrading from old client:
* Price of 72 € is displayed but 60 € is billed

**Comment by mpfau** [comment]
Must be fixed:

- [ ] Reason in case of cancelled downgrade is not displayed (e.g. second user is active)
