### ISSUE TITLE
End of the Month Event Display on Agenda View not Working Intuitively

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#1782]
**Bug Description**

I'm not 100% sure if this qualifies as a bug or just a usability issue, but I think it is worth looking into. There is some unexpected (I think) behavior in the agenda view when a the view includes the end of the month. Rather than including events in the upcoming week that are in the next month, the agenda view only shows those from the current month. This always confuses me and I end up thinking there is an issue with the calendar.

Additionally, when the month rolled over, when I checked my calendar on agenda view this morning it showed no events despite having ~6 scheduled for today (2/1). Once I viewed the calendar view and went back to agenda view the agenda displayed as normal.

**To Reproduce**
1. Make sure your calendar has events at the end of the current month and beginning of the next month 
2. Go to 'Calendar > Agenda View' in a week that includes the end date of the current month
3. You will only see events for that month in the agenda view 

**Expected behavior**

Agenda view should show events in the current week even if they are in the next month.

Agenda view should show current day's events on the 1st of the month.

**Screenshots**

![tuta-bug](https://user-images.githubusercontent.com/45246438/73595216-f19bb580-44e3-11ea-8314-ded44bf49e41.png)

**Smartphone (please complete the following information):**
 - Device:  iPhone
 - OS:  iOS 13.3.1
 - Version: v3.66.5

**Additional context**

**Comment by brendon-boldt** [comment]
I recently had this happen to me on the web version (Firefox on GNU/Linux). Although this issue was present in both the week view and the agenda view. This occurs when I first open the calendar. Once I load the next month, the week view and agenda view for the intermonth week displays correctly.

**Comment by charlag** [comment]
I think it's the same issue as #3136

**Comment by ganthern** [comment]
Fixed as of 3.98.19, probably since #3136 was done.
