### ISSUE TITLE
Can we have desktop app retry login at PC startup instead of giving "looks like you are offline" error and stopping there?

### ISSUE THREAD

**Issue by TheShitcoiner** [tutao/tutanota#1783]
**Description**
Getting an error at PC startup before it even connects to the wifi.

**To Reproduce**
1. Enable Tutanota at startup.
2. Turn on pc while offline or have a 2 second delay before connecting to the internet.

**Screenshots**
![Screenshot_20200201_185431](https://user-images.githubusercontent.com/49177109/73601641-df913580-452a-11ea-83ea-ee658973e552.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 19.10
 - Desktop Environment:  KDE Plasma 5.16.5

**Additional context**
It'd be nice to have the app not stop at that error and keep trying to log in. It's annoying to be faced with that error at every startup.

**Comment by charlag** [comment]
Hi
Can I verify that you are talking about automatic startup of Tutanota on login? Because this shouldn't open any windows.

**Comment by TheShitcoiner** [comment]
Yes, it's the Tutanota appImage integrated into the system using TheAssassin's appimage launcher. I have it enabled on Kubuntu's system Autostart.

https://github.com/TheAssassin/AppImageLauncher

![Screenshot_20200206_190146](https://user-images.githubusercontent.com/49177109/73992076-a3d3e280-4913-11ea-82fa-36219a43c4e2.png)

Note: I updated the app since my OP. Still the same.

**Comment by charlag** [comment]
Don't add AppImage, use these options to start up the app in background. Then you will log in the first time you open the window and you will receive notifications in background.
![Screenshot from 2020-02-07 09-27-16](https://user-images.githubusercontent.com/3099142/74013148-17b1d180-498c-11ea-8058-0e77f8717203.png)

**Comment by TheShitcoiner** [comment]
That's done. Issue is still there. A few seconds connectivity delay results in previously mentioned error and app stops there. No retry to login until pressed "Ok" to clear error then pressed on Email address to login.

**Comment by charlag** [comment]
Default integration puts it into the auto-launcher with -a
like so:

![Screenshot from 2020-02-10 09-42-00](https://user-images.githubusercontent.com/3099142/74133797-aa9b7780-4be9-11ea-871f-45b5f990e632.png)

In your screenshot it's without it, maybe because you put it there manually. Then the app starts in background, connects to notifications and doesn't try to open any windows until you tell it so.

**Comment by TheShitcoiner** [comment]
I apologize. I should have been clearer. It doesn't open a window at startup after removing Appimg from startup list. 

What I was refering to as "issue" in previous comment was that Tutanota app (after clicking on tray icon and showing window) would still have "Could not reach server,...etc" error. That error would presist until cleared even after a connection has been established.

However, I just sent myself a test email (using phone) and it was received (popup notification showed on laptop) even though "Could not reach server..." error was there after launching app by clicking on popup notification icon. I hope this makes sense.

**Comment by charlag** [comment]
Thanks for clarification. Notifications are a separate system form login and windows and they work in background and have retry mechanism. With error - I'm not sure how it happens. When you click on the tray and the window pop up is the error already there or does the client try to log in first and then gets an error? Does subsequent attempt give successful login?

**Comment by charlag** [comment]
I am closing this as there's a background mode which automatically reconnects and app windows are not supposed to be opened automatically.
