### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by fredhampton** [tutao/tutanota#179]
I followed the build instructions and when I ran gulp dist
I received the following error message

Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined

**Comment by mrAl-x** [comment]
I'm also having issues building the project since it appears to no longer be using gulp. So I'm assuming the README might be outdated…

**Comment by mrAl-x** [comment]
I'm having the same issue… Did you manage to find a solution for this?

**Comment by mrAl-x** [comment]
I might've found the solution, try updating Karma: `npm install karma@latest`
Seems to have fixed the issue for me

**Comment by armhub** [comment]
Great, thanks!
