### ISSUE TITLE
Option to not mark mails read automatically

### ISSUE THREAD

**Issue by P-E-Meunier** [tutao/tutanota#1791]
**Bug in web app**

**Describe the bug**
I want to manually mark my emails as read, instead of having tutanota mark it read as soon as I open it. Not all mail can be answered right away, and some call for a faster answer.

I know not all users want that, so an option would be nice.

**To Reproduce**
Open an unread email in my inbox, it's marked as read.

**Expected behavior**
I want the message to not be marked as read when I open it.

**Comment by charlag** [comment]
Hi
This is a feature requests and we don't accept them here, sorry
