### ISSUE TITLE
Error message after login: This security key has not been registered.. 

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1792]
A few minutes after successful login this error message shows up:
"This security key has not been registered with your account. Please use a valid one."
I can confirm the error message and everything works as expect. 

How to reproduce:
1. Add U2f device as second factor
2. Login to the account using Chromium, confirm the login from another session (don't use u2f device).
3. Three minutes after Login the error message shows up.

**Comment by mpfau** [comment]
The error still occurs on.

**Comment by charlag** [comment]
Could not reproduce in FF, reproduced in Chrome
