### ISSUE TITLE
[linux/desktop app] update fails/app doesn't open

### ISSUE THREAD

**Issue by linuxgirl22** [tutao/tutanota#1797]
Hello :-)
Just to report that update is failing in the linux desktop app, which stops the program from opening. I never click on 'update' when that message comes up, but there wasn't the option on this occasion ... a message didn't come up, and it was taking a long time to login, then did these messages. 

![tutanota error](https://user-images.githubusercontent.com/35760727/74075669-88e49980-4a0b-11ea-94d1-8bea75fa4f42.png)

The web client works perfectly still. Let me know any information you need.

**Comment by linuxgirl22** [comment]
Rebooted, and the issue isn't happening now. A bit concerned that the app tried to auto-update, and needed rebooting to fix.

**Comment by ganthern** [comment]
Glad the reboot resolved your issue. I'll be closing this for now, but if this problem should surface again you can help diagnosing what's happening by starting the client from the command line and attaching the log output.

Cheers!

**Comment by linuxgirl22** [comment]
Thanks, @ganthern! Appreciate advice, and will be sure to attach the output if problem resurfaces. :-)
