### ISSUE TITLE
Import of contacts fails

### ISSUE THREAD

**Issue by szdavid3** [tutao/tutanota#180]
Hello, 

I downloaded a vcf file from my carddav provider but whet in try to upload it says "the file can not be read"

Any idea ?

Thanks

David

**Comment by asteintutao** [comment]
Hello szdavid3,
vCard files can come in different versions some provider / programs may export contacts in other vCards versions then the one currently accepted by us. 
If you like you can try to open your vcf-file with notepad, for ubuntu with gedit or any other text editor and then check the version of your vCard file it is written in between the BEGIN:VCARD and END:VCARD tag 
It may look like: 
![image](https://user-images.githubusercontent.com/31402512/31940065-1def4bac-b8bd-11e7-8fe7-e92577231a1d.png)
Important is that your file is in version 3.0 
If it is not, don't worry we are already working on implementing version 2.1
