### ISSUE TITLE
Direct replies to sent emails sent to Spam.

### ISSUE THREAD

**Issue by JustEffy** [tutao/tutanota#1807]
**Bug in web app**

**Describe the bug**
I emailed The Samaritans. The direct and timely reply was placed in the Spam folder. This has happened twice in succession, both with their reply to my initial email, and also to their reply to my reply.

**To Reproduce**
I certainly wouldn't suggest sending test emails to The Samaritans, as they're a suicide-prevention charity and staffed by volunteers, but I believe what I wrote above should be sufficient if you're going to do it anyway.

**Expected behavior**
I expect timely replies to emails I've sent _not to be placed in the Spam folder_. 
(And no, I had no user-defined rules. Now I have "No Spam:*" set to avoid this. But that's a bad workaround.)

**Comment by charlag** [comment]
HI
Sorry that it happened to you. We plan to improve spam filter to check that it's part of the existing thread but I'm not sure that we have such information available on the server in unencrypted form.

**Comment by bedhub** [comment]
This issue has been solved with tutanota server version 3.89.0 see server issue 70
