### ISSUE TITLE
Add s/mime infrastructure for external mails

### ISSUE THREAD

**Issue by axel9n** [tutao/tutanota#1814]
When sending/receiving emails to/from external emails addresses, implement s/mime signing and encryption, preferably with a Tutanota certificate, including automatic certificate processing when included in received mails. 
Rationale: s/mime is implemented in most commercial email clients off the shelf and deployed in large organizations as security feature.

**Comment by charlag** [comment]
Hi. This is a feature request. We don't accept them here. See README where to submit feature requests.
