### ISSUE TITLE
BadRequestError when accepting an calendar invitation as a cancelled premium customer

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1821]
A BadRequestError is dispatched when I accept an calendar invitation as a cancelled premium customer. The client should handle this case and display the upgrade dialog, instead.

We need to implement re-enabling cancelled accounts from the client to fix this bug.

**Comment by vitoreiji** [comment]
> We need to implement re-enabling cancelled accounts from the client to fix this bug.

For now let's just show an error dialog.

**Comment by vitoreiji** [comment]
2918228 implements the check for accepting an invitation and also for sharing a calendar.
