### ISSUE TITLE
Windows client crashing on startup

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1825]
**Desktop:**
 - OS: Windows 10
 - Version: 3.64.7

**Additional context**
This is related to the [keytar](https://github.com/atom/node-keytar) and probably electron-builder in some way. I was not able to build it. When it was build on another machine, the issue was not there. Another build from CI also leads to a crash.

We stopped rollout and put the previous version for downloading so that there are no more upgrades and that there's an ability to downgrade.

**Comment by bedhub** [comment]
fixed on build server
