### ISSUE TITLE
Tray icon not showing up on Linux with 3.67.4

### ISSUE THREAD

**Issue by ajgraves** [tutao/tutanota#1829]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
On Arch Linux using XFCE, the tray icon does not show up on version 3.67.4. I have tried both the AUR package as well as downloading and running the AppImage directly, and neither shows a tray icon any longer, despite having "run as tray app" set to yes.

**To Reproduce**
1. Launch app
2. Observe no tray icon

**Expected behavior**
Tray icon should show up.

**Desktop (please complete the following information):**
 - OS: Arch Linux current as of 17 Feb
 - Desktop Environment: XFCE 4.14
 - Version 3.67.4

**Comment by charlag** [comment]
Hi
I've seen another report about this but it works for us under GNOME. Do you have any ideas?

**Comment by charlag** [comment]
We've received a lot of complains about Mint.

I see that there were some changes in Electron 8 related to this:
https://github.com/electron/electron/pull/21904

But it was merged before Electron 8 was released so :thinking:

**Comment by charlag** [comment]
I'm not sure if it might be related:
https://github.com/electron/electron/issues/21445

I checked Mint/XFCE installation and indeed there's no tray icon.

As it already does not work consistently across Linux distros and almost each Electron app struggles with this, I would propose to:
 - add a new window button inside the app (like Gedit or GNOME files). We already have it as an icon menu option but it only works in Ubuntu via libappindicator afaik
 - remove "hide instead of close" behavior and
- rename "run as a tray app" to "run in the background"
 - drop tray icon on Linux (or at least not rely on it)

**Comment by vladimiry** [comment]
I update status [here](https://github.com/electron/electron/issues/21445#issuecomment-565710027) and [there](https://github.com/vladimiry/ElectronMail/issues/254). So tray icon supported on KDE/Xce/Mate/Gnome systems but in some cases you need to install some plugins or configure the system, see above links for details.

**Comment by charlag** [comment]
Hi
I've seen your comment, I checked and the xfce library is pre-installed on mint but it doesn't help

**Comment by vladimiry** [comment]
You also added the plugin to panel like (@ajgraves, it's Arch Linux + XFCE on the screenshot)?

![xfce](https://user-images.githubusercontent.com/1560781/74900352-880b1a80-53b0-11ea-934f-2d9c36e7405f.png)

There is another recipe for Mint but with Cinnamon DE (not sure it's applicable if Mint + Xfce used): `"System Settings" -> "General" -> "Enable support for indicators" flag needs to be enabled`.

**Comment by vladimiry** [comment]
For Xfce there is also https://gitlab.com/vala-panel-project/xfce4-sntray-plugin working plugin, alternative to `xfce4-statusnotifier-plugin`. It also supports Mate but I didn't try it yet.

**Comment by charlag** [comment]
@vladimiry thanks, adding this plugin to XFCE panel indeed works.
Unfortunately it only proves my point that we shouldn't rely on it but at least we can share it as a workaround.

**Comment by vladimiry** [comment]
> we shouldn't rely on it but at least we can share it as a workaround.

Agree on this point. This is why in ElectronMail I automatically disable `Start minimized to tray` and `Close to tray` flags for Linux users in first @electron-v8-based release, so the UX won't be completely ruined for them (see respective [issue](https://github.com/vladimiry/ElectronMail/issues/254) if interested).

**Comment by k3VTSjczL3** [comment]
It's also happening on Linux Mint 19.3 "Tricia". I'm using the appimage, set up run on startup and minimzed to tray option in the app. On boot tutanota app is running and I can open it using the desktop iintegration but cannot see it after minimizing to system tray.

**Comment by armhub** [comment]
As there is no reliable mechanism for the tray icons in the different Linux distributions, we have added buttons for the following operations to the left nav menu in the Tutanota desktop client:
* open a new window
* quit the app

**Comment by dotenorio** [comment]
See my solution:

https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150
