### ISSUE TITLE
[feature reuest] search

### ISSUE THREAD

**Issue by vasanthaganeshk** [tutao/tutanota#183]
Search for a particular email, the subject or the body would be nice to have.

Thanks.

**Comment by mx1010** [comment]
Yes indeed, would be amazing ✨

**Comment by armhub** [comment]
Available in the new client: https://mail.tutanota.com

**Comment by mx1010** [comment]
Thanks for all the hard work, you all rock 👍

**Comment by armhub** [comment]
:-)
