### ISSUE TITLE
[Feature request] Folders in folders

### ISSUE THREAD

**Issue by bla-ke** [tutao/tutanota#184]
Hello!

I'm a new user of Tutanota Mail and I changed my mail from Vivaldi Mail. Well, I think that Tutanota is a great and good alternative, but, to be honest, I lack this one simple, but powerful feature: folders in folders. I've not seen any option to do it. It's very helpful for example to make a registration folders with mails, it helps to organize everything and search information about used data on websites. Just something like this:
https://i.imgur.com/mKN5GXt.png

Is it possible to add this function?

Thank you so much for your reply.

Greetings, Daria

**Comment by armhub** [comment]
Sorry, folders in folders are not planned. In the new client you have a list of all your custom folders separate from the default folders (inbox, sent etc.).
