### ISSUE TITLE
Recipient to Select Password

### ISSUE THREAD

**Issue by IFSUK** [tutao/tutanota#1840]
When sending an encrypted email to a non Tutanota user a password has to be set by the sender.  

That becomes a real problem in how to convey that password to the recipient.

It is possible to devise a mechanism for the recipient to select his/her own password.  That would be a welcome feature.

**Comment by charlag** [comment]
Hi
This is a feature request, we don't accept them here.
Such a mechanism exists and it's called "sign up".
