### ISSUE TITLE
Some invalid links are not replaced

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1842]
We already replace some of the invalid links but still some slip through, e.g.:
`file:///C%3A/Users/folder...` (this is already link after sanitizing, it's not clear how original one looked like)

then on clicking users get errors like

```
Error
Error message: Failed to open
Stacktrace:
Error: Failed to open
```

**Comment by charlag** [comment]
Another link, which should maybe be accepted but leads to an error currently:
`mailbox:///tmp/tuta/2020-07-21-16h53m11s.eml?type=application/x-message-display&number=0#`

**Comment by johnbotris** [comment]
these particular examples seem to be getting sanitized now
