### ISSUE TITLE
[Bug] I can't remove any folders from Spam

### ISSUE THREAD

**Issue by bla-ke** [tutao/tutanota#185]
Hello!

I have a folder called `-` in Spam section. Unfortunately, I can't do anything to remove it, I just have a simple error. I dunno why it's appearing for me, but it isn't only with this one - it happens to every folder in Spam (I made for this experiment two other folders called `One folder` and `Second folder`, always this bug). Browser doesn't matter, it happens everywhere.

Log:
```
Client: Browser
Type: Free
Tutanota version: 2.15.0
Timestamp (UTC): Sun, 05 Nov 2017 17:31:05 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.2.2 Waterfox/55.2.2

Stacktrace:
InternalServerError.
tutao.util.ErrorFactory.prototype.handleRestError@https://app.tutanota.com/app.min.js:54:30235
error@https://app.tutanota.com/app.min.js:53:1170
u@https://app.tutanota.com/app.min.js:8:6601
fireWith@https://app.tutanota.com/app.min.js:8:7374
r@https://app.tutanota.com/app.min.js:9:10336
n/<@https://app.tutanota.com/app.min.js:9:16166
```

**Comment by armhub** [comment]
This bug only occurs in the old client. It will be fixed with the next server release. In the meantime please use the new Tutanota client (https://mail.tutanota.com), there it should work fine.
