### ISSUE TITLE
Safari: Scrollbar not visible

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#186]
A user has reported that the scrollbars are not visible in the mail list and the mail viewer using the latest Safari browser (11.0) and OSX High Sierra on a Mac Book Pro. We could not reproduce this error on one of our test machines.

If anyone also has this problem please report details about your configuration so we can reproduce this error.

**Comment by bedhub** [comment]
Another user has reported that he cannot scroll the mail list on https://app.tutanota.com
Using https://mail.tutanota.com he can scroll the mail list but he cannot scroll the mail viewer. Scrolling in MailEditor is possible

"With the new version of Tutanota, however, it seems I am having a slightly different problem. I can scroll through emails in my Inbox and whichever email happens to be highlighted opens in the column to the right of the inbox (as it would for a 'preview' screen). Normally, I would double-click on the email in the inbox to open the message in a separate window or pop-up that I can then scroll through to read it in entirety. Unfortunately, nothing happens when I double-click the email to open it. And I cannot find an icon or command anywhere to open the email (or perhaps I'm just missing it?). As a result, I can only read the portion of the email message that appears in the 'preview' screen. As a work-around, I have found I can click on the 'reply' or 'forward' icons, and this opens the message in a pop-up window -- and there, I am able to scroll through the message in its entirety.
Any suggestions would be much appreciated -- thank you!"

I am using a MacBook Pro laptop with MacOS Sierra (version 10.12.6 -- 16 G1036). The browser I use to open Tutanota is Firefox Quantum (57.0.1) 64-bit.

**Comment by antomor** [comment]
Not able to reproduce it, does it still exist?

**Comment by charlag** [comment]
which versions did you try?

**Comment by antomor** [comment]
I tried on MacOS Catalina, both on Safari 13.1 and Firefox 75.0, and Tutanota 3.71.4.

**Comment by charlag** [comment]
Couldn't reproduce it either
