### ISSUE TITLE
Ghost unread mail counter

### ISSUE THREAD

**Issue by phath9** [tutao/tutanota#1860]
version: 3.67.5

In Emails tab, the number of unread email never gets to 0 even though all emails have been read. So the counter badge is always there, cannot get rid of it.

![image](https://user-images.githubusercontent.com/60891576/75634010-addebd80-5c01-11ea-8b91-a97be2156295.png)

**Comment by charlag** [comment]
Counter fixes itself in a few seconds if you load folder till the end. If you loaded inbox till the end, select another folder and then inbox.

**Comment by phath9** [comment]
> Counter fixes itself in a few seconds if you load folder till the end. If you loaded inbox till the end, select another folder and then inbox.

I think it's taking time to scroll to the end, especially if you have 1000+ emails. The app also loads only about X emails each time.

**Comment by charlag** [comment]
@phath9 please contact support

**Comment by phath9** [comment]
Which issue is this a duplication of? I guess it has been reported before so it's labelled as duplicate but no reference number given.

**Comment by charlag** [comment]
#1316 #1267
