### ISSUE TITLE
Auto-capitalization does not work on iOS after the newline

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1863]
1. Finish the sentence
2. Insert newline
3. See that the next character will not be capitalized.

It's fixed in Squire already but there's no release with it yet:
https://github.com/neilj/Squire/commit/9218c9ba1423989570c9cb2f1b062ec45a2ef7f9

**Comment by mpfau** [comment]
test notes:

Editor in HTML and Plaintext mode on iOS, Android and Firefox and Chromium
Edit Signature
