### ISSUE TITLE
Tutanota as a default mail app

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1864]
- [x] Linux
 - [x] macOS
 - [x] Windows
--------------------

For Linux what we need to do is to add 
```
MimeType=x-scheme-handler/mailto
```
to our .desktop file. Under GNOME it might be necessary to run
```
update-desktop-database ~/.local/share/applications
```
------------------------

For mac it is already possible to select Tutanota but currently it must be done through the Mail.app:
https://support.apple.com/en-us/HT201607
They also mention that
> You can also set your default email app in the preferences of your third-party email app.

So I think it should be possible to select it in Tutanota

-------------------

For Android it doesn't seem like there's a category for email in default apps and we already can handle mail sending intents so it should be enough.#

---------------------

I don't think it's possible at all on iOS, you cannot even select a browser.
https://www.wired.com/story/how-to-change-default-apps-windows-android-macos-ios/

--------------------

**Comment by ThracianKnight1907** [comment]
As of iOS 14, it is possible to set a default mail app on iOS and iPadOS devices
