### ISSUE TITLE
Cannot share calendar (invalid email address)

### ISSUE THREAD

**Issue by melat0nin** [tutao/tutanota#1868]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality). I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Sharing a calendar doesn't work, giving message about 'invalid email address' even when the address is correct.

**To Reproduce**
1. Go to 'Calendar'
2. Click on '...' next to a calendar, then 'Sharing'
3. Enter a valid email address, and click 'Invite'

**Expected behavior**
The specified email address receives an email with a link to the calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/912688/75857794-1b077400-5df7-11ea-898f-969f70b29591.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 74 beta 9

**Comment by charlag** [comment]
Please contact support mentioning the email address
