### ISSUE TITLE
[Feature Request] Some Sort of Notifications without Push Notifications (GCM)

### ISSUE THREAD

**Issue by ded5r** [tutao/tutanota#187]
Some of us would like to use Tutanota for the purposes of getting away from corporations like Google. We therefore also go to great lengths of even installing custom ROMs on our phones and do not install Google Play Services. For such users of your app, there are no notification options available at all. We can understand not having to create an entire push server just for us, or that you are not there yet with, say, implementing something along the lines of what Signal has done with websockets for their Android app, for those who do not use Google services. But would it be possible to have at least some sort of notification? Maybe just a little red dot on the app icon when there is a message? And even better, maybe also a sound notification? Now we can maybe understand that this simple compromise might not be able to happen when not logged in on the app, but logging in and remaining so for the time being, until better solutions can be made, would be better then how it is now, where a message shows up in the app but you cannot know it is there until you open the app, whether you are logged in or not. Some possibility for notification is better than nothing at all.

Thank you for your consideration.

**Comment by mpfau** [comment]
The new app will be published on fdroid within the following months and we will also remove all dependencies to google APIs!
