### ISSUE TITLE
Email is not dated correctly (goes over 24hr day period)

### ISSUE THREAD

**Issue by FozzieHi** [tutao/tutanota#1870]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Email is not dated correctly, goes over the 24hr day period.

**To Reproduce**
Not sure

**Expected behavior**
The time should be 00:46

**Screenshots**
![image](https://user-images.githubusercontent.com/23139726/75912980-fab4d500-5e49-11ea-9365-f88378dac723.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave (Chromium: 80.0.3987.122)
 - Version: 3.68.1

**Additional context**
None

**Comment by charlag** [comment]
For date formatting outside of calendar we actually only use browser formats so this must be a browser bug.
