### ISSUE TITLE
Push Desktop Clients out of beta

### ISSUE THREAD

**Issue by baimafeima** [tutao/tutanota#188]
I expect to have a desktop client for Tutanota and be able to install it on my operating system.

**Comment by zeeshan595** [comment]
If you are really looking for a desktop client you can download it here. Its the exact same Github build but on electron. Which lets it run the tutanota web-app as a desktop application.

https://github.com/zeeshan595/tutanota/releases

**Comment by vladimiry** [comment]
[email-securely-app](https://github.com/vladimiry/email-securely-app) is an alternative Electron based  wrapper app.

**Comment by charlag** [comment]
For reference, there's a beta desktop client available now:
https://tutanota.com/blog/posts/desktop-clients

**Comment by joshwithkids** [comment]
Suggestion:  Please consider adding tags/labels support on the import feature on desktop client.  Must dovetail with tab/label support in Tutanota overall.  Our business uses labels extensively and the 2 features keeping us from switching are IMPORT and LABELS

**Comment by jeffmcneill** [comment]
Please add the links in the URL above to the website itself. It is very difficult to find these desktop clients (and also Android/IOS client links on the website. I would recommend adding these links to the home page. I know that the icons for fdroid, play, iapp are there near the top, but things like search within the page don't surface these, and small icons are easy to overlook. One additional column at the bottom of all pages that have the six app download links would be a great usability boost. Thanks!

**Comment by pke** [comment]
Have you considered designing the Electron based e-mail client in a way to add other e-mail providers too? More like an VSCode like approach where it can be extended by language servers and code editors?

**Comment by charlag** [comment]
There's an issue for IMAP support

**Comment by zeeshan595** [comment]
> Please add the links in the URL above to the website itself. It is very difficult to find these desktop clients (and also Android/IOS client links on the website. I would recommend adding these links to the home page. I know that the icons for fdroid, play, iapp are there near the top, but things like search within the page don't surface these, and small icons are easy to overlook. One additional column at the bottom of all pages that have the six app download links would be a great usability boost. Thanks!



> Have you considered designing the Electron based e-mail client in a way to add other e-mail providers too? More like an VSCode like approach where it can be extended by language servers and code editors?

Hello, I haven't looked at this in a long time and it is probably very out of date by now. But now you can probably use nativefier to build yourself a desktop client https://github.com/jiahaog/nativefier

Here is what you need to do.
1. Make sure npm is installed from https://nodejs.org/en/
2. Open terminal / command prompt
3. Type `npm install -g nativefier` for mac and linux try putting `sudo` at the start for permission issues
4. Create tutanota desktop app by typing `nativefier --name "Tutanota" "https://mail.tutanota.com"`
5. A new folder should be created containing a `tutanota` executable which is your desktop app

**Comment by pke** [comment]
@zeeshan595 nice rambox, however it does not support keybase, which is a shame since they are both Electron based.

**Comment by beerisgood** [comment]
For Windows it would also be awesome if the client is available at Windows Store.
Also as Windows store app, the client can be build as [AppContainer](https://docs.microsoft.com/en-us/windows/win32/secauthz/appcontainer-isolation) version which is even more secure.

The biggest advantage for Windows Store is automatic updates for user.

**Comment by akg83** [comment]
A Tutanota client that can be installed on aarch64 (arm based arch linux distros) will be very much appreciated, 

from what I understand all it will take to make this a reality is to have one of the dependences support aarch64, or switch to a specific package that supports it, please  correct me if I am wrong.

**Comment by bedhub** [comment]
Security review is done but we will add spell checker #1069 for official out of beta release and also build keytar on our own #2582.

**Comment by bedhub** [comment]
We finally finished security review and made released the open task. So we are officially out of beta.
