### ISSUE TITLE
Calendar optimizations

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1896]
We should avoid laying out events as much as possible

**Comment by charlag** [comment]
Fixed by b698570fdff2a5a3501c3005d284945d340e7831

**Comment by charlag** [comment]
Test hints:
Showing/hiding calendars
Adding/removing events
Adding/removing calendars
Loading different dates

**Comment by armhub** [comment]
In the mobile apps in the month view the rendering performance is very bad if you have many events, e.g. 3 per day. User interactions are delayed for seconds in this case.
