### ISSUE TITLE
Column order in signup and upgrade dialog wrong for small screen sizes

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1902]
If the screen width is less than 1230px, the free column will be displayed on the right instead of the left side. The columns should only be displayed in that order on mobiles (where only one colum is displayed), not on desktops with smaller screens.

**Comment by antomor** [comment]
Do you mind if I work on it?

**Comment by charlag** [comment]
@antomor feel free to work on it, it is some mismatch with CSS rules I assume
