### ISSUE TITLE
Title field of new calendar entry jumps around on mobiles

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#1906]
The field is focused and immediately blurred on mobiles.

**Comment by bedhub** [comment]
I retested on mobile safari browser and the input field is now not focused at all. Is this the expected behaviour?
The create folder dialog behaves different. The input field gets the focus but no keyboard shows up, Same with MailEditor.

**Comment by charlag** [comment]
Calendar dialog should not be focused, others should be

**Comment by bedhub** [comment]
created new issue #1948 for ios case.
