### ISSUE TITLE
Tutanota Desktop app logs out when closing to tray on Windows

### ISSUE THREAD

**Issue by jernejp21** [tutao/tutanota#1910]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When closing app to tray, it logs out, but sill active. You receive message about new email.

**To Reproduce**
1. Make sure you have enabled tray option in desktop version of Tutanota
2. Close app
3. Open from tray (on Windows)
4. Tutanota will start logging in

**Desktop (please complete the following information):**
 - OS: Windows
 - Desktop Environment, if applicable (on Linux)
 - Version 3.69.2

**Comment by charlag** [comment]
Hi
This is intended behavior now, we don't keep your login outside the window. If you want to keep login, minimize window instead. Notifications are completely independent from login sessions.
