### ISSUE TITLE
Swipe deleting email marks next email read

### ISSUE THREAD

**Issue by ajgraves** [tutao/tutanota#1912]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When viewing the email list, swiping to delete on an email will mark the next email in the list as read.

**To Reproduce**
1. Swipe delete an email that has unread emails below it
2. Observe email below gets marked as read

**Expected behavior**
Emails should not be marked read until you’ve opened them

**Screenshots**
I have a screen recording but Github isn’t allowing me to upload.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.3.1
 - Version 3.69.2

**Comment by ajgraves** [comment]
This works in reverse also. If you delete the bottom email, the unread email above it gets marked as read.

**Comment by charlag** [comment]
This is not a bug but we have some ideas on how to improve this, we will open another issue once we have a plan on how to act
