### ISSUE TITLE
System navbar buttons are not visible on some Android versions

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1913]
We cannot color navbar buttons before Android O (API 26) but we can color navbar itself starting from Android M (API 23). Our programmatic condition only changes colors starting from O but our XML resource (which is used for splash screen) changes them starting from M.

It can be reproduces on Android M and Android N.

![Screenshot from 2020-03-18 12-14-59](https://user-images.githubusercontent.com/3099142/76955356-4bc8cc80-6912-11ea-85e8-9acefca21cd9.png)

**Comment by charlag** [comment]
This is still broken on Android 5 (API 21)

**Comment by vitoreiji** [comment]
I can confirm this is working on Nougat 7.1.2 (API 25)
