### ISSUE TITLE
Dialog for adding aliases does not redirect on "ok"

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1919]
**To Reproduce**
1. Reach max. aliases number
2. Go to mail settings
3. Expand mail aliases table
4. Press add button
5. You should see a dialog "You can choose a larger alias package to register more aliases."
6. After pressing Ok nothing happens

**Expected behavior**
Subscription settings are opened

https://github.com/tutao/tutanota/blob/9b2d082c862ba3ea512f7e7ecf0c971b1e7fd4fa/src/settings/EditAliasesFormN.js#L123-L127

**Comment by jowlo** [comment]
Redirection works fine, but only if there are no aliases deactivated, as when creating a new alias we check for `availableToEnable` instead of `availableToCreate`

**Comment by jowlo** [comment]
I think its fine, it is not a regression, i fixed it in #2489

but i think this should not block the release
