### ISSUE TITLE
Add select all on folders and mark by mouse 

### ISSUE THREAD

**Issue by vired** [tutao/tutanota#1921]
the app( i have only used the web app) does not support select all emails in folder.
due to this we need do it manually.

also there is no way to mark a email via mouse.
we need to use Ctrl+mouseclick to do this. 

which makes it less usable.
   
please solve this problems.

**Comment by charlag** [comment]
Hi
To make the issue tracker manageable we don't accept feature requests here.
Please see README for other ways to do that.
Thanks for understanding.

**Comment by vired** [comment]
@charlag i can't use reddit form form Bangladesh. also i don't understand how to submit a support mail.
please solve the problem here. or i have to stop using Tutanota.

**Comment by vired** [comment]
@charlag please response.

**Comment by charlag** [comment]
We have a contact page where all contact options are listed:
https://tutanota.com/contact/
