### ISSUE TITLE
Firefox need to ender password twice

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#193]
on Firefox when connecting to my webmail a problem recur, authentication is done in duplicate. I have to enter the password twice as well as the authentication code.

Tutanota version: 3.25.0
User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by charlag** [comment]
Did we receive any more reports on this? Never occurred to me

**Comment by mpfau** [comment]
Closing as Meike has not received any reports regarding this issue.
