### ISSUE TITLE
[a11y] hidden password fields in signup dialog are focusable using tab

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1932]
Enter email address in signup dialog and then try to reach the password field using tab. Before the actual password field is focused there are other elements focused which the screen reader mentions as password input.

**Comment by Pa7Hub** [comment]
This seems to be a general problem when using the password field. Also happens when trying to change password (under Settings > Login > Password) when tabbing from "Old password" to "Set password".

**Comment by bedhub** [comment]
Test notes
- [ ] Check that auto fill guard still works. Password managers should only be allowed to auto fill email address and password on the login screen. In all other places like changing passwords, account registration, send mail to secure external password and user management the managed password should not be used.
- [ ] Check that the invisible fields are not focused anmore.

**Comment by johnbotris** [comment]
Firefox password manager still offers to fill in a password when the password field is focused but the field itself isn't filled in automatically. This is the current behaviour so i think it's fine
