### ISSUE TITLE
[ios] Cannot edit title of calendar event.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1938]
When creating a calendar appointment and typing a title with 2 words, if I want to make any changes, the cursor skips to the end of the title.

For example, I create an event, I type the event title e.g. ‘Doctor’s appointment.’ I move my cursor to the end of the word ‘Doctor’s’. I press delete and the cursor automatically moves to the end of the word ‘appointment’.

**Comment by vitoreiji** [comment]
Also true for other text inputs, like Create folder, for example.

**Comment by bedhub** [comment]
It is not only related to iOS. I can also reproduce this on Safari on a desktop computer.

**Comment by bedhub** [comment]
After debugging this case it is somehow dependent to the onkeydown listener in the TextFieldN component. When removing this listener the cursor behaves normally. Another thing that fixes this case is setting "e.redraw = false" inside the listener.
