### ISSUE TITLE
U2f support for Firefox

### ISSUE THREAD

**Issue by rjtg** [tutao/tutanota#194]
The addition of u2f to the new tutanota client is really great. Unfortunately it still does not seem to support firefox, even though firefox now has u2f support built-in.

It would be great if the firefox support could be added.
Unfortunately i was not able to dig into the code and identify how this could be achieved. I would be willing to invest some time if i was given some directions. Since this is security sensitive i would appreciate it however, if someone with more expertise would engage with this issue.

**Comment by armhub** [comment]
Seems like Facets and AppID are not yet supported by the Firefox built-in u2f support: https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/
We need these functions to get it working with Tutanota.

**Comment by armhub** [comment]
We should check if Firefox 60 supports it now: https://www.mozilla.org/en-US/firefox/60.0/releasenotes/

**Comment by rjtg** [comment]
any news?

**Comment by charlag** [comment]
There's a discussion on
https://github.com/w3c/webauthn/issues/1045
But it seems like we will have to accept for now that the user cannot easily share same hardware factor between the app and the web (it would have to be added twice then).

**Comment by armhub** [comment]
https://blog.mozilla.org/security/2019/04/04/shipping-fido-u2f-api-support-in-firefox/

**Comment by esparta** [comment]
https://www.mozilla.org/en-US/firefox/67.0/releasenotes/

> Enable FIDO U2F API, and permit registrations for Google Accounts
