### ISSUE TITLE
Confirm new calendar dialog with Enter opens new add calendar dialg

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1946]
- open add calendar dialog, enter name and confirm by pressing enter.
-> new calendar dialog opens.

Happens also for other dialogs like edit sender name dialog.

**Comment by bedhub** [comment]
fixed by 9d9567f0

**Comment by charlag** [comment]
Now it opens the button twice (works with other buttons like new event button too)

**Comment by charlag** [comment]
I tested in Firefox 74.0 and Chrome 83.0.4093.3 Dev and they both dispatch click event at on enter

**Comment by charlag** [comment]
Closed by  f1632a9fa2889748c21782cac7fe99e8c32bcdcf
