### ISSUE TITLE
Popup: Could not reach server, looks like you are offline. Please try again later.

### ISSUE THREAD

**Issue by alx** [tutao/tutanota#1947]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

A popup with the following error message appears a lot, when opening messages, randomly:

`Could not reach server, looks like you are offline. Please try again later.`

**Describe the bug**

It's kind of annoying, because each time I've got to click on the popup button to close it.

It's not an issue from my connectivity, I'm connected to all kind of places without error.

It might be a firefox extension, messing with some part of the code.

**To Reproduce**
1. Go to Email panel
2. Click on Email message
3. Sometimes, often, a popup with `Could not reach server, looks like you are offline. Please try again later.` error appears.

**Expected behavior**

This popup should only appear when there's a real connectivity issue.

**Screenshots**

![2020-03-30-155036_1920x1080_scrot](https://user-images.githubusercontent.com/373/77920855-474fcc80-729f-11ea-9c1b-e63c2adc83cf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox 74
 - Version 3.69.2

**Additional context**

Could you tell me how I could debug it further ? I've seen there is a "send log" option in the about popup, what should I look inside of it to learn a bit more about what's happening ?

**Comment by charlag** [comment]
I think if you get this message it won't help to look into logs, all you will see is connection errors.
Please check that privacy protection is *not* enabled for Tutanota (shield to the left of address bar). I think for me it was blocking random requests (maybe together with some external content from emails, not sure)

**Comment by charlag** [comment]
You can try to check which requests are blocked in developer console by looking at console and network tabs

**Comment by alx** [comment]
Thanks @charlag for your answer, I'll try to disable the privacy protection and let you know if it solves the issue.

It might be nice to hint the user about this possibility if it's working.

**Comment by alx** [comment]
After a day of testing with privacy protection disabled, it's much better than before, but the popup still appears occasionally.

I'm opening the console to check the network tab.

**Comment by mpfau** [comment]
@hahub also noted a bug when a connection error occurs during initial loading of the mailfolders. The mailfolders are not displayed in this case and even after confirmation of the ConnectionError, the mail view is unusable. However, it is possible to create contacts and appointments.

After a short discussion, @bedhub and me came to following conclusion: ConnectionErrors are triggered by slow server responses or connection issues. We should first focus on retrying GET requests to see how much impact connection issues have. If this does not help, we could try to reduce the amount of long requests on the server side or switch to async responses.

What needs to be fixed:
- [ ] If a ConnectionError happens during initial mailfolder load, the mailbox should be re-initialized at a later time
- [ ] RestClient should retry a get request five seconds after a ConnectionError has occured.

**Comment by charlag** [comment]
This is absolutely related to the Firefox tracking protection, as soon as I enable it I get the error on loading folders. They don't show that anything is blocked on the page so I am certain that this is Firefox bug between this protection mechanism and service worker.

**Comment by avrelaun** [comment]
Same problem here.

**Comment by coyote240** [comment]
I've turned off tracking protection in firefox for a couple of weeks now, and the problem persists.

The error comes up immediately after the browser receives a 404 when requesting https://tutanota.com/images/maintenancecheck.png. I'm pulling the code now to see if there is a direct correlation, and if this is the only condition that is now being used by the web client to determine if it is online.

**Comment by avrelaun** [comment]
Same, disabled for 12 days, still horrible.

**Comment by bedhub** [comment]
The maintenancecheck.png is only requested after a network error occured. It would be nice to identify the network error before the maintenance check and check the details of that error. The timeout for rest requests is currently 20s and if we receive no response or status notification we throw and error. 

I would like to know if the first failing request is because of a timeout or because of another error. If it is the timeout case then the request takes way too long and we have to improve server side code or deliver status notifications for long running requests. 

It seems that the timout is not the only case were we receive this offline error message. I played around with changing ip address/changing suspension state while being logged in. An then the request sometimes returns with an error code after a few milliseconds.

This is my scenario:
* Restart Firefox (v 75)
* Log in on https://mail.tutanota.com
* Switch to VPN connection
* Load content of another folder 
-> Offline message appears.

**Comment by Aninstance** [comment]
I'm experiencing the same issue, as described above.

- Kubuntu 18.04
- Firefox 75.0
  - Enhanced tracking protection: Off
  - Ublock origin: Disabled
  - Privacy Badger: Disabled
  - Multi-account containers: Enabled

Below are screenshots from the dev console.

![Screenshot_20200425_152659](https://user-images.githubusercontent.com/6099727/80314788-6e8cb180-87eb-11ea-9298-bdf7ecee4611.png)![Screenshot_20200425_152758](https://user-images.githubusercontent.com/6099727/80314786-6df41b00-87eb-11ea-985b-31eef9043747.png)
![Screenshot_20200425_152741](https://user-images.githubusercontent.com/6099727/80314787-6e8cb180-87eb-11ea-97df-eb02e182d111.png)

**Comment by tompatulpan** [comment]
Im seeing this lately on both my iphone and web (firefox 75 on Ubuntu) but it seems to be related to what network Im on...?
My home network with ISP its Ok.
On 4G network it sometimes fails on both phone and PC.

**Comment by charlag** [comment]
We experimented with disabling TLS 1.3 in Firefox and it didn't happen anymore. We enabled HTTP/2 which should fix it, please report any changes you observe.

**Comment by armhub** [comment]
See #1045.

**Comment by charlag** [comment]
Anyone in this thread can confirm that it's gone now? I could close it then.

**Comment by Aninstance** [comment]
> Anyone in this thread can confirm that it's gone now? I could close it then.

I have not experienced this issue for the past several days. Thank you.

**Comment by coyote240** [comment]
> Anyone in this thread can confirm that it's gone now? I could close it then.

I have not seen the issue in a number of days.

**Comment by alx** [comment]
Thanks a lot, no more popup on my side too :)

I think you can close it @charlag

**Comment by charlag** [comment]
Thanks for the feedback everyone, especially @Aninstance for SSL hint
