### ISSUE TITLE
Safari: Web site using too much energy 

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#195]
The problem occurs when the site has been open on an Safari tab which I was not viewing. When I return to it I find it blank with the message. I then need to reload it (see attachment).

<img width="496" alt="screen shot 2017-12-15 at 20 06 54" src="https://user-images.githubusercontent.com/8296817/34096843-2355bd2a-e3d7-11e7-8f71-55aea1341a6d.png">

Tutanota version: 3.25.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7

**Comment by asteintutao** [comment]
related to #164

**Comment by charlag** [comment]
It doesn't show up for some time already
