### ISSUE TITLE
Firefox: Can't wheel scroll email headers if opened with menu button

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#1950]
**To Reproduce**
1. Open email from external (preferably one with lots of header lines)
2. Click the three dots button and then "Show email headers"
3. Place the mouse cursor on the headers dialog and try to scroll down using the mouse wheel

**Expected behavior**
Headers are scrolled

**Actual behavior**
Headers are not scrolled

OS: Ubuntu 19.10
Client: Firefox Browser
Tutanota version: 3.69.2
Time zone: Europe/Berlin
User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Additional context**
If you open the headers using the H shortcut this does not happen.

**Comment by charlag** [comment]
Can't reproduce on my machine (I made window smaller to get scrolling behavior but should be no difference)

**Comment by vitoreiji** [comment]
Interestingly, I could also not reproduce it from a fresh profile on my machine. Further testing revealed that deactivating uMatrix solves the problem, which is weird because uMatrix doesn't say it is blocking anything.

Closing this because it must be an addon bug, then.
