### ISSUE TITLE
Webapp does not send mails

### ISSUE THREAD

**Issue by heronils** [tutao/tutanota#1958]
I am using the web application (https://mail.tutanota.com/mail/...) from a current Firefox.

It often does not send messages. Currently it doesnt send any at all. It shows 'your message is being sent', but doesnt send it (it doesnt show up under 'sent'). These mails are unencrypted and dont contain images or other big media. My internet connection works, as i can visit other sites.

Second, sometimes when i drag drop mails to usergenerated folders i have to reload the page, in order to see the changes.

**Comment by charlag** [comment]
Hi
Do you have any extensions installed? Do you have protection enabled in Firefox (shield next to the address bar)? We've seen some problems with both recently.

**Comment by heronils** [comment]
I just noticed that it works when i copypaste the text from the draft and insert it in the input which i get when i click on 'reply' in a mail - aka the bug seems to be related to saving it as draft before actually sending it. These drafts can not be sent.

**Comment by charlag** [comment]
I didn't get your comment. Draft is saved always before sending, reply or not

**Comment by heronils** [comment]
Wow that was a quick answer! :-)

Ok, i disabled this Firefox protection (didnt knew - or forgot - that Firefox does that, grr). I have uBlock and uMatrix installed but both are disabled on this site.

**Comment by heronils** [comment]
stop answering so quick, lol :-)

**Comment by heronils** [comment]
No, it doesnt work. What i did:

Open a mail someone has sent you, type something into it, close it, reopen it from 'drafts', edit something, click send. Then it just shows the 'sending message' dialog forever (which btw could need an 'abort' button) and i have to reload the page in order to get rid of it.

When i click on 'create new mail' and then, after editing it directly click 'send' from that dialog, without closing it once inbetween, then it immediately sends the mail.

Can you reproduce this?

**Comment by charlag** [comment]
No, of course I can't reproduce that.
Also there's no technical difference between draft and non-draft. I think there's some problem with Firefox, some connections are randomly dropped but then sending should fail too.
If you can check network tab in dev console and pin down request which hangs, it would be fantastic.

P:S: pls don't spam with messages, we get emails for this

**Comment by heronils** [comment]
Of course you can't reproduce that. Here is a video:

https://youtu.be/QFH-hTdwYxA

P:S: I didnt know that moving mails to the trash is so difficult for you.

**Comment by heronils** [comment]
Bye.

**Comment by charlag** [comment]
Thanks for the video. It must time out in 20 seconds if there is no network activity. I would kindly repeat my request to check what gets stuck in a network tab (F12, network).
Another very helpful thing you can do is running Firefox in safe mode and checking if it happens there.
It seemed to me that you didn't get websocket update when new draft should have appeaead. Do you run via VPN?

My "of course" was not towards you, just on general difficulty of reproducing things.
I don't mind checking Github emails but my colleges process hundreds of emails per day and I just politely ask to respect this amount of traffic (to get fast responses everyone likes).

**Comment by heronils** [comment]
Ok, i checked the system proxy setting, firefox's proxy settings (no proxy), i restarted with disabled addons.

The issue is still there. In the network tab i see that requests to `https://mail.tutanota.com/rest/sys/publickeyservice?...` are 404's.
The console also shows these messages (`failed request GET https://mail.tutanota.com/rest/sys/publickeyservice?_body=...`)

I dont have any more ideas, let me know if you have.

**Comment by charlag** [comment]
thanks. 404 is normal in this case, it didn't find public key for external user. There rather should be something that is started but not finished. There's a small chamce there's something non-network related but I have hard time imagining what.

**Comment by heronils** [comment]
charlag, i measure this with the firefox dev tools. I see nothing which doesnt stop loading. Do you have too much server traffic? Other websites load like a charm. With this app i constantly see spinning symbols.

And drag drop is funtamentally broken. Thats what i observe.

**Comment by charlag** [comment]
I don't observe this. If server failed to reapond you would get an error right away. it might be a client code error but why can't I reproduce it then?
I suspect you don't receive real-time updates for the same reason sending gets stuck for you. I know you tried different pc but was it also Firefox? I'm just trying to narrow down possible problems at this point.

**Comment by heronils** [comment]
Yes, it is also Firefox.

I also constantly play on eg. Lichess which also uses websockets. It works well there, i very rarely have disconnections. Once in a day, which is normal i guess. I also played around with local python servers using websockets.

Is it safe if i post a video including the network tab or will this show sensible data? (Not that i care too much)

**Comment by heronils** [comment]
I just tested it in a Chrome - it works there! The email is sent.

In Firefox, after pressing the 'send' button when editing the draft, the last network request is `https://mail.tutanota.com/rest/tutanota/draftservice` - code 200. Then no more requests are sent and the 'your message is being sent' dialog stays forever.

In Chrome there is a short delay and then 16 more requests are sent, most starting with `M40`.

Screenshot Chrome after sending the Mail:
![Chrome Screenshot](https://user-images.githubusercontent.com/6892179/78405817-92e8da00-7601-11ea-942f-098a10f73054.png)

Screenshot Firefox while the dialog is active (and the mail is not sent):
![Firefox Screenshot](https://user-images.githubusercontent.com/6892179/78405819-95e3ca80-7601-11ea-9440-12a6c3d0374a.png)

**Comment by heronils** [comment]
I solved it. Stupid me.

I have set up the [global Tracking protection mechanisms](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop) to be stricter in Firefox, when i installed it and i forgot that i did so.

The setting 'Tracking content in all windows' broke it (German 'Inhalte zur Aktivitätenverfolgung'). when disabling this setting the app works again! The other three can stay enabled.

It loads very fast now :-)

Only question left is, why do i need to disable this security setting? isnt it good and safe when this is set up to be strict? How does this fit to the Tutanota philosophy ('care about privacy', see console)?

**Comment by charlag** [comment]
Hi
Thanks for reaching back and explaining the reason, it will save us and other people a lot of headache!
We don't know why Firefox would block any of our requests. We don't do anything suspicious, it' probably false positive and should probably be reported to Firefox (they allow to do it when you press shield button I think).
I also have this to "strict" yet I don't observe this which puzzles me.
![Screenshot from 2020-04-06 09-02-44](https://user-images.githubusercontent.com/3099142/78531264-67bee000-77e5-11ea-8e04-9b627d0a4454.png)
