### ISSUE TITLE
[Feature Request] add a Bridge app like protonmail for access using mail clients

### ISSUE THREAD

**Issue by jeroen7s** [tutao/tutanota#196]

**Comment by mpfau** [comment]
An adapter/bridge wouldn't be a lot of work but we decided not to implement it for various reasons:
1. All mails are stored unencrypted on the devices of the users when you use an adapter/bridge
2. Without a decent mail client plugin, there is no way for a user to know if his messages will be sent end-to-end-encrypted or not

Both of these reasons are absolute no-gos for a secure mail service like tutanota.

**Comment by spartanz51** [comment]
For anyone still landing here: I went ahead and built this as an open source project, TutaBridge. It runs entirely on your own machine, exposes a local IMAP/SMTP server, and does all the decryption on device, so you can use Tuta in Thunderbird, Apple Mail, K-9 and so on.

To be fair to the Tuta team's reasoning above: yes, this means your mail is decrypted locally and handed to a normal client, which is a real trade-off. So it is aimed at people who trust their own machine but want full control of their data: any client, local search, plain .eml backups, automation. If that is not your threat model, the official apps remain the safer choice.

Not affiliated with Tuta. Repo: https://github.com/spartanz51/tutabridge
