### ISSUE TITLE
Useless Unlock Keyring input message

### ISSUE THREAD

**Issue by Ahmed-E-86** [tutao/tutanota#1960]
**Describe the bug**

When I open the desktop application it shows Unlock keyring input message which is completely useless, because it doesn't matter if I enter a password, press cancel, or does nothing, the application will run successfully.

**Screenshots**

![Screenshot_20200404_173641](https://user-images.githubusercontent.com/29783425/78455124-c9276780-769c-11ea-8d00-ac035cc4e32b.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 19.10
 - Desktop Environment: KDE Plasma 5.18.3
 - Version: 3.69.5

**Comment by charlag** [comment]
Hi
We keep push notification master key in keyring. We did not see any reports of it requiring password before. Probably your default keyring itself it locked with password.

**Comment by Ahmed-E-86** [comment]
> Probably your default keyring itself it locked with password.
My default keyring is not locked, because my WIFI connection wont work if it does, and as I said before if I press cancel, the application will run without having to write the password.

**Comment by charlag** [comment]
Well the screenshot says that default keyring is locked. I'm not sure that wifi passwords are stored in the same keyring and our usage of keyring only affects background notifications, you will still able to log in but I'm not sure you would be able to receive notifications and alarms, at least without being logged in

**Comment by Ahmed-E-86** [comment]
>  you will still able to log in but I'm not sure you would be able to receive notifications and alarms, at least without being logged in

I receive notifications just fine without having to write any passwords.

KDE Plasma uses KDE Wallet which looks different this message, this message looks like GNOME Keyring, and I am pretty sure that Tutanota Desktop doesn't use KDE Wallet, because I don't see its name inside KDE Wallet.

**Comment by charlag** [comment]
We use https://github.com/atom/node-keytar and it in turn uses libsecret.
Here's code for posix:
https://github.com/atom/node-keytar/blob/fd66226fb556a3333c9474b5e56e208724dd6dc7/src/keytar_posix.cc

I'm pretty sure it doesn't bind to GNOME keyring specifically but maybe it is handled by it for some reason?

**Comment by nitschis** [comment]
I don't use the KDE wallet.

For two weeks now I have been getting the same message ever launch.

**Comment by charlag** [comment]
@graingert do you remember if we changed something about keytar two weeks ago? I think there were no changes

**Comment by graingert** [comment]
sorry I don't have any context on this

**Comment by charlag** [comment]
oops, sorry, I meant to mention @ganthern

**Comment by graingert** [comment]
@charlag lol, no worries

**Comment by ganthern** [comment]
@charlag last update was on february 13. Keytar itself doesn't seem to have any issues about this.

@Ahmed-E-86 the keyring access is required for **calendar** alarms (scheduled notifications). Those are stored encrypted on your machine so they can get rescheduled as soon as you start the app, before logging in. The key is supposed to be in the keyring.
- Could you run the app from a terminal and compare the output when you unlock the keyring and when you cancel the dialog? If there's something about "alarmstorage key creation failed!" or "alarm storage failed to initialize:" in the output, the app couldn't get access to the keyring. A paste of the printed error may help in that case.
- Could you create an event with reminder in the calendar, log out, close the app, restart it without logging in and check if the reminder goes off?

**Comment by Ahmed-E-86** [comment]
> Could you run the app from a terminal and compare the output when you unlock the keyring and when you cancel the dialog? If there's something about "alarmstorage key creation failed!" or "alarm storage failed to initialize:" in the output, the app couldn't get access to the keyring. A paste of the printed error may help in that case.

After cancelling the dialog, I received these messages:
```
[2020-04-21T19:03:46.612Z] device key not found, generating a new one
** Message: 21:03:52.628: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
[2020-04-21T19:03:52.629Z] alarm storage failed to initialize: [Error: Cannot create an item in a locked collection]
```

I opened the application again, and unlocked the keyring, then I received this message:
`[2020-04-21T19:18:16.221Z] alarm storage initialized`

> Could you create an event with reminder in the calendar, log out, close the app, restart it without logging in and check if the reminder goes off?

After restarting the application, it logged in automatically, so I logged out, and the reminder didn't go off. Logging in doesn't make any difference, and the keyring is unlocked.

**Comment by charlag** [comment]
I'm pretty sure it's something with KDE and/or libsecret because I've seen the same reported for Fractal.

**Comment by nitschis** [comment]
> @nitschis I guess you could also help with that since you're in the same situation

Sorry, my post was unrelated, it actually asked me to define a password, I left it blank, now there is no more popups. Thanks

**Comment by charlag** [comment]
So the problem is that KWallet is in maintanance mode and does not support libsecret protocol properly (which was developed exactly to unify KWallet and GNOME Keyring). I suspect that KDE users get GNOME keyring.

**Comment by Ahmed-E-86** [comment]
That actually happens only on Kubuntu, but on KDE neon User Edition I do not get `Unlock keyring input message`.
