### ISSUE TITLE
Error message when trying to run the application during startup

### ISSUE THREAD

**Issue by Ahmed-E-86** [tutao/tutanota#1961]
**Describe the bug**

I always get the error message: `Could not reach server` when I choose `Run on startup` from `Desktop settings`.

**Screenshots**

![Screenshot_20200404_181156](https://user-images.githubusercontent.com/29783425/78456179-6f29a080-76a2-11ea-8a76-3bae0cca6ba3.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 19.10
 - Desktop Environment: KDE Plasma 5.18.3
 - Version: 3.69.5

**Additional context**

I guess the application open itself too soon, and that is why I always get this message. Is there any way to delay the startup of this application?

**Comment by charlag** [comment]
There's a flag to start in in background (`-a` I think), please try to remove it from desktop settings and add it using settings inside Tutanota

**Comment by Ahmed-E-86** [comment]
You answer is a little vague. Could you explain more if that is not much to ask?
