### ISSUE TITLE
Shared calendar list occasionally broken

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#1965]
Three issues were suddenly visible in the shared calendar list on the left sidebar (own calendars shared with others):
* All shared calendars have the default blue color instead of the selected colors.
* All shared calendars have the name of one of the people it is shared with. That person is in the middle of the shares list.
* When clicking on "Sharing" on these calendars a NotAuthorizedError is thrown.

I noticed this issue when opening the calendar view after I was logged in for some time already. I changed some event prior to noticing this issue. After logging out and in everything looked fine again. Not reproducible afterwards. Browser: Chromium

**Comment by armhub** [comment]
Occurred again for me, but in general only sporadically. Also see corresponding server issue #439.

**Comment by mpfau** [comment]
not reproducible
