### ISSUE TITLE
[mac] Unread mail indicator is not cleared when using the app

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1971]
>I've to restart my Mac client every time I get an email, because the "you got new mail"-icon does not disappear after reading my mail. This makes the Mac client almost unuasable. Is this a known issue, and if so, are there any workarounds/fixes known, other than restarting the application?

I think @vitoreiji

**Comment by vitoreiji** [comment]
I don't need to restart the application, simply clicking the icon on the dock removes the red dot. But yes, this should not be necessary.

**Comment by charlag** [comment]
Ah, so it stays when you read email inside the app, without re-focusing the app, is this correct?
We have mechanism for Android where we clear the counter on every mail URL change (yeah that's drastic but works)

**Comment by vitoreiji** [comment]
Not exactly, if you click the notification it will focus the app, and you can read the mail, click around and do a lot of stuff and the red dot won't go away until you click the dock icon. Or maybe I don't understand what you mean by re-focusing...

**Comment by charlag** [comment]
Ah, okay, red dot doesn't go away when you click notification.
Anyway, I think we should do like on Android.
