### ISSUE TITLE
Search results are duplicated

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#1972]
Our user submitted a way to reproduce this issue (thanks!):

 1. be in search view
 2. type something for new search and immediately press Return
 3. See duplicated results

I tried it out and I could reproduce it. Seems like we do two search queries at once.

**Comment by GiraffeKey** [comment]
I believe the issue is that both oninput and onkeydown call the search method when, respectively, the search input is changed or the enter key is pressed. A possible solution may be to make sure only one search method is being run at a time.

**Comment by charlag** [comment]
We have not been able to reproduce it reliably. Maybe it happens only with search during indexing.

**Comment by SnowyMouse** [comment]
I've found that, while searching, I can fairly often get it to show two or even three of every entry if I press the enter key a bunch of times while it's searching starting after typing in the query. It is possible to also reproduce it by only pressing enter once, but I think pressing multiple times is more reliable, as it may sometimes cause it to show only one of each result but then show duplicate results a fraction of a second later.

![out](https://user-images.githubusercontent.com/39858815/99697302-3e418480-2a55-11eb-9916-074061416e20.gif)

**Comment by jowlo** [comment]
Couldn't reproduce, but i am unsure if i am doing it right.

**Comment by vaf-hub** [comment]
I also checked and it is indeed fixed. I was able to reproduce on production but not on the test system. So the fix seems to work fine.
