### ISSUE TITLE
Purchase on account won't show proper message

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#1980]
The label is shown instead.

![Screenshot_2020-04-09 Mail Done Right Tutanota Login Sign up for an Ad-free Mailbox](https://user-images.githubusercontent.com/197261/78876375-89230480-7a4f-11ea-9320-f30e7c1b9256.png)

3.71.0

**Comment by charlag** [comment]
works fine now
![Screenshot from 2020-04-14 14-07-10](https://user-images.githubusercontent.com/3099142/79223258-4307df80-7e59-11ea-9155-38443e85e05a.png)
