### ISSUE TITLE
Custom meta tags 

### ISSUE THREAD

**Issue by mstroiu** [tutao/tutanota#1984]
**Bug in web app**

**Describe the bug**
Custom meta tag data is not wrapped in a title tag or relative tags.

**To Reproduce**
1. Go to **Settings > Whitelabel > Custom meta tags**
2. Click **edit** and fill out the field then save
3. Now open a new browser window and check the tab title
4. You'll get the domain URL instead of the Custom meta tag

**Expected behavior**
The data from the Custom meta tag field should be displayed as the title of the page.

**Screenshots**
[Screenshot](https://postimg.cc/zV3g5sCT)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: **Safari v13.1**, **Firefox v75**, Chrome v84

**Additional context**
I would expect the Custom meta tag to be wrapped in a `<title></title>` tag

**Comment by charlag** [comment]
Hi
I don't see why meta tags should be wrapped inside the title. They are already in the header and you are supposed to write them like:
`<meta property="og:url" content="https://tutanota.com/">`

**Comment by mstroiu** [comment]
Hey,

Thank you for your reply!
That field is a little bit confusing then as I thought I need to **write only text and not the tag itself**.

Please disregard this bug!
