### ISSUE TITLE
BadRequestError when changing sender name

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#1988]
When trying to change the sender name for my user in "Settings->Email->Default sender name" i get a BadRequestError.

This is the associated error from the server log:
```
I 10:24:02.460 final attribute mailAddressAliases is tried to be modified - PUT /rest/sys/groupinfo Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.69.5 Chrome/80.0.3987.86 Electron/8.0.2 Safari/537.36 - 
de.tutao.tutadb.rest.exceptions.BadRequestException: final attribute mailAddressAliases is tried to be modified
```

**Comment by bedhub** [comment]
Updating the sender name is a reqular put on the GroupInfo instance. Email aliases are stored on GroupInfo as well and it seems that the order of the email aliases matters. After comparing GET and PUT request in the network panel of the web client i noticed that for the failing case the order of email alias is different in the PUT request.

**Comment by bedhub** [comment]
To reproduce this create two email aliases in this order:

1. b@tutao.de
2. a@tutao.de

**Comment by charlag** [comment]
I think it's a regression because of the #1918
