### ISSUE TITLE
Move trash button.

### ISSUE THREAD

**Issue by ryanpcmcquen** [tutao/tutanota#199]
The problem I am having is that the trash button is right next to the move folder button. And since the spam filter is still being improved for Tutanota, a lot of valid email ends up in my spam folder. The issue this creates is that on mobile, I have accidentally deleted valid email, by slipping my finger a little too far to the right. I wonder if the Tutanota team would consider moving the trash button somewhere else (maybe inside the nested ellipsis menu), or anywhere that would prevental accidental clicks that permanently delete valid email.

Please!

![screenshot capture - 2017-12-24 - 14-30-16](https://user-images.githubusercontent.com/772937/34329483-55124150-e8b7-11e7-9fff-0aed6b13af84.png)

**Comment by asteintutao** [comment]
we have implemented a confirmation for finally deleting emails so if you accidentally clicked it you need to confirm your action.
983fbb39e68c2cd69beb4b84a9160a684d47850b
