### ISSUE TITLE
Cannot read reply email contents due to poor contrast of background and text

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#1992]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in Android app/Windows desktop app/web app**

**Describe the bug**
When replying to an email, the white background of the original email is replaced by a black background with very dark text. The contrast of these colours are too similar and I'm also not sure why the original email isn't getting a dark background applied to it in the read view. In the reply window, it's important to be able to scroll down to reread the original email to but it's currently not clear enough to read.

**To Reproduce**
_Note: this was using the dark theme on all platforms_

Steps to reproduce the behaviour:
1. Open an existing email
2. Click reply
3. Scroll down to previous email text

**Current behaviour**
The text of the email being replied to is not a readable colour based on the background.

**Expected behaviour**
The text of the email being replied to is a readable colour.

**Screenshots**
Please see screenshot by Echauffateur on Reddit here: https://imgur.com/a/8db47rg

**Smartphone**
 - Device: Motorola
 - OS: Android
 - Version: 3.69.5

**Desktop**
 - OS: Windows
 - Version: 3.71.4

**Desktop**
 - OS: Windows/Mac
 - Browser: Firefox
 - Version: 3.71.4

**Additional context**
The issue has been raised with a screenshot on Reddit here: https://www.reddit.com/r/tutanota/comments/f8omz4/text_color_in_android_app_collides_with_dark_mode/
I could not find any issue related to above post on GitHub

Is there any reason the F-Droid version is behind all other platform versions or is this same for all mobile platforms (seems they are all the same)?

**Comment by charlag** [comment]
Hi
I wanted to open it but probably forgot, thanks for bringing it up.
We cannot disregard any text color in replies but we should check why original text has hardcoded black color in the first place.

**Comment by shepswitcher** [comment]
Thanks for your response!

> I wanted to open it but probably forgot, thanks for bringing it up.

Yes that's totally fine!

> We cannot disregard any text color in replies but we should check why original text has hardcoded black color in the first place.

True but if the user wants a dark theme, the colour can't be too low of a contrast that the dark background makes the text unreadable. I think most email clients with dark themes render a dark version of the original email with the conversion of dark text to light on a dark background. In another client, I have one email with blue text that does not get converted but all the others get the dark text converted to light on the dark background.

**Comment by andreasmjg** [comment]
To add to this - the text colour that the RECIPIENT sees is ALSO impacted by the dark/light themes. :| 

So if I send an email in dark theme, the recipient will get text that is shaded light-gray, making it very hard to see. 

to reproduce: 

turn on dark theme
send an email to an outlook/exchange inbox
open the email in outlook/exchange

Expected: Dark/light theme should ONLY impact how it appears for ME as the user, not the formatting of the email that is sent to the recipient....

**Comment by vitoreiji** [comment]
Also happens on calendar event descriptions (and probably in all html editors).

**Comment by kibhub** [comment]
Depending on the formatting of the email, it could also be displayed with a white background but with grey font.

**Comment by charlag** [comment]
This does not seem to occur anymore, please tell us otherwise!

**Comment by charlag** [comment]
Tracked as [#7820](https://github.com/tutao/tutanota/issues/7820)
