### ISSUE TITLE
Pinch-to-zoom in mail viewer

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#1997]
In addition to being more intuitive than double tapping (some users don't even realize this is possible), this gives the user control of the zoom level.

We will not support dragging while zooming.

- [x] Implement algorithm for initial pinch to zoom
- [x] Adapt algorithm to set correct transform origin and translation for consecutive pinch to zooms
- [x] Consider scrolled or otherwise moved mail body (e.g. opened header)
- [x] Implement dragging
- [x] Respect initially scaled mail body
- [x] Make sure that the double tap zoom still works and zooms to the double tap position (and not top left like currently)
- [x] Respect the viewport borders, so that the mail body border can not be inside the visible area
- [x] make sure that iOS works as well
- [x] Document how the calculations work

## Test notes:
* [ ] should work both on android and ios and for HTML and non-HTML emails:
* [x] large HTML emails (e.g. newsletters) are initially scaled to the available width (i.e. zoomed out initially)
  * double tap:
    * [x] double tapping an unzoomed email zooms in
    * [x] double tapping a zoomed email (zoom factor is not important) should zoom out
    * [x] double tapping a link does not trigger any link action, but will show the desired zooming behavior
    * [x] single tapping a link triggers the link action
    * [x] zoom center of the double tap is the tapped position when zooming in
    * [x] email has the right scroll position after double tap when zooming out
  * pinch zoom and dragging:
    * [x] it is not possible to zoom further out than the initial state
    * [x] a zoom limit exists (infinite zooming is not possible)
    * [x] email can't be dragged in fully zoomed out state
    * [x] no edges are cut-off in fully zoomed out state
    * [x] the zoom center is the middle between the two fingers
    * [x] scrolling the conversation and then zooming works
    * [x] expanding the mail header and then zooming works
    * [x] when zooming out and a border is reached, the zoom center is not longer between the fingers but adjusted in a way to allow further zooming out without violating the borders
    * [x] while dragging and zooming it is not possible to move the borders of the email to the visible area (ask us if this in unclear 😆 )
    * [x] when zoomed in: dragging in vertical direction until it is not longer possible (border reached) -> the conversation starts scrolling
    * [x] zooming in an HTML email before loading images and then loading the images resets the email back to the initial zoom factor
    * [x] when images are loading with a slow internet connection the email is reset to the initial zoom factor whenever the email size changes
  * combination of double tap and pinch zoom
    * [x] it is possible to double tap and then further zoom in via pinching
    * [x] it is possible to zoom out an email completely by double tapping which was zoomed in via pinching
    * [x] ...
* [x] try out different kind of things, also unusual behavior (exploratory testing)

### Regressions:
* [x] non and mobile devices:
  * [x] conversations are scrollable
  * [x] mail header can be expanded without having any bad side effects on the mail (cut-off at the bottom)
  * [x] links can be clicked and are handled correctly (e.g. mailto: opens mailviewer in tutanota, url in browser)
  * [x] non-HTML emails are rendered correctly
  * [x] HTML emails are rendered correctly but without images by default
    * [x] images can be loaded via clicking the respective button

**Comment by charlag** [comment]
Having real zoom control proved to be.. not really possible in HTML, that's why we have this switch between "real size" and "scaled to width". We can switch between them with pinch-to-zoom (that's requested a lot) but real zooming is impossible in conjunction with container scrolling

**Comment by charlag** [comment]
We checked it and as we cannot cancel scrolling it doesn't seem to be possible without disabling native scrolling.

**Comment by leogallego** [comment]
> Having real zoom control proved to be.. not really possible in HTML, that's why we have this switch between "real size" and "scaled to width". We can switch between them with pinch-to-zoom (that's requested a lot) but real zooming is impossible in conjunction with container scrolling

Hi @charlag, Could you point out *where* the option for "scaled to width" is available? I receive several emails in HTML that can only be read by double tapping and scrolling horizontally.  Until we have the option to view in "plain text only" mode, having the scaled width one might prove useful.

ps. Android user.

**Comment by nokhub** [comment]
Detecting touches and zoom gestures is a bit tricky, but possible and implemented in this wip-branch: pinch-to-zoom-1997.
However, the main problem with using pinch-to-zoom is that we want to zoom to the point between the fingers. This is technically possible, but it requires the transformation-origin. If we set the transformation-origin to specific coordinates, the entire div will be shifted in its parent div. This causes problems when scrolling, because the child can then overlap its parent.

There is no easy solution to this problem, but one way to fix this would be to either create a custom component that is used whenever a pinch-to-zoomable div is needed, or a javascript object that can be attached to any div. This object is initialized with a scale and must manually control the scrolling (x and y) in the div.

Regardless of which solution is chosen, all logic must be moved out of MailViewer.

**Comment by charlag** [comment]
Has a lot of very weird artifacts when trying to zoom in/out on an inline image, looks like multiple GPU layers got outright corrupted. Also dropdown opens and gets pressed when it shouldn't.



https://github.com/tutao/tutanota/assets/3099142/8f26be6f-4b8e-4589-8a85-cd2abb277f6e
