### ISSUE TITLE
Dropdown for sender/recipient does not contain email address

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2001]
When clicking on the button of receipient or sender the dropdown should show the email address as first entry.

* It provides the option to select the email address and copy it.
* In external mailboxes the dropdown is empty otherwise

**Comment by charlag** [comment]
I tried to implement this and I have doubts that this is a good idea. If we want to wrap email address, we won't know the height of it and we cannot give dropdown the size it needs. If we will wrap it, it makes it kinda pointless. We can add a copy action instead.
