### ISSUE TITLE
macOS update error notifications every 15 minutes

### ISSUE THREAD

**Issue by alstr** [tutao/tutanota#2012]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**

Every 15 minutes, I am receiving the following notification, twice:

```
Oh no!
Something went wrong during the update process, we'll try again later.
```

**To Reproduce**
1. Just leave the macOS appliaction open in the background.
2. Every 15 minutes the error should occur.

**Expected behavior**

No error.

**Screenshots**

![Screenshot 2020-04-21 at 09 45 10](https://user-images.githubusercontent.com/11612438/79845357-d2127b80-83b4-11ea-84bc-32f411a214b2.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Catalina 10.15.4

**Additional context**

**Comment by ganthern** [comment]
Hey @alstr,
I'll need a little more info to narrow down the problem. Can you send the logs after you started the app and the first notification appeared to nig@tutao.de ? There's a button for that in the "About" dialog (settings screen -> bottom of the left menu -> about -> send logs).

Thanks!

**Comment by alstr** [comment]
Sent. Thanks.

**Comment by alstr** [comment]
Told by email to reinstall and it should be fixed in the latest version. So far so good. I'll close this then seeing as it seems to be sorted.

**Comment by alstr** [comment]
This has just started again. I will email logs.

**Comment by charlag** [comment]
I think it's the same issue as #2032

**Comment by alstr** [comment]
Looks like the latest version has fixed it.
