### ISSUE TITLE
Inbound MTA-STS for custom domains

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2014]

**Comment by armhub** [comment]
Custom domain users need to add two DNS entries to setup MTA-STS:
- _mta-sts CNAME _mta-sts.tutanota.com
- mta-sts CNAME mta-sts.tutanota.com

This is also displayed at your custom email domain setup in "Settings" -> "Global settings" -> "Custom email domains". When you click on the email domain you will see if any DNS entries are missing. As soon as the mta-sts entries are shown as existing here, we will automatically order a Letsencrypt certificate for the mta-sts subdomain, so we can deliver the mta-sts policy file with the correct certificate.

**Comment by CodeSapiens** [comment]
> Custom domain users need to add two DNS entries to setup MTA-STS:
> 
> * _mta-sts CNAME _mta-sts.tutanota.com
> * mta-sts CNAME mta-sts.tutanota.com
> 
> This is also displayed at your custom email domain setup in "Settings" -> "Global settings" -> "Custom email domains". When you click on the email domain you will see if any DNS entries are missing. As soon as the mta-sts entries are shown as existing here, we will automatically order a Letsencrypt certificate for the mta-sts subdomain, so we can deliver the mta-sts policy file with the correct certificate.
-----------------------------------
Isn't a dot needed at the end of each statement? Or does the background process automatically add it as needed?  Also, the popup you refer to under Settings -> Global settings -> Custom email domains - does not say if the new entries should be CNAME or TXT. Some confused folks are commenting about this in the Blog article.

Thanks for what you do!

**Comment by armhub** [comment]
Depending on how your domain provider allows you to enter your DNS entries, there might be a dot needed.
If you use an older version of Tutanota the DNS entry type is not displayed. Please upgrade to the latest version and it will show is as "CNAME".

**Comment by FozzieHi** [comment]
The MTA-STS deployed on the Tutanota domain seems to still be in testing mode and not enforced https://mta-sts.tutanota.com/.well-known/mta-sts.txt. This should be enforced right or it's pretty much useless?

**Comment by charlag** [comment]
We are finishing the testing of it and fixing remaining issues, we will enforce it as soon as we are ready.

**Comment by FozzieHi** [comment]
> 
> 
> We are finishing the testing of it and fixing remaining issues, we will enforce it as soon as we are ready.

Surely it should have said in the big marketing announcement that it is in a testing phase? It seems a bit misleading having all of these protections without it actually being enforced.

**Comment by iJorgen** [comment]
> 
> 
> > We are finishing the testing of it and fixing remaining issues, we will enforce it as soon as we are ready.
> 
> Surely it should have said in the big marketing announcement that it is in a testing phase? It seems a bit misleading having all of these protections without it actually being enforced.
> 
> As the user has to activate it themselves then they know what it does.

Hi! Any schedule when this will be released? :-) Still in "testing-mode" when I checked my domains today.
