### ISSUE TITLE
Birthday of contact is not encrypted

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2015]
When changing the format of how we store the birthday in contacts the attribute as not been marked as encrypted. We need to change this  to be an encrypted value

https://github.com/tutao/tutanota/issues/413

**Comment by bedhub** [comment]
Test hints:
- Test birthdays with and without year
- Migrate birthday which is stored as unencrypted aggregate
- Migrate birthday which is stored as encrypted date
- Import/export contacts with birthday
- Merge contacts

**Comment by armhub** [comment]
Two different birthdays are shown in the old and new client when
1. Set or migrate to new birthday format in the new client
2. Set a different birthday in the old client
-> Old and new client show different birthdays

**Comment by armhub** [comment]
We will fix the remaining issue later, see #2045.
