### ISSUE TITLE
Open as new mail / message

### ISSUE THREAD

**Issue by BuZZ-dEE** [tutao/tutanota#2019]
Please implement "Open as new mail / message".

For example:

I have sent a mail, but forgot to attach a file. Now I want to open the sent mail as new mail / message, so that I can send the mail to all (cc, bcc etc.) again with the attachment, without to have to add recipients again.

This is not bug, it is a  feature request.

**Comment by charlag** [comment]
It's not a bug, we don't accept features here.
Please reply to the email on a sent folder for this.

**Comment by charlag** [comment]
https://tutanota.com/contact?page=feature

**Comment by BuZZ-dEE** [comment]
Hmm, that is not really the idea of openness and transparency I like.

**Comment by charlag** [comment]
We believe that a non-technical forum like Reddit is a better platform for open discussion than technical issue tracker like Github. Sorting through Github issues takes time from our work and we hope that community understands and collaborates with us on that.
