### ISSUE TITLE
Tutanota is a walled garden

### ISSUE THREAD

**Issue by BuZZ-dEE** [tutao/tutanota#2020]
I really like your software and that you provide it through F-Droid. But in the end it is a walled garden, because I only can send encrypted mails to other Tutanota users.

Maybe you should collaborate with [ProtonMail ](https://github.com/ProtonMail) to define the next level of email.

**Comment by charlag** [comment]
We are working on post-quantum protocol and we think it will make sense to work on interop after that, since all encryption will change anyway
