### ISSUE TITLE
Excesive wakelock time on Nougat

### ISSUE THREAD

**Issue by jgora** [tutao/tutanota#2025]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in android mobile app**

**Describe the bug**
The tutanota app uses too much wakelock time and doesn't let the device going into deep sleep, so the battery is getting drained quick.

**To Reproduce**
Just install the app and login into your account.

**Expected behavior**
More battery friendly application

**Screenshots**
![image](https://user-images.githubusercontent.com/35234089/80834085-52748000-8bf0-11ea-9f8b-a8e86d95ec27.png)

**Smartphone (please complete the following information):**
 - Device: [Motorola]
 - OS: [LineageOs]
 - Version [14.1]

**Additional context**

**Comment by charlag** [comment]
The app holds wakelock via job only until connection is established and released it right after. That `scheduleJobFinish()` you removed in #2026 is what releases wakelock.
Return value from `onStartJob()` tells if system should restart the service afterwards. Maybe you can try to change `onStartJob()` alone and measure if it changes anything?

**Comment by jgora** [comment]
As my understanding, returning false in onStartJob() releases the wakelock and make able next schedules. 
https://developer.android.com/reference/android/app/job/JobService#onStartJob(android.app.job.JobParameters)
![image](https://user-images.githubusercontent.com/35234089/80968961-28ea6d00-8e19-11ea-9deb-38e5beb6b9c2.png)

For some reason your delayed-execution of jobFininsh() may not be working on Nougat.

This is the wakelock time of my fork with #2026 :
![image](https://user-images.githubusercontent.com/35234089/80968529-67cbf300-8e18-11ea-8ef7-023ae5cd0cb9.png)

**Comment by charlag** [comment]
I think it shouldn't matter if we return `false` right away or schedule job finish after 20 seconds. We could reduce the time but I wouldn't change this to be sync as it would decrease reliability, *especially* if it's only a bug in Nougat.
Android 10 does not even show Tutanota in battery usage, neither did 9 show any problems with it.

**Comment by jgora** [comment]
It is not about how much battery consumption is reported to being wasted by tutanota, it is about not letting device going into deep sleep.
