### ISSUE TITLE
Add action buttons to notifications on Android

### ISSUE THREAD

**Issue by kamilzych** [tutao/tutanota#2027]
Hi. I think it'd be great to be able to delete/archive/reply(?) straight from the notification on Android. A lot of apps support that, more about that here https://developer.android.com/guide/topics/ui/notifiers/notifications
If this will get accepted maybe I could help with the implementation.
WDYT?

**Comment by charlag** [comment]
Hi
To keep repository manageable we don't accept feature requests here. Please see README or https://tutanota.com/contact for other options.

About the issue: there;s no authentication besides the app main view so it's not possible currently.
