### ISSUE TITLE
System Tray Icon not appearing in 3.72 - Linux Mint 9.3 Cinnamon

### ISSUE THREAD

**Issue by dosenfleisch** [tutao/tutanota#2028]
This is straight forward.  I was precluded today from opening the app because the version I had was no longer supported.  I had to update to 3.72.  With that, the systray icon no longer appears.  This was confirmed by rebuilds to two other machines that I downloaded 3.72 to and the same problem was present.

**Comment by charlag** [comment]
Duplicate of #1829
