### ISSUE TITLE
Feature request: Chat view

### ISSUE THREAD

**Issue by JVariance** [tutao/tutanota#2031]
Delta Chat, OX Coi Messenger, MailTime, Spark.
Some names of apps that use the e-mail protocol for instant messaging.
I'd love to see something similar in Tutanota.
Maybe a toggle switch to (de-)activate a Chat View for a conversation.

**Comment by charlag** [comment]
Duplicate of #6

**Comment by JVariance** [comment]
I know of the conversation view in Gmail, but this isn't what I meant, even though it's probably based on the same code.
I rather meant an specific chat UI like the messengers ones (WhatsApp, Signal, ...) for mail conversations intended to be a chat. This would (or could) be an extra tab next to mails and calendar.
