### ISSUE TITLE
Mail server key exchange parameters update

### ISSUE THREAD

**Issue by idunno101** [tutao/tutanota#2038]
I tested the mail server connection on internet.nl and it gave a warning that there are insufficeint key exchange parameters used for the server. 
(See test result here --> https://internet.nl/mail/tutanota.com/358360/ )

The test determines that the mail server uses DH-4096 key exchange algorithm which is classified as insufficient since all past traffic can be decrypted if an attacker gains access to the key in the future.
(More info on page 25 of the pdf from here --> https://english.ncsc.nl/publications/publications/2019/juni/01/it-security-guidelines-for-transport-layer-security-tls )
(See a 2015 technical paper on an experimental attack here --> https://weakdh.org/ ) 

They recommend using ECDHE for the algoritm since the keys are replaced and destroyed which eliminates the possibility of decrypting the past traffic.

**Comment by charlag** [comment]
Hi
We are tracking this internally already.

**Comment by charlag** [comment]
This should be fixed now, thanks for the links!
