### ISSUE TITLE
Forward button is duplicated

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2039]
![image](https://user-images.githubusercontent.com/3099142/81265526-882bc580-9043-11ea-95e2-8350c0682de6.png)

**Comment by joshuaobrien** [comment]
Mind if I pick this one up @charlag?

**Comment by charlag** [comment]
Feel free to. We might need this for the release after next one but it should be a 2 minute fix.

**Comment by joshuaobrien** [comment]
PR here #2043 :)
