### ISSUE TITLE
Unsubscribe from newsletters and mailing lists

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#204]
Add an "Unsubscribe" button to the client for all newsletters and mailing lists that send the "List-Unsubscribe"-Header.

We need to add a new List-Unsubscribe attribute to the model of the body and parse the List-Unsubscribe header into it on the server.

**Comment by armhub** [comment]
- Newsletter from heise.de can not be unsubscribed -> BadGatewayException
- BadGatewayException when unsubscribing: Try to unsubscribe again is possible (batch was canceled because of exception)

**Comment by armhub** [comment]
Unsubscribe header for heise.de:
List-Unsubscribe: <http://newsletter.heise.de/d?q000ziwq0b4ub40il0000kjq000000000hjy0uyy1076>, <mailto:news_heise_zeitschriften@inxserver.com?subject=unsubscribe%20params%3Db0000in00b4ub4000cduqc000000000b2o07qsfht>

**Comment by armhub** [comment]
fixed on server
