### ISSUE TITLE
Unable to change my default mailing app from Tutanota on Android 10

### ISSUE THREAD

**Issue by ContentPersonality2** [tutao/tutanota#2046]
Hello, I've got a video [here](https://streamable.com/92wj76). As you can see I'm unable to change my default mailing app from Tutanota. My device is a OnePlus 6T and it's running Android 10 (OxygenOS 10.3.3).

If anyone else is having this issue please comment as it'd be nice knowing I'm not the only one.

**Comment by charlag** [comment]
Hi
I think it has nothing to do with us.
On Android 9 I don't even have a selector for default email app and we certainly don't do anything special to make ourselves default, we just tell the system "yes, we can send emails":
https://github.com/tutao/tutanota/blob/30ec166c30952caeb9da113704988bfad0ef0c0a/app-android/app/src/main/AndroidManifest.xml#L35-L42
