### ISSUE TITLE
Blocked by "Number of attempts exceeded" after aborting successful login

### ISSUE THREAD

**Issue by heyheyhello** [tutao/tutanota#2048]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**

When logging in to Tutanota it's easy to accidentally forgot the "Store credentials" tick box. This has happened twice to me in the last few days while migrating to a new laptop. I have 2FA enabled, and when I click "Log in" it shows me the 2FA dialog but I click "Cancel" because I want to tick "Store credentials" before continuing. However, clicking "Log in" for the second time yields _"Number of attempts exceeded please try again later"_.

The password is correct. I logged in correctly. So... seems weird. Also, why is the number of attempts set to 1?

**To Reproduce**

1. Go to login page
2. Click on login
3. Cancel 2FA dialog
4. Try again

**Expected behavior**

It lets me login.

**Screenshots**

Here's a GIF

![Peek 2020-05-11 10-27](https://user-images.githubusercontent.com/44614862/81592029-2daba580-9372-11ea-85a6-f6787a2c9016.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 72

**Comment by charlag** [comment]
I vaguely remember that there was a security reason why it must work like that but I didn't have a chance to clarify it yet. I'll answer when I'll find out for sure.

**Comment by heyheyhello** [comment]
Is pressing cancel considered a failed login?

**Comment by mpfau** [comment]
@heyheyhello no, but we only allow one concurrent login and that one is not cancelled yet.

**Comment by mpfau** [comment]
Test notes on server side issue 573
