### ISSUE TITLE
Not receiving notifications on any devices

### ISSUE THREAD

**Issue by marissarousseau** [tutao/tutanota#2049]
I originally thought I wasn't receiving notifications on my Google Pixel 3 running the GrapheneOS custom ROM (based on Android 10). After some testing, I am not receiving notifications no matter which device I use. I tried the macOS desktop application as well as the web app and do not receive notifications through those platforms either.

**Comment by charlag** [comment]
This was a server-side issue after the last release, it should work now.

**Comment by ebroto** [comment]
I ran into this today, at least on my phone (Android)

**Comment by marissarousseau** [comment]
I ran into it today and yesterday as well. Didn't notice some emails unless I manually checked the app.

**Comment by mpfau** [comment]
@ebroto and @marissarousseau Thanks for reporting! This was a different issue and seems to have only caused troubles with Android but it has been fixed now.

**Comment by ebroto** [comment]
Thanks! I can confirm it's fixed
