### ISSUE TITLE
Clicking on Tutanota notifications opens up both Tutanota app and Qbittorrent

### ISSUE THREAD

**Issue by ThracianKnight1907** [tutao/tutanota#2054]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Just as the title says.

**To Reproduce**
1. Install Qbittorrent and Tutanota, set them both to run in tray (i use appindicator extension for this)
2. Receive a notification from Tutanota (like an email)
3. Clicking on it opens both apps

**Expected behavior**
Only tutanota would have opened

**Desktop (please complete the following information):**
 - OS: Fedora 
 - Desktop Environment, if applicable (on Linux) Gnome 3.36.2
 - Version: 32

**Additional context**
THis doesn't happen with other apps' notifications. If I click a software center notifications qbitorrent isn't launched.

**Comment by charlag** [comment]
Hi
I would make an educated guess that we have nothing to do with this, sorry

**Comment by ganthern** [comment]
Just out of curiosity, does QBittorrent have notifications and do they open Tutanota?

**Comment by tp0** [comment]
I think this has something to do with the appindicator/notify libraries many Linux DEs use. Same thing happens (qBittorrent opens) with plain Chromium on Xubuntu (Xfce).

**Comment by ThracianKnight1907** [comment]
It has but they don't open anything, not even the app itself

**Comment by ganthern** [comment]
There's an Issue on qBittorrent's repo: https://github.com/qbittorrent/qBittorrent/issues/9084 

I'll close this one.
