### ISSUE TITLE
Unknown error when opening pdf attachment

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2055]
This was reported by a user today that an unexpected error was shown when opening an pdf attachment in the desktop client. I don't think this happens very often but we should catch the error and show an error dialog that something went wrong. Something like "Failed to open attachment". Best would be to identify why this error occured but i am not sure if it is because of the filename or a decryption problem.

```
Client: win32
Type: PREMIUM
Tutanota version: 3.72.0
Timestamp (UTC): Wed, 13 May 2020 21:11:18 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.72.0 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36
Error
Error message: UNKNOWN: unknown error, open 'C:\Users\<username>\AppData\Local\Temp\tuta\foo bar $605.14.pdf'
Stacktrace:
Error: UNKNOWN: unknown error, open 'C:\Users\<user>\AppData\Local\Temp\tuta\foo bar $605.14.pdf'
```

**Comment by ganthern** [comment]
I was (expectedly) unable to reproduce the problem with that file name.

#2065 aims to somewhat salvage the user experience if stuff like this happens, but may need some work to not catch too many errors.

**Comment by mpfau** [comment]
could trigger another error dialog by going offline while downloading the attachment. The "failed to download attachment" dialog was displayed and in addition the native error dialog.

```
Feedback v3.74.0 - Error - PREMIUM - linux
Client: linux
Type: PREMIUM
Tutanota version: 3.74.0
Timestamp (UTC): Tue, 02 Jun 2020 09:09:31 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.74.0 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36
Error
Error message: ENOENT: no such file or directory, unlink '/tmp/tuta/visualvm_201.zip'
Stacktrace:
Error: ENOENT: no such file or directory, unlink '/tmp/tuta/visualvm_201.zip'
```
