### ISSUE TITLE
Feature: haveibeenpwned Notification

### ISSUE THREAD

**Issue by K73SK** [tutao/tutanota#2056]
Hi,

I imagine many of us have the premium subscriptions and take advantage of the email aliases. I know I do, where I use a unique alias for just about every website I have an account on. However, having to go to haveibeenpwned.com and manually input all those aliases to see if any have been compromised can be kind of a hassle. I know I can probably create a quick script I run every time a new data source is uploaded, hitting their API to see if any of my accounts were compromised, but I thought it'd be a cool feature for Tutanota to notify users when their account email or one of their aliases were compromised in a data breach.

**Comment by charlag** [comment]
Hi
To keep repository manageable, we don't accept feature requests here.
Please use https://www.reddit.com/r/tutanota or https://tutanota.com/contact/ to discuss features.
Thanks for understanding!
