### ISSUE TITLE
Tutanota references visible with whitelabel for normal users

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2057]
- invitation email -> remove for non-admins
- settings: recovery code -> remove recovery code for non-admins
 - settings: 2FA -> remove info link for non-admins

**Comment by bedhub** [comment]
We also need to remove these references
- Disable JavaScript in browser -> Message is shown "Tutanota requires JavaScript to be enabled". We can replace it with "This site required JavaScript to be enabled"
- When the developer console is opened we show the Tutanota job advertisment. We should remove that on whitelabel domain.

**Comment by johnbotris** [comment]
Regarding support email, should we also disable the FAQ search for non admins and directly open a support mail editor?

**Comment by bedhub** [comment]
Test notes
- [ ] Check job advertisement in console log
- [ ] Check Java script disabled
- [ ] Check local admins have no recovery code settings Settings->Login
- [ ] Check info link has been removed

**Comment by jowlo** [comment]
Tested

* [x] Check job advertisement in console log
* [x] Check Java script disabled
* [x] Check local admins have no recovery code settings Settings->Login
* [x] Check info link has been removed
   - not completely removed, see #2448
* Check that recovery code option is not shown when 
             * [x]  a) create user, 
             * [x]  b) add second factor as admin for a user,
             * [x] c) add second factor as normal user.
* [x] Recovery code should be shown when adding 2fa as global admin for himself
