### ISSUE TITLE
[Windows] Automatic Updates don't work

### ISSUE THREAD

**Issue by Tumeez** [tutao/tutanota#2058]
Hello!

I noticed that automatic updates doesn't work even I set those "Activated". I need always upgrade Tutanota Desktop Client manually.

Tutanota Dekstop Client: 3.73.1
Windows: Win 10 Enterprise 1909, Build: 18363.836

Another good feature could be that I can check Tutanota Desktop Client version without needing log in first, so I suggest that you put version number also to login screen or title bar or something like that.

Thank you,

Tume

**Comment by charlag** [comment]
HI
May I ask how exactly it does not work?
It's a good suggestion to show version on login screen I think

**Comment by Tumeez** [comment]
> HI
> May I ask how exactly it does not work?
> It's a good suggestion to show version on login screen I think

Hello! It just doesn't update the program itself at all. It will be stucked at same version what I manually installed or updated. So I need every time update Tutanota manually.

**Comment by charlag** [comment]
@Tumeez I believe we might have improved that with backoff on upadate failures but it might take some time to update. Please let us know how the next update goes.
