### ISSUE TITLE
[desktop/windows] prevent reserved file names from being written (CON, NUL, ...)

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2063]
The windows client will happily create files named con.txt or nul.pdf if a default download path is set.

These names are reserved and the corresponding files can't be opened or deleted in a normal way.

The full list of reserved names can be seen here https://social.technet.microsoft.com/Forums/windows/en-US/e22c021d-d188-4ff2-a4dd-b5d58d979c58/the-specified-device-name-is-invalid

a solution could be to handle these names as if the file already exists and to assign the next non-colliding name (so for example con.txt -> con-2.txt if con-1.txt exists)

**Comment by bedhub** [comment]
I have not checked the implementation yet but it would be great if we can also take care of the export case:

https://github.com/tutao/tutanota/issues/2036

Regarding the problem of reserved filenames we also need a solution for the web interface.

**Comment by ganthern** [comment]
Firefox, Chromium and Safari handle the sanitization and filename collisions for the web interface except in the case of same filename, same content - safari will replace the file instead of giving it a non-colliding name.

#2093 also solves the export problem for the desktop client on all platforms.
