### ISSUE TITLE
Closed sessions show only the desktop sessions but mobile app

### ISSUE THREAD

**Issue by albertociccone** [tutao/tutanota#2064]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**
Closed sessions show only the desktop sessions but mobile app.
In the Tutanota webapp and also in the mobile app, in the settings can opt in to show the closed sessions.
It show the closed session only if they were in webapp but it show neither in the web app nor the mobile app the closed mobile app sessions in the list.
It show only the last closed session for the mobile app, and also all the closed webapp sessions.

**Describe the bug**
Please see it above.

**To Reproduce**
1. Go to the options menu and activate the logging.
2. Click on list.
It is useful to logout and login again several times to see a generated list.
Please use both the webapp (tested with Firefox 76.0.1 64bit) and also the Android app v3.73.1
3. Scroll down the list of the closed sessions.

**Expected behavior**
Show the closed sessions what were initiated from Android device.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [76.0.1 64 bit]

**Smartphone (please complete the following information):**
 - Device: [Android phone]
 - OS: [9]
 - Browser [Tutanota app]
 - Version [3.73.1]

**Additional context**

Thank you!

**Comment by charlag** [comment]
Hi
How did you close your session on mobile? Do you have password saved?

**Comment by albertociccone** [comment]
Hi Ivan,

I checked the session on my mobile and realized, that the session was active all the time, in spite I logged out from the app. After I closed the session in the webapp, it showed in the list of the closed sessions, so it works without any problem. Sorry, this was my bad.
Please consider this ticket solved.

Have a great day!

**Comment by charlag** [comment]
@albertociccone when you save the password, session becomes permanent and logging out doesn't close it. If you remove saved credentials from login screen it will be closed.
Thanks for reaching back.
