### ISSUE TITLE
[FEATURE PROPOSAL] Option to hide calendar/contacts

### ISSUE THREAD

**Issue by ralxxx** [tutao/tutanota#2066]
I am proposing a modification to the UX

I am happy about the introduction of the calendar and address book features, but for those who do not need it, it would be great if the buttons for Calendar and Contacts could be hidden from the main screen. 
- If the calendar icon would be hidden, the respective icon could simply vanish.
- The same for the address book. 
- If at the same time the buttons are removed from where they are now and (if needed) put to the left side, the appearance could be simplified and more space could be set free for email. 

How this could like like please see below: 

As it is now
![Tuta-b4](https://user-images.githubusercontent.com/36100882/82321450-21a88f00-99d5-11ea-9b34-1b718dfda8d9.jpg)

As it could look like:
![Tuta-projection](https://user-images.githubusercontent.com/36100882/82322577-076fb080-99d7-11ea-9322-7a37939356d4.jpg)

the mobile apps would need an adaptation as well, but the gain in terms of space (in case of not used calendar/contacts would be even more important

**Comment by charlag** [comment]
Hi
to keep repository manageable, we don't accept feature requests here. Please use reddit or support for feature requests.
Thanks for understanding.
