### ISSUE TITLE
Login in Brave browser not possible any more

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#207]

**Comment by jonathansampson** [comment]
Is `indexedDB.open` called from a script hosted on another domain/origin? If so, that is likely the problem. Brave prevents _third-parties_ from accessing local storage. Users would have to explicitly permit third-party storage to avoid this problem.

**Comment by mpfau** [comment]
No, we are loading all scripts from a single domain (our own).

**Comment by mijiturka** [comment]
I can confirm seeing this (getting stuck on the login screen) in Brave 0.20.42 on mail.tutanota.com with all of its shields down. app.tutanota.com works fine.

**Comment by jonathansampson** [comment]
@mijiturka To clarify: you *are* able to login from app.tutanota.com, but you *are not* able to login from mail.tutanota.com. Is that correct?

**Comment by ptrwllrd** [comment]
@jonathansampson Yes, the issue is exclusive to the beta platform.

**Comment by mpfau** [comment]
@jonathansampson we don't use indexeddb at app.tutanota.com, only on mail.tutanota.com (beta).

**Comment by janos-szenfner** [comment]
please fix it.

**Comment by charlag** [comment]
Checked upstream, staging and released version with Brave 0.23.39 and following settings

setting | value
---------|-------
Ad control | Block ads
Cookie control | Block 3rd Party Cookies
Fingerprint protection | Block all fingerprinting
HTTPS Everywhere | on
Block Phishinhg / Malware | on
Block scripts | off

and did not experience any problems. Can anyone in the thread confirm that it works?
