### ISSUE TITLE
Optional integration of calendar with Android system calendar

### ISSUE THREAD

**Issue by snaggen** [tutao/tutanota#2080]
I use multiple calendar sources, a shared work, another shared family, some webcal subscriptions. Hence, I need a calendar that aggregate that, so I use Etar fot this. 
It would be great if Tutanota Calendar would work as a calendar provider for the Android system calendar, and hence be usable from within Etar and other calendars.

**Comment by charlag** [comment]
Hi
to keep repository manageable we don't accept feature requests here.
see https://tutanota.com/contact/
Thanks for understanding.
