### ISSUE TITLE
Error message is shown each time update fails 

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2081]
Created new issue to cover one part of the problem of issue #2032. 

- users will now be notified of an update failure after the 5th error
- update checks now implement random exponential backoff
- different versions of the app can now steal the single instance lock
from each other, terminating the already running instance

**Comment by charlag** [comment]
Tested it locally by:
1. Building a local client
2. In build/desktop-snapshot/latest-linux.yml changed `version` to a higher one and `files.url` to invalid one
3. Changed interval in electron-package-json-template.js to a smaller one to test more easily

After that can observe checking for updates. Can add additional logging when update is scheduled. Saw that it stops and shows notification after 5 tries.
