### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by pyro-dev** [tutao/tutanota#2089]
When using the desktop client and trying to open an attachment, this fails and I get a message about an expired certificate.
Here is the contents for the error itself

> Feedback v3.73.1 - Error - PREMIUM - win32
> Client: win32
> Type: PREMIUM
> Tutanota version: 3.73.1
> Timestamp (UTC): Wed, 03 Jun 2020 00:43:13 GMT
> User agent:
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.73.1 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36
> Error
> Error message: certificate has expired
> Stacktrace:
> Error: certificate has expired
> at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
> at TLSSocket.emit (events.js:210:5)
> at TLSSocket._finishInit (_tls_wrap.js:794:8)
> at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
> 

1.Select an email with attachments
2. Click on an attachment and select "open"

 - OS: Windows 10 1909
 - Version 3.73.1

**Comment by charlag** [comment]
@pyro-dev hi, thanks for reporting. Does it only happen with attachments? Does downloading (not opening) work for them? Thanks

**Comment by pyro-dev** [comment]
I could download them without problem it seems. Only opening generated an error.
I'm also using Tutanota on IOS and no issue to report there either.

**Comment by bedhub** [comment]
With release 3.74.2 we will catch the unkown error now and show a message that the file could not be opened. https://github.com/tutao/tutanota/issues/2055

When testing the desktop client i also noticed this error and  i am able to reproduce this case each time when opening an attachment or use download on on inline image with right click.

**Comment by mpfau** [comment]
fixed on server side
