### ISSUE TITLE
Improve process for adding custom email domain

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2092]
Users are often confused how they can connect their custom domain to a Tutanota account. We have a howto entry which explains the steps (https://tutanota.com/howto#custom-domain) but there are still some pitfalls were users can make mistakes.

1. In the "Add domain" dialog it is not understandable that they need to add another TXT record to proof domain ownership.  They have read the howto entry and configured MX and TXT records properly but when adding the domain in Tutanota they must add another TXT record.

2. In the "Add domain" dialog the users don't know which domain they should enter. They are trying to add a subdomain like www.example.com instead of their main domain example.com

3. After successfully passing the domain ownership we show the "Check DNS records" dialog which users can understand and also solve but then they don't understand if they should create email aliases or users and were they should add them.

**Comment by bedhub** [comment]
My proposal is to create a wizard dialog which guides the user through all the steps. It should not be necessary to have such a detailed howto entry, the dialog should be self explaining.

The steps for such a wizard which i have in mind are:

1. Enter domain
2. Do domain ownership validation
3. Create email aliases for main account
4. Validate other DNS record (MX, SPF, DMARC, MTA-STS)

I created a mockup with our current ui elements. Needs some polishment but this is how it can look like.



![add-domain-wizard-step1](https://user-images.githubusercontent.com/8296817/83846565-13fc4480-a70b-11ea-87ba-921401b6e33e.png)
![add-domain-wizard-step2](https://user-images.githubusercontent.com/8296817/83846601-24acba80-a70b-11ea-869e-70105f3f0c47.png)
![add-domain-wizard-step3](https://user-images.githubusercontent.com/8296817/83846611-29716e80-a70b-11ea-95b5-6f7813840e92.png)
![add-domain-wizard-step4](https://user-images.githubusercontent.com/8296817/83846625-2c6c5f00-a70b-11ea-9fd9-4027141e1059.png)

**Comment by armhub** [comment]
Looks good! When adding an alias, we should also show the option to set the alias as default sender.

**Comment by charlag** [comment]
I'm not sure why we first add aliases and then DNS records

**Comment by bedhub** [comment]
The main reason is that emails are getting rejected when no email alias is configured.

**Comment by vaf-hub** [comment]
Test notes:

- [ ] check signup and subscription wizards

- [ ] add custom email domain, configure alias, add users, skip adding users/aliases, 

- [ ] check if dns customDomainCheckReturn results are correctly displayed with missing, invalid and too many records

- [ ] finish wizard without all values being set up and resume it later

**Comment by mpfau** [comment]
On the last page of the wizard, the finish action can be triggered twice (by keyboard) which leads to the following error:
```
Cannot read property 'checkResult' of null
    at VerifyDnsRecordsPage.js:56
```

**Comment by armhub** [comment]
How-to entry is not updated: https://tutanota.com/howto/#custom-domain

**Comment by armhub** [comment]
We should test this with the old client, too.
