### ISSUE TITLE
Allow cancel unsubscribe from Premium

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2094]
If you unsubscribe from Premium (select Free subscription) it is currently not possible to cancel this and restore the Premium subscription by the user.

**Comment by bedhub** [comment]
fixed on server:

Test hint:
- upgrade to premium
- downgrade to free
- upgrade again

**Comment by mpfau** [comment]
Works fine. The customer is not debited immediately, this will happen with the next debit job.
