### ISSUE TITLE
Dates are formatted incorrectly in chrome and desktop client

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2096]
Should be 00:46 instead of 24:46. Looks like a bug in chrome but we should try using "hourCycle" property instead of  "hour12"

![invalid-date-format](https://user-images.githubusercontent.com/8296817/83895492-0b2f6100-a753-11ea-993c-cf1e4401f812.png)

Can easily be reproduced in browser console using

`tutao.lang.formats.dateTime.format(new Date(2020, 05, 05, 0))
`

https://support.google.com/chrome/thread/29828561?hl=en

**Comment by charlag** [comment]
`hourCycle` is a new property, there's a reason why there's no flow definition yet.
Chrome >= 73, FF >= 58, Safari > 13

see here
https://caniuse.com/#feat=mdn-javascript_builtins_intl_datetimeformat_datetimeformat_hourcycle

or here in support table in the bottom
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

**Comment by charlag** [comment]
Another option is to append needed hour cycle to the locale name.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#Syntax

**Comment by bedhub** [comment]
Tested with adding "hc" tag to local name but it seems that the flag is also not supported when hourCycle is not supported (tested with older Safari 11 browser). As older browsers are just ignoring the hourCycle flag when not supported i guess we can just use the implementation from commit 2a40656. All modern browsers now support this flag.

**Comment by charlag** [comment]
I agree, as long as there are no errors I think we can just use it.
