### ISSUE TITLE
Update model version for native wrapper classes

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2099]
Mainly for downloading MissedNotifications but also for other requests we do in the native part.
* For Android we have to adjust model version. 
* For iOS we have to define the model version and send the model version for MissedNotification requests
* Check if there are other places were we need to send the model version
* Check desktop application as well. Do we already use generated classes in the native part of the desktop application?

**Comment by charlag** [comment]
Yes, we use generated classes in Desktop and we send correct versions there:
https://github.com/tutao/tutanota/blob/b6702cf48126557897c1cf3951f3b0d6d9f3c329/src/desktop/sse/DesktopSseClient.js#L152

**Comment by johnbotris** [comment]
- [ ] Test Android
- [ ] Test iOS
- [ ] Test desktop
