### ISSUE TITLE
Cannot import calendar ical files

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2101]
There are cases were we fail to import calendar files. Some cases were reported were the file does not comply to the RFC but i think we should be more lenient with our parser to allow such cases.

* [x] Missing UID property [calendar-without-uid.txt](https://github.com/tutao/tutanota/files/4746988/calendar-without-uid.txt)
* [x] Alarm without action [alarm-without-action.txt](https://github.com/tutao/tutanota/files/4747029/alarm-without-action.txt)
* [x] Properties that are not well-formed according to the in RFC like `CATEGORY_COLOR` which has underscore in it. [calendar-with-custom-property.txt](https://github.com/tutao/tutanota/files/4753027/calendar-with-custom-property.txt)
* [x] Invalid alarm triggers like `TRIGGER;RELATED=START:P` (seem like it was send from some exchange servers :P can be handled as :PT0S.)

**Comment by jowlo** [comment]
> 4\. Invalid alarm triggers like `TRIGGER;RELATED=START:P` (seem like it was send from some exchange servers :P can be handled as `:PT0S`.)

7ee3026 takes care of the `:P` one during parsing. Do we know of any other formats that need to be accepted?

**Comment by jowlo** [comment]
From what i can tell we assume that every calendar event has a `uid` set. Thus,  25ea27fa55 creates a new uid similar to our `${groupid}-${Date.now()}@tutanota.com` format as `import-${Date.now()}@tutanota.com` if no uid is set on the event to parse.

**Comment by jowlo** [comment]
## Test notes
 - [ ] import calendar-without-uid.txt twice, there should be a new event for each import (new generated id)
 - [ ] make file with `TRIGGER;RELATED=START:P` and there should be an alarm at the beginning event

**Comment by sarashub** [comment]
>     * [ ]  import file with `TRIGGER;RELATED=START:P` and there should be an alarm at the beginning event

Can be imported but there is no reminder at all (same for :PT0S)
