### ISSUE TITLE
"Save all" attachments and "Export" opens a download confirmation dialog for each file

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2104]
When you press "Save all" for the attachments of an email there is currently a download location confirm dialog for each attachment. We should find a way to ask for the download location only once for all attachments. 

The current workaround is to set a default download location in the web browser or in the desktop client but this problem is reported often in support and maybe we can do better.

**Comment by mpfau** [comment]
Test notes:
- [ ] Download multiple attachments with Firefox
- [ ] Download multiple attachments with Chrome
- [ ] Download multiple attachments with Desktop client on Linux
- [ ] Download multiple attachments with Desktop client on Mac
- [ ] Download multiple attachments with Desktop client on Windows
- [ ] Export multiple mails with Firefox
- [ ] Export multiple mails with Chrome

**Comment by charlag** [comment]
I would check Safari as well

**Comment by mpfau** [comment]
save all is not displayed on ios

**Comment by charlag** [comment]
It is not available on ios
