### ISSUE TITLE
Auto-cleanup TTL setting on email folders

### ISSUE THREAD

**Issue by localstorm** [tutao/tutanota#2109]
Hi,

It would be super useful feature to set maximum time to live duration for certain email folders. For instance, I sign up for some news letter. No reason to keep this stuff for more than a couple of months. Having some automated clean up is basically the same thing we have in Spam folder, I just don't see why it has to be only limited to Spam.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
