### ISSUE TITLE
Calendar events in some time periods cannot be loaded

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2114]
To reproduce:
1. Create an event on 8th of November 2018 (works with all-day and non-all-day events)
2. Reload the app
3. Open November 2018
4. Observe no event

Seems like we are filtering events out on the client.

**Comment by charlag** [comment]
Check loading of statistics logs in contact form.

**Comment by bedhub** [comment]
Were not able to check statistic logs because of this issue.
https://github.com/tutao/tutanota/issues/2154
But loading of calendar events is fine.
