### ISSUE TITLE
Maximized window state is not saved

### ISSUE THREAD

**Issue by aetherbrain** [tutao/tutanota#2115]
Just noticed that window size, or maximized/custom size is reset on every reset. Win64.

**Comment by charlag** [comment]
@aetherbrain "on every reset"?

**Comment by aetherbrain** [comment]
Yes. Same problem on two computers running win10 pro on one and win10 home on the other, both x64
23. jun. 2020, 09:20 av notifications@github.com:

**Comment by charlag** [comment]
I'm sorry, I don't understand what "on every reset" means. On every reboot?

**Comment by aetherbrain** [comment]
Sorry, i should have been more specific. Even though I exit with the window maximized, the app starts up with the window not maximized after i exit the app and restart it, also after reboot. As said, i minor inconvenience at the most..

Regards,

Aeth
23. jun. 2020, 10:22 av notifications@github.com:

**Comment by charlag** [comment]
@aetherbrain do you still experience this? I think we do not save maximized state yet.

**Comment by aetherbrain** [comment]
Yes. Maybe it's just my computer. Running windows 10 home x64.


Jul 28, 2020, 13:38 by notifications@github.com:

**Comment by ganthern** [comment]
Can't reproduce it in 3.98.20 (linux or windows, fullscreen or just maximized. works fine).

Note that the saved window state will be the one of the last closed window, so if you use multiple windows, some of which are not maximized, that may be the reason.
