### ISSUE TITLE
Canceling of message deletion leads to disappearing message

### ISSUE THREAD

**Issue by sgabler-solytic** [tutao/tutanota#2117]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

Message disappears if I cancel my attempt to delete a message.

**To Reproduce**

- I swipe left on a message
- A popup appears, which i cancel
- The message is gone

**Expected behavior**
I would expect that the message is still there after clicking on cancel

**Screenshots**
![ezgif-6-35e44cd7ce91](https://user-images.githubusercontent.com/55686147/85161544-33918200-b260-11ea-98bd-0c43392bea08.gif)

**Smartphone (please complete the following information):**
 - Device: Honor 8
 - OS: Android 8.0.0
 - Version: Tutanota 3.73.1

**Additional context**

**Comment by RiverAT70** [comment]
https://github.com/tutao/tutanota/issues/1935

**Comment by sgabler-solytic** [comment]
The good thing is that the message is not actually deleted. If you leave the screen and come back, the message appears again. So it seems to be only a visual issue

**Comment by charlag** [comment]
Thanks for reporting, we should fix this (and it should be an easy fix)

**Comment by bedhub** [comment]
Happens again with version 3.81.7, click cancel but mail disappears from list.

**Comment by charlag** [comment]
Seems like it's only on mobile so I move it out
