### ISSUE TITLE
Delete swipe animation on iOS 14 is slower and choppy

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#2122]
**Bug in mobile app**

**Describe the bug**
The delete animation is slower and choppy 

**To Reproduce**
Delete swipe on a email and the animation is slower and choppy on iOS 14
**Expected behavior**
It should not be choppy the delete swipe animation 

**Smartphone (please complete the following information):**
 - Device: [iphone se 2nd gen
 - OS: iOS 14
 - Version [3.7.3.0

**Comment by charlag** [comment]
Please wait until the later iOS version, it doesn't make sense to fix anything in early iOS betas, they break things each time and it's normal.

**Comment by charlag** [comment]
I think it's not the case anymore?

**Comment by vitoreiji** [comment]
I don't know, there was a complaint from a user on support, recently. Do we have a device to test?

**Comment by Pa7Hub** [comment]
I have a iOS 14 phone and tested it, not choppy for me, but I know for a fact that some apps (Spotify does this alot for me) act very choppy when sliding sometimes, I couldn't figure out under which conditions that applies though.

**Comment by Pa7Hub** [comment]
I managed to reproduce the choppy slide bug in Spotify (and sometimes in other apps) when sliding with an open keyboard. (Happens 1/10 times) I don't see a way to slide-delete stuff with an open keyboard in Tutanota though?

**Comment by charlag** [comment]
I'm not sure what to do with it, @vitoreiji was there some more info?

**Comment by charlag** [comment]
wasn't really reported lately
