### ISSUE TITLE
Feature Request: Apply Spam/Inbox rules using TLD

### ISSUE THREAD

**Issue by mtris** [tutao/tutanota#2123]
Dear Tutanota Team: First, excellent job with your email suite. 

Would it be possible to filter spam messages using the Top Level Domain? It has been convenient using the domain to filter messages, but I notice waves of spam with obscure TLDs (ex: .xyz, .guru, .icu, etc.) that could be handled quickly with a single rule instead of infinite additions from random domain names.

Thank you for your time and consideration. Your devotion to privacy is remarkable. Sincerely,

**Comment by vitoreiji** [comment]
Hi
To keep repository manageable we don't provide support or accept feature requests here. Please see README or https://tutanota.com/contact for other options.
