### ISSUE TITLE
Images are not visible

### ISSUE THREAD

**Issue by adlgrbz** [tutao/tutanota#2128]
Image links are not visible...

OS: `GNU/Linux Debian Buster`
Desktop Environment: `Xfce 12`
Version `3.70.0`

![resim](https://user-images.githubusercontent.com/40023234/86222808-65271900-bb8f-11ea-90e6-6872c529fa07.png)

**Comment by charlag** [comment]
There's a button to load images in the button bar

**Comment by adlgrbz** [comment]
Ohh sorry... Thanks.
