### ISSUE TITLE
Default search index is to small

### ISSUE THREAD

**Issue by snaggen** [tutao/tutanota#2138]
Whenever I need to search on a new device and enter my search term, I'm asked to enable the search index. I then do that and it fetches a few mails and index them and I never find what I'm looking for. Then I have to go in to the sidebar and look, just to see that the index is only for today. What is the use case here, when do people only want to search for mails they got today? Whenever I use a search function it is because I cannot remember exactly when and were the information is, which always means it is not from today. 

I suggest that the dialog to enable the index contains a dropdown asking from when to index with, today, this week, this month, this year, and everything as options. What the default should be might be hard to decide since most people might have different preferences, but at least this month (I would prefer everything). 

Also, the date selector in the search side bar should have and "everything" option.

**Comment by snaggen** [comment]
Just realized that leaving the entry blank in the search range means "everything". So, maybe just make it more discoverable.

**Comment by charlag** [comment]
It's acceptable search index for free users which prevents excessive server load

**Comment by snaggen** [comment]
Fair, but for us paying customers it would still be nice with a larger default index.
