### ISSUE TITLE
Add SAML / SSO support

### ISSUE THREAD

**Issue by tormoon91** [tutao/tutanota#2139]
It makes sense for organizations to use tutanota for their business.
SSO will allow tutanota to be added to the suite of tools that businesses use by allowing for login without the annoying username and passwords.

In addition, centralized control of accounts is important for many businesses.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
