### ISSUE TITLE
Migrate to WebAuthn (WebAuthentication) for 2FA

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2140]
Chromium is about to deprecate U2F API.
It will mostly be disabled in February 2022. We need to migrate existing clients.
https://groups.google.com/a/chromium.org/g/blink-dev/c/xHC3AtU_65A

Before doing the migration we should check whether we can make it compatible with mobile apps in the future (#2177, #443, #2178).

Acceptance criteria:
 - [ ] Existing keys should still work
 - [ ] It is possible to add new keys

---
Test notes:
 - [x] U2F: Old client, old key. Still possible to authenticate (using old client add U2F second factor in settings and then log in using said second factor)
 - [x] U2F: new client, old key. Still possible to authenticate (using old client add a key. Using new client authenticate)
 - [x] U2F: new client, new key (add key, try to log in):
   - [x] Success
   - [x] Cancel our dialog (key stops blinking and it's possible to log in again right away)
   - [x] Timeout after one minute
   - [x] Wrong key lets you retry
   - [x] Cancelling via browser or system API lets you retry
 - [ ] Check that it's possible to add U2F key in web but not possible to add it on mobile or in desktop app)
 - [x] Check that it's possible to authenticate with U2F key in web but not possible to do it in mobile or desktop app
 - [ ] Add OTP code
   - [x] web or desktop (QR code displayed and works)
   - [ ] Android (button to open OTP app still works)
 - [x] Add key on our domain. Try to log in on whitelabel domain. Message should be displayed that there are no compatible keys
   - [x] Add key on whitelabel domain as well. Should still be possible to authenticate on both
 - [x] Test confirming login from another client
   - [x] Test that U2F is cancelled and dialog is closed on the waiting side
 - [x] Test cancelling 2FA prompt
 - [x] Test logging in using 2FA
 - [x] Both U2F and TOTP prompt can be displayed on the 2FA dialog
 - [x] Recover login displayed when clicking on 2FA link
 - [x] Recover login is *not* displayed when resetting second factors from the login screen ("recover login"0

**Comment by charlag** [comment]
About the app compatiblity.
It seems like there are two ways: either opening custom browser tab with a prompt or using some SDK. There are pros and cons for both but I would vote for the web solution just because it seems easier and more straightforward.

see https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Desktop_and_Mobile_Authentication.html
see https://developers.yubico.com/WebAuthn/Supporting_U2F_or_FIDO2_Security_Keys_on_iOS_or_iPadOS/Paths_for_Supporting_U2F_or_FIDO2_Security_Keys.html
see https://www.rfc-editor.org/rfc/rfc8252#appendix-B

cc @bedhub

**Comment by bedhub** [comment]
- [ ] Cannot authenticate with a second key that has been added with the new client. The first key still works ( added with old client)

**Comment by charlag** [comment]
@bedhub I cannot reproduce the problem with 2 keys locally

**Comment by charlag** [comment]
We reproduced it locally now

**Comment by charlag** [comment]
The issue is on the server, U2F and Webauthn keys should be grouped together into one challenge

**Comment by charlag** [comment]
Closed on the server (issue 976)

**Comment by AydroPunk** [comment]
Forgive my ignorance, so today, tuta already uses FIDO2 (with the WebAuthn protocol)?
I read tuta's blog and saw that they use the old U2F protocol.
[https://tuta.com/es/blog/why-u2f-is-important](url)
