### ISSUE TITLE
Add progress indicator that email list is updated

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2142]
We need an indicator when the email list (inbox folder) downloads new emails, especially for mobile apps. We are receiving a lot of complaints that people don't see the new email after they clicked on a push notification.

Scenario:
1. App is in Background with logged in user
2. User receives push notification and clicks on it
3. App moves to foreground and inbox list opens -> new email is not shown yet
4. App establishes web-socket connection, downloads new entities and decrypts them.
5. -> No progress indicator is shown during that time and user thinks that that the mail list is up to date.

**Comment by vaf-hub** [comment]
test notes:

- [ ] go offline, receive some mails, go back online and watch progress bar
- [ ] test gui when offline in different views (emails, search, calendar, contacts)
- [ ] test with different screen sizes and on apps
