### ISSUE TITLE
[macOS] Printing order process agreement shows invalid characters

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2145]
Use the latest macOS desktop client to print the order process agreement. It will only show some garbage characters. 
[garbage.pdf](https://github.com/tutao/tutanota/files/4903704/garbage.pdf)

Seems to be only happening with latest macOS version.
Tutanota desktop: 3.75.0
MacOS: 10.15.5

**Comment by charlag** [comment]
Check if it's fixed with Electron 9

**Comment by bedhub** [comment]
Seems like the update of electron fixed the issue.
