### ISSUE TITLE
Please dont use RSA 2048 bits for your HTTPS-Key, use RSA 4096 bits instead

### ISSUE THREAD

**Issue by ofiqfakj** [tutao/tutanota#2146]
You are using RSA 2048 bits for your HTTPS-Key on your website. Please use RSA 4096 bits instead.

Here analysis: https://tls.imirhil.fr/https/tutanota.com

**Comment by mpfau** [comment]
4096 bit is not yet needed for transport encryption. One example for this is German BSI which recommends > 3000 bits from 2024 on. Until then, 2048 is secure enough for transport level encryption.

Therefore, we will do this at a later time.
