### ISSUE TITLE
Add more information about updates to desktop settings

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2151]
- show if there's an update ready to be installed
- add "check for update now" button

**Comment by charlag** [comment]
Both checking for update and clicking faq for tray trigger dropdown which is #2238 
Also checking for update is missing a redraw for when it's finished

**Comment by ganthern** [comment]
> Also checking for update is missing a redraw for when it's finished
The redraw was supposed to happen here:
https://github.com/tutao/tutanota/blob/edfea9481080f3dfc3710809e23a6bfd6ca635ae/src/settings/DesktopSettingsViewer.js#L246-L249

I am under the assumption that fixing #2238 will also fix the redraw issue, since it worked during development before DropdownN was changed.
