### ISSUE TITLE
RTL support in mail editor

### ISSUE THREAD

**Issue by ArtikBanana** [tutao/tutanota#2157]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web and smartphone apps**

**Describe the bug**
When writing in RTL languages, punctuation placed at the end of a sentence shows up at the beginning of it.
Inserting words from LTR languages such as English, changes the order of words in a sentence.

**To Reproduce**
1. Write a new email.
2. Write in an RTL languages and place a period at the end of it.
3. Period shows up at the beginning of the sentence.

**Expected behavior**
Punctuation and words from LTR languages should be placed where they are intended in RTL languages and not change the order of words in a sentence.

**Screenshots**

![Screenshot from 2020-07-18 16:58:00](https://user-images.githubusercontent.com/68469554/87854102-d6402d80-c8fe-11ea-9fc8-e1da11fd3ebd.png)

**Comment by charlag** [comment]
Hi
Could you please specify your environment (browser/OS and versions)?
Maybe we could set some special mode for the editor to fix punctuation but I think inserting English words will always reset RTL flow.
Does changing browser language help with this?

**Comment by ArtikBanana** [comment]
> Hi
> Could you please specify your environment (browser/OS and versions)?
> Maybe we could set some special mode for the editor to fix punctuation but I think inserting English words will always reset RTL flow.
> Does changing browser language help with this?

It happens in every device / environment I've tried. 
Windows 10, several Linux distros - Firefox 78.0.2 and Chromium 86.0.4210
Android 9 using the Tutanota app v3.73.1 and Firefox mobile 79.0.0-beta.9 + 68.10.1

Changing the browser's language doesn't help.

**Comment by ArtikBanana** [comment]
This works in Protonmail's app. Since it's open-source, maybe looking into it could help.

**Comment by charlag** [comment]
Do you mean web app or mobile app from them?

**Comment by ArtikBanana** [comment]
It works in both and both are open source.
https://github.com/ProtonMail/proton-mail-android
https://github.com/ProtonMail/WebClient

**Comment by charlag** [comment]
I tried out their editor and for them direction is only correctly set when plaintext is enabled (at least it works in the stable version).
I think we need to add `dir="auto"` to the mail editor element. If we need it per paragraph, then we need to set it to each element.

**Comment by ArtikBanana** [comment]
It works also in the "Normal" mode.
You have an option to choose between "Left to Right" and "Right to Left" for each paragraph.

**Comment by charlag** [comment]
Ah, I see, it's manual then.
I think having automatic is a good start.

**Comment by HassanHeydariNasab** [comment]
> I tried out their editor and for them direction is only correctly set when plaintext is enabled (at least it works in the stable version).
> I think we need to add `dir="auto"` to the mail editor element. If we need it per paragraph, then we need to set it to each element.

Setting `dir="auto"` to every element increases the size of email body unnecessarily; especially when the entire text is in a ltr language. Also, notice lack of `dir="auto"` on IE: https://www.w3.org/International/tests/repo/results/the-dir-attribute-auto

**Comment by charlag** [comment]
I don't think either is a compelling argument to be honest...

**Comment by HassanHeydariNasab** [comment]
As I said (https://github.com/tutao/tutanota/pull/2333#issuecomment-713679021) Gmail and Yahoo Mail don't use `auto`. it should has reasons.

**Comment by HassanHeydariNasab** [comment]
Outlook web client uses a manual approach.
![2020-10-23_10-48](https://user-images.githubusercontent.com/8642505/96968091-550bbe80-151d-11eb-8aad-68e81bc481f2.png)

**Comment by charlag** [comment]
Counterexample: Geary uses `auto`

**Comment by HassanHeydariNasab** [comment]
Geary adds `dir="auto"` attribute to the email body container. so the direction of the text depends on the first character of the first paragraph and the next paragraphs have been ignored.
![2020-11-02_13-47](https://user-images.githubusercontent.com/8642505/97856731-f2cb6e80-1d11-11eb-9806-6aaf93fad804.png)
I think that a good solution is adding `dir="auto"` to every paragraph.

**Comment by charlag** [comment]
Test notes:

 - [ ] Check that every HTML block has `dir="auto"`
 - [ ] Check that LTR text is aligned to the left
 - [ ] Check that RTL text is aligned to the right

**Comment by mpfau** [comment]
The initial blocks and blocks of the signature don't have the `dir` attributes.

**Comment by johnbotris** [comment]
> The initial blocks and blocks of the signature don't have the `dir` attributes.

We track this in #3181

**Comment by Asquator** [comment]
It seems proper RTL is still not supported with Hebrew.
Even if the text is aligned to the right, the punctuation gets messed up. Will this be fixed?
