### ISSUE TITLE
Mail is not deleted or moved into spam folder after reporting fishing email

### ISSUE THREAD

**Issue by guoyunhe** [tutao/tutanota#2158]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Mail is not deleted or moved into spam folder after reporting fishing email

**To Reproduce**
1. Go to inbox
2. Mark a mail as fishing email

**Expected behavior**
The mail should be moved to trash or spam folder

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charlag** [comment]
We already add a banner to it I think it would be confusing if it disappeared

**Comment by guoyunhe** [comment]
In GMail and Outlook, if you mark a mail as "Fishing", then it will be moved to trash folder. It is a well recognized design.

**Comment by charlag** [comment]
Thanks for the feedback, perhaps we should consider it
