### ISSUE TITLE
Subject line with forward slash caues export zip file to treat what comes before it as directories

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2160]
**To Reproduce**
1. Get an email with subject "a" and another with subject "b/c"
2. Select both of them and export
3. The generated zip file contains

```
├── 2020-07-20-12h09m53s-a.eml
├── 2020-07-20-12h10m06s-b
│   └── c.eml
```

**Expected behavior**
Exporting just the "b/c" mail causes the forward slash to be replaced with an underscore (possibly by the browser?). This could be done also in the zip case:

```
├── 2020-07-20-12h09m53s-a.eml
├── 2020-07-20-12h10m06s-b_c.eml
```

**Comment by ganthern** [comment]
the sanitization of invalid characters that the browser performs is implemented for the desktop client [here](https://github.com/tutao/tutanota/blob/d46d3379ae4fbbae4f5ada00d0247f0602aef51f/src/desktop/DesktopUtils.js#L309) and the reserved filename sanitization [here](https://github.com/tutao/tutanota/blob/d46d3379ae4fbbae4f5ada00d0247f0602aef51f/src/desktop/DesktopUtils.js#L330)

That could be reused to perform sanitization on files before zipping the exports,
