### ISSUE TITLE
Calendar UI improvements

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2162]
The calendar still has a lot of rough points, particularly in the navigation and the UI.  Many users request and make suggestions for changes. Some UI based improvements for usability that we want follow:

**Acceptance criteria:**
* [x] Desktop: Switch to day view when clicking on day number to see all events of a day.
* [x] On each view (day, week, month, agenda) this information must be displayed to the user
- day number, 
- month, 
- week day
- week number.
* [x] Mobile: Switch to day view when clicking on day in the month view. (Do not open event preview from mobile month view)
* [x] Desktop: Left click on an empty space inside the day should create a new event.
* [x] Month view needs buttons for switching between months in mobile layout. (Swipe gesture is not always available on smaller screens):
    * Buttons in title
    * or buttons in the same row as the selector (like it is in desktop) 
* [x] In Agenda/Week/Day view do not show the start time in the first place. Instead we can show start-/end time underneath the title.
    * In Week/Day view the height of the bubbles is dynamic based on the duration. This can lead to text being sliced through the middle which looks pretty bad. We should only display as many lines as fit completely and then ellipse the rest of the text. If the bubble only fits a single line of text then the time should appear after the title, otherwise the time should always be on it's own line.
* [x] Allow drag and drop to change event time.
* [x] Indicate current day with accent colour

**Test notes:**
* [ ] Check that every acceptance criteria is realized
* [ ] As some refactoring has been included in this issue, perform general regression tests for calendar 
* [ ] Test date picker
* [ ] Check that calendar on android is still optimised
 
**experts**
@bedhub @charlag @johnbotris @sarashub

**Comment by johnbotris** [comment]
> Month view needs buttons for switch between months in mobile layout. (Swipe gesture is not always available on smaller screens)

![Screenshot from 2021-06-09 16-50-42](https://user-images.githubusercontent.com/22109738/121377785-eca20e00-c942-11eb-920c-8d5937191344.png)

regarding:
> Add selector for changing between views (month/week/day) which should be accessible from all views (not from the nav column)

Not sure if we would want to put something in the header for this case as well, that wouldn't work so nicely with these arrow buttons

**Comment by jowlo** [comment]
How about making the month (so "February 2021") clickable and add a dropdown to select between views here?

**Comment by johnbotris** [comment]
Some more possiblities:
* Day view on desktop - It is currently only implemented for mobile and doesn't work so well on desktop. If we flesh out the view then we can include a switcher to day view. Clicking on a day in month view would also take you straight to day view
* Selectable day - by clicking on a day that would become the new selected day. There would be some indication of what day is currently selected. This would be used by the navigation buttons on the sidebar.
* Different clickable areas in the day box on month view that could have different behaviours
