### ISSUE TITLE
Scaling does not work

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2165]
v3.75.3

ctrl + mousewheel does not scale app anymore so it's impossible to change the font size.

**Comment by ganthern** [comment]
looks like onmousewheel was finally removed. onwheel/the 'wheel' event listeners (which are the preferred replacements) are not fired in electron 9.0.5 or 9.1.2 for some reason. Manually creating and issuing a WheelEvent through the console works, so the listener is there.

the main thread doesn't offer a way to handle mouse input, so there's no immediate fix I can see.

**Comment by charlag** [comment]
Maybe we can add a setting to scale fonts instead but that would be a bigger issue.

**Comment by ganthern** [comment]
adding a keyboard shortcut to zoom would be a possibility, those events are fired.

**Comment by charlag** [comment]
macOS has menu actions for that but they do nothing right now so there may be event a shortcut.

**Comment by mpfau** [comment]
It is currently not possible to reset to default scale (usually CTRL + 0)

**Comment by mosabaldosari** [comment]
> v3.75.3
> 
> ctrl + mousewheel does not scale app anymore so it's impossible to change the font size.

**Comment by ganthern** [comment]
> It is currently not possible to reset to default scale (usually CTRL + 0)

made a new issue: https://github.com/tutao/tutanota/issues/2199
