### ISSUE TITLE
Error 0xc000007b when trying to open the Tutanota desktop app for Windows

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2166]
Reported by a user [on reddit](https://old.reddit.com/r/tutanota/comments/hwx542/error_0xc000007b_when_trying_to_open_the_tutanota/)

Fresh windows install (20.04 64 bit). Chkdsk and sfc show no problems. Redownloading and reinstalling makes no difference. Installing as administrator or local user makes no difference.

Running the program as administrator removes the error message popup, but the program never opens so it still doesn't work.

All other programs on the computer work fine.

**Desktop:**
 - OS: Windows
 - Version: 3.75.3.948

**Additional information**

- Install file: tutanota-desktop-win.exe
- Sha256: A9F9467A304CCEE5D99685AE2F00560A089A324582F1F58F2FF48E3D664505AA

**Comment by charlag** [comment]
Did not get any more reports about this
