### ISSUE TITLE
Tutanota Android app cannot be resized

### ISSUE THREAD

**Issue by alexanderadam** [tutao/tutanota#2167]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Resizing the tutanota app window is broken / not possible.

**To Reproduce**
1. Open tutanota app on an Android Desktop environment
2. Try to resize it

**Expected behavior**

Resizing is possible

**Screenshots**

As you can see, even the resizing button is greyed out. Dragging edges or corners is also not possible.

![Screenshot_20200727-093444_Tutanota](https://user-images.githubusercontent.com/372620/88515940-c6a2a200-cfec-11ea-845f-92cfb72957a9.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S6
 - OS: Android 10
 - Version: `v3.73.1`

**Additional context**

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

Applications like Firefox, VLC or Termux can be resized without any problems.

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.
**PPS:** I'm not sure whether this is relevant but [this](https://codeberg.org/gitnex/GitNex/pulls/601/files) is how GitNex fixed the issue and [this](https://github.com/TobiGr/NewPipe/commit/ea486e769ff9728c4e5d7dac6028587c39476fa9) is how NewPipe fixed it.

**Comment by charlag** [comment]
Hi
Can you please send a PR, maybe with the same changes as GitNex? We are web app and already react to resize so there shouldn't be any work except to declare that we support it.

**Comment by johnbotris** [comment]
how could this best be tested? @charlag

**Comment by charlag** [comment]
Do not test it, I think we will get reports if it works

**Comment by alexanderadam** [comment]
Do you know when this change will appear in the stable F-Droid release?

**Comment by johnbotris** [comment]
We are planning to release this tomorrow, F-Droid is usually updated within a few days but we don't have control over that
