### ISSUE TITLE
Improvement: don't ask for the domain each time on the log in screen

### ISSUE THREAD

**Issue by l0k9j** [tutao/tutanota#2168]
Typing '@tutanota.com' at the end of my email address on the log in screen is unnecessary and tedious on mobile. Like many users I dislike to type on mobile keyboard because it's slow, fiddly and error prone. If you use yahoo mail, gmail, etc. you no longer have to enter the full email address.

I am aware of your response to gh-192, gh-733 and why the email username isn't enough. I'm assuming here that usernames are not unique across your various domains otherwise there wouldn't be an issue at all.

What I don't understand is why the user interface doesn't assist the user at all with this. At the very least a domain drop down would help. What would be even better is to remember the last selected domain in that drop down. I'm sure that would be very appreciated by your users.

Could you please explain why you haven't considered that option?

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

**Comment by geoffroy-noel-ddh** [comment]
Hi @charlag, I'm a bit confused as I see tickets marked as improvement in your github issues list. E.g. is gh-2162 not a feature request?

**Comment by geoffroy-noel-ddh** [comment]
![image](https://user-images.githubusercontent.com/3778106/88666018-68062280-d0d7-11ea-8a2a-8930f7d7888f.png)

**Comment by charlag** [comment]
@geoffroy-noel-ddh we open feature issues on our own. Message on the screenshot is a message from Github, not us.
