### ISSUE TITLE
Tray icon is displayed even if it's disabled in Settings

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2173]
As a user of a desktop client on Linux I don't want to see tray icon when "Run in background" option is deselected in settings.

**acceptance criteria**

In Settings -> Desktop toggle off "Run in background" and restart the app. No tray icon should be displayed.

## Test Notes (Windows, linux if tray icons are available)
- [ ] When 'run in background' is disabled
  - [ ] The taskbar icon disappears
  - [ ] The taskbar icon does not appear when the client is rebooted
- [ ] When 'run in background' is enabled
  - [ ] The taskbar icon appears
  - [ ] The taskbar icon appears when the client is rebooted
- [ ] the tray icon appears/reappers as the setting is toggled

**Comment by humanape** [comment]
Does the same on Windows 10. Did not do this in the beginning.

**Comment by dolandemort** [comment]
Can confirm this also happens for me. The colored icon is also really out of place compared to standard KDE icon style.
