### ISSUE TITLE
Refactor MailEditor

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2176]
Use new SendMailModel with MailEditor

**Comment by mpfau** [comment]
test notes:
- [ ] formatting
- [ ] attachments
- [ ] sanitizing
- [ ] bubble input

**Comment by sarashub** [comment]
- [x] formatting
- [x]  attachments
- [ ] sanitizing
- [ ] bubble input

**Comment by charlag** [comment]
Doesn't open from search (shortcut/button)

**Comment by charlag** [comment]
fixed by #2349
