### ISSUE TITLE
Support FIDO U2F security key in iOS

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2177]
As a user i want to be able to use (login and register) my FIDO U2F security key as a second factor in the mobile iOS app so that i can use my key on all of my devices.

### AC
* Allow setting up a security key in Settings > Login 
* When security key is registered within the app it is always registered for https://mail.tutanota.com/ 
* Authentication with security key as second factor in desktop client/mobile app is allowed
* Authentication with the same key in web client on https://mail.tutanota.com/ is allowed
* Authentication with key that has been registered on whitelabel domain is allowed

### Older notes

We checked pros and cons from the yubico documentation page and decided to try the ASWebAuthenticationSession or SFSafariViewController approach.

https://developers.yubico.com/WebAuthn/Supporting_U2F_or_FIDO2_Security_Keys_on_iOS_or_iPadOS/Paths_for_Supporting_U2F_or_FIDO2_Security_Keys.html

This requires iOS 13, but it is not a problem anymore as we dropped support for iOS 12 already.

### Test Notes
- [ ]  Keys that have been previous registered still work, specifically for tutanota.com
- [ ]  Keys that have been previous registered still work, specifically for whitelabel domain
- [ ]  Add a key in Settings > Login
- [ ] Check that when adding new key, the user can cancel
- [ ] Check that new key works on login in ios app
- [ ] Check that new key works on login for desktop and web apps
- [ ] Check that when authenticating, the user can cancel
- [ ] Check that using wrong key will not work on login

**Comment by Doelfke** [comment]
@bedhub what is the status of this?
