### ISSUE TITLE
Handle unused deleted Free accounts

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#2181]
Unused free accounts are deleted after six months without a login. We should display this with an option to upgrade on first login (only for free users). A similar message should also be displayed when downgrading to a free account.

We also need to handle AccessExpiredError when creating a new session and display a message that the account was disabled due to inactivity. In this case the user may re-use the address in a Premium account.

**Comment by johnbotris** [comment]
- [x] confirm that a message is shown on signup regarding deletion of inactive accounts
- [ ] confirm that a message is displayed upon login when a users account has been deleted due to inactivity
