### ISSUE TITLE
Code request: Split src/api out to npm package

### ISSUE THREAD

**Issue by LoveIsGrief** [tutao/tutanota#2182]
Hello,

Thanks for working on providing encrypted mail for the masses. Using the apps has been quite smooth.
As an app and script developer however, integrating with tutanota isn't very easy. An API documentation doesn't exist and neither does a library to communicate with tutanota.  
Looking at the code, it seems like most (if not all?) of the API code is contained within `src/api`. Unfortunately, in order to use it, at the moment the only possibility seems to be copying that directory and integrating it somehow.

It would be great if that directory could be moved into its own repo and published to npm (or yarn or some other package index).

Cheers

**Comment by charlag** [comment]
Hi
Even with keeping monorepo we could do that. It was the original idea but right now it's kinda tightly coupled and we are not ready yet to provide stability guarantees for that.
What is your use case for integration? Maybe it would help us plan it better in the future.

**Comment by LoveIsGrief** [comment]
Thanks for responding.  
I'd like to work on writing a SMTP bridge like Protonmail has in order to allow services to use Tutanota for sending emails. At the moment I'd have to create an account on GMail and use their SMTP server or get a paid service from whichever webhost I pick, which I find suboptimal.

The idea is `service --SMTP--> Bridge --API--> Tutanota`. With a paid Tutanota plan for a custom domain, tutanota would then act as the domain's email service. It's not only interesting for personal use, but also for businesses since I don't know how else this could be achieved.

**Comment by tukusejssirs** [comment]
@charlag, I’d like to manage my contacts / calendar events programically, i.e. add, create, update/modify contacts and calendar events.

Google has such integration in their Google Apps Script and I use Google Sheets to manage them.

If I could use Node.js script with your API, that’d awesome!

**Comment by charlag** [comment]
I think if you want to use it you should use sources directly (you can put it git hash into your package.json). We are not ready to provide any versioning guarantees for internal APIs.
