### ISSUE TITLE
Custom language is not respected after logging out

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2188]
How to reproduce:
1. Log in in the web client and change the language in the appearance setting to something different than the browser language.
2. Log out
-> The login view is in the browser language.
As soon as you click on the "More" button the language switches to the selected language.

Expected:
The selected language should also be used in the login view after logging out.

Reproducible at least in Chromium on Ubuntu.

**Comment by brshub** [comment]
With version 3.85.3 the language changes persist after logout and upon logging back into the account. However, if the changes are made and you attempt to login through an incognito window or another browser, the settings revert to default.

**Comment by johnbotris** [comment]
> However, if the changes are made and you attempt to login through an incognito window or another browser, the settings revert to default.

This would be expected, or do you mean the language settings are being reset in non-incognito mode after logging in in incognito mode?

**Comment by brshub** [comment]
> > However, if the changes are made and you attempt to login through an incognito window or another browser, the settings revert to default.
> 
> This would be expected, or do you mean the language settings are being reset in non-incognito mode after logging in in incognito mode? @brshub

If the user logs in through an incognito browser or another browser the default settings are used.

**Comment by brshub** [comment]
We have also received reports that the language settings revert to automatic after the mail client updates, rather than persisting in the new version.

**Comment by charlag** [comment]
@brshub language and theme are stored locally
