### ISSUE TITLE
Date picker parses invalid dates incorrectly

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2190]
v3.75.3

To reproduce:
1. Select English (US) as browser language (reproduced in FF)
2. Go to calendar
3. Open new event dialog
4. Paste 2020-12-09 into the "from" field
5. Observe it parsed as April 12 2077

It should say that this is invalid format instead.

**Comment by johnbotris** [comment]
# Test Notes

Try passing various invalid date formats to the date picker, in particular putting the year in the wrong spot.
Note that the parser interprets a two-part date as a month+day

**Comment by vaf-hub** [comment]
created this issue when testing it: #2290
