### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by noloader** [tutao/tutanota#2191]
I'm trying to delete my tutanota account. The service did not work out for me.

Here's the error. I have no idea what it means or how to fix it.

![Screenshot from 2020-08-07 18-15-44](https://user-images.githubusercontent.com/3538226/89692569-13825480-d8da-11ea-8be3-8f9e7d5d999b.png)

This error really sums up the problems with the service. It is too hard to use, even for simple operations. For example, I can't install the Tutanota client on Ubuntu (no packages), I can't send an email to support@tutanota.com, I can't delete an unneeded account, etc. On other occasions it is impossible to use, like trying to use Thunderbird or Evolution over IMAP to ease some of the usability problems.

Please delete the jwalton@tutanota.com account.

**Comment by mpfau** [comment]
You specified an email address to take over your mail addresses. Don't do that if you don't want to take over your mail address to a different account. You will be able to delete the account yourself, then.

I'm sure you understand that we can't delete accounts without authentication.
