### ISSUE TITLE
Need Inbox FILTERS and Filter Rules - mostly - need an 'unread' only display

### ISSUE THREAD

**Issue by lcalamar** [tutao/tutanota#2197]
Need an UNREAD view of all messages across all folders that are UNREAD.

This is the minimum for what should be done for filtering what I see in my inbox.  Ideally, the ability to create filters based on tags/folders/subject/sender/receiver/etc...    But I'll take unread only as a start

**Comment by mosabaldosari** [comment]
66

**Comment by vitoreiji** [comment]
Hi
To keep repository manageable we don't provide support or accept feature requests here. Please see README or https://tutanota.com/contact for other options.
