### ISSUE TITLE
Deleteing calendar event with confidential external recipient may be impossible 

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2209]
v3.76.6

1. Create calendar event
2. Add external recipient
3. Select confidential mode and provide a password
4. Go to contacts
5. Delete contact for this recipient
6. Try to delete event
7. See "please provide a password for each external recipient"

We should probably just delete event in this case because we cannot send cancellation.

Another way to reproduce this is to add an attendee and then select to not send out updates. Attendee with be saved but password will be not.

**Comment by vaf-hub** [comment]
Test notes:

- [ ] check that the bug is no longer present
- [ ] check that all recipients with password or internal DO receive cancellation notification

**Comment by johnbotris** [comment]
Currently getting the old, incorrect behaviour on the test system
