### ISSUE TITLE
Sent emails don't show up immediately in [Sent] folder...

### ISSUE THREAD

**Issue by sfd99** [tutao/tutanota#2211]
**1st)** Tutanota is GREAT!.

**Bug:**
Any just-sent email 
_DOES NOT  show up _immediately__ in [Sent] folder...

You have to _logout_ of TN
and _login in back_ to see it listed
in the  [Sent] folder.

Only then
(logout+login again),
will a recently sent email
show up in the [Sent] folder.

Hope you can fix this urgently.
**_Thanks / Danke!_**

**Comment by charlag** [comment]
Please check your websocket connection and that no extensions interfere with it.

**Comment by sfd99** [comment]
"Please check your websocket connection and that no extensions interfere with it."

How do I: 
"check your websocket connection " ?.
As a simple Tutanota user,
I don't know how to do that...
thks,
my PC: Ubuntu Linux 20.04.4 LTS
+ Chrome Browser (latest version).

**Comment by vitoreiji** [comment]
@sarashub you saw this today too, correct?

**Comment by sarashub** [comment]
Yes, but I can't reproduce it right now.
