### ISSUE TITLE
Build of the --win application fails on debian 9 with: ERROR: "Tutanota Desktop.exe" not signed! The NSIS installer may not work

### ISSUE THREAD

**Issue by alternaivan** [tutao/tutanota#2213]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**
Trying to build the win desktop app fails when trying to build the application from the node:10.22.0 docker image with the following error:
  • ERROR: "Tutanota Desktop.exe" not signed! The NSIS installer may not work.
	• install osslsigncode
I've installed osslsigncode, but somehow the build process doesn't detect the package.

**To Reproduce**
1. docker pull node:10.22.0
2. git clone https://github.com/tutao/tutanota.git && cd tutanota
3. git checkout tutanota-release-3.76.5
4. docker run -ti -v $PWD:/app node:10.22.0 /bin/bash
5. dpkg --add-architecture i386 (to install wine32 dependency)
6. add `deb http://ftp.de.debian.org/debian stretch main` in /etc/apt/sources.list
7. apt update
8. apt install wine wine32 wine64
9. export WIN_CSC_FILE="/app/tutao-pub.pem" (not sure if the var is correct, but I added it nevertheless) - this step is probably wrong
10. export HSM_USER_PIN="somepassword" (same as the above var, added some random string) - this step is probably wrong
11. apt install osslsigncode
12. cd /app
13. npm install (fails with error: No package 'libsecret-1' found)
14. node dist --win (fails with the above mentioned error of osslsigncode)

**Expected behavior**
Upon installing necessary dependencies (wine32, wine64, osslsigncode) build of the win application should be okay.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, Debian
 - Desktop Environment, if applicable (on Linux): Build done within docker container
 - Version [Debian 9]

**Additional context**
Maybe document the build procedure for win desktop app?

**Comment by charlag** [comment]
As the error says, you need libsecret. See https://github.com/atom/node-keytar

**Comment by ganthern** [comment]
@alternaivan did installing libsecret solve your problem?

**Comment by alternaivan** [comment]
Hi @ganthern, thanks for waiting on my reply, no, I'm still getting the same message. Maybe it is an issue with the signing (setting WIN_CSC_FILE and HSM_USER_PIN env vars)?

**Comment by ganthern** [comment]
`node dist --win` will produce a windows client that tries to get updates from our servers, and for that the build script assumes the presence of a Hardware Security Module when building the client cross-platform to provide the signature for the installer.

If you want a client to use for yourself, the preferred method is the `--custom-desktop-release` flag (see in [BUILDING.md](https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md)), but that currently doesn't work cross-platform and will not try to run auto updates.

What is your use case, especially with respect to automatic updates?

**Comment by alternaivan** [comment]
Okay, thanks, I'll then try with the ```--custom-desktop-release``` flag. I had some issues in upgrading tutanota windows client from version 3.76.0 to the latest one (at the time) 3.76.5, so I wanted to build that version on my dev machine and install it on windows machine. However, I think this issue with the upgrade is fixed, since I now use the latest one (3.76.7) on the windows client.

I think it is okay to close this issue.

Thank you for your help!

Regards,
Marjan

**Comment by ganthern** [comment]
Okay, I'm glad you were able to get it working.

Have a nice day!
