### ISSUE TITLE
Extremely large images make email text impossibly small to read

### ISSUE THREAD

**Issue by alstr** [tutao/tutanota#2214]
- ✅ This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- ✅ I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

If someone sends a very large image in the email body, the view in the iOS app zooms out to fit it on screen. The text then becomes minuscule and you cannot zoom to enlarge it.

**To Reproduce**

1. Send email to your Tutanota address with large image (e.g. 2000px wide) in email body with some text content around it.
2. Open the received email. The text should initially display at the correct size, then the view will zoom out to fit the image on screen.

**Expected behavior**

The view should not resize to fit the image - or if it does, you should be able to zoom in to read the text.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.6
 - Version: 3.75.3

**Comment by charlag** [comment]
Double-tap to zoom back in

**Comment by alstr** [comment]
Ah okay, thanks. I will try that when the app becomes available again.

(I wouldn’t say that is obvious. Wondering what is wrong with the standard pinch gesture to zoom.)

**Comment by charlag** [comment]
Service is back up.
Double tap is also standard, we didn't add pinch-to-zoom because it's not really a gradual zoom. We should try to improve that, that's true.

**Comment by alstr** [comment]
Yep, works as you say. 👍 Would be good to see it improved (at least hinted at when the view zooms out). I personally prefer pinch and would argue that’s more common on iOS, but the main thing is that it works and it’s conveyed clearly. Thanks.
