### ISSUE TITLE
Per-Client 2FA required [FIDO U2F security key]

### ISSUE THREAD

**Issue by ghamet** [tutao/tutanota#2216]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Mobile App [android 9] requires webclient unlock when 2FA is activated.
This is unexpected behaviour as it does not allow independent access of multiple clients.

**To Reproduce**
1. Connect U2F key as 2FA
2. Open mobile app
3. Mobile App will wait for authorization from client with U2F key
4. Removed 2FA
5. Open mobile app
6. Mobile app opens

**Expected behavior**
Binding of 2FA to specific client / independent client usage

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [blackview BV9500]
 - OS: [android ]
 - Version [9.1]

**Additional context**

**Comment by charlag** [comment]
Duplicate of #443

**Comment by ghamet** [comment]
Hi Ivan,

maybe my description was insufficient. I do not want to use the U2F key on
the android device. I need to use different 2nd factor on different
clients. E.g. u2f on desktop, fingerprint on mobiles.

I did see the referred issue, I see a different use case here as I want
different 2nd factors on different clients.

Regards
Georg

**Comment by charlag** [comment]
Sorry that I misunderstood you. Please discuss feature with support or on Reddit, maybe it would also help to know your use case better.

**Comment by ghamet** [comment]
I expect to be able to login on android client without allowing this from desktop client = independent android client use.
