### ISSUE TITLE
start minimised on KDE

### ISSUE THREAD

**Issue by dockerformthedock** [tutao/tutanota#2229]
from AUR on KDE
it doesnt hold the setting for start minimized on window rules
when you tell it  yes it goes to no 
![flameshot - 02-35 - August 27 -- 240](https://user-images.githubusercontent.com/69120363/91367212-6b372000-e7f5-11ea-94bc-cf610a6eb2a6.png)

any work around?

**Comment by charlag** [comment]
There's an option in Tutanota to start minimized, we don't know why KDE options work or do not work for you.

**Comment by dockerformthedock** [comment]
> There's an option in Tutanota to start minimized, we don't know why KDE options work or do not work for you.

i have it from AUR and it seams to miss that option, thanks alot

![image](https://user-images.githubusercontent.com/69120363/91844833-ac8d5c80-ec47-11ea-970d-cd02f4610296.png)

**Comment by charlag** [comment]
I think "show tray icon" and "run at startup" should already do it
