### ISSUE TITLE
TutaNova Syncronization Service fails with TOR

### ISSUE THREAD

**Issue by solarelf** [tutao/tutanota#2231]
![Screenshot_20200831-014558_Fennec F-Droid](https://user-images.githubusercontent.com/42090132/91671540-4f52b780-eb30-11ea-9c7f-aca155d67b0f.jpg)
[1598802066983_main_tutanota.log](https://github.com/tutao/tutanota/files/5147059/1598802066983_main_tutanota.log)
[1598802066983_worker_tutanota.log](https://github.com/tutao/tutanota/files/5147060/1598802066983_worker_tutanota.log)
[log.txt](https://github.com/tutao/tutanota/files/5147061/log.txt)

Hi,

I noticed that a notification message "Tutanota notifications sync" service is trying to sync, but it cannot unless I turn off TOR so it does in seconds. Apperently, this service uses incompatible, impenetrable through the TOR, protocols (UDP)?

Since this whole TutaNova project is about privacy, it should not be a surprise for developers that many users would want to use it along with TOR.

Please fix this in your next releases.

**Comment by charlag** [comment]
We don't use UDP, it's just HTTP connection. Your tor exit node might have problems accessing Tutanota.

**Comment by solarelf** [comment]
> We don't use UDP, it's just HTTP connection. Your tor exit node might have problems accessing Tutanota.

can you add httpS syncronization too?
