### ISSUE TITLE
More flexible recurring event frequency

### ISSUE THREAD

**Issue by ZeroAbility** [tutao/tutanota#2232]
It would be helpful to have a more flexible frequency of recurring events such as:

Monthly, the `x` `y` of the Month

For example, the first Monday of the month, or the second Wednesday of the Month

**Comment by vitoreiji** [comment]
Duplicate of  #1666.

Also, to keep repository manageable we don't provide support or accept feature requests here. Please see README or https://tutanota.com/contact for other options.

**Comment by ZeroAbility** [comment]
Thank you for the response and I apologize for the duplicate. Unfortunately, I don't have or want a Reddit account and there may be others using your service that feel the same. Just a perspective worth considering.
