### ISSUE TITLE
The app will always restart after close if an update is available and installed on quit

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2237]
Expected behaviour is only to restart if the user clicked on the notification or on the "install now" button in the settings.

Closing it via the tray icon or the shutdown symbol in the app should install, but not restart.

Currently, autoUpdater.quitAndInstall() has a boolean flag to force restart after install, but it may still restart if that flag is not set.

related: #1617

**Comment by mpfau** [comment]
Needs to be tested with the next release.
