### ISSUE TITLE
Keyboard disappears when typing Return or Backspace

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2242]
Some Android users have reported that, on replying to an email, if they type the Return or Backspace key.

**Smartphone:**
 - Client: Android App
 - Versions 3.75.3, 3.76.7

**Comment by charlag** [comment]
Can anyone confirm whether this still happens? I have a feeling it was a WebView bug

**Comment by charlag** [comment]
Haven't been reported for a while
