### ISSUE TITLE
Duplicated contacts in suggestion dialog

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#2243]
This was reported by a user.
To reproduce: start typing in a contact name on the To: line. For some contacts, it shows their name multiple times in the suggestion dialog. This happens even if the contacts aren't duplicated.
This issue is probably related to  #1972

**Comment by charlag** [comment]
It is a separate issue if the word is in both name/email address or coming from search and native parts

**Comment by jowlo** [comment]
I could not reproduce this on the webclient with a contact containing the search term in name and email address.

**Comment by bedhub** [comment]
Was reported again today by a user and i found a way to reproduce this case. 
I created a contact with name "Test" and an email address "test1@tutao.de". Then i opened the mail editor and started typing the word "tes". The contact appeared twice in the suggestion list.

![contact_suggestion](https://user-images.githubusercontent.com/8296817/105694146-e285f280-5f00-11eb-8045-1c0bf6689be1.png)
