### ISSUE TITLE
Split build script to release desktop client and web client separately

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2245]
- Add option to only build desktop client 
- use own tag for desktop client 

https://github.com/tutao/tutanota/issues/3221      is a prerequisite for solving this issue.

**Comment by charlag** [comment]
I've made some good progress on this but I would also suggest another related thing as part of this issue: run web build for each environment separately.
Currently we generate all the JS files we might need in web thread during the build. This is unnecessary and hard to keep clean as we have to tidy up things in each build. Example: we generate index.js, index-app.js, index-desktop.js, in current release we bundle RsaApp into web bundle even though we don't need it in the web app and so on.

Instead I think we should statically resolve this. There are three ways:
1. Different entry points
2. macro-like conditions
3. resolve things as external imports when we don't need them

All of them have their own disadvantages but I think net result is still positive, cleaner app.

**Comment by charlag** [comment]
https://github.com/tutao/tutanota/issues/3221#issuecomment-908274978
