### ISSUE TITLE
DatePicker in calendar event editor not accepting keyboard or pasted input

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2250]
Go to the calendar, create a new event, and try to type or paste into the to or from fields and the input is not accepted. The visual date picker still works. 

The date pickers created by showDatePickerDialog are working as intended

**Comment by bedhub** [comment]
TODOS:
- [ ] Input is not accepted when pressing enter or tab
- [ ] End date does not change if start date is after end date

**Comment by johnbotris** [comment]
Testing notes:
Type or paste input into a DatePicker, click in and out and tab in and out of a DatePicker and test that the visual selector appears and disappears correctly.
Test not only the DatePicker but the TextFieldN and try to make sure the animation still works as intended
