### ISSUE TITLE
[Feature Request] Right click context menu

### ISSUE THREAD

**Issue by Parasrah** [tutao/tutanota#2252]
In some other web mail clients, they override the right click context menu to provide actions based on what was selected. For example, right clicking on an email in the inbox might present options to delete, archive, move, reply, etc. Likewise right clicking on a folder might provide actions to rename or remove the folder. I personally find these context menus very useful in outlook (which I must use for work), and think it could make the tutanota clients more user friendly.

Sorry in advance if this has been brought up before, I tried searching through the issues and didn't see anything similar. And thanks so much for all your hard work!

**Comment by vitoreiji** [comment]
Hi
To keep repository manageable we don't provide support or accept feature requests here. Please see README or https://tutanota.com/contact for other options.
