### ISSUE TITLE
ConnectionError on login: saltservice Reached timeout of 20000ms

### ISSUE THREAD

**Issue by nikolayhg** [tutao/tutanota#2255]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Unable to login due to timeout connection error.

**To Reproduce**
1. Start the Desktop app on Linux
2. Enter email and pass
3. Click on "Log in"
4. See error in Developer Tools and UI
  - Dev Tools:
    - `ConnectionError {name: "ConnectionError", message: "Reached timeout of 20000ms  | GET /rest/sys/saltservice", data: undefined, stack: "ConnectionError: Reached timeout of 20000ms  | GET…tanoMl5O1N/resources/app.asar/worker.js:1:747956)", isOperational: true}`
  - UI: 
    - `Could not reach server, looks like you are offline. Please try again later.`

**Expected behavior**
Successful Login

**Screenshots**
![image](https://user-images.githubusercontent.com/14300004/93019192-34774d00-f5de-11ea-922e-d06ab1ef9b8e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Desktop Environment, if applicable (on Linux)
 - Version: 20

**Comment by nikolayhg** [comment]
I tried again after few hours and managed to connect. Not sure why I couldn't previously. You can close the issue if you like.

**Comment by AFulgens** [comment]
There is an ongoing, persisten DDoS happening against Tutanota since the middle of August (see blog post here, if you can connect: https://tutanota.com/blog/posts/ddos-attack-tutanota/ I currently cannot...).

In my eyes, this just means, that they are doing something right.

**Comment by nikolayhg** [comment]
@AFulgens you might be right about the DDoS attacks.

Even after successful login, I still get often enough timeout errors:
![image](https://user-images.githubusercontent.com/14300004/93116526-0b31ec00-f6c6-11ea-93b3-f9d14061bd89.png)

**Comment by nikolayhg** [comment]
Login issue still happening.

![image](https://user-images.githubusercontent.com/14300004/93448196-047cc200-f8dc-11ea-907c-896faf8c416c.png)

**Comment by nikolayhg** [comment]
- I managed to login without using VPN.
- Using VPN I cannot login or access my emails.

**Comment by nikolayhg** [comment]
In the last few days it works well also with VPN, thank you!
