### ISSUE TITLE
Handle EntityEventBatches sequentially

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2264]
EntityEventBatches should only trigger sequential loading of data to avoid too many parallel server requests.

**Comment by charlag** [comment]
I'll start with testing mail and calendar views, someone can handle contacts/settings

**Comment by mpfau** [comment]
Tested the following setting screens:

Login
- change password
- delete session
- create/delete second factor

Mail
- change sender name, sig, confidentiality, formatting, create contacts, 
- add/remove/deactive/activate alias
- add/remove inbox rules
- add/delete notification

Appearance
- change time format/week start

User Management
- add user
- sender name / admin flag / deactivate / activate
- create/delete second factor
- activate / deactivate alias

Group Management
- add group
- change name
- activate/deactivate group
- add/remove group members

Global
- add/remove spam rules
- save ip
- enforce pw update
- add/remove custom domain

Whitelabel
- enable/disable
- add/remove custom notification mails
- add/remove custom domain
- enable/disable custom logo
- enable/disable custom colors
- enable/disable custom meta tags
- enable/disable custom links
- switch lang

Contact forms
- add/remove
- change target mailbox
- add/remove responsible
- change other fields

Subscription:
- switch subscription
- change period
- switch to business
- sign processing agreement
- add storage
- add aliases
- enable/disable whitelabel
- enable/disable sharing

Payment:
- change invoice address
- change payment method

Not tested:
- contact forms
