### ISSUE TITLE
My web browser is not allowing my to even load the page.

### ISSUE THREAD

**Issue by notsars10** [tutao/tutanota#2271]
This has happened multiple times. I am connected to the internet and can access anything my heart desires EXCEPT tutanota. It says it cannot find the IP address of Tutanota. Anybody else have this issue?

**Comment by bartlettD** [comment]
This isn't a bug, Tutanota is currently under a DDoS attack targeting their DNS infrastructure.  Things are starting to resolve themselves now.

**Comment by charlag** [comment]
This was downtime indeed, please see blog for more info
