### ISSUE TITLE
[Desktop/Web] Add setting to stop auto-opening of the next email upon deletion

### ISSUE THREAD

**Issue by I-Dont-Remember** [tutao/tutanota#2275]
I often run into emails getting overlooked when I delete the currently open one and it marks the next as unread without my input. If i'm not careful to reset it, when I come back later it looks like I've already gone through the contents of it. On mobile your app makes it super simple to delete without affecting other emails from the list screen with a swipe, now the desktop just needs to have a similar feature as it makes it very difficult for me to use Tutanota as my primary provider. Some of these smaller issues like #318 and this are why I haven't been able to delete my old Outlook and gmail accounts.

**Comment by vitoreiji** [comment]
Hi
To keep repository manageable we don't provide support or accept feature requests here. Please see README or https://tutanota.com/contact for other options.
