### ISSUE TITLE
Wrong Recovery Code when Admin Enables 2FA for User

### ISSUE THREAD

**Issue by SethiPandi** [tutao/tutanota#2280]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
If using the admin account for a team or organization of users, the admin can set up 2FA for users.  
For example, as I am one of the users under the organization, I just tried to do it through the admin account for convenience.

However, when hitting the recovery code stage of the process, it asks for the admins account password, and displays the admin accounts recovery code. It does not display the recovery code for the account that just had it's 2FA setup, but instead for the admin account that's currently logged in.

**To Reproduce**
1. Login to an account which can manage users.
2. Click the cog at the bottom left. (Settings)
3. Click "User management"
4. Create a user if one doesn't exist, or select a user which doesn't have 2FA other than the admin user itself.
5. Under "Second factor authentication" click the + icon, and setup 2FA.
6. The recovery code produced is for the admin account, not for the user.

**Expected behavior**
I'm not sure what I'd expect, since I think it's weird that the admin can even enable 2FA for other users in the first place.  

If this is intentional, I think it should request the admin's password, but display the recovery code of the account that just had 2FA enabled, not of the admin account.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 80.0.1 (64-bit)

**Comment by vaf-hub** [comment]
Test notes:
- [ ] recovery code dialog is only shown when setting 2fa for the logged in user and not for other users
