### ISSUE TITLE
Allow downloading credit statements

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2286]
As a user, I want to be able to download credit invoices when I am given credit via a gift card or from the Tutanota team.

##### Acceptance criteria
* In Settings -> Payment -> Invoices & Payments, I should be given an option to download an invoice for credit listings, not just debit
* A credit invoice should be like a regular invoice, with the reason for the credit, and the total amount listed

##### Non-functional requirements
* Specify on the invoice how the credit was obtained (by redeeming a gift card or via manual intervention from a team member).

##### Implementation hints
* The server generates a PDF Invoice and the client requests it by calling the `PdfInvoiceService`.
* The server is already capable of generating credit invoices (it is possible to do in the admin client). We just need to expose this from the client.

**Comment by Pa7Hub** [comment]
Hi, I want to try to fix this issue. Where do I find the Invoices & payments section?

**Comment by armhub** [comment]
"Settings" -> "Payment" -> "Invoices & payments", it is visible in paid accounts.

**Comment by Pa7Hub** [comment]
Alright, thanks! Will try my best.

**Comment by Pa7Hub** [comment]
Okay, I tried fixing it and also got some help from Ivan. We couldn't get the second Download Button to work because the Invoice Number for "Credit" is always null, Ivan said it might be a server issue?

**Comment by jakequade** [comment]
@armhub it looks like this has been done? Was just able to download a statement.

**Comment by jakequade** [comment]
Have just been looking to contribute and noticed the beginner tag :)

**Comment by armhub** [comment]
I think it should not be possible yet to download credit statements because we did not fix anything yet. Just invoices are downloadable.
We had a quick look and it seems like some server side changes are needed to solve this, so I removed the "good first issue" tag. Maybe you would like to pick some other issue if you want to contribute?

**Comment by johnbotris** [comment]
Currently all credit invoices look the same, with just the item "Credit for Tutanota usage fees", however there are currently 2 ways to obtain credit: From a gift card or via manual intervention from a Tutanota team member. It might be desirable to specify this in the invoice message.

**Comment by jowlo** [comment]
## Test notes
 * [ ] Redeem a gift card, download and check credit statement
 * [ ] Credit account from admin client, download and check credit statement
