### ISSUE TITLE
Indexer doesn't use cache

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2291]
Indexer users `EntityRestClient` instead of `EntityRestCache` for almost all requests (except for mail indexing processing updates). We should use cache in almost all cases (with the exception of initial indexing).

**Comment by bedhub** [comment]
- [ ] create contact and check that there is only one get request for this contact
- [ ] same with receiving new email after indexing is enabled

**Comment by johnbotris** [comment]
also fixes #2289

**Comment by johnbotris** [comment]
I'm still seeing duplicate requests, an initial request by the indexer when a mail is received, and then again then the mail is opened:

![requests](https://user-images.githubusercontent.com/22109738/96872310-c2fbab80-1473-11eb-8248-aaeb4b6c1fd7.png)
