### ISSUE TITLE
Enable dragging of mails into file system to export

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2293]

**Comment by ganthern** [comment]
https://github.com/electron/electron/issues/2923

**Comment by armhub** [comment]
TODO

- [ ] Finish msg library
- [ ] Integrate msg library into Tutanota
- [ ] Handle downloading of attachments (and mail bodies + headers for multi-select). Ideas: trigger download first before being able to drag or download while dragging if it is possible to finalize the drop async later
- [ ] Decide if we want to mark imported emails, like a "[Tutanota]" prefix in the subject

**Comment by mpfau** [comment]
I see three different kinds of problems:
1. When starting the desktop client, an system error dialog is immediately shown
2. After logging in, a Tutanota error dialog is shown
3. When exporting a mail with an attachment for dnd, an error dialog is shown
4. When moving a mail that has been exported from Tutanota to the Outlook Incoming messages, a new mail editor is opened and the exported mail is attached to it. This is not the case for mails that were dropped out of outlook.

Errors:
[1. startup.txt](https://github.com/tutao/tutanota/files/5893310/1.startup.txt)
[2. after login.txt](https://github.com/tutao/tutanota/files/5893309/2.after.login.txt)
[3. export with attachment.txt](https://github.com/tutao/tutanota/files/5893308/3.export.with.attachment.txt)

**Comment by johnbotris** [comment]
I'm *guessing* 1 and 2 are not related to this issue, but I could be wrong. it looks like they are the same error too.
