### ISSUE TITLE
Synchronizing Notifications Still Appears when Disabled

### ISSUE THREAD

**Issue by SethFalco** [tutao/tutanota#2295]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Despite the fact in my notification settings I have "Synchronizing notifications" disabled, I continue to get those notifications.

**To Reproduce**
1. Install Tutanota
2. Go to notification settings on Android and disable "Synchronizing notifications"
3. Wait for Tutanota to next synchronize

**Expected behavior**
I should stop seeing this notification as soon as I disable the option.

**Screenshots**
![image](https://user-images.githubusercontent.com/22801583/94532023-a043f180-023d-11eb-8dbb-278329c39779.png)
![image](https://user-images.githubusercontent.com/22801583/94532041-a508a580-023d-11eb-9ffa-3def073e4b22.png)

**Smartphone (please complete the following information):**
 - Device: Honor 10 (128 GB)
 - OS: Android
 - Version 10

**Additional context**
I changed this setting over a week ago, but unfortunately still today I get these notifications which I have explicitly disabled.
I'm unsure if this is a problem with Tutanota, or my push notifications on Android, but think my notification settings seem to work and are effective everywhere else.

**Comment by prnam** [comment]
Sorry to ask this @SethFalco ... but is this still an issue? 🧐

I am checking this issue today and since the report was 1y ago, I thought ill check if there was any change during this period w.r.t your app upgrade / phone upgrade before I do any analysis and see if its something I can contribute on. 🙂

**Comment by SethFalco** [comment]
I've moved away from Android in favor of Linux ([PinePhone](https://www.pine64.org/pinephone/)) now, so I can't confirm.

I could technically test with Anbox, but I think it's best if someone with a real Android device attempts to reproduce the issue and reports the result here.
