### ISSUE TITLE
Calendar event not visible after create

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2296]
If i create a new calendar event it is not visible right away. I need to log out and log in again.

**Comment by sarashub** [comment]
Noticed the same behavior. Steps to reproduce:
* Create an event without reminder -> it appears in the calendar
* Create an event with reminder -> it does not appear in the calendar
* Create another event without reminder -> it does not appear in the calendar

**Comment by johnbotris** [comment]
It seems that more generally, creating an event with a causes the calendar to stop receiving any updates until the app has been reloaded. This specifically only happens upon creation of the event, not when adding a reminder to an existing event.

* Make various changes to the calendar (adding, removing, modifying events) and see that the calendar updates with each
* Make an event with a reminder
* Make various changes to the calendar, see that the calendar does not update until the app is reloaded
