### ISSUE TITLE
Add option of pinning emails [New Feature]

### ISSUE THREAD

**Issue by Cl8vM1nd** [tutao/tutanota#2298]
Hey guys. I love tutanota.
But it lacks a basic feature of **pinning emails**.
Sometimes I am working with multiple emails and I want them to be pinned so I can return to them anytime without searching through email. Please add this. Thanks!

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
