### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#230]
- change layout of folder colum to be above header bar (design update)
- consider position of new mail button

**Comment by stantond** [comment]
Also worth reviewing the Material Design guidelines and revisiting some basics like navigation across the whole app. I tried the app a couple months ago and found there are some very confusing design bugs (or choices)

**Comment by mpfau** [comment]
Some errors can be triggered by changing window size on the current dev state

**Comment by stantond** [comment]
Do you have any wireframes or designs you'd be happy to share for user feedback here before starting development?

**Comment by charlag** [comment]
@stantond there were wireframes few weeks ago, they're implemented now, I just noticed this issue only now.

**Comment by stantond** [comment]
@charlag are you sure? Unless there's some unreleased work on this, none of the obvious GUI improvements for mobile have been implemented

**Comment by charlag** [comment]
It's not released yet, that?s coming with the next release.

**Comment by charlag** [comment]
Things are very sad on notched iPhones

**Comment by stantond** [comment]
OK, sure. What's the version number? I'll keep a look out

**Comment by charlag** [comment]
It will be some of the 3.66 versions, we've found some issues with 3.66.0 so it will be 3.66.1 at least

**Comment by stantond** [comment]
Does this include moving to sensible icons that align with the typical mental models users have for how to navigate an app? There are a lot of breaks in convention which have the negative impact of increasing cognitive effort to achieve basic app navigation.

**Comment by charlag** [comment]
Yes

**Comment by bedhub** [comment]
* new email  button is shown for external users, contact form users and with ReplyOnly feature
* Bottom navigation on mobile shows tabs for calendar, search and contacts for externals and enabled Features
* left menu show settings for externals

**Comment by stantond** [comment]
This is definitely a big improvement, good work!

I'll try and review it in a few days, may have some tips for your next go at it, assuming you're interested in Product and Design contributions as well as code.

Question - why was the floating button removed? This seems like a design regression rather than an improvement. They're great when implemented just right.
