### ISSUE TITLE
Handle PayloadTooLargeException on client side

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2300]
We should handle this exception whereever we post to the server (e.g. save draft, save contact, save calendar entry, save signature, save custom mail, save whitelabel customizations)

**Comment by johnbotris** [comment]
PayloadTooLarge is now handled when sending and saving mails, saving signatures, saving notification templates and saving contacts.

**Comment by mpfau** [comment]
We accept that the dialogs might not be shown on chrome currently (see #2350)
