### ISSUE TITLE
Contact are imported in parallel

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2302]
v3.76.10

Contacts are imported in parallel. It must be done one by one to not runinto rate limits.

https://github.com/tutao/tutanota/blob/dcd42872df32c06da4d4338479a28f8a8507b3f7/src/contacts/ContactView.js#L251-L264

**Comment by bedhub** [comment]
- [ ] import contacts and check that they are created sequentially
- [ ] import contacts from two files
