### ISSUE TITLE
Tutanota not reconnecting after extended sleeps

### ISSUE THREAD

**Issue by M1ch431** [tutao/tutanota#2306]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When Tutanota is focused (not minimized) and my computers go to sleep for a few hours; upon waking and logging in, Tutanota stays in a reconnecting loop (red/white bar on top of window that never goes away) until I restart the application or close and reopen the window from the tray (in which case it logs back in). This could be related to my VPN (Mullvad), which has a killswitch and has to reconnect upon waking, but even after regaining internet connection Tutanota does not retry/update.

**To Reproduce**
1. Have a VPN (Mullvad in my case) with a killswitch enabled and connected. Have Tutanota open and active and put the computer to sleep for a few hours.
2. Wake computer and log in. VPN should automatically reconnect, if not reconnect to the VPN or disable it.
3. See Tutanota not reconnecting and a red and white bar at the top of the window.

**Expected behavior**
Tutanota should be trying to connect as long as the \ \ red and white bar is appearing on the top of the window.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Latest Tutanota (as of 03-Oct-20)

**Additional context**
My VPN may have zero to do with this issue.

**Comment by charlag** [comment]
When you are not on the login screen, we continiously try to reconnect. Can you plese check the worker logs (settings->about->send logs)? All reconnection attempts should be listed there.

**Comment by M1ch431** [comment]
I don't seem to be having the issue anymore.
