### ISSUE TITLE
[Desktop] Trackpad zooming is too sensitive

### ISSUE THREAD

**Issue by RiffLord** [tutao/tutanota#2317]
Pinch zooming with the trackpad on a laptop is far too sensitive, making it hard to adjust the size of the UI elements. They often end up much bigger or much smaller than intended.

**Comment by charlag** [comment]
Hi
I don't think we have control over this?
Could you also specify some more information (which we ask in the issue templates) like your app and OS versions?

**Comment by RiffLord** [comment]
Forgive me, I seem to have missed the issue template.
I'm using version 3.76.10 of the desktop app on Windows 10 Home (version 2004, build 19041.508).
