### ISSUE TITLE
[Desktop] Calendar: Drag & drop import of events

### ISSUE THREAD

**Issue by mariozski** [tutao/tutanota#2318]
Hi,

As a user, I would like to have a possibility to import calendar events by simply drag & dropping e.g. *.ics file on the Desktop calendar instead of having to go to hamburger menu -> ... dots near calendar name -> Import -> search file on disk and import event.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
