### ISSUE TITLE
User defined templates

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2326]
As a user i want to be able to add predefined text templates into an email. I often receive similar questions and i need to reply with the same text for a question or even add multiple texts into the the same reply if there are multiple questions. I also need to reply in different languages for the same topic. 

To find a default answer a small popup or dialog should appear were i can search for a text template and select one of the templates. The selected template should then be added at the current cursor position in the mail editor.
Opening the template search can either be with a button in the mail editor or by using a special key combination like Ctrl+Space. 

For having quick access to the text templates i want to be able to define keywords which i can type into the mail editor and then upon template search activation the template will be automatically added to the editor. When there are multiple languages for a keyword i still want to be able to select the language before the text is added.

For maintaining (create/update/delete) the templates i need a section in the settings. As author of these templates i want to be able to create my own templates but also share them so other users of my organization can use them.

**Comment by Pa7Hub** [comment]
- [ ] Window function

- [ ] Navigation

- [ ] Filter

- [ ] Submit

**Comment by fim-hub** [comment]
- [ ] optimize initializing of first template in mail editor
- [ ] rename tag -> shortcut
- [ ] remove templates button inside mail editor for normal user
- [ ] add option to filter templates inside settings
- [ ] optimize scroll inside template popup
- [ ] Translationkeys / Phrase

**Comment by johnbotris** [comment]
# Test notes

## In settings view

- [ ] trying to create templates or accept template group invitations will prompt the user to first buy the business feature if  they dont have it
- [ ] user can create/edit/delete templates when they have the correct permissions
- [ ] user can accept invitations to use shared template lists, permissions will be respected
- [ ] user can share template lists, either their own or those for which they have permission to share
- [ ] user can leave any shared template list, or remove other users when they have the correct permissions
- [ ] sharing/accepting/declining template group invitations will send a notification mail
- [ ] the action button for a template list will only show when that list is selected

## In mail editor

- [ ] user can open the template popup with the button in the editor toolbar or with Ctrl+Space
- [ ] user can create new templates from the popup, but will be prompted to first buy the business feature if they dont have it
- [ ] user can edit or delete templates from list for which they have write permissions
- [ ] user can add templates to list for which they have write permissions
- [ ] the list in the popup is updated accordingly

- [ ] selecting templates works by double clicking or clicking the select button. The currently selected content language is respected
- [ ] type the shortcut for a template in the editor and hit tab. It will be autofilled when there is only one language for that template, or they will be shown a dropdown to select the language
- [ ] highlighting some text and then opening the template popup will automatically fill in the filter text field
- [ ] the filter correctly filters items in the list of templates
- [ ] up and down keys can be used to navigate the template list

 # Regression testing
 
- [ ] sharing calendars
- [ ] accepting and receiving calendar invites
- [ ] notification mails are sent and have the correct text
- [ ] calendar permissions are respected
- [ ] when a calendar is deleted, all of the events/alarms/permissions etc are also removed from the database
- [ ] all of the above, but tested from an old client

- [ ] PremiumLegacy/Business feature still works 
- [ ] shortcuts on dialogs are still respected
- [ ] you can use up and down keys to navigate all lists
- [ ] all lists still render and behave as expected
- [ ] mail editor will not send if the bubble fields have leftover text
- [ ] the action button on user settings still shows when the Users section is selected, still works correctly

**Comment by brshub** [comment]
Deleting an addition to the knowledge base throws an error message:

Feedback v3.83.0 - NotFoundError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.83.0
Timestamp (UTC): Fri, 23 Apr 2021 09:28:15 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4455.2 Safari/537.36
NotFoundError
Error message: 404: MYy2jCE----0 | DELETE /rest/tutanota/knowledgebaseentry/MYxapNo--7-0/MYy1tbX----0
Stacktrace:
NotFoundError: 404: MYy2jCE----0 | DELETE /rest/tutanota/knowledgebaseentry/MYxapNo--7-0/MYy1tbX----0
at ac (https://test.tutanota.com/common-min-c46f8113.js:1:2654)
at XMLHttpRequest._suspensionHandler.isSuspended.f.onload (https://test.tutanota.com/worker.js:1:104169)

**Comment by johnbotris** [comment]
The template button is visible in the mail editor toolbar in an external mailbox

**Comment by jowlo** [comment]
## Testing

### Settings
 * When deactivating the business feature we show the following text. 
![Screenshot from 2021-04-23 13-09-44](https://user-images.githubusercontent.com/6842104/115863104-47d07d80-a435-11eb-993d-ca41fd2e16f3.png)
We show this error if we still have templates _after_ the order dialog. We should warn the user in the first dialog and check if it is possible to downgrade.
 * Without any templates (never created any or deleted all doesn't matter) i still _cannot_ deactivate business feature. Only one user is active. Did work with a user created after the update and buying business _after_ the update, removing the templates and then deactivating. Did not work with an account that had business before the upgrade.
 * When accepting a template list invitation from a free account i first need to upgrade to premium and afterwards i am told i also need business. This should be clear in the beginning _before_ the first update.
 * When trying to add a user to a template list that already is a user (eg to give them more rights) we show am error that mentions "calendar"
![Screenshot from 2021-04-23 13-23-54](https://user-images.githubusercontent.com/6842104/115864475-2ec8cc00-a437-11eb-8fcd-aa3d9bb946df.png)
 * The *Sharing* dialog is not updated on the receiving site after removing and readding a participant with more rights, resulting in a user listed twice:
![Screenshot from 2021-04-23 13-27-07](https://user-images.githubusercontent.com/6842104/115864850-c7f7e280-a437-11eb-92ce-a248a02d0b06.png)
 * If i want to reshare a template list that was shared with me by someone else, i appear to also need the sharing feature myself, is that correct?
 * I was able to add a template with multiple language entries, when reselecting the same language multiple times i can create the same language multiple times. Is this supposed to be happening?
![Screenshot from 2021-04-23 13-35-21](https://user-images.githubusercontent.com/6842104/115865620-dd214100-a438-11eb-9757-9572d686a452.png)
![Screenshot from 2021-04-23 13-38-01](https://user-images.githubusercontent.com/6842104/115865974-55880200-a439-11eb-8bfc-46897a6feebc.png)
![Screenshot from 2021-04-23 13-40-23](https://user-images.githubusercontent.com/6842104/115866080-7a7c7500-a439-11eb-8677-b0a556b273ca.png)

 
### Mail Editor
 * If in text only mode (no rich text toolbar) i do not see a button to show the templates. Ctrl-space works fine.
 * The template popup does not give a hint about which list the template originates from. This would probably be helpful.
 * When filtering the templates also content in other languages leads to selecting the template but does not select such language.
 * The scrollbar on the list of (filtered) templates overlaps with the `>` arrow
![Screenshot from 2021-04-23 13-56-33](https://user-images.githubusercontent.com/6842104/115867927-f7a8e980-a43b-11eb-9e1b-7294e9090399.png)

**Comment by jowlo** [comment]
While trying to reproduce the "cannot remove business feature"-bug i triggered a `500 internal server error`:

```
Feedback v3.83.0 - InternalServerError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.83.0
Timestamp (UTC): Fri, 23 Apr 2021 13:22:30 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
InternalServerError
Error message: 500: MYytLIG----0 | DELETE /rest/tutanota/templategroupservice
Stacktrace:
InternalServerError: 500: MYytLIG----0 | DELETE /rest/tutanota/templategroupservice
at ac (https://test.tutanota.com/common-min-c46f8113.js:1:2992)
at XMLHttpRequest._suspensionHandler.isSuspended.f.onload (https://test.tutanota.com/worker.js:1:104169)
```

**Comment by johnbotris** [comment]
When sending a template group invitation, if the sender doesn't have a sender name set then the invitation email will say "hello, has invited you....", we should use the email address in this case. Also there is a typo in the text.

**Comment by johnbotris** [comment]
#2874

**Comment by johnbotris** [comment]
# testing notes
- [ ] A template can only have one content per language
- [ ] Deleting a template list will not cause a 500 error
- [ ] There is no mention of calendar where it should be referring to templates
- [ ] No error is thrown when opening a mail editor in an external mailbox/it is not possible to access templates in external mailbox
- [ ] There is no knowledgebase button in mail editor in external mailbox

**Comment by johnbotris** [comment]
The template popup doesn't work in the mobile app. I would suggest that we postpone mobile release, and that the current version of the popup would generally not work very well in mobile, so we should disable it in apps for now and maybe come up with a mobile friendly version, although I'm not convinced that it would be super necessary to access templates on mobile

**Comment by jowlo** [comment]
@johnbotris What do we do for users using the webapp from a phone browser. I just tested it and the dialog just pops up and closes again (like it probably does on the mobile apps as well).

**Comment by jowlo** [comment]
I think we should keep this open as there are still some unresolved issues, most regarding usability.

**Comment by johnbotris** [comment]
I would say better to make a new issue for specific problems
