### ISSUE TITLE
[New Feature] Mark important messages

### ISSUE THREAD

**Issue by Open-wan** [tutao/tutanota#2327]
Hello,

Thank you for your wonderfull work.

Is it planned on a roadmap to have a possibility to Mark important messages ?

Best regards

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
