### ISSUE TITLE
Desktop Integration - Entry is malconfigured

### ISSUE THREAD

**Issue by filipeluna** [tutao/tutanota#2328]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Describe the bug**
I use Budgie which comes with Plank, a desktop dock which shows the currently open and pinned programs. Whenever I pin Tutanota desktop, I get a duplicate entry when i run it.

Only one application icon should appear on Plank, but this isn't the case as the AppImage process and *.desktop entry have different WMClasses

Original tutanota-desktop.desktop:
````
[Desktop Entry]
Name=Tutanota Desktop
Comment=The desktop client for Tutanota, the secure e-mail service.
Exec="/home/user/software/tutanota-desktop-linux.AppImage" %U
Terminal=false
Type=Application
Icon=tutanota-desktop.png
**StartupWMClass=de.tutao.tutanota-desktop**
MimeType=x-scheme-handler/mailto;
Categories=Network;
X-Tutanota-Version=3.76.11
TryExec=/home/user/software/tutanota-desktop-linux.AppImage
````
To fix this issue, all that is necessary todo is remove the "de.tutao." prefix from the StarupWMClass.
de.tutao.tutanota-desktop -> tutanota-desktop

**To Reproduce**
1. Run the AppImage on an Ubuntu-based distro.
2. Choose to integrate the Tutanota appimage with the desktop.
3. Pin tutanota desktop to the Plank dock.

**Desktop (please complete the following information):**
 - Ubuntu Budgie 20.04 LTS

**Comment by bedhub** [comment]
see comment in pull request

**Comment by filipeluna** [comment]
Thanks to all the Tutanota team for all the attention regarding this issue! Cheers!
