### ISSUE TITLE
Reset account / 2FA

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#233]

**Comment by alvarogr91** [comment]
Hi guys! Do you know when it will be available? I just lost my password and I habe really important data in my account :-/

**Comment by armhub** [comment]
Text "Wiederherstellungs-Code" is cut off in recovery code dialog

**Comment by ganthern** [comment]
It's saying 'invalid password, check it again' when using a wrong recovery code.
Maybe we should just change the failure message to 'Invalid Credentials'?

**Comment by mpfau** [comment]
The recovery mask uses plural "Email addresses" but should be "Email address".

**Comment by mpfau** [comment]
The login message "Invalid login address" should contain a link "Lost access?" that opens the recovery mask.

**Comment by armhub** [comment]
Fixed all remaining issues in e447c47
