### ISSUE TITLE
Scaling does not work in mobile view

### ISSUE THREAD

**Issue by ida** [tutao/tutanota#2336]
When viewing a message on my mobile phone, zooming in by moving two fingers apart does not work.
This applies to viewing it in the Android-app as well as viewing it in a web-browser.
Additionally in the Android-app the body-text gets resized smaller, so the whole width fits the screen. This decreases the font-size and it gets too small to read it without a magnifier. In a web-browser resizing fortunately does happen, you need to scroll horizontally, but the font-size stays readable, still zooming is not possible.

**Comment by pstorch** [comment]
Got hit by this bug, too.
Got a Mail with a very long line. The text is so small that I can't even read it in the App.

**Comment by charlag** [comment]
We evaluated if it would be possible to implement pinch-to-zoom and it is not possible right now. Double tap to switch into original size works.

**Comment by pstorch** [comment]
Double tap works fine for me, thanks.
