### ISSUE TITLE
show unread mail count on folders

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#234]

**Comment by x80486** [comment]
Hello there! Are there any updates on this one?

**Comment by charlag** [comment]
@x80486 not yet, sorry, we really want them but we're quite busy with other things now. We will mention this once we start working on it. Thanks for the patience.

**Comment by vladimiry** [comment]
`email-securely-app` desktop app is going to get this feature supported, see work in progress demo [here](https://github.com/vladimiry/email-securely-app/issues/32#issuecomment-419095141).

**Comment by charlag** [comment]
@vladimiry this looks very interesting! Any chance of merging parts of it to the Tutatnota itself?

**Comment by vladimiry** [comment]
@charlag that's a desktop app which keeps all the messages/folders/contacts in a local database (in-memory first, with dumping to the encrypted file), fetching is done in an incremental way consuming an event batch updates, similar to how for example mails indexer does it in this project. And that's why app is capable to get the unread counters for all the folders, it basically derives the counters form the local database. So that app works side by side with and in background of a web client enhancing user experience on the desktop. I don't think this would be an exact way to go for the web client, since it's intended to be used just in a browser, ie without Electron/Node.js backup. But technically it's, of course, doable for example to consume the even batch updates in web client, but store only the unread values per folder not overflowing a limited in-browser storage space.

**Comment by charlag** [comment]
@vladimiry thanks for validating my assumptions
Browser storage is not a problem in most cases, you can store GBs of data. Storing whole database in browser is not very secure and that's a real concern. Your proposal with counters makes sense but it will not be accurate unless for the new log-ins, is that correct?
We had an idea of storing counters on the server side and updating them on the client

**Comment by vladimiry** [comment]
> Your proposal with counters makes sense but it will not be accurate unless for the new log-ins, is that correct?

Not sure I got this question right. When a user gets logged in app makes sure that missed event batches got handled, see [this](https://github.com/vladimiry/email-securely-app/blob/7440399d4e09d64ea2d93d18d4c3d119e49fd01c/src/electron-preload/webview/tutanota/index.ts#L61) iteration. Plus there is a logic that listens on the batch updates stream and reacts accordingly, so app could get live updates, see [this](https://github.com/vladimiry/email-securely-app/blob/7440399d4e09d64ea2d93d18d4c3d119e49fd01c/src/electron-preload/webview/tutanota/index.ts#L252) observable.

> We had an idea of storing counters on the server side and updating them on the client

In my opinion, this is how it's supposed to work in most of the cases. Would be great if you go this way, so there will be no need in workarounds/hacks, but simply listening for new values on the stream. Currently used even batch like scenario also works. So desktop/web client gets an "unread"-like `EventUpdate`, then reacts to it getting the corresponding entity which contains the unread values for all the folders.

**Comment by vladimiry** [comment]
If someone wants to try it in action, I just published the [first beta](https://github.com/vladimiry/email-securely-app/releases/tag/v2.0.0-beta.1) of a desktop app with the enabled feature of showing unread count on each folder.

**Comment by snaggen** [comment]
@vladimiry I'm using the official beta, and I haven't seen any unread counters as far as I can remember. Do I need to do anything special to get unread counters on folders, or is it not included in the official beta?

**Comment by vladimiry** [comment]
@snaggen counters for each folder are enabled in database view mode, so you need to enable the `local store` feature, see [here](https://user-images.githubusercontent.com/1560781/45978558-4f4d0180-c055-11e8-8158-54d57d90bf7b.gif) how. The most recent version is [final v2 release](https://github.com/vladimiry/email-securely-app/releases/tag/v2.0.0).

If you were about enabling counters for the online/official Tutanota's UI, I believe it might be with `local store` feature enabled. You can open respective issue here https://github.com/vladimiry/email-securely-app if you want. The issue won't get a hight priority though but won't be forgotten.

**Comment by snaggen** [comment]
@vladimiry Ok, I didn't realize that you were talking about some unofficial client... for this kind of security sensitive applications, I try to keep to the official clients.

**Comment by andy5995** [comment]
Just wanted to reference the [uservoice topic](https://tutanota.uservoice.com/forums/237921-general/suggestions/36435871-better-inbox-managing) for this issue...

**Comment by charlag** [comment]
We're working on counters, so stay tuned!
