### ISSUE TITLE
Error when downloading attachment on MacOS

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2344]
Several users have reported this:

```
Error: ENOENT: no such file or directory, open '/var/folders/...
```

Tutanota version 3.76.11

**Comment by charlag** [comment]
Most people say it's when opening attachments

The question is at which moment `open()` happens. When we call our *own* `open` it catches the error (with losing the error info) so it must be some other request.

I think the error happens in `downloadNative()`:
https://github.com/tutao/tutanota/blob/c76ca300e0335807fb462ea578509b1e38cb97ac/src/desktop/DesktopDownloadManager.js#L30-L62

On both `response.error` and `stream.error` we call cleanup which will reject with whatever was passed to us.

`createWriteStream()` creates a file if it does not exist so it must be the directory which does not exist.
Indeed, on line 33 we call `mkdirp()` which is async version which returns a promise and we don't wait for it.

**Comment by ganthern** [comment]
I don't think this is happening anymore in 3.98.20
