### ISSUE TITLE
Inbox rules added in web disappear if the mobile app is opened

### ISSUE THREAD

**Issue by lionirdeadman** [tutao/tutanota#2352]
- [ x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x ] I've searched and did not find a similar issue.

**Bug in mobile app**
Inbox rules added in web disappear if the mobile app is opened
**Describe the bug**
Inbox rules added in web disappear if the mobile app is opened

**To Reproduce**
1. Add inbox rules in the web app
2. Go on the mobile app
3. Weep as all the changes you made are reverted

**Expected behavior**
Inbox rules don't disappear

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XA2
 - OS: LineageOS
 - Version 17.1

**Comment by barretobrock** [comment]
Confirming that this happens with my account as well.

When I updated the rules in the Firefox webapp on laptop, about 5-10 minutes later checked mail on my phone. After that, upon returning to my computer, the newly-added rules had disappeared after a refresh of the page.

In my case, this was with a Google Pixel 4 XL running Android 11 and a laptop with Firefox, running Kubuntu 20.04.

Also noting that these issues seem to have been covered in #1073 as well.

**Comment by lionirdeadman** [comment]
Ah, I didn't see that one. Sounds like a duplicate so I'll close in favour it.
