### ISSUE TITLE
After increasing font size, message pane not large enough

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#2353]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**
1. Settings -> Display -> increase font size
2. See error

** Expected Behavior**
The message pane should expand vertically to fit the text, combined with some text being truncated and appended with "..." (as what happens in other apps when font size is very large, for example:)
![Screenshot_20201025-002149_Settings](https://user-images.githubusercontent.com/16764864/97099557-58f02b80-1658-11eb-8724-3fd792b7064c.jpg)
 

**Screenshots**
![Screenshot_20201025-001322_Tutanota](https://user-images.githubusercontent.com/16764864/97099477-82f51e00-1657-11eb-80f1-ea3e7641cc72.jpg)

**Smartphone (please complete the following information):**
 - Device: SM-J727U
 - OS: [Android 8.1.0] (Samsung Experience v. 9.5)
 - Phone Baseband version [J727UUES8BTF3]
- Tutanota v3.76.10

**Comment by rezbyte** [comment]
I cannot reproduce this issue with the current version of Tuta Mail.
