### ISSUE TITLE
NotFoundError for calendar event

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2354]
v3.77.1
NotFoundError
Error message: 404: MKQwdO5----2 | GET /rest/tutanota/calendarevent/LlkHQXl--7-1/MTU2OTAxODA0MzY2Mg
Stacktrace:
NotFoundError. 404: MKQwdO5----2 | GET /rest/tutanota/calendarevent/LlkHQXl--7-1/MTU2OTAxODA0MzY2Mg
NotFoundError@https://mail.tutanota.com/common.js:1:260148
https://mail.tutanota.com/common.js:1:256361
https://mail.tutanota.com/worker.js:1:689040

v3.76.11
Error message: 404: MKPz3rA----2 | GET /rest/tutanota/calendarevent/Ljdy24M--V-1/MTU5OTM2MTc4OTI4OA
Stacktrace:
NotFoundError. 404: MKPz3rA----2 | GET /rest/tutanota/calendarevent/Ljdy24M--V-1/MTU5OTM2MTc4OTI4OA
NotFoundError@https://mail.tutanota.com/common.js:1:254868
@https://mail.tutanota.com/common.js:1:251140
value/

**Comment by johnbotris** [comment]
- [ ] get rate limited and then make a request that returns a not found error, ensure that no unhandled exception occurs

(this can be achieved by trying to delete a calendar twice while rate limited

**Comment by armhub** [comment]
However, the client does not catch NotFoundError for deleted calendars yet.
