### ISSUE TITLE
Show progress bar for loading calendar when initially accessing it

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2357]
While loading you just see a calendar without events.

**Comment by charlag** [comment]
I have doubts we will need this when offline comes. After the initial loading it should be instant and for updates we will have progress bar anyway.

**Comment by charlag** [comment]
Test notes:
- [ ] Test that no progress on starting the app
- [ ] Test that there is progress on loading calendar for the first time
- [ ] Test progress on reconnect
- [ ] Test calendar import shows progress dialog
- [ ] Test mail indexing progress not in the header but in searchbar
