### ISSUE TITLE
Insecure password message is shown for confidential message to custom domain email address

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2358]
1. Create contact for custom domain email address and specify an agreed password which is simple.
2. Add custom domain to Tutanota account and create an email alias
3. Set default delivery to non-confidential
4. Create a new message and enter the email alias as recipient
-> The status underneath the subject is not end-to-end encrypted. It should be end-to-end encrypted because messages to internal users are always encrypted.
5. Send the message
-> The message dialog appears showing that the password is insecure. Seems like the recipient address is not handled correctly as internal address.

https://twitter.com/dmanduzio/status/1320674691120537600

**Comment by johnbotris** [comment]
Testing:
Have a mail editor open with a custom domain tutanota user as a recipient
- [ ] ensure that the correct confidentiality message is displayed under the subject
- [ ] the custom domain recipient's password should be ignored upon sending if it has one set in it's contact
