### ISSUE TITLE
whitelabel: disable associated accounts

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#236]

**Comment by mpfau** [comment]
Error:
* Signup a new child for domain test.keemail.net
* Deactivate the child
* Remove domain test.keemail.net from whitelabel parent
* Activate child

The last step should not be possible as the parent does not own the domain anymore.

**Comment by mpfau** [comment]
Error:
* Remove domain test.keemail.net from whitelabel parent
* Signup new child

The last step should not be possible as the parent does not own the domain anymore. When removing a custom domain and this one is used as a registration domain (Whitelabel), it must be set to disabled.

**Comment by mpfau** [comment]
Signup after removing the mail domain has been fixed as it is not possible to remove a mail domain that is used as signup domain. The error messages that is displayed when you try to remove a mail domain that is used as a registration domain is misleading: "Bitte deaktiviere zunächst alle Benutzer und alle E-Mail-Aliasse mit der Domain: keemail.net."

The following error persists: An error dialog occurs, if you 
* Signup a new child for domain keemail.net
* Deactivate the child
* Remove domain keemail.net from whitelabel parent
* Activate child

**Comment by armhub** [comment]
Reactivation issue is handled in #276
