### ISSUE TITLE
SSE: Only pass single userid to authenticate

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#2362]
We should delete the stored userId if the authentication fails and proceed with next userId.

See server issue 615.

**Comment by charlag** [comment]
Test notes

We need to get into situation where the decide knows multiple users but the first used one* doesn't have such a push identifier anymore.

1. Add multiple user
2. Login into the first/last added user (Android/iOS take the last, Desktop takes the first but maybe better to test both)
3. Go to Settings->Mail->Notifiactions
4. Remove current push identifier
5. Send email to *another* user than the one you removed push identifier for

For alarms it's similar but with scheduling the alarm from the same user
