### ISSUE TITLE
Too big file attachments not being handled gracefully

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2367]
Trying to attach a file that is too big throws an error that isn't being handled in most places

**Comment by johnbotris** [comment]
Testing:
- [ ] Attach too many or too big files to the mail editor and ensure that an unhandled error doesn't occur
- [ ] also try attaching by dropping into the mailviewer

**Comment by bedhub** [comment]
Dropping on mail editor shows different error message: "File could not be loaded"

**Comment by johnbotris** [comment]
Sharing too many files from native fails but with no error message
