### ISSUE TITLE
Unify Chinese translations

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2371]
The languages zh-tw and zh-hant are not well maintained anymore. We will only support one of them which should be zh-hant (chinese traditional). The default chinese translation key zh should be renamed to zh-hans (chinese simplified). We will have two chinese translations then, zh-hans and zh-hant.

**Comment by johnbotris** [comment]
> We will only support one of them which should be zh-hant

>We will have two chinese translations then, zh-hans and zh-hant

I'm unsure what to make of this... are we saying that we will have one set of translations to which both keys zh-hans and zh-hant will map to? or we will have both sets of translations but only *officially* support zh-hant?

**Comment by bedhub** [comment]
Yeah, that is what this issue is about dropping zh-tw and renaming zh to zh-hans. I think Hanna already prepared this step in phrase app and we just need to make sure that translation keys are working fine on all devices and on the server after updating languages from phrase.

**Comment by bedhub** [comment]
Test notes:
- [ ] Check that switching to new language is possible
- [ ] Send notification email in new language

**Comment by jowlo** [comment]
UI and mail notification is fine, but the translation keys are a bit inconsistent, for example the language key which has the English "Language" on it only in one of the chinese variants. Although i think this is not a bad idea to have in any language, in case you accidentally all the things.

![Screenshot from 2021-02-19 17-49-30](https://user-images.githubusercontent.com/6842104/108534998-13c4c900-72db-11eb-88fb-da7c1ad39b5c.png)

![Screenshot from 2021-02-19 17-49-14](https://user-images.githubusercontent.com/6842104/108535015-1cb59a80-72db-11eb-87f7-daddb7121276.png)
