### ISSUE TITLE
Enable drag & drop events in calendar [new-feature]

### ISSUE THREAD

**Issue by alternaivan** [tutao/tutanota#2372]
Hello,

Is there a possibility to make events in calendar "movable" > you can drag the event to a new time slot and drop it there and by that update the event?

Thanks,
Marjan

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
