### ISSUE TITLE
Tab Not working to Email Body

### ISSUE THREAD

**Issue by who8mypnuts** [tutao/tutanota#2380]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When using the tab button from the Subject line, through encryption, attachments, so on, the tab used to go to the message body so that one could begin typing without having to remove one's hands from the keyboard. This no longer works in the Linux desktop 3.77.3 version.

**To Reproduce**
1. `n` for new message
2. add recipient
3. tab to subject and type subject
4. tab tab tab tab tab tab tab argh!

**Expected behavior**
I expect to hit tab three times after completing the subject line and then be able to start typing the body of the email. Instead the tab key never goes to the body.

**Screenshots**
none needed

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - Desktop Environment, if applicable (on Linux) KDE
 - Version 19.5

**Additional context**
This worked in previously, two versions ago. No so in the most recent.

**Comment by charlag** [comment]
Can confirm that, side effect of #2369

**Comment by jowlo** [comment]
also fixes #2413
