### ISSUE TITLE
Leader client

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2402]
Some task are not required to execute by all connected client. There should be a leader status for the client which is responsible for processing inbox rules, updating entropy on TutanotaProperties and updating ownerEncSession key.

**Comment by bedhub** [comment]
See commits: e44567d4 31f53071

**Comment by bedhub** [comment]
- [ ] Check that only the leader client executes inbox rules for new emails received when logged in
- [ ] Non leader client may still process inbox rules when explicitly selecting the inbox folder
- [ ] Check that only the leader client updates the owner enc session key
- [ ] Check that only the leader client updates entropy
- [ ] Check switching of leading client when disconnecting.
- [ ] Check that old clients can receive push notification without errors

**Comment by mpfau** [comment]
* non leaders still download incoming mails immediately
* desktop client push does not work for me
