### ISSUE TITLE
[ios] Not possible to add pdf documents as attachment

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2404]
The new photo picker is working but i cannot add other files like documents or images taken from the camera anymore.

**Comment by MatthewPhilipStadler** [comment]
Tutanota won't attah documents to my emails. This began a week or so ago. I need to attach documents for my work. How can I fix this?

**Comment by charlag** [comment]
We will release a fix soon, for now you can open tutanota in safari

**Comment by MatthewPhilipStadler** [comment]
You mean on the website (not the app) attachments work? Why? And why did no one say so earlier? Is this system wide? PLEASE answer at least the last question. It's very disturbing that Tutanota thinks it's normal for emails to not allow attachments. Matthew
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


4 Nov 2020, 18:50 by notifications@github.com:

**Comment by MatthewPhilipStadler** [comment]
The Safari site "mail.tutanota.com" rejects my login! Why? I'm certain that I typed my password in accurately. What's going on?

Thank you for helping, Matthew
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


4 Nov 2020, 18:50 by notifications@github.com:

**Comment by charlag** [comment]
It's not normal, it a bis mistake, I apologize. It only affects ios app, not website. Check your *email* and password.

**Comment by MatthewPhilipStadler** [comment]
Thank you for helping me. I really support Tutanota, and I hope they thrive. But it's impossible to function with any email system that won't carry attatchments. Worse still, that their support team treats this like a "bug." That's bizzare. This is an email system that doesn't work—not a "bug." I'll try every option to make my Tutanota account function normally. I wish Tutanota would do the same. M
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


4 Nov 2020, 19:14 by notifications@github.com:

**Comment by MatthewPhilipStadler** [comment]
Thank you! Do I just download the fix from Github into my iPad? I've never used Github before, but thank you so much for fixing this. What do I do next? Matthew
-- 
 Sent with Tutanota, the secure & ad-free mailbox: 
 https://tutanota.com


5 Nov 2020, 14:07 by notifications@github.com:

**Comment by charlag** [comment]
Hi
We published the new app version for review, now Apple will review it and update will be available in App Store
