### ISSUE TITLE
Out of office notification

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#241]

**Comment by jamesscaur** [comment]
Yes please!

**Comment by jflatz** [comment]
There should be options to only send these notifications to Contacts within your contact-book, as well as within the same domain / organization.

**Comment by Munisha2003** [comment]
Oh, please do give us auto reply as soon as possible. It's the one thing that prevents me using my Tutanota account for everything and giving up on other email services. I need a secure account because of the nature of my work, and the people I advise worldwide need to know how to contact me in emergencies and there is no way to tell them this at present. It's a real problem. Thank you!

**Comment by idimitriadis0** [comment]
When you implement this feature, please allow the user to edit the Out-of-office subject line as well, or at least to set its language. Thanks!

**Comment by acidicX** [comment]
It would be really cool to have an API that can be used to set this, to integrate into other calendar / time tracking solutions.

**Comment by Munisha2003** [comment]
I really do need an out of office facility on Tutanota as soon as possible. 
I also need to be able to send large group emails.
Without these two functions, my Tutanota account is quite limited in its usefulness and I have to carry on running another, non-secure, account which does those, as well.
Best wishes,

Catherine
Munisha (Catherine Hopper)
European Safeguarding Officer
European Liaison Officer (inter-Buddhist co-operation)
The Triratna Buddhist Order and Community

+44 (0)7982 408134
+46 (0)73 093 5816 for WhatsApp
Skype: catherine-hopper
www.thebuddhistcentre.com <http://www.thebuddhistcentre.com/>

This email address is for confidential communications and will not generate an auto reply if I am away. 

If you need help urgently please email safeguarding@triratnadevelopment.org <mailto:safeguarding@triratnadevelopment.org>. If I am away this will generate an auto reply containing emergency contact details.




7 Oct 2019, 13:27 by notifications@github.com:

**Comment by bedhub** [comment]
Created a first prototype for out of office notification
* Each user should be able to define its own notification message
* It should be possible to define start and end date, start date is required end date is optional

* [ ] GUI for creating out of office notification, including Subject, Message, Start and End date.
* [ ] Support templates and set a default text
* [ ] Send notification for internal senders
* [ ] Send notification for external senders
* [ ] Prevent loops
* [ ] Restrict sending (abuse, newsletter, notification emails)

**Comment by jamesscaur** [comment]
YES! Thank you @bedhub!

**Comment by jamesscaur** [comment]
Is there any way to get beta access to the prototype?

**Comment by mpfau** [comment]
Not yet. Will probably not take too long...

**Comment by dragonfruit637** [comment]
Almost finished? It's holiday now, so an out of office notification would be great! Being honest? We need it desperately.

**Comment by ECPMF** [comment]
there are news on the out of office notification?

**Comment by vaf-hub** [comment]
After reading [RFC3834](https://tools.ietf.org/html/rfc3834) I add the following requirements:

When to send:
- only once in 7 days/24 hours?
- only send if Auto-Submitted header is missing or has value "no"
- only if Return-Path address is explicitly part of To, Cc, Bcc,Resent-To, Resent-Cc, Resent-Bcc (not for Catch-All mailbox)

When not to send:
- original message has one the following header
1. Precendence with value "list", "auto reply", "bulk", "junk"
2. List-* header field
3. X-Auto-Response-Suppress with value "All" or "OOF" (for exchange senders)
4. X-Autoreply
5. X-Autorespond

How:
- only send to one recipient
- send message back to envelope sender (Return-Path)
- limit cache size of senderrecipient tuples to keep track of sent-out notifications
- limit size of message (1024 characters?) and subject (78 characters?)
- the same notification is sent for all addresses (aliases) belonging to a mailbox

Response format:
- SMTP MAIL FROM: <> (empty envelope sender)
- RCPT-TO: originalSender@external.com NOTIFY=NEVER (if supported)
- header:
1. In-Reply-To: messageId
2. References: meesage-id
3. From should contain name and address of original recipient
4. To only one address
5. Date set to the time the notification is sent
6. Subject preceeded by "Auto: "
7. Auto-Submitted: "auto-replied"

**Comment by vaf-hub** [comment]
Test notes:

- [ ] envelope sender in notifications sent to external senders is not set: <>

**Comment by vaf-hub** [comment]
avoid sending out of office notifications for feedback reports, resolved by #2570

**Comment by vaf-hub** [comment]
Test notes:
- [ ] check basic functions: define out of office notification for inside and outside and verify the correct message is sent to 1) addresses belonging to the same customer, 2) other Tutanota customers and 3) unsecure external recipients. (secure external are not supported at the moment.)
- [ ] check messages are only sent during time range specified, check corner cases. (it is allowed to only specify a start date and no end date)
- [ ] envelope sender in notifications sent to external senders is not set: <>
- [ ] check no out of office notification is sent as reply to automatic mails (mailing lists) (verify with mail log)
- [ ] check that out of office notification is sent after external recipient has clicked the whitelist service link to prove it is not spam
- [ ] no out of office notification is sent by catch-all mail addresses
- [ ] out of office notification is sent as non-confidential, but invoice and other mail notifications are still confidential

**Comment by vitoreiji** [comment]
End date of time range is displayed as the next day after saving.

**Edit dialog:**
![image](https://user-images.githubusercontent.com/197261/108518829-4fef2e00-72c9-11eb-9121-b4395819aa97.png)
**After saving:**
![image](https://user-images.githubusercontent.com/197261/108518877-5c738680-72c9-11eb-9956-da645a5f1e4a.png)

**Comment by vitoreiji** [comment]
Stuff I could not test:

* whitelist service
* invoice and other mail notifications are still confidential (how do I trigger invoice mails?)
* push notifications (could not build android app)

**Comment by vaf-hub** [comment]
Additional Test notes after fixes:

- [ ] try executing sendInfoBatchJob
- [ ] trigger sendFailureNotification

**Comment by charlag** [comment]
Empty subject is possible and it looks weird:
![Screenshot from 2021-02-24 11-22-18](https://user-images.githubusercontent.com/3099142/108986606-9ca08380-7692-11eb-9572-e7328abfeab2.png)

**Comment by charlag** [comment]
I received a OOF from catch-all address, is this how it's intended?

**Comment by charlag** [comment]
When both internals have OOF enabled, no OOF is sent at all, even for the first message

**Comment by charlag** [comment]
Ah, no, it was my mistake

**Comment by charlag** [comment]
Catch all is actually not an issue, I ran into an existing alias

**Comment by vitoreiji** [comment]
> Catch all is actually not an issue, I ran into an existing alias

Now I'm wondering if these notifications should be set per alias...

**Comment by charlag** [comment]
They probably should but I think we can start as-is

**Comment by charlag** [comment]
@jamesscaur we don't know your contacts so it wouldn't be possible currently.
