### ISSUE TITLE
Move to Codeberg or another free place!

### ISSUE THREAD

**Issue by musicsd** [tutao/tutanota#2412]
Unfortunately, Tutanota does not yet have the features of a free app. Tutanota source code is on GitHub, does not have IMAP and SMTP connection feature

The first is a priority; Tutanota says our program is "free and open source", but it is not!
If the application is located in a free and open source location such as Codeberg, the application will be free and open source.
GitHub boycotts Iranian users, mocks RTL, removes apps, is not open source, and more ...
Please add IMAP and SMTP feature as well, thanks.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
