### ISSUE TITLE
Knowledge base

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2420]
A knowledge base contains information about how to reply to requests / questions received via email, this can be for example a technical support request or an order of a product. In its base variant a knowledge base entry just contains a textual description of actions that must be performed to solve the case. In addition these entries can contain references to existing text templates which can be used to reply to an email. 

**Creating**
Knowledge base entries should be maintained in the settings as a list of knowledge base entries. Each entry has a title, a keyword list, and a content. For the content it should be possible to define references to existing text templates. 

**Using**
From the mail view there should be an option to open a knowledge base window (similar to FAQ search) which can be used to find a knowledge base entry using full text search. From the found entry the user should be able to click on the referenced text template to check the content and then have the option to reply with that template. 

**Suggesting knowledge base entries**
If an email is selected and the user opens the knowledge base a suggestion should be made for matching knowledge base entries. The entries should be filtered by matching keywords within the email body and subject.

**Optional: Language detection** 
As text templates can have multiple languages it would be good to automatically detect the appropriate language for the answer. In order to achieve that we also can use the keyword list. It should be possible to define a language for a certain keyword. If a keyword matches the language of the text template should be in the language of keyword.

**Comment by johnbotris** [comment]
Currently only for private use, we will evaluate it internally but not publish it for now

**Comment by brshub** [comment]
Deleting an addition to the knowledge base throws an error message:

After creating a knowledge base article, upon deletion the first click does not actualize the UI and the second click throws the following error code. However, upon clicking back the articles are deleted.

Feedback v3.83.0 - NotFoundError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.83.0
Timestamp (UTC): Fri, 23 Apr 2021 09:28:15 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4455.2 Safari/537.36
NotFoundError
Error message: 404: MYy2jCE----0 | DELETE /rest/tutanota/knowledgebaseentry/MYxapNo--7-0/MYy1tbX----0
Stacktrace:
NotFoundError: 404: MYy2jCE----0 | DELETE /rest/tutanota/knowledgebaseentry/MYxapNo--7-0/MYy1tbX----0
at ac (https://test.tutanota.com/common-min-c46f8113.js:1:2654)
at XMLHttpRequest._suspensionHandler.isSuspended.f.onload (https://test.tutanota.com/worker.js:1:104169)
