### ISSUE TITLE
Split events which cross midnight into two parts

### ISSUE THREAD

**Issue by renaldofreire** [tutao/tutanota#2429]
- [ x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x ] I've searched and did not find a similar issue.

**Bug in web/desktop/mobile app**

**Describe the bug**
When I create an event that started on Mon 9, 8:12 pm, which ends at 6:00 am on Tue 10, the event is at the top, similar to all day events. Why does this type of event not appear throughout the day?

**To Reproduce**
1. Creat a event,
2. Insert start date at mon 9, 8:12pm and finish tue 10, at 6 am;
3. Event is create fix at the top;

**Expected behavior**
Events should fill in during the start day, migrating to the end day and time, even if it is the next day.

**Screenshots**
Below are some screenshots to better exemplify:

![2020-11-13_17-33](https://user-images.githubusercontent.com/35435780/99118975-402fc180-25d7-11eb-8316-6e287101dfb4.png)
![2020-11-13_17-34](https://user-images.githubusercontent.com/35435780/99118976-40c85800-25d7-11eb-99e2-7b141babd903.png)

**Comment by charlag** [comment]
Hi
This is by design. Events spanning more than one day do not make sense in a grid. Other calendars behave in the same way.

**Comment by renaldofreire** [comment]
> Hi
> This is by design. Events spanning more than one day do not make sense in a grid. Other calendars behave in the same way.

Hi @charlag, but the event is 9 hours and 40 minutes long. He doesn't have more than a day.

**Comment by charlag** [comment]
It is included in more than one calendar day. I agree it might be odd in some situations and probably agenda works better then.

**Comment by charlag** [comment]
I misunderstood the issue, I apologize. Indeed other calendars show it on top but only if it spans more than one day and it's split into two parts if it crossed midnight but is shorter than a day.

We will re-evaluate this.

**Comment by wrdhub** [comment]
This issue seems to have been fixed as part of the Calendar navigation improvements that @ganthern mentioned. Events that are less than 24 hours are shown on the two days. Events that are longer than 24 hours are still shown along the top, if we want to improve this in the future we can open another issue.
