### ISSUE TITLE
Search index is periodically lost

### ISSUE THREAD

**Issue by ark-** [tutao/tutanota#2453]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When I want to search for an email I go into the sidebar and set the search time period to many years. I then wait 30 minutes for my mails to index and then perform the search.

One would assume that now I've performed that index, and that the past cannot be unwritten (unless mails are deleted, which is just an index mishit) that this index should be stored on my phone until I uninstall or erase my data. 

However, on the rare occasion I need to search (estimate ~once a week) I'm always finding I have to rebuild the index.

**To Reproduce**
1. Go to 'Search'
2. Change date range to 2018-2020
3. Wait for index (the UI on this is awful too, if I close the window will indexing stop?)
4. Perform search
5. A week later
6. Perform same search and see that index needs rebuilding

**Expected behavior**
Index should be persistent and available whenever I want to search. Usually the reason I'm search is that I want a **quick** result.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone12 and Samsung Note8
 - OS: iOS14 .1 and Android 10 (Samsung OneUI v2.5)

**Comment by charlag** [comment]
Hi, thanks for the bug report.
It should work as you describe but seems like there are some issues with the database when we give up and start over again.
We'll keep collecting info.

**Comment by jeroen7s** [comment]
Similar issue here (Desktop app + android app)
Have to re-build the index pretty often before I'm able to search.

**Comment by bedhub** [comment]
We still receive reports about this case, especially from users with a windows desktop client. What they observed is that the search index is lost with each update of the application. @johnbotris or @ganthern  can you please check if that is the case? One user reported that he has installed the windows desktop client for all users i don't know if that makes a difference for the search index.

**Comment by jeroen7s** [comment]
Can confirm, just received an update on the desktop client and the search index is gone again (note I'm on Linux, not windows)

**Comment by remi-sc** [comment]
I was on 3.77.4 more than a month - index cache has disappeared several times without updating during this period.
Now I just installed 3.81.8 and upon launching I still have functioning cache (it did not nuke itself like I expected)

(this is on linux desktop)

**Comment by LuckySandwich** [comment]
> We still receive reports about this case, especially from users with a windows desktop client. What they observed is that the search index is lost with each update of the application. @johnbotris or @ganthern can you please check if that is the case? One user reported that he has installed the windows desktop client for all users i don't know if that makes a difference for the search index.

It's not onlly related to Windows or the desktop client.  I'm on Linux and use the web app (in Firefox) and it has happened to me at least 3 times in the last month or two.

**Comment by jeroen7s** [comment]
Also happens to me on Linux, and sometimes android as well

**Comment by johnbotris** [comment]
It looks like changes to `ClientWebSocket` in server-side commit 31b1a2fa may be the culprit. With this change we no longer create noop events, so the client can no longer detect between inactivity of some indexed group (most likely users), and going out of sync.

@armhub will discuss with @mpfau the initial reason for these changes, but reverting them would probably be the best option. I would also add some more diagnostics to confirm this if we think it necessary

**Comment by mpfau** [comment]
We removed noop events due to server side issue #623 but failed to adapt clients properly.

We need to:
- [ ] Remove the OutOfSync check from https://github.com/tutao/tutanota/blob/a251e2c0d189da1d21c22879d48401fc8ee12af4/src/api/worker/search/Indexer.js#L443-L461

- [ ] Add a new time based OutOfSync check to the indexer. Server sends date header to the client. We should store the time of last successful sync in metadata table. We want to show an error dialog in case the client is out of sync and tell the user that index will be deleted now.

**Comment by johnbotris** [comment]
# testing
- [ ] Inactive groups will not cause the index to be deleted even when regularly logging in
- [ ] Not updating the search index for 45 days will cause the search index to be deleted
- [ ] Updating client and then logging in with an out of sync index will still cause your index to be deleted
- [ ] Smoke test indexing/searching

(testing help: you can travel through time by intercepting your rest requests and replacing the `Date` header)
