### ISSUE TITLE
Hardcoded timeout prevents login on slow connection.

### ISSUE THREAD

**Issue by JustEffy** [tutao/tutanota#2458]
**Bug in web app**

**Describe the bug**
Hardcoded login timeout returns "Could not reach server, looks like you are offline. Please try again later." error message when I am online with a slow-but-functional connection.

**To Reproduce**
Throttle your internet speeds down to a few hundred kbps, and your ping up to a few hundred ms, and attempt to login to tutanota's web-based email. Observe the "Could not reach server, looks like you are offline. Please try again later." error message. Repeat as many times as you like.

**Expected behavior**
I expected to either see the timeout automatically attempt to increase, or be able to increase the timeout manually, in order to log in.

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser: Firefox
 - Version: 84

**Comment by charlag** [comment]
It times out if there's no progress for 20 seconds. Is there a way to reasonably use the client when one request takes 20s?

**Comment by JustEffy** [comment]
It timed out before 20 seconds had passed from initial page load. However, it's stopped doing it now, so I'm unable to reproduce anymore.

**Comment by charlag** [comment]
Then I would close it for now
