### ISSUE TITLE
Download notification is missing on newer android versions

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2460]
When downloading an attachment from the android application on android 10 there is no download notification anymore. There is no way  to directly access the file after downloading anymore.

**Comment by charlag** [comment]
We can either open the file directly (that's what Firefox does e.g.) or we can open the directory with
`startActivity(new Intent(DownloadManager.ACTION_VIEW_DOWNLOADS));`

**Comment by bedhub** [comment]
We should show a notification which can redirect you to the downloads folder.
