### ISSUE TITLE
Redirect to subscription dialogs after login if user has open payment or exceeded storage

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2461]
@johnbotris and I stumbled across this.

If an account needs to pay for additional storage we should redirect them to the subscription/storage dialog after login, see 

https://github.com/tutao/tutanota/blob/3b3b9812dd20aa50971c2fdc2a3d36811fd53422/src/login/LoginViewController.js#L312-L314

We also should redirect if an unpaid invoice is on the account, see

https://github.com/tutao/tutanota/blob/3b3b9812dd20aa50971c2fdc2a3d36811fd53422/src/misc/LoginUtils.js#L34-L36

It looks like this would be a good idea to generalize a bit

**Comment by johnbotris** [comment]
# Testing
- [ ] on browser, after linking paypal or credit card, the tab is closed and the user is taken back to the tutanota tab
- [ ] on app, the  user is automatically directed back to the app
- [ ] on desktop, the user is given feedback directing them to return to the client
- [ ] in the case of verification error, the user is presented with an error message and a button that will take them back to the app (in the case of browser and app)

**Comment by johnbotris** [comment]
when I log into my test account I'm greeted with this dialog
```
Sorry, you are currently not allowed to send emails because at least one of your invoices is not paid. Please update your payment data in 'Settings' ⇨ 'Payment data' and trigger the payment there afterwards.
```
clicking ok doesn't take me to payments - not sure if this is related. The curious thing is that when I navigate to payments afterwards, it shows that my current balance is 0, nothing owed, is this another bug?

**Comment by charlag** [comment]
It depends on account status. I don't know if it suppsoed to redirect?

**Comment by johnbotris** [comment]
perhaps it should? also, whats the best way to get myself in an exceeded storage/open payment state? I guess I can set some values in the admin client, I'm currently unable to login to it though

**Comment by johnbotris** [comment]
it redirects after showing the storage warning, I have to work out how to get it into an open payment state now

**Comment by johnbotris** [comment]
Ok so I was a bit confused, but it turns out that the fix was only for redirecting when storage capacity is exceeded. We should just include this version and make a separate issue for the open payment case, rather than blocking the release over this
