### ISSUE TITLE
[Suggestion/Question] DNSSEC etc.

### ISSUE THREAD

**Issue by barbiehunter** [tutao/tutanota#2462]
Hey, I don't know if this is important but maybe it would be good to have a look at the 2 tests. e.g. Tutanota has no DNSSEC and the TLS is oudated. I am inexperienced in this and marked as a question.

Test 1: https://en.internet.nl/mail/tutanota.de/448090/#
Test 2: https://starttls-everywhere.org/results/?tutanota.de (already maked a Issue to this few months ago) #1488

**Comment by barbiehunter** [comment]
Update: Now it says it dont have MTA-STS 
![image](https://user-images.githubusercontent.com/38357837/102018730-662fb980-3d6f-11eb-9445-298de43ed080.png)

Feels weird when it say on the Blog it use MTA-STS: 
![image](https://user-images.githubusercontent.com/38357837/102018740-7c3d7a00-3d6f-11eb-8709-195fe192e37f.png)

**Comment by charlag** [comment]
MTA-STS is there but it's not enforced yet

**Comment by barbiehunter** [comment]
> MTA-STS is there but it's not enforced yet
> https://aykevl.nl/apps/mta-sts/
> 
> we will change it with next release

Okay thx for the Reply then, i was abit confused about that thats why. I will let it still open and close it in the next release

**Comment by barbiehunter** [comment]
Okay i see it got Changed, nice
