### ISSUE TITLE
Flatpak desktop version out of date preventing use. 

### ISSUE THREAD

**Issue by develroo** [tutao/tutanota#2471]
I pulled the latest flatpak today but that seems to be out of date from January 2020.

```
flatpak info com.tutanota.Tutanota

Tutanota - Email client

          ID: com.tutanota.Tutanota
         Ref: app/com.tutanota.Tutanota/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 3.50.10
     License: GPL-3
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 214.0 MB
     Runtime: org.freedesktop.Platform/aarch64/19.08
         Sdk: org.freedesktop.Sdk/aarch64/19.08

      Commit: 566f335a9306e88f89d2ddcfb4f7e3602befd947ed16d18de215212387274773
      Parent: b2a44e2922f1cf601ef25957349093db179f6b8f5f6ae62ee40f85e2e95def65
     Subject: Update runtime version to 19.08 (9cf4f5fe)
        Date: 2020-01-27 11:00:12 +0000

```

Hence you are greeted with this message when you try and use it. 

![tutanota-flatpak](https://user-images.githubusercontent.com/7777993/100775618-6c32ab80-33fb-11eb-9ddd-a673e10dd070.png)

For reference I am using Manjaro Linux on a Pinebook Pro and the architecture is aarch64. However I assume all the flatpaks are built at the same time so it is probably not isolated to the stable branch for arm.

**Comment by charlag** [comment]
There's no aarch64 build at the moment. Contributions welcome.

**Comment by develroo** [comment]
WHAT? How come it installed a version from the flatpak repo in the first place ? Someone must have built it? And what are you doing closing this issue? Given Arm is becoming an increasingly important architecture this issue should be left open until addressed. 

This is not inspiring much confidence in this project.

**Comment by charlag** [comment]
There was an old build before it was handed over to us. We changed the app quite a bit since then.
We do not have plans to provide arm build yet as it would require cross-compilation of native modules for us. It can be done if build is executed completely in flatpak sandbox but we have not been successful with that. As I said, contributions welcome.

**Comment by develroo** [comment]
>  it would require cross-compilation of native modules for us. 


Sorry am I talking to a professional developer or just some pr person? Because cross compiling binaries from source and hence flatpaks can be done on any platforms and certainly compiling for arm on amd64 is pretty trivial so long as you have a sane developer environment.

Please see [this guide here](https://developer.puri.sm/Librem5/Apps/Packaging_Apps/Building_Flatpaks/Cross-Building.html) for pointers. As it stands your git repo does not have the full requirements to build a flatpak from properly anyway so how you expect people to contribute is beyond me.

**Comment by charlag** [comment]
You are not understanding the problem I'm afraid, If the build is already written in a way that it's possible to compile on any architecture, then of course you can tell flatpak builder to do that. But if it's not - and in our case we need ARM version Electron and ARM version of keytar - then it's not just a matter of telling flatpak builder which arch to build. It's not impossible but we are not at capacity right now as there are a lot of high-priority things to attend to and I would imagine that enthusiasts who use ARM as their dev machines (and who are, frankly, absolute minority at the moment) would have no problem giving us a hand.

I hope this clarifies the situation for you.
