### ISSUE TITLE
Backdoor germany 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [tutao/tutanota#2475]
germany law enforce tutanota devellop backdoor , before next year 

what realy change for user  ??

french: https://www.01net.com/actualites/le-service-mail-le-plus-securise-au-mondecontraint-d-integrer-une-backdoor-pour-la-police-2012718.html

english: https://www.reddit.com/r/ProtonMail/comments/k4itch/tutanota_is_forced_to_provide_backdoor_to_german/

backdoor weakness software global , everybody can use backdoor for me problem

judge mandantory no problem with this

**Comment by SnowyMouse** [comment]
Tutanota clarified this in a reddit post here: https://www.reddit.com/r/tutanota/comments/k3sfs5/in_englisch_court_forces_mail_provider_tutanota/ge4xywc/?utm_source=reddit&utm_medium=web2x&context=3

Basically, it doesn't affect end-to-end encrypted e-mails, so by definition of a backdoor, this isn't one.

**Comment by SnowyMouse** [comment]
Tutanota clarified this in a reddit comment here: https://www.reddit.com/r/tutanota/comments/k3sfs5/in_englisch_court_forces_mail_provider_tutanota/ge4xywc/?utm_source=reddit&utm_medium=web2x&context=3

Basically, it doesn't affect end-to-end encrypted e-mails, nor does it affect e-mails that have already been encrypted (nobody can actually directly access your mailbox), so by definition of a backdoor, this isn't one.

If you want your messages to be confidential, you'll need to send (and receive) them end-to-end encrypted.

**Comment by Disqu3-mirOir-qt** [comment]
ok thanks for explain , again media said shit , not backdoor

**Comment by artemmolotov** [comment]
> so by definition of a backdoor, this isn't one

Hello, @SnowyMouse! Are you going to add one in the future if Germany forces you?

And... Flathub now:
> Okey, **write** access to the **full filesystem**

😂😂😂👍

https://github.com/flathub/com.tutanota.Tutanota/pull/13
https://github.com/flathub/com.tutanota.Tutanota/pull/15
