### ISSUE TITLE
Sender and recipient email address is not included when printing email

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2478]
"When I print an e-mail, I have found no way to print the sender's address and the recipient(s)'s
address(es).
Clicking "See more" before printing doesn't change anything.
A few months ago, it was possible without problem."

**Comment by bedhub** [comment]
We should have just one print style for the email independent from the user interface state.

**Comment by johnbotris** [comment]
# testing
- [ ] printing an email will include the sender and recipients when the details are expanded
