### ISSUE TITLE
Order gift cards

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2481]
Allow premium users to buy gift cards for a premium memberships for other users.

**Comment by johnbotris** [comment]
# Testing notes

-[ ] Ensure that the correct gift card value is created upon purchase, and that it is applied when redeemed
-[ ] Redeeming on new or existing free account will give a Premium subscription with the remaining value as credit and payment method of account balance
-[ ] Redeeming on an existing Premium account will give the full amount as credit and will not change the payment method
-[ ] Gift card can only be redeemed for non business users
-[ ] Must get user confirmation when they are not in the same location as specified on the gift card
-[ ] Gift cards cannot be purchased without providing credit card or paypal details
-[ ] Gift cards are invoiced immediately
-[ ] Sharing via email works

## Mobile testing
-[ ] make sure that sharing works properly (for now only on android)
-[ ] check that the terms are shown and rendered properly (when purchasing and redeeming)

## Regression testing
-[ ] Login view works normally when going to paths other than /giftcard
-[ ] Extensions can still be purchased freely when using a regular payment method, invoicing still occurs in a batch
-[ ] Can write an email without being limited by max length
-[ ] Inline non-external images in the MailEditor aren't broken (they get attached properly, they are shown properly, they can be downloaded (when replying or forwarding))

**Comment by bedhub** [comment]
Not done with testing yet, just some notes

* When clicking on the gift icon in the left bar i don't want to be redirected to settings view.
* Better text for : "Hey! I hope you enjoy this gift card!"

* Layout: 
- too big to fit on mobile when scanning code (too much red).
- "Gutschein" or "Gift card" is too close to the Tutanota name. There should be more space between.
- Looks like the QR-Code and the amount are not aligned to the right.

* Mixed languages for validity e.g. "Valid in Deutschland"
* Custom message is not printed on the attached image
* When sharing via email the image is not visible as inline attachment in thunderbird or gmail 

* If my account balance is already negative then the new balance is not shown in braces.

**Comment by jowlo** [comment]
>     * If my account balance is already negative then the new balance is not shown in braces.

I tried to reproduce, but could not. Do you mean a negative account that eg bought another item, or am i missing something?
So, basically this situation

![img](https://user-images.githubusercontent.com/6842104/102246784-6b237300-3eff-11eb-8167-23df878d6f11.png)
