### ISSUE TITLE
Attendee with comma in the name does not work

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2482]
If one of the attendees has a name like `LastName, FirstName` then invitation cannot be parsed correctly.
We need to check whether we need to escape/quote the name or fix our parser to allow it.

**Comment by armhub** [comment]
Similar issue: if there are quotes in the the CN we do not see the attendee and do not show confirm/reject buttons if you are the recipients yourself.

**Comment by charlag** [comment]
We checked it and if attendee has a comma in the name it must be quoted according to the RFC (SAFE_CHAR here: https://tools.ietf.org/html/rfc5545#section-3.1).
