### ISSUE TITLE
Use LoginForm, SignupForm and CredentialsSelector in the LoginView/UpgradeSubscriptionWizard

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2485]
These GUI elements were extracted into their own classes to be used elsewhere (for gift cards). The code is currently duplicated so we should consolidate

**Comment by johnbotris** [comment]
# regression testing
- [ ] logging in with new unsaved credentials
- [ ] saving credentials
- [ ] logging in with saved credentials
- [ ] deleting credentials
- [ ] browser autofill works and the ui reacts properly
- [ ] the signup page still works as normal

**Comment by charlag** [comment]
It's probably not a regression but:
I was signing up and used credit card with successful 3DSecure. Then I came back to step 3 (payment data) and I cannot proceed anymore:
![Screenshot from 2021-01-07 12-39-51](https://user-images.githubusercontent.com/3099142/103888770-90ae3180-50e5-11eb-97dc-6b9488efb552.png)

**Comment by charlag** [comment]
So we didn't remember that we have already paid

**Comment by johnbotris** [comment]
These changes shouldn't have had an effect on payments. 
Does this have anything to do with all the braintree test cards having already been used up on the test system?

**Comment by charlag** [comment]
Seems like the error is unrelated

**Comment by armhub** [comment]
This error is also currently shown if the user tries too many times with the same credit card. We have the server issue #680 to fix this.
