### ISSUE TITLE
Gift cards: Text for item in invoice is missing

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2493]
Currently we show the order date twice but it should be something like "Tutanota gift card".
 
![invoice-giftcard](https://user-images.githubusercontent.com/8296817/102336348-57c0e800-3f91-11eb-82b1-83db22f983ff.png)

**Comment by jowlo** [comment]
How is this account configured exactly, it should say Tutanota gift card, and it for some reason it does in my test case
![Screenshot from 2020-12-16 12-19-11](https://user-images.githubusercontent.com/6842104/102342007-f56be580-3f98-11eb-9cdd-6726ff376c8f.png)

The dates are still there though

**Comment by jowlo** [comment]
Only happens to Business customers apparently

**Comment by jowlo** [comment]
Happens only on german accounts, a translation was missing. Fix is commited
