### ISSUE TITLE
Incorrect placeholder in translation key

### ISSUE THREAD

**Issue by Link009** [tutao/tutanota#2504]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Credit is being showed as variable name {lastingCredit}.

**To Reproduce**
1. Open Tutanota web
2. Click Gift Card symbol
3. See bug in the three buyOptionBox

**Expected behavior**
See remaining credits.

**Screenshots**
[Screenshot](https://imgur.com/sxT6k3Y)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [Firefox]
 - Version [84]

**Comment by johnbotris** [comment]
looks like the italian translation has the wrong placeholder key. should be "{remainingCredit}"

**Comment by jowlo** [comment]
Just fixed it in the translations. This will be fixed with the next update.
