### ISSUE TITLE
It takes way to long time to load Tutanota-pages in a webbrowser. Please do something about it.

### ISSUE THREAD

**Issue by 4tip** [tutao/tutanota#2507]
Hi. When I enter my Tutanota-mail through Firefox it takes several minutes to load the inbox and to switch to other pages like "Sent" or "Settings". That is way to slow! Please try to do something about it, if it's possible.

Best regards

**Comment by charlag** [comment]
Hi
Can you please provide more information about your broswer/system.
This looks like a connectivity issue to me.

**Comment by johnbotris** [comment]
doesn't seem like there's much we can directly do about this
