### ISSUE TITLE
Password manager RoboForm shows error message

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#251]
So RoboForm is the extension giving the error. But only when using your email system.
I currently have Chrome Version 63.0.3239.132 (Official Build) (64-bit)
Hopefully you can solve that issue?

I have used RoboForm for more than 10 years and I still use ver. 7.9.31.1 (WIN) https://www.roboform.com/version-7-old

**Comment by bedhub** [comment]
still occurs with Tutanota 3.25.11

**Comment by charlag** [comment]
Not reported for some time
