### ISSUE TITLE
Gift card mobile

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2511]
the unreleased sharing of gift cards on mobile is currently broken as the logo icon isn't being retained in our assets

**Comment by armhub** [comment]
fixed in d39c0d0b

**Comment by johnbotris** [comment]
- [ ] make sure that gift card link can be shared natively on android without throwing an error
- [ ] an icon should be shown in the preview

**Comment by charlag** [comment]
Terms do not show up on Android, empty dialog

**Comment by charlag** [comment]
I got no image on Android 10, just "share a tutanota gift card" text

**Comment by charlag** [comment]
When trying to redeem it as business I got "only private accounts can do that" dialog twice at least on top of each other

**Comment by charlag** [comment]
Also occurs on production right now when language code is en_gb

**Comment by charlag** [comment]
*with any language but en and de

**Comment by charlag** [comment]
on iOS there's a print option in gift card dialog but it doesn't work.

**Comment by johnbotris** [comment]
i think this was left in the issue but last comment has not been addressed

**Comment by jowlo** [comment]
## Test notes
 * [ ] There should be no print option on iOS
