### ISSUE TITLE
Better handle payment errors when purchasing gift cards

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2512]
Right now we just give a generic error message, it's not so helpful. We already have messages for this case so we can use those

**Comment by johnbotris** [comment]
related to server issue 675

**Comment by armhub** [comment]
fixed in 723c4afb

**Comment by johnbotris** [comment]
- [ ] Simulate payment errors when buying giftcards, make sure a useful/relevant message is given, rather than a generic one
