### ISSUE TITLE
Progress bar getting stuck

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2513]
I left the payment settings page open on mobile while I was updating the payment method of the same account using the browser. Then I unlocked my phone into the app, the progress bar got triggered, and then it stopped as shown and was stuck until i logged out:

![loading_bar_stuck](https://user-images.githubusercontent.com/22109738/102907202-9f51e300-446d-11eb-9605-632c6a5f56f4.png)

**Comment by armhub** [comment]
Same occurred for me on Android and Linux desktop. On desktop I lost the internet connection when it got stuck and it did not recover when the internet connection was re-established. We can try to reproduce it this way.

**Comment by bedhub** [comment]
Steps to reproduce are:
1. go offline
2. send mails to offline mailbox
3. go online and go offline again while progress bar is shown.
4. go online again and wait until all events are processed. 
     -> Error:  Progress bar is stucked
