### ISSUE TITLE
Paypal payment data stored but "ok" and "cancel" shown

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2517]
It is possible to press cancel and save in the paypal dialog although the paypal data is already stored.

**Comment by johnbotris** [comment]
Still WIP, I just realised this doesn't take into account the case where the user links their account, clicks save and then gets rejected by the server - the cancel button will no longer be shown and they'll be stuck (they could still press esc). This is possible, eg when the paypal account is already in use, right?

**Comment by vitoreiji** [comment]
@jowlo sorry, forgot to self-assign

**Comment by jowlo** [comment]
no problem :)
