### ISSUE TITLE
3DS2/Paypal verification windows not closed in mobile apps and desktop client

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2518]
For desktop clients and mobile apps the 3ds browser window with the message "Your credit card will be verified now..." is not closed. console shows: "Scripts may close only the windows that were opened by them."

**Comment by johnbotris** [comment]
We need to redirect the window to "tutanota://app" in the case of the app, we will have to tell the server type of app the user is using so it can send back the correct closing action in the webhook callback. In the case of desktop, the user will just have to close the tab and navigate back to the app themself

**Comment by johnbotris** [comment]
relates to server issue #698

**Comment by johnbotris** [comment]
# Testing
- [ ] on browser, after linking paypal or credit card, the tab is closed and the user is taken back to the tutanota tab
- [ ] on app, the  user is automatically directed back to the app
- [ ] on desktop, the user is given feedback directing them to return to the client
- [ ] in the case of verification error, the user is presented with an error message and a button that will take them back to the app (in the case of browser and app)

**Comment by jowlo** [comment]
>  on browser, after linking paypal or credit card, the tab is closed and the user is taken back to the tutanota tab
When i link the paypal account in the browser, the tab stays open (with a close button). The tutanota tab stays in the payment modal, clicking next is not possible

**Comment by jowlo** [comment]
With the failure case on the app i do get shown the button, but clicking doesn't redirect me anywhere.

Also, the alignment is slightly off on my phone:
![Screenshot from 2021-01-29 12-36-25](https://user-images.githubusercontent.com/6842104/106270815-d5357480-622e-11eb-9974-4befcfb7a6dd.png)

**Comment by johnbotris** [comment]
for paypal it's server side, for 3ds2 it's client side. When doing this from that app it shouldn't be calling `window.close` at all, but it seems to think you're coming from the browser, and in desktop there should be no button, so same thing, it thinks you're in the browser

**Comment by jowlo** [comment]
well, at that point i am in the browser

**Comment by charlag** [comment]
So do we reopen it or?

**Comment by johnbotris** [comment]
@jowlo but you started it in the app right?

**Comment by jowlo** [comment]
@charlag It still looks nicer than before, but i think the current behavior is more confusing than it was before. So I'd say reopen..

@johnbotris Yeah, both on desktop and on android. I just meant that that page is (obviously) shown in the browser...

**Comment by johnbotris** [comment]
So when the user cancels out of the paypal setup, paypal doesn't send the customer ID to the PaypalAgreementWebhook so we can't know which version of the page to send, meaning it defaults to the browser version. Hopefully this doesn't happen in the other error cases.

**Comment by charlag** [comment]
Fixed on the server

**Comment by jowlo** [comment]
## Test notes
 * Paypal
   * [ ] desktop
   * [ ] web
  * Credit Card
   * [ ] desktop
   * [ ] web
