### ISSUE TITLE
mail.tutanota.com is Down

### ISSUE THREAD

**Issue by wapfalls** [tutao/tutanota#2526]
When I try to login via, web app or android app, am getting the following message,

"Could not reach server, looks like you are offline. Please try again later."

Note: My internet is up and working, I even tried login over a VPN, but same issue.

**Comment by jowlo** [comment]
This sounds like a connection issue on your side.
For support requests please use [reddit](https://www.reddit.com/r/tutanota/), and github only for bug reports.

BTW: You can also check https://status.tutanota.com to see whether our servers are up and running.
