### ISSUE TITLE
Separate app for Tutanota Calendar

### ISSUE THREAD

**Issue by makkussu** [tutao/tutanota#2528]
Dear Tutanota Developers!

First of all, I highly appreciate your efforts in creating privacy-oriented, user-friendly and sustainable service. I've been a user of it for a long time and have been grateful with everything you do. 

Nevertheless, here is a suggestion of mine: a separate calendar app. I haven't been active user of Tutanota Calendar option but would love to. However, I am easily distracted by email, therefore Tutanota App is not an option for me. Is there any possibility to separate calendar and mail apps?
I understand that in terms of usability and ease, having mail and calendar is more preferable. 
As an example I would provide Proton which has separated its [Mail](https://play.google.com/store/apps/details?id=ch.protonmail.android&hl=en&gl=US) and [Calendar](https://play.google.com/store/apps/details?id=me.proton.android.calendar) apps.

**Comment by Pa7Hub** [comment]
Hi there,

thanks for the kind words! However, we only take feature requests over on our [subreddit](https://www.reddit.com/r/tutanota/) or by [contacting our support](https://tutanota.com/contact).
