### ISSUE TITLE
E-Mail in trash can trigger "save as draft" action, doesn't save it as draft however

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2535]
1. open an E-Mail, press ctrl + s or "Close" and then "Save draft" after changing the E-Mails' content
2. go to the tab "Drafts" and delete the just created draft
3. go to the tab "Trash" and edit the contained E-Mail, trigger a save as in step 1 again
4. the dialog for saving a draft will be issued, however the E-Mail will never be saved as a draft

expected behavior:
Either don't allow saving trashed E-Mails as drafts, or actually save them.

**Comment by jowlo** [comment]
### Test notes
 - Create a new mail and save as draft
 - Go to drafts and delete the new draft
 - Go to trash, select the draft and edit
 - Save edits

 - [ ] You now have a new draft in your drafts folder
 - [ ] The mail in the trash has not changed

*Bonus: Your new draft will not be automatically deleted after 30 days*
