### ISSUE TITLE
closing a dialog on login page will trigger login

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2549]
You have to tick "Store password" when logging in for this to work
1. Go to the login view (where you can enter Email, password, etc.)
2. Click on **More > Different account > Sign up** , then once the Dialog opens, close it
3. a login will automatically be triggered

alternative step 2: Click on **More > Lost account access** , then close again

https://user-images.githubusercontent.com/70587561/103290192-3d532980-49e9-11eb-8a0d-40c16cbcedfc.mp4

**Comment by johnbotris** [comment]
Default behaviour for the LoginView is to login automatically when a single user's stored credentials exist in localStorage - this means we need to take care to set autoLogin=false when routing to the LoginView for cases where that might be a bit awkward (or change the default behaviour if there are more awkward cases than fewer).

**Comment by Pa7Hub** [comment]
Bug also triggers when having some accounts credentials saved, then going into signup, completing it, Upon confirming the creation, it will log you into your saved account.

**Comment by nif-tutao** [comment]
## Test Notes
- [ ] Log-in to any account and store credentials
- [ ] Log-out and see the saved account shown
  - [ ] see that you are not automatically logged back in
- [ ] Click **More** > **Different account** > **Sign up**. When the dialog window is loaded, close it.
  - [ ] see that you are returned to the login page, but auto-login doesn't happen.
- [ ] Click **More** > **Different account** > **Sign up**
  - [ ] Select a subscription of your choice
  - [ ] Enter any email address and create a password, agree to all the conditions, then click **Next**
  - [ ] Wait until your account is created. When the next dialog window is loaded, click **Cancel** until you end up on the login page
  - [ ] see that you are not automatically logged-in to the saved account
- [ ] Click **More** > **Different account** > **Sign up**
  - [ ] Select a subscription of your choice and generally complete the sign-up proccess.
  - [ ] After you have signed-up for a new account, you should end up on the login page with previously saved credentials but not be automatically signed-in to any of the accounts.
- [ ] Click **More** > **Different account** > **Lost account access**. When the dialog window is loaded, close it.
  - [ ] see that you are returned to the login page, but auto-login doesn't happen.
