### ISSUE TITLE
keyboard shortcuts of logging in are different

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2550]
When on the login view, press F1, it will only show 
         _"F1: Show this help"_
If you are in the process of logging in and press F1, it will show:
         _"F1: Show this help"
          "Shit + Tab: Select previous"
          "Tab: Select next"_
Once logged in, the keyboard shortcuts will be full. How do the three shortcuts during login occur? 

![Screenshot from 2020-12-29 15-31-24](https://user-images.githubusercontent.com/70587561/103290954-ff570500-49ea-11eb-8ae3-697e2e2387c0.png)
on login

![Screenshot from 2020-12-29 15-31-32](https://user-images.githubusercontent.com/70587561/103290966-05e57c80-49eb-11eb-8974-a104bdbff0a8.png)
during login

![Screenshot from 2020-12-29 15-31-40](https://user-images.githubusercontent.com/70587561/103290986-13026b80-49eb-11eb-82ca-3ca4c48e1828.png)
after login

**Comment by jowlo** [comment]
> "Shit + Tab: Select previous"
:dancing_men: 

But, seriously: what is the problem?

Components are registering their respective shortcuts with the `KeyManager.js`. As soon as the UI is fully loaded, they are all there. During Login, no element registers any shortcuts.

The three shortcuts during login are actually the default ones that any Dialog registers. The `ProgressDialog` ("Loading") is a `Dialog` and therefore also registers these. We should probably prevent that, but OTOH i do not see a bug here.

**Comment by jowlo** [comment]
I think we have quite some dialogs, eg for errors, that register these by default and it could be misleading.
It's a quick fix...

**Comment by charlag** [comment]
I think they are there for accesibility and that you cannot escape the dialog with tab keys, I wouldn't change it just for the help dialog to be honest.

**Comment by charlag** [comment]
We need to ask someone why they are there in the first place. I bet they are to avoid escaping the dialog (even though we applied some other measures otherwise) and I wouldn't touch this in any case.

**Comment by jowlo** [comment]
I think it is fine if we just close this. This is a small glitch but actually pretty hard to reach (fast fingers needed) at all. And even then it kinda makes sense even. I'd vote to close with `wontfix`

**Comment by Pa7Hub** [comment]
> 
> 
> I think it is fine if we just close this. This is a small glitch but actually pretty hard to reach during login at all (fast fingers needed). And even then it kinda makes sense even. I'd vote to close with `wontfix`

I agree. I knew that no normal user would find this. I wanted to atleast document it incase it allows for some janky interactions.
