### ISSUE TITLE
active search bar removes F1 functionality

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2553]
Next to "Emails", press the search icon, then cancel the confirmation. Pressing <kbd>F1</kbd> will not do anything anymore, despite it usually opening the keyboard shortcuts.
Further, F1 doesn't work at all when the search bar is active.

expected behavior: <kbd>F1</kbd> should still work!

**Comment by jowlo** [comment]
<kbd>F1</kbd> does not work at all while the search bar is active

**Comment by Pa7Hub** [comment]
Oh, that cant be intentional. I'll edit the issue to include that

**Comment by jowlo** [comment]
### Test notes:
 - [ ] Click on search icon and type in search bar
 - [ ] While still focused press F1
 - [ ] There you should have your help dialog
