### ISSUE TITLE
Error when uploading custom whitelabel ssl certificate

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2554]
Currently the client shows the possibility to upload custom certificates but this fails with an error because the server does not support it any more. We decided to

- [ ] Remove the upload possibility from the client (also adapt how-to!)
- [ ] Keep the server side implementation for checking RSA and elliptic curve certificates in case some bigger customer requests to use custom certificates in the future.
- [ ] Switch existing custom certificates to Letsencrypt
- [ ] Inform customers with custom certificates about it? Maybe check first how many this affects?

**Comment by armhub** [comment]
We have decided that we will disable custom whitelabel ssl certificates.

**Comment by mpfau** [comment]
test notes:
- [ ] it is not possible to upload a customer certificate anymore
- [ ] how does the switch work for existing customers?

**Comment by bedhub** [comment]
I created a issue on the server which handles the migration stuff. server issue 875

**Comment by mpfau** [comment]
extracted faq update to #3309
