### ISSUE TITLE
Sync external calendars as read-only

### ISSUE THREAD

**Issue by benhylau** [tutao/tutanota#2563]
I have a bunch of team calendars from [ Nextcloud, SOGo, Google Calendar ] that can supply a CalDAV / ics link. It would be nice if Tutanota's `Other Calendars` feature can actively sync these non-Tutanota calendars as read-only, so the Tutanota calendar clients can aggregate all of a user's calendars in one view.

I understand the reasoning behind not publishing the Tutanota CalDAV / ics feed, or wanting to bi-directionally sync with external calendars, but actively pulling (rather than one-time importing) an external feed as read-only seems pretty safe?

_Please close if this is not the place for feature requests. Thanks for the excellent product I am a happy new customer._

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
