### ISSUE TITLE
F-droid version outdated

### ISSUE THREAD

**Issue by duggalsu** [tutao/tutanota#2564]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

The fdroid version is v.3.78.2 whereas the github apk version is v.3.80.2. Is there something I am missing?

**Comment by charlag** [comment]
We will check it

**Comment by charlag** [comment]
Tag was missing, sorry, should be there soon
