### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [tutao/tutanota#2567]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by jowlo** [comment]
Thanks for the find!
From your Link:
> **For users who choose to share usage statistics and diagnostics with Google**, WebView sends usage statistics and crash reports to Google.

It is only active if you enable diagnostics for Google in your Android system. I think we should opt-out anyways.
