### ISSUE TITLE
Calendar import blocked

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2568]
We do some parallel requests to the server which result in blocks.

**Comment by jowlo** [comment]
I could not reproduce the issue, and also couldn't find any parallel requests in the code. There is one `Promise.map` in the `CalendarImporter` but it is for exporting and is working on local data only.

![Screenshot from 2021-01-05 10-24-26](https://user-images.githubusercontent.com/6842104/103629212-53f50580-4f40-11eb-8d0e-33774762a7fd.png)

Do we have reports from users getting blocked?

**Comment by armhub** [comment]
I noticed those places:
- Promise.map in CalendarFacade._createAlarms()
- No return statement for this._createAlarms() in CalendarFacade.createCalendarEvent()
- No return statement for this._sendAlarmNotifications() in CalendarFacade.createCalendarEvent()

The user report says importing a 185 KB .ics file in the Mac desktop client blocks the server connection halfway through the import.

**Comment by dionvl** [comment]
Hi, I followed the link to this issue which was sent to me when I reported this. I believe I am the user @armhub mentioned in the comment above. I found another report on reddit [(link)](https://redd.it/k7luae) which led me to reach out to the support team. 

It might have something to do with notifications, I have them turned on for my pretty much all my events (usually 1 hour before start). I tried to import again just now. When the server kicks me out I get spammed with these messages. Hope this helps.  

<img width="414" alt="Schermafbeelding 2021-01-05 om 11 06 47" src="https://user-images.githubusercontent.com/16754743/103634050-d7b1f080-4f46-11eb-9050-36f7cbd87cf1.png">

**Comment by jowlo** [comment]
@dionvl 
Thanks for having a look at this and providing more feedback!
I cannot reproduce this error, but we are doing parallel loads in two places. Both are related to loading alarms which would explain why you are encountering this issue and others are not.

@armhub 
I fixed the parallel map you mentioned (and another one). If i understand correctly, those missing `return` statements are implicit in the arrow functions.

**Comment by charlag** [comment]
It might also be related to counting of missed notification requests on the server, when a lot of alarms are created it will try to download a lot of them too

**Comment by armhub** [comment]
> @armhub
> I fixed the parallel map you mentioned (and another one). If i understand correctly, those missing `return` statements are implicit in the arrow functions.

You are right, I did not notice that.

**Comment by charlag** [comment]
We are still creating and receiving each alarm change one by one, even for the same event, we probably should improve on that later
