### ISSUE TITLE
Limit signature size

### ISSUE THREAD

**Issue by vaf-hub** [tutao/tutanota#2573]
We should have a limit on how large an email signature can be. At the very least we should show a warning if a large signature is configured.

It does not make sense to have large signatures, e.g. with embedded base64 images, but those should reference other sources.

**Comment by charlag** [comment]
Currently base64 images is the only way to embed images into signatures. I don't know if having external images is a good idea.

**Comment by vaf-hub** [comment]
OK, anyway I think we should have a reasonable size limit to prevent people from sending large images with every single email. Our Tutanota logo is a little over 7kb as b64 image for instance. What do you think?

**Comment by charlag** [comment]
is it 7kb for svg or png? seems quire a lot but I don't know what's the average size for image in signature.
Ideally we would do files instead but it would also be limited.

**Comment by vaf-hub** [comment]
after a discussion we decided to show a warning when setting up a large signature (>20kb?) but have no hard limit, because we already have a hard limit on the size of mails.

the warning should explain that it is not a good idea to send a large signature with every single email and fill the recipients' mailboxes

**Comment by vaf-hub** [comment]
decided to go with 15kb as soft signature size limit. because 20 really seems like a lot. we could go for 10 and see if we get a lot of complaints...
