### ISSUE TITLE
notification emails are only sent to external mail addresses

### ISSUE THREAD

**Issue by vaf-hub** [tutao/tutanota#2577]
Currently, it is possible to configure an mail address for notification emails under settings/email.
If this is an external mail address notifications work properly. However, if it is a Tutanota mail address notifications will not be delivered because we only allow sending mails to external addresses (via SMTP) on the server and thus the notification delivery will fail.

We should either support sending notifications to other Tutanota mailboxes or check in the client during setup and show an error if the configured notification mail address is a Tutanota address.

**Comment by vitoreiji** [comment]
Notifications are sent but they get delivered to spam.

**Comment by vaf-hub** [comment]
> Notifications are sent but they get delivered to spam.

have you checked that the production system behaves the same as the local setup for spam detection in this case?

**Comment by vitoreiji** [comment]
> > Notifications are sent but they get delivered to spam.
> 
> have you checked that the production system behaves the same as the local setup for spam detection in this case?

Yes :-)

**Comment by vaf-hub** [comment]
then we should definitely do something about it...

**Comment by vaf-hub** [comment]
The root cause is that we always send the notification mail as an SMTP message. We should treat the notification mail as an internal notification mail if we the recipient is a tutanota address.

**Comment by vaf-hub** [comment]
Today I was not able to reproduce the issue in the current production environment. Did we have a change of policies for outgoing and incoming SMTP messages in the last month?

Anyway, I still think we should send notifications as internal mails. Therefore I close this issue ion favor of the newly created server issue 781.
