### ISSUE TITLE
Getting error from renaming mail group after deactivation of mail group "bad request"

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#258]
If the page is refreshed after deactivation renaming does not produce an error

**Comment by asteintutao** [comment]
Same happens when trying to rename a deactivated user

**Comment by asteintutao** [comment]
Or after trying to add a deactivated user to a mail group

**Comment by bedhub** [comment]
Rename fixed, for adding a deactivated user to mailgroup see #272
