### ISSUE TITLE
Safari doesn't support U2F, client shouldnt try to do U2F setup or authentication

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2581]
A user reported being unable to 2FA with their yubikey on both safari and on the mac desktop client.

I can confirm that I can neither setup nor login with 2FA on safari using my nitrokey. I haven't checked on the desktop client. The dialog just waits and doesn't respond to the key

**Comment by charlag** [comment]
Duplicate of #2140 
Safari does not support U2F and neither does desktop client, desktop shows the message that you can't use the key

**Comment by johnbotris** [comment]
U2fClient.isSupported should return false in safari then, it's currently returning  true

**Comment by charlag** [comment]
It should!

**Comment by johnbotris** [comment]
# Testing
- [ ] The user isn't given an option to set u2f in safari or apps
- [ ] The user isn't gived an option to login with u2f in safari or apps
- [ ] u2f is presented as available to use in other cases
