### ISSUE TITLE
Calendar reminders are received for the old time

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2585]
> have a bug with calendar. I get reminder notifications for events at their old time. 
> 
> Steps to reproduce:
> 1. Create reoccurring event with reminder
> 2. Change event time
> 3. Receive reminder notifications for the event at its old time. E.g. reminder an hour before for event at 9 but event is actually now at 10. 

3.80.2

**Comment by bedhub** [comment]
Is this behaviour reproduceable? I received a similar report today which might be related. The user created a reoccurring event with reminder and then delete the event. He still receives the notifications for the deleted event. Similar case as changing event time also leads to delete operation.

**Comment by vaf-hub** [comment]
I just spent some time trying to reproduce this and do not seem to be able to on both Android and Desktop client.
Also, I debugged the server and client code and to me it seems that the old push notification is properly deleted and a new one is then created (in case the time is changed, in case of deletion it is just deleted).

So maybe this only occurs for some repetitions of an event but not all of them or there are some other things to consider.

I tested with current master locally and on production with 3.82.17 (Linux Desktop) and 3.82.7 (Android).

**Comment by bedhub** [comment]
We still receive reports about old reminders. This is a little bit different as the event has been removed but maybe it is related.
https://github.com/tutao/tutanota/issues/2523

**Comment by charlag** [comment]
I checked the code for Android and:
1. We do not re-insert alarms on every reschedule
2. When we do, we replace them:
```java
@Dao
public interface AlarmInfoDao {
	@Insert(onConflict = REPLACE)
	void insertAlarmNotification(AlarmNotification alarmNotification);
        // ...
}
```

and

```java
@Entity(primaryKeys = "identifier")
@TypeConverters(AlarmNotification.OperationTypeConverter.class)
public class AlarmNotification {
	private OperationType operation;
	private String summary;
	private String eventStart;
	private String eventEnd;
	@Embedded
	@NonNull
	private AlarmInfo alarmInfo;
	@Embedded
	private RepeatRule repeatRule;
	@Embedded(prefix = "key")
	private NotificationSessionKey notificationSessionKey;
	private String user;
        // ...
}
```

Closing until we get more info as it's not actionable now

**Comment by ekaats** [comment]
I have a similar kind of issue. Created recurring appointments with a reminder. After changing the date/time of the reminders, and later removing the entire set, the notifications still pop up.

Not sure how to reproduce, but the original post sounds about right.
