### ISSUE TITLE
Drafts cannot be updated

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2594]
Each time you edit and save a draft a new one is created using a POST request. We should use UPDATE instead.

**Comment by jowlo** [comment]
Probably related to #2547

**Comment by jowlo** [comment]
This was a bad one. A closing parentheses moved during review changes.

https://github.com/tutao/tutanota/pull/2547/commits/1960fd5c1df0eac81cf62b842ad58915b3a9bfae#diff-b5c564e15f9615bb6c811791e3ca5f158604f9364f0eb30028f565025f7c7331R794

vs

https://github.com/tutao/tutanota/pull/2547/commits/a4cc4993aa68740134d877dce676983328959eb2#diff-b5c564e15f9615bb6c811791e3ca5f158604f9364f0eb30028f565025f7c7331R792
