### ISSUE TITLE
Improve client side validation of credit card information

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2602]
Our current implementation doesn't do particularly thorough validation of credit card information. We should do proper validation so that we aren't sending garbage data off to be verified, also to give the user better feedback when inputting their information.

**Comment by kunalnagar** [comment]
Is this open to contributions?

**Comment by charlag** [comment]
@kunalnagar you could try to do some basic validation and feedback!

**Comment by johnbotris** [comment]
ah I had already begun working on this

**Comment by kunalnagar** [comment]
@johnbotris - no worries, do you have any recommendations for good first issues to pick up when familiarizing with the repo?

**Comment by johnbotris** [comment]
@kunalnagar apologies for the delayed response - anything labeled "good first issue" would be a good place to start, if there are any. Otherwise I don't have any particular suggestions, there are various UI bugs and oddities.

**Comment by johnbotris** [comment]
# testing
- [ ] valid credit card numbers are sent off to the server for processing
- [ ] invalid ones are rejected before a request can be made
