### ISSUE TITLE
Sharing links from Android doesn't work

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2605]
User(s) on [reddit](https://www.reddit.com/r/tutanota/comments/kumtdl/sharing_link_does_not_work/) report that sharing links doesn't work / works only sometimes on Android.

**Comment by jace4411** [comment]
> User(s) on [reddit](https://www.reddit.com/r/tutanota/comments/kumtdl/sharing_link_does_not_work/) report that sharing links doesn't work / works only sometimes on Android.

**Comment by Pa7Hub** [comment]
duplicate #2597

**Comment by Pa7Hub** [comment]
duplicate of #2597

**Comment by Pa7Hub** [comment]
Duplicate of #2597
