### ISSUE TITLE
Emails with white background on dark theme

### ISSUE THREAD

**Issue by RickyM7** [tutao/tutanota#2610]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Basically all received emails (or at least 99% of them) have a white background, even with the app in the dark theme. This has been happening for a long time and I thought that PR #2434 would finally solve this, but this did not happen.

**Screenshots**
![white-background](https://user-images.githubusercontent.com/24703825/104307619-37138180-54ae-11eb-8ca3-44eb6b51e417.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4
 - OS: MIUI 11 (Android 7.0)
 - App version: v3.80.4

**Comment by jowlo** [comment]
To keep your mails readable we set a white background on all e-mails that either set CSS `color` directly or via a `font` attribute.
If you scroll down you will see light grey text on that mail from github.

I think we have only very few options here if we want to a) keep all mails readable and b) enable dark mode for more mails.

Would you rather have a "force dark" mode where we strip all custom color formatting from the mail, or a "ignore low contrast checks" setting so we do not even check for color tags and just display on a black background? Do you have another approach in mind?

**Comment by RickyM7** [comment]
@jowlo As it stands now (white background, black texts), an option that literally reversed colors would not make everything legible and still have the black background? Would it be possible to have an option to invert the colors of the emails in the appearance options?

**Comment by charlag** [comment]
There's no general solution to that, we cannot infer what combination of colots/backgrounds exists in resulting email and our #1 priority is readable emails. Other email clients just always use white background, we do our best effort.
All "plaintext-ish" emails will have dark background, anything "webpage-like" will have forced white background, there's no way around that.

**Comment by RickyM7** [comment]
@charlag No problem! I agree that it is more important to have readable emails, but at another time please try to add an option to force dark mode or to invert the colors of emails. But if it's not possible to add that, it's really not a problem.
