### ISSUE TITLE
Pull out Archive button

### ISSUE THREAD

**Issue by nkuba** [tutao/tutanota#2621]
Currently in the desktop client to archive a message you have to go into the dropdown menu: `Move -> Archive`:
<img width="302" alt="Screenshot 2021-01-15 at 00 55 01" src="https://user-images.githubusercontent.com/10741774/104663062-19b80080-56c4-11eb-9d05-ca60f66c0170.png">

 It would be handy to have the `Archive` button pulled out next to the `Delete` button, as it's available in many clients (e.g. Gmail, macOS Mail app):
![Screenshot 2021-01-15 at 01 05 08](https://user-images.githubusercontent.com/10741774/104663820-bb8c1d00-56c5-11eb-98ca-f3ff24aca14d.png)

**Comment by johnbotris** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
