### ISSUE TITLE
Duplicate trash button in Email view

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2622]
We have two buttons for moving E-Mails to trash when viewing an E-Mail.

![Screenshot from 2021-01-15 13-16-24](https://user-images.githubusercontent.com/70587561/104726582-24aa7980-5734-11eb-82a1-990ddb62e537.png)

**Comment by charlag** [comment]
That's by design?

**Comment by Pa7Hub** [comment]
Yeah, makes sense. But... Both move them to the trash folder.. If we already have the Trash button directly there, why do we have it a second time?
