### ISSUE TITLE
[Feature Request] Email text formating - switch between html, rich and plain text

### ISSUE THREAD

**Issue by invalid-error** [tutao/tutanota#2623]
Very often when doing copy/paste operations you paste the source format which is sometimes a pain with tutanota.

It would be nice to have:

- a "how to paste" option: **with** or **without format** or
- a way to switch the whole email body **from html to rich or plain text**.
- 
![tutanota-formating](https://user-images.githubusercontent.com/55282571/104808913-8a0c7200-57e9-11eb-8b12-d98c68c06cf8.png)

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
