### ISSUE TITLE
Common mail shortcuts not available on MacOS

### ISSUE THREAD

**Issue by ark-** [tutao/tutanota#2624]
**Describe the bug**
On MacOS there are a group of very commonly used shortcuts which are missing from the desktop experience. 

#1644 fixes common editing shortcuts such as control, paste, close window etc.

**To Reproduce**

1. Open Tutanota app
2. Press keybinding 

The following shortcuts are missing (that I can think of from the top of my head)

Reply
Reply to All
Forward
Open Search Dialog
Delete
Move to Archive
Mark as Read / Unread
Compose New Email

**Expected behavior**
Shortcuts to work

**Desktop**

 - OS: MacOS
 - CPU: Apple M1 (So assume this is running under Rosetta translation layer)
 - Version: 3.80.4.1186

**Comment by charlag** [comment]
Hi
We have shortcuts for that, you can see them by pressing help icon when email is selected or by pressing F1.

**Comment by ark-** [comment]
Oh damn! Sorry. I tried looking in the menu bar and seeing the little shortcuts to the right.

<img width="244" alt="Screenshot 2021-01-18 at 08 29 46" src="https://user-images.githubusercontent.com/6353339/104890421-725af800-5967-11eb-9945-12a04b516cb5.png">

**Comment by charlag** [comment]
No problem, would be great to have shortcuts there as well but it doesn't work like that yet

**Comment by ark-** [comment]
Thanks for your help. 👍
