### ISSUE TITLE
Please publish your DB schema.

### ISSUE THREAD

**Issue by cnighswonger** [tutao/tutanota#2628]
The Tutanota mail server code is obviously not open-sourced. This is a great handicap in potential 3rd party development. Please at least publish the DB schema. This would potentially allow for development of an off-line feature on the client side.

**Comment by charlag** [comment]
Please don't post requests here.
Model is in the source, look in src/api/entities

**Comment by cnighswonger** [comment]
Apologies. The Reddit channel looks dead, especially for dev purposes. Tutanota sales indicated there were no other avenues of development discussion. IRC, mailinglist, etc. would be nice for those who are interested in contributing. Tnx.

**Comment by charlag** [comment]
Hi
If you are interested in contributions, this is probably the right place but when it comes to third-party apps we are not in capacity to moderate that. We will see how it will change though.
