### ISSUE TITLE
Refactor expander panels

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2632]
There is a lot of duplicate code and old components, would be a good thing to do to make further changes easier

**Comment by johnbotris** [comment]
# testing

make sure the expanders are still working properly (opening/closing is correct, child components are working)
- [ ] mail folders expanders, contacts expander
- [ ] settings expanders
- [ ] mail editor "show more" expander
- [ ] calendar event editor "add guest" expander

**Comment by sarashub** [comment]
- [x] mail folders expanders, contacts expander
- [x] settings expanders
- [x] mail editor "show more" expander
- [x] calendar event editor "add guest" expander
