### ISSUE TITLE
Technical improvements

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2635]
Post-Rollup cleanup:

- ~~Ship models and translations not as JS but maybe as JSON. It's faster to build and faster to run~~ #3164
- Make sure we don't use models in main thread to avoid processing them twice? -- later
  - We use models for create() so unless we make it async it's going to be complicated
  - Tracked at #3164 , can actually be achievable
- ~~Optimize chunks manually a little bit so that we run only the required code at any moment (e.g. don't pull calendar/settings into mail chunk)~~ done with #2671 
  - use coverage inspector from Chrome and [bundle-wizard](https://github.com/aholachek/bundle-wizard)
- ~~Use dynamic imports in worker to load it faster. This is one of the main slowdowns on login as worker is a big chunk and we probably don't need all the indexer things to log in.~~ #3165
  - ~~Tricky for debug as ESM is not supported in workeks widely~~
- ~~Use hashes to avoid re-downloading some of the chunks on update from service worker -> later~~ #4212
- ~~Drop old browsers and use modern JS, at least with classes and arrow functions~~
  - Tracked at #2695
- ~~Drop bluebird and use await. Find replacement for Promise.map~~
  -  tracked at #2725
- Consider using numeric identifiers for translation keys as they take up quite some space in the bundle (less when gzipped) -> later
- Load order processing agreement texts async -> it is already in settings bundle so we can do it later.
- ~~If we keep autolinker, load it async~~ done with #2671

**Comment by johnbotris** [comment]
replacement for Promise.map is `Promise.all(arr.map(doStuffAsync))`, no?

**Comment by charlag** [comment]
Promise.map gives you controllable concurrency level, like "execute up to 2 promises in parallel".
We rarely need it (and in fact in many places we just do `{concurrency: 1}` now) but sometimes we do, like in the SearchFacade.

**Comment by charlag** [comment]
I've tried to complie to esm and I've run into issues with worker. We need to import common modules in a worker but for that we need to execute it as a module. We can only do it in modern Chrome.
Another option would be to inline whole common into worker but currently it's huge (467KB, 421KB of which is entities). If we would at least kept entities only to worker, it would be fine but as they are in both, we can't easy duplicate it.

The easiest option is to stick to systemjs, at least until esm is well supported in worker.
