### ISSUE TITLE
Desktop client breaks on unicode path

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2641]
![desktop-win-404](https://user-images.githubusercontent.com/8296817/105321186-6f5e4280-5bc7-11eb-8623-c789c4692a69.png)

This error is shown on windows desktop installation when the windows username contains umlaut characters. Could be reproduced when creating a test user Börnd on a virtual machine.

**Comment by QEDeD** [comment]
I'm also getting this error on a Windows 10 machine:
![image](https://user-images.githubusercontent.com/16562457/106451327-b16c6b80-6486-11eb-992b-0c50fa4f726b.png)

The user name of the Windows user does contain an "ø".

**Comment by charlag** [comment]
I looked at this a lot and I can't find the cause yet. I replaced all loadURL with loadFile but this didn't help yet. Blank project with loadUrl works tho.

**Comment by charlag** [comment]
That's an oddity in Mithril
https://github.com/MithrilJS/mithril.js/issues/2659
