### ISSUE TITLE
Tab Issue from Email Address input in Compose View

### ISSUE THREAD

**Issue by who8mypnuts** [tutao/tutanota#2644]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Similar to this which was fixed in a previous release: https://github.com/tutao/tutanota/issues/2394

**To Reproduce**
1. In compose new mail: type an email address
2. hit `tab`
3. focus is lost! can't proceed via keyboard and must click with mouse

**Expected behavior**
Hit tab after completing email addresses, goes to subject, then to body.

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - Desktop Environment, if applicable (on Linux): KDE
 - Version: 3.80.5

**Comment by charlag** [comment]
- [ ] Test on Safari
 - [ ] Test with at least one screen reader that it reacts to changed dom

**Comment by charlag** [comment]
Tested with Windows Narrator, expanders are fine
