### ISSUE TITLE
Cannot open broken invites

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2649]
Users report this for accepted invites regularly, seems like mail address of one of the recipients is invalid. We should handle it.

```
Tutanota version: 3.80.4
TypeError
Error message: Cannot read property 'endsWith' of undefined
Stacktrace:
TypeError: Cannot read property 'endsWith' of undefined
at file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/common.js:1:12959
at file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:2013187
at SendMailModel.value (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:1329433)
at SendMailModel.value (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:1328987)
at file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:863447
at Array.forEach ()
at CalendarEventViewModel.value (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:863285)
at new CalendarEventViewModel (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:859975)
at file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/main.js:1:853688
at new CalendarEventPopup (file:///Applications/Tutanota%2
```

> I received an event update by email that I accepted. Since then, I cannot view the event in question in my calendar anymore. Each time I try, I get the error message which led me to send you this report.

> Cannot open this agenda item

> when accepting a google calendar event and opening the event to edit, the error started to appear and now I can't edit it nor delete it.

> Vom Absender gelöschte Termine verschwinden nicht vom Kalender.

> I am simply clicking on an accepted event on my calendar but I cannot access the event or make any changes. The orignal sender is on Google. THis same error occurs on both Linux and Windows desktop apps and the iOS app.

> Hello, some items in my calendar all of a sudden cannot be open, it notifies me of an error. It´s very uncomfortable as I have links to meetings in some of those items. Thank you. And pls consider making a bigger place for this message, not only one line.

**Comment by vaf-hub** [comment]
@bedhub and spent some time investigating the issue and found that this might happen if the property `address` of `EncryptedMailAddress` cannot be decrypted. We decided to check for the CryptoError and indicate the error to the user in the event popup and event editor. We should probably also log the CryptoError.

**Comment by vaf-hub** [comment]
### Test notes:
The actual issue is not testable.

- [ ] Regression test for `CalendarEventPopup`: attendees are displayed correctly.
- [ ] Regression test for `CalendarEventEditDialog`: guests are displayed correctly
