### ISSUE TITLE
Activating email aliases of deactivated user is possible

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2654]

**Comment by johnbotris** [comment]
@armhub could you please elaborate?

**Comment by charlag** [comment]
@armhub do you know how to reproduce this?

**Comment by vaf-hub** [comment]
Reproduce:

1. Select a user in user settings.
2. Deactivate it.
3. Add an alias (also in user settings).

See that it works without the server-side changes. With the updated server we should receive a PreconditionFailedError.

**Comment by vaf-hub** [comment]
I (successfully) tested it for a regular user. Do we need to test it for shared mailboxes too?

**Comment by vaf-hub** [comment]
> I (successfully) tested it for a regular user. Do we need to test it for shared mailboxes too?

As I don't think it is possible to add aliases to a shared mailbox group from the ui, I add the `tested` label.
