### ISSUE TITLE
Improvement: Add Time Zone selector when creating events in Calendar

### ISSUE THREAD

**Issue by wesaka** [tutao/tutanota#2655]
I feel that it would be useful to have a manual way of selecting a time zone when adding an event to the calendar, as especially nowadays when we are working/studying remotely, one can have multiple events in multiple time zones, also keeping in mind "automatic" changes such as daylight savings in areas that employ them.

This is the main issue at the moment as to why I haven't migrated all my planning to Tutanota's calendar.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
