### ISSUE TITLE
Left side folders don’t load at login

### ISSUE THREAD

**Issue by nadesco** [tutao/tutanota#2658]
Since updating to the Mac desktop client I’ve noticed that the left sidebar doesn’t always load the folders immediately after logging in as it did in previous versions. The small pyramid to the right of the email address points upward (as it should), so I need to click it twice for the folders to display. I tried uninstalling/reinstalling the app and associated files but it didn’t help. Not sure if it’s a bug or just slow to load, but the folders do eventually show after about a minute (when the red line goes across the top, I think). It’s intermittent and happens around 50% of the time.
 OS X 10.14.6
Tutanota ver 3.80.5

Screenshot here. (I got an error message when trying to directly upload the file to github.)
https://tinyurl.com/y683gvpb

**Comment by vitoreiji** [comment]
I also see the on the webclient.

**Comment by charlag** [comment]
Looks like rate limiting to me but not 100% sure yet

**Comment by thinkpad4** [comment]
I'm seeing this too on the web client

**Comment by charlag** [comment]
I just had this once, I think it's something with expander, expanding/collapsing it a few times seemes to help?

**Comment by ThatLifeofGames** [comment]
I have this almost every time I load Tutanota in the web client (Firefox 85.0), I see no issues in console, happy to do some testing. It seems to have only started to happen after v3.80.5.

**Comment by charlag** [comment]
Another release is almost out, let's see if it's fixed

**Comment by charlag** [comment]
can someone confirm it's not happening anymore?

**Comment by nadesco** [comment]
It seems to be fixed on the desktop client. I haven't had any probs for about a week now. Thanks a lot for getting it sorted.

**Comment by ThatLifeofGames** [comment]
Haven't had it happen since the last update on the web client, seems it is fixed.

**Comment by charlag** [comment]
Thanks for reporting back
