### ISSUE TITLE
Link FAQ entry in VAT id number info

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2660]
We have the case that customers have a VAT id number, but it is not valid for cross border transactions within the EU. In this case they can not use it in Tutanota, have to leave the field empty and will have to pay the VAT. From the info text we should link to an FAQ entry explaining this. We can also include the VAT ID number check website in the FAQ (https://ec.europa.eu/taxation_customs/vies/).

**Comment by hahub** [comment]
Here is the FAQ Link: https://tutanota.com/faq/#vat

**Comment by vaf-hub** [comment]
Does this FAQ entry actually exist? The link is broken and I cannot find an FAQ entry on the website for this!?

**Comment by vaf-hub** [comment]
Talked to @hahub who told me that that the VAT id is no longer required in this case. Therefore the FAQ entry does not longer exist and this will be closed.
