### ISSUE TITLE
Auto capitalization of login inputs on android firefox

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2664]
Firefox on android auto capitalizes the first letters of the email and password field. It's not happening in Chrome. Tested with the AOSP Keyboard and Openboard

**Comment by jowlo** [comment]
Maybe we should try [`autocapitalize`](https://developer.mozilla.org/de/docs/Web/HTML/Globale_Attribute/autocapitalize)

**Comment by charlag** [comment]
I think it's a FIrefox problem that they capitalize fields with type=email

**Comment by johnbotris** [comment]
it's happening in the password field aswell

**Comment by charlag** [comment]
s/type=email/type=password

**Comment by yopfox** [comment]
Cannot be reproduced anymore and neither field is auto-capitalized on Firefox Android.
Furthermore, support for `autocapitalize=none` was [added](https://bugzilla.mozilla.org/show_bug.cgi?id=1425291) for FF on Android.
