### ISSUE TITLE
It's possible to open up the calendar event editor even with no calendars

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2665]
1. Delete all your calendars
2. Open editor for a new event
3. Click save
4. Get an unhandled error

It should either a) Not be possible to open up the editor when there are no calendars or b) Automatically create a new default calendar if no calendars exist (I would prefer option b)

**Comment by charlag** [comment]
Calendar is already auto-created but only when you open it (for the first time?) so we might need to do this in more places

**Comment by johnbotris** [comment]
Oh yep, a new one will be created upon re-logging in.

**Comment by johnbotris** [comment]
# testing
- go to the calendar view
- delete all existing calendars
- create a new event
- [ ] a new calendar has been created automatically, and the event will be linked to this calendar
