### ISSUE TITLE
DOMPurify 2.2.6

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2666]
No new vulnerabilities but new mXSS logic

**Comment by charlag** [comment]
## Test notes

- [ ]  Editor still works
- [ ] Calendar still works

**Comment by vaf-hub** [comment]
Both editor and calendar seem to work. I played around with both. Or is there anything specific I should test?

**Comment by charlag** [comment]
Nothing specific, regression testing. You can try to paste some disallowed HTML into editor and see that it's still sanitized away

**Comment by barbiehunter** [comment]
Is this now updated to 2.2.6 or 2.2.7? just as question and if its changed to 2.2.7 change the name of this issue.

**Comment by charlag** [comment]
2.2.7, yes, thanks for poiting out
