### ISSUE TITLE
Business feature

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2668]
There should be a new business feature which enables certain business related functionality.  In the first version it will include

- Out of office notification
- Calendar event invites
- Multiple domains

The business feature should increase the per user price by 12€ per year and will be included in all subscription plans for business customers.

**Comment by vaf-hub** [comment]
Test notes:
- [ ] adding more than 1 custom domain is only possible if business feature is booked
- [ ] business feature is booked a) if business usage is selected during signup, b) if usage is changed to business in SubscriptionViewer, c) if customer with business usage, that does not have the business feature, switches the subscription type
- [ ] all prices shown in SwitchSubscriptionDialog are correct, the correct features are booked (no currently booked features must be canceled for upgrades!), the features displayed for the subscription plan are the ones actually booked
- [ ] invoices are correct for all plans and additionally booked features

**Comment by armhub** [comment]
Findings after test

- business feature order info is only shown after configuring the out-of-office notification 
- business feature order info is only shown after setting up DNS entry for a second domain
- after disabling the business feature as a private customer the out of office notification stays enabled and is still sent

**Comment by vaf-hub** [comment]
> Findings after test
> 
>     * business feature order info is only shown after configuring the out-of-office notification
> 
>     * business feature order info is only shown after setting up DNS entry for a second domain

WIth @bedhub  and @armhub we decided not to change this for now, but to discuss it in the UI team and find a general solution that can also be applied to other cases/features.

**Comment by armhub** [comment]
BadRequestError fixed in 7dd6bdc3
Active out of office notifications after canceling business feature is fixed on server side
