### ISSUE TITLE
After removing a user from a mail group and deactivating mail search in settings an error occurs

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#267]
Reproduction:
1. Add yourself to a mail group
2. Get a working search index (can find mails in mail group inbox too)
3. Remove yourself from mail group
4. Go to settings deactivate mail search 
-> Error occurs

**Comment by armhub** [comment]
no error, but after activating mail search again it is possible to find emails from the mail group still in cache

**Comment by armhub** [comment]
Last issue will be handled in #274
