### ISSUE TITLE
Calendar: allow for "istantaneous" events

### ISSUE THREAD

**Issue by ftrotta** [tutao/tutanota#2673]
As a user of the desktop/mobile app, I would like to add events whose end date equals the start date, as to allow for memo events.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
