### ISSUE TITLE
Calendar: allow for colored events

### ISSUE THREAD

**Issue by ftrotta** [tutao/tutanota#2674]
As a user of the mobile/desktop app, I would like to assign a color to each event, as to easily distinguish them visually.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
