### ISSUE TITLE
Confirming event invitations in an email takes too long

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2677]
If you press the confirm button it takes multiple seconds until you see the message that you have accepted the invitation. There is no indicator that this is still processing, so you are likely to press again. We should introduce a progress dialog or similar.

**Comment by gaganvats-05** [comment]
Hi, I would like to work on this issue, can you suggest me ways to get started?

**Comment by charlag** [comment]
You can find the place where invite is accepted (somewhere in MailViewer) and introduce progressDialog there

**Comment by charlag** [comment]
## Test notes

- [ ] Open email with calendar invite, respond to invite, check progress dialog
