### ISSUE TITLE
This is not a spam quick button is needed!

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2679]
all important emails and contracts from insurances companies CIGNA and others
are going to spam
very bad

please add THIS IS NOT A SPAM quick button!

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
