### ISSUE TITLE
add offline indexes search db

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2681]
every time when i try to search, i have to reindex entire mailbox, takes ages
please add offline local db sync even if it take 10 GB or whatever the size of my paid mailbox

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

duplicate of #590
