### ISSUE TITLE
Search bar can be activated without accepting dialog

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#2689]
Steps to reproduce: (May take a few tries)

1. Click search Icon (=> This will open the dialog/popup)
2. Cancel out of the Dialog
3. Now press any keys on the keyboard (quickly)
4. The Popup will open, but so will the search bar

This allows you to "bypass" the dialog, you can also access the search view by doing this. 

![Screenshot_18](https://user-images.githubusercontent.com/70587561/107363325-43552380-6ada-11eb-8391-cfaf2031ac97.png)

## Test Notes
- With the search disabled:
   - [ ] When user clicks on the search bar, a dialog is shown asking to enable the search index
   - [ ] The dialog blocks the interaction with the page
   - [ ] After clicking on cancel, if the user type something, no matter how fast, a new dialog is displayed and no search bar overlay is displayed

- With the search enabled:
   - [ ] The user is able to search

**Comment by charlag** [comment]
It's possible to type in the field but I think that's fine
