### ISSUE TITLE
Inline picture not shown as attachment when editing draft after saving once

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2692]
**To Reproduce**
1. Compose new message with an inline image
2. Verify that the image is shown in the list of attachments
3. Save as draft
4. Edit draft
5. Verify that the image is no longer shown in the list of attachments

**Expected behavior**
Either never show the image in the list of attachments or always show it.

**Screenshots**
When first adding the image:
![image](https://user-images.githubusercontent.com/197261/107517602-3c97e080-6bae-11eb-8df7-4a5b781dc2a1.png)
When editing the draft:
![image](https://user-images.githubusercontent.com/197261/107517768-7537ba00-6bae-11eb-91e1-f4ab463eaafa.png)

**Additional information**
Related to #1734

**Comment by charlag** [comment]
We can discuss it again but it's not a bug, it's by design so that you can remove them while editing

**Comment by vitoreiji** [comment]
> We can discuss it again but it's not a bug, it's by design so that you can remove them while editing

Then it should be shown also when editing the draft, no? My issue with this is that it is different between first adding and editing afterwards.

**Comment by charlag** [comment]
ah, sorry, I misunderstood. It's a bug then, yes
