### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2695]
We will change our browser support polity to be the following:

- Chrome desktop (any Blink-based, including Android WebView, Opera and new Edge): two latest releases
- Firefox desktop: two latests releases + ESR
- Safari desktop: two latest releases
- iOS: three latest major releases

We already list those as supported browser but now we define which versions are supported and dropping IE.

With this we can drop all polyfills we currently use. We still need systemjs for module loading on the worker side.

**Comment by bedhub** [comment]
We have to increase the minimum version number for iOS at least because i think this will drop support for iOS 10. This change should be visible in the app store and users should not download a not supported version by accident. 

Will we drop support for Android 5 as well with this issue?

**Comment by charlag** [comment]
We should drop Android 5 and modify iOS, as well, yes, it's related

**Comment by bedhub** [comment]
We should try to detect es6 support feature based instead. We should use all features that are required to run the application inside the ClientDetector and then use the ClientDetector inside app.js. In case importing app.js throws an error we should show the NotSupported page. Use same handling for dev and prod builds.

**Comment by charlag** [comment]
async functions do not use bluebird promises and sometimes we learn about it very late

**Comment by johnbotris** [comment]
- [ ] Error described in issue #3039  is not occurring
