### ISSUE TITLE
Enable compression of mail bodies when saving/sending emails

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2697]
Up to now we just had enabled reading compressed mail bodies (see #481).

[server issue](https://next.tutao.de/gitlab/tuta/tutadb/-/issues/716)

**Comment by armhub** [comment]
See server side issue #861

**Comment by johnbotris** [comment]
# Testing notes

All mail bodies are now compressed on the client side. We need to make sure that compression is used and decompression is successful in all cases:

- [ ] Send to an internal recipient
- [ ] Receive from an internal sender
- [ ] Send to an external recipient
- [ ] Receive from an external recipient
- [ ] Save then edit then send a draft
- [ ] Not possible to send with very large mailbodies (>= 1 MB)
- [ ] Regression test encrypt+map for all entity attribute types (string, bytes, etc)
