### ISSUE TITLE
Indicate longer description in event preview if it was cut off

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2698]
On mobile only a part of the event description is shown when you click on an event. It is not visible that there is some more hidden description, so you are likely to miss it. Only if you edit the event you see the full description. We should indicate that the description is actually longer.

**Comment by charlag** [comment]
Description is actually scrollable, we could use overflow stile which shows the scrollbar but it might be ugly when there's nothing to scroll

**Comment by armhub** [comment]
Ok, I see. We can try the scrollbar.

**Comment by johnbotris** [comment]
# testing
- [ ] if a description for an event is too large to fit in the event popup, then it will be scrollable, vertically or horizontally

**Comment by charlag** [comment]
Scrollbar shown on Android but it doesn't hurt
