### ISSUE TITLE
Automate android build

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2703]
The android build needs more automation and we should add a jenkins task for it. 
- Build android client on build server
- Run test cases automatically
- Tag source code after successful build
- Upload release to play store (prod release)
- Upload release to GitHub releases page (prod release)
- Update release to Nexus (test and prod release)
- App store/F-Droid release notes: link to https://github.com/tutao/tutanota/releases ("app-android/app/src/main/play/release-notes")
- Create release from Jenkins, collect release notes from the milestone based on the app version number.

see 24a2cf4a

**Comment by bedhub** [comment]
After discussion with @johnbotris @rosso-ptg @charlag @bedhub there seems to be no good way to publish releases notes to different locations automatically, e.g. length restriction on PlayStore. We said that GitHub should be source of truth for the release notes and we will link from the app store descriptions to https://github.com/tutao/tutanota/releases.

Release creation should be triggered from the android build task.
