### ISSUE TITLE
Contact view not usable after opening contact with invalid birthday

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2708]
Import the attached contact and then observe what happens to the contact viewer and folder section. Contact is not displayed and cannot be deleted.
![contact-view](https://user-images.githubusercontent.com/8296817/107780450-f88c1380-6d46-11eb-85ce-0542e5c0eebb.png)

[contact-invlaid-birthday.txt](https://github.com/tutao/tutanota/files/5972362/contact-invlaid-birthday.txt)

**Comment by jowlo** [comment]
## Test notes

The fix changes import behaviour (not allowing invalid birthdays) and display behaviour (not breaking everything) if you have such contact. Rename the attached file to `.vcf` to import.

Ensure that:
 * UI does not break if there is a contact with an invalid birthday already in the database that was imported before this change.
 * UI does not break if you import fresh.
