### ISSUE TITLE
Cannot go back after opening mailto link

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2723]
web browser
load webpage
click on mailto: 
pop ups tuta page with no email address injected
cannot press back button to return to original page

**Comment by europound** [comment]
https://lithuania.mid.ru/vizovye-voprosy

**Comment by europound** [comment]
<a href="mailto:&quot;lithuania@mid.ru&quot;">lithuania@mid.ru</a>

**Comment by europound** [comment]
`<a href="mailto:&quot;lithuania@mid.ru&quot;">lithuania@mid.ru</a>`

**Comment by europound** [comment]
hmmm looks like a bad coding on their part?

**Comment by europound** [comment]
but still why can't i use back button? tuta web blocks history back -1

**Comment by johnbotris** [comment]
seems to only be happening in dist builds:
* After being taken to mail.tutanota.com, no mail editor is shown, only the mailview
* click back and then the mail editor pops up - close the mail editor - repeat

 In local builds it works more or less as expected, however it requires about 4 clicks of back to actually be taken to the original page.

**Comment by charlag** [comment]
I don't think we should fix this. You can hold back button to jump across redirects. We have to redirect to replace things.
