### ISSUE TITLE
Remove bluebird dependency

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2725]
With our new supported browser policy we can now remove bluebird as a dependency. We already removed it from the native desktop client part and we should change the flow typing.

---

Test notes:
 - [ ] Check that the app generally works on all supported browsers (we removed async-to-generator translation)
 - [ ] Check that signup still works
 - [ ] Check that creating a session works (password login)
 - [ ] Check that external login still works
 - [ ] Check that download all in desktop works
 - [ ] Check that download all with duplicate filenames works in desktop and names are changed
 - [ ] Check that search index generally works
 - [ ] Check that search works on iOS
 - [ ] Check that updating event does not show error if the event is already deleted
 - [ ] Check that while creating event alarms are loaded one by one
 - [ ] Check that calendar event invites generally still work
 - [ ] Check that attaching and uploading files works and is done one by one
 - [ ] Check that loading missed events after reconnect works
 - [ ] Adding/removing calendars works
 - [ ] Contact viewing still works
 - [ ] Async dropdowns
 - [ ] Showing progreess in list (initially and later)
 - [ ] Swipe actions in the list
 - [ ] Date picker
 - [ ] Contact form requests
 - [ ] Recover login error handling (like wrong password)
 - [ ] Takeover error handling (like wrong password)
 - [ ] Login view: invalid gift card handling
 - [ ] Purchasing gift card
 - [ ] Redeeming gift card
 - [ ] Reach size limit in mail editor
 - [ ] Mail export w/ attachments
 - [ ] Inbox rules are still applied (both when loading the least and from WS updates)
 - [ ] Moving mails
 - [ ] Deleting mails
 - [ ] Viewing/scaling of mails still works, loading external content still works
 - [ ] Scrolling mail in viewer with shortcuts
 - [ ] Approving 2FA
 - [ ] U2F register/login
 - [ ] Moving multiple mails from different mailboxes is not possible in search
 - [ ] Adding alias and running into limit
 - [ ] Changing mail signature
 - [ ] Configuring out of office
 - [ ] Displaying of template/knowledgebase groups in settings
 - [ ] Deleting account
 - [ ] Payment data dialog shows
 - [ ] Paypal dialog from payment viewer works (add paypal)
 - [ ] Change storage capacity
 - [ ] Switch subscription
 - [ ] Templates load and can be inserted

**Comment by charlag** [comment]
Regarding Promise.map:

https://github.com/sindresorhus/p-map

**Comment by charlag** [comment]
.catch() is now unsafely typed, it is not bound to the type of the promise (R) and we probably don't want to change the type of the chain in catch():

https://github.com/tutao/tutanota/blob/80937efa35353e16b4213e67e5b5dcfac3404f30/flow/api/libs.js#L51-L59

**Comment by johnbotris** [comment]
>  Moving multiple mails from different mailboxes is not possible in search

The folder button still remains but the dropdown is empty. Not sure if this exists on production already
