### ISSUE TITLE
zh_hant breaks android build

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2728]
We changed zh_tw to zh_hant, and when updating languages we generate `values-zh-rhant/strings.xml` in the android main resources directory. This is an invalid code, it needs to be `values-zh-rtw/strings.xml`.

**Comment by johnbotris** [comment]
also requires a change in `update-languages`

**Comment by jowlo** [comment]
So, android builds fine and the two chinese languages are there, is there anything else to test here?

**Comment by johnbotris** [comment]
sounds fine to me
