### ISSUE TITLE
Tutanota rendering wrong fonts from Windows partition in Linux Mint.

### ISSUE THREAD

**Issue by nadeem49** [tutao/tutanota#2738]
- ✅ This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- ✅  I've searched and did not find a similar issue.

**Description of the bug**
Tutanota App Image renders fonts from Windows partition since I always have my windows partition mounted in Linux Mint. It renders Helvetica condensed font and other fonts which are not system defaults.  Also this has been a problem for a long time ( Many months and many versions updated) 

Proof to see Tutanota uses Windows Partition:
![image](https://user-images.githubusercontent.com/58687234/108548865-679ed480-7312-11eb-80f4-d81f8ad0fb2d.png)

**To Reproduce**

1. Mount Windows Partiton
2. Relaunch Tutanota
3. Fonts from Windows partition back again

**Actual Behavior Screenshot**
![Tutanota](https://user-images.githubusercontent.com/58687234/108549140-cb290200-7312-11eb-8050-40785de7717c.png)

**Expected behavior Screenshot**
Unmounting the Partition gives correct fonts
![image](https://user-images.githubusercontent.com/58687234/108549733-949fb700-7313-11eb-8a5f-38698841e108.png)

Unmounted Proof:
![image](https://user-images.githubusercontent.com/58687234/108549799-aed99500-7313-11eb-9f51-3396790cf319.png)

**Desktop version**
 - OS: Kernel: 5.11.0-051100-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.8.6 
           wm: muffin dm: GDM3 Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Tutanota  App Image version: 3.80.2 
(All previous versions are also having this problem)

**Note**
I did not make any changes to cinnamon font settings, as you can see in screenshot, there is no where Helvetica
![image](https://user-images.githubusercontent.com/58687234/108550145-27d8ec80-7314-11eb-9c4b-093705697ea0.png)

**Thank you, would be glad if someone helped me read Emails with the right fonts**

**Comment by johnbotris** [comment]
I've seen your [post](https://forums.linuxmint.com/viewtopic.php?f=47&t=343103) in the linux mint forums and it looks like this is an issue with your system rather than the app.
