### ISSUE TITLE
Uncached languaged might lead to a problem on update

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2744]
v3.81.8

**To reproduce**:
1. Let the app install service worker
2. Select non-English language
3. Make a new version with updated language
4. Let the new app version install but don't apply it yet
5. Reload the page
6. See the error

**What happens**:
We don't cache non-English translations in service worker for now. When the new version is published but the old service worker is still active we will try to fetch old translation (with old hash in the filename) and this translation is not there anymore.

**Possible solutions**:
Do one of:
  - Remove hash from the language name
  - Cache used languages on demand
  - Silently fall back to English

**Comment by mpfau** [comment]
test notes:
- [ ] login with old version, switch lang to DE
- [ ] press F5, error should occur
- [ ] update to new version
- [ ] press F5, error should not occur anymore (verify from network view, that translation-de is cached by the service worker)
