### ISSUE TITLE
Allow drag and drop msg export

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2756]
Enable export to msg with drag and drop on windows desktop clients. Should only be active if feature ExternalEmailSender is active.

**Comment by johnbotris** [comment]
# Testing Notes

- [ ] Users with an account type "ExternalEmailProvider" or "Starter" are able to drag mails from the mail list to other applications om .msg format by holding Alt when dragging.
- [ ] When mails don't download in time before the user releases the mouse, they are notified of what happened and told to try again
- [ ] Exported .msg files are correctly interpreted by outlook, the subject, body, recipients, sender, attachments, inline and external images, send date and receive date are all correct
- [ ] The same mail will not be downloaded more than once across DragEvents (given that the temp dir hasn't been cleared)
- [ ] Progress bar won't get stuck when email contents are being downloaded

## Regression testing
- [ ] Regular EML export works still
- [ ] Dragging mails from the mail list to a folder works still
- [ ] HTML Sanitizer works properly:
- [ ] External images will be blocked/not blocked when required
- [ ] Relative links will be enabled/disabled when required (test receiving emails from Tutanota Team that link to parts of the app)
- [ ] A placeholder for inline image attachments is shown while images are loading

**Comment by mpfau** [comment]
The feature feels very nice!

Open issues:
- [ ] The name is currently not exported. On our test system, no sender is displayed in the mail list.
- [ ] The temp folder should be cleared on export
- [ ] It is hard to learn about the feature as we also have a "normal" drag within our application. We should either combine the feature with the normal in-application drag (only start downloading when we believe that the user will do an out of application drop) or show at least a dialog to the user if he drops a mail outside of Tutanota, that he needs to press ALT...

**Comment by jowlo** [comment]
For regular (single file) eml exports, inline images are shown as attachments, but the inline display is broken at least in Thunderbird. I do not know if this is a old issue.
![Screenshot from 2021-02-26 13-05-07](https://user-images.githubusercontent.com/6842104/109298197-7fef8180-7833-11eb-8b9e-44c35ebe9a35.png)

**Comment by johnbotris** [comment]
>  It is hard to learn about the feature as we also have a "normal" drag within our application

I agree with this,  maybe not for this release but when we enable it for all clients

**Comment by armhub** [comment]
We will create separate issues for the remaining findings.
