### ISSUE TITLE
client host rejected cannot find your reverse hostname

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2767]
I cannot receive emails sometimes
some web services cannot find tuta domain

**Comment by europound** [comment]
185.87.148.118

**Comment by charlag** [comment]
Exuse me, what is this IP address?

**Comment by europound** [comment]
some crypto exchanger

**Comment by jowlo** [comment]
I have contacted the "crypto exchange" that is running the server under the IP you mentioned and asked if they could check if there are any problems with resolving our domain and/or if they would provide some more information.
