### ISSUE TITLE
"Move" action not shown for messages from Tutanota 

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#2769]
On the web and desktop clients.

For emails sent from Tutanota to all users, the "move" action is not shown, and users cannot move them to "archive" etc. The keyboard shortcuts work.

![image](https://user-images.githubusercontent.com/197261/109320406-45481200-7850-11eb-8343-6af68414d363.png)

**Comment by charlag** [comment]
This is a notification message, not an email, no move button here

26 Feb 2021, 16:38 by notifications@github.com:

**Comment by armhub** [comment]
Moving such emails with drag&drop also still works.
