### ISSUE TITLE
Clean up the temporary directory

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2770]
We use tmp to store exported msgs aswell as downloaded attachments. Windows doesn't automatically clear it out, so we should be clearing it manually.

**Comment by johnbotris** [comment]
# testing
- [ ] the tutanota temporary directory should be deleted upon app start and up close. test his by downloading attachments and then seeing if the directory remains after closing the app or after starting the app up again

**Comment by jowlo** [comment]
### Linux
 * [x] Dir is removed on app start
 * [x] Attachments: I cannot see the directory when downloading files, but when _opening_ an attachment, the directory incl contents is created and removed again when i quit via the tray icon.
 * [x] Drag'n'Drop:

**Comment by johnbotris** [comment]
It has been noted that generated file names are quite ugly, which is true because they were originally not supposed to be seen. This will be changed now

**Comment by johnbotris** [comment]
# testing 2.0

- [ ] Drag and drop still works, file names are no longer ugly
- [ ] When exporting multiple eml files, a save dialog is shown
