### ISSUE TITLE
Hovering over NavButton shows href tooltip

### ISSUE THREAD

**Issue by qbit0101** [tutao/tutanota#2773]
**Describe the bug**
Since updating to 3.82.1 Win10
On mouse rollover of the options, apart from first sidebar, the file location of the option appears bottom left.

**Comment by jowlo** [comment]
I think this is about us displaying the path for links now on the bottom left on the desktop client. This is also happens to me on Linux.

![Screenshot from 2021-03-01 08-54-09](https://user-images.githubusercontent.com/6842104/109468009-4e152f80-7a6c-11eb-88e5-705b76e13c68.png)


@qbit0101  Could you please clarify if this is what you mean by your bug report?

**Comment by qbit0101** [comment]
@jowlo 
Yes.
Thank you

**Comment by jowlo** [comment]
Somehow, i cannot reproduce this today.

**Comment by qbit0101** [comment]
Still present in W10.
Was this here before 3.82.1?
I find it distracting and should be changed.

**Comment by charlag** [comment]
Can confirm on windows

**Comment by jowlo** [comment]
It is the chromium status bar. I was looking for options on the electron `BrowserWindow` to disable it. setting `kiosk = true` works, but then, also, the whole app is in kiosk mode.

**Comment by charlag** [comment]
It's not a chromium bar, it's our own overlay. Condition for link is broken somehow.

2 Mar 2021, 12:39 by notifications@github.com:

**Comment by jowlo** [comment]
Oh, okay, thanks,  thought it was the chromium one and it was gone with `kiosk`, but then again i wasn't able to reproduce before anymore anyways. 

@charlag Could you give me a rough pointer me to where those are drawn?

**Comment by charlag** [comment]
Check `updateTargetUrl` in NativeWrapperCommands, it is called from main thread ApplicationWindow
