### ISSUE TITLE
Change system tray icon

### ISSUE THREAD

**Issue by xonha** [tutao/tutanota#2775]
How can i alter the tray icon so that it would match my theme (Papirus)?
Using appimage on kde.

![Screenshot_20210227_133040](https://user-images.githubusercontent.com/25267506/109393447-708a3a00-7900-11eb-869a-747f348a4d8d.png)

**Comment by LibreFoss** [comment]
It's no such a big deal..

**Comment by jowlo** [comment]
If you build the desktop app yourself (see [here for a guide](https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md), you could play around with the icons and change them any way you want. 

The one that is used for the tray should be in `resources/desktop-icons/`, it is one of the files named `logo-solo-red`, depending on your system.
