### ISSUE TITLE
Unread mails in folder not shown in folder list

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2777]
Although i have unread mails in a folder, it does not get displayed in the folder list. This is consistent through logins/clients.

![Screenshot from 2021-03-01 10-24-02](https://user-images.githubusercontent.com/6842104/109477601-7f93f800-7a78-11eb-8dbc-af0949b7db50.png)

**Comment by charlag** [comment]
Counter is broken? if you move email out/in?

**Comment by jowlo** [comment]
Still the same if i move stuff around. Actually, github's notification mail for your comment was sorted into the folder and did not show up as unread. A second one did though.

**Comment by jowlo** [comment]
Yes, they actually seem to go to negative, as seen on Brakepoint in https://github.com/tutao/tutanota/blob/01e94056ce66ae2e30652a84323d6f3f83b10cb0/src/mail/model/MailModel.js#L301.
I guess this should never happen...

![Screenshot from 2021-03-01 10-43-14](https://user-images.githubusercontent.com/6842104/109479756-00ec8a00-7a7b-11eb-8224-ded4bde5cd9b.png)

**Comment by charlag** [comment]
If you load the list to the end it should fix itself

**Comment by jowlo** [comment]
Ok, thanks! It's still a bug though, right?

**Comment by charlag** [comment]
It very rarely goes inconsistent and we implemented this "self-healing" as a workaround. I don't think there's a real fix tho.

**Comment by jowlo** [comment]
Hmm, well, at least it should never be negative, right? I just skimmed over it, is this generated on the client?

**Comment by charlag** [comment]
no, it's counted by DB, client just temporarily applied changes when something happens

**Comment by bedhub** [comment]
Currently we don't have a better solution then this self healing.
