### ISSUE TITLE
Add message expiration time for folders

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#278]
It would be nice if we can have the possibility to configure/set a _message expiration time_ per folder that allow us to delete, automatically, the folder's content when older than the expiration time configured.

For instance, assuming the following image resembles the mailbox structure for a given user, it can be something like this:

![image](https://user-images.githubusercontent.com/34633617/35773434-7cbecef6-0920-11e8-83f2-44d3a45421b1.png)

It would be nice, if/when this is implemented, that we can have the hability to _pin_ (to name it somehow) messages, so they don't get deleted, regardless of the folder they are located at, and the deletion policy applied to those.

**Comment by x80486** [comment]
Folks, have you considered this one? I think it should be doable now that `Spam` and `Trash` have a fixed number.

**Comment by armhub** [comment]
This is not scheduled yet, therefore it is not on the roadmap milestone.
