### ISSUE TITLE
Silent failure on sending email when account is in PaidSubscriptionNeeded

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2781]
How to reproduce:
1. Set account to approval status PaidSubscriptionNeeded
2. Login into that account
3. Try to send an email to another internal user
-> The send progress dialog is shown shortly but the email draft stays open and the email is not sent

AccessBlockedError occurs: could not send mail (blocked access)

Should not be possible to open mail editor in this state, should see the dialog instead

moved from server issue 630

**Comment by charlag** [comment]
checkApprovalStatus is defined in both approval.js LoginUtils

**Comment by johnbotris** [comment]
# testing
for a user who's account is in paid subscription needed state:
- [ ] User is informed that they are unable to send mails when opening a mail editor or sending
- [ ] A mail editor still opens though, and they are able to mail sales, support, etc. (but noone else)

for all other users
- [ ] it's the same as always

# regression testing
Did a refactor of login error handling while dealing with a TODO
- [ ] make sure errors at login are all handled as they should be:
- [ ] AccessBlocked
- [ ] BadRequest
- [ ] NotAuthenticated
- [ ] AccessDeactivated
- [ ] AccessExpired
- [ ] TooManyRequests
- [ ] CancelledError
- [ ] ConnectionError
