### ISSUE TITLE
Precondition does not work on iOS

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2785]
In case the business feature is not enabled and hit save on the out of office notification dialog we show a plain PreconditionFailed error message in the iOS app. Not sure if this also happens in the web application or just on iOS.

![precondition_failed_out_of_office](https://user-images.githubusercontent.com/8296817/109672465-5ad17a80-7b75-11eb-9b8d-56c3e69dad39.jpeg)

**Comment by charlag** [comment]
Only happens on iOS, we can't get Precondition header (or Erro-Id) for some reason, neither debug nor dist. CSP issue?

**Comment by jowlo** [comment]
We have just deployed a new server release to the test system with a server-side fix. Tested by @charlag

**Comment by charlag** [comment]
Test notes:
- [ ] Try to activate out-of-office without booking business feature on iOS

**Comment by bedhub** [comment]
fixed with server release 3.82.9
