### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#2787]
TODO

**Comment by mpfau** [comment]
Test notes:
- [ ] [desktop] Test migration of config files
- [ ] [desktop] Test alarm invalidation
- [ ] [desktop] Test changing and persisting desktop settings
- [ ] [desktop] Test opening external URLs works as expected
- [ ] [desktop] Test that SSE retries with increasing interval

**Comment by jowlo** [comment]
## Testing
* [x] Test migration of config files
   * On first try push identifier were removed from `conf.json`, however could not reproduce again. Seems to be working.
* [ ] Test alarm invalidation
* [ ] Test changing and persisting desktop settings
* [ ] Check that URL handling still works (changes in `ApplicationWindow.js`)
    * [ ] Test opening external URLs works as expected
    * [ ] No file url handling
    * [ ] Check logout and no auto login
    * [ ] Open second window in desktop client
* [ ] Test that SSE retries with increasing interval
* [x] Start desktop client with non-parseable (ie broken) config
* [ ] Check gift card redemption works with new and existing account
* [x] Change desktop config and restart
* [ ] Check custom notificaton emails for whitelabel domain (preview)
