### ISSUE TITLE
PayloadTooLargeError for AlarmService when logging in on mobile/desktop apps

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2788]
When logging in on mobile or desktop apps for the first time we check if event reminders need to be scheduled for this device. If so we try to schedule all user alarms using the AlarmService in one request. This can lead to a PaymentTooLargeError if there are too many reminders and then we try to schedule the initial alarms each time we log in and each time the same error is shown.

Code:
`PushServiceApp._scheduleAlarmsIfNeeded()`
`CalendarFacade.scheduleAlarmsForNewDevice()`

Things to consider for this fix:

- Split user alarms into multiple chunks and do multiple AlarmService requests
- Avoid creating user alarms for outdated reminders (check if old reminders are already cleaned up)
- Check if we really need to go through the server to schedule these initial alarms or if we can also schedule them directly by introducing a `scheduleAlarmsForNewDevice` function to the `NativeRequestType`.

**Comment by charlag** [comment]
Check that alarms are scheduled for new device on
- [ ] Desktop
- [ ] Android
- [ ] iOS
