### ISSUE TITLE
use node.js url.pathToFileURL instead of own implementation

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2791]

**Comment by jowlo** [comment]
Could you rebase and see that you also use `url.pathToFileURL` for the changes in 55b424ee2455367945afe30eee86dedc8896913a

**Comment by jowlo** [comment]
Could you rebase and see that you also use `url.pathToFileURL` for the changes in 55b424e?

**Comment by vaf-hub** [comment]
I tested it and it seems to work fine. Except for redirects after logout, I am not sure, if we get the expected behavior:
If we are in calendar view, then logout and login again, we will go to email view instead of going back to calendar view.
Is this what we want? If so we can label it as tested.

**Comment by charlag** [comment]
I think that's how it works in prod as well so it's fine
