### ISSUE TITLE
When exporting multiple emails, subjects with / in the subject name results in a directory in the zip file

### ISSUE THREAD

**Issue by Kingwad** [tutao/tutanota#2799]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
When you select multiple files to export and get a zip file of .eml files named with the date, time and subject, with any characters that are invalid for filenames replaced with _
If any of those email subjects contains a / character it is interpreted as a directory break.

**To Reproduce**
Select multiple emails, at least one of which contains at least one / in the subject
Export those emails
Open the zip file downloaded

**Expected behavior**
A flat (no nested directories) zip file of .eml files, each one named with the date, time and subject of the email, with invalid characters including / replaced with _

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 86
 - Version 3.82.4

**Comment by jowlo** [comment]
Zip file contents look fine, extraction works on linux.
