### ISSUE TITLE
Allow custom theme in mobile and desktop apps.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2804]
Currently the custom colors are only visible when logging in on the users whitelabel domain. Users are confused that they can configure these colors in the apps but then they are only active until they log in again. They expect to also have these colors within the mobile and desktop apps. ~~~Maybe we can store the theme configuration in the local storage.~~~

 - We need to save custom themes into the native storage because we need to apply it early.
   - We can avoid using localStorage altogether in apps.
   - As IPC is async and depends on the worker we should pass theme info in the URL to apply it to the webview early enough.
 - When logging in the app with whitelabel domain we should show a dialog suggesting to apply a custom theme. We also save theme to the native storage
   - We do this to avoid unwanted switching between themes in case there are multiple accounts on the device
 - We do not yet allow custom themes on our domain
 - Change color switcher to use a picker and show domains as options there

---

## Test notes

It's best to test with both colors and logo when configuring whitelabel. 

 - [ ] Check that logout still works in all apps.
 - [x] Check that second factor does not break the app.
 - [x] Check that opening links without _target=blank does not do anything.
 - [x] Add whitelabel and see that color changes are applied immediately but not persisted when on tutanota.com
 - [x] Log in on whitelabel domain and see that custom theme/colors are applied. There should be no color picker.
 - [ ] Try to remove whitelabel colors and log in on custom domain. See that theming is not applied.
 - [x] Add whitelabel colors and log in in desktop/android/iOS apps. See dialog that suggests to apply a theme. See that theme is actually applied if agreed.
   - [x] Check that theme picker shows domain as one of the options.
   - [ ] Check that theme switching works with custom domain.
   - [x] Check that reloading the app/logout does not flash with different color. (does not work on desktop before the restart).
   - [ ] Check that removing whitelabel colors on another device removes them from the app after login and that domain is not one of the options in theme picker anymore.
- [x] Check that logo is still sanitized (upload SVG with custom elements or change conf.json for desktop).
- [x] Check that colors can be configured with 3 digits
- [ ] Check that Android/iOS apps change status/navbar colors to black/white to contrast header_bg

**Comment by bedhub** [comment]
* detects custom colors even though there are no colors configured for the whitelabel domain
* change color in web client and login on desktop -> Colors are not applied after login.

**Comment by johnbotris** [comment]
>  iOS app crashes after login

We will do the web and desktop release and then fix iOS. We need to replace some certificates as part of the iOS build automation changes
