### ISSUE TITLE
Frequent new version available popup

### ISSUE THREAD

**Issue by iripu** [tutao/tutanota#2809]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Whenever new version is available, a popup asks to refresh or postpone on website. Updates are frequent so it's annoying to see this popup often. It's understandable on a native app but not on website, imagine this a happening on every website, how annoying it will be.

**To Reproduce**
Steps to reproduce the behaviour:
1. Just open the webapp after an update available.

**Expected behaviour**
It should automatically update behind without any click or information, just like any other webapp that exists.

**Screenshots**
https://ibb.co/GHGdxCP

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser: Chromium
 - Version: 88

**Comment by charlag** [comment]
Tutanota is not "every website", it is an app and which deals with a lot of sensitive data. We we cache all code locally (so that we cant just replace things) and we update in background when you open the app. If you close the tab it will apply update automatically as well.

**Comment by foldfree** [comment]
I think in terms of ux it is not the best for the common user. I am not a critical risk person, I'd rather have silent updates and get to my emails as fast as possible.

Would it be possible to implement a checkmark box: 'never show again, refresh & update automatically' kind of thing?
