### ISSUE TITLE
Mismatched scrollbars in event preview popup in chromium

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2811]
The vertical and horizontal scrollbars in the description field of the event preview popup are different thicknesses in electron and chromium:

![Screenshot from 2021-03-08 16-47-48](https://user-images.githubusercontent.com/22109738/110345568-a1681e80-8026-11eb-9a25-9d904ca29958.png)

They're also generally just pretty chonky, I think they could have lower profiles

**Comment by wrdhub** [comment]
Cannot reproduce
