### ISSUE TITLE
Use only a single view for setting domain records

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2820]
Right now we have two different views (`showDnsCheckDialog` and a page of `showAddDomainWizard`) where users can see the necessary/recommended DNS records.

We should always use the same one.

![Screenshot from 2021-03-09 16-44-43](https://user-images.githubusercontent.com/6842104/110497749-0723db80-80f7-11eb-8b69-1dbe839e86fe.png)
![Screenshot from 2021-03-09 16-44-30](https://user-images.githubusercontent.com/6842104/110497751-07bc7200-80f7-11eb-903c-828a66587be6.png)

**Comment by vaf-hub** [comment]
## Test notes (copied from the PR)
There are two places where we show expected/recommended DNS records for custom domains, check both places:
 * In the setup wizard when registering a new domain (or continuing)
 * When clicking on the line below a registered domain 

For both views, 
 * [ ] verify that when setting up a custom domain the requested values (points to) for CNAME and MX entries end with trailing a dot ie `...tutanota.com.`
 * [ ] verify that text records do not end with a dot (eg for dkim)
