### ISSUE TITLE
MSG export breaks with duplicate attachment filename

### ISSUE THREAD

**Issue by namazso** [tutao/tutanota#2822]
**Describe the bug**
"An error occoured" when exporting more than a few mails

**To Reproduce**
1. Select a bunch of emails (I did 100)
2. Click on 'Export'
3. See error

**Expected behavior**
Export works

**Screenshots**
![image](https://user-images.githubusercontent.com/8676443/110605458-72b68900-8189-11eb-87fa-3e4e24de8d57.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.82.8

**Additional context**
Doesn't seem to reproduce with very few emails (like 10)

**Comment by johnbotris** [comment]
Could you please provide the error output that shows when you click "Send report"

**Comment by namazso** [comment]
Oh, didn't know "Send report" does not just send it instantly, and lets me view the data. Maybe something to consider changing?

anyways:

```
Feedback v3.82.8 - Error - PREMIUM - win32
Client: win32
Type: PREMIUM
Tutanota version: 3.82.8
Timestamp (UTC): Wed, 10 Mar 2021 09:59:07 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.82.8 Chrome/87.0.4280.88 Electron/11.1.0 Safari/537.36
Error
Error message: The attachment with the name 'unknown.txt' already exists
Stacktrace:
Error: The attachment with the name 'unknown.txt' already exists
at r.value (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain-89a52085.js:13:71157)
at r.value (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain-89a52085.js:13:71521)
at r.value (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain-89a52085.js:13:80030)
at ql (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain-89a52085.js:13:88454)
at Object._invokeMethod (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain-89a52085.js:13:246789)
at C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain-89a52085.js:13:241271
at electron/js2c/browser_init.js:189:579
at Object.<anonymous> (electron/js2c/browser_init.js:157:9268)
at Object.emit (events.js:315:20)
```

**Comment by johnbotris** [comment]
thanks!

Maybe it is ambiguous, but also don't hesitate to send error reports when you get them, we find them very useful.

**Comment by johnbotris** [comment]
@namazso It looks like one of the emails you are trying to export has two attachments with the same name which is breaking the .msg file generator. You can go to Settings->Desktop and switch back to eml mode, or avoid that particular email. We'll get this fixed soon

**Comment by johnbotris** [comment]
fixed now here, will just need an update: https://github.com/tutao/oxmsg/commit/a201b436f34e6b795359597b3a454cacc1aaff22

I don't thinks there's any reason to deny attachments with the same name, even if they have the same cid - A duplicated filename+cid is an issue that should be handled at the source, rather than causing an error here

**Comment by johnbotris** [comment]
# testing
make sure that exporting an email as msg when it has attachments with duplicated filenames still works
