### ISSUE TITLE
Calendar event sometimes has vertical overflow

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2824]
I can only get it to happen once after a fresh reload, upon first click of a calendar event, if the description overflows vertically then the background does not grow to fill. Any subsequent clicks of any events will display normally

![Screenshot from 2021-03-10 10-59-56](https://user-images.githubusercontent.com/22109738/110612269-efe0fe80-8187-11eb-883d-610224d41919.png)

**Comment by johnbotris** [comment]
# testing
1. directly after opening the app go to the calendar view and click on an event with a multi-line description (the html sanitizer can't have been loaded already)
2. the popup should fit the text completely

**Comment by ganthern** [comment]
The description text fits everywhere, but I couldn't get it to break on the current production system as well, so maybe someone else should double check this.
