### ISSUE TITLE
Navigate to inbox after deleting email

### ISSUE THREAD

**Issue by rarealphacat** [tutao/tutanota#2830]
Possible to add option to choose where to navigate after deleting email? e.g. return to the inbox. The current default navigation is to open up next in the inbox, which automatically mark the next email to "read". The common practice such as Protonmail and Gmail is to return to blank inbox.

**Comment by johnbotris** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
