### ISSUE TITLE
All links in support dialog go to homepage

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2838]
- Open up the support dialog
- Type in a query, eg. Whitelabel
- Click any link

The link will take you to the homepage of https://tutanota.com, rather than wherever you would expect it to take you

**Comment by jowlo** [comment]
The howto link routing is are a bit inconsistent. Sometimes we send a `302` redirect from `/howto#asdf` to `/howto/#asdf` (note the trailing slash) and it works fine. When we do local routes, we do not append the `/`. When there is not `302` when coming from an external (eg the webapp) we neither show the faq nor do the redirect.

**Comment by charlag** [comment]
Links were generated for https://www.tutanota.com and www redirects to homepage. Fixed in website project.
