### ISSUE TITLE
emails are not coming through

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#2839]
weird
https://liteswap.org
https://www.mahnem.ru/
and others from russia or shady countries 
mails are not coming through
why is that?
you ve got very strict resolving, scam, spam rules?

**Comment by europound** [comment]
please loosen up something somewhere
too tight

**Comment by charlag** [comment]
Please see https://tutanota.com/contact/
Some Russian providers can't send to us because of the block

**Comment by europound** [comment]
what block?
all these sites are ok with gmail
