### ISSUE TITLE
2FA time issue with TOTP

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#284]
I've had a hard time trying to add an OTP 2F through your webclient until I realized time is not accurate in my computer, because of BIOS dead battery. I knew 2FA uses current time to generate the codes so I could "fix" it and add my second factor, but I needed some time and many tries to figure it out.

I've never had this problem before with the same computer because, I think, when I try to authenticate to other servers they don't check my computer's time, since code was generated with my mobile, which is perfectly synchronized in time, thus generating proper codes.

If your webclient does the same check when authenticating (which I don't know, since I only had problems when trying to add a new second factor), it can be problematic if you're using a computer in which you can't change time settings.

**Comment by mpfau** [comment]
We already check multiple time windows on the server and should adapt the client to it (see https://github.com/tutao/tutanota/blob/83f4647445d3e075b82e3e20bd1287111b3dae06/src/settings/EditSecondFactorsForm.js#L179).

**Comment by armhub** [comment]
Also increase the time on the server accordingly.
