### ISSUE TITLE
Open mail-editor when opening mailto: link

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2840]
We are not opening the mail-editor when opening `mailto:` links in the browser.

See [reddit](https://www.reddit.com/r/tutanota/comments/m2tjyq/problem_with_mailto_links/), also happens to me. Desktop app seems to work fine.

**Comment by jowlo** [comment]
It works fine on local but not on the production system.

It seems that in
https://github.com/tutao/tutanota/blob/2215b88730e9585945c40eb5682684a24a59afb4/src/mail/view/MailView.js#L524
`m.route` is undefined on the production system but not when testing locally.

**Comment by charlag** [comment]
What about dist locally?

**Comment by johnbotris** [comment]
local dist also doesn't work

**Comment by jowlo** [comment]
It looks like on dist we somehow skip the redirect to `/mailto` route and directly go to `/mail`, thus, never triggering this branch. `m.route` being undefined was some weird scoping i messed up in debugging.
