### ISSUE TITLE
Local admin is not authorized to remove himself from shared mail group

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#285]
1.) login as local admin
2.) create shared mail group
3.) login as global admin and add local admin to shared mail group
4.) login as local admin select shared mail group and try to remove membership 
-> Exception dialog because of NotAuthorized exeption. Consider to catch NotAuthorized or allow local admin to administrate himself by default.

**Comment by mpfau** [comment]
fixed on server

**Comment by bedhub** [comment]
exception catched on client. and admin can add or remove himself if he administrate himself
