### ISSUE TITLE
Administrated groups are displayed without text

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#286]
1. log in as local ladmin
2. create shared mail group and user
3. log in as global admin and select local admin group in Settings->Group.
4. Group viewer shows empty rows for administrated groups
![administrated_groups](https://user-images.githubusercontent.com/8296817/35854830-c15c8432-0b31-11e8-899a-45c2053231dc.png)

**Comment by mpfau** [comment]
fixed
