### ISSUE TITLE
Feature request: "ala Calendly" functionality

### ISSUE THREAD

**Issue by gwpl** [tutao/tutanota#2872]
Just I would love to be able to generate encrypted URL ala tresorit, cryptpad, eventually protected by password, that would allow people to see my free slots on given week and pick something, and keep whole thing encrypted end2end of course.

**Comment by johnbotris** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

**Comment by gwpl** [comment]
Thank you! Done https://www.reddit.com/r/tutanota/comments/nea3s4/feature_request_ala_calendly_functionality/ .
