### ISSUE TITLE
Uncancellable text selection in Android

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2873]
Selecting text in android will cause the selection indicator to be stuck until you copy/select all/etc, even when tapping somewhere else or going back out of the mail viewer:

![text selection](https://user-images.githubusercontent.com/22109738/112461189-ffec0700-8d5f-11eb-8ca6-771903cf8b3a.png)

![Screenshot_20210325-115054_Tutanota](https://user-images.githubusercontent.com/22109738/112461647-6ec96000-8d60-11eb-8624-dbf689e1c6a1.png)

## Test Notes:
- [ ] test on ios, android and in single column layout
- [ ] test the following in mailview and searchview
- [ ] select text in an email
- [ ] following actions deselect the text:
  - [ ] back button (android)
  - [ ] in-app back navigation
  - [ ] left swipe
  - [ ] clicking somewhere else on the mailbody
  - [ ] expanding and collapsing quotes and mailbody shows correct behavior
  - [ ] after zooming in and dragging the deselection still works

**Comment by rezbyte** [comment]
Found an issue while testing on iOS: #6209. Also does this weird behaviour where if you select some text then zoom in & drag, the highlight sticks to the screen & does not move to stay over the text.
