### ISSUE TITLE
Deleted group memberships not being handled by cache

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2874]
1. As A, invite B to be in your calendar
2. As B, accept the invite, open up the group sharing dialog for the calendar
3. As A, delete B from the group, then invite B again
4. As B accept the invite, open the group sharing dialog
5. See that B is listed twice as a member

Seems like we don't get DELETE events for group member instances, so the membership list is remaining in the cache. Is this related to/duplicate of #2619?

We could fix this be removing all instances belonging to a given group when the membership has been removed from the user. This isn't a huge issue now because it's fixed by reloads, but will become a much bigger issue with offline mode #590 

## Test notes migration
 - [ ] Start with an existing desktop offline database (better back it up for multiple tests), log in with new version, see that there are no errors when loading/saving entities. The contents of db will be purged with migration.
 - [ ] Start with a new database (add new account), see that there are no errors when loading/saving entities

## Test notes lost membership
test these in desktop and browser

 - [ ] Lose membership (e.g. participate in shared calendar and then get removed by another user), see that everything works and instances are removed (at least visibly)
 - [ ] Be an admin, make another user lose the same membership that you have, check that you still didn't delete anything (e.g. a calendar event can be opened without network request)

**Comment by charlag** [comment]
This overlaps with #2619 a bit but there are more issues

**Comment by armhub** [comment]
Found a similar issue: 
1. As A, invite B to be in your calendar
2. Deactivate user B (not sure if this step is necessary to reproduce the issue)
3. As A, remove B from your calendar
-> The participants list is not updated and B is still visible.
After opening the sharing dialog again B is not visible any more.

**Comment by ganthern** [comment]
Can be tested once 
* #4706 
* #4707 
* #4700 

are closed
