### ISSUE TITLE
Notification problem on Windows

### ISSUE THREAD

**Issue by bingoxo** [tutao/tutanota#2878]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Describe the bug**
i'm having same issue as https://github.com/tutao/tutanota/issues/2334 , but for him it auto fixed for me it hasnt

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 3.82.12

**Comment by charlag** [comment]
Could you please grab logs from settings->about->send logs and send them to hello@tutao.de (or Premium support) with link to this issue? Thank you.

**Comment by bingoxo** [comment]
> Could you please grab logs from settings->about->send logs and send them to [hello@tutao.de](mailto:hello@tutao.de) (or Premium support) with link to this issue? Thank you.

Done :)

**Comment by bingoxo** [comment]
Client: win32
Type: FREE
Tutanota version: 3.83.3
Timestamp (UTC): Sat, 01 May 2021 03:54:31 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.83.3 Chrome/87.0.4280.141 Electron/11.4.4 Safari/537.36
CryptoError
Error message: invalid mac
Stacktrace:
CryptoError: invalid mac
at C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:1:415399
at Object.aes256Decrypt (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:1:415739)
at Object.aesDecryptObject (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:205269)
at Object._getEncryptedVar (C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:208726)
at async C:\Program Files\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:13:246033

**Comment by charlag** [comment]
@Pablohn26 some data is corrupted it seems, you would need to clear `%APPDATA%`
