### ISSUE TITLE
Remove target="_blank" from login button

### ISSUE THREAD

**Issue by FeixuRuins** [tutao/tutanota#2891]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
The `LOGIN` button in the toolbar shouldn't open in a new tab.

**To Reproduce**
1. Go to `https://tutanota.com`
2. Hit `LOGIN`

**Expected behavior**
It should behave like a normal link.

**Screenshots**
![image](https://user-images.githubusercontent.com/66232834/113017096-1eca0f00-914d-11eb-9295-c58105f0eeed.png)

**Desktop:**
 - OS: [Windows, Ubuntu, ChromeOS]
 - Browser [Chrome, Firefox]
 - Version [Chrome: 89.0.4389.90, Firefox: 87.0]

**Comment by charlag** [comment]
It puts you on a different website on a different domain. If you want to log in wouldn't it make sense to bookmark mail.tutanota.com directly?

**Comment by vaf-hub** [comment]
I think we should close this as wontfix, because the current behavior seems fine with me.
