### ISSUE TITLE
Event for next month is not displayed with week view

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2892]

**Comment by vaf-hub** [comment]
I am not sure I understand this. Do you mean that if I look at week 17 (the last week of April) and have an event for May, 1st, it is not displayed? For me such an event is visible when looking at week 17. Can you please elaborate how to reproduce this?

**Comment by charlag** [comment]
That's how it was for us. Maybe there was something special, I'm not sure now, will need to try again.

**Comment by vaf-hub** [comment]
So I tried and was unable to reproduce this, both with 3.82.12 on the production system and with current master locally. So there's probably something else to be considered for this bug.

**Comment by charlag** [comment]
Try to load it on the week before the month boundary (you can manipulate the URL). I think when you switch months it might not be visible.

**Comment by vaf-hub** [comment]
Still no luck reproducing this. The event is displayed for me.

**Comment by charlag** [comment]
Yes, It's the same, I just couldn't find it

duplicate of #3136
