### ISSUE TITLE
Subscription selector highlights options incorrectly when upgrading

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2893]
For each page (private/business) it should just highlight the center option, but it looks like this:

![Screenshot from 2021-03-31 11-19-00](https://user-images.githubusercontent.com/22109738/113121723-35d33480-9213-11eb-9a81-02823aad4568.png)

![Screenshot from 2021-03-31 11-19-05](https://user-images.githubusercontent.com/22109738/113121726-366bcb00-9213-11eb-8eae-b933f5acef1e.png)

**Comment by vaf-hub** [comment]
The way I understand this we should highlight the Premium box if and only if this is a) a private target subscription type and b) an initial signup or the current subscription type is Free.
