### ISSUE TITLE
Cannot change payment method

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2895]
Customers which have no account posting cannot change the payment methods. We should handle the case when there are no posting, e.g. customers with first year for free promotion.

https://github.com/tutao/tutanota/blob/0243aa882ce0446ad29a346cd86b75dc331045aa/src/subscription/PaymentViewer.js#L99

**Comment by vaf-hub** [comment]
### Test notes:

Go to settings/payment and open change payment method to reproduce the error.
You will need an account with no postings yet. It can be created by signing up with a first year free promotion link generated in the admin client.

- [ ] create an account with no postings and check the error does not occur anymore.
- [ ] change the payment method and check the price data and invoices are still correct afterwards for both an account with and one without postings.
