### ISSUE TITLE
long description & location overflow event popup horizontally

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2899]
**Bug in web app**

**To Reproduce**
1. create an event in calendar view with very long name and/or location
2. click on it and see overflow

**Expected behavior**

**Screenshots**
![overflow-calendar-chrome-win](https://user-images.githubusercontent.com/29049728/113273711-36380200-92dd-11eb-9059-5f044429a3fb.png)

**Environment:**
seems to be happening in all browsers & platforms

**Comment by johnbotris** [comment]
# testing
- [ ] horizontally long event descriptions/titles/locations will not overflow the popup

**Comment by Pa7Hub** [comment]
Very long text will stretch the popup and becomes unreachable

![Screenshot from 2021-05-12 15-28-29](https://user-images.githubusercontent.com/70587561/117982956-ce8ec100-b336-11eb-81a8-4db1faa7b603.png)
