### ISSUE TITLE
PreconditionFailedError not handled in suspension handler

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2900]
When the move mail operation is executed after the suspension and throws an PreconditionFailed error. This error is not being handled correctly. 

Client: Browser
Type: PREMIUM
Tutanota version: 3.82.11
Timestamp (UTC): Sat, 27 Mar 2021 21:38:44 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
PreconditionFailedError
Error message: 412: none | POST /rest/tutanota/movemailservice
Stacktrace:
PreconditionFailedError: 412: none | POST /rest/tutanota/movemailservice
at ab (https://mail.tutanota.com/common-min-b77d519d.js:1:2753)
at XMLHttpRequest._suspensionHandler.isSuspended.f.onload (https://mail.tutanota.com/worker.js:1:103932)

**Comment by vaf-hub** [comment]
This error is not handled because we use different functions in MailView.js to move mails, one of which did not take care of handling errors. So I think it is not directly related to the suspension handler.

**Comment by vaf-hub** [comment]
### Test notes

- [ ] moving single and multiple mails in MailView still works fine and LockErrors and PreconditionFailedErrors are caught
- [ ] move a mail/ multiple mails during an active suspension for which we get a PreconditionFailedError response from the MoveMailService (if the mail is currently locked) and check that the error is handled and an error dialog is shown
