### ISSUE TITLE
Add bank transfer info

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#2905]
If payment via bank transfer is selected below the payment method we should show something like:
"It may take up to one week until the payment you made via bank transfer is shown here."

**Comment by vaf-hub** [comment]
Am I right that we need this for both Invoice and Sepa PaymentMethodTypes?

**Comment by armhub** [comment]
"Sepa" is direct debit which we do not support any more, so we just need the text for "Invoice" which is the normal bank transfer.

**Comment by vaf-hub** [comment]
### Test notes:

- [ ] If the current payment method is invoice the info text is shown below the text field for payment method selection. For other payment methods no info text is shown.
- [ ] During signup and in the dialog shown when changing the payment method (in the PaymentViewer), the info text for invoice payments now finishes with the same info text shown below the payment method text field
