### ISSUE TITLE
[android] enable moving the app to external storage sdcard

### ISSUE THREAD

**Issue by 1000283** [tutao/tutanota#2907]
The title is self-explanatory.
This helps prolong the usage of older unrooted smartphones since the system progressively hogs internal memory.

**Comment by johnbotris** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.

**Comment by 1000283** [comment]
And yet i see a lot of issues tagged as [improvements](https://github.com/tutao/tutanota/issues?q=is%3Aissue+is%3Aopen+label%3Aimprovement)? Weird double-standard.

**Comment by charlag** [comment]
Those are opened by us or were opened before we implemented this policy and we decided to keep them.
The app is 2Mb, it doesn't make much sense to move it around.

**Comment by 1000283** [comment]
Maybe not to you, but if you have an unrooted device most of the internal storage is gradually taken up by the system. 
Moving apps, however small, to external storage alleviates this.

**Comment by jowlo** [comment]
This was also asked for on [reddit](https://www.reddit.com/r/tutanota/comments/mmzt76/cant_move_the_android_app_to_external_storage_why/) (which would be the correct channel for this type of question/request). I have added some more info regarding the limitations there.
