### ISSUE TITLE
BadRequestError when editing imported calendar event

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2909]
We can get an unhandled BadRequestError from the PublicKeyService when trying to edit a calendar event that was imported from an .ics file. It's happening because there is an invalid value in the EMAIL field for a participant:

`ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=name;EMAIL=mail:mailto:mail`

We make a call to the public key service with the bad parameter  when resolving recipients in the sendmailmodel:

https://github.com/tutao/tutanota/blob/f47cf1e3993133749e438f4a9647f99d103aaa77/src/mail/model/MailUtils.js#L135-L140

We should handle the error and also either discard invalid recipient addresses when parsing calendar files or ignore them when initializing the CalendarEventViewModel

test .ics:
```
BEGIN:VCALENDAR
PRODID:-//Tutao GmbH//Tutanota 3.82.12//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
DTSTART:20210330T110000Z
DTEND:20210330T120000Z
DTSTAMP:20210325T163746Z
UID:id
SEQUENCE:0
SUMMARY:test
ORGANIZER;EMAIL=mail:mailto:mail
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;CN=name;EMAIL=mail:mailto:mail
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=name;EMAIL=mail:mailto:mail
END:VEVENT
END:VCALENDAR
```

**Comment by bedhub** [comment]
seem to be fixed with https://github.com/tutao/tutanota/issues/2975
