### ISSUE TITLE
Names of attendees are not quoted in serialized events

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2910]
Only CN of organizer is in quotes.
We cannot parse it back.

**Comment by johnbotris** [comment]
What's the issue here? It's parsing fine for me. The spec doesn't seem to require it either

**Comment by charlag** [comment]
Attendee with comma in name, we can't parse the invite then

**Comment by johnbotris** [comment]
# testing

- [ ] Attendee names in exported calendar events are surrounded in double quotes
- [ ] Calendar's with events whose attendees have commas, when exported, can be imported again
