### ISSUE TITLE
Short event with long title has title cut off vertically in event bubble

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2914]
![Screenshot from 2021-04-08 10-16-21](https://user-images.githubusercontent.com/22109738/113992664-fa101e80-9853-11eb-9d71-05cc602f6c22.png)

We should have the title render on the same line as the time and use `text-overflow: ellipsis`

**Comment by ganthern** [comment]
seems to work now, I can't reproduce it anymore.
