### ISSUE TITLE
[windows] scale / zoom factor resets after some time in background

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#2917]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
the windows client seems to forget to open new windows with the last scale/zoom factor after some time

**To Reproduce**
* open tutanota desktop
* zoom out with ctrl + mouse wheel 
* close the window, but leave client running in tray
* wait for about 10-15 minutes
* open new window
* see that the scale factor has reset to about 1.0
* try to zoom out again one level -> scale resets to previously set value and *then* zooms out further

**Expected behavior**
the scale factor should be maintained while in background

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Current Desktop Client (3.82.12)

**Additional context**
reported here: https://www.reddit.com/r/tutanota/comments/mhq4t1/zoom_is_constantly_resetting_on_win10_clientapp/
and reproduced in a Win10 VM

**Comment by ganthern** [comment]
related: https://github.com/electron/electron/issues/10572

**Comment by ganthern** [comment]
faster ways to reproduce:

* clear user data
* log in
* zoom in
* log out (the login page is shown in scale 1)

* log in
* zoom in
* quit tutanota
* start tutanota
* zoom out
* create a new window (this one is still zoomed in)

**Comment by mpfau** [comment]
@ivk successfully tested on win

**Comment by marcosdiasalves** [comment]
Facing this bug with MacOS desktop app v.3.122.5. When I open a new windows the zoom level is reset.
