### ISSUE TITLE
Dropdown stays open when clicked

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#2924]
This was introduced in the last release, it only effects usages of the old Dropdown, not DropdownN. If changes from #2559 would completely remove old Dropdown and are going to be included soon then we won't need to make a fix for this, otherwise I have a fix ready.

**Comment by johnbotris** [comment]
# testing

On instances of old DropDown:
- [ ] Clicking buttons in the dropdown still triggers the respective action, and the dropdown disappears
- [ ] Clicking away from the dropdown still causes it to disappear without triggering an action
- [ ] Clicking/typing in a text field in a dropdown will not cause the dropdown to disappear (eg. the country selector when creating a gift card)

- [ ] check that instances of DropDownN still behave as expected

**Comment by charlag** [comment]
It is probalby unrelated but instanced of the old dropdown do not focus on the field automatically while new ones do. We should just replace remaining usages.
