### ISSUE TITLE
Android: 'Download' embedded image opens, but does not save the image.

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#2925]
When the user long-taps an embedded image they are presented with a download option. The option will open the image, but does not save it locally.

**To Reproduce**
1. Long-tap an embedded image
2. Click on 'Download'
3. Choose which application should open the file (Photos, Files, etc)
4. If the image is then closed, it must be reopened from the email. It does not save a local copy to the device.

**Smartphone(s):**
 - Device: Pixel 3a, Nokia 7 Plus
 - OS: Android 11, Android 10
 - Tutanota 3.82.11

**Comment by johnbotris** [comment]
# testing
- [ ] long press of inline image attachment on android or ios will give the user and option to either download or open in another program
- [ ] right click on desktop will give the user the same options

**Comment by johnbotris** [comment]
Moving this to 3.83.2 milestone because this release won't include mobile apps
