### ISSUE TITLE
Missing panel icon on XFCE

### ISSUE THREAD

**Issue by cosminhume** [tutao/tutanota#2930]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When adding a launcher of the Tutanota desktop app on the XFCE panel, the icon is missing.

**To Reproduce**
1. Go to the XFCE applications menu
2. Start typing "Tutanota"
3. Find the app shortcut and right-click on it
4. Click "Add to panel"
5. Observe the new icon on the panel

**Expected behavior**
The Tutanota icon should be visible on the launcher.

**Screenshots**
The (placeholder of the) Tutanota icon is the one between the Emacs icon and the Firefox window:
![tutanota_launcher_icon](https://user-images.githubusercontent.com/42698386/114305921-cdbe0180-9ae2-11eb-8a33-4c221079665f.png)

**Desktop**
 - OS: Linux Mint
 - Desktop Environment: XFCE
 - Version: 20.1 Ulyssa, with XFCE 4.14

**Additional context**
I am using the AppImage from the website.
I tried a few other AppImage applications and they did not have this problem.

**Comment by charlag** [comment]
Hi
I'm pretty sure the problem is that the panel points to AppImage file which is not there anymore.
If I'm wrong and you have any other idea why only XFCE panel doesn't have it please let us know.

**Comment by cosminhume** [comment]
My launcher was in the file `~/.config/xfce4/panel/launcher-20/16181484184.desktop` and had the following content:

```ini
[Desktop Entry]
Name=Tutanota Desktop
Comment=The desktop client for Tutanota, the secure e-mail service.
Exec="/home/cosmin/apps/tutanota-desktop-linux.AppImage" %U
Terminal=false
Type=Application
Icon=tutanota-desktop.png
StartupWMClass=tutanota-desktop
MimeType=x-scheme-handler/mailto;
Categories=Network;
X-Tutanota-Version=3.82.17
TryExec=/home/cosmin/apps/tutanota-desktop-linux.AppImage
X-XFCE-Source=file:///home/cosmin/.local/share/applications/tutanota-desktop.desktop
```

The AppImage file was in place.
I searched for the icons:

```bash
$ find ~ -name 'tutanota-desktop.png'
/home/cosmin/.local/share/icons/hicolor/64x64/apps/tutanota-desktop.png
/home/cosmin/.local/share/icons/hicolor/512x512/apps/tutanota-desktop.png
```

I fixed the issue by removing the filename suffix for the icon:
```diff
7c7
< Icon=tutanota-desktop.png
---
> Icon=tutanota-desktop
```
