### ISSUE TITLE
Many events might be loaded at startup in parallel

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2941]
In this place we load all UserAlarmInfo's and then we load all corresponding calendar events one by one and in parallel.

 - We should not load calendar events in paralallel
 - We should group requests and not load events one by one
 - We should probably clean up UserAlarmInfo's after alarm happens

https://github.com/tutao/tutanota/blob/dbc0f1d62756bde9f835962c31b81f35a96dd767/src/api/worker/facades/CalendarFacade.js#L244-L274

**Comment by johnbotris** [comment]
# testing
- [ ] at login, events for alarms are loaded in groups by listId
