### ISSUE TITLE
Font color is not reset to black when white background is enabled

### ISSUE THREAD

**Issue by akaessens** [tutao/tutanota#2942]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web/desktop/android app** 

**Describe the bug**
When using the dark mode, sometimes there are emails with light grey font while the background remains white which makes it very hard to read. On Light mode its black on white. In my case this occurs (only) with the Stud.IP system emails. 

**Expected behavior**
Either full inversion (background + font) or not at all - but not only the font. As this only happens with this specific mails i suspect an issue in their formatting but this should be tolerated and not partially inverted.

**Screenshots**
Light mode
![image](https://user-images.githubusercontent.com/24660231/114763407-0966fe80-9d63-11eb-991f-68fa2dd4cf2d.png) 
Dark mode
![image](https://user-images.githubusercontent.com/24660231/114763711-66fb4b00-9d63-11eb-8eda-3a5a3ddf2ff4.png)

This happens not only in web app but also in desktop and phone.

**Comment by charlag** [comment]
Hi
Thanks for the report
Can you please check by right-clicking and inspecting the element where the color of text comes from? Should be visible in the right panel under class list

**Comment by akaessens** [comment]
Hi,

This is where it comes from:
![image](https://user-images.githubusercontent.com/24660231/114846698-3952e800-9ddd-11eb-8ef8-1735823ae76e.png)

Changing `#DDDDDD` to something else impacts the email text color as well as the text color of the list elements of all mails.

**Comment by charlag** [comment]
I see now how it happens.
They didn't change the text color, we did, because  we didn't detect colored text. Can you check where white background comes from? Maybe we can improve the detection.

**Comment by akaessens** [comment]
This unnamed `<div>` inside the mail body has a background porperty. Again - changing it did change background of the mail.
![image](https://user-images.githubusercontent.com/24660231/114888253-58676f00-9e09-11eb-91bf-6683b3f11233.png)

**Comment by charlag** [comment]
We enable white background color when we detect colored text but we don't reset font color I guess.
The right thing would be to do both, background color and font color.

**Comment by jowlo** [comment]
Well, actually add the class `content-black` here but it is not effecting the div apparently.
https://github.com/tutao/tutanota/blob/d614a047812c4fe07ae4cd1e4312ddc445e30d4a/src/mail/view/MailViewer.js#L329

Could you check whether that class is there on the outer div?
Or better yet paste or attach the (anonymized) HTML of that mail so we can try to reproduce this locally?

**Comment by akaessens** [comment]
@jowlo The entire HTML does not contain the `content-black` class.

This it what i get:
```
<div class="rel margin-are-inset-lr scroll-x plr-l pb-floating scroll-no-overlay ">
    <div style="line-height: 1.8; transform-origin: left top 0px;" id="mail-body"
        class="selectable touch-callout break-word-links">

        <div style="background-color: white; margin: auto; max-width: 700px; padding: 4px;">
            <img src="..."
                alt="Mail_header" style="max-width: 100px;">
            <p>
            </p>
            <div class="">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur suscipit urna a metus mollis, quis
                iaculis risus fringilla. Nunc aliquam.
            </div>
            <p></p>
            <hr>
            <span class="">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur suscipit urna a metus mollis, quis
                iaculis risus fringilla. Nunc aliquam. </span>
        </div>
    </div>
</div>
```
If you need more to reproduce it then i will forward you a mail, please let me know.

**Comment by jowlo** [comment]
> If you need more to reproduce it then i will forward you a mail, please let me know.
Yes, i guess that would make it much easier, thank you. Could you forward one of those mails to jow@tutao.de?

**Comment by jowlo** [comment]
Thanks to @akaessens i have a copy of the example mail now.
It turns out that white background does not come from us but is set on a div in the mail itself, however, no font color is set. Thus we do not revert to black on white but use dark mode style.

I would think the best way to deal with this is to just revert to black on white as soon as _any_ element has a `style:"background-color"` set.

**Comment by johnbotris** [comment]
# testing
- [ ] When an email triggers the contrast fix in dark mode, make sure that the font color is set to black
