### ISSUE TITLE
Remove old TextField

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2945]
See #2559

**Comment by johnbotris** [comment]
# Test notes

- [ ] Test Signup Form (including Captcha)
- [ ] Test all Whitelabel Settings
- [ ] Test Adding a custom domain + users
- [ ] Test Contact Viewer / Editor
- [ ] Test reattaching of TextFieldN works
- [ ] Test KeyManager
- [ ] Test EmailEditor
- [ ] Test ContactFormEditor
- [ ] Test login using second factor
- [ ] Test group management

**Comment by charlag** [comment]
SetDomainCertificateDialog does not work if the value was already there

**Comment by charlag** [comment]
SetDomainCertificateDialog is fixed by #3064
