### ISSUE TITLE
Calendar importer POSTs and GETs results one by one and quickly runs into limits.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2946]
As a user i am able to import my data like calendar events or contacts into my Tutanota account. These actions lead to a lot of POST and GET requests in a short amount of time and i quickly run into rate limit which enables the suspension state in the client. We need to reduce the amount of requests for such imports to avoid that clients are getting suspended/blocked.

**Acceptance criteria**
- [x] Backend: Extend DefaultListElementResource POST to accept and create multiple instances in one list. Return generated ids.
- [x] Backend: Write resources for ListElementTypes that do allow POST but should not allow POST of multiple instances.
- [x] Backend: If there is a resource for the ListElementType this must also implement POST of multiple instances if needed.
- [x] Backend: DefaultElementResource should NOT allow POST to accept and create multiple instances. 
- [x] Backend: Ensure that only one web socket notification will be send for creating multiple entities.
- [x] Backend: write instances in one batch. If an error occurs (even for one instance only) do not write the batch.
- [x] Backend: Limit number of entities that can be created in one request to avoid PayloadTooLarge errors and database overload.
- [x] Client: Handle errors to maintain a consistent state and inform users about failing imports.
- [x] Client: Use POST multiple for calendar import
- [x] Client: Use POST multiple for contact import
- [x] Client: Use GET multiple when processing web socket event (could be that it is already ensured by #2947)

**Implementation hints**
`CalendarEvent` and `Contact` types have POST visibility and instances can be created one by one from the client. The import is currently implemented in a way that it iterates through the data and does POST requests for each instance. Each POST from the client will also lead to a GET because the server defines the instance id and sends a CREATE event with that id. The `EventBusClient` will process the CREATE event and does a GET request for either updating `EntityRestCache` or updating the search index. For importing 100 contacts we will have 100 POST requests, 100 web socket notifications and 100 GET requests.

We already allow GET for multiple instance of the same type for all `ET` and `LET` that have GET visibility with the restriction for `LET` that they have to be from the same list.

There should be a similar interface interface for all  `LET` that have POST visibility which allows creating multiple instances in one request. 

**Additional Information:**
Backend issue is 894 but all the required information should be documented here.

**Experts:**
@armhub @mpfau @bedhub

**Test Notes:**
 Import a contact list and observe
- [ ] that it results in only one post and one get request per max. 100 instances
- [ ] that dialog displays correct number of successfully imported contacts and contacts are imported successfully
- [ ]  importing multiple contacts at once works
- [ ] open 2 clients and set one to offline. Import from the online clients. Observe that second client receives updates after going online again. Verify it works if the offline client has already opened ContactView and also if not (should show the correct contacts once you open it).

Import a calendar and observe that 
- [ ] it results in only one post and one get request per list (long and short events) and per max. 100 instances if no alarms are defined for the events (in the later case a higher number of get requests will be made). However in case multiple alarms are defined for an event, the event is only loaded once.
- [ ] Import a calendar with more than a hundred events per list and observer that several requests with 100 instances are made. Not that long and short events will be handled individually because they have different list ids.
- [ ] events are imported successfully
- [ ]  when trying to import events that already exist an appropriate error is displayed. Try both importing a file that only contains existing events and a file that contains some events that exist and some that do not. Verify that only the non-existing events are imported and the user is informed about the not-imported events.
- [ ]  importing multiple calendar files at once works
- [ ] open 2 clients and set one to offline. Import from the online clients. Observe that second client receives updates after going online again.
- [ ] when a calendar file contains events without uids import still works and uids are generated

Perform some regression testing for calendar as some refactoring has been made here:
- [ ] creating, updating, moving and deleting events with and without alarms and invitations

Test PushIdentifiers as a new Resource has been created
-  [ ] post still works (register new device and observe request)

**Comment by jowlo** [comment]
I was evaluating having a general REST interface that enables the creation (POST) of multiple instances (of the same type) at once. On the other hand, this is quite a bit more effort than just making a service that handles the calendar import after client side parsing.
Do you have a preference on this, @bedhub?

**Comment by johnbotris** [comment]
enabling POST of multiple instance would be beneficial for cases other than calendar imports and imo better than the alternative of creating a service every time we just need to create many entities at once.

**Comment by bedhub** [comment]
@jowlo I think for types were we have decided to create them from the client directly using POST requests we should also be able to create multiple instances of them. So i am in favor of adding a POST multiple for them. For types were we use services we have to create new services. Mainly i am thinking of importing emails and all the associated types like Mail, MailBody, File and FileData were POST multiple can not be used.

**Comment by jowlo** [comment]
@bedhub Yes, that is what we thought as well. OTOH, it looks like we will need it for importing only, so basically for calendar and mail instances. And, since like you said Mail can't be done generically, we might just implement a single service for multiple calendar imports in addition.

Do you see any more instances and use cases where this would be beneficial?

**Comment by vitoreiji** [comment]
> Client: Use GET multiple when processing web socket event (could be that it is already ensured by #2947)

Just to confirm: this was not implemented, and will be handled in #2947?

**Comment by vaf-hub** [comment]
> > Client: Use GET multiple when processing web socket event (could be that it is already ensured by #2947)
> 
> Just to confirm: this was not implemented, and will be handled in #2947?

No. Actually it WAS implemented. This means that for instance after importing a file with less than 101 contacts or calendar events without alarms you should only see a single GET request for this instance type after the import is finished. Can you confirm this behavior? (Before this change you would see at least one GET request per contact/event that was posted.)

**Comment by vitoreiji** [comment]
I noticed when testing the online/offline clients that when the client that was offline goes online, it does one GET request per contact. I can confirm that the client that did perform the import only does one GET request per 100 contacts, though.

**Comment by vitoreiji** [comment]
>  importing multiple calendar files at once works

When importing from multiple files the user is not informed of the number of events imported.

**Comment by vaf-hub** [comment]
> 

I think the same is true for just importing from one file unless there is an error. Can you confirm this. (Unlike contacts in the case of calendar importer we only show a message in case something did NOT work.)

**Comment by vitoreiji** [comment]
Oh, that's right, sorry. I should not be testing while sleepy...
