### ISSUE TITLE
Search / Suggestion result entities are loaded one by one

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2948]
Load entities after search in one request. It might be that this is not only related to suggestion but also to for regular search.

**Comment by vaf-hub** [comment]
I tried to reproduce this, but entities seem to be grouped by list id and loaded as one request per list. This happens with both QuickSearch and in SearchView. See  `_loadAndFilterInstances()` and `_downloadResults()`.

I am not sure how we can improve on this. @bedhub do you think we should load entities in different lists also in one request?

**Comment by bedhub** [comment]
Search in results in general are not affected. The issue is about contact suggestions in the mail editor. Suggestion results (Contacts) are loaded one by one.
