### ISSUE TITLE
Sidebar elements are not aligned and SidebarSection not used in all appropriate places

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2971]
The new Sidebar elements are not correctly aligned in the calendar view. The section heading has different negative margin left than the calendar-checkbox. Negative margin should be used to align those element properly. I suggest that the heading should never have a negative margin and the content rows should only have negative margin if necessary.

**Comment by vaf-hub** [comment]
I decided to cleanup the places where we use the SidebarSection a bit. So that we do not have so many places where (negative) margins and paddings are added. Also, I decided to use the SidebarSection where possible for instance in SearchView.

**Comment by vaf-hub** [comment]
**Test notes:**

- [ ] check that elements in the sidebar are always correctly aligned in all different views
- [ ] check for different screen sizes as the sidebar can vary in size
