### ISSUE TITLE
Improve error message for non-existent Tutanota recipient

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2974]
When sending a mail to a non-existing `@tutanota.com` address, the error message asks to "correct" the address. This is not very helpful.
Same error shows up when inviting non-existing attendees to a calendar event and trying to save that event. The contact exists in my contacts list just fine.

![Screenshot from 2021-04-23 12-46-38](https://user-images.githubusercontent.com/6842104/115861136-b5c77580-a432-11eb-9ae0-674da78e8276.png)

**Comment by elemesa** [comment]
On Friday, 23 April 2021, 11:52:35 GMT+1, Jonas Wloka ***@***.***> wrote:  
 
 


When sending a mail to a non-existing @tutanota.com address, the error message asks to "correct" the address. This is not very helpful.
Same error shows up when inviting attendees to a calendar event.

**Comment by vaf-hub** [comment]
As it turns out we use this error message for different cases. For instance when sharing calendars it is also shown if the user tries to invite a non-Tutanota address or if there is some text which is not a mail address left in the BubbleTextField when hitting the send button. I tried to distinguish those cases and show distinct and more understandable error messages depending on what caused the error.

**Comment by vaf-hub** [comment]
**Test notes:**

In the following, whenever testing for handling of non-exstisting Tutanota addresses, also test for an exsting custom domain address and a non-existing custom domain address!

- [ ] check that we display appropriate (more meaningful) error messages in all places we used to show the `invalidRecipients_msg`: MailEditor, Calendar Event (add guests), share a calendar
- [ ] leave text (that is no valid mail address in some recipient field in the MailEditor and press the send button)
- [ ] enter a non-existing Tutanota-address in a recipient field of the MailEditor and let it create a bubble
- [ ] leave a non-existing Tutanota-address in a recipient field of the MailEditor and hit send
- [ ] try adding a non-existing Tutanota address as guest to a calendar event
- [ ] share a calendar with a non-exsting Tutanota user
- [ ] share a calendar with an external user
