### ISSUE TITLE
UserAlarms are loaded each time

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#2977]
When logging in to the desktop client we load the list of UserAlarms and all associated CalendarEvents each time. This should not happen as we keep track of alarms in the native part of the desktop client. 

From a first look at the code we should prevent executing scheduleAlarmsLocally() when initializing CalendarModel after login for the desktop client.

**Comment by vitoreiji** [comment]
# Test notes

- [ ] Check on debugger that `CalendarModelImpl#scheduleAlarmsLocally` does not execute `loadAlarmEvents` on desktop app

**Comment by charlag** [comment]
You could also just check in network inspector that it doesn't download alarms and events
