### ISSUE TITLE
Darkmode Logout Flash on iOS

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#2988]
**Bug in mobile app**

When logging out of an iOS device in the dark theme there is a brief white flash on the screen before it returns to the dark theme.

**To Reproduce**
1. Set Account to Dark Theme
2. Log out
3. Quick Flash prior to returning to Dark Theme

**Smartphone:**
 - Device: iPhone 12 Pro Max
 - OS: iOS 12.5 and iOS 14.4.2
 - Version Tutanota 3.82.19

**Comment by charlag** [comment]
The reason is that we never invoke `changeTheme` from SystemApp. We need to save theme to native part for it to work smoothly.

see #3001

**Comment by charlag** [comment]
nvm, it's called dynamically from LoginViewController (or at least it should be)

**Comment by charlag** [comment]
This was fixed by #3132
