### ISSUE TITLE
To field is missing 

### ISSUE THREAD

**Issue by milachevalier** [tutao/tutanota#2993]
My browser (Safari MacOS Big Sur) is not displaying the To field in emails. When I click on a mail, it only has the From, subject line and timestamp fields. The To address only shows up when you click on show more. I only signed up for a Tutanota premium subscription for the additional aliases but because it doesn't show which alias I'm receiving the mail it is very difficult to use.

Should I be using a different browser?

**Comment by charlag** [comment]
Hi
No, we do not show to which address email is received unless you expand the details. We might change it later but its not planned yet.
