### ISSUE TITLE
Add a blue theme

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#2998]
Add a blue theme that will be default for new signups for a week.

## Test notes
 * There should be another blue theme available in the settings
 * When going to `/signup#theme=blue` the blue theme should be selected automatically
 * All areas should look consistent color wise
 * Check that everything still looks nice with whitelabel colors applied
 * Check that the logo is using correct colors in different themes (also in the about dialog)

**Comment by AdamWysokinski** [comment]
Great. Now we need Dark Blue theme :)
