### ISSUE TITLE
Limit iterations of recurring events

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#2999]
We should add safeguards like we have for long events to prevent repeating events from freezing the app. We should limit the number of iterations.

**Comment by vaf-hub** [comment]
Do you think we should have hard limits and not even allow users to create or import such events or should we just sanitize how they are displayed/ loaded?

**Comment by charlag** [comment]
Test notes:
 - [ ] Check that short one-time events still work
 - [ ] Check that recurring events still work
 - [ ] Check that long events still work
 - [ ] Check alarms on web or desktop

**Comment by Pa7Hub** [comment]
Creating an event from today to a few years and making it repeat daily will sometimes crash the app or make it very unresponsive

**Comment by johnbotris** [comment]
This issue already has a merged fix that was tested and included in a previous release

**Comment by charlag** [comment]
@johnbotris And yet it did not work in the situation @Pa7Hub has found?

**Comment by charlag** [comment]
I see new #3193 now
