### ISSUE TITLE
Getting notifications for ruled messages. 

### ISSUE THREAD

**Issue by dynamiclynk** [tutao/tutanota#3004]
When you have emails that go to curtain folders based on rules you are notified for every email instead of just the ones in the Inbox (hundreds of notifications in a short period).

**Expected behavior**
Only received notifications for Inbox or at least allow opt-out for ruled emails.

Personally I had to disable app notification because it became useless it became the email that cried wolf.

**Smartphone (please complete the following information):**
Android 11 (Pixel 4XL)

**Comment by johnbotris** [comment]
this is a duplicate of #1095, the final comment in that thread still applies.
