### ISSUE TITLE
Make theme handling easier to use

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#3005]
Right now, creating or changing a theme takes alot of annoying steps through theme.js and deviceConfig.js, f.e. saving is only handled separately so you have to invoke it twice, some things are also hardcoded. 
We should change the theme model to be more straight forward to use.

**Comment by johnbotris** [comment]
# testing
- [ ] Theme handling is A-OK
- [ ] settings themes
- [ ] saving theme in local storage
- [ ] check test notes of #3046 and #3030

**Comment by johnbotris** [comment]
Some errors with theming, see comments on #3030
