### ISSUE TITLE
Use system preference for light/dark theme

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#3006]
## User story
As a user i want the default theme of the Tutanota app to follow the system preference so that I don't have to think about changing the tutanota theme when the system theme changes

## AC
* (mobile) When the app starts, the splash screen should be shown in the selected theme
* there is an option to use the system theme in the appearance settings
  * if the current theme is light, we use the red light theme
  * if it's in dark/night mode, we use the dark theme
  * if no theme is persisted we use the system default theme
* themes are only persisted if the decision was explicitly made
* persisted themes are kept (no change to the setting if there is something stored)
* if the system preference setting is used, we check the theme when the app receives focus
* on desktop, after the theme change is detected, there is no flash of the previous theme even on windows that were in the background
* the theming of whitelabel domains stays as it is

## Test notes
Each test on web, desktop, iOS, Android

 - [ ] Regression testing for normal dark/light themes
 - [ ] Regression testing for whitelabel editor
 - [ ] Regression testing for whitelabel theme
 - [ ] Test that when "system" preference is set, dark/light is picked up correctly on startup
 - [ ] Test that when "system" preference is set dark/light is changed together with the system
 - [ ] Check that "system" is the new default for fresh installations

## Notes
Usually the mobile operating systems provide an option to set a system light or dark mode. We want to pick up that setting and update the Tutanota theme according to that configuration. 

Operating systems also provide a setting that light/dark  theme selection changes depending on time. We don't know yet what is the best option to synchronize the theme in that case. The idea is to check the setting each time the app receives focus (put to foreground)

## Original comment
I do not use the forum so I will try to write here. I hope they will understand me. 

In Tutanota there is a light and dark theme, it would be great if you could configure the function in the settings so that the themes change automatically depending on the time on the computer or the user's time zone. 

Thanks.

**Comment by jowlo** [comment]
For web client see [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by jowlo** [comment]
I think we should not switch between light and dark mode based on the system time but only based on system preference.

At least for android i know that it is quite easy to switch the system wide dark/light preference based on time (or sunset) and we would then change in the app as well.

**Comment by xbvrhlmb** [comment]
in Android, this does not work quite correctly. (for example, when in Europe at 7 pm in the winter, a light theme works and it's already dark outside) in the summer, this works fine

In addition, it will not work well on older versions of android

**Comment by charlag** [comment]
You can configure in your system when its daytime and when it's not. We should not implement our logic, I agree completely.

**Comment by rightsaidfred99** [comment]
I'd hope this would be a simple addition to ad!

Majority of apps and websites now support automatic switching of day and night mode based on system prefs. 
Surely this would be like a few lines of code as already the backbone of the day and night theme is there!

Would be a good update and easy one :)

**Comment by charlag** [comment]
@rightsaidfred99 I also want to have it but it's more complicated than a few lines. We need a new preference value for selected theme and we need to have detection in the native part of each app.

**Comment by rightsaidfred99** [comment]
> @rightsaidfred99 I also want to have it but it's more complicated than a few lines. We need a new preference value for selected theme and we need to have detection in the native part of each app.

I don't understand, isn't a web interface so basically CSS? Why would it not be possible to use this then have the Tutanota default UI as white and default dark UI as the dark ui? 

[prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by charlag** [comment]
We do generate css programmatically so it's not as easy as just applying a bit of CSS.

In addition we have:
 - 2 light themes
 - whitelabel themes (which are handled in web and apps)
 - whitelabel theme editor (which applies the theme only whilte editing)
 - mobile/desktop apps (which also make use of colors although this could be changed slightly but they also need to use *some* system API to query dark theme status)
 - we need to introduce another preference, codify it into UI and change our already not so simple theming model

This is a desirable feature but it's not three lines, it never is.

**Comment by bufothefrog** [comment]
In some other applications (also Electron) the selection of system theme in the theme menu defaults to the regular light/dark theme (which imo is a good enough v1) or allows you to choose two separate ones for light/dark.

**Comment by Magical898** [comment]
Can you also apply dark css for the content of the email (similar to darkreader browser extension)? 
Html emails are often sent by companies and those burn eyes because there is no dark mode.

**Comment by WannabeSmith** [comment]
Any update on this one? Most Android/iOS apps automatically adapt to the system theme, and it'd be great to not have to switch the theme manually each day.

Thanks to the devs for all that you do! ❤️

**Comment by charlag** [comment]
It is scheduled so hopefully it's not too far

**Comment by kibhub** [comment]
Login on Android is randomly stuck at "offline" for about 5s

**Comment by jeremiah-miller** [comment]
On Linux, where does tutanota read the preferred theme? I switch to dark mode with 
```
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark
```
but tutanota doesn't seem to respect the theme. Is there something else I should set? I skimmed the code but must've missed how it actually gets the theme

**Comment by ganthern** [comment]
If you haven't already, you also need to set the "System" option in Settings -> Appearance -> Switch Color Theme, then it should work.

**Comment by jeremiah-miller** [comment]
Yep, it's set to "System"

**Comment by ganthern** [comment]
that sounds like a bug then. the relevant code for the preference is in the ThemeController.ts file for the web renderer and the DesktopThemeFacade.ts for the native side of the equation. If you can make an issue with your setup and repro steps, we'll take a look at it.

**Comment by jeremiah-miller** [comment]
Created #5886
