### ISSUE TITLE
Shortcuts are listed multiple times in help

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3008]
After hitting <kbd>F1</kbd> to see the shortcut help, some key (combinations) are listed multiple times. They should only appear once.

![Screenshot from 2021-05-03 10-41-03](https://user-images.githubusercontent.com/6842104/116857175-ab5c6700-abfc-11eb-9cfd-c5069ad134cb.png)

**Comment by johnbotris** [comment]
the keybindings are different though, but maybe we could list multiple bindings on a single entry per action

**Comment by jowlo** [comment]
How are they different? I mean, each block of 2 makes sense (as they are different), but there should not be 3 (red) blocks, right?

**Comment by johnbotris** [comment]
oh oops, I didn't read it properly

**Comment by johnbotris** [comment]
# testing
- [ ] Shortcuts are not duplicated in the MailViewer after switching to and fro
- [ ] Shortcut functionality still behaves correctly in general (regression testing)
