### ISSUE TITLE
Desktop app fails to quit completely

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3012]
>does not close any more. When I klick the exit button in the lower left corner, my folders disappear and only the default folders (such as Inbox, Sent, Trash, ...) remain. The window will not close.

>Bei mir laufen oftmals drei Prozesse "tuanota-desktop" weiter nachdem ich die Desktop-Anwendung geschlossen habe. Ich bemerke das daran, daß der Lüfter meines Rechners laut wird. In der Prozeßliste sehe ich dann die "tutanota-desktop"-Prozesse, die zusammen über 100% Prozessorlast erzeugen. Wenn ich sie mit kill abschieße, wird der Lüfter wieder leiser.

**Comment by ganthern** [comment]
I'm failing to reproduce this on Windows & Ubuntu atm, it would be useful to know the platform and how the client is configured wrt running in background/running on startup.
