### ISSUE TITLE
Add Ctrl+Enter shortcut to send mails

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3023]
Use common <kbd>Ctrl</kbd>+<kbd>Enter</kbd> shortcut to send mails from the editor directly.

**Comment by jowlo** [comment]
## Test notes
 * [ ] Send a mail via <kbd>Ctrl</kbd>+<kbd>Enter</kbd> from the mail editor
 * [ ] <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd> still works as well
 * [ ] Feel good :small_airplane:

**Comment by johnbotris** [comment]
I feel OK at best but I'll take it

**Comment by olof-nord** [comment]
[x]  Feel good small_airplane

nice!
