### ISSUE TITLE
Gift card redeem country mismatch confirmation is unclear

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3024]
We show the error message "This gift card is only valid for use in x but we have detected that you are in y" in a confirm dialog if the countries do not match. It is hard to understand that a click on "Ok" will just accept the gift card country for the account and successfully redeem it. We should add a sentence like "Please confirm if {1} is your country." to the message.

**Comment by jowlo** [comment]
Updated on phrase to say
> This gift card is only valid for use in {valid} but we have detected that you are in {actual}. Please confirm that you are using this gift card in {valid}.
