### ISSUE TITLE
Slow Indexing, Slow search

### ISSUE THREAD

**Issue by europound** [tutao/tutanota#3025]
When are you going to make a proper desktop client with auto sync offline db?

https://www.reddit.com/r/tutanota/comments/n6pmhx/quick_search_emails/

**Comment by jowlo** [comment]
Sorry @europound, but this issue is not a bug report. It is also not a real feature request which this would be the wrong place to put anyways. Please ask for new features or improvements on reddit, like you did. Our github repository is for posting actual bugs and we need to keep it manageable.
