### ISSUE TITLE
[Feature Request] Add option to format date/time — in the front-end

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#303]
Currently, on the section where we see an "excerpt" of the e-mails (namely: sender, subject, date) the date/time is in **24 hour** format, on the section where the actual e-mail is displayed, it's in **12 hour** format — see the text highlighted in yellow.

![Date/Time Issue](https://user-images.githubusercontent.com/34633617/36082658-70a866ea-0f79-11e8-96c0-71a8fc15ba6a.png)

It would be better to be consistent on that matter. Furthermore, it would be nice if we can have the option (somewhere in the **Settings**) to select between the **12** or **24** hour formats.

**Comment by charlag** [comment]
I'm sorry I didn't notice this but this is a duplicate for #1357
