### ISSUE TITLE
Cannot start desktop client: ReferenceError: Cannot access 'customTheme' before initialization

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3030]
https://github.com/tutao/tutanota/blob/2cf8d85de76895a30873bcdb8ab6dbe9476abe9d/src/gui/theme.js#L242-L248

`getTheme` depends on `customTheme` so we need to change the order of initialization

**Comment by johnbotris** [comment]
# testing
- [ ] Themes are updated correctly
- [ ] Themes are saved and remembered correctly
- [ ] Custom themes aswell

**Comment by Pa7Hub** [comment]
- changing colors under **Whitelabel > Custom colors** will not change the preview accordingly

![Screenshot from 2021-05-20 11-21-18](https://user-images.githubusercontent.com/70587561/118954130-c26db980-b95d-11eb-935d-1e1613041990.png)

- when a custom theme is applied, it will change the localconfig to _'themeId: custom'_ , but does not remove it when no whitelabel colors or logo are selected, the theme selection under Appearance settings are also not rendered anymore, so the user is stuck in 'custom'

**Comment by johnbotris** [comment]
> changing colors under Whitelabel > Custom colors will not change the preview accordingly

That's existing but I can fix it anyway

**Comment by johnbotris** [comment]
# testing

- [ ] client doesn't get stuck in "custom" state after editing custom theme
