### ISSUE TITLE
Change icon when deleting on mobile from 'archive' to 'trash'

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#3037]
When swiping a mail to the left on mobile, it will show 'delete' alongside an 'archive'/'folder' icon. A trash icon would fit better, since the action is 'delete' and not 'move to trash' (or anything the like).

**Comment by mpfau** [comment]
test notes
- [ ] Verify that the trash icon is displayed in case of left swipe on the mail list
