### ISSUE TITLE
Make external warning dismissing on mobile more explicit

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3042]
With #147 the banner on mobile changed to be just a big button but there's no indication that you can tap on it to dismiss it.

**Comment by jowlo** [comment]
Do you mean we should make it clear that it is actually a button? I don't see how to _dismiss_ it as in _do not put on the allow list and also do not show the button anymore_...

**Comment by jowlo** [comment]
Is #3146 a more elaborated version of this?

**Comment by bedhub** [comment]
We will change the banner with #3146. Haven't seen this one.
