### ISSUE TITLE
No email notifications on desktop and android

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3051]
On android the notification simply doesn't occur (battery optimisation is off, the notification service is running), on desktop I get a notification but the message is "failed to handle PushMessage". Event reminders are still working on android, but not on desktop (#2931)

**Comment by johnbotris** [comment]
possibly related to #2858

**Comment by charlag** [comment]
This is a server issue (666)

**Comment by johnbotris** [comment]
# testing
- [ ] Notifications are shown when receiving mails
- [ ] Desktop
- [ ] Android
- [ ] iOS
