### ISSUE TITLE
Version update notification dialog UI broken

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3052]
**Bug in web app**

**Describe the bug**
The "new version available" dialog is missing background, buttons and has wrong page alignment for some window widths.

![Screenshot from 2021-05-14 11-10-59](https://user-images.githubusercontent.com/6842104/118249321-96f25700-b4a5-11eb-858d-0cdf02408c3d.png)

**Comment by charlag** [comment]
I believe this is fixed now
