### ISSUE TITLE
Permit selection of german language file (du/sie) for whitelabel customers with german language preset

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#306]

**Comment by armhub** [comment]
- In the contact form editor the language "Deutsch (Sie)" can still be added which does not make sense any more.
- The selection in the whitelabel settings should be "Deutsch (du)" instead of "Deutsch"

**Comment by armhub** [comment]
Contact form language is "de" when "de" is available in browser languages, whitelabel language is Deutsch (Sie) and "de" is configured in contact form.
