### ISSUE TITLE
Problems with setting Tutanota as mailto handler in Windows

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3075]
* When you set Tutanota as the default mailto handler in windows, this isn't shown in the default apps settings of Win10 (it will remain as Mail, or whatever it was already set to). If you set the default mailto handler to firefox (from the default apps settings), then when following a mailto link, firefox will prompt to select a handler. Tutanota will not be listed here, and you have to manually select it as a handler from this dialog.

* When running the client from a normal cmd/powershell with -r or -u flags, we don't try to elevate, don't give any indication it would require it, and nothing actually happens. I'm not sure that this is even a feature that we need to have. Is it documented? Powershell also gets confused and doesn't update it's prompt.

**Comment by charlag** [comment]
You are not suppoesd to run the app with -r or -u flags, it is done from the DesktopSettings UI

**Comment by johnbotris** [comment]
> You are not suppoesd to run the app with -r or -u flags, it is done from the DesktopSettings UI

That's my point, it's possible and I don't see why it should be

**Comment by ganthern** [comment]
IIRC it was because we can't elevate a running process and it's easiest to use the app itself instead of a separate registry writer executable. 

#3155
