### ISSUE TITLE
overlay elements flicker upon creation

### ISSUE THREAD

**Issue by vaf-hub** [tutao/tutanota#3079]
We use `displayOverlay()` to show different overlays (e.g. search(Ctrl+F) in the desktop client: or the notification overlay).
When the actual element is attached to the dom it flickers. This is because it is displayed in its final state briefly before the `createAnimation` is called (which might for example move it in from outside the screen).

We should fix how animations work in such cases. It might be that we have similar problems in other places.

## Test notes
On desktop:
- [ ] Search bar can be opened with `Ctrl+F`
- [ ] Search bar can be closed

On iOS:
- [ ] Snackbar appears fine

**Comment by charlag** [comment]
While search bar can be opened it is very very jittery

**Comment by charlag** [comment]
Oops my bad it was actually current version
