### ISSUE TITLE
Show monthly prices at signup

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3087]
Instead of showing the yearly price for a yearly subscription we should show the monthly price instead. This allows direct price comparison between monthly and yearly subscription.
We need to check if we should add something like "per month, billed yearly" for the yearly subscription.

Must be done for website and app.

**Comment by vitoreiji** [comment]
# Test notes

- [ ] Sign up and Upgrade wizards, plan selection page:
    - [ ] prices are shown monthly, even for yearly subscription
    - [ ] payment interval hint ("per month...") not shown for free plan
- [ ] Sign up and Upgrade wizards, confirmation page:
    - [ ] the yearly amount is shown for yearly subscription, and monthly for monthly subscription
    - [ ] "(net)" is shown for business plans, "(incl. taxes)" for private
- [ ] On yearly Premium account, monthly prices are shown for:
    - [ ] Settings => Subscription => Storage capacity
    - [ ] Settings => Subscription => Email aliases
- [ ] Gift card buying wizard, "per month" is not shown
