### ISSUE TITLE
Mark as Spam button not appearing // Mozilla Firefox 78.6.1esr

### ISSUE THREAD

**Issue by clort81** [tutao/tutanota#3090]
After exhaustive search, I did not find a way to block spam senders.  
The optimal place to expose this function would be in the email actions dropdown [screenshot]
![no_mark_as_spam](https://user-images.githubusercontent.com/51511737/119271429-c4f03d80-bc01-11eb-8a00-0110177477f0.png)

**Comment by charlag** [comment]
If you want to report as spam then "report this email" button will do the trick.
If you want to block the sender, expand "show more", click on sender and use "add spam rule" button.
