### ISSUE TITLE
Polling updates?

### ISSUE THREAD

**Issue by mycorrhizas** [tutao/tutanota#3091]
I have been using the desktop app on OSX for a while now. However, more often than not it is slow to update when a new email arrives. I often hear the notification on my phone and on my local machine but have to wait for the Desktop UI to refresh with the new information. I am not sure if this is a UI issue or network issue? 

Does the desktop poll and then notify before pulling the information?

**Comment by charlag** [comment]
Hi. This is the wrong place to ask questions, Reddit or at least [discussions](https://github.com/tutao/tutanota/discussions) might be a better place.
Desktop does not poll, there's a websocket connection. If you don't see a striped bar on top of your screen it means that you are connected. If it is slow it is either the network issue or rate limiting.
