### ISSUE TITLE
Custom domain wizard asks for mail address when navigating pages

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3094]
**Bug in web app**

**Describe the bug**
When going back to step 2 after step 3 (using the numbers up top) in the custom domain setup wizard and trying to continue, a user is forced to enter an email address on the new domain even if there are already some aliases registered from being on this page before. Those addresses are listed correctly but an error dialog with "Please enter mail address." is shown.

We should check if a user had entered mails on the page before and proceed with the setup accordingly.

![Screenshot from 2021-05-25 11-25-54](https://user-images.githubusercontent.com/6842104/119473994-0260e200-bd4c-11eb-8599-f837d90bdb97.png)

**Comment by ganthern** [comment]
not happening anymore
