### ISSUE TITLE
Security warning when trying to login

### ISSUE THREAD

**Issue by 13r0ck** [tutao/tutanota#3107]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
When loading /login I am presented with a security error

**To Reproduce**
1. /login on firefox (maybe just linux)

**Expected behavior**
No Error

**Desktop (please complete the following information):**
 - OS: Fedora 33
 - Browser Firefox
 - Version 88.0.1

**Additional context**
```
Feedback v3.83.7 - SecurityError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.83.7
 Timestamp (UTC): Tue, 25 May 2021 15:22:22 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
SecurityError
 Error message: The operation is insecure.
Stacktrace: 
execute/</<@https://mail.tutanota.com/app.js:1:115397
execute/<@https://mail.tutanota.com/app.js:1:116054
l@https://mail.tutanota.com/polyfill.js:1:81787
n</e.exports<[22]</e.exports/H.prototype._settlePromiseFromHandler@https://mail.tutanota.com/polyfill.js:1:54790
n</e.exports<[22]</e.exports/H.prototype._settlePromise@https://mail.tutanota.com/polyfill.js:1:55590
n</e.exports<[22]</e.exports/H.prototype._settlePromise0@https://mail.tutanota.com/polyfill.js:1:56289
n</e.exports<[22]</e.exports/H.prototype._settlePromises@https://mail.tutanota.com/polyfill.js:1:57641
f@https://mail.tutanota.com/polyfill.js:1:9215
u@https://mail.tutanota.com/polyfill.js:1:9155
n</e.exports<[2]</s.prototype._drainQueues@https://mail.tutanota.com/polyfill.js:1:10098
s/this.drainQueues@https://mail.tutanota.com/polyfill.js:1:8896

```

**Comment by johnbotris** [comment]
Thanks for the report. Have you made any changes to Firefox's security settings or to `about:config`?

**Comment by johnbotris** [comment]
It happens when Firefox has "Delete cookies and site data when Firefox is closed" enabled: https://github.com/gatsbyjs/gatsby/issues/16076#issuecomment-558959071

**Comment by johnbotris** [comment]
# testing
- [ ] When opening the client in a firefox based browser "Delete cookies and site data when Firefox is closed", no unhandled exception is thrown (you can confirm this by checking the console)

**Comment by 13r0ck** [comment]
Yes you are 100% correct!
Is there anything that can be done about this?

**Comment by johnbotris** [comment]
@13r0ck You could add mail.tutanota.com as an exception, but besides that I don't think so. I fix will be in the next release however, most likely next week.

**Comment by 13r0ck** [comment]
Awesome thanks!!!

**Comment by JuanRomanoChucalescu** [comment]
Oh thanks! I had not seen this post. 
Indeed, with the parameter: Delete cookies and site data when Firefox is closed = "off", it works normally.

I just have 2 questions:
- By remaining on "on", can I connect anyway (securely)?

- Doesn't the solution to add mail.tutanota.com reduce security (identification by the exception list)?

Sorry if my english is approximate, i'm french, but i love tutanota! Thank you team

**Comment by lucknaumann** [comment]
[**@13r0ck**](https://github.com/13r0ck) commented on [May 26, 2021, 10:13 AM MST](https://github.com/tutao/tutanota/issues/3107#issuecomment-848956912 "2021-05-26T17:13:33Z - Replied by Github Reply Comments"):
> Yes you are 100% correct! Thanks!  
> Is there anything that can be done about this while leaving "Delete cookies and site data when Firefox is closed" on?

Using a Private Window works.

**Comment by jowlo** [comment]
Works fine, somehow i am unable to add the tested label though.

**Comment by AngelosNaoumis** [comment]
This is happening again on new domain app.tuta.com

while on https://mail.tutanota.com/ it is super fine.
