### ISSUE TITLE
Preshared password field doesn't show up in the contact editor for new contacts

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3112]
The preshared password field only shows if the contact already has a password set:

https://github.com/tutao/tutanota/blob/4f84c07ac48d9eb396c48af544e624283a8d9efc/src/contacts/ContactEditor.js#L420-L423

Meaning you can't sent set a password for a contact upon creation. This was introduced during the UI component refactoring.

**Comment by jowlo** [comment]
Moved from 3.84.0 to 3.84.1 because this does not affect sending mails to contacts from the mail editor but only contact viewer.
