### ISSUE TITLE
White Background in Dark Mode

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3117]
When the mail client is set to dark mode, the email body appears with a white background, rather than the dark background.

** Desktop & Mobile **
 - Windows 8.1, Android 9, iOS 14.5
 - Desktop Client, Web Client, Mobile Applications
 - Version 38.3 (Desktop), 3.82.18 Android.

**Comment by jowlo** [comment]
... should say _colored text or elements with background color_ because we cannot ensure the contrast between text and background and then fallback to the colors of the mail itself. And mails usually assume white background.

**Comment by jowlo** [comment]
If there is no specific case where we apply our contrast fix (reverting to black/colored on _white background_) although it is not needed, we should close this.

**Comment by jowlo** [comment]
Feel free to reopen if you have such a case.
