### ISSUE TITLE
Mailbody flickering even when already loaded

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3120]
When switching between mails in the mailview, the mailviewer will flicker each time, by showing a loading spinner for a frame before the content is attached, it looks pretty ugly. If the mailbody has been loaded already we should be able to avoid this somehow.

**Comment by charlag** [comment]
Is it caused by delay of mailbody rendering?

**Comment by jowlo** [comment]
> Is it caused by delay of mailbody rendering?

Nope, it is the same before c03d671a9d93c803943fdb9dc316ee8265c1ec4b (and 5d49c95b7dd0a08220d85ff9d01442137da3cb5d).

**Comment by johnbotris** [comment]
# Test notes
- [ ] Progress spinner doesn't show for mails that have already been loaded
- [ ] Progress spinner does show for mails that are being loaded
 * Try to test with mails that load quickly and ones that load slowly

**Comment by ganthern** [comment]
Still showing the spinner when switching back & forth between two mails.
