### ISSUE TITLE
Simple mode for whitelabel color chooser

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3124]
As a user I want to have an easier way to change my custom colors for the whitelabel theme. I want to define one accent color  for the theme but right now i have configure five different values to apply a new accent color. I just want to change one value and it should change all the places were that color is used. 

I also prefer to use a dark or white theme so this selection should also be changeable with just one selector.

I like to have a preview of what colors are actual changing which shows some UI components that are affected 

All other color definitions  should be hidden by default behind an expander button. If the other colors are visible they should be grouped so it is easier to identify which section of the application is modified.

**Acceptance criteria**

- [x] User can select only one accent color
- [x] User can choose between dark/light theme as a base theming
- [x] Preview of some components is displayed.
- [x] Introduce color picker for all the colors that can be defined
- [x] Hide other color definitions by default
- [x] Group color definitions by area were they are used (header, navigation column, list column, content coloum)

**Implementation hint**
It would be preferable if the preview would be a real preview component which is independent from the colors of the application. We discussed options to implement such component but it would either require to refactor how the theme is applied in the application (in order to use existing component for preview)  or we need to create a custom component and do the color mapping again. We then would have keep the mapping of colors in sync. 

We discussed with @charlag @bedhub @Pa7Hub  and decided against using a custom preview component. We will instead use our existing components and switch all colors of the application. The user can always cancel the edit dialog and this will reset the changes.

**Comment by Pa7Hub** [comment]
Some things to clarify and discussed with @charlag @bedhub @Pa7Hub 
1. Should selecting a different base theme also set new values to the advanced colors
     -- No, changing the base theme should change the default color and not override existing customizations
2. Which base theme should be the choosen if we open editor.
   -- When there is a base on the ThemeCustomization we should pre select that. If there is no base defined yet we will fallback to the light base.
3. What do we want to save. A fully defined Theme or just the customizations?
    -- On the server we right now just store the customizations and we want to keep that behavior. We will add a base theme id as an additional refrence into the JSON object. Therefore we change the TypeDefinition for what is stored on the server to ThemeCustomization. When applying or if we save the them to the native storage we want a fully assembled Theme definition. A base theme reference is then not required because all values are set.
