### ISSUE TITLE
Feedback v3.84.0 - SecurityError - UNKNOWN - Browser

### ISSUE THREAD

**Issue by lyrebird-sound-cloning-system** [tutao/tutanota#3130]
**Describe the bug**
This message appears:
```

Feedback v3.84.0 - SecurityError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.84.0
 Timestamp (UTC): Fri, 28 May 2021 03:15:06 GMT
 User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
SecurityError
 Error message: The operation is insecure.
Stacktrace: 
execute/</<@https://mail.tutanota.com/app.js:1:115362
execute/<@https://mail.tutanota.com/app.js:1:116019
l@https://mail.tutanota.com/polyfill.js:1:81787
n</e.exports<[22]</e.exports/H.prototype._settlePromiseFromHandler@https://mail.tutanota.com/polyfill.js:1:54790
n</e.exports<[22]</e.exports/H.prototype._settlePromise@https://mail.tutanota.com/polyfill.js:1:55590
n</e.exports<[22]</e.exports/H.prototype._settlePromise0@https://mail.tutanota.com/polyfill.js:1:56289
n</e.exports<[22]</e.exports/H.prototype._settlePromises@https://mail.tutanota.com/polyfill.js:1:57641
f@https://mail.tutanota.com/polyfill.js:1:9215
u@https://mail.tutanota.com/polyfill.js:1:9155
n</e.exports<[2]</s.prototype._drainQueues@https://mail.tutanota.com/polyfill.js:1:10098

```
**To Reproduce**
1. Open mail.tutanota.com to make a login attempt.

**Expected behavior**

**Screenshots**
![Screenshot_2021-05-28 Mail Done Right Tutanota Login Sign up for an Ad-free Mailbox](https://user-images.githubusercontent.com/84561213/119924762-913b4d80-bf4a-11eb-8597-171015dc7cdc.png)

**Desktop (please complete the following information):**
 - OS: KDE Neon 5.21.5
 - Browser: Firefox: 88.0.1
 
**Additional context**
N/A

**Comment by lyrebird-sound-cloning-system** [comment]
Oops, I chose the wrong template (desktop instead of web) D:

**Comment by JuanRomanoChucalescu** [comment]
I have the same bug.

![error](https://user-images.githubusercontent.com/51752708/119929546-070cdc80-bf7e-11eb-8195-d606f21f198d.png)



Desktop: Windows NT 10.0; Win64; x64; rv:88.0
Browser: Firefox/88.0

Additional context: 
No connection problem from another machine.

**Comment by johnbotris** [comment]
Duplicate of #3107

**Comment by AngelosNaoumis** [comment]
This is happening again on new domain app.tuta.com
