### ISSUE TITLE
Calendar events are not loaded for part of this/next month until the date is changed on some dates

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3136]
**To Reproduce**
1. Pick a date at the end of the month. Let's say 2021-5-31
2. Create an event on the next date, like on 2021-6-1
3. Open calendar directly on the picked date so that URL is /calendar/month/2021-05-31
4. See that the event we created is not loaded

**Expected behavior**
Event is loaded

v3.84.0

**Comment by ericmjones** [comment]
Thank you, I noticed this today @charlag

**Comment by charlag** [comment]
Correction: it must be actually 31st because the first date to load depends on the current date.
