### ISSUE TITLE
Control + Enter to "Send" is not listed under the F1 Shortcut Menu

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3141]
If users hit "ctrl + enter" emails will send, but this shortcut is not listed in the keyboard shortcuts menu in the desktop client. Although the shortcut is not listed here, it is live. Users have reported accidentally sending draft emails because of this.

1. Click F1
2. ctrl + enter is not listed
3. Create a new email draft
4. Click control + enter > Email will be sent.

** Desktop Environment **
 - OS: Ubuntu
 - Desktop Client Linux
 - Version 3.84.0, 3.83.7

**Comment by jowlo** [comment]
Actually, <kbd>Ctrl</kbd>+<kbd>Enter</kbd> is listed for me the same on web and on the desktop client. It is hidden between two more "Send" shortcuts...

**Comment by brshub** [comment]
> Actually, Ctrl+Enter is listed for me the same on web and on the desktop client. It is hidden between two more "Send" shortcuts...

Ah I missed it. I wasn't looking while having a draft tab open. I will close this issue.
