### ISSUE TITLE
"Create Contact" from email header does not load beyond a blank screen

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3142]
When opening an email and clicking on the sender's address the option "Create Contact" does not load. It simply hangs on a blank loading screen with the sender's name at the top.

**To Reproduce**
1. Open an email and click "show more".
2. Click on the sender's address and choose "Create contact"
3. Window opens but remains blank.

**Expected behavior**
The window should open and allow the user to fill in the necessary contact information.
This works correctly in the Android application.

**Desktop (please complete the following information):**
 - OS: Linux
 - Desktop Client, Web Client
 - Version 3.84.0

**Comment by johnbotris** [comment]
# testing
- [ ] It is possible to create a contact from the mail editor recipient bubbles
