### ISSUE TITLE
Missing load external image buttons.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3146]
In mobile layout the load external image buttons are not always visible or they are not recognizable by the user. The notifications and buttons are also shown differently in mobile / desktop layout. We should find a common way to display the information. 

1. Show images is not available when the mail is not authenticated. A click/touch on the text will show the load images button button but it is also not clear that this is a clickable item.
![authentication-fail-mobile](https://user-images.githubusercontent.com/8296817/120484878-c9f87e00-c3b3-11eb-940b-bcd23c124080.png)

2. People don't recognize that "Show images" is actual a clickable button:
 ![always-trust-mobile](https://user-images.githubusercontent.com/8296817/120484756-ac2b1900-c3b3-11eb-986c-f9f8b684c708.png)

I would prefer to show all messages at once and add buttons like in the desktop layout or at least use a regular button style.
![load-images-desktop](https://user-images.githubusercontent.com/8296817/120485829-c31e3b00-c3b4-11eb-871c-ddddec036d2d.png)

**Comment by bedhub** [comment]
We should also consider the styling of the accept invitation buttons. I think the buttons in this section should look the same. We should not have too many different styled buttons. 

![invitation-buttons](https://user-images.githubusercontent.com/8296817/120490393-a8e65c00-c3b8-11eb-9808-f161a102041c.png)

**Comment by johnbotris** [comment]
Something like this @bedhub? Went with a more prominent border and highlight the warning by changing the border color, so as to keep consistency in the button styling.

![Screenshot from 2021-06-03 17-31-16](https://user-images.githubusercontent.com/22109738/120671968-2d58dd80-c492-11eb-889c-cd4b4bb815ec.png)

![Screenshot from 2021-06-03 17-31-45](https://user-images.githubusercontent.com/22109738/120671969-2df17400-c492-11eb-9347-23f1414031e7.png)

![Screenshot from 2021-06-03 17-33-11](https://user-images.githubusercontent.com/22109738/120671972-2df17400-c492-11eb-83f7-2a4e47b2bcdd.png)

![Screenshot from 2021-06-03 17-34-18](https://user-images.githubusercontent.com/22109738/120671974-2e8a0a80-c492-11eb-8668-a3bcea9ebea9.png)

![Screenshot from 2021-06-03 17-31-07](https://user-images.githubusercontent.com/22109738/120671967-2cc04700-c492-11eb-8513-92afa78fb35a.png)

**Comment by johnbotris** [comment]
# testing notes
- [ ] test all banner cases (mail auth hard/soft fail, phishing warning, external images)
- [ ] phishing warning, hard auth fail and soft auth fail warnings will not be displayed together (they are prioritised in that order)
- [ ] external image banner will show alongside mail auth failure banners
