### ISSUE TITLE
Links to Tutanota faq are incompatible with whitelabel

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3150]
As an customer who is using the whitelabel feature, i do not want my users to see any links to Tutanota domains. As an administrator of a whitelabel account it is fine to see those links.

We need to remove the links from these views for non-admins while in whitelabel mode (see also  #2057):
* login settings
    * https://tutanota.com/howto/#2fa (see also #2448)
* desktop settings
    * https://tutanota.com/howto/#tray-desktop
* mail authentication banner
    * https://tutanota.com/faq/#mail-auth
* image loading banner
    * https://tutanota.com/faq/#load-images

A more generic approach to take care of these links would be nice.

#### AC:
 *  [ ] A user in whitelabel mode does not see any links to Tutanota domains.

### Testing
see acceptance criteria (Check primarily in settings)

**Comment by vitoreiji** [comment]
Shouldn't we hide _all_ links to `tutanota.com` in whitelabel mode?

**Comment by armhub** [comment]
We accept that administrators see links to tutanota.com. However, if there are more links for non-admins we also need to hide them.

**Comment by jowlo** [comment]
@arm and i cleared up some of the confusion on this issue (which was mostly me completely misunderstanding the whole thing).

We will keep the FAQ as is for now (see #3356 for dealing with those) and only remove the links in the settings view, just as in #3305 .

**Comment by vaf-hub** [comment]
If I create a new user from the admin's user management page, all looks fine, but if I register a user with a registration code directly from the whitelabel domain login then this whitelabel child user will be treated as an admin and thus also see the tutanota.com links. I am not sure that we want that?
