### ISSUE TITLE
Translations for spell checker dictionaries are missing

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3151]
![dictionary-languages](https://user-images.githubusercontent.com/8296817/120600708-5e60f000-c449-11eb-9123-623ade8da051.png)

**Comment by johnbotris** [comment]
Do you mean translations of the dictionary names? They are based on the client's language setting, rather than the chosen dictionary

**Comment by bedhub** [comment]
I was referring to af and cy for example.

**Comment by johnbotris** [comment]
The translations still need to be added to Phrase

**Comment by johnbotris** [comment]
# testing
- [ ] spellchecker language options are all properly labelled (no raw code is shown in the list)

**Comment by charlag** [comment]
Dropdown width is not configured properly so not all language names fit (looking at you, Portuguese!)

**Comment by vitoreiji** [comment]
> Dropdown width is not configured properly so not all language names fit (looking at you, Portuguese!)

Just call it Brazilian, problem solved :)
