### ISSUE TITLE
Disabeling spell checker has no effect

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3152]
There is an option under  Settings > Desktop > Spell checking to disable the functionality. I can switch it to "No" but this does not disable spell checking in the mail editor.

I also find it confusing to have two controls for the spell checker. I expected to have the selection of the dictionaries in the settings but there is only a switch to disable and enable the checking. The dictionary can be selected only from the context menu of the mail editor. 

I suggest to have only one component to select the dictionary and allow "none" as selected value to disable the spell checking. This component can then be used in the settings and the context menu.

**Comment by johnbotris** [comment]
# testing
- [ ] Desktop spellchecker is configurable from settings
- [ ] it is possible to disable the spellchecker from settings or from the context menu
