### ISSUE TITLE
[windows] Desktop Client can't register as default mail app

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3155]
When trying to register with Settings -> Desktop -> Default Email Handler
the app will ask for registry access and show that it's registered, but it will not
show as an option in the Windows Default Apps Settings.

After restarting the app, the menu option will show "Not Registered" again.

Some possible reasons: 
* elevate.exe doesn't work anymore to get admin permissions
* we're setting the wrong keys (but then the option should stay on "registered")
* the node winreg package is doing something wrong
* the recursive call of the client with the -r or -u switches fails somehow

**Comment by bedhub** [comment]
Is this issue somehow connected or can we mark this as duplicate? #3075
