### ISSUE TITLE
Add "always block image from sender" option to external loading

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3163]
As a user, I want to be given an option to permanently ignore external images from certain senders, and not have to see or attend to the external image banner whenever they send me an email (it is often just visual clutter). This is particularly relevant in the case of senders who include pixel trackers in their emails (such github) but never actually any useful visual content. 

##### acceptance criteria
* When receiving an email containing external content from a sender without a rule set, I should have an option to "Never allow external content"
* If I choose to never allow, then further emails from said sender will not show the external image loading banner, and external content will not be loaded
* I should be given an option to reset my choice for the given sender, if I make a mistake or change my mind.

##### non-functional requirements
* An option to set a blanket rule to never load image content, and thus never show the banner

### Test notes
- [x] In an email with external content, select the "Always block images from sender" option. The banner will then never be shown on other emails from that sender
- [x] In the more menu, it is possible to re-allow showing images from that sender
- [ ] The show/always show options still work as expected.
- [x] previously saved rules will not be lost with the update

**Comment by vitoreiji** [comment]
> We could use the new snackbar component to enable a quick undo of trusting and blocking.

The current implementation does not use this, instead, when you want to change the config for the sender of the currently displayed email you go to the "more" button and click "Show images" or "Block external content", which resets the rule to the default, which is to ask.

**Comment by johnbotris** [comment]
button is missing from mail authentication failed banner:

![Screenshot from 2021-08-05 10-54-58](https://user-images.githubusercontent.com/22109738/128322203-039d5ebe-9cc3-4744-82c7-d5f86aa13916.png)

**Comment by ganthern** [comment]
The "Always trust sender" button seems to have been replaced by the "Always block sender" option.

**Comment by johnbotris** [comment]
> The "Always trust sender" button seems to have been replaced by the "Always block sender" option (it is not visible in some cases).
> 

Always show isn't offered when authentication fails. Maybe it could be made more clear what is happening here
