### ISSUE TITLE
organize emails by tags/labels

### ISSUE THREAD

**Issue by lidorcg** [tutao/tutanota#318]
After over six years (wow...) we are finally going to add this. Thank you everyone for your patience!

## AC

-  It is possible to create, delete and rename a label.
- Labels should have a color,
- It is possible to assign and remove multiple labels for an email
- When viewing mail the assigned labels are visible
- List of labels is displayed below the folder list
- When selecting a label all mails matching this label are displayed
- Nested labels are not supported

added by @wrdhub 

## Tasks
 - [x] #7752
 - [x] #7753
 - [x] #7754
 - [x] #7755
 - [x] #7756
 - [x] #7757
 - [x] #7758
 - [x] #7759
 - [x] #7760
 - [x] #7761

---------

Original Text:

I'm new in tutanota but the first thing I looked for in the UX is the ability to tag/label my mails.
It is a very simple and powerful feature, superior to folders as many tags could be applied to an email when only one folder could be associated with it.

I think you should consider this feature as it will dramatically enhance the user experience and it's relatively simple to implement.

**Comment by prog-amateur** [comment]
I agree, this is a must have. Is there any option to enable it ?

**Comment by BuZZ-dEE** [comment]
https://tutanota.uservoice.com/forums/237921-general/suggestions/7917633-labels-like-gmail

**Comment by stijnvangils** [comment]
Would be great if the same could apply to the contact manager as well.

**Comment by lambda100** [comment]
Sad to see that this feature was removed from "next release", a label system is really helpful in organising emails

**Comment by OtsoHelenius** [comment]
The lack of Gmail-style labels is the biggest obstacle preventing me from transitioning to Tutanota and continuing to pay for it. Organizing mail into folders is an old-fashioned and clumsy way to sort mail. Furthermore, the labeling system absolutely needs to have a regex support for automatically labeling mail by sender/title in order to be useful for managing large volumes of e-mail.

**Comment by Newbie60** [comment]
I totally agree with having tags. I wish they were available now and especially the part of being able to have multiple tags to one email

**Comment by Galiwyx** [comment]
Any update ?

**Comment by Joeyzo** [comment]
This feature is really needed!

**Comment by hilakata** [comment]
Hungry developers don't write good code, hence me paying as a private user for the team version to support you all. 
This feature request is now more than two years old and a must have feature for the bog standard end user.
What is the ETA on this, please (with a cherry on top ;) )?

**Comment by joshwithkids** [comment]
Thank you hilakata - this is the NUMBER ONE and ONLY reason I haven't switched my whole business and personal to Tutanota.  Please world.  For all things lovely.  Thank you!

> 
> 
> Hungry developers don't write good code, hence me paying as a private user for the team version to support you all.
> This feature request is now more than two years old and a must have feature for the bog standard end user.
> What is the ETA on this, please (with a cherry on top ;) )?

**Comment by shervinsahba** [comment]
Obligatory supportive comment. I pitched in for a paid account, and this feature would absolutely cinch Tutanota as my ideal email service.

**Comment by x80486** [comment]
It's indeed very basic; services like `Criptext` already have that – and they are babies compared to Tutanota.

**Comment by marhalish** [comment]
This needs to be the next released feature. It is basic and seriously inconvenient to not have by default.
