### ISSUE TITLE
Add press release interface

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3186]
For sending out press releases or newsletters to external contacts we need an easy way of sending a mail to multiple people with some per contact modifications.

This is intended for internal use only for now.

**Comment by johnbotris** [comment]
# testing
- [ ] press release mode is only available with the feature type "Newsletter"
- [ ] test that sending of mails still works
- [ ] test that pre-mail-send condition checks are still functioning and honoured (no password, weak password, no subject, invalid recipient) by both mail editor and calendar invites
