### ISSUE TITLE
Android 5 support has been dropped

### ISSUE THREAD

**Issue by v011** [tutao/tutanota#3188]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

The new Android version of Tutanota (v3.84.*) seems to have dropped support for Android 5, despite the fact that it's not a breaking change version.

**Expected behavior**

According to the [semantic versioning specification](https://semver.org), a minor version change must not break anything.
_OR_
An alternative could be to increment the version number to v4 and to announce that Android 5 is no longer supported. If so, please explain why.

**Screenshots**

[v3.82 on F-Droid](https://f-droid.org/en/packages/de.tutao.tutanota/)
![fdroid_screenshot_2021-06-12](https://user-images.githubusercontent.com/72566583/121781829-e14f1c80-cba6-11eb-800a-354d08f79e46.png)

[v3.84 on Google Play](https://play.google.com/store/apps/details?id=de.tutao.tutanota)
![google-play_screenshot_2021-06-12](https://user-images.githubusercontent.com/72566583/121781856-02b00880-cba7-11eb-9e4d-e9613a1c2973.png)

**Comment by johnbotris** [comment]
We do not use semantic versioning for Tutanota

**Comment by charlag** [comment]
Hello
We do not use semantic versioning for the client (and I personally think it's rather pointless for apps). We use our own versioning scheme based on the models which does similar things most of the time
