### ISSUE TITLE
Send e-mail shortcuts have disappeared from the help page

### ISSUE THREAD

**Issue by v011** [tutao/tutanota#3189]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

When the new keyboard shortcut for sending e-mails (`Ctrl + Enter`) was added, I noticed that the help explaining how to send via the keyboard disappeared.

**To Reproduce**

1. Login
2. Press F1
3. There is no help for sending e-mails

**Expected behavior**

There should be help explaining how to send e-mail via the 2 current keyboard shortcuts (`Ctrl + Enter`, `Ctrl + Shift + S`).

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04
 - Tutanota version : 3.84.4

**Comment by jowlo** [comment]
The help only shows the shortcuts that are applicable in the _current_ view. So you will need to open a mail editor and hit <kbd>F1</kbd> then. It does show both send options for me.
Please reopen if you don't have the shortcuts listed when opening from an editor.

**Comment by v011** [comment]
Yes, you are right, the help is context-based. I forgot that. Thanks !
