### ISSUE TITLE
Too many ouput console.log from EventBusClient.js

### ISSUE THREAD

**Issue by rom-bar** [tutao/tutanota#319]
I got many debug output in devTools console like this.

> ws message:  {"_format":"1","clientVersion":"2.15.1","eventBatchId":null,"eventBatchOwner":null,"modelVersions":"20.17","msgId":"0","type":"entityUpdate","authentication":null,"chat":null,"entityUpdate":{"_id":"----","application":"tutanota","instanceId":"-------","instanceListId":"-----","operation":"2","type":"Mail"},"eventBatch":[],"exception":null}

i think this output must be disabled in production mode.
because in EventBusClient.js i see many console.log() called.

**Comment by charlag** [comment]
Fixed for some time now
