### ISSUE TITLE
Closed sessions are not deleted automatically

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#320]
Closed sessions should be removed automatically after a fixed amount of time. Currently this does not happen.

**Comment by armhub** [comment]
TTL is set when accessing sessions, but old sessions must be deleted immediately

**Comment by armhub** [comment]
fixed on server side

**Comment by asteintutao** [comment]
not working properly old sessions are still not deleted

**Comment by armhub** [comment]
now really fixed on server side
