### ISSUE TITLE
Using Tab + Enter to cancel a permanent email deletion still deletes the email. 

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3200]
**Describe the bug**
If you choose to delete an email from the Trash folder you are presented with a popup asking if this is ok or if you would like to cancel. If you use "tab + enter" to select the cancel option, the email is still permanently deleted. You can only cancel this action by clicking cancel with the mouse.

**To Reproduce**
1. Open the Trash folder
2. Select and email and click the trashcan icon
3. A popup window will appear asking if you really want to delete the email or if you would like to cancel
4. Tab between "Cancel" and "Ok" and hit enter to choose "Cancel"
5. The email is still deleted (this occurs regardless of if you hit enter while cancel or ok is selected)

**Expected behavior**
If you tab to select the "Cancel" option and hit the enter button, the action should be cancelled and the email should remain in the Trash folder.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Desktop Client
 - Version 3.84.4

### Test notes
- [x] in the confirm email deletion dialog, check that tabbing to either the confirm or cancel buttons and then hitting enter will execute the expected action
- [x] check that this is the case for other confirm/confirmMultiple dialogs
- [ ] there should not be a dialog in which you cannot execute the affirmative action by tabbing to a button and pressing enter

**Comment by jowlo** [comment]
It appears that we do not change focus correctly even if the shortcut is removed (or gated with a setting as in #3304). After tabbing `document.activeElement` still is set to the OK-Button and <kbd>Enter</kbd> triggers its handler.

**Comment by johnbotris** [comment]
There are two problems here:
* We hardcode the ok action to the enter key, so it makes no difference which button is highlighted, enter will always confirm (this is _very_ bad for accessibility)
* The dialog starts with the cancel button highlighted, but the highlighting is unclear - We indicate the selected item by making it pale. This is less of an issue when there are lots of buttons so it's clear which one the odd one out is, but it is definitely unintuitive that the non-bold button would be the selected one. (this seems to be where confusion is coming from)

**Comment by ganthern** [comment]
https://github.com/tutao/tutanota/issues/3349

**Comment by johnbotris** [comment]
The issue you noted exists on prod, I don't think it needs to block the release
