### ISSUE TITLE
Cannot install desktop client on macOS

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3212]
It is not possible to mount the dmg file on macOS seems like the dmg file has not been created correctly. Here is what users are reporting.

Version: 3.84.4
macOS: 10.14.6

![Screen Shot 2021-06-22 at 9 58 13 PM](https://user-images.githubusercontent.com/8296817/123084474-706af880-d421-11eb-9157-722c456fb9cb.png)
![Screen Shot 2021-06-22 at 9 57 53 PM](https://user-images.githubusercontent.com/8296817/123084481-7365e900-d421-11eb-8419-8da3b445ff31.png)

**Comment by johnbotris** [comment]
the desktop clients for 3.84.5 aren't released yet. Is this the 3.84.4 version or did something go wrong?

**Comment by johnbotris** [comment]
Are users reporting this as a problem still? Maybe we can see once this next release goes out

**Comment by brshub** [comment]
> Are users reporting this as a problem still? Maybe we can see once this next release goes out

This was only reported once and we were unable to recreate the problem.
