### ISSUE TITLE
Email scrolling with arrow keys shifts between emails

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3217]
**Bug in web app and in desktop client**

**Describe the bug**
If you open a long email which requires scrolling to read, attempting to scroll down with the arrow keys moves us to the next email.

**To Reproduce**
1. Open a long email
2. Click into the right column containing the email
3. Scroll down using the arrow key

**Expected behavior**
If you are active in the email column, the user should be able to scroll using the arrow keys.

**Desktop (please complete the following information):**
 - OS: Linux, Windows 10
 - Browser: Firefox
 - Versions: 3.84.5 and 3.84.4

**Comment by charlag** [comment]
Hi
Sorry, but this is "feature, not a bug" case. If you check F1 help you will see that scrolling is with PgUp/PgDn keys
