### ISSUE TITLE
Inbox rule field sender is misleading

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3219]
The UI for inbox rules is currently misleading because you create a rule for the "Sender" but it does not match the "Sender" that we are displaying in the mail viewer. Inbox rules are only checking against the from address and not the technical sender (envelop from).

MailViewer
![Screenshot from 2021-06-25 16-32-30](https://user-images.githubusercontent.com/8296817/123440548-32add180-d5d3-11eb-9e2c-cb886087a025.png)

Create inbox rules
![Screenshot from 2021-06-25 16-30-29](https://user-images.githubusercontent.com/8296817/123440551-33466800-d5d3-11eb-9533-4629541e996d.png)

To fix this we  can use the existing inbox rules and check against From and Sender or we introduce a separate field type to match the technical sender.

**Comment by sarashub** [comment]
Test hints:

Receive an email with different envelope sender, then

- [ ] when clicking on the Sender address in the mail view a dropdown opens, containing an info text and buttons to create a spam or inbox rule.
- [ ] when creating an inbox rule either from this dropdown or from the corresponding one that opens when clicking on the From address, the rule is applied for both Sender and From addresses 

As changes to the dropdown component where made, also test

- [ ] dropdowns (especially those containing text) look fine
- [ ] external recipients that click on the recipient address in the mail editor do not see the "create contact" or "remove" button in the opening dropdown,

**Comment by charlag** [comment]
This is how it looks now for sender:

![Screenshot from 2021-08-02 15-09-14](https://user-images.githubusercontent.com/3099142/127867173-c87bdd49-c640-4040-bf6d-3f0695bba439.png)

We could probably make it wider on desktop but it's not that important.
