### ISSUE TITLE
1-3 keys for switching between calendar views do not work

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3225]
They are listed in the code but they are not in F1 help and do not work.

**Comment by ganthern** [comment]
* MailView is registering Shortcuts depending on the customer object which means it needs to await before calling the KeyManager in oncreate/onremove. 
* This places the unregisterShortcuts call behind CalendarViews' registerShortcuts call
* both of them use 1-3, therefore MailView's unregister call will remove the Shortcuts the CalendarView just added.

**Comment by vitoreiji** [comment]
Fixed by 99e0112ab6862508804423fade34f6ef23a0671f
