### ISSUE TITLE
Add ability to run admin client build without build server

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3226]
For CI jobs we have a lot of complication and unnecessary overhead from using buildServer.
As we have a facade for accessing it (`buildWithServer`) we could add a parameter which would just import and call builder directly.

See PR20 in tutanota-next for changes.

**Comment by jowlo** [comment]
Is there anything to test here?

**Comment by johnbotris** [comment]
@jowlo We test it by building a release of admin client in CI ~:) Already seems to be working
