### ISSUE TITLE
Starting build server should not fail with stale socket

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3227]
There are situations when build server was not stopped properly and did not clean up its socket file.
In this case restarting build server might fail with "address already in use".
We should recover from this scenario somehow:
1. From buildServerClient delete the socket if the server is not running
2. From BuildServer delete it if we start

**Comment by rosso-ptg** [comment]
This should be implemented and released together with #3226. Otherwise deleting the socket on server (re-)start (see 2. above) can lead to issues in our CI environment where one build process could delete the server socket of another build process.

**Comment by charlag** [comment]
We should not scenario where it happens anymore
