### ISSUE TITLE
Disable "Always trust sender" option when mail is not authenticated

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3228]
It is still confusing for users that there is a "Always trust sender" option for loading images which in some case do not load the images (#147). 

We do not load images automatically in cases were the mail authentication fails and we decided to keep this behavior (see #3147).

We should remove the "Always trust sender" option for emails that are not authenticated. It should be then clear to the users that  the automatic image loading for this email does not work.

**Comment by johnbotris** [comment]
Could it be worth mentioning in the banner that even if a sender was already "trusted", the images have been blocked due to mail auth failure? we could combine the two banners then, though it would become pretty wordy
