### ISSUE TITLE
Email template list is scrolled to bottom

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3229]
When you enter a search string in the email template selector, the result list is often scrolled to the bottom, so the best search results are hidden.

**Comment by bedhub** [comment]
I am also able to reproduce this case. Seems like it always happens if the current selected template is not part of the search result.

**Comment by bedhub** [comment]
**Test notes:**
It is required to have a long template list so you can even scroll the template list after filtering.
- [ ] Check that changing selection with up and down errors always focus the selected element
- [ ] After entering a filter string it should always scroll to the first element
- [ ] After filtering Select an element with mouse, scroll down the list so selected element is not visible anymore, use up and down to change selection.
- [ ] Basic regression test to select/edit/create a template

**Comment by jowlo** [comment]
Notes: 
 * After clicking on one of the templates in the list, arrow key navigation is not possible anymore. When returning to the filter textinput it works again. Is this intended behaviour?

**Comment by jowlo** [comment]
After checking again, this appears to be solved. I must have tested on an old version, sorry @bedhub.
