### ISSUE TITLE
Fix DMARC result interpretation

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#323]
OpenDMARC headers have been changed from:
dkim=pass

to:
dmarc=fail (p=none dis=none)

=> We have to interpret the disposition value from now on. Must be fixed at MimeStringToSmtpMessageConverter line 189.

Possible values for dis are REJECT, QUARANTINE and NONE (see http://www.trusteddomain.org/pipermail/opendmarc-dev/attachments/20160524/32226303/attachment.patch)

**Comment by ofiqfakj** [comment]
The current setting is "v=DMARC1; p=none; adkim=s".
Could you please change p=none to p=reject ? This would be great!

**Comment by vitoreiji** [comment]
We are moving away from openDMARC, so this is not relevant anymore.
