### ISSUE TITLE
spell check underlines misspelling in inbox emails

### ISSUE THREAD

**Issue by christopherpickering** [tutao/tutanota#3238]
**Describe the bug**
The spellcheck seems to be checking incoming emails, not just new emails being typed.

**Expected behavior**
No Curley red line on misspelled words in my inbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/17788706/124163220-fa8c1000-da64-11eb-8a1d-865357d61b46.png)
**Desktop (please complete the following information):**
 - max os 11.4
 - Version 3.84.7.1543

**Comment by charlag** [comment]
Hi
This is in desktop app, right?
Is it something like a text field they added to email?

**Comment by christopherpickering** [comment]
Yes the desktop app. It seems to be just text in the email body. I can forward you an example email if you would like?Thanks!


Jul 2, 2021, 3:30 AM by ***@***.***:

**Comment by charlag** [comment]
@christopherpickering if you still experience this, please forward email to support, this is not a general case
