### ISSUE TITLE
librejs license overview

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#324]
Create a license overview for librejs: https://www.gnu.org/software/librejs/free-your-javascript.html

**Comment by galex-713** [comment]
It would be as well interesting to follow some of the conventions of https://www.gnu.org/licenses/javascript-labels.html so users takes the habit of using extensions and/or browsers that may use standards to check they will be able to later check the source code of any past executed javascript code, with proper archiving and versioning, ensuring no javascript have ever, for instance, sent the keys to the server.
