### ISSUE TITLE
howto links are not valid any more

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3260]
The howto links used in the settings partly do not work any more. They need to be replaced by faq links, e.g.
https://tutanota.com/howto#2fa -> https://tutanota.com/faq#2fa

See also related issue #3150

**Comment by johnbotris** [comment]
fixed by 64c82164846bce2bc1152895e099a6e7908d199f

**Comment by ganthern** [comment]
link to "Gift card Terms & conditions" in Settings -> Subscription is rendered as text, not as a URL, which is inconsistent with all the other links.

**Comment by vitoreiji** [comment]
> link to "Gift card Terms & conditions" in Settings -> Subscription is rendered as text, not as a URL, which is inconsistent with all the other links.

Good catch. Since this was already like this, I just created a new issue: #3311
