### ISSUE TITLE
Buggy interaction between HtmlEditor and Button

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3261]
When clicking away from a HtmlEditor, it seems to consume the mouse event on blur. For example, in the invoice and payment data page of the subscription wizard, it is not possible to click the country dropdown button while the invoice data input is focused. The first click will blur the editor without triggering the button. This same behaviour doesn't occur when selecting a payment method with the editor focused.

![Screenshot from 2021-07-07 16-58-24](https://user-images.githubusercontent.com/22109738/124782528-97a6e700-df44-11eb-9fb5-d3e3904958a4.png)

**Comment by ganthern** [comment]
seems to work in 3.98.20
