### ISSUE TITLE
getTutanotaTempDirectory doesn't distinguish between users on the same system 

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3264]
e.g. attachments that are opened via the "Open" option are readable system-wide until the tmpdir is cleared.

possible solutions:

- use a directory inside /home/user/ instead of /tmp (or platform equivalent)
- create tmp dirs unique to each user and set 700 permissions on them (or platform equivalent)

**Comment by ganthern** [comment]
## Test Notes

* [ ] when starting tutanota, the tmp dir is created in a user-specific location
    * ` /Users/<name>/AppData/Local/Temp/` on windows
    * `/tmp/tutanota/<name>` on linux
    * `$TMPDIR/tutanota/<name>` on macos
* [ ] attachment download/upload still works
* [ ] registering/unregistering as mailto handler on windows works
* [ ] drag-export mails still works

**Comment by johnbotris** [comment]
the user directories are only created as needed rather than on startup. I would say this is not a problem
