### ISSUE TITLE
Whitelabel setup breaks if you select manual certificate

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3265]
* Open up whitelabel domain editor
* Select _Manual_ certificate (this shouldn't even be offered as an option?)
* You can't change back to automatic
* Click close
* An error report dialog opens up
* Click send report
* The report dialog is empty
* Hitting close will open up another broken error dialog (ad infinitum)
* Open up the whitelabel setup dialog
* It is empty

**Comment by armhub** [comment]
Seems to be related to #2554

**Comment by bedhub** [comment]
duplicate of #2554
