### ISSUE TITLE
extract shortcut help gui component from keymanager

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3267]
Some refactoring is needed for better separation between bookkeeping shortcuts and the UI that displays them.

Test Notes:

- [ ] the F1 help dialog opens correctly with the shortcut and the help button in the drawer menu
- [ ] desktop shortcuts are added for the desktop client (Search page, Print, New Window etc) and work as intended
- [x] the shortcuts that are used in multiple views do the right thing and are displayed correctly (e.g. 1,2,3 in mail/calendar view)
- [x] only one help dialog can be open at a time
- [x] modal shortcuts shadow other shortcuts correctly (mail editor, signature editor, password change, dropdowns...)

**Comment by ganthern** [comment]
Test Notes:

- [ ] the F1 help dialog opens correctly with the shortcut and the help button in the drawer menu
- [ ] desktop shortcuts are added for the desktop client (Search page, Print, New Window etc) and work as intended
- [ ] the shortcuts that are used in multiple views do the right thing and are displayed correctly (e.g. 1,2,3 in mail/calendar view)
- [ ] only one help dialog can be open at a time
- [ ] modal shortcuts shadow other shortcuts correctly (mail editor, signature editor, password change, dropdowns...)

**Comment by johnbotris** [comment]
The Shortcuts button from the help button dropdown shows the wrong shortcuts (the dropdown modal shortcuts, rather than the view shortcuts)
