### ISSUE TITLE
change language code for serbian from `sr` to `sr-cyrl`

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3270]
# testing
- [ ] Serbian language still works

**Comment by johnbotris** [comment]
closed by 8947737c40d7e75d79684517d29335bd51822878

**Comment by johnbotris** [comment]
Forgot to update `LanguageViewModel` ~:)

**Comment by johnbotris** [comment]
fixed by c76a2d70704b39f2aac634e594bb1749b8197a9e

**Comment by bedhub** [comment]
breaks android build
