### ISSUE TITLE
Duplicate Calendars Created

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#3272]
## ISSUE
I use multiple calendars on the Tutanota calendar to allow me to color code and categorize events. By default, new events are added to the "Private" calendar. I have added several others, for example the "Cleaning" calendar shown in the screenshot below. 

However, after some amount of time, numerous additional "Private" calendars show up despite me not creating them. I have gone through and deleted them in the past, however, they reappear over time.

When I export the calendars, they don't contain any events:

```
BEGIN:VCALENDAR
PRODID:-//Tutao GmbH//Tutanota 3.84.11//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
END:VCALENDAR
```

## Steps to Reproduce

I haven't been able to pin down when or why this happens. I have deleted all the calendars and will update the issue if I can isolate when they come back.

## Screenshot

![647654938 109166public](https://user-images.githubusercontent.com/45246438/125179269-2a50bb80-e1bb-11eb-8c21-aa59c2558d59.jpeg)

**Comment by bobmatyas** [comment]
I have added new events this week and already have 3 new  "Private" calendars created. I am still unable to pin down when or why this is happening.

I switch between using Tutanota on macOS and iOS with the latest version of both the OS and app.

**Comment by johnbotris** [comment]
It would help if you can detect if this is happening after creating new events, or after opening up the calendar for the first time. It looks like it could be happening if you click New Event before calendars have been loaded, which leads to a new calendar being created.

**Comment by bobmatyas** [comment]
This happens when I:

1. Open the app
2. Navigate to calendar
3. Immediately create a new event

As you suspected, it happens because the calendars aren't loaded. If I wait for the small progress indicator on the top to finish, I can create an event without creating a duplicate calendar.

Perhaps the add an event button could be disabled until the calendar is fully loaded?
