### ISSUE TITLE
Deleting Calendars Too Quickly Causes Error

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#3273]
- [ x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [  x ] I've searched and did not find a similar issue.

**Describe the bug**

Deleting more than one calendar in rapid succession frequently triggers errors.

**To Reproduce**
1. Create multiple different calendars
2. Delete one calendar
3. Immediately try to delete another calendar

```
NotAuthorizedError
Error message: 403: MeHw_P9----2 | GET /rest/tutanota/calendarevent/MdKQ7mq--B-2
Stacktrace:
NotAuthorizedError: 403: MeHw_P9----2 | GET /rest/tutanota/calendarevent/MdKQ7mq--B-2
at af (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/common-min-82f59dc4.js:1:2222)
at XMLHttpRequest.d.onload (file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/worker.js:1:100256)
```

I noticed if you wait the error is less likely to happen.

**Expected behavior**

Deleting calendars in quick succession should not trigger an error.

A spinner to give an indication that the calendar is working could prevent this issue.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version v3.84.11

**Comment by ganthern** [comment]
I can't reproduce this in 3.98.17 anymore, even with the slowest of devices/connections. Please comment if anyone still experiences this.
