### ISSUE TITLE
Authenticator App Code Doesn't Work

### ISSUE THREAD

**Issue by ByteHaker** [tutao/tutanota#328]
![screenshot at 2018-03-17 07-36-40](https://user-images.githubusercontent.com/30409831/37723545-a099a3f2-2d54-11e8-9b4d-138f452da4e3.png)
When Adding a New Auth. App the code for verify not working.
So,Not able to add any Auth. App.
I'm test this with 2 accounts; 
Browser: Chromium 62.
OS: Debian 9 Testing

**Comment by duianto** [comment]
I just setup a 2nd factor of type: Authenticator (TOTP)
with the Google Authenticator, on both Android and iPhone, and the code validated without any issues.
Logging in also worked as expected, with the authenticator code, on mail.tutanota.com

**Comment by ByteHaker** [comment]
Yes this Problem is Solved.
