### ISSUE TITLE
Email editor does not have background change mechanism like mail viewer

### ISSUE THREAD

**Issue by samsaraswheel** [tutao/tutanota#3281]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.
Similar but not the same to https://github.com/tutao/tutanota/issues/2610

**Bug in mobile app**

**Describe the bug**
This is similar to https://github.com/tutao/tutanota/issues/2610 for white background activation to allow darker font colors to be seen.  

I have an email with dark colored fonts, it defaults to a white background when reading emails which is ok and readable.

But when I REPLY or FORWARD to these emails, it defaults to a dark background, no white, with hard to see darker fonts, some emails just aren't readable at all. I assume the color modes applied in email Read settings don't apply here in Reply or Forward.

**To Reproduce**
1. Go to an Email with a white background and dark fonts in Dark mode
2. Click on Reply or Forward
3. Reply or Forward email screen defaults to a Dark background with dark fonts which are hard to read.

**Expected behavior**
When in Reply or Forward modes make the color settings consistent with Read mode

**Smartphone (please complete the following information):**
 - Device: Samsung S4
 - OS: Lineage OS
 - Version: 14

**Additional context**

Ideally here is a suggestion for a simple solution:
When in Dark mode just do 2 color settings,
-  a blanket default on all fonts force colors to white 
-  hyperlinks to another color to make it easy to read, 

that's it, no autodetect, no contrast detect, no white background needed. Keep dark mode dark.
Or at least have a display option to do so. 

i have another mobile email app k9 that forces this simple color setup in dark mode and it does this seamlessly to all emails it recieves in html format, outlook, gmail etc. and all emails appear readable and don't look odd at all with formatting. 

At current different email displays with varying black white background and font colors look quite odd and inconsistent with Tutanota mobile.

**Comment by charlag** [comment]
Hi
We can't just say "okay email now will have white text" because it can have some colored background already. We will rather have readable emails so simple solution is not an option.
We need to fix the editor though.
