### ISSUE TITLE
Issues with npm install dependencies

### ISSUE THREAD

**Issue by browntownington** [tutao/tutanota#3287]
**Bug in web app**

**Describe the bug**
This isn't a bug per say but rather and issue with install of dependencies.

**To Reproduce**
run "npm install" within /tutanoto as per guide https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md

**Expected behavior**

**Logs*
mrlb@DESKTOP-CM4IDJ9:~/tutanota$ sudo npm install
npm ERR! code 1
npm ERR! path /home/mrlb/tutanota/node_modules/keytar
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build
npm ERR! > keytar@7.2.0 build
npm ERR! > node-gyp rebuild
npm ERR! prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.0.0
npm ERR! gyp info using node@14.17.3 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.9 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/mrlb/tutanota/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/mrlb/tutanota/node_modules/keytar/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/mrlb/tutanota/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/mrlb/.cache/node-gyp/14.17.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/mrlb/.cache/node-gyp/14.17.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/mrlb/tutanota/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/mrlb/.cache/node-gyp/14.17.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/mrlb/tutanota/node_modules/keytar',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: pkg-config: not found
npm ERR! gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/mrlb/tutanota/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 4.19.128-microsoft-standard
npm ERR! gyp ERR! command "/usr/local/bin/node" "/home/mrlb/tutanota/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /home/mrlb/tutanota/node_modules/keytar
npm ERR! gyp ERR! node -v v14.17.3
npm ERR! gyp ERR! node-gyp -v v8.0.0
npm ERR! gyp ERR! not ok
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mrlb/.npm/_logs/2021-07-14T02_51_18_609Z-debug.log

**Installation**
Ubuntu 18.04 WLS

**Comment by johnbotris** [comment]
you need to install `pkg-config`

**Comment by browntownington** [comment]
Actually when I installed libsecret-1-dev it fixed the issue. Perhaps this can go in the build instructions as a pre-req.

sudo apt-get install libsecret-1-dev
https://github.com/atom/node-keytar#on-linux

**Comment by charlag** [comment]
We should probably make it `|| true` in postinstall, it's not strictly important for everyone to have our own version, mostly for distribution builds.
