### ISSUE TITLE
Status bar icons and buttons are hardly visible 

### ISSUE THREAD

**Issue by rehork** [tutao/tutanota#3299]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
After latest update 3.85.3 when using the app a status bar icons and buttons are almost invisible.

**To Reproduce**
1. Lineage OS 17.1
2. Option for "Enable on-screen nav bar" (Settings->System->Buttons)
3. Launch Tutanota application
4. Check that status bar icons and buttons are hardly visible

**Expected behavior**
The color of icons in the status bar should differs from the background color, as well as the color of buttons should differs from the background color.

**Screenshots**
![Screenshot_20210716-222945_Tutanota](https://user-images.githubusercontent.com/67607997/126006187-22e4a682-e165-4310-9412-bf11a279b651.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Lineage OS 
 - Version 17.1

**Comment by rehork** [comment]
At the top of the screenshot you can see a red bar. It's a battery power indicatior and it differs because there was low battery power, otherwise nothing would be visible in the status bar, at all.

**Comment by Herohtar** [comment]
It's more obvious that something is wrong in dark mode. The color theme isn't being set properly to make the icons dark in light mode and light in dark mode:

![Screenshot_20210718-143451](https://user-images.githubusercontent.com/10427164/126080000-cf7fb32a-16ab-4c74-8f2f-645cbd80e1f1.png)
