### ISSUE TITLE
Attachments are duplicated when a draft is closed and re-opened.

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3310]
**Bug in desktop client and web app**

**Describe the bug**
When creating an email draft with an attachment, if you minimize the draft and close it, when the draft is re-opened the attachment has been duplicated (1 -> 2). If this process is repeated the attachments again double (2 -> 4). 

**To Reproduce**
1. Create a new email draft with an attachment.
2. Click on 'Close'
3. Click "X" and close the minimized draft.
4. Edit the saved draft
5. The attachment has been duplicated.

**Expected behavior**
When the draft is saved and re-opened the attachments should not increase.

**Desktop:**
 - OS: Windows, Linux
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Version 3.85.3

**Comment by johnbotris** [comment]
### testing
- [ ] save an email with an attachment for the first time
- [ ] save an email with an attachment that has already been saved
- [ ] send an email with an attachment that hasn't been saved once
- [ ] send an email with an attachment that has been saved
- [ ] open a new mail editor, attach a file, close and reopen the editor multiple times

### regression testing
- [ ] too large mailbodies (> 1MB) are still rejected

In all of these cases, no attachments are duplicated, and saving/sending of emails with attachments will still work

**Comment by ganthern** [comment]
copying to edit:

### testing
* [ ]  save an email with an attachment for the first time
* [ ]  save an email with an attachment that has already been saved
* [ ]  send an email with an attachment that hasn't been saved once
* [ ]  send an email with an attachment that has been saved
* [ ]  open a new mail editor, attach a file, close and reopen the editor multiple times

### regression testing
* [ ]  too large mailbodies (> 1MB) are still rejected

In all of these cases, no attachments are duplicated, and saving/sending of emails with attachments will still work
