### ISSUE TITLE
[desktop] Add capability for attaching files via mailto links

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3325]
As a linux desktop user, I want to be able to use the "File -> Send As -> Email" option in my applications to attach files directly to a new mail.

#### What this is about:

The desktop client is able to take a mailto-URL as a command line argument. It can contain parameters to flesh out the initial state of the editor:

`mailto:bert@example.com?body=hello%20bert&cc=ernie@example.com&subject=greetings`

Some applications offer "Send as Mail" functionality that uses mailto-URLs pointing at temporary/local files to get the files into the default mail editor, e.g. LibreOffice:

`/tmp/.mount_tutanoQMs6Tn/tutanota-desktop -s mailto:?subject=report&attach=file:///home/user/Documents/report.odt`

Nautilus:
`/opt/tutanota-desktop-linux.AppImage -s mailto:?attach=file:///home/user/cat.jpg&attach=file:///home/user/dog%20man.jpg`

We should support this (addmittedly nonstandard) format.

#### What needs to be done (AC):
* The desktop client needs to be able to parse mailto urls with multiple `attach=` params
* it can get the file contents from disk during the mail editor inititalization
* it should be able to handle file paths `C:\file.txt` and URIs `file:///home/user/file.txt` on all platforms
* **It must notify the user about files attached in this way and offer the option to decline the attachment.**
* this should work in case tutanota desktop gets started because of clicking the link (cold start) and if it's already running and gets the mailto-argument through the single instance lock (warm start).

#### Additional notes
This functionality is a prerequisite/companion for #2968

---

#### Regression testing:

* [x] any confirm dialog that is **not** the one shown before attaching files from a mailto url
* [ ] mailto-URL handling that's not part of the desktop client: web client, android, ios
* [ ] sharing via tutanota on android/ios (uses createMailEditor like the mailto handling)

**Comment by ganthern** [comment]
The current implementation passes the mailto-URL to the render process as-is, which then parses the URL and requests the file contents as a  `DataFile` from the native side via a new IPC message `readDataFile`

* no need to implement `getSize`, `getMimeType`, `getName` to enable `FileRef` compatibility like the apps do
* no need to implement native-side encryption and file upload

**Comment by ganthern** [comment]
Regression testing:

* any Dialog.confirm call that doesn't pass the new optional infoToAppend argument

**Comment by johnbotris** [comment]
Cold start on macOS doesn't seem to work
