### ISSUE TITLE
Alarm notifications are saved every time at login

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3331]
Alarms are always scheduled when logging in (should this be happening?), and they are not being deduplicated when being written to native storage. This may have implications for https://github.com/tutao/tutanota/issues/3010

---

Test notes:
 - [ ] Add alarm. Start the app twice. Remove alarm. Alarm shall not be shown.

**Comment by charlag** [comment]
They should be re-scheduled indeed. In case of recurring alarms we only schedule limited number of them ahead. They should not be duplicated in storage though.
