### ISSUE TITLE
Add support for IDN domains

### ISSUE THREAD

**Issue by mitjajez** [tutao/tutanota#3332]
I'd like to upgrade my free account to use with my domain so I can move my mail to tutanota. Since I found that I cannot send mail to mails with IDN, I'd like to do something to support it.

IDNs in ascii starts with xn-- where support is not implemented and there is correct regex to support double --, but support growing and it's nice to type just unicode. 

I believe that on line [FormatValidator.js#L59](https://github.com/tutao/tutanota/blob/d614a047812c4fe07ae4cd1e4312ddc445e30d4a/src/misc/FormatValidator.js#L59), should be used `punycode.toASCII($IDN_domain);`
and similar to show domain in gui `punycode.toUnicode($ASCII_domain);`

I'm I need to search for other lines of code ...
Maybe here: [FormatValidator.js#L16](https://github.com/tutao/tutanota/blob/6e244133786874af29a8b58158faccab18873ab5/src/misc/FormatValidator.js#L16)

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
