### ISSUE TITLE
Broken `Settings -> Payment` link in Tutanota invoice emails on Desktop client

### ISSUE THREAD

**Issue by 0xedward** [tutao/tutanota#3333]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
`Settings -> Payment` link in "New invoice for Tutanota" email on Windows client points to `file:///{default drive letter}:/settings/invoice` (e.g. `file:///C:/settings/invoice`) instead of `file:///settings/invoice` resulting in an broken link.

**To Reproduce**
1. Download Desktop client
2. Purchase a Tutanota subscription
3. Wait for an invoice email
4. Search for the link in the following texts: [`invoiceMailBodyAutomatic_msg`](https://github.com/tutao/tutanota/blob/HEAD/src/translations/en.js#L635) or [`invoiceMailBodyOnAccount_msg`](https://github.com/tutao/tutanota/blob/HEAD/src/translations/en.js#L636)

**Expected behavior**
`Settings -> Payment` link sent with Tutanota invoice emails should open a user account's Payment settings page on Desktop clients

**Desktop:**
 - OS: Windows 10
 - Tutanota Version 3.85.6

**Additional context**
- This issue isn't present on Android.
- I'm not familiar Electron, so I don't know the implications if there exists a file where the link is referencing (e.g. ` C:/settings/` directory contains a file named `invoice`)

**Comment by charlag** [comment]
@0xedward thanks for reporting, we will have a look!

**Comment by charlag** [comment]
Relative link is transformed into `javascript:void` (which complains about CORS by the way and looks ugly in link hover overlay) but I consider it working. We should probably discuss link landing a bit.
