### ISSUE TITLE
Wrong time if Privacy.resistFingerprinting setting in Firefox is enabled/true

### ISSUE THREAD

**Issue by slrslr** [tutao/tutanota#3338]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Hello, in Firefox 90.0.2 i go to about:config page and search for Privacy.resistFingerprinting and have it true/enabled and as a result the time of the e-mails become displayed wrong, like 2 hours ago. When i disable that setting (set to default), restart Firefox, i see that time is correct. After this restart the setting change has immediate effect on page reload (Shift+F5 with clearing cache).

Please show the time correctly even the fingerprinting resisting is enabled.

**Comment by Long-FA** [comment]
It is an intended behavior. Enabling Resist Fingerprint will force browser timezone to UTC+0, no matter what your real timezone is, as an attempt to...resist fingerprinting. The whole idea of Resist Fingering is to make all browsers have the same window size, timezone, canvas data, etc, so it's difficult to fingerprint a specific browser.

**Comment by slrslr** [comment]
ctemplar.com displayed correct time even when fingerprinting resisting was enabled. In their settings i see they have option "Current time zone", maybe they asked during mailbox signup, maybe i have set it.
Why not adding such option so user have option to override wrong time
Why not asking user about timezone when server detect browser fingerprinting enabled / UTC zone reported by browser?

**Comment by charlag** [comment]
We would have to do a lot of things that would have consequences for the app. resistFingerprinting has a lot of other effects e.g. animations wouldn't work because precise timing is not working as intended.
If you want to use resistFingerprinting and still have the app working at full functionality please consider using the desktop app or building it on your own.

**Comment by SjoerdV** [comment]
Still think this is a serious issue. 

It would be much better if the user was given the (override) option to select their timezone in tuta settings. Please +1 the original poster if you agree.

Thanks!
