### ISSUE TITLE
Update Luxon to v2

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3339]
see https://moment.github.io/luxon/#/upgrading

# Test notes
 - [ ] Check that calendar works on
   - [ ] FF
   - [ ] Chrome
   - [ ] Safari
   - [ ] Desktop
   - [ ] Android
   - [ ] iOS
 - [ ] Check that import of events still works
 - [ ] Check that export of events still works

**Comment by bedhub** [comment]
They only support iOS >= 14 which is in conflict with our support policy.
https://moment.github.io/luxon/#/matrix
