### ISSUE TITLE
Spam rule editor doesn't fill in "Discard" for existing rule

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3345]
* Create a spam rule with rule=Discard and save it
* Open editor for the created spam rule, see that the editor has "Not spam" in it's rule field
* This doesn't occur if you set the rule to Not/Always spam

**Comment by ganthern** [comment]
still broken:

![image](https://user-images.githubusercontent.com/29049728/146932340-ecd58b6c-0fe8-4571-851a-beee7d3fccdb.png)

 (I'm sorry)
