### ISSUE TITLE
Desktop app doubles the number of attachments inserted if you leave the mail as a draft

### ISSUE THREAD

**Issue by prentakias** [tutao/tutanota#3347]
Desktop app doubles the number of attachments inserted if you leave the mail as a draft

Tutanota Desktop: v3.85.6
Windows 10 Pro
Version: 20H2
Build: 9042.1110

**Comment by johnbotris** [comment]
Duplicate of #3310

**Comment by prentakias** [comment]
> Duplicate of #3310

Thank you. I will check the list of issues more closely in the future
