### ISSUE TITLE
The free usage condition checkboxes do not need to be checked to create a free account

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3349]
**Bug in web app**

Hitting Enter during the free signup process, when the free usage conditions are shown, enables one to skip to the next wizard page without checking the boxes.

**To Reproduce**
1. Go to login page
2. Click on "sign up"
3. Click "Free"
4. Hit enter without checking any checkboxes
5. the wizard shows the next page (account creation)

**Expected behavior**
- [ ] If the "Cancel" button is highlighted, hitting enter should close the dialog back to the plan selection
- [ ] if "Ok" is highlighted and all checkboxes are checked, the wizard should progress to the "create account" page upon hitting enter
- [ ] if "Ok" is highlighted and any checkboxes are unchecked,  hitting enter has no effect.

**Comment by rezbyte** [comment]
This was fixed by PR #6129.
