### ISSUE TITLE
Will you allow us to use the old app once you have new?

### ISSUE THREAD

**Issue by LearnPhalcon** [tutao/tutanota#335]
Will we be able to use the old app/ui from https://app.tutanota.com/#login
when you're done with your beta at https://mail.tutanota.com/login

I don't know about everyone else, but the only thing I like about new app is dark theme.
I much more prefer the design of the old design. Its simple and just works, everything an email client needs. New design is very bulky looking and reminds me of Google way too much. Even when you try to write an email it popsup the writing dialog just like Google does.

**Comment by armhub** [comment]
Sorry, we will not allow the old app any more. But if you have any comments about the new interface, please send us an email and we may consider your ideas.
