### ISSUE TITLE
Filter is not always automatically focused in dropdown selector

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3352]
It should be focused so that you can just start typing

* Open the country selector in the gift card purchase wizard or the signup wizard.
* The filter text field is not automatically focused
however, the language selector in appearance settings does automatically focus the filter (probably a difference between DropdownSelector and DropdownSelectorN)

**Comment by nif-tutao** [comment]
Could not reproduce on client/web v. 3.98.21
