### ISSUE TITLE
MailBodyToLargeError is not handled in the client

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3355]
**Bug in web app**

**Describe the bug**
Trying to send mail with a large mail body will fail with an unhandled error popping up

**To Reproduce**
1. Create a new mail and paste a large amount of text ( >1MB)
2. Click on 'Send'
3. see unhandled error pop up

**Expected behavior**
The error  should be handled by showing a message to the user explaining the problem

**Comment by johnbotris** [comment]
Duplicate of #3326

**Comment by ganthern** [comment]
definitely happening in prod
