### ISSUE TITLE
Offer XRechnung for invoices

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3357]
**As a german government agency, i want to be able to download my invoice in the [XRechnung](https://de.wikipedia.org/wiki/XRechnung) XML standard, because that is the mandatory format for public mandates in my state.**

The XRechnung standard is the german implementation of *EN 16931-1* already mandatory in some states and for federal agencies. We should offer the option of downloading an XRechnung XML file for customers.

The *Koordinierungsstelle für IT-Standards* has a [FAQ (german only)](https://www.xoev.de/xrechnung/betrieb-und-support/faq-17664) including some technical aspects. They also provide tools at https://github.com/itplr-kosit that can be used to verify compliance.

#### Acceptance criteria
- [x] For business customers, the button for downloading invoices in Payment Settings will show a drop down that offers either "PDF" or "XRechnung"
- [x] If XRechnung is selected, then the invoice will be downloaded in an XRechnung-compliant XML Document
- [x] If PDF is selected, then the normal PDF is downloaded

##### some links
https://github.com/itplr-kosit/xrechnung-testsuite
https://github.com/itplr-kosit/validator-configuration-xrechnung

#### Test notes

- [ ] Have any Tuta non-business plan account with access to an invoice
    - [ ] Choose to print the invoice
    - [ ] Ensure that clicking the button immediately prints a PDF just like always
- [ ] Switch to / create an account with a business plan
    - [ ] Ensure that a dropdown menu now appears when clicking the button to download the invoice
    - [ ] Select "PDF" and ensure a PDF is printed like before
    - [ ] Select "XML" and ensure that an XML (Xrechnung) is downloaded
    - [ ] Use this tool https://erechnungsvalidator.service-bw.de/  and upload the xml invoice to it
    - [ ] Ensure it validates correctly
 - [ ] Repeat procedure with an account that has some discount applied to it

**Comment by johnbotris** [comment]
Should we bump priority on this, if it will become a requirement at some point?

**Comment by jowlo** [comment]
I am not sure how hard the requirement is, i think as of now it is only for government agencies as clients themselves, but it might be transitive. I think basically it makes it easier for other businesses to import the invoice. @armhub should know a bit more.
