### ISSUE TITLE
New Shorter Domains?

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#336]
Can you introduce more shorter domains? @tuta.io is perfect so build up on that. Something like @tuta.eu etc. Don't do more longer donations.

**Comment by UnnoTed** [comment]
tuta.cx is just 3.5 usd on internetbs

**Comment by livingsilver94** [comment]
IMHO keeping using "tuta" would be weird to Italian speakers as "tuta" means tracksuit (that's the reason I have keemail.me).

**Comment by charlag** [comment]
We'll announce when we have more domains, for now you can use any custom domain of your liking
