### ISSUE TITLE
Android: Setting description text does not properly wrap.

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#3371]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue. (possibly related to #1336?)

**Bug in mobile app**

**Describe the bug**
When loading the Global Settings menu on the Android mobile app, the text listed under "Security" does not wrap correctly. (See image below)

**To Reproduce**
1. Go to Settings > Global Settings in Android App
2. Scroll down to "Security"
3. See error

**Expected behavior**
The text in this lins should wrap correctly so the entire description can be read.

**Screenshots**
![securitytextwrapping](https://user-images.githubusercontent.com/82211006/128999090-623b54aa-41f9-4bdf-92e5-0c356117da4f.png)

**Smartphone Information:**
 - Device: Android 
 - OS: Android 11
 - Tutanota Version: 3.85.10

## Test Notes
- [ ] The label for the option to save IPs in the logs do not clip the screen on mobile.

**Comment by Sami32** [comment]
Same for me with Android 7.0 and Tutanota v.3.89.10
