### ISSUE TITLE
Native colors don't update when custom theme definition changes

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3373]
When the currently active saved theme definition changes when in a mobile app, the native side colors (status bar, nav bar) will not be updated until the app is restarted.

### steps to reproduce
* in app, login to account with custom whitelabel theme and apply it
* from another client change the theme colors:
    * if testing in iOS, change `content_bg`
    * if testing in Android, change `header_bg`
* logout of app and back in again, the theme colors will change, but the status and navigation bars will remain with the old colors

### Test notes
Follow the reproduction steps, but the status and navigation bars change color when you would expect

**Comment by jowlo** [comment]
Tested on android, it works fine!
