### ISSUE TITLE
newMailtoUrlMailEditor doesn't check the attachment size

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3376]
**Bug in desktop app**

**Describe the bug**
passing a mailto url with attachments exceeding 25MB in size will cause an uncaught UserError.

**To Reproduce**
1. call the desktop client (current master) with a command line argument like mailto:?attach=/path/to/large/file.zip
2. see error after clicking "attach files"

**Expected behavior**
the "tooBigAttachment_msg" should be shown.

**Comment by vaf-hub** [comment]
**Test notes:**

- [ ] try opening the desktop client with a too large file pointed to in the mailto link and verify the `tooBigAttachment_msg` is shown before the MailEditor appears
- [ ] try with attachments smaller than 25MB and verify no error message is shown and the file is attached in the opened MailEditor
- [ ] verify other mailto links still work as before
