### ISSUE TITLE
Shortcut to exit Tutanota is not working

### ISSUE THREAD

**Issue by jamoness** [tutao/tutanota#3378]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
The shortcut to exit Tutanota (Ctrl+Q) doesn't work at all.

**To Reproduce**
1. Open Tutanota desktop application
2. Press Crtl + Q to close
3. Nothing happens

**Expected behavior**
After pressing Crtl + Q the application should close.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Version 3.85.10

## Test Notes
* [ ] Ctrl + Shift + Q will quit the app on linux & desktop if a window is focused
* [ ] it's not closing the app if no tutanota window is focused
* [ ] it's also not closing the app if a mail editor is open, rather saves the draft and closes the editor
* [ ] on all desktop platforms, the shortcut shows up in the `F1` menu

### Regressions
* [ ] on mac, Cmd + Q still closes the app if a window is focused
* [ ] it's not closing the app if no tutanota window is focused

**Comment by charlag** [comment]
Ctrl+Q is not a standard shortcut on Windows.
In Microsoft Outlook, pressing Ctrl+Q marks the selected e-mail(s) as read.
In Microsoft Word, Ctrl+Q removes all formatting from a highlighted paragraph.

We could add it though.

**Comment by vaf-hub** [comment]
I cannot see how the listed shortcut is useful if one can already press Alt + F4 to close the app. I think we should close this as wontfix.

**Comment by jamoness** [comment]
@charlag in the tray if you right click Tutanota it shows "Exit - Ctrl + Q" is not my own invention or suggestion. It just doesn't work.

**Comment by jamoness** [comment]
@vaf-hub Alt + F4 would just close the window, not Tutanota completely.

**Comment by johnbotris** [comment]
I see this in windows now. It seems we have registered CmdOrCtrl+Q as the accelerator hint for this menu item, without registering it with `globalShortcut`. We should either remove this hint or register the keybinding

**Comment by ngrigoriev** [comment]
I second this issue. In fact, on Linux there seems to be no way to exit Tutanota gracefully. No key shortcut or a menu item to shutdown the client. And killing the X window leaves Tutanota in the background, needs to be killed (and hard - with -9) from the terminal.
A proper X app should at least handle WM_DELETE. And provide a decent way to exit.

**Comment by charlag** [comment]
@ngrigoriev if you don't have a "run in background" enabled then closing the window *will* close the app
