### ISSUE TITLE
Make storing of IP address opt-in

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#338]
Tutanota client stores the IP address encrypted for one week & only the user can see this data to verify that no one elese has accessed their account. The storing of IP addresse should be switched to opt-in. Once user opts-out the last logged in IP address should be shown for one week still to make sure no one else can secretly turn off the feature.

**Comment by asteintutao** [comment]
Made a few GUI adaptations for this 

![image](https://user-images.githubusercontent.com/31402512/45822749-753c7400-bcec-11e8-91ac-dac25e6071b7.png)

Model implementation is still needed

**Comment by charlag** [comment]
Are we waiting for the server update to close this or there's something else to be done here?

**Comment by armhub** [comment]
Server changes are available now, just the client has to be adapted.

**Comment by asteintutao** [comment]
gui component was placed wrong. Is only visible for admins

**Comment by asteintutao** [comment]
Fixed by 983e9d227b92e59e046bb7d74da80a609515ae95
