### ISSUE TITLE
"Download" option for attachments not working

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3382]
* attach a file to an email
* click the attachment bubble, select download
* error message is shown

* receive email with attachments
* click the attachment bubble
* select open -> the file opens
* select download -> error message is shown

I would also mention that the error message "This file can not be opened on this device." makes no sense at all in this context

![Screenshot from 2021-08-16 10-55-36](https://user-images.githubusercontent.com/6842104/129538274-262ec22d-beae-4fef-b8d8-c8483e275599.png)

---

## Test notes
 - [ ] Open file from email attachment
 - [ ] No default directory, download attachment
 - [ ] Download it again, overwriting it
 - [ ] Download it again, picking another name
 - [ ] "Download all" from email produces zip
 - [ ] Set default download directory, download attachment
 - [ ] Download it, it should produce another filename
 - [ ] "Download all" from email produces zip.

**Comment by johnbotris** [comment]
```
error opening file: TypeError: this._electron.DownloadItem is not a constructor
    at DesktopDownloadManager.saveBlob (nollup-int:///src/desktop/DesktopDownloadManager.js:112)
    at IPC._invokeMethod (nollup-int:///src/desktop/IPC.js:206)
    at eval (nollup-int:///src/desktop/IPC.js:105)
    at electron/js2c/browser_init.js:189
    at Object.<anonymous> (electron/js2c/browser_init.js:157)
    at Object.emit (events.js:315)
```

**Comment by jowlo** [comment]
The error is the same for a single file or when hitting "Save all". Opening a file works fine.
