### ISSUE TITLE
Multiple events in calendar invite

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3383]
**Bug in calendar**

When creating and event and adding invalid (eg mistyped) guests with Tutanota addresses, trying to send the invite, removing the invalid addresses and successfully sending afterwards, the event invitation has multiple `.ics` files as attachments, one for each sending attempt.

**To Reproduce**
1. Create new event in calendar
2. Add a guest with an invalid internal address, eg `d08b7489b47f40afae5aff99@tutanota.com`
3. Add another guest with a _valid_ internal address
4. Hit "Send"
5. See error about the invalid address and dismiss this error
6. Remove invalid address from step 2
7. Hit "Send" again
8. See invite mail in "Sent" folder or recipients inbox
9. Invite mail contains *two* `.ics` files, one from the first attempt and one from the second one

**Expected behavior**
There should only be a single attached `.ics` file that contains only the valid recipients as it was displayed when hitting send the last time.

**Screenshots**
![Screenshot from 2021-08-13 15-11-56](https://user-images.githubusercontent.com/6842104/129365189-3d53fd18-a1c4-4f1a-992a-1b864d4ce568.png)

**Context**
We probably create the attachment file before sending the invite and never remove it from the mail draft when fails sending. Thus we add the file again on the next attempt to send.

**Comment by vaf-hub** [comment]
**Test notes:**

- [ ] send calendar event with valid and invalid Tutanota addresses (as described in the bug report), then remove the invalid address and verify the invite mail is sent with only one correct attachment
- [ ] verify that errors that may occur during sending of events are handled correctly (e.g. no password for an external recipient)
- [ ] regression test: verify sending of calendar event invitations, updates, responses and cancellations works fine
