### ISSUE TITLE
Show warning when closing calendar edit dialog without saving

### ISSUE THREAD

**Issue by NotepadPlusUser** [tutao/tutanota#3387]
Here are some calendar actions needed for less clumsy working, and for more consistency with the usual Windows conventions used by most software for Windows:

*  **Hovering** on an item should bring up the rectangular window with the details and the further actions.  At the moment, you have to click, which is a bother (particularly when clicking just a little outside the colour launches a new calendar item).  This is normal Windows practice.
    --- The **further actions**, edit and delete, should be able to be launched from the pop-up window, and the window should disappear when the mouse is moved away from the window. 

* **Ctrl+S** should be activated to save the screen for entering a calendar item.  This is stock-standard Windows practice, and is far more convenient than using the mouse to reach all the way up to the Save button.
 
*  A **Do you want to save?** dialogue should pop up when the user closes the screen for entering a calendar item, but has not saved any changes.   Again, this is stock-standard Windows practice, and would have saved me many times from completing the form a second time.
   --- **Escape** should be a second way to close the edit window, as is normal in Windows, so that you don't have to reach for the mouse.  And again, a dialogue should pop up if the item has not been saved.

**Comment by charlag** [comment]
Hi
I do not fully understand your first point but Ctrl+S and Escape already work? We are missing window close handler for some reason though.

**Comment by NotepadPlusUser** [comment]
Thanks, @charlag, for your remarks.  I should probably have stated at the outset that I am always working from the month-view of my calendar items.

* To clarify the first point.  In month view, when I use the mouse to hover on an item, nothing happens, which is not normal Windows practice.  I have to click the item for the rectangular window to come up.

I would far prefer a cursor in the calendar, so that I could move up, down, left and right, and select and open with the keyboard.  Then I could abandon the mouse.

* Apologies — Escape, and Ctrl S do indeed work, and are in the F1 Help.  But the problem remains that they only go back to the day-view calendar, and don't go back further to the month-view calendar where I started from — that step requires the mouse.

* A popup warning about closing  the editor without saving, however, is really needed.  Almost all software warns if you try to close without saving any changes.

The general point is that things are too clumsy.  I can do somethings with the keyboard, but other things have to be done with the mouse, and then the icons to click are right up at the top of the screen.

**Comment by charlag** [comment]
We will discuss hovering. You can switch between day/month view with shortcuts, check the F! help. I will rename the issue to refer to accidental closing.
