### ISSUE TITLE
Updating deleted event shows error

### ISSUE THREAD

**Issue by jowlo** [tutao/tutanota#3388]
### Steps to reproduce
1. Open calendar of same account in two browser windows
2. Create event
3. Open edit dialog in first window
4. Delete event in second window
5. Save changes to event in first window
6. See error

```
Feedback v3.86.0 - NotFoundError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.86.0
Timestamp (UTC): Mon, 16 Aug 2021 07:01:55 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
NotFoundError
Error message: 404: MhCl2QY----0 | PUT /rest/tutanota/calendarevent/MgzaHuZ--B-0/MTYyODAzODc1MzkyMA
Stacktrace:
NotFoundError: 404: MhCl2QY----0 | PUT /rest/tutanota/calendarevent/MgzaHuZ--B-0/MTYyODAzODc1MzkyMA
at ai (https://test.tutanota.com/common-min-0b4a1380.js:1:2210)
at XMLHttpRequest.p.onload (https://test.tutanota.com/worker.js:1:101575)
```

## Test Notes
- [ ] Do the same steps to reproduce, but when try to save the event, you see a dialog informing that the event no longer exists
- [ ] Editing existing events still working

**Comment by vaf-hub** [comment]
I am not sure what the desired behavior is here. Should we just discard the changes made after deleting the event?

**Comment by jowlo** [comment]
I think we should inform the user that the original event has been deleted and ask if they want to create a new one with the changes or discard.
I guess the usual way to get into this is to have multiple tabs open. And i can imagine both scenarios where you want to actually have the new event but others were i would want it removed.

**Comment by ganthern** [comment]
When editing existing events through the editor, the message box seems to always be triggered, even though the changes are applied.

Dragging & dropping does not have this problem.

**Comment by rezbyte** [comment]
> When editing existing events through the editor, the message box seems to always be triggered, even though the changes are applied.
> 
> Dragging & dropping does not have this problem.

Yes, there is an issue (#6207) & PR (#6208) up to solve this.
