### ISSUE TITLE
Refactor worker communication

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3405]
Worker-client communication needs a lot of ceremony:
 * Define the function you want to call
 * Add the method in types.js
 * Add the method in WorkerClient (and define the signature again)
 * Add the handler in the worker impl
 
Why is it not okay?
 * Slow to add and hard to maintain
 * Many places know about one individual operation
 * Not type safe (signatures are not checked, only _defined_ methods)
 * Exposes implementation (everyone needs to know about and have a reference to the worker)
 
 Basically worker protocol is just doing some plumbing. Worker/client boundary doesn't have to know about each detail of operation, it is enough to just know which things we expose.

We could use some kind of metaprogramming (reflection or code generation) to expose whole facades and reuse type information.

----

*Test notes:*

- [x] Sign up with new account, check that you can log in afterwards
- [x] Sign up with premium account, see that account works like premium afterwards (e.g. creating calendars works)
- [x] Downgrade account
- [x] Log in without saved password
- [x] Log in with saved credentials
- [x] Send secure external email and read it
- [x] Delete saved credentials from login screen
- [x] Delete session from login settings
- [x] Change password in login settings, check that it is changed
- [x] Create mail folder
- [x] Check creating/updating/send emails
- [x] Viewing inline images works (the ones added via editor bar)
- [x] Open attachment on desktop
- [x] Upload attachment on desktop
- [x] Deleting account works
- [x] Disable/enable email alias in mail settings
- [x] Add mail alias
- [x] Create another user in user settigns
- [x] Change password for another user in user settings
- [x] Make another user admin
- [x] Delete user
- [x] Add spam rule and check that it is applied
- [ ] Edit spam rule and check that it is still applied
- [x] Create admin group
- [x] Create mail group
- [x] Add/remove user from group in user settings
- [x] Deactivate group in group settings
- [x] Create contact form
- [x] Send message via contact form
- [ ] Read reply view contact form
- [x] Add custom email domain
- [x] Remove custom email domain
- [x] Assign catch-all for mail domain. Check that it works.
- [x] Add whitelabel domain
- [x] Deactivate whitelabel domain
- [x] Add TOTP second factor
- [x] Check TOTP second factor
- [x] Enabling search works
- [x] Disabling search works
- [x] Extend mail index by selecting earlier date on search page
- [x] Search for mails yields results, loading more result when scrolling works
- [x] Search for contacts works
- [x] Download invoice
- [x] Log in with desktop client, delete your push identifier in mail settings, re-login, see that it's regenerated and notifications still work
- [x] Add second factor, start logging in, cancel it. There should be no waiting time before the next attempt.
- [x] Use recovery code to restore access (login screen)
- [x] Delete account and take over it (try to log in, specify new email address)
- [x] #3514
- [x] Invite user from another account into calendar. Accept invite.
- [x] Invite again and reject invite.
- [ ] Report email for phishing. Confirm it. Check that email with this content is checked and marked (on another client or another email with same markers)
- [x] Allow to always show images from the sender
- [x] Never show images from the sender
- [x] Send calendar invite. Accept it. Send update. Email in calendar should be updated.
- [x] Create gift card and redeem it.
- [x] Create template group

**Comment by ganthern** [comment]
Can't seem to get notifications to work in desktop-linux, but that's probably not related to this (works on windows and mac).

**Comment by jowlo** [comment]
### Whitelabel & Contact Forms
 - [ ] External contact form users cannot login to read replies.

### Gift Cards
 - [ ] Gift card display after purchase does not show a qr code

**Comment by charlag** [comment]
Correction: cannot log in after temporary login (contact form or singup) until the page reload.

**Comment by rosso-ptg** [comment]
@jowlo we've found that gift card QR code generation is broken since last release. We could not reproduce problem with signup wizard showing up after gift card redemption. Is there a specific scenario?
