### ISSUE TITLE
Unhandled error when U2F request is cancelled

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3419]
In firefox
* setup new u2f key or try to login to an account with u2f setup
* press cancel on the browser dialog
* get an error

This is the request to cancel:
![Screenshot from 2021-08-25 14-28-24](https://user-images.githubusercontent.com/8296817/130793874-647ced37-5350-4b1b-bbe2-22a98a3b3f68.png)

Stacktrace:
Feedback v3.86.4 - U2fError - UNKNOWN - Browser
 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.86.4
 Timestamp (UTC): Wed, 25 Aug 2021 12:28:36 GMT
 User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0
U2fError
 Error message: U2f error code: 1
Stacktrace: 
U2fError. U2f error code: 1

**Comment by jowlo** [comment]
Sorry, cannot test further because i only have a single key. Timeout is handled correctly.

Also note that on Chromium there is no browser popup (anymore?), i am unsure if we need to reflect that in the UI.

**Comment by vaf-hub** [comment]
Can someone in the office test it with different keys, please?

If you like we can create a new issue to indicate to the user (with a dialog or some progress icon) that they should use their key now on Chromium, but I think it is not a very high priority and I would just ignore it until we receive complaints in support tbh.
