### ISSUE TITLE
NotFoundError when viewing event as external recipient.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3420]
When receiving an event invitation as external recipient there is an option to view the event. Clicking on it throws a NotFoundError because we try to load the customer instance but the external recipient does not have permission.

1. Send calendar invitation to secure external recipient
2. Click "view event" on the received email

Possible solution:
Hide the "view event" action for external recipients or avoid loading the customer instance. When clicking on "view event" the calendar event editor opens and it has an option to "save" the event. I am not sure what this action does because external users do not have a calendar view. I propose also to remove that "save" action. Maybe we instead just show the calendar event preview pop up.
 

Feedback v3.87.0 - NotFoundError - EXTERNAL - Browser
Client: Browser
Type: EXTERNAL
Tutanota version: 3.87.0
Timestamp (UTC): Wed, 25 Aug 2021 11:43:20 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
NotFoundError
Error message: 404: Mhx6mvp----0 | GET /rest/sys/customer/MVvA3cS--3-0
Stacktrace:
NotFoundError: 404: Mhx6mvp----0 | GET /rest/sys/customer/MVvA3cS--3-0
at ai (https://test.tutanota.com/common-min-3bc23135.js:1:2210)
at XMLHttpRequest.p.onload (https://test.tutanota.com/worker.js:1:101483)

**Comment by vaf-hub** [comment]
**Test notes**:
This bug fix is not testable after #3434 is merged because external users will no longer be able to open the 'CalendarEventEditDialog'.
