### ISSUE TITLE
Contact form request behaves badly when account in blocked state

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3429]
**reproduction steps**
* create contact form on an account
* get the account into a state like INVOICE_NOT_PAID
* visit contact form
* make request
After trying to send, the client receives an `AccessBlockedError`, which results in the client trying to refresh, which in firefox at least will pop up this dialog: 
![Screenshot from 2021-08-27 17-20-20](https://user-images.githubusercontent.com/22109738/131150786-e9b0aeec-842f-4283-a12f-deedba1c87d3.png)

We should handle errors when sending contact form requests, but if the owner of the contact form is in a deactivated state, we should just not make it available until they have rectified their account state.

**Comment by vaf-hub** [comment]
We do not support contact forms anymore.
