### ISSUE TITLE
include icon in Triple-T Gradle Play Publisher for better F-Droid support

### ISSUE THREAD

**Issue by eighthave** [tutao/tutanota#3435]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

If the app entry does not provide the icon to f-droid.org, it is extracted from the APK.  This is not always the best version, and the F-Droid client needs to download it for each new release.  If the app entry does provide the icon Triple-T Gradle Play Publisher, then the quality is guaranteed, since that file is copied, and F-Droid client will cache the icon until it changes.

**To Reproduce**
1. Go to F-Droid then Settings
2. Set "Over Data" to the middle, "on demand".
3. Set "Over WiFi" to the right, "always".
4. When there is a new Tutanota release, check the Latest Tab 
5. The app icon will be missing:

![Screenshot_20210830-183218](https://user-images.githubusercontent.com/143465/131373166-ee95e189-eee6-451f-9bef-82f56e4749b1.png)

**Expected behavior**

The app icon should be there. 

**Additional context**

 The icon should be added to this git repo under _app-android/app/src/main/play/listings/en-US/graphics/icon/_.

Tested with F-Droid v1.13.1 but is probably relevant to all recent F-Droid releases, and third party clients as well.

----

Test notes:
 - [ ] Regression testing for app icon on Android

Metadata will be tested after F-Droid release

**Comment by charlag** [comment]
@eighthave is there any docs on what specs icon should have? is it like in Play store?

**Comment by eighthave** [comment]
yeah, following the Play store specs will work but f-droid.org isn't as strict. 
  IIRC Play requires 512x512 but f-droid.org will just use the PNG you specify.
