### ISSUE TITLE
Admin client build does not reflect changes to tutanota-3

### ISSUE THREAD

**Issue by rosso-ptg** [tutao/tutanota#3440]
When working with a local version of tutanota-3 in admin client, the admin client's build process currently does not:

- [x]  the build should use the updated files if tutanota-3 source files change

- [ ] update flow output when tutanota-3 source files change

In order to improve the overall development experience in admin client, both these things are supposed to work.

**Comment by bedhub** [comment]
We updated the source files in tutanota repo (removed assignement to _viewController and also removed attribute definition of _viewController ) but we were able to execute "node make" without reporting any error.

But the changed code was actually used by the new admin client build and created a runtime when logging in as expected.

**Comment by vaf-hub** [comment]
We incremented the build server version for the admin client and it should work now.
