### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3450]
Some users in reports are reporting this error:

```
Stacktrace:
RangeError: Invalid time value
at dr (https://mail.tutanota.com/main-977a37ac.js:1:19841)
at Mn.setDate (https://mail.tutanota.com/date-f931fe20.js:1:89408)
at https://mail.tutanota.com/calendar-view-fcc9cc77.js:1:3084
```

The error message is from the browser:
https://stackoverflow.com/questions/54462227/rangeerror-invalid-time-value

Messages from users:
> keine eintrage im kalender möglich ubuntu touch

> Sony F8131. Kontakte und mail o.k. :-) beim Kalender stuerzt die App immer leider ab.

> Kalender stürzt über Smartphone mit Betriebssystem Ubuntu Touch regelmässig ab. Browser ist Morph Browser.LGUbuntu Touch

> Every time I log into Tutanota, there is an error message - it has been happening for over a week, over Browser (Chromium, on Mac - and the F-droid app on Android). Just as I log in, the first thing that pops up is this error message, and then nothing else happens so it all works just fine. Thank you!

> Tried to add an event on calendar

> ich weiss nicht was ich getan habe. Ich kann denn Kalender nicht nutzen.

**Comment by charlag** [comment]
@johnbotris any idea if this is still a problem?

**Comment by johnbotris** [comment]
The most recent report seems to be from November 7th

**Comment by charlag** [comment]
@johnbotris that's pretty old, I will close this for now
