### ISSUE TITLE
Better template search results

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3462]
As a user i am searching for email templates in the template dialog. If i enter multiple search words i expect that all of the words must be included in the email template or title. Right now it is sufficient that one matches.

**Comment by bedhub** [comment]
Instead of hiding templates that do not match all words we change the order of the results. Entries that match more words are shown on top. This is similar to the FAQ search function.

**Comment by vaf-hub** [comment]
### Test notes:

- [ ] Verify the search in the support dialog still works (all entries that have at least a partial word hit should be shown) and results are sorted correctly. Sorted by the following priority (the same for knowledge base and template search):
1. full query string
2. more different words from query string matched
2. more full word matches
3. more partial word matches
- [ ] Verify searching in knowledge base `description`, and `title` works.
- [ ] Verify searching in knowledge base `keywords` array works.
- [ ] Verify searching in templates works and hits in different languages are found.
- [ ] Search for a tag by starting the query with "#" like "#my query" and make sure only results that have a hit in tags are displayed.
- [ ] In any search verify that adding white spaces (" ", "\n", "\t" etc.) to the query string does not change the results.
