### ISSUE TITLE
update keytar to v7.7.0

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3467]
keytar switched to N-API prebuilds (https://github.com/atom/node-keytar/pull/331). this has a few consequences:

* there are no dedicated binaries for electron 13, breaking the local desktop build which tries to fetch them
* the local keytar build postinstall script needs changes

**Comment by bedhub** [comment]
**Test notes**
On all desktop client platforms (windows, linux, macos)
- [ ] Check that after updating desktop client calendar event reminders are scheduled correctly.
- [ ] Uninstall old client / install new one and receive  new event reminders.
