### ISSUE TITLE
Logo proposal for Tutanota

### ISSUE THREAD

**Issue by moenawar85** [tutao/tutanota#348]
Hello Sir... I would like to contribute with your project by created a new logo. I'm waiting for your response and answer, If you like it I will send the original file that editable in CDR / PDF and PNG also. If you have any suggestion with color or something else I will fix it.
![tutanota logo](https://user-images.githubusercontent.com/36834147/39132215-81cb349e-473b-11e8-93a3-9ea3c7af5a20.png)

Best regards, Moenawar.
Thank you indeed.

Discord: @moenawar#1364
Twitter : @moen85
Steemit: http//www.steemit.com/@moenawar

**Comment by armhub** [comment]
Hi Moenawar, thanks a lot for these logo proposals! We will have a look at them in the team and get back to you.

**Comment by armhub** [comment]
We will currently not change the logo, but we will keep this in mind for the future. Thanks again!
