### ISSUE TITLE
Create Crypto Module

### ISSUE THREAD

**Issue by rosso-ptg** [tutao/tutanota#3486]
When discussing how to extract a low level API module (see #3485) from tutanota-3 we have tracked/analysed the dependencies we would have to extract into distinct modules. One module that we would need to extract, is all the crypto stuff. This would include pretty much anything in the worker/crypto directory except for CryptoFacade.js and InstanceMapper.js

We could start working on this as soon as the common/utils module has been created (see https://github.com/tutao/tutanota/issues/3184) since the crypto stuff only depends on some of the utils stuff.

**Comment by johnbotris** [comment]
# Testing
- [  ] Crypto functionality is still working
