### ISSUE TITLE
Taskbar Flicking on emails in darkmode when scrolling

### ISSUE THREAD

**Issue by theoasispc** [tutao/tutanota#3489]
- [ Yes ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ Yes ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

Screen flicking (White to black) on taskbar (Eg Reply/forward) when scrolling in a email on dark mode theme. 

**To Reproduce**
1. Go to 'A email'
2. Click on 'A email'
3. Scroll down to 'the middle or more'
4. See error Screen flicking on taskbar

**Expected behavior**

No screen flicking on taskbar in dark mode

**Screenshots**

https://imgur.com/a/wuf8DiA

**Smartphone (please complete the following information):**
 - Device: [LG V20]
 - OS: [Android 8.0]
 - Version [US996]
 - Software Version [US99620f]

**Additional context**
![Capture+_2021-09-13-16-39-33](https://user-images.githubusercontent.com/75642019/133025192-98d1d32a-5a56-442f-8ec2-c85bfec00e09.png)

**Comment by charlag** [comment]
Hi, thanks for the bug report.
Does it happen to all emails with background in dark mode or is a specific one? So far I have not seen this

**Comment by theoasispc** [comment]
Hi, 

It happen with emails that have a image on them, text only emails work fine without flickering

**Comment by theoasispc** [comment]
Should I include a video of the bug? @charlag

**Comment by theoasispc** [comment]
When I change the GPU Render to OpenGL (Skia) the problem is fixed but when I set it to OpenGL (Default) the flicking problem is there

**Comment by charlag** [comment]
@theoasispc video might be helpful but I suspect we have nothing to do with it.
Do you use stock ROM or something else?

**Comment by theoasispc** [comment]
I will make the video in the next few days aspa. I use the stock US996 rom from LG

**Comment by theoasispc** [comment]
I think its a issue with OpenGL (default) and not with Tutanota because I'm been using OpebGL (Skia) for a few days and the flicking is totally gone. So I'm going to close it. :) Thanks for the help @charlag
