### ISSUE TITLE
Purge trash button becomes invisible on Firefox

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#349]
Using Firefox (v59), mail.tutanota.com. The button still works when clicked, it just disappears most (but not all) times I click the Trash folder.

https://i.imgur.com/QBp1fci.mp4

edit: Ubuntu 16.04 if that helps

**Comment by blurakkun** [comment]
Still applies in Firefox 60

**Comment by asteintutao** [comment]
does not happen on ubuntu firefox 61

**Comment by blurakkun** [comment]
I opened a clean Firefox profile and there's no problem, so I must have an extension interfering with it or something. Sorry, I should have tried that in the first place.

**Comment by blurakkun** [comment]
Well, I found out what caused it: setting 'privacy.resistFingerprinting' to true in about:config. I don't know if that's within your scope, but at least if anyone else complains of the same issue we know where the problem is.

**Comment by charlag** [comment]
A-ha! Thanks a lot, we need to check it, maybe it has something against invisible things.

**Comment by mpfau** [comment]
Animations don't work as expected as timings are random when `privacy.resistFingerprinting==true`.
