### ISSUE TITLE
Bug: Android: Email Search: Period of time changes automatically to a smaller period after a few days.

### ISSUE THREAD

**Issue by AuthenticPumpkin** [tutao/tutanota#3497]
On the Android app, after I set the Email Search Period of time to anything from a few months to 2 years so that I can make instant searches, after a few days (maybe post updates?) it changes automatically to a smaller period that is around a month or so, which leads to a long wait time to reindex all emails before I can search and hampers productivity.

**Comment by charlag** [comment]
@vsinghsanwal hi, that does sound bad, sorry to hear that.

Please use bug template to report issues next time.
Can you tell which Android and app versions do you use?

If you go to Settings -> About -> Send logs and check indexer logs do you see that the index was reset?

**Comment by vsinghsanwal** [comment]
Hi! This has been happening on the last 2-3 app versions. I an always on the latest from github releases, currently -

 Tutanota version: 3.88.0
User agent:
Mozilla/5.0 (Linux; Android 11; Pixel 4a Build/RQ3A.210905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.82 Mobile Safari/537.36

The problem has become worse now, previously it would stay at the 1 or 2 year period of time I had set for a few days, now it resets back to the the last 20-30 days within a day of indexing for a year :/

Unable to understand the logs from About, would you like me to send them somewhere?

**Comment by charlag** [comment]
@vsinghsanwal you could send them to hello or you could check indexer logfile when the search index was recreated

**Comment by charlag** [comment]
@AuthenticPumpkin thanks for the logs, unfortunately I don't see traces of search index being deleted yet (there should be a special file if it would be the case)

**Comment by AuthenticPumpkin** [comment]
The problem still persists, in fact now the search index recreates from scratch when I try to search 2-3 days after creating it in the android app. Hoping it can be fixed because it removes my only use case for a premium account. Is there anything else I can help with to help diagnose the issue?

**Comment by charlag** [comment]
I am pretty certain that the storage gets purged one way or another, most likely because the device was full. We do not observe this behavior.
