### ISSUE TITLE
Email aliases not shown in user management

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3501]
How to reproduce:
1. Prepare an account with at least 2 users and at least one email alias each
2. Open user management and either 
  a) open the email aliases expander of one of the users and close it again
  b) open one of the users but do NOT open the alias expander
3. Try to open the email aliases expander of another user
-> No email aliases are shown. Even when going back to the first user they are not shown any more now.

Reproduced in Linux desktop client v3.88.0

# Testing notes
- [x] Follow reproduction steps, and the correct behaviour occurs (the list of aliases is shown)
- [x] When any expander is hidden, it's children are not in the taborder (e.g. in the MailEditor, if cc/bcc are hidden, then tabbing will skip them (check this after having opened and closed the expander as well))
- [x] The expanders always expand and contract correctly (try doing it rapidly as well)
- The expander button renders correctly **in all supported browsers** (text and icon display horizontally rather than vertically)
- [x] firefox
- [x] chrome
- [x] safari

**Comment by bedhub** [comment]
I cannot reproduce this case so far on my machine using the tutao account and switching between the users. The email alias expander always shows up and shows the correct results. Is it for newly created accounts/users?

**Comment by bedhub** [comment]
I can confirm now that i can reproduce this case when switching between users with collapsed email expander. Description has ben updated.
