### ISSUE TITLE
[Android] Tapping a notification doesn't open correct folder, or the email

### ISSUE THREAD

**Issue by pslyman** [tutao/tutanota#3504]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When tapping a notification for a new email, it defaults to open the inbox. If the email is sorted by folder, it does not open that folder. Alternatively, opening a notification does not open the email directly (likely because it has not been fetched yet). 

**To Reproduce**
1. Set up a domain alias or sender to be automatically sorted into a folder
2. Send a test email to yourself
3. Open the notification (closing the app from Overview first does not effect the results)
4. The app defaults to opening Inbox. The email will show up briefly, then is whisked away into the right folder. 
Then you have to go hunt for the email through the sidebar

**Expected behavior**
You tap on the notification, and you're immediately brought to a place where you can see it rather in a list, or directly. 

**Screenshots**
(not really applicable)

**Smartphone (please complete the following information):**
 - Device: Asus ROG 5 and OnePlus 7 Pro
 - OS: Android 
 - Version: 11

**Additional context**
As I'm learning about how this app works, I'm assuming that the notification service runs independent of the main app. If a notification is received, a re-fetch of latest emails isn't triggered until you open the notification or re-open the app. Thus, the email is not yet available until after the app is opened and the re-fetch is done. Understandably, the notification cannot immediately open the email. However, the notification does know the domain alias the email was sent to, so there is some information provided on which inbox the email folder to sort into if there's a rule set by receiver.

Then again, perhaps the amount of information transferred between the notification and the app is very limited, making the infrastructure for this feature a limiting factor. 

Is it possible for the notification to guide where the app opens at all, and to take into consideration the folder that email belongs to? 

Understandably, if this bug is something that can't be fixed without new vulnerabilities, it can be left. But it was worth mentioning since I rely on aliases and a series of folders to keep my email organized. Whenever I tap a notification, it can take up to 10 (and sometimes 20 with a slower connection) seconds to find the email, the open it.

**Comment by charlag** [comment]
Hi
This is not a bug, it wasn't included in capabilities originally.
First of all, we don't transmit info about email itself besides the receiving address.
Second, the email might have been moved around and it might not be there anymore.
We could include tracking across inbox rules but it will be some effort.

I will close it for now as it's not a bug, maybe we will revisit notifications functionality later.
