### ISSUE TITLE
Seems like your browser is not supported or outdated

### ISSUE THREAD

**Issue by tonyrci2** [tutao/tutanota#3505]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
After upgrade to latest version of the app on iOS 11.4, seeing message: "Seems like your browser is not supported or outdated".

**To Reproduce**
1. Open App on iOS 11.
2. Observe message above.

**Expected behavior**
The app should load to login screen or inbox.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 11.4
 - Version 3.87.2

**Additional context**
If possible, please set minimum iOS version for release 3.87.1 and above so we can revert to the previous release which did not exhibit this issue.

**Comment by bedhub** [comment]
Please update your system in order to continue using Tutanota.

We maintain a list of supported browsers and operating systems here:
https://tutanota.com/blog/posts/browser-support/
