### ISSUE TITLE
Gift card display after purchase does not show a qr code

### ISSUE THREAD

**Issue by rosso-ptg** [tutao/tutanota#3516]
**To Reproduce**
1. Click on gift card button in side bar
2. Purchase a gift card
3. See gift card share screen with buttons to send it. QR Code is not displayed on that screen.

**Expected behavior**
QR code is displayed on share screen for gift card

 - Version 3.88.0

The content of svg disappears after sanitizing.

**Comment by johnbotris** [comment]
This was broken by an update to DOMPurify with 0b621701e9ae82844696b6acbf30840842c0c639, which went out with v3.82.15. Looks like poor gift cards weren't thought of during testing :(

**Comment by johnbotris** [comment]
# testing
- [ ] The QR code on gift cards is rendered
- [ ] Sanitization still works properly in all cases
