### ISSUE TITLE
Calendar reminder notifications do not give the day 

### ISSUE THREAD

**Issue by pslyman** [tutao/tutanota#3519]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Let's say I've created an event for Friday at 9:00 AM, and set up a reminder for 1-day before the event. Thursday morning at 9:00 AM I will receive a reminder notification that says "9:00 <event_name>". I will panic thinking it's happening that morning, only to realize that the reminder was actually for Friday, not Thursday. However, the event did not say "Tomorrow, 9:00" or "Sep 24, 9:00". This is further a problem if you set up a reminder for 1 week before the event, you'll receive a notification for the calendar event saying the time, and you'll not realize it's a reminder in advance, and instead think it's happening that day unless you have the foresight to verify. 

**To Reproduce**
1. Create an event for 2 days from now at 9:00 AM (or any other time)
2. Set up a notification reminder for 1 day before event.
3. Wait until notification is received a day in advance. Note that it does not give the day, thus giving the notion that the event is actually happening a day ahead of schedule. 

**Expected behavior**
Rather option 1 or 2:
1. "Happening in 1 day: 9:00 <event_name>" (indicating that it's a reminder _before_ the event)
2. "September 24, 9:00 <event_name>" (indicating the actual date it is happening) 

**Screenshots**
(not needed, but I can provide if needed)

**Smartphone (please complete the following information):**
 - Device: Asus ROG 5 and OnePlus 7 Pro
 - OS: Android
 - Version: 11

**Additional context**
The idea here is to make the reminder notifications useful, and to indicate their intent. If the notification is happening before the event takes place, that should be indicated in the notification. Last thing anyone wants is to wish someone Happy Birthday a day early, only later to realize they set up a reminder for 1 day before event and didn't realize.

**Comment by charlag** [comment]
Hi
Yes, that's true and I've also had issues with this. Thanks for reminding us.

**Comment by pslyman** [comment]
Happy to help. I'll note that the desktop client does show these notifications correctly, it's just missing on mobile. Thanks!

**Comment by pappasadrian** [comment]
Yes I had this happen to me, I saw the notification for the event at 18:00, when it was 18:00, so I freaked out and thought I had forgotten about my meeting, and consequently sent apologetic emails and rushed to get into a call. The mobile notification failed to indicate that it is in 24 hours and now now, causing me random stress and a bit of humiliation with the uncalled for apology.

**Comment by nokhub** [comment]
## Test notes
* [ ] use the client on an Android device
* [ ] create a calendar event for the next day and select reminder before event "1 day"
* [ ] choose a time for the event which will give you a notification during the next few minutes
* [ ] make sure the text of the notification is displayed in the following format: e.g. Fri 25 Nov 12:31 ...
* [ ] create an event for the current day and select a suitable reminder
* [ ] when the notification arrives, make sure that it displays only the time and not the whole date: e.g. 12:31 ...
