### ISSUE TITLE
Impossible modification combination UPDATE CREATE

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3521]
When I log into one of my test system accounts. Hard to say if it's related to the release. (probably?)

error 
Object { name: "ProgrammingError", message: "Impossible modification combination UPDATE CREATE {\"_type\":{\"app\":\"sys\",\"type\":\"EntityUpdate\"},\"_id\":\"sXtCIw\",\"application\":\"tutanota\",\"instanceId\":\"Mk7rRK9--3-0\",\"instanceListId\":\"MKFEql9-2o-0\",\"operation\":\"0\",\"type\":\"Mail\"}", stack: "ProgrammingError. Impossible modification combination UPDATE CREATE {\"_type\":{\"app\":\"sys\",\"type\":\"EntityUpdate\"},\"_id\":\"sXtCIw\",\"application\":\"tutanota\",\"instanceId\":\"Mk7rRK9--3-0\",\"instanceListId\":\"MKFEql9-2o-0\",\"operation\":\"0\",\"type\":\"Mail\"}\n", data: undefined }

**Comment by charlag** [comment]
Could not reproduce, probably was related to #3522
