### ISSUE TITLE
Bromite webview not supported as supposed to system webview

### ISSUE THREAD

**Issue by Thewisem** [tutao/tutanota#3528]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When I change the weview to bromite system webview, it says unsupported even though android system webview of that same version is supported. This wasn't an issue until the recent releases
**To Reproduce**
1. Download bromite system Webview
2. Replace android system webview
3. Open the app

**Expected behavior**
It should work properly and not show unsupported.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung Galaxy Tab A
 - OS: [e.g. iOS8.1] Android 7.1.1 Nougat
 - Version [e.g. 22] 3.88.3

**Additional context**

**Comment by charlag** [comment]
Which version of Chromium is it compatible with? If it doesn't support the feature we need then it doesn't support the feature we need (and we don't need that much)

**Comment by Thewisem** [comment]
Bromite System webview: Version 93.0.4577.83
This isn't supported but
Android System Webview: Version 93.0.4577.82
Is supported. Reason: No Idea

**Comment by charlag** [comment]
We do not support Bromite, if it works, it works, if not, they need to update Chromium (even though we don't use anything crazy)
