### ISSUE TITLE
Escaped commas remain in calendar event location

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3542]
If the location of an event contains commas, Google calendar will escape them with backslash. We don't detect this and the backslashes are shown to the user in both the preview and the editor:

![Screenshot from 2021-10-11 15-44-54](https://user-images.githubusercontent.com/22109738/136800983-febacb6b-9eac-43a7-96af-3121dc67e4ec.png)

![Screenshot from 2021-10-11 15-47-03](https://user-images.githubusercontent.com/22109738/136801063-5babf623-991f-4a36-9dae-7dc269dcc993.png)

**Comment by johnbotris** [comment]
@vaf-hub I haven't looked into it

**Comment by rezbyte** [comment]
I believe this issue has been fixed since #6200 was merged. I tested importing an `ics` file with escaped commas in the location field and it displays fine.
