### ISSUE TITLE
Cannot receive pgp encrypted mails.

### ISSUE THREAD

**Issue by peterzam** [tutao/tutanota#3552]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When receiving encrypted email with PGP self-signed certificate, receive only "blank body" (but the subject is OK).

**To Reproduce**
1. Send PGP encrypted email from external email with receiver address's self-signed certificate.
2. Receive blank body

**Expected behavior**
Show encrypted message or encrypted message as attachment.

**Not related to app nor version**

**Additional context**
If the receive address and certificate address are not the same, it attach body as "*encrypted.asc*" attachment.
It seems the server is trying to decrypt the body and unable to do it.

*P.S Sorry for the edits. I was a bit rush.*

**Comment by vitoreiji** [comment]
Cannot reproduce: I get the encrypted message as attachment.

If you are a premium user, please get in touch with support if you are still having problems.

PS: we do not try to decrypt PGP encrypted emails.
