### ISSUE TITLE
Title in agenda view is hard to understand

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#3564]
It says: "Agenda 13 Wed-Tue, Oct 26, 2021". 13 probably refers to the current date (October 13), but it is not immediately clear. Maybe it could say "Agenda Wed, Oct 13 - Tue, Oct 26, 2021"

**Comment by ganthern** [comment]
## Testing
check that the title shows the agenda time range in an understandable way for different languages.

* [ ] with start and end day in the same month
* [ ] start and end in different months
* [ ] start and end in different years
