### ISSUE TITLE
DatePicker accepts non-exisitng date

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#3565]
If I create an event and manually set the date to the non-existing date 11/31/2021 the event will be created on 11/3/2021. This is rather weird behavior. I would expect an error or at least the event to be created on Dec 1 or Nov 30 which are the closest dates

**Comment by wrdhub** [comment]
When navigating away from the date picker, by click or tab, it truncates the date to something valid (in this case, using just the 3). I think the calendar app has better visuals to indicate to the user which day is selected now, so I am closing.
