### ISSUE TITLE
Copy & paste mail with CTRL+A

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#357]
If I want to copy the whole text of a message and press CTRL+A, the mail folders get selected, too. I would expect only the mail content to be selected.

**Comment by charlag** [comment]
Closed by dbd3d548ff92fe2

**Comment by bedhub** [comment]
On Firefox Ctrl+A copies also the outer elements like body and view colums so you can't use this feature to copy and paste html content. Pasting the content as plain text is possible.
