### ISSUE TITLE
Not all apps recognise Tutanota as the default mailto application in windows

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3574]
We register tutanota as the default mailto by setting the registry keys under `HKEY_LOCAL_MACHINE > SOFTWARE > Clients > Mail`, but there are other choices like `HKEY_CURRENT_USER > SOFTWARE > Clients > Mail`. It seems like not all apps check the same key, for example MS Word is always opening in MS Outlook

## Update
We decided to change the approach because having two places where we can write registry keys leads to some problems (see #3787). Instead of deciding on `HKEY_LOCAL_MACHINE` vs `HKEY_LOCAL_USER` we will always use `HKEY_LOCAL_USER` to write registry keys (the only reason to not do that is for the admin to set mailto handler for all users but admin has other means to do that should they wish to).

## Acceptance criteria
 - [ ] Enabling integration in Tutanota settings writes Tutanota as available mailto:/MAPI handler for current user, it doesn't affect other users
   - [ ] per-user install
   - [ ] per-machine install
 - [ ] Disabling it removes Tutanota from default and removes Tutanota from the list of available mailto: handlers for current user, it doesn't affect other users
   - [ ] per-user install
   - [ ] per-machine install

## Testing
Two users, A and B
  - [x] Install locally for A, set mailto handler
    - [x] mailto: for A is handled
    - [x] MAPI works for A
    - [x] user B is unaffected
 - [x] uninstall locally, install globally, run for A
    - [x] mailto: for A is handled
    - [x] MAPI works for A
    - [x] user B is unaffected
 - [x] Run as B, enable integration
    - [x] mailto: for A is handled
    - [x] MAPI works for A
    - [x] mailto: for B is handled
    - [x] MAPI works for B
 - [x] Setting default download folder (at least on one system)

**Comment by charlag** [comment]
The situation is... complex cc @ganthern 
https://superuser.com/a/1119010/267277

**Comment by ganthern** [comment]
okay, seems like we need to be more judicious in applying the registry keys. 

again, thank you for your effort!

**Comment by ganthern** [comment]
So, in my tests, the demo version of Sage50 seems to be OK with a per-user install and a global install of tutanota in a fresh Win10 VM (if it doesn't choke on date formats and refuses to run at all).

* install tutanota desktop
* install Sage50 with all options
* use the dummy data to create an invoice or offer
* "Abschließen" -> "Mailen..."
* works _almost_ as expected: Sage writes the mailto mail address as `SMTP:info-gs@sage.de` which gets rejected by tutanota desktop due to the `SMTP:` prefix and replaced by an empty address. otherwise the attachment works fine.

I'll test this again with a system that has been "tainted" by thunderbird, but so far I can't see a fundamental problem.

**Comment by ganthern** [comment]
The registry entries for registering as a mail handler should be a little more well-behaved now.

## Testing
on a fresh windows machine with two users A and B: install tutanota desktop for A per-user and register/set it as the default mail handler, then check:
* [ ] user A can use Send as mail feature and mailto links with tutanota
* [ ] user B can not select tutanota as a mail handler in the settings

unregister, then uninstall tutanota and then reinstall per-machine

* [ ]  user A and B can select tutanota as default mail app
* [ ] both can use Send as mail feature and mailto links with tutanota

**Comment by macxcool** [comment]
Will do. Probably tomorrow.

**Comment by ganthern** [comment]
@macxcool, the checklist is part of our testing processes for the next release. It would be better to wait for the PR being merged, since this one depends on another PR in a different repo.

**Comment by sarashub** [comment]
MAPI is not working for local install (windows 10)

**Comment by charlag** [comment]
We discovered that it is somehow related to the .dll built on Windows machine. .dll built via Wine is bigger but works.

**Comment by charlag** [comment]
Should be fixed by depending on this release:
https://github.com/tutao/mapirs/releases/tag/mapirs-release-0.4.0

**Comment by charlag** [comment]
Clean global install, attempt to register:
```
Stacktrace:
Error: EPERM: operation not permitted, open 'C:\Program Files\test Tutanota Desktop\99dc225701c4bd5289ae99e7'
```

it seems like we still need to elevate permission to register when it's a global

**Comment by ganthern** [comment]
> Clean global install, attempt to register:
> 
> ```
> Stacktrace:
> Error: EPERM: operation not permitted, open 'C:\Program Files\test Tutanota Desktop\99dc225701c4bd5289ae99e7'
> ```
> 
> it seems like we still need to elevate permission to register when it's a global

This is happening because the client tries to write the registry script it needs to execute into its execPath, which is in `C:/Program Files` for global installs and read-only for normal users.

Putting it into the tutanota tmp directory should fix this.

**Comment by johnbotris** [comment]
Documents sent from applications such as LibreOffice aren't being attached
