### ISSUE TITLE
Don't save mail as draft when closing unless changes have been made

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#3580]
With the new minimization of mails we also save a draft upon closing the editor. This helps when finishing a mail and saving changes that have been made, however can get annoying when every close triggers a draft save.

It would be better and more convenient that we only save a draft if changes have been made to the mail. 

**AC:**
- If I do not change the body of the mail, pressing close should not trigger a draft save. Only when something has been changed (such as recipients, title, etc.) should we trigger a draft save. 

Discussed with @johnbotris @Pa7Hub , should be discussed again with @bedhub 

## Test notes
- [ ] Create a new email without writing anything in it.
- [ ] Close the email. It should not save a draft.
- [ ] Create another new email, but this time change something in it (upload an attachment, etc.)
- [ ] Close the email. It should save a draft.
- [ ] the above works with forwarding and replies
- [ ] when a draft is saved with a recipient from the contacts, then opened (without changing it) and the contact gets edited (loses the mail address), the draft is saved on closing it.
- [ ] notification mails for calendar event participants still work

**Comment by LewisMichaelHarold** [comment]
I have an android mobile device and my drafts are not saved when closing the app?

**Comment by Jlll1** [comment]
Maybe in case of empty messages we could just prompt the user if he wants to save it as draft? My Messaging app does that for empty messages.
