### ISSUE TITLE
Repeated events are randomly duplicated

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3589]
Originally from https://github.com/tutao/tutanota/issues/3502#issuecomment-922863186

When an event extends into another month, it is listed twice in the week view if both months are shown (Jan. 31 - Feb. 6 2022 for example). The steps to reproduce this duplicate listing are as follows:
   1. Set up an event from 15th January to 15th February, repeated Annually
   2. Switch to a week view (not month view) and get to the week where one month ends and the following begins
   3. The event is displayed as a bar at the section right bellow the day name and date, but it is incorrectly displayed twice

When the repeating event overlaps with itself we should show both but in the provided example there's no overlap yet it's displayed twice.

**Comment by wrdhub** [comment]
Cannot reproduce anymore.
