### ISSUE TITLE
Convert more parts of iOS app to Swift

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3591]
Working with Objective-C is hard and Swift has good support. Swift is more type-safe and has more libraries available.

We should make use of Swift serialization built-ins for storing alarms and for webView communication: https://developer.apple.com/documentation/swift/swift_standard_library/encoding_decoding_and_serialization

and of Result type for error handling for callbacks: https://developer.apple.com/documentation/swift/result

For synchronous functions error handling should be done with throwing functions.

We should not convert or significantly change cryptography code and code that is used from it: TUTCrypto, TUTAesFacade, TUTLog, TUTErrorFactory.

## Test notes
 - [ ] Receiving notifications
 - [ ] Logout
 - [ ] Selecting and sending files (correct size & name)
 - [ ] Downloading and opening files
   - [ ] Suspension active while downloading
 - [ ] Download invoice
 - [ ] Changing language
 - [ ] Log in, make some alarms, delete push identifier, restart the app (without login), check that alarms are invalidated
 - [ ] Receive alarms when the app is in background
 - [ ] Receive encrypted email and make sure it's decrypted on the phone
 - [ ] Changing themes (including whitelabel)

**Comment by johnbotris** [comment]
Downloading attachment while suspended:
* I tried once, and the download failed with an error dialog but no error was logged
* Second try at the download was successful
