### ISSUE TITLE
Fix text "0 Shared Mailbox" in subscription

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#360]

**Comment by asteintutao** [comment]
fixed by f478b07d9f1e7e7bc7907b52629a5d9b75e8f7ab

**Comment by charlag** [comment]
Now it can be "1 shared mailboxes"
Easiest would be to not use plural at all and just do "shared mailboxes: 1"

**Comment by armhub** [comment]
Label should be "Shared mailbox" instead of "Shared mailboxes" at some places.

**Comment by ganthern** [comment]
It's still saying "1 Shared Mailboxes". en.js on master is correct, but the one on PhraseApp was wrong, which I fixed.
