### ISSUE TITLE
MAPI functionality doesn't always work even when configured

### ISSUE THREAD

**Issue by macxcool** [tutao/tutanota#3602]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When Thunderbird is installed and configured for MAPI, Tutanota does not set the HKCU:\SOFTWARE\Clients\Mail 'Default' value and doesn't work with some software (Sage 50 Accounting, specifically). I'm not sure about the Thunderbird thing, but Thunderbird *does* work with Sage 50 on the older setup I tried. On the newer one Sage 50 can't send via MAPI with either Thunderbird nor Tutanota. Strange.

**To Reproduce**
1. Install Thunderbird (not sure if the Thunderbird angle is relevant, though)
2. Make sure Thunderbird is set as the default Mail handler
3. Install Tutanota
4. Set up Tutanota as default mail handler (within Tutanota and Windows Default Apps)
5. Trigger a MAPI call from Sage 50 accounting by emailing an invoice.

**Expected behavior**
Tutanota should set the HKCU:\Software\Clients\Mail value?? and completely take over from Thunderbird as mail handler and should work with all MAPI clients.

**Screenshots**
![sageMAPIError](https://user-images.githubusercontent.com/2531654/138733355-d5a53537-964d-43f4-98d3-9979dd952eca.png)
This is the error that Sage 50 2013 shows. I think that it's looking for something in the Windows registry and doesn't find it, so it doesn't even try to load the MAPI dll.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit

**Additional context**
Tutanota MAPI works fine with things like the right-click menu even when Thuderbird is installed. It's just this registry key that seems to be the problem? I tried this with two different versions of Sage 50. The older one throws a nasty error when I change the registry 'Default' value for the key to anything other than 'Mozilla Thunderbird'.

I'm starting to think that the Thunderbird angle is a bit of a red herring, though, because I tried a fresh install of Thunderbird, then Tutanota and Sage 50 2013, and I get the error in the screenshot regardless of which mail client is set up as default.
I'm not even sure this is a bug, but it seems like there's a piece of the MAPI puzzle missing still.

I tried to use Procmon to see what Sage 50 is trying to do but was unable to find anything useful. I can post a dump from it if you want?

I'd be glad to demo this over Discord or something like that. I'm not sure what other software to try which makes MAPI calls.

**Comment by jomapp** [comment]
This issue seems to be back on windows. Sometimes it works, but sometimes it doesn't. There seems to be a correlation with the client being in the foreground. When the client is completely closed it does always work.
