### ISSUE TITLE
Split NativeWrapper implementation

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3610]
`NativeWrapper` has two separate implementations for the main and worker threads, but they both live inside the same class. The worker only needs a thin wrapper to send messages to the main thread, while the main side is what actually needs to do the work. We should also move the `nativeApp` singleton onto the locator in both cases.

At least `fileApp` is pretty tightly coupled with the `nativeApp`, and it could be tricky to do this without also doing https://github.com/tutao/tutanota/issues/2890

**Comment by johnbotris** [comment]
# Testing

We need to ensure that all main <-> worker as well as web <-> native communication is still behaving properly. App bootstrap also needs to be checked. If at any point the app tries to access native interfaces from the web client, an error will be thrown, so we need to make sure there are no cases where this will happen (always checking which client we're in before trying)

- Native functionality works in:
    - [ ] Electron
    - [ ] Android
    - [ ] iOS
- [ ] In web, no errors will be thrown due to invalid attempts to access native.
- [ ] Worker/main communication is still working as expected
- [ ] App bootstrap completes successfully in both web and native (no deadlocks, errors due to timing, etc)
- [ ] Logging out and back in works
- [ ] Refreshing app works normally

**Comment by johnbotris** [comment]
Seems like opening a mail from a notification has broken

**Comment by ganthern** [comment]
refreshing the web app doesn't open the same page when there's more than one set of credentials saved (also happens on prod)

**Comment by johnbotris** [comment]
> refreshing the web app doesn't open the same page when there's more than one set of credentials saved (also happens on prod)

I believe this is intended

**Comment by johnbotris** [comment]
notifications don't seem to be coming on mac

**Comment by sarashub** [comment]
importing a calendar is not enabled on mobile so I cannot test it

**Comment by johnbotris** [comment]
> notifications don't seem to be coming on mac

False alarm
