### ISSUE TITLE
MacOS, Firefox:  Remains at log in screen after enter credentials, and submit

### ISSUE THREAD

**Issue by dtaviation** [tutao/tutanota#3618]
- [X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X ] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Remains at log in screen after entering credentials, and submit submitting, or autologin.   No message is desplayed.  Expected behavior is showing emails screen.

**To Reproduce**
1. Go to 'https://mail.tutanota.com/login.
2. Enter credentials and click "Log In" button, briefly shows moving circle in the "Logging In" box.
3. Scroll down to '....'  N/A
4. Unfortunately, there is no error.

**Expected behavior**
Show emails screen.

**Screenshots**

**Desktop (please complete the following information):**
MacOS 10.13.5
Firefox 93.0 (latest)
Tested in Firefox troubleshooting mode to ensure that Firefox extensions were not in use.
**Bug in web app**

**Describe the bug**
Remains at log in screen after entering credentials, and submitting, or autologin.   No message is desplayed.  Emails are not display, only the log in screen.  Other alias also do not work.  Same credentials with same Firefox on Fedora Linux works properly.

**To Reproduce**
1. Go to 'https://mail.tutanota.com/login.
2. Enter credentials and click "Log In" button, briefly shows moving circle in the "Logging In" box.
3. Scroll down to '....'  N/A
4. Unfortunately, there is no error.

**Expected behavior**
Shows emails screen.

**Desktop (please complete the following information):**
MacOS 10.13.5
Firefox 93.0 (latest)
Tested in Firefox troubleshooting mode to ensure that Firefox extensions were not in use.
)

**Comment by charlag** [comment]
@dtaviation does it still happen?

**Comment by dtaviation** [comment]
It does.




Mar 4, 2022, 07:47 by ***@***.***:

**Comment by charlag** [comment]
@dtaviation any errors in the dev tools?
