### ISSUE TITLE
Invalid login credentials when using other devices

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3620]
We receive reports from time to time that users are not able to login into their accounts when using other devices. They can login on their desktop computer for example but when they try to login on their mobile devices they get the error message "Invalid login credentials". 
It sounds like that they just have a typo when entering the credentials but as we receive similar reports from time to time we want to collect more information about this problem.

Here is an example user report:

> I just experienced an odd problem when logging into my account and wondered whether you have seen this before.
> In summary, I cannot log into the account using my iPhone 11 running iOS 15.0.2. When I try the message is: "Invalid login credentials. Please try again."
> I can log in using my iPad, also running iOS 15.0.2.
> I can log in using my Windows 10 desktop.

**Comment by brshub** [comment]
After updating iOS to version 15.1 the login seems to be working correctly.

**Comment by demigodryoxviii** [comment]
This is my problem now.
