### ISSUE TITLE
Calendar current day circle not centred

### ISSUE THREAD

**Issue by ziomek64** [tutao/tutanota#3624]
**Bug in mobile app**

**Describe the bug**
Just look at the picture and 31 number. This might be due to the fact i have tall phone. 21:9 aspect ratio. I dont have other phones so i dont know if its correct there

**To Reproduce**
1. Go to calendar

**Expected behavior**
Circle (or day number) centered correctly. Dunno which of them is wrong lol

**Screenshots**
![Screenshot_20211031-183341_Tutanota.png](https://user-images.githubusercontent.com/84880432/139595380-bc69a8d5-cd59-49f8-b727-6d67df0eddaf.png)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia 10@
 - OS: Android 11
 - Version - tutanota version? 3.89.5

**Comment by vaf-hub** [comment]
You can ignore commit https://github.com/tutao/tutanota/commit/61eded46df640937eba3f2fa2b329a2108ee4be5 I accidentally referenced this issue.

**Comment by v011** [comment]
Same for me. I drew a vertical line to highlight the circle's alignment. Note also that single digit dates are not centered too.

![image](https://user-images.githubusercontent.com/72566583/148298722-a39b8893-245c-48d5-80a7-1c48171a82bb.png)

**Comment by johnbotris** [comment]
# Testing

- [ ] In the calendar, the number in the current day indicator is centered properly
    - [ ] In desktop mode
    - [ ] In mobile mode (either in app or using browser devtools)
