### ISSUE TITLE
No button for image embed

### ISSUE THREAD

**Issue by cunninglemming** [tutao/tutanota#3632]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
A button for image embed is missing from text editing tools

**To Reproduce**
1. Start composing new message
2. Open text edit tools
3. No image embed button

**Expected behavior**
A button should be present

**Screenshots**
![Actual](https://user-images.githubusercontent.com/87859114/140050587-307cf1b4-6f90-4bf8-8088-97c5845bb0e8.png)
The missing button is present on screenshot from documentation:
![According to docs](https://tutanota.com/resources/images/howto/tutanota-text-edit.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: LineageOS 18.1 (Android 11)
 - Version: 3.89.5 (F-Droid)

**Additional context**
Adding images as attachments is working as expected

**Comment by charlag** [comment]
@cunninglemming we don't support it on mobile currently

**Comment by charlag** [comment]
@cunninglemming at least it's not a bug and we need to plan whether/how to do it. Currently there are technical limitations on passing big amounts of data over the bridge and we would have to work around that.

**Comment by cunninglemming** [comment]
@charlag How come those limitations do not apply to attachments? I really don't understand this. And it's a bug because it breaks the user expectations.

**Comment by charlag** [comment]
@cunninglemming you don't see the whole attachment on your screen, it is just a reference to a file. To display data we need to transport it to the webview and we can't do that yet. I understand that it would be great to have and it's odd from the user perspective, we will fix it eventually
