### ISSUE TITLE
Calendar eventCopy_msg shown even when changes are saved

### ISSUE THREAD

**Issue by starsep** [tutao/tutanota#3637]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
While editing event created by another user in the calendar I own I see message
`eventCopy_msg`: This event was sent from another calendar. Changes to the event will only be visible in your calendar.
Relevant code: https://github.com/tutao/tutanota/blob/bb18f5b7e212876746e118ec840a3ad1cb1f183a/src/calendar/view/CalendarEventEditDialog.js#L363-L367

**To Reproduce**
1. Create calendar
2. Share it with a user with read/write rights
3. User creates event
4. Once you edit this event `eventCopy_msg` is shown
5. Make changes and save
6. Changes are synced to both users' calendars - contradicts the message.

**Expected behavior**
I expect this message not to be shown.
It is expected that changes are saved (correct behaviour already).

**Screenshots**
![image](https://user-images.githubusercontent.com/2798728/140470861-c8b05cc5-6bd8-42d7-ac3f-3137c041f787.png)

**Versions checked:**
 - Version 3.89.9 (web/desktop Linux),
 - Version 3.89.5 Android/F-Droid

**Comment by rezbyte** [comment]
I do not believe this occurs anymore.
