### ISSUE TITLE
Change credential authentication enrollment process

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3646]
As described in #3444 we defined that upon the first login or on migrating from previous app version we would display a dialog letting you select credential authentication method.

This led to some difficulties when we managed to select a method and create a key but failed to encrypt credentials (#3645). The user is then left in the broken state and cannot store or load credentials anymore.

Another issue is that user experience after the first login is far from perfect, user is presented with many conflicting dialogs at once.

Both issues need to be addressed separately but to release fingerprint right now we will change opt-in process to select "automatic" authentication method without user interaction. User can then change the authentication method in settings (the same way it works now).

With this change we don't risk locking someone out of their app on opt-in.

---

## Test notes
 - [ ] Fresh app install, user is *not* prompted for auth method after login
   - [ ] Android < 11
   - [ ] Android >= 11
 - [ ] Migrate from v3.89.5, should still be able to use credentials
   - [ ] Android < 11
   - [ ] Android >= 11
- [ ] Regression testing for changing auth methods in settings
   - [ ] Android < 11
   - [ ] Android >= 11

**Comment by ganthern** [comment]
## Android 7.0
- [x] Fresh app install, user is *not* prompted for auth method after login
- [ ] Migrate from v3.89.5, should still be able to use credentials
- [x] Regression testing for changing auth methods in settings

Note: Auth method is set globally (can't have one account with biometrics and one that's unlocked automatically), is that intended?

**Comment by charlag** [comment]
Yes, auth method is global

**Comment by ganthern** [comment]
## Android 7.0
- [x] Fresh app install, user is *not* prompted for auth method after login
- [x] Migrate from v3.89.5, should still be able to use credentials
- [x] Regression testing for changing auth methods in settings

## Android 12.0
- [x] Fresh app install, user is *not* prompted for auth method after login
- [x] Migrate from v3.89.5, should still be able to use credentials
- [x] Regression testing for changing auth methods in settings
