### ISSUE TITLE
iOS: Provide option to lock saved credentials with PIN/biometrics

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3653]
see #3444

---

## Test notes
 - [ ] Migrate from the previous app version
 - [ ] When there's no biometric enrolled, "biometric only" should not be available
 - [ ] Start authenticating and cancel, localized message should be shown on the login screen
 - [ ] Credential invalidation: select biometric, add another biometric (finger or face), try to log in. Credentials should be invalidated with a message
 - [ ] Automatic authentication
 - [ ] Password
   - [ ] When no biometric then just system password prompt is shown
   - [ ] When there's biometric then it should shown biometric and fall back to password if you don't provide the right biometric auth 
 - [ ] Biometric
 - [ ] Switching between methods

**Comment by johnbotris** [comment]
After keychain invalidation, credentials will be deleted, and the mode gets set back to automatic

**Comment by johnbotris** [comment]
* Have fingerprints enrolled, enable biometrics only.
* While app is running, remove all fingerprints
* Try to switch to automatic/system password
* an error occurs
* It is also not possible to login afterwards
