### ISSUE TITLE
Bugs with iOS fingerprint update

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#3656]
- Selecting 'biometrics', then adding a new fingerprint under settings will 'nuke' the app. It deleted my login data, didnt accept any fingerprints anymore (Error upon asking for fingerprint: "An unexpected error occurred") until I re-installed the app.

**Comment by johnbotris** [comment]
# Testing
* Follow description
- [ ] The error doesn't occur
(Keep in mind this has not yet been reproduced)
