### ISSUE TITLE
Language options for spellchecking displaying incorrect name

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#3659]
For Portuguese, all three options `pt`, `pt-BR` and `pt-PT` show the name "Portuguese, Brazil". Maybe it should be just "Portuguese", like English is just that.

![language_selection](https://user-images.githubusercontent.com/197261/141152705-3fee51a0-c6b4-4a6d-857e-808cbb6af952.png)

**Comment by ganthern** [comment]
Just showing "Portuguese" should be OK here since we also show the code in the same line, but we're using the same strings in the language selection, where no codes are shown.
