### ISSUE TITLE
[Android] Button icons not shown

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#3660]
Some users report that their buttons are empty, not showing the icons:

![empty-buttons](https://user-images.githubusercontent.com/197261/141259322-6befc0c7-4da7-4e55-8b82-dcf8f1c0bdd4.jpg)

Android version: 8.1.0

**Comment by charlag** [comment]
@vitoreiji I suspect that this is an old WebView problem. I didn't hear about it in a while.
