### ISSUE TITLE
App breaks on adding biometric

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3663]
After keychain invalidation, credentials will be deleted, and the mode gets set back to automatic. If all credentials are removed then this would be expected. However it also happens upon adding a new fingerprint

_Originally posted by @johnbotris in https://github.com/tutao/tutanota/issues/3653#issuecomment-966096552_

**Comment by charlag** [comment]
Fixed by 6857a7da44cfe61ae9471a60bd302a88002b9a89 and 2eb77c1992a4c8376a2ecd9934057bdbcbc4cbdf

**Comment by johnbotris** [comment]
# testing
* Have credentials locked with system keychain
* Add a fingerprint
* log in
- [ ] The keychain is invalidated, but mode isn't set to automatic

**Comment by johnbotris** [comment]
For now we will handle keychain invalidation the same in all cases. We might look into handling these cases differently in the future if it seems useful
