### ISSUE TITLE
Key invalidation is not handled in mode switching dialog

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3664]
* Have fingerprints enrolled, enable biometrics only.
* While app is running, remove all fingerprints
* Try to switch to automatic/system password
* an error occurs
* It is also not possible to login afterwards

First error message shows error code -3 for key invalidated, this is expected (though in this case, we should just try again i think)
If you try again unhandled error with code -25293

If you do the same thing but instead you invalidate the keychain by _adding_ a fingerprint, then the following error code is -50

_Originally posted by @johnbotris in https://github.com/tutao/tutanota/issues/3653#issuecomment-966128973_

**Comment by johnbotris** [comment]
# Testing
* Follow reproduction steps
- [ ] Instead of an error, the mode change works properly, and login is not broken
