### ISSUE TITLE
About dialog shows whitelabel logo instead of Tutanota

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3666]
At the top of the about dialog you see "Powered by" and then the Tutanota logo. If a whitelabel theme is configured with a custom logo, then that logo will be shown rather than the Tutanota one. 

This should always show the Tutanota logo, regardless of whitelabel configuration.

**Comment by ganthern** [comment]
this is showing the tutanota logo in orange for `bedpremium@tutanota.com`

is that intended or should we reopen?
