### ISSUE TITLE
Suspension while download/uploading files is not handled

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3667]
Trying to download or upload a file while suspension is active triggers an error. It should retry the request after the specified time instead.

**Comment by johnbotris** [comment]
fixed by 7d59cd4ee6b80ef703dfbb6817b44f50cbda76a6

**Comment by johnbotris** [comment]
# Testing
* In suspended state, try to download an attachment
    - [ ] The app waits until suspension is complete, tries again, and the download is successful
- [ ] Download works also when not suspended

**Comment by johnbotris** [comment]
The error still occurs
