### ISSUE TITLE
Timepicker is invisible in latest iOS update

### ISSUE THREAD

**Issue by Pa7Hub** [tutao/tutanota#3670]
Navigate to any Timepicker (adding a new Event under Calendar will show one), the time is invisible. 
Only happens on the iPadOS 15, tested on iOS14 on iPhone and it was fine. **Keep in mind that iOS 15 != iPadOS 15**

**Comment by johnbotris** [comment]
I can reproduce this on the version on test flight, but when I build locally it works fine

**Comment by johnbotris** [comment]
It looks like <input type=time> in iOS webview can only handle 24 hour time as an input string. This was broken with the fix for issue https://github.com/tutao/tutanota/issues/3604.

**Comment by johnbotris** [comment]
# Testing notes

- [ ] In desktop/web, the time format in the time picker is based off of the selected format in Appearance settings
- [ ] In mobile, the time format is based on the system time format. 
- [ ] In mobile, the time picker is never blank, regardless of the selected format in Appearance settings
