### ISSUE TITLE
Need 2 actions to get tuta-desk running.

### ISSUE THREAD

**Issue by qmusq** [tutao/tutanota#3675]
OS host : Mxlinux - vbox
OS guest : Arch - endeavouros 
DE : Xfce4 - 4.16.0
WM : xfwm - 4.16.1

_edit::_
Running Tutanota-desktop on arch. 

_Output run tutanota-desktop from terminal. Uses lots of cpu._

> the monkey has been patched
(node:2863) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
version:   3.89.12
config up to date
[ApplicationWindow] startFile:  file:///opt/tutanota-desktop/resources/app.asar/index-desktop.html
[DownloadManager] getting dictionaries from: https://mail.tutanota.com/desktop/dictionaries/
default mailto handler: false
[DownloadManager] spellcheck-dictionary-initialized nl
scheduling to check sse in 1 seconds
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
last missed notification check: { lastMissedNotificationCheckTime: 1637002579280 }
scheduling to check sse in 3 seconds
starting sse connection
lookup sse request
established SSE connection
received new timeout: heartbeatTimeout:240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
sse heartbeat 240
scheduling to check sse in 288 seconds
downloading missed notification
lookup
missed notification response 200
MissedNotification is empty
scheduling to check sse in 288 seconds
dl missed notification response closed

At this state (first launch) it uses a lot of cpu. When i click the tray icon, 
an empty window appears.
When i close this window, after that i can choose a new window from the tray icon. 
The cpu goes down and Tutanota-desktop runs fine.

Is this a known issue.
Using the app with pleasure.

**Comment by johnbotris** [comment]
At first glance i notice `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`, which seems to be an issue with electron: https://github.com/electron/electron/issues/30902. Could be this has something to do with it. I'll see if I can't reproduce it myself

**Comment by johnbotris** [comment]
@qmusq Are you running the app in a virtual machine?

**Comment by qmusq** [comment]
I saw that too, but don't know what to do with it.
I have libva 2.13.0-1 installed. (arch)

This happens for a view weeks now.

**Comment by charlag** [comment]
>libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

is pretty clear that you are missing GPU acceleration so I guess it has to do with your GPU drivers?

**Comment by qmusq** [comment]
> > libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> 
> is pretty clear that you are missing GPU acceleration so I guess it has to do with your GPU drivers?

Thanks. 
I tested Vbox with 3D acceleration on. 
With 3D on, Tutanota-desktop works.
My Vbox/Guest setup is prob. not setup  well. Very slow and tearing windows with 3D on.

[SOLUTION] Turn on 3D acceleration.

**Comment by qmusq** [comment]
[SOLUTION] Turn Vbox 3D acceleration on to get Tutanota-desktop work properly.
