### ISSUE TITLE
Links do not work (iOS)

### ISSUE THREAD

**Issue by Kingwad** [tutao/tutanota#3680]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Clicking on links in email or about dialog does not open the links

**To Reproduce**
1. In settings, open about dialog
2. Click on Website or Releases
3. Nothing happens
4. Open email
5. Click on a link in the email
6. Nothing happens

**Expected behavior**
clicking on a link opens the link in Safari (or whatever browser is default)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.1
 - Version: 3.89.18

**Comment by Kingwad** [comment]
Long pressing a link in an email does bring up a menu that allows you to open the link, but a tap does nothing. Long press does not work for anybody the links in the settings dialogs.

**Comment by johnbotris** [comment]
# Notes for testing
- [ ] Pressing a hyperlink in an email will open the target in safari
- [ ] Pressing a hyperlink in help text will also open the target in safari
- [ ] In-app navigation still works 100%
- [ ] Relative URLs in Tutanota Team mails will navigate to the correct part of the app.
- [ ] Returning to the app after it has been put in the background will open the login screen
