### ISSUE TITLE
Multiselect elements are not aligned correctly

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3681]
When opening the app the the multi select bar in the header is normal. But after some interaction with the app (e.g. reading three or four different emails) the multi select bar layout is not correct anymore. Once the broken multi select bar was visible the header bar is also not aligned correctly anymore.

![IMG_5828](https://user-images.githubusercontent.com/8296817/142409718-fac4a0fb-7f54-4dcb-8e67-3e27e51bf5e9.png)
![IMG_5829](https://user-images.githubusercontent.com/8296817/142409719-eda39e82-3f77-40ac-8658-b948f289505b.png)

Maybe it is related to the but were emails are not scaled correctly because the issue also only appears after opening some emails. See: 
https://github.com/tutao/tutanota/issues/3642

**Comment by johnbotris** [comment]
For some reason, the header's wrapper div is losing the class `flex-grow`.

the DOM when it's not broken:
![Not Broken](https://user-images.githubusercontent.com/22109738/142453457-eb466568-15d9-42d6-a301-ff1ad82ad2bd.png)

the DOM when it's broken:
![Broken](https://user-images.githubusercontent.com/22109738/142453495-353291a0-9c3f-465b-963c-1f6924cfdca3.png)

This gets generated here: 

https://github.com/tutao/tutanota/blob/bb18f5b7e212876746e118ec840a3ad1cb1f183a/src/gui/base/Header.js#L67

`injectedView` is coming from `MailView.headerView`. It must be getting modified somewhere else along the way?

**Comment by charlag** [comment]
This was part of the Safari 15 bug which was fixed since
