### ISSUE TITLE
Calendar invitation message is wrong

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3682]
When sharing a calendar an invitation message is sent out. The text is missleading as calendar name and the username are not mentioned correctly inside the message. It is like this right now:

"\<calendar name\> has invited you to participate in the calendar \<username\>. You can check the details of this invitation in the calendar view to accept or decline it." 

But should be: 
"... \<user name\> has invited you to participate in the calendar \<calendar name\>...."

**Comment by johnbotris** [comment]
# testing notes
- [ ] Send a calendar invitation. In the invitation email, the name of the calendar and the name of the sender are in the correct places in the sentence
