### ISSUE TITLE
Leap Year Birthdays Default to 3/1/???? and not 2/29/????

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#3684]
**Describe the bug**
When creating a birthday for a contact on 2/29/???? the date is stored as 3/1/???? upon saving in the contact editor menu. 

**To Reproduce**
1. Go to 'Contacts"
2. Select a contact and add 2/29/???? as their birthday
3. Click on "Save

**Expected behavior**
The birthday should be stored as the leap day, rather than being moved forward.

**Comment by sarashub** [comment]
The birthday defaults to 3/1 instead of 2/29
