### ISSUE TITLE
Search filter "Period of Time" has incorrect label for second date field

### ISSUE THREAD

**Issue by Kingwad** [tutao/tutanota#3686]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
The search filter for Period of Time contains two date fields both labelled "From"

**To Reproduce**
1. Go to search
2. Open filters
3. Adjust Period of Time
4. Notice both fields are labelled "From"

**Expected behavior**
Expected labels would be "From" and either "To" or "Until".

**Screenshots**
![Screen Shot 2021-11-19 at 1 37 40 PM](https://user-images.githubusercontent.com/439829/142674571-54422022-a10d-449c-a08a-9890d444b324.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.1
 - Browser: Safari 15.1
 - Tutanota Version: 3.89.12

**Comment by johnbotris** [comment]
# testing notes
* go to range selection in search view
* confirm that the two date pickers are labelled correctly ("To" and "From")
