### ISSUE TITLE
White screen on iOS

### ISSUE THREAD

**Issue by Unclezz** [tutao/tutanota#3687]
Hello,

It seems there is trouble with Tutanota App on iPhone.
The app shows a blank screen with only iOS status bar available. To have it back working I needed to force close it with task switcher.

I am running latest iOS version 15.1.1

**Comment by FXlife** [comment]
Same problem here, apparently it only occurs when Tutanota tries to ask for the fingerprint/PIN Code authentication if opened from notifications or a certain time after it has been opened.

**Comment by johnbotris** [comment]
this should be fixed by #3683 which will go out soon
