### ISSUE TITLE
App crash on start up iOS

### ISSUE THREAD

**Issue by Optomod** [tutao/tutanota#3688]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
App won't stay open to view.

**To Reproduce**
Tap Icon

1. Tap icon
2. Splash screen appears then disappears
3. tap home button to see app in background, tap app screen
4. Tries to open then disappears to the back again

**Expected behavior**
App starts but immediately disappears to the background where you can find it but can't bring it forward to check email.
Have tried multiple phone shutdowns and app reinstalls.

**Screenshots**

**Smartphone (please complete the following information):**
iPhone6
iOS 12.5.5 (16H62)

**Additional context**
Was working fine up until last day or so

**Comment by johnbotris** [comment]
Thanks for the report, would you say that this is the same issue as https://github.com/tutao/tutanota/issues/3687? does the app work initially and then stop working after going to the background?

**Comment by caio** [comment]
I don't think it's the same as the white screen issue.

The same happens to me and I'm on a similar boat: older iOS; The crash is immediate: the splash screen appears and the app crashes, nothing is left running.

To me the problem started immediately after updating to v3.89.18, which made me suspect https://github.com/tutao/tutanota/commit/47933cd439f2733be354dfd4df41119c767d453b and point that to `support@`.

**Comment by fk555** [comment]
I am experiencing the same thing iPhone Plus
iOS 12.5.5 app does not load, splash screen appears and then immediately crashes, there is no white screen. The new mesage notification and number are still working/updating on the app icon.

**Comment by Optomod** [comment]
No it shows the splash screen then falls back into the background, the app is unusable.
Hope this helps and is sorted quickly, very frustrating.

Tim

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Optomod** [comment]
Howdy
I also updated to the latest version of the app in hope of a fix, restarted the phone and the result is the same, see attached video.

Tim

**Comment by Optomod** [comment]
https://user-images.githubusercontent.com/94802055/143296058-0438fc24-a7d5-422c-b020-3b96a32d3aaf.MP4

**Comment by rsip22** [comment]
> To me the problem started immediately after updating to v3.89.18, which made me suspect [47933cd](https://github.com/tutao/tutanota/commit/47933cd439f2733be354dfd4df41119c767d453b) and point that to `support@`.

Same here, I'm also on iOS 12.5.5 and this bug started happening with version 3.89.18.

**Comment by johnbotris** [comment]
This should be fixed by 010e84d137dfc6addc0079bd7eeb18f17cf25bc8, a new version will be available next week.

**Comment by Fulp-Piction** [comment]
I had the same issue with my iPhone 6, iOS 12.5.5 - but the app is ok now that I've updated to the 3.89.21 version of the Tutanota app.

**Comment by johnbotris** [comment]
This was fixed with 3.89.21
