### ISSUE TITLE
Relative links in tutanota team mails don't work properly (on iOS)

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3689]
- [ ] Click on a relative link in a tutanota team mail
- [ ] Instead of taking you to that page, the app is reloaded
- [ ] log back in and click on it again
- [ ] it works now

It should just take you to the linked part of the app

**Comment by bedhub** [comment]
Seems to be fixed with 
https://github.com/tutao/tutanota/issues/3680
