### ISSUE TITLE
False error: `Could not reach server, looks like you are offline. Please try again later.`

### ISSUE THREAD

**Issue by 3kh0** [tutao/tutanota#3692]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I am connected to the internet but when I load up tutanota it says that it could not reach the server. What is going on here?

**To Reproduce**
1. Go to 'mail.tutanota.com'
2. Login
3. See error

**Expected behavior**
It should display all of my emails.

**Screenshots**

![image](https://user-images.githubusercontent.com/58097612/143332287-8681f88a-e283-429a-9275-0999107f2d3c.png)

**Desktop (please complete the following information):**
 - OS: `ChromeOS`
 - Browser `Google Chrome`
 - Version ???

**Additional context**
no

**Comment by johnbotris** [comment]
This could occur when we are undergoing DDOS attacks, it's also possible that your IP address was blocked due to our DDOS mitigation measures. If you're still experiencing connection issues, please contact support
