### ISSUE TITLE
Can't zoom out from email body on Android

### ISSUE THREAD

**Issue by picsi** [tutao/tutanota#370]
![screenshot_2018-05-11-19-59-06-818_de tutao tutanota](https://user-images.githubusercontent.com/23157217/39950177-e1a005c0-5555-11e8-9df3-4b4d5e39121e.png)

For instance, in that email I can't pinch to zoom out and read all of it. The text should either be wrapped or zooming out should be possible.

**Comment by armhub** [comment]
Related to #322
