### ISSUE TITLE
Make doesn't detect changes to preload.js

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3701]
it doesn't seem to get invalidated when you make changes

**Comment by charlag** [comment]
@johnbotris should it be? We don't actually "build" it, we just copy it and it shouldn't ever need to change

**Comment by johnbotris** [comment]
If it ever does get changed, it doesn't get detected.

**Comment by charlag** [comment]
We can just copy it on every generation although I think this is not really an issue
