### ISSUE TITLE
Several popup dialogs push buttons/fields into notch and status bar on iPhone

### ISSUE THREAD

**Issue by Kingwad** [tutao/tutanota#3703]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
An event with a long description, such as one accepted from an email invite with a long privacy statement, can display the edit, delete and close buttons under the iOS status bar, with the edit button completely obscured by the camera notch, when clicked.

**To Reproduce**
1. Create an event with a long description (see screenshot for example of length. Exact length required depends on where event is on the screen in step 2)
2. View the day with the event, with the event on the lower half of the screen (if the event is in the upper half of the screen then the event is used as the upper bound so bug does not occur)
3. Tap the event
4. The close and delete buttons are under the phone’s signal/battery display, and the edit button is hidden by the camera notch. None can be activated

**Expected behavior**
UI buttons should not be in areas of the screen where they cannot be seen/used, so the event display should have its upper bound below the status bar.

**Screenshots**
screenshot doesn’t show where the camera notch blocks rendering of the edit button
![screenshot doesn’t show where the notch blocks rendering of the edit button](https://user-images.githubusercontent.com/439829/143614259-8ffbccab-4307-4a4f-8165-0835a77f7185.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.1.1
 - Version 3.89.20

**Comment by Kingwad** [comment]
The same issue occurs when adding a new folder with a large number of folders already existing: the filter field is unusable, which is really only useful when there are a large number of folders ![07086699-BE29-4A2E-BB7C-667B318BB608](https://user-images.githubusercontent.com/439829/147495184-c9591316-9f6b-4ee8-811f-cf17e87f55be.jpeg)

**Comment by ganthern** [comment]
Just to check since I stumbled over this while looking for something else, I think we solved this a while ago?

**Comment by Kingwad** [comment]
I can no longer reproduce the examples used, so I’d say yes, fixed.
