### ISSUE TITLE
Make "action" icons visible when scrolling down on large e-mails

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#371]
I usually receive some pretty long e-mails and I always have to scroll back to the top in order to do anything with them.

I think it would be nice to have the bar or section (this element: `<div class="header">...</div>`) that holds the headers and the "action" icons to become sticky / floating when we scroll down on some e-mails that have a certain length.

**Comment by x80486** [comment]
Not sure what pull request fixed it, but now the `div` class'ed `header plr-l` is fixed/sticky and we can scroll through the e-mail content.

**Comment by charlag** [comment]
Glad to see it solved, we indeed fixed it to the top on desktop and weighting solutions on mobile.
