### ISSUE TITLE
Events shifted of one hour and current time as well

### ISSUE THREAD

**Issue by ThomasTraineau** [tutao/tutanota#3710]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Yesterday I created some events on the calendar of the webapp. Everything went fine. But now when I checked them today on the mobile app (downloaded from f-droid, version 3.89.14), the events are all displayed one hour later (so an event from 8h to 10h is now from 9h to 11h).
Moreover, the current time (horizontal bar) is at the right time on the phone app but is one hour too early on the webapp (it is currently 9h28 and the webapp calendar displays it as 8h28).

**To Reproduce**
1. Create an event on the webapp
2. Check the time delay on the android app

**Expected behavior**
No time delay

**Desktop (please complete the following information):**
 - OS: artix linux
 - Browser librewolf
 - Version 94.0.2

**Smartphone (please complete the following information):**
 - Device: pixel 4a (5G)
 - OS: GrapheneOS
 - Using the mobile app
 - Version 3.89.14

**Comment by johnbotris** [comment]
The privacy settings of your browser are causing it to always report your timezone as UTC+0. If you disable `privacy.resistFingerprinting` in `about:config` then it should be fixed, but I'm not sure that that's what you want...

**Comment by ThomasTraineau** [comment]
When I visit the website "time.is" for example, the clock displays the correct time (the one of my real timezone).
