### ISSUE TITLE
`Ctrl + 0` (reset zoom factor) doesn't work properly

### ISSUE THREAD

**Issue by v011** [tutao/tutanota#3717]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**To Reproduce**
1. Go to "Emails" -> "Inbox" (or any other folder, doesn't matter).
2. Zoom in/out with `Ctrl + mouse wheel`.
3. Then reset the zoom factor via `Ctrl + 0` (keyboard shortcut).
4. The zoom factor is now 100%.
5. Change folder by clicking on another folder.
6. The previous zoom factor is used again (no longer 100%).

Note 1: Changing folder ("Emails" page) with keyboard shortcuts (1, 2, 3, ...) does not produce this unexpected effect.
Note 2: The same effect on "Calendar" page when changing view, e.g. from "Month" to "Week".

**Expected behavior**
The zoom factor should properly reset via `Ctrl + 0` keyboard shortcut.

**Desktop (please complete the following information):**
 - OS : Ubuntu 20.04
 - Desktop Environment : GNOME
 - Tutanota version : v3.89.12

**Comment by ganthern** [comment]
this seeems to be happening since 9498ab8ef6e14f8d24b6be1232736ed2a9b9c5fd because `Ctrl+0` doesn't emit a `zoom-changed` event, so the locally stored zoom factor in the main thread doesn't get updated. When the next URL change occurs, we reset zoom to the saved value.

**Comment by ganthern** [comment]
this needs to be tested on windows, mac and linux

## Testing:
* [ ] follow reproduction steps in the issue description and check that the problem doesn't occur anymore
* [ ] `Ctrl/Cmd+0` resets the zoom factor on all currently opened windows to 1

## Regressions:
* [ ] zoom factor is retained when the app restarts
* [ ] new windows get created with the saved zoom factor
* [ ] `Ctrl/Cmd+Wheel` changes the zoom factor across all opened windows

**Comment by sarashub** [comment]
zoom factor is not retained when the app is restarted.

**Comment by johnbotris** [comment]
Cmd+Scroll doesn't zoom in on Mac. This seems to be the case in the current production client aswell
