### ISSUE TITLE
Adding attachment not working anymore on my android device

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3718]
User report, but we cannot reproduce it. We need to collect more information. We also have the log file but there is no information regarding adding attachments. Maybe we need to at least add log statements when adding attachments.

> Actually there is no error message.
> It simply do nothing when I try to attach.
> 
> 1/  click on the attach icon in tutanota app
> 2/ Then it opens the file browsing app to select a file
> 3/ select a file
> 4/ Then it comes back to my draft in the Tutanota app
> But No file is attached
> 
> Other way around: 
> 1/ open file manager
> 2/ select a file
> 3/ choose "share"
> 4/ select Tutanota
> 5/ then it opens tutanota app with an empty draft
> But no file is attached
> 

Client: android
Type: PREMIUM
Tutanota version: 3.89.20
Timestamp (UTC): Tue, 23 Nov 2021 18:08:22 GMT
User agent:
Mozilla/5.0 (Linux; Android 11; Mi 9T Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36

**Comment by davenewham** [comment]
Interestingly, I have experienced the same bug. We both have Android 11 build RKQ1.200826.002

**Comment by charlag** [comment]
@davenewham is it Xiaomi then?

**Comment by davenewham** [comment]
> @davenewham is it Xiaomi then?

Yes - Xiaomi Poco X3 NFC

**Comment by davenewham** [comment]
I was able to fix this issue by enabling the  "Turn on MIUI optimization" option in the developer options.

**Comment by charlag** [comment]
I haven't heard anything else about this for a long time
