### ISSUE TITLE
Migrate to SplashScreen API (Android 12)

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3719]
See https://developer.android.com/guide/topics/ui/splash-screen/migrate

### Test Notes
test cold and warm starts with dark theme, light theme, whitelabel on 
* [ ] Android 7
* [ ] Android 10
* [ ] Android 12 or 13

**Comment by v011** [comment]
I'm afraid that this change could force users to upgrade their Android version (or to change their phone), like it was the case earlier this year (#3188). Could you confirm that it will not happen, please ?

**Comment by charlag** [comment]
@v011 it absolutely will not force us to drop any support. There's also a support library mentioned on the linked page

**Comment by v011** [comment]
Yes, I read that the guide recommends using the [compat library](https://developer.android.com/guide/topics/ui/splash-screen/migrate#splashscreen_compat_library). Thank you for clarifying that point !
