### ISSUE TITLE
Add DKIM and DMARC support for custom domains

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#372]

**Comment by eminx** [comment]
Gmail often puts my emails sent to gmail users into spam. I suspect the sole reason is that these are not yet in place. 

For a premium account, I think it is almost not acceptable to not have these in place. 

When are these supposedly going to be implemented?

**Comment by cujanovic** [comment]
Any ETA on this? Thanks.

**Comment by mpfau** [comment]
We can't promise on a fixed date but it is already on our roadmap (https://tutanota.com/roadmap/)

**Comment by jacobludriks** [comment]
i was considering going with tutanota for my personal email, but since it looks like security isnt a priority i have changed my mind.

**Comment by carloshmm** [comment]
> i was considering going with tutanota for my personal email, but since it looks like security isnt a priority i have changed my mind.

The problem is only with custom domains, the official domains (tutanota.com, tuta.io, tutanota.de, keemail.me) all have dkim/dmarc enabled. I was one of the first to complain about this on the past, they at least added this on the roadmap.

**Comment by mateusz-holysz** [comment]
This improvement is very much needed. I hope that the changes will be made quickly. It is badly needed for premium users.

**Comment by tiritto** [comment]
I just bought the service and I already starting to regret it. Please, DKIM and DMARC support is extremely important for pretty much everyone who want to send emails from under his own domain.  Hopefully, it'll be released soon.

**Comment by charlag** [comment]
Dear concerned people,
we very much want to support it but we have a lot on our plate right now.
If you want to support a thing, there's a :+1:

**Comment by samip5** [comment]
I'm starting to regret my premium too as these are really important aspects which are missing.

**Comment by insipidlight** [comment]
> I'm starting to regret my premium too as these are really important aspects which are missing.

I don't regret buying premium, it was only €12 and I will still be using it. But I'm going to have to use something else for my custom domain for now.

**Comment by charlag** [comment]
We know that it's highly requested and we'll try to add it soon

**Comment by millettjon** [comment]
I purchased premium but have never used the service since dkim is not supported for my custom domain :/ .

**Comment by jacobludriks** [comment]
I'm not even considering purchasing as they don't even consider this to be a priority. It's 2019...

**Comment by Sigawan** [comment]
Any progress at all???
I'm about to close all my Premium accounts due to lack of support for DKIM for custom domains. It's been literally years and years people have been asking for this BASIC SECURITY MEASURE. I feel a fool for assuming this would be part of a Premium account, my bad...

**Comment by charlag** [comment]
We actually made some progress, there's a working prototype of signing. It's on the top of our roadmap and should be done in the next 2-3 weeks.
Although I disagree that it's "basic" and your comment about "included in premium" is rather irrelevant: it's not hidden behind some additional payment, it's just not implemented yet.
Thanks for your patience.

**Comment by samip5** [comment]
> **_Any progress at all???_**
> It's been literally four years people have been asking for this **_BASIC SECURITY MEASURE_**.
> I'm about to close all my Premium accounts due to lack of support for DKIM for custom domains.
> I feel a fool for assuming this would be part of a Premium account, my bad...

This is the reason why I cancelled my Premium, and went to Protonmail with my emails.

**Comment by avrelaun** [comment]
I just bought a Premium account for custom domains, thinking this would be supported, but nope.
This should be a high priority.

**Comment by mcuix** [comment]
12 days ago it was estimated that that Dmarc and DKIM would be available in 3 weeks. Is this estimate still on schedule? If so, it's ready in a week's time. Or is that too optimistic.?

**Comment by charlag** [comment]
@mcuix the person who is the most proficient in DMARC & DKIM was very busy with important infrastructure upgrades, mitigating DDOS and such. We would say it's this-next week but no promises yet, sorry.

**Comment by QEDeD** [comment]
@charlag I hope progress is going well, although things always take more time than expected :) Tutanota is great!

**Comment by charlag** [comment]
@QEDeD I was told that there's a good progress on it but I don't want to promise the same thing again. Thanks for the patience!

**Comment by mcuix** [comment]
Without DKIM and DMARC protections the Premium accounts are a security risk especially when using custom domains. For that very reason, I am investing in the ProtonMail premium.

**Comment by iJorgen** [comment]
Is this postponed to the next release?! Any new ETA? Seemed really close a few weeks ago but a bug stopped the release...

**Comment by sofiageo** [comment]
Hello, thanks for this. When is the deployment ETA? I just tested it and there is still no DKIM for my domain.

**Comment by QEDeD** [comment]
@sofiageo the lastest release is 3.55.7 (see https://github.com/tutao/tutanota/releases) and it seems 3.56.0 will be the next release (see https://github.com/tutao/tutanota/milestones) and this issue (adding DKIK + DMARC issue #372) is referenced as being part of that release (3.56.0) as you can see here: https://github.com/tutao/tutanota/milestone/83?closed=1   

So in conclusion: DKIM and DMARC support will be included in 3.56.0 which should be the next release. Seeing that 8/9 of the things that 3.56.0 include are done/closed (again, see: https://github.com/tutao/tutanota/milestone/83?closed=1) it should be released very soon :)

**Comment by sofiageo** [comment]
Hi @QEDeD, my confusion happened because I build tutanota from source, so I was hoping I could see the update. I had missed the part that we are supposed to only build the release tags. 
Upgrading the client like this needs another step which I forgot when I made the comment. (oops)

I'm not really in a hurry, I'm just trying to familiarize with the process and provide any feedback :)

**Comment by QEDeD** [comment]
Ah I see, you are ahead for me then! :grin:
