### ISSUE TITLE
Opening/closing minimized mail editor while file is uploading creates multiple drafts

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3726]
**To Reproduce**
1. Create mail draft with a file (make sure it uploads for some time so either make it big or make connection slow)
2. Click on close
3. Open minimized mail editor
4. Repeat multiple times
5. See that the file is uploaded multiple times in parallel and that the draft is created multiple times

**Expected behavior**
File is uploaded only once and draft is created only once.

**Desktop:**
 - Version 3.89.23

**Comment by charlag** [comment]
After looking at the code for a bit I think that the problem is that the state of the editor is not really stored in the ViewModel. We should probably keep saving/sending state there and if the editor is opened up again indicate that the uploading is still ongoing

**Comment by johnbotris** [comment]
### Testing
* Create mail draft with a file (make sure it uploads for some time so either make it big or make connection slow)
* Click on close
* Open minimized mail editor
* Repeat multiple times
- [ ] The create draft call is not made multiple times (check the network logs) (an update draft calll might occur)

- [ ] Do the previous with an existing mail. See that the draft is actually updated and keeps any changes

* Create mail draft with a file (make sure it uploads for some time so either make it big or make connection slow)
* Click on close
* Saving the draft fails (turn of network connection in the network toolbar)
* open the minimized editor and send again
- [ ] The send operation is successful (you will have to have re-enabled the connection)

### Regression Testing
- [ ] Creating new drafts in general works
- [ ] Saving existing drafts in general works
- [ ] Conffirmation prompts behave correctly when sending a mail
- [ ] Try sending a mail with no subject, it prompts for confirmation. 
- [ ] Try sending a secure external mail with a weak password, it prompts for confirmation
- [ ] Try sending an secure external mail with no password. It is denied.
- [ ] Try sending an email with many (> 10) to recipients. It prompts for confirmation.
