### ISSUE TITLE
iOS app cannot create new account

### ISSUE THREAD

**Issue by Kingwad** [tutao/tutanota#3736]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When trying to create a new account via the iOS app, you get an error instead of a new account.

**To Reproduce**
1. If signed in, sign out and select “Different account”
2. Click on “Sign up”
3. Enter a new email address, your new password twice, and check both boxes.
4. Click next.
4. See error.

**Expected behavior**
successfully create a new account.

**Smartphone (please complete the following information):**
 - Device: iPhone12 Pro
 - OS: iOS 15.2
 - Version v3.89.21

**Additional context**
Error report included below:

Feedback v3.89.21 - tutanota - UNKNOWN - ios

 Client: ios
 Type: UNKNOWN
 Tutanota version: 3.89.21
 Timestamp (UTC): Tue, 14 Dec 2021 12:33:18 GMT
 User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
tutanota
 Error message: Unknown comand: generateRsaKey
Stacktrace: 
y@file:///private/var/containers/Bundle/Application/A36882D5-4822-4416-9150-15C036EBF294/tutanota.app/build/dist/common-min-354c0fec.js:1:10986
_handleMessage@file:///private/var/containers/Bundle/Application/A36882D5-4822-4416-9150-15C036EBF294/tutanota.app/build/dist/common-c72a04c3.js:1:6966
handleMessageFromNative@file:///private/var/containers/Bundle/Application/A36882D5-4822-4416-9150-15C036EBF294/tutanota.app/build/dist/native-common-877619a7.js:1:1508

**Comment by johnbotris** [comment]
Thanks for the report, a fix for this will be released soon
