### ISSUE TITLE
[iOS] fix safe-area-inset usages

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3738]
There are some layout issues on iOS full screeen devices that don't have a home button anymore like iPhone X. 
The notch on ie the iPhone X is also an issue, as seen in https://github.com/tutao/tutanota/issues/3703

- [x] Minimized mail editor
- [x] Snack bar
- [x] Vertical layout more menu, new email button, end of mail list
- [x] Review calendar, contact, search and settings view in portrait and landscape mode.

## Test Notes
Test layout on ios with a notch (iPhone X simulator or similar) and check that all control elements are usable.
Use Landscape and Portrait mode to get notches at the left/right

* [ ] big dialogs (Mail editor, Contact, Help, Calendar)
* [ ] all list views (Mail, Contacts, Trash, ...)
* [ ] Settings Viewers
* [ ] Multiselect Header actions
* [ ] Snackbar (Connection error, spam reporting)
* [ ] Minimized mail editor

**Comment by nif-tutao** [comment]
All tests can be passed in a vertical orientation of an IOS device with a notch. However, if the tutanota app is used in a horizontal orientation with notch on the left side the following sections are not usable as the notch covers the apps' texts/dialogs:

- User management in admin settings (if a specific user is selected, notch covers the shown text)
- If a specific user is selected in contacts, the same thing happens as written above
- Minimized mail editor, if notch is on the right side (notch covers a part of the minimized mail editor popup)
