### ISSUE TITLE
Cmd+Scroll doesn't zoom in on mac desktop client

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3739]
*reproduction steps:*
* in desktop client, do cmd+scoll
-> nothing happens (or at least, the page scrolls normally and doesn't zoom)

*what should happen:*
the app's zoom factor should increase/decrease

## Test Notes
* [x] clicking "zoom in" on top in the menu zooms in, if still possible
* [x] clicking "zoom out" on top in the menu zooms out, if still possible
* [x] clicking "Actual size" on top in the menu resets the zoom
* [x] the shortcuts that are mentioned in the menu also show the right behavior

**Comment by kibhub** [comment]
issue persists

**Comment by ganthern** [comment]
we decided to go the way other apps do it on macOS, did we not? 

From the original PR:
> Barely any application supports zooming under macOS with cmd+scroll. The intended way to zoom specified by the operating system is by using the menu. This commit adds the options zoomIn, zoomOut and resetZoom to the menu.
