### ISSUE TITLE
Use web message ports for android native communication

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3741]
For offline mode (https://github.com/tutao/tutanota/issues/590) we want to store data on the native side. We would need to update how we do our native message passing for the apps, because it currently uses javascript evaluation to send data from native to the webview. We can fix this for android by using `WebMessagePort`s. Unfortunately they still only support passing of string data, but we at least will no longer have to `eval`.

https://developer.mozilla.org/en-US/docs/Web/API/MessagePort
https://developer.android.com/reference/android/webkit/WebMessagePort

**Comment by charlag** [comment]
@johnbotris test notes pls

**Comment by johnbotris** [comment]
# Testing

We need to regression test android:
- [ ] Requests sent from web are received by native and handled, and responses and error responses are sent successfully
- [ ] Requests sent from native are received by web and handled, and responses and error responses are sent successfully

Suggestions for what to test: 
- [ ] Uploading and downloading attachments
- [ ] Mailto handling
- [ ] Sharing to android
- [ ] Contacts from system
- [ ] Email notifications
- [ ] Alarm notifications

- [ ] Smoke test on iOS, make sure it's still running (shouldn't really have been affected)
