### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3746]
We want to migrate our typesystem from flow to TypeScript.
- [x] oxmsg
- [ ] admin client
- [x] web client
- [x] client code generators
- [ ] use .ts file extension instead of .js, make sure that git history is preserved

**Comment by charlag** [comment]
some converters:
https://github.com/khan/flow-to-ts
https://github.com/bcherny/flow-to-typescript

**Comment by charlag** [comment]
another point is enums:
https://www.typescriptlang.org/docs/handbook/enums.html

I would recommend to use `as const` objects at first or maybe `const enum` where necessary because they have the lowest overhead.

**Comment by vitoreiji** [comment]
Some preliminary client testing revealed the following issues:

- "..." drop down menus are empty in:
    - mail viewer
    - contact editor
    - Settings > Email
    - calendar event editor
    - autoresponder editor
    - Settings > Appearence (except for language)
    - Add group
    - selecting tutanota domain
    - shared mailbox config
    - creating custom colors: base theme
    - setting alignment (mail editor)
    - folder settings
- no button to:
    - add 2FA
    - close active sessions
    - add alias
    - add inbox rule
    - add spam rule
    - add custom domain
    - add custom notification emails
    - add gift card
    - download invoice
- 404 when:
    - changing language
    - viewing recovery code
    - adding language to template
- receiving mail with attachment throws:
```
    error Error: AssertNotNull failed : null
    at assertNotNull (app.js:2108:15)
    at eval (MailViewer.ts:1860:52)
    at Array.filter (<anonymous>)
    at MailViewer._createAttachmentsButtons (MailViewer.ts:1860:17)
    at eval (MailViewer.ts:1127:42) Error: AssertNotNull failed : null
    at assertNotNull (http://localhost:9000/client/build/app.js:2108:15)
    at eval (nollup-int:///src/mail/view/MailViewer.ts:1378:58)
    at Array.filter (<anonymous>)
    at MailViewer._createAttachmentsButtons (nollup-int:///src/mail/view/MailViewer.ts:1378:23)
    at eval (nollup-int:///src/mail/view/MailViewer.ts:795:52)
```

**Comment by vitoreiji** [comment]
@nowhub and I are testing Contacts.

**Comment by vitoreiji** [comment]
@nowhub and I are testing Appearance settings.

**Comment by vitoreiji** [comment]
@nowhub and I are testing Whitelabel settings.

**Comment by vaf-hub** [comment]
Found the following minor problem:

1. Signup as a Free account.
2. Go to subscription settings.
3. See that it reads "FREE". It should be "Free" without caps.

The same will happen always if the accountType is something other than Premium. It happens because of a change in `TutanotaConstants.ts`:
```export const AccountTypeNames = ["System", "Free", "Outlook", "Premium", "Stream", "External"]```
was replaced with
```export const AccountTypeNames = reverse(AccountType)```

We should either keept the reversed map explicitly or convert the enum to natural capitalization for the definition of `AccountTypeNames`.

**Comment by vaf-hub** [comment]
I will test subscription settings.

**Comment by vitoreiji** [comment]
@nowhub and I are testing Contact form settings.

**Comment by vitoreiji** [comment]
@nowhub and I are testing Global settings.

**Comment by vaf-hub** [comment]
I am testing PaymentSettings

**Comment by vaf-hub** [comment]
I am testing GroupSettings

**Comment by vaf-hub** [comment]
I am testing UserSettings.

**Comment by vaf-hub** [comment]
I will continue with MailSettings now.

**Comment by mpfau** [comment]
I will focus on search now

**Comment by mpfau** [comment]
will start testing mail editing, now

**Comment by vitoreiji** [comment]
@vaf-hub can you test the rejected senders list? I cannot seem to make anything appear there, don't know what the correct conditions would be.

**Comment by vitoreiji** [comment]
I'll test mail folders and drag & drop now.
