### ISSUE TITLE
Contact form can not be deleted after deactivating whitelabel

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#3747]
How to reproduce:
1. Order whitelabel and configure a whitelabel domain
2. Create a contact form
3. Remove the whitelabel domain and deactivate the whitelabel feature
4. Try to delete the contact form
-> When clicking on the contact form the error message "Please first configure your whitelabel domain." is shown.

If you are stuck in this situation it is also not possible to switch to the Free subscription because the contact form is still existing.

**Comment by bedhub** [comment]
Discussed with @armhub  that we should allow deleting contact form when the whitelabel is not assigned but we should also check that you cannot remove the whitelabel domain with an existing contact form.

**Comment by ganthern** [comment]
### Test Notes

#### Deactivating Whitelabel with contact form
* [ ] deactivating the whitelabel domain shows a message box telling them to delete the forms before proceeding
* [ ] the whitelabel domain stays active and the contact form still works
* [ ] removing the contact form lets them proceed to delete the domain without further messages

### Regressions
* [ ] trying to remove whitelabel with an active domain still works as expected
* [ ]
