### ISSUE TITLE
2nd time orders made with other email get responses in tutanota web account

### ISSUE THREAD

**Issue by linuxgirl22** [tutao/tutanota#3758]
Unsure if this is a bug, but am not on reddit etc, as generally stay offline/avoid sign-ups, for privacy, so I hope it is okay to post/ask (github last resort/very rare). Realise that tutanota may be simply the email receiver in this, but I only have these issues with tutanota.  

I'd started re-using tutanota email as a second address over the last few months, but am not signed up at order-sites via tutanota regarding order-connected emails that are arriving in the account. One, ebay, I've never used the tutanota email at, but the other, xp-pen, used to use the tutanota email address at least over a year ago. Three times over the last 2 weeks, I receive order updates from xp-pen via 2 emails, despite being signed up there with the non-tutanota email. There have been other issues with switching something from a tutanota account across to other email, where the switch never is actioned, e.g. no meter reading reminders, despite confirmation that the switch has been done. 

Behind all this is the increasing lack of privacy by Google/big tech/larger companies, regarding manifest 3/cohorts/harvesting a lot more data etc. I have also noticed for a few months that where a VPN used to be respected for privacy, that seems to be being bypassed sometimes now. 

I'm running Sparkylinux Mate (debian) and hardened Librewolf v95.0.2-1 on main tower PC [no smartphone]. Concerned that the only email I have any such issues, of emails received that are not registered via tutanota, and switches not happening, is with tutanota email. Is this a vulnerability with my system or tutanota? If this isn't a bug, I'd be grateful to be pointed in the right direction. Thanks.

**Comment by charlag** [comment]
@linuxgirl22 this would be a question to support so that they can check details for you but it sounds like you set up some kind of redirection from your old email address (forgive my assumption when this is not the case).
As I said, we can't discuss your details publicly so please contact support.

**Comment by linuxgirl22** [comment]
Thanks @charlag, and, yes, I hadn't set up a redirect. It's concerning me further that I'd deleted this post but here it publicly is, eek, so I'll just leave things for now. All the best.

**Comment by charlag** [comment]
@linuxgirl22 we will delete an issue
