### ISSUE TITLE
Windows client glitches, freezes, and disables Windows actions

### ISSUE THREAD

**Issue by Cascadence** [tutao/tutanota#3760]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Describe the bug**
The latest Windows client installed on Win10 Pro 10.0.17763 exhibits GUI components flashing rapidly, disappearing, and disabling right-click functionality not only within the client window, but in Windows Explorer itself (i.e. can't right-click on taskbar or desktop).

**To Reproduce**
1. Launch client
2. See error

**Desktop**
 - Win10 Pro
 -10.0.17763

**Comment by charlag** [comment]
HI
It doesn't sound like it's something desktop client would be able to cause, sounds like inner Windows problem

**Comment by Cascadence** [comment]
> HI It doesn't sound like it's something desktop client would be able to cause, sounds like inner Windows problem

Hello , thanks for your reply.

It doesn't seem like the client should be able to affect Windows in this way, but it is the only application that exhibits this behavior, and it started occurring immediately after the most recent client update. It makes sense to me that the GUI flickering as it is may confuse the OS as to whether or not the client is currently the active window, thereby causing right-click functionality on the taskbar or desktop to malfunction.

To add: there is an Nvidia graphics card on this machine, which works fine in all instances.

**Comment by charlag** [comment]
@Cascadence unfortunately we are unable to reproduce it so far, I suspect that it's a specific problem with your graphic card. If it keeps happening, please let support know, they might analyze your logs
