### ISSUE TITLE
Tutanota app does not answer anymore after a file dowloading

### ISSUE THREAD

**Issue by CocoR55** [tutao/tutanota#3761]
**Bug with the last version 3.89.25 of tutanota (tutanota-desktop-linux.AppImage), however it is possible to
to read messages
to send messages with attached files
to receive messages with attached files
to download an attachment but once the file is downloaded, the tutanota application does not answer anymore... "please wait".
/run/firefail/appimage/tutanota-desktop --field-trial-handle=2.....2 --disable-features=SpareRebderFor.......
.. You have to kill it.

Notes:
If I go directly to the tutanota site without using the application, there is no bug.
No bug with the previous tutanota application versions.

**

**To Reproduce**
1. Menu/internet/Tutanota/Identification/password
2. Open a message with an attachment.
3. Download file.
4. See bug: "the tutanota application does not answer anymore"

**Expected behavior**
After file downloaded, tutanota can answer and continue to work.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Firefox: 95.0.1
 - Firejail version 0.9.66

**Comment by charlag** [comment]
@CocoR55 hey, thanks for the report, could you please check the logs (settings->about->send logs), especially desktop log to see if there are any errors?

**Comment by CocoR55** [comment]
In the 1641917174227_main_tutanota.log file, they are many errors:
 Error message: DbFacade.open.onerror: uT+..........................................F/k=
request.error: {"code":0,"name":"UnknownError","message":"Internal error opening backing store for indexedDB.open.","INDEX_SIZE_ERR":1,"DOMSTRING_SIZE_ERR":2,"HIERARCHY_REQUEST_ERR":3,"WRONG_DOCUMENT_ERR":4,"INVALID_CHARACTER_ERR":5,"NO_DATA_ALLOWED_ERR":6,"NO_MODIFICATION_ALLOWED_ERR":7,"NOT_FOUND_ERR":8,"NOT_SUPPORTED_ERR":9,"INUSE_ATTRIBUTE_ERR":10,"INVALID_STATE_ERR":11,"SYNTAX_ERR":12,"INVALID_MODIFICATION_ERR":13,"NAMESPACE_ERR":14,"INVALID_ACCESS_ERR":15,"VALIDATION_ERR":16,"TYPE_MISMATCH_ERR":17,"SECURITY_ERR":18,"NETWORK_ERR":19,"ABORT_ERR":20,"URL_MISMATCH_ERR":21,"QUOTA_EXCEEDED_ERR":22,"TIMEOUT_ERR":23,"INVALID_NODE_TYPE_ERR":24,"DATA_CLONE_ERR":25}
event: {"isTrusted":true,"type":"error","target":{},"currentTarget":{},"eventPhase":2,"bubbles":true,"cancelable":true,"defaultPrevented":false,"composed":false,"timeStamp":0,"srcElement":{},"returnValue":true,"cancelBubble":false,"path":[],"NONE":0,"CAPTURING_PHASE":1,"AT_TARGET":2,"BUBBLING_PHASE":3}
event.target.error: UnknownError: Internal error opening backing store for indexedDB.open.: UnknownError, Internal error opening backing store for indexedDB.open.> Internal error opening backing store for indexedDB.open.

Does it speak to you?
Regards,
CocoR55

**Comment by charlag** [comment]
@CocoR55 doesn't seem to be the cause but might be related, my guess could be that we don't have permission to write files for some reason?

**Comment by CocoR55** [comment]
The file tutanota-desktop-linux.AppImage was downloaded again. The signature was checked. Then it was executed with chmod +x permissions. The problem is still there.
I would like to reproduce the defect with an earlier version of tutanota-desktop-linux.AppImage but I don't know where to find the earlier versions. For example, v3.88.4.
Do you have any idea?
Regards,
CocoR55

**Comment by CocoR55** [comment]
Stacktrace: 
IndexingNotSupportedError: DbFacade.open.onerror: uT+n3+6eAMUT+MEyIE1wd5uHjKERI06kpOz4nLESF/k=
request.error: {"code":0,"name":"UnknownError","message":"Internal error opening backing store for indexedDB.open.","INDEX_SIZE_ERR":1,"DOMSTRING_SIZE_ERR":2,"HIERARCHY_REQUEST_ERR":3,"WRONG_DOCUMENT_ERR":4,"INVALID_CHARACTER_ERR":5,"NO_DATA_ALLOWED_ERR":6,"NO_MODIFICATION_ALLOWED_ERR":7,"NOT_FOUND_ERR":8,"NOT_SUPPORTED_ERR":9,"INUSE_ATTRIBUTE_ERR":10,"INVALID_STATE_ERR":11,"SYNTAX_ERR":12,"INVALID_MODIFICATION_ERR":13,"NAMESPACE_ERR":14,"INVALID_ACCESS_ERR":15,"VALIDATION_ERR":16,"TYPE_MISMATCH_ERR":17,"SECURITY_ERR":18,"NETWORK_ERR":19,"ABORT_ERR":20,"URL_MISMATCH_ERR":21,"QUOTA_EXCEEDED_ERR":22,"TIMEOUT_ERR":23,"INVALID_NODE_TYPE_ERR":24,"DATA_CLONE_ERR":25}
event: {"isTrusted":true,"type":"error","target":{},"currentTarget":{},"eventPhase":2,"bubbles":true,"cancelable":true,"defaultPrevented":false,"composed":false,"timeStamp":0,"srcElement":{},"returnValue":true,"cancelBubble":false,"path":[],"NONE":0,"CAPTURING_PHASE":1,"AT_TARGET":2,"BUBBLING_PHASE":3}
event.target.error: UnknownError: Internal error opening backing store for indexedDB.open.: UnknownError, Internal error opening backing store for indexedDB.open.> Internal error opening backing store for indexedDB.open.
    at IDBOpenDBRequest.i.onerror (file:///run/firejail/appimage/resources/app.asar/worker.js:12:39511)

**Comment by charlag** [comment]
I don't think that the problem is that file itself doesn't have permissions to run, I think it cannot write to ~/.config

**Comment by CocoR55** [comment]
I did a chmod 777 to /.config/firejail/tutanota-desktop.profile but this is the same

**Comment by CocoR55** [comment]
With previous versions to V3.89.25, there was no problem with write permissions. I don't understand why this version is causing problems.

**Comment by CocoR55** [comment]
Ooops! I found a previous version of tutanota-desktop-linux. This is version 3.89.20. I tested with it and problem is the same. Probably, downloading is not something I do often.
     When I download from the site, a dialog box opens titled "Opening (the file name)."
In this dialog window, the mentioned question is: What should Firefox do with file?
you click OK and then the window disappears and it's OK.
Whereas with the application, this window does not open. So, what triggers the opening of this window? I don't know if there is a log that could tell us?

**Comment by charlag** [comment]
You can get some output from stdout and the rest from "send logs" button in About dialog. I imagine there's something wrong with your setup.

**Comment by CocoR55** [comment]
Thank you **charlag**
"A mutation operation was attempted on a database that did not allow mutations."
I suppose "mutation" = downloading  and  "database that did not allow mutations" = sandbox.

**Comment by CocoR55** [comment]
Tutanota installed on another PC with Linux Mint Xfce without Firejail. That works. Then, tutanota + firejail but with noprofile, no issue. On the previous PC with Linux Mint Cinnamon, this is the same. tutanota+firejail+noprofile = no issue. However, tutanota+firejail+profile=/home/leloup/.config/firejail/tutanota-desktop.profile, the downloading issue is reproduced.
tutanota-desktop.profile is the same like [https://github.com/netblue30/firejail/pull/3870/commits/70ef3de4b62ddb9577083d9656732a679a43a7c8](url)
Something in the tutanota-desktop.profile is wrong but what?
I tried to add noblacklist ${HOME}/.config/tutanota-desktop.profile and whitelist ${HOME}/.config/tutanota-desktop.profile but I get the same issue.

**Comment by CocoR55** [comment]
Before leaving, a question I ask myself:
What are these two directories for?
mkdir ${HOME}/.config/tuta_integration
mkdir ${HOME}/.config/tutanota-desktop
Maybe I'm making an installation mistake.
Regards.
CocoR55

**Comment by charlag** [comment]
@CocoR55 first of all, the problem is not with Tutanota and you should open this issue with firejail.
`tuta_integration` is a marker for whether we enable desktop integration on Linux.
`$XDG_CONFIG_HOME/tutanot-desktop` or `$HOME/.config/tutanota-desktop` is where we keep all the persistent data
