### ISSUE TITLE
Missleading message in shared calendar

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3762]
There is currently a missleading message when editing a calendar event in a shared calender. The message is "This event was sent from another calendar. Changes to the event will only be visible in your calendar". Which is not true in case of a shared calendar.

Steps to reproduce:

1. Invite another premium user to shared calendar with write permission.
2. Create event as participant in shared calendar
3. Edit event as owner 

The message does not show up  if:
* owner creates an event and participant edits the event
* participant creates the event and another particpant edits the event.
* the creator (participant/owner) of the event opens the event

**Test notes**

- [ ]  Invite another premium user to shared calendar with write permission, create event as participant in shared calendar, edit event as owner and observe that the message is not shown.
- [ ] Regression test permissions for calendar events (own, shared and invites).

**Comment by charlag** [comment]
I could reproduce it, it seems like we don't detect even type correctly, not sure why yet

**Comment by charlag** [comment]
It seems like we struggle to differentiate between invite that we received and someone creating an even in our calendar but I think we do not allow accepting invites into the shared calendars?
