### ISSUE TITLE
Login in error message: Keychain operation failed biometrics

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3763]
**Description**
The user cannot log into the iOS device using stored credentials. Every time the error message below appears. Seems like something is corrupted when retreiving the key from ECIES (Secure Enclave).  

**Steps to reproduce**
We cannot reproduce this so far but we received a second report about this problem today. I opened this issue to collect more information. 

**Hints**
The report is from an iOS 15.0 device and latest iOS version is now 15.2. It might just be a bug within the iOS version.

**Workaround:**
Reinstall the app. User will loose stored credentials

Client: ios
Type: UNKNOWN
Tutanota version: 3.89.26
Timestamp (UTC): Fri, 07 Jan 2022 00:38:10 GMT
User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_0_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
de.tutao.tutanota
Error message: Keychain operation failed biometrics
Stacktrace:
Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data (err -69)" UserInfo={numberOfErrorsDeep=0, NSDescription=ECIES: Failed to aes-gcm decrypt data (err -69)}

## Test notes
- [ ] Authenticate with all 3 methods on iOS
- [ ] Change between auth methods
- [ ] Fresh install, select a method
- [ ] Delete credentials
- [ ] Cancel authentication

**Comment by brshub** [comment]
We have received another related case on iOS 15.2 with Tutanota version 3.89.26:

Error message: Keychain operation failed deviceLock
Stacktrace:
Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data (err -69)" UserInfo={numberOfErrorsDeep=0, NSDescription=ECIES: Failed to aes-gcm decrypt data (err -69)}

**Comment by PreludeAndFugue** [comment]
I'm seeing the same problem on an iPad 14.8.1

Tutanota version: 3.91.9

```Feedback v3.91.9 - de.tutao.tutanota - UNKNOWN - ios



 Client: ios
 Type: UNKNOWN
 Tutanota version: 3.91.9
 Timestamp (UTC): Tue, 08 Feb 2022 18:58:32 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)
de.tutao.tutanota
 Error message: Keychain operation failed deviceLock
Stacktrace: 
Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data" UserInfo={numberOfErrorsDeep=0, NSDescription=ECIES: Failed to aes-gcm decrypt data}```

**Comment by jimzhong** [comment]
Same error on iPad 15.3

```
Feedback v3.91.9 - de.tutao.tutanota - UNKNOWN - ios



 Client: ios
 Type: UNKNOWN
 Tutanota version: 3.91.9
 Timestamp (UTC): Sun, 13 Feb 2022 06:49:33 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)
de.tutao.tutanota
 Error message: Keychain operation failed deviceLock
Stacktrace: 
Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data (err -69)" UserInfo={numberOfErrorsDeep=0, NSDescription=ECIES: Failed to aes-gcm decrypt data (err -69)}
```

**Comment by johnbotris** [comment]
We have reports of this happening on iOS12 as well

```
Client: ios 
Type: UNKNOWN
Tutanota version: 3.94.2 
Timestamp (UTC): Mon, 04 Apr 2022 22:10:06 GMT 
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 12_5_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 de.tutao.tutanota 
Error message: Keychain operation failed deviceLock Stacktrace: Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data" UserInfo={NSDescription=ECIES: Failed to aes-gcm decrypt data}
```

**Comment by bedhub** [comment]
I had this error today after using an iPad that was not used for a few weeks. So battery was empty.

Feedback v3.95.4 - de.tutao.tutanota - UNKNOWN - ios



 Client: ios 15.2.1
 Type: UNKNOWN
 Tutanota version: 3.95.4
 Timestamp (UTC): Sat, 21 May 2022 06:12:51 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)
de.tutao.tutanota
 Error message: Keychain operation failed deviceLock
Stacktrace: 
Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data (err -69)" UserInfo={numberOfErrorsDeep=0, NSDescription=ECIES: Failed to aes-gcm decrypt data (err -69)}

**Comment by charlag** [comment]
@bedhub did it just upgrade to iOS 15?

**Comment by charlag** [comment]
I propose to treat as invalidated keychain exception. I am pretty sure Apple changed something (kind of like the change of API on Android) but I have no idea what and where and whether we can adapt.

**Comment by FDUZS** [comment]
Same error on iOS 15.5

```
Feedback v3.96.8 - de.tutao.tutanota - UNKNOWN - ios



 Client: ios
 Type: UNKNOWN
 Tutanota version: 3.96.8
 Timestamp (UTC): Thu, 02 Jun 2022 23:16:59 GMT
 User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
de.tutao.tutanota
 Error message: Keychain operation failed deviceLock
Stacktrace: 
Error Domain=NSOSStatusErrorDomain Code=-50 "ECIES: Failed to aes-gcm decrypt data (err -69)" UserInfo={numberOfErrorsDeep=0, NSDescription=ECIES: Failed to aes-gcm decrypt data (err -69)}
```

**Comment by charlag** [comment]
This likely happens after restoring from iCloud backup (keys are not backed up but the other things are)

**Comment by charlag** [comment]
FWIW the whole thread of 1Password people trying to figure it out
https://1password.community/discussion/91882/touch-id-not-working-for-1password-after-macos-reinstall
