### ISSUE TITLE
Gift card is not displayed

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#3792]
When I buy a gift card from Settings > Subscription view, the gift card should be displayed in the according table.

**Comment by vaf-hub** [comment]
@mpfau can you provide more details when this happened? I just tried to reproduce it and for me the bought gift card was displayed correctly in the subscription settings. It disappears once it is redeemed, though. I also succesfully bought a gift card from the navbar.

**Comment by mpfau** [comment]
@vaf-hub you are right. It seems like I only checked after redeeming!
