### ISSUE TITLE
Notification not working on Android 

### ISSUE THREAD

**Issue by InfinityLoop1309** [tutao/tutanota#3796]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**
Notification not working on Android
**Describe the bug**
(When app asked for close battery optimization, I chose OK.)
Just as the title. The only time service work is the first time it installed. After being installed ~15-30min, the service never work.
App can only get notification when they are visiable. Once it turn to background, no notifications.

**To Reproduce**
1. Install
2. close it, wait for ~30min
3. It just happen

**Expected behavior**
Notification works.

**Screenshots**
Not applicable

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Oneplus 8T
 - OS: [e.g. iOS8.1] LineageOS 18.1 (Android 11)
 - Version [e.g. 22] 3.89.25

**Additional context**
Logcat not showing any related info. 
The most suspicious is
`01-16 20:16:04.282  1344  1344 I JobServiceContext: Client timed out while executing (no jobFinished received), sending onStop: 6ba8f16 #u0a228/1 de.tutao.tutanota/.push.PushNotificationService
`
But I'm not sure.

**Comment by kedwjao** [comment]
PushNotification is always running when I check it in the system

**Comment by kedwjao** [comment]
Tried to fix it myself but due to environmental problems I am not able to compile it (anything related to flow stuck forever). Hope maintainers could give this issue a high priority, and I will provide any info needed for solving this ASAP.

**Comment by charlag** [comment]
@kedwjao we don't use Flow anymore, please check out the latest commit on trunk

**Comment by kedwjao** [comment]
> @kedwjao we don't use Flow anymore, please check out the latest commit on trunk

Now it turns flow is not the problem - it stuck at `reify:app-builder-bin: timing reifyNode:node_modules/typescript Completed in 2976ms` LMAO
Since every solution I found not work, I would prefer wait for others to fix this.
