### ISSUE TITLE
Notifications are not displayed in MailSettingsViewer

### ISSUE THREAD

**Issue by vaf-hub** [tutao/tutanota#3802]
1. Go to EMail Settings.
2. At the bottom add a mail adress for notifications.
3. See that it can be added but is not displayed.

After adding the mail address notifications are sent but it is not shown in the setting and thus also cannot be deleted or deactivated.

After fixing the bug we should also check if it works when adding a new device.

**Comment by vaf-hub** [comment]
I just checked in the desktop client and there the notifications and push identifiers are displayed correctly and can be deactivated/deleted.

**Comment by charlag** [comment]
@vaf-hub I think it was broken before too, I don't see any changes done there but it should be easy to fix
