### ISSUE TITLE
[desktop/linux] fix & upgrade keytar

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3809]
Stock keytar doesn't tell us whether `getPassword` can't return a password due to user cancellation or because there's no password saved.

https://github.com/tutao/node-keytar makes that distinction visible on linux

## Testing

On Linux specifically:

* [x] starting tutanota desktop with an unlocked login keychain works as expected and sseInfo, notifications and alarms get loaded (install seahorse to check the keychain)
* starting tutanota desktop with a locked login keychain will prompt for the password and
   + [x] cancelling shows an error dialog that the keychain is unavailable
   + [x] unlocking the keychain causes startup to proceed normally

**Comment by EVLRBT-01** [comment]
Will this build on arm64? I believe the existing keytar was one of the blockers for getting Tutanota running on arm64 Linux, so would be great if this was solved. 🙏

**Comment by charlag** [comment]
@EVLRBT-01 it's not a blocker anymore since we build keytar on our own anyway. We just don't provide ARM builds yet, for either Linux or Mac. Someone could just do it (like AUR does probably?)

**Comment by EVLRBT-01** [comment]
Excellent, will give it a go, thanks!
________________________________

**Comment by charlag** [comment]
I couldn't get it to work yet. Here's what I did:
 -  run `gnome-keyring-daemon -f -r` to effectively "lock" the keychain
 -  Start the app
   - See keyring prompt, cancel it
   - See another keyring prompt, cancel it
   - client shows "could not access secret storage" dialog, see from output that client treats it like cancellation (like it should)
   - try to select stored credentials
   - See 2 other prompts and cancel them
   - client output "key credentials-device-lock-key not found, generating a new one" which shouldn't actually happen

**Comment by charlag** [comment]
This is actually more of a #3733 so I will move it there
