### ISSUE TITLE
Provide an 'undo send' button

### ISSUE THREAD

**Issue by Jos512** [tutao/tutanota#381]
The Tutanota email client can really benefit from an 'undo send' feature, like GMail has. That way when we press 'Send', there is a number of seconds in which we can cancel sending to correct an error.

This also has a privacy benefit, in case we realise after pressing 'Send' that we used the wrong Tutanota alias to reply from or inserted the wrong signature and contact details.

**Comment by armhub** [comment]
Thanks for the idea, but this would be a very time-consuming implementation, so we will not be able to do it.

**Comment by 4jNsY6fCVqZv** [comment]
@armhub What exactly makes the implementation of this feature so time-consuming?
