### ISSUE TITLE
Description not formatted when importing events to the calender

### ISSUE THREAD

**Issue by Emiliaaah** [tutao/tutanota#3819]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When importing a calendar event from an email the formatting on the description breaks.
(I do actually believe it also does this when doing a normal import and not specifically one attached to an email)

**To Reproduce**
1. get an invite to a calendar event
2. click "view event"
3. click the edit button
4. click save
5. if you now go to your calendar and open the event the formatting on the description will be broken

**Expected behavior**
The description should keep the formatting.

**Screenshots**
(What is looks like)
![image](https://user-images.githubusercontent.com/55017867/150167071-7da7aa15-165f-40b9-ba1d-cd0b95378277.png)
(what it should look like)
![image](https://user-images.githubusercontent.com/55017867/150171062-75bb2e93-de2a-4a19-b8b5-56923d50f99f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Desktop Environment, if applicable (on Linux)
 - Version v3.89.25

**Additional context**

**Comment by johnbotris** [comment]
Some services use plaintext with a custom markup for formatting in their event descriptions. Tutanota currently only stores and interprets event descriptions as HTML. This issues is the same as https://github.com/tutao/tutanota/issues/3507
