### ISSUE TITLE
Option to always show sending email address in 'compose new email' window

### ISSUE THREAD

**Issue by Jos512** [tutao/tutanota#382]
When I compose a new email in Tutanota, it by default hides the email address I would be sending from. Because I have multiple aliases, I always have to click 'Show more' to select which alias I'd be sending from.

It would be easier if there's a setting to always show the alias setting. That way people who often need to switch between aliases can do so easier.

An extra benefit is that this makes the error of using the wrong alias less likely, since the address from which the email is send isn't hidden anymore. (When that human error occurs, there's also a decent privacy exposure, which makes it even more important to clearly show the sending email address in the compose new mail window.)

**Comment by charlag** [comment]
Already there for a while
