### ISSUE TITLE
iOS App throws "unable to connect" while trying to connect sometimes.

### ISSUE THREAD

**Issue by Buttermilch13** [tutao/tutanota#3837]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

From times to time when opening the App on ios it says "unable to connect to server".

There is also then no new DNS Resolution referring to my pihole.

As I am facing those issue on an iPhone 12 and 11 pro plus also whitelisted all necessary domains in my pihole I am assume it could be a bug.

**To Reproduce**
1. Open the App.

**Expected behavior**

A successfull login.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [12,11pro]
 - OS: [iOS15.2]
 - Version [1]

**Additional context**

**Comment by Buttermilch13** [comment]
Any Updates on this ?:)

**Comment by charlag** [comment]
@Buttermilch13 we don't seem to be able to reproduce this, is there some specific scenario where it happens? We need more information to make a guess

**Comment by Buttermilch13** [comment]
Hi, i would answer that with no i guess. I am running a normal iPhone With a pihole and it will happen reguarly:) 
I an also do Not use dns over tls of dnssec.

**Comment by Buttermilch13** [comment]
Friendly reminder

**Comment by charlag** [comment]
@Buttermilch13 sorry for the delay, we are unable to reproduce this so far. I will close this for now, feel free to provide more info or send logs to support.
