### ISSUE TITLE
Typescript does not write incremental results to the disk

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3842]
tsc has an option to write incremental results to the disk to make rebuilds faster. It seems like Rollup plugin for Typescript does provide some directory for tsc but it doesn't seem like any cache is actually written. This makes rebuilds slower.

We should try to specify the directory manually or report a bug to Nollup.

**Comment by rosso-ptg** [comment]
It seems the incremental results/cache is indeed written to disk and appears to be picked up by rollup. The typescript plugin we are using (https://www.npmjs.com/package/@rollup/plugin-typescript) seems to not fully support some of the more recent typescript features such as project references, incremental builds, etc.
The linked commit adds project references and incremental build settings to all the packages/modules of tutanota. This will at least somewhat speed up the rebuild of packages.

**Comment by elemesa** [comment]
Ok bien reçu. 

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., févr. 4, 2022 à 9:23, ***@***.***> a écrit:   


Closed #3842.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
