### ISSUE TITLE
CC and BCC set from a mailto link or draft are not shown by default

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3844]
The CC and BCC lines are collapsed by default, and for this case, they probably shouldn't.

# Test notes

## Mailto
- [ ] Click on a mailto link that has no CC/BCC in it (e.g. [mailto:test@test.com](mailto:test@test.com))
    - [ ] Verify that CC and BCC are not displayed.
- [ ] Click on a mailto link that has CC in it (e.g. [mailto:test@test.com?cc=cc@test.com](mailto:test@test.com?cc=cc@test.com))
    - [ ] Verify that CC and BCC are now displayed.
- [ ] Click on a mailto link that has BCC in it (e.g. [mailto:test@test.com?bcc=bcc@test.com](mailto:test@test.com?bcc=bcc@test.com))
    - [ ] Verify that CC and BCC are also displayed.
- [ ] Click on a mailto link that has CC and BCC in it (e.g. [mailto:test@test.com?cc=cc@test.com&bcc=bcc@test.com](mailto:test@test.com?cc=cc@test.com&bcc=bcc@test.com))
    - [ ] Verify that CC and BCC are also displayed.

## Drafts
- [ ] Click "New email" to open the mail editor with a new email.
    - [ ] Verify that CC and BCC are not displayed yet.
- [ ] Click "Show" to expand CC and BCC and add a recipient to CC, and close the mail to save it as a draft.
- [ ] Reopen the mail.
    - [ ] Verify that CC and BCC are already expanded.
- [ ] Add a recipient to BCC and close the mail to save it as a draft.
- [ ] Reopen the mail
    - [ ] Verify that CC and BCC are already expanded.
- [ ] Remove the recipient from CC but leave BCC in the draft, and close the mail to save it as a draft.
- [ ] Reopen the mail
    - [ ] Verify that CC and BCC are already expanded.

**Comment by paw-hub** [comment]
We should also extend this behavior to drafts so that, when editing a draft, the user is aware of the CC/BCC fields in the draft, as those are also not immediately visible in the preview.
