### ISSUE TITLE
MAPI doesn't attach files from certain applications

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3847]
in windows, with tutanota as the default email client:
* from libreoffice or adobe reader, choose "file -> send -> email as document"
* see that there is no attachment in the new mail editor

The file should have been attached

Testing:
- [x] follow the reproduction steps, files should be attached correctly
- [x] files are still correctly attached when sent from the file explorer
- [x] files are named correctly i.e. when sent from libreoffice

- [x] temporary files are being created under `C:\Users\<user>\AppData\Local\Temp\tutanota\attach` in all cases, even when `tutanota\attach` subdir wasn't already existent

**Comment by johnbotris** [comment]
https://github.com/tutao/mapirs/issues/13

fixed by: https://github.com/tutao/mapirs/pull/12

**Comment by charlag** [comment]
From Libreoffice file -> send -> email as document did not work

**Comment by charlag** [comment]
fresh local install
