### ISSUE TITLE
Autocorrect messes with input in email input field

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3849]
### to reproduce
On android

* go to the account recovery dialog from the login screen
* start typing an email address into the input field
* see that autocorrect is primed with some suggestion
* upon typing '.', that suggestion will replace the typed email address

### what should happen?
The input text should not be replaced with anything

It's happening in v3.89.25, so pre-typescript

**Comment by johnbotris** [comment]
This also happens in the mail editor

**Comment by ganthern** [comment]
still happening in 3.98.20
