### ISSUE TITLE
Calendar invite emails trigger white background

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3851]
1. Send calendar invite
2. Open it on the client with dark theme selected
3. See that the white background is applied even though there's no text color defined

It seems like our `<hr>` element is triggering it unintentionally because its style has `background`.

**Test notes**

- [ ] Send calendar invite, open with dark theme selected and confirm that the mail body has the dark theme applied.

**Comment by sarashub** [comment]
The white background is triggered because the <hr> element has white background set and the logo has white background set.
We discussed with @bedhub to only show the hr element if the logo is shown but in the end decided to remove the logo so that themes can be applied.
