### ISSUE TITLE
iOS message body height does not fill screen

### ISSUE THREAD

**Issue by alstr** [tutao/tutanota#3863]
**Bug in mobile app**

**Describe the bug**
When viewing a particular email, the height of the message body goes incredibly small. You have to scroll the tiny pane to view all of the content. Alternatively, you can zoom in and zoom out and it resets to fit the window correctly, but on returning later it will be back to the original state.

**To Reproduce**

I can currently only reproduce this with one email which leads me to believe it is something particular about its layout. The issue does not occur on desktop.

**Expected behavior**
The message should fill the remaining blank space on screen.

**Screenshots**

![IMG_1705](https://user-images.githubusercontent.com/11612438/152496536-08029e28-b9ab-4029-8f3f-5a8a45f70160.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 15.2.1
 - Version: V3.91.6

**Comment by charlag** [comment]
We've seen such behavior before but I believe it was fixed with one of the early iOS 15 versions.
Could you forward this specific email to support?

**Comment by alstr** [comment]
I see. I don't want to forward this particular email, but if it happens with another one I will do.

**Comment by bedhub** [comment]
doesn't seem to happen anymore.
