### ISSUE TITLE
Tutanota does not store the password

### ISSUE THREAD

**Issue by Ahmed-E-86** [tutao/tutanota#3887]
**Describe the bug**
After the latest update, the application keeps asking for E-mail address and password every time I open it, and it does not store them anymore.

**Desktop (please complete the following information):**
- OS: Kubuntu 21.10
- Desktop Environment: KDE Plasma 5.22.5
- Version: 3.91.10 (Flatpak)

**Comment by pizzadude** [comment]
Even with https://github.com/flathub/com.tutanota.Tutanota/commit/5f3036baffa5f9700380f2e09a73795dde3171d3 it still doesn't work.

**Comment by charlag** [comment]
First of all, and I can't stress it enough, *Flatpak is in preview*. There are known issues.
Second, there was a fix specifically for flatpak yesterday evening (3.91.10-1)

**Comment by pizzadude** [comment]
So I should use the appimage?

**Comment by Ahmed-E-86** [comment]
The [tutanota-desktop-3.91.10-unpacked-linux.tar.gz](https://github.com/tutao/tutanota/releases/download/tutanota-release-3.91.10/tutanota-desktop-3.91.10-unpacked-linux.tar.gz) works fine without any issues. Maybe it is time to remove the Flatpak version.

**Comment by Aaron-von-Awesome** [comment]
> > First of all, and I can't stress it enough, _Flatpak is in preview_. There are known issues. Second, there was a fix specifically for flatpak yesterday evening (3.91.10-1)
> 
> Is the status "preview" related to the problem reported here?
> 
> I have been using the Tutanota app for over a year now and have not had any problems like this before.
> 
> In any case, the latest update does not solve the problem.

I concur - this issue should not have been closed...

**Comment by pq2** [comment]
@charlag I think that this issue should be reopened. The problem still persists and was not fixed by version 3.91.10-1.

**Comment by charlag** [comment]
I will reopen it because it is still the case for many people

**Comment by charlag** [comment]
Will keep tracking on Flatpak, it has nothing to do with the app itself I'm afraid
https://github.com/flathub/com.tutanota.Tutanota/issues/77
