### ISSUE TITLE
server borked today.

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [tutao/tutanota#3891]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**

got this error while ago, after refreshing tutanota : 

```
Feedback v3.91.10 - TypeError - UNKNOWN - Browser

 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.91.10
 Timestamp (UTC): Sat, 12 Feb 2022 21:19:08 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
TypeError
 Error message: ServiceWorker script at https://mail.tutanota.com/sw.js for scope https://mail.tutanota.com/ encountered an error during installation.
```

**To Reproduce**
just be logged in, refresh and you got it. : | both with being logged out

i use free version.

PS: second thing to say - ur server laggy and making 'store password' doesnt do that for longer than 3 days :/ (probly server problems)

**Comment by hacknorris-aka-penguin** [comment]
problem still is but now it didnt logged me out :/

**Comment by johnbotris** [comment]
Which browser are you using, and do you have any extra security settings or addons enabled? Can you reproduce this consistently? I cannot.

**Comment by hacknorris-aka-penguin** [comment]
it wasnt? firefox (with privacy addons ofc - eff badger, decentraleyes, ublock and tor). and reproduce - now no but still its slow asf. this bug was yesterday cause probly you was either updating, had a hacker or was messing up with servers...
