### ISSUE TITLE
Tutanota does not store the password

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [tutao/tutanota#3892]
**Describe the bug**
After the latest update, the application keeps asking for E-mail address and password every time I open it, and it does not store them anymore.

**Desktop (please complete the following information):**

    OS:  Linux Mint 20.3
    Desktop Environment: Cinnamon 5.2.7
    Version: 3.91.10-1 (Flatpak)

Related to this issue that should not have been closed:  https://github.com/tutao/tutanota/issues/3887

**Comment by charlag** [comment]
This is a flatpak issue that you linked, please keep track of it in that repo
