### ISSUE TITLE
Comment field in contact viewer is not selectable

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3895]
In the contact viewer the comment field is not selectable in web and mobile apps. A user should be able to select the content to support  copy & paste.

Tutanota version: 3.91.10 (Browser und apps)

**Comment by ganthern** [comment]
## Testing
test selecting and copying text from the contact comment:
* [ ] firefox
* [ ] chromium
* [ ] safari
* [ ] mobile

**Comment by mpfau** [comment]
couldn't test on safari but I should be fine.
