### ISSUE TITLE
Clicking on bottom of text input field does nothing

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3896]
**Describe the bug**
When writing an email, Tutanota presents a large text box. However, clicking at the bottom of that text box does not select it although the mouse courser is set to text style.

**To Reproduce**
1. Open mail editor
2. Click on the very bottom of the mail editor

**Expected behavior**
Courser should be placed to the end of the existing text and i can start typing.

**Screenshots**

**Version**
 - Tutanota version 3.91.10

**Comment by johnbotris** [comment]
# testing
- [ ] in mail editor, when cursor is not in the mail body editor, clicking anywhere below the text will place the cursor in the mail body
- [ ] regression test other editors (they render and behave as normal)
    - [ ] signature editor
    - [ ] notification editor
    - [ ] template editor
    - [ ] event editor
