### ISSUE TITLE
Selecting and overwriting a word using shortcuts removes the space before the word

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3897]
**Describe the bug**
If i use the shortcut ctrl-shift-left to select the previous word and then press a chracter to overwrite the word the space in front of the word is also removed.

**To Reproduce**
1. Open mail editor and write some text
2. Use ctrl+shift+left to selct previous word
3. Start writing new word and see that space will be removed.

**Expected behavior**
The space should remain between the words.

**Version**
Tutanota 3.98.20 (Desktop, Chrome, **not** Firefox)

**Comment by rezbyte** [comment]
I cannot reproduce this anymore.
