### ISSUE TITLE
improve WebDialog API

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#3899]
The recently introduced `WebDialog` (https://github.com/tutao/tutanota/pull/3889) uses a special preload script for its `BrowserWindow`. 

It should be possible to use a single preload script for all `BrowserWindows` and configure the set of messages that get handled automatically.

**Comment by charlag** [comment]
@ganthern isn't this already the case? It just has `init` and `facade` and the rest depends on a URL?

**Comment by charlag** [comment]
Ah, you mean to have the same preload script for WebDialog and main IPC. I am not sure about this but I think we need to definitely redo main IPC with more common code.
