### ISSUE TITLE
Unexpected error message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3900]
**Describe the bug**
Unexpected error message when starting tutanota desktop client (see detailed error message below) and the user can't login using stored credentials. 

**To Reproduce**
1. uninstall gnome-keyring
2. start tutanota and log in using stored credentials / try adding stored credentials.

**Expected behavior**
An error message should be shown that some dependency is missing and the gnome-keyring needs to be installed. Option to save credentials should not be available.

**Desktop (please complete the following information):**
 - Linux desktop client 3.91.10

**Additional context**
We had this problem before when storing alarms to the keychain (see #2929) and the reason was that we are using `keytar` for accessing the keychain and keytar depends on `libsecret` and that requires `gnome-keyring` to be installed on the system. As soon as  `gnome-keyring` is installed the error should not occur anymore. We are now storing the key for encrypting credentials to the keychain and that is why this error occurs more often #3733.

One option might be to replace `keytar` with electrons `safeStorage` api but there are some problems because the api requires a window to be present #3676 and we cannot use this aproach for securing the alarms.

As we cannot remove the dependency in the short term we should catch the error and show an appropriate error message that a dependency is missing. If possible we can also disable the "save credentials" checkbox.

#3676
#3733
#2929
#1257

> Client: linux
> Type: FREE
> Tutanota version: 3.91.10
> Timestamp (UTC): Mon, 14 Feb 2022 20:43:21 GMT
> User agent:
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.10 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
> Error
> Error message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
> Stacktrace:
> Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service file

**Comment by qube-03** [comment]
i am currently experiencing the exact problem here.
im trying to log in using the flatpak and each time it tells me an error occured with this log.

**Comment by charlag** [comment]
@bedhub `libsecret` is *provided* by `gnome-keyring` but can be provided by anything

**Comment by charlag** [comment]
FAQ entry: https://tutanota.com/faq/#secretstorage

**Comment by ganthern** [comment]
## Test Notes
* [ ] when logging when no libsecret is available (for example a stock kubuntu install) and the save credentials checkmark is set, the client doesn't save credentials and doesn't show the uncaught error popup, but logs a device storage unavailable message. login proceeds as normal
* [ ] when libsecret is available, but the keychain is locked and the prompt is cancelled at the time of login with a set save credentials checkmark, the login fails and no credentials are saved

### Regressions:
* [ ] make sure saving credentials with an unlocked keychain works
* [ ] login with saved credentials with unlocked keychain works
* [ ] login with saved credentials while the keychain is locked fails when the prompt is cancelled

**Comment by charlag** [comment]
Yes, seems like we don't handle it when logging in but I think it's pretty rare
