### ISSUE TITLE
Unexpected Error message: The file was externally modified

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3902]
Feedback v3.91.10 - Error - UNKNOWN - linux

Client: linux
Type: UNKNOWN
Tutanota version: 3.91.10
Timestamp (UTC): Sat, 12 Feb 2022 18:02:00 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.10 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
Error message: The file was externally modified
Stacktrace:
Error: The file was externally modified

**Comment by ThracianKnight1907** [comment]
I get this error every time I close and then reopen Tutanota's window. After a reboot, the app will log me out, but If I log back in, the cycle repeats

**Comment by neptalactone** [comment]
I also experience this. Here's my error message. I'm using the flatpak version.

```
Feedback v3.91.10 - Error - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.91.10
 Timestamp (UTC): Tue, 22 Feb 2022 09:40:49 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.10 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
 Error message: The file was externally modified
Stacktrace: 
Error: The file was externally modified
```

Basically the same error message like @bedhub

**Comment by charlag** [comment]
@ThracianKnight1907 @neptalactone are you using flatpak by any chance too?

**Comment by ThracianKnight1907** [comment]
Yes

**Comment by ganthern** [comment]
some more reports:

> My login keeps getting rest, even if I toggle "store password".

> Always get logged out despite storing password on this machine

> I cannot login to the flatpak App on POP OS. Am logged into other accounts and can log in via web and android app, just not on flatpak. Said wrong credentials at first. restarted the Tuta app and now it just says error.

**Comment by SethFalco** [comment]
I have the same issue, just want to share the details on my side in case it helps.

OS: Debian GNU/Linux 11 (bullseye) x86_64
CPU: 11th Gen Intel i7-11370H (8) @ 4.800GHz
Flatpak version: Flatpak 1.10.7
Tutanota version: 3.91.10-1

When I close and open the Window, I get the following exception:

```
Client: linux
Type: UNKNOWN
Tutanota version: 3.91.10
Timestamp (UTC): Tue, 01 Mar 2022 10:04:00 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.10 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
Error
Error message: The file was externally modified
Stacktrace:
Error: The file was externally modified
```

To work around this, I go to `htop` and kill the process. But when I launch Tutanota again it fails to open the system keyring and I have to put in the credentials for all of my inboxes again.

**Comment by charlag** [comment]
We should move this to the [flathub](https://github.com/flathub/com.tutanota.Tutanota/) repo

**Comment by ganthern** [comment]
> We should move this to the [flathub](https://github.com/flathub/com.tutanota.Tutanota/) repo
