### ISSUE TITLE
[Wayland] Do not even start

### ISSUE THREAD

**Issue by BirdInFire** [tutao/tutanota#3904]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When i use flatseal to forbid the start with Xorg (Xwayland) on the now default desktop environment (Gnome Wayland (Mutter)), the app don't start at all, can you fix (update) the electron to actually support native Wayland instead of relying of the insecure Xorg (Xwayland).

**To Reproduce**
1. Go to Flatseal, uncheck X11 and fallback X11 (only let Wayland)
2. Click on Close and restart the app
3. See error it doesn't start

**Expected behavior**
Starting on native Electron's code for wayland.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] (Linux Fedora 35)
 - Desktop Environment, if applicable (on Linux): Gnome Wayland (Mutter)
 - Version [e.g. 22] 3.91.10 (Flatpak)

**Additional context**
Since Electron support native wayland and many Linux distro (even with Nvidia driver) now use it as default it must be functional relying on the transition system (who have their security concern) isn't enough, and when i use a secure services (like tutanota) i expect flawless security (even if the security come from another services used (flaw in the Xorg design).

**Comment by charlag** [comment]
Please open the issue at https://github.com/flathub/com.tutanota.Tutanota/
Flatpak has a lot of known issues at the moment
