### ISSUE TITLE
Eyedropper in desktop Linux application returned NaN

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3909]
**Describe the bug**
In the calendar menu, I click the "+" sign to create a new calendar, which produces this dialogue. I then click the color indicator bar to choose the color of the calendar items. I was pleased to find an eyedropper option!

**To Reproduce**
1. In the calendar menu, I click the "+" sign to create a new calendar,
2.  I click the "+" sign to create a new calendar and click on the color indicator bar.
3. Select eydropper to select a color from screen
4. no matter what I eyedrop, the R component always ends up "NAN" as in the screenshot.

![Screenshot_20220217_001856](https://user-images.githubusercontent.com/8296817/154985146-cf6f1290-1b77-447a-8f59-6d329fbb19c7.png)

**Comment by ganthern** [comment]
Doesn't reproduce on Ubuntu, Pop!_OS, Mint Cinnamon or Kubuntu in 3.98.17.
