### ISSUE TITLE
Text overflow in mail authentication InfoBanner

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3910]
Text overflow is not set correctly for the InfoBanner box on small screen sizes. See screenshot:
![Screenshot_20220217_001856](https://user-images.githubusercontent.com/8296817/155083956-1ae7ea81-79c9-4c10-90fc-5e9623828ec7.png)

# Test notes
- [ ] Resize the client's window to be small
- [ ] View an email with a notice that its contents cannot be verified but also shows a technical sender with a long address in a banner. Alternatively, use Developer Tools to make the displayed technical sender a long sequence of characters that cannot be broken up easily (e.g. a long sequence of repeated characters such as `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@email.com`).
- [ ] Verify that it is correctly wrapped to the end of the banner and that it does not overflow off the edge.

**Comment by nif-tutao** [comment]
Text overflows the InfoBanner only if technical sender address is too long. Text in the InfoBanner with any short address doesn't overflow the frame of the banner.
Checked on desktop client v. 3.98.4
