### ISSUE TITLE
WebDialog should not have ServiceWorker enabled

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3914]
**Describe the bug**

![Screenshot from 2022-02-23 11-19-32](https://user-images.githubusercontent.com/3099142/155300569-7d979021-c502-4f2f-ab04-9ecd22ab0896.png)

**To Reproduce**
1. On desktop authenticate with Webauthn
2. Release a new version of the client
3. Authenticate with webauthn again
4. See update popup

**Expected behavior**
There's no update popup and we always load the most recent version of the client in WebDialog.

**Additional context**
ServiceWorker caching might give us unexpected client version and also has other side-effects like update popup.

**Comment by johnbotris** [comment]
# Test notes
- [ ] Follow reproduction steps,  the issue doesn't happen
- [ ] service worker still runs in the web

**Comment by johnbotris** [comment]
The serviceworker still runs
