### ISSUE TITLE
Not all users load when first navigating to user management

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3928]
* Login
* Switch to the user management section
* Not all of the users are loaded
* Go to a different view and then back to user management
* All the users are now loaded

I was able to reproduce on one of my  test system accounts. The global admin user shows initially, but all other only show after the second load

**Comment by charlag** [comment]
Same can happen if inbox rules moves email before the list loads

**Comment by charlag** [comment]
How to reproduce this for the mail list:

1. Have an empty folder. Make sure you *don't* open that folder after logging in
2. Move some mails to that folder
3. Open that folder
4. See that only one email is displayed
