### ISSUE TITLE
Recipient lists

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#393]
As a user I want to be able to create recipient lists. When sending a mail or calendar invites I want to be able to use such a list in the address field to send the mail to every user in the list without entering each mail address individually. Furthermore, I want to be able to share such lists with other users and define who has which right on the list (read/write/manage). 
For privacy reasons I only want to share the mail address for each entry in the recipient list but not the entire contact I have in my private contact list. I do not want to share entire contact lists. In the contact view I want to be able to see and edit all my recipient lists and who they are shared with.

**AC:**
- [x] #5407 
- [x] #5432 
- [x] #5433 

**IH:**

- Sharing is a solved problem. See shared calendars and template groups.
- When the user enters such a list in the address field every mail address should be resolved like we do now and the user should be informed if there is a problem with one mail address. They should be able to decide if this address should be excluded. If no errors occur, sending such a mail should work just like the user had entered each address individually, i.e. the mail is encrypted for every recipient and then sent.

## Layout Proposals
(these are missing the "sh-are recipient list" action)

One folder entry per recipient list
![Image](https://user-images.githubusercontent.com/29049728/232474212-3cfa62c7-70c6-445f-98bb-a160d91b6883.png)

Lists of Recipient lists
![Image](https://user-images.githubusercontent.com/29049728/232473393-98b78f15-fd60-4dc8-a144-5966de5bf637.png)

**Comment by musicmissionary** [comment]
Yes, please! This would be a great help. I really need to be able to set up contact groups for regular emailing to groupings of recipients. Tutanota can only be an occasional use client without this feature.

**Comment by opensam** [comment]
I'm trying Tutanota : my use case is e-mail communication inside a relatively small group (less than 50 people). I appreciate the service. I value the privacy features and I would like to advocate Tutanota to all members of the group (most of them use GMail, YMail, MS, etc). But I can NOT recommand Tutanota because of this very missing feature of recipients groups.

**Comment by michaeljensen** [comment]
I want to setup a couple of my custom domains in Tutanota, but this feature is required for me to do so.  Any ideas as to where this falls in the priority list?

**Comment by brshub** [comment]
These recipient or contact groups would also be useful for adding groups of guests into the Tutanota calendar.

**Comment by Trai1Blaz3r** [comment]
This is the main reason I'm unable to refer Tutanota to friends. Because there's no way to send a group email to my friends!
How do I even let them know my new email address? Help!

**Comment by MelbourneGirl** [comment]
please please please: can you add recipient lists?
* Create different lists of recipients in the contact view

This function would make a HUGE difference to me.

**Comment by Pryla** [comment]
Main and only reason for me and my family to wait until we switch to tutanota. It makes me loose a little bit of trust to see that this is a 3yo topic and it does not seem to be integrated within this or the next year..

**Comment by edearmicas** [comment]
I join the petition because it is a facility widely used in the management of emails.  Not having her detracts a lot from the tutanota service.

**Comment by DavidKuttruff** [comment]
I would also love to be able to create email recipient groups.  This is the only reason I still keep Thunderbird around.

**Comment by kukini118** [comment]
This is much overdue!
I made the switch to Tutanota a few years ago and have been very happy with it. I, like the other requesters, have the need to be able to send out emails to groups of people. I have worked around it but it is inconvenient and not efficient. 

Please add this functionality!

**Comment by edearmicas** [comment]
Me adhiero a la petición, que también hice hace ya más de un año,. No es normal que una aplicación de correo que se precie de ser actual no tenga esta funcionalidad.

**Comment by bedhub** [comment]
all the functionality has been released with 3.118.1

**Comment by MelbourneGirl** [comment]
Hi Thanks for this. To confirm: It is now available on a Paid Plan? 
Please note none of the paid plans list "Contact Groups" as accessible under their plan. 
Otherwise great work!!

**Comment by charlag** [comment]
Hi, the feature is available for new paid plans. We've just updated the pricing list to include the info: https://tutanota.com/pricing

**Comment by MelbourneGirl** [comment]
Thanks. It's not yet visible on list on the pop-up screen from the Macbook based App. When I click on Contacts> Contact List '+', the 'Plans' window, doesn't have it.

**Comment by charlag** [comment]
It will show up with the next release
