### ISSUE TITLE
Windows desktop client is broken

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#3940]
To reproduce:

- install desktop client for windows
- see the following error occur when you run it
![windows_error](https://user-images.githubusercontent.com/58424555/156392254-e7a35e94-8a79-4494-8d69-2dc82c2f7fbc.png)

**Comment by johnbotris** [comment]
We aren't building SQLite3 on the windows machine, we need to do the same as we do for keytar

**Comment by charlag** [comment]
@johnbotris should work without it (mapi is only working w/ Wine for some reason)

**Comment by johnbotris** [comment]
fixed by https://github.com/tutao/tutanota/pull/3948

**Comment by johnbotris** [comment]
# Testing
* follow reproduction steps, app starts successfully without the error message
    - [ ] windows
    - [ ] linux
    - [ ] mac
- [ ] MAPI still works
    * In windows, with tutanota set as default mail client, go to file explorer, right click a file an choose to send as an email. tutanota is loaded with a new mail and the file is attached
- [ ]
