### ISSUE TITLE
Show buy dialog when there is no price change.

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#3949]
As an admin of a Tutanota account i want to see that adding an additional user or other item is without charge if i pay a fixed amount or there is a discount.

**Acceptance criteria**
* Buy dialog is shown when adding a feature and there is no price change.
* Buy dialog is shown when removing a feature and there is no price change.
* When there is no price change the dialog should use "confirm" instead of "buy/order"

**Comment by bedhub** [comment]
We will change this behavior to fix https://github.com/tutao/tutanota/issues/3946

**Comment by ganthern** [comment]
## Testing
(start server locally and change prices in BookingItemService.java to get orders with no net price change)

### General
* [ ] when ordering a feature that increases the price, the buy dialog shows up with a "Buy" ok button
* [ ] when the price decreases, it shows up with an "Order" ok button
* [ ] if the price stays the same, the button says "Accept"

### Regressions for ordering
* [ ] cancelling an order in the buy dialog works
* [ ] Whitelabel 
* [ ] Users 
* [ ] Sharing 
* [ ] Aliases
* [ ] contact forms
