### ISSUE TITLE
U2F windows visual issues on macOS

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#3950]
1. Incorrect padding below or incorrect window size
2. Rounded window which doesn't look like our dialog (not that significant)

![Screen Shot 2022-03-07 at 13 29 16](https://user-images.githubusercontent.com/3099142/157036006-c448d9e9-7d79-4542-8cf0-cfbd5cedcdd1.png)

**Comment by ganthern** [comment]
## Testing 

* [ ] the WebDialog that appears after clicking "use security key" in the SecondFactorAuthView has sharp corners$
* [ ]  it looks convincingly like a tutanota dialog

### Regressions
* [ ] retest https://github.com/tutao/tutanota/issues/2178 "Check WebDialog window behaviour" on mac
