### ISSUE TITLE
Trusted emails ends up in Spam

### ISSUE THREAD

**Issue by Umeaboy** [tutao/tutanota#3952]
Everytime I get an email from a trusted company called Matsmart (Food smart in English) it goes straight to Spam and I haven't even marked it as Spam. I get this mail as I'm subscribed to their mailing list.

1. Go to https://www.matsmart.se/
2. Subscribe to their mailing list.
3. Wait for the email to appear.
4. After a number of emails the incoming emails get sent to Spam instantly.

**Expected behavior**
Since this email comes from a trusted company I'd like to see that their emails don't end up in Spam in the future.

**Screenshots**
![Matsmart](https://user-images.githubusercontent.com/714473/157208384-9be5f761-453b-498f-89ee-6c0ee7928e57.png)

**Desktop (please complete the following information):**
 - OS: Mageia 8
 - Desktop Environment: MATE
 - Version: 1.24.1

**Comment by charlag** [comment]
@Umeaboy please contact support about specific cases so that you can share more details with them
