### ISSUE TITLE
[Linux/Flatpak] "The system keychain has been invalidated. Deleting stored credentials"

### ISSUE THREAD

**Issue by Mek101** [tutao/tutanota#3953]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
After logging in, quitting the application and re-opening, it doesn't automatically login but displays the error above: "The system keychain has been invalidated. Deleting stored credentials".

**To Reproduce**
1. Login normally, selecting "store password".
2. Quit tutanota from the notification menu
3. Restart tutanota
4. Not logged in, error instead

**Expected behavior**
Being automatically logged in at restart

**Screenshots**
![Schermata da 2022-03-08 14-43-29](https://user-images.githubusercontent.com/34246799/157249895-3a118352-9d51-430a-bea7-26338103652c.png)

**Desktop**
 - OS: Manjaro, Flatpak
 - Desktop Environment: Gnome 42.3
 - Version: 3.39.5

**Comment by bedhub** [comment]
Can you please check if this can be solved by installing gnome-keyring?
Please check this issue for more details:
https://github.com/tutao/tutanota/issues/3900

**Comment by charlag** [comment]
This is tracked there:
https://github.com/flathub/com.tutanota.Tutanota/issues/77

**Comment by passthejoe** [comment]
> Can you please check if this can be solved by installing gnome-keyring? Please check this issue for more details: #3900

I have GNOME-KEYRING, and the behavior is still the same.

**Comment by h5law** [comment]
I am having the same error, gnome-keyring installed too.
OS: Fedora 35, Flatpak
Desktop Environment: Gnome 41.4
Version: 3.95.4

**Comment by ItsMeOnceMore** [comment]
I have the same problem on iOS.

**Comment by barcazama** [comment]
Still a problem on PopOS 22.04 LTS using flatpak version 3.106.4 (using the appimage work out of the box, so I will use that instead)

**Comment by alongwhile** [comment]
I am seeing this using Fedora Workstation 37.  I used the above posted workaround by logging in via appimage initially, which resolved the problem.  Hope this gets fixed eventually!

**Comment by Dumb223** [comment]
Having the same issue on Xubuntu 23.04, Tutanota version 3.112.6. 
AppImage seems to work fine instead.
