### ISSUE TITLE
Colour theme back to default after log out

### ISSUE THREAD

**Issue by NGeek752** [tutao/tutanota#3954]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
The web app doesn't seem to remember the selected colour theme after logging out from the browser.

**Expected behavior**
I thought when switching to a colour theme like the dark theme, the web app would remember my choice.
However, after I logged out and logged in again, the colour theme changed back to the default white and red theme.
Not sure if this is by default or an issue btw

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser: Firefox ESR
 - Version: 91.6.0esr

**Comment by bedhub** [comment]
The color theme in the webbrowser is only available on your whitelabel domain. It will not apply on the domain https://mail.tutanota.com. The colors appear there when you configure the colors for the first time to give you a preview of how your whitelabel theme looks like. But after logout or reloading the site the default theme for http://mail.tutanota.com applies. 
When you access https://<your-whitelabel-domain>  the colors should appear always.

**Comment by charlag** [comment]
I think there's misunderstanding, this bug was not about whitelabel. However we are unable to reproduce an issue, I suspect that your localStorage does not work.
