### ISSUE TITLE
Unread email count badge number in iOS disappears immediately after opening the app

### ISSUE THREAD

**Issue by ryancabanas** [tutao/tutanota#3955]
- [ X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ X ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When a new email arrives, the app icon will receive a badge number "1" to show me that there is a new email.  When I open the app, but do **_not_** read the new email, and then simply minimize (or close) the app, the app badge is now gone, implying that I have no unread emails, when in fact, I **_do_** have an unread email.

**To Reproduce**
1. Receive a new email in my `@tutanota.com` mailbox.
2. The app icon will receive an app badge with a "1" on it, indicating I have an unread email.
3. Log into the mobile app.
4. Minimize (or close) the mobile app **_without_** reading the new email.
5. Note that the app badge with a "1" is now gone, even though the email has **_not_** been read.

**Expected behavior**
After opening the app, **_not_** reading the new email, and then minimizing (or closing) the app, the app badge with a "1" should **_still_** be present on the app because I still have an unread email.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.3.1
 - Tutanota App Version: 3.93.4

**Additional context**
I am a paying customer.

**Comment by bedhub** [comment]
We like to use the badge for unread notifications. 
https://github.com/tutao/tutanota/issues/1757
