### ISSUE TITLE
Unread email count badge number in iOS is never higher than "1", even though multiple unread emails are present

### ISSUE THREAD

**Issue by ryancabanas** [tutao/tutanota#3956]
- [ X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ X ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When multiple new emails arrive (let's say "2" new emails), the app icon will show a badge number "1", instead of a "2".  Regardless of how many new emails you receive, the app badge number never goes higher "1".

**To Reproduce**
1. Receive a new email in my `@tutanota.com` mailbox.
2. The app icon will receive an app badge with a "1" on it, indicating I have one, new, unread email.
3. **_Without_** having opened the app, receive another new email in my mailbox.
4. Note that the app badge still only says "1", conveying that I have only 1 new unread email, when, in fact, I now actually have "2".

**Expected behavior**
When receiving multiple new emails, the app badge number should reflect how many new, unread emails I have waiting for me in my inbox.  Using the example steps described above, I should see an app badge number of "2" on the app icon.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.3.1
 - Tutanota App Version: 3.93.4

**Additional context**
I am a paying customer.

**Comment by bedhub** [comment]
We like to use the badge for unread notifications. 
https://github.com/tutao/tutanota/issues/1757

**Comment by ryancabanas** [comment]
@bedhub To be honest, that doesn't really make a whole lot of sense because that's what Banners are for.  There are already `Lock Screen` banners, `Notification Center` banners, and unlocked screen `Banners`.  All, of which, are working properly for the Tutanota iOS app.

![IMG_5805](https://user-images.githubusercontent.com/27093222/157574726-eb090f93-ed74-4c48-9300-15cb3e87d93a.jpeg)

Why would you want to take the `Badge` setting and turn it into yet another notification banner, of sorts?  Every other iOS app I've every used uses the `Badge` setting for indicating the count of **_"something"_**.  And in the case of all iOS email apps I've ever used, that count of **_"something"_** is/are unread emails.

Can you please at least explain the logic behind choosing to turn the `Badge` setting into a 4th (and unnecessary, I would argue) banner option in iOS?

Thanks.

**Comment by thommesborg** [comment]
@ryancabanas let me jump in: it's because we are used to it. Furthermore, displaying only a 1 on the badge, even though several messages have arrived, is misleading and irritating. You may kill the 1 and replace it with an Asterix, or a sm:)ey, but a counter has to count - up and/or down.

**Comment by charlag** [comment]
@thommesborg the #1757 is planned and it will show the number of unread notifications since opening the app :)

**Comment by thommesborg** [comment]
@charlag thank you for bringing the other bug report to my attention!
