### ISSUE TITLE
"An error occurred" on android app login

### ISSUE THREAD

**Issue by Skyterix1991** [tutao/tutanota#3965]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Trying to log in for the first time on the android app with a new account, it shows the error message "An error occurred". It's a new account with a 2fa setup.

**To Reproduce**
1. Login into the android app

**Expected behavior**
Login successfully.

**Smartphone (please complete the following information):**
 - Device: Galaxy S7
 - OS: LineageOS 19.0 (Android 12L)

**Additional context**
Both the f-droid and the google play version does not work.

**Comment by charlag** [comment]
Oh but it's Android 12, my apologies. What's the app version?

**Comment by Skyterix1991** [comment]
> Oh but it's Android 12, my apologies. What's the app version?

3.93.7

**Comment by charlag** [comment]
Do you see some details of the error?

**Comment by Skyterix1991** [comment]
> Do you see some details of the error?

Just this message and option to "send report". I sent it earlier today.

**Comment by charlag** [comment]
Thank, no idea yet but and so far only you reported that, need to keep looking into it

**Comment by Skyterix1991** [comment]
I figured out what happened. Few days ago google released "L" update for Android 12 and broke the keystore. They released patch fixing it, so it should work now. (Btw. what a great timing I choose to install the app 🙂)

I will install the patch in an hour so I will let you know if the issue is resolved.

**Comment by Skyterix1991** [comment]
Yes, the issue was resolved in newest patch.
