### ISSUE TITLE
Can't inline attachments in app

### ISSUE THREAD

**Issue by ballo** [tutao/tutanota#3979]
[x ] I've searched and did not find a similar issue.

I consider this a bug. If you don't, fine, but it's not listed in the issues either way (and there is no way in heck I'm getting a plebbit account. That's just another bug)

**Comment by johnbotris** [comment]
@ballo can you please elaborate on what you mean by this?

**Comment by ballo** [comment]
Feel free to label it however you wish. I can only make bug reports

**Comment by johnbotris** [comment]
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Feel free to make a feature request via [reddit](https://www.reddit.com/r/tutanota/) or [contact us](https://tutanota.com/contact/).
Thanks for understanding.

**Comment by charlag** [comment]
You can inline attachments via editor bar but it's not available on all platforms yet (should at least be on desktop and web)
