### ISSUE TITLE
Attachments are opened in the same tab as the web client in firefox

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3983]
* in firefox, click on an attached PDF
* It automatically opens in the same tab

If you are using the client without saved credentials, this also results in you being logged out.

This doesn't happen for all filetypes, e.g. images and text files are just downloaded

We should either make sure that the PDF opens in a separate tab _or_ just download it and not try to open it automatically. This seems to be some firefox specific behaviour, as in chromium PDFs are just downloaded.

Some users have noted that firefox no longer offers to open images in a preview after downloading. We might want to do this manually, if it's what users expect.

**Comment by sarashub** [comment]
This seems to be this a firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1756980
A workaround would be to got to Settings->General, scroll to the "Applications" section and change the PDF action to something other than "Open in Firefox".

**Comment by johnbotris** [comment]
### Testing notes
- [ ] In Firefox >= 98, when PDFs are set to be opened in firefox automatically, clicking on a PDF attachment will open it in a new tab
- [ ] In Firefox >= 98, the user specified behaviour for PDFs is always respected (go to settings > applications and check the various options for PDFs).

- [ ] In Firefox < 98 (try version 97 or 68 ESR), behaviour is unchanged for opening attachments (PDF and otherwise) Check various settings like "Open in firefox", "Always ask", "Save to", etc
- [ ] Attachment downloading behaviour is unchanged in Android
- [ ] Attachment downloading behaviour is unchanged in iOS
- [ ] Attachment downloading behaviour is unchanged in Linux desktop
- [ ] Attachment downloading behaviour is unchanged in Mac desktop
- [ ] Attachment downloading behaviour is unchanged in Windows desktop
- [ ] Attachment downloading behaviour is unchanged in Chromium
- [ ] Attachment downloading behaviour is unchanged in Safari
- [ ] Attachment downloading behaviour is unchanged in Edge

**Comment by charlag** [comment]
When FF 98 is set to open PDFs it will both open and save the pdf which is a bit confusing

**Comment by charlag** [comment]
Chrome 100.0.4896.60, always downloads PDF, regardless of browser setting, but this seems to be unchanged

**Comment by charlag** [comment]
> Linux desktop, "open" and "download" do the same thing?

Win desktop the same, both open, not download.

**Comment by charlag** [comment]
Downloading PDFs in mobile Safari is a bit wonky, it will also replace the app and you might even need to press "back" twice but Safari on iOS is not a primary target so I think it is fine.
