### ISSUE TITLE
Build doesn't fail when running a build with typescript errors on existing server

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3984]
* have a build server running and finish a successful build with `node make`
* introduce typescript errors into the code
* run `node make` again
* see that the build "finished successfully", but no new output is generated

It should pick up that the typecheck failed and fail accordingly. It works correctly again once you run a clean build.

This doesn't seem to happen _all_ of the time, but fairly often

**Comment by vaf-hub** [comment]
For debugging it would probably be nice to print which files have been changed after calling `node make`.

**Comment by johnbotris** [comment]
the typechecking error does get logged to the file once the new build runs, but it isn't picked up by nollup/builder or what have you
