### ISSUE TITLE
Congrats message upon completion of signup

### ISSUE THREAD

**Issue by hahub** [tutao/tutanota#3990]
When a signup has been completed, the user should not be sent to the login screen right away.

### Acceptance Criteria:

* After signup is complete, the wizard doesn't disappear immediately
* It will instead show a celebratory message 'Welcome to your encrypted mailbox.' until dismissed
* after it is dismissed, the login page is shown as it is now

### Hints:

* the wizard would track another page with the bar at the top
* a follow up dialog after the wizard would be annoying
* → options: add hidden pages to the wizard or have an option to display an icon (confetti, fireworks, a star) instead of the sequence number in the last place of the wizard progress bar

**Comment by ganthern** [comment]
implemented with https://github.com/tutao/tutanota/pull/5136
