### ISSUE TITLE
LazyLoaded gets stuck with a ConnectionError even after connection is restored

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3995]
For example:
* Go to calendar view
* Lose your network connection
* Try to open a new event edit dialog (it fails due to lost connection)
* Restore your network connection
* Any further tries to open the dialog will result in a connection error

This is because we are using `LazyLoaded` for some state, which remembers it's most recent error. In the case of `ConnectionError`s, we probably would want to always retry (not just in the case described above).

If we want to make a special case for `ConnectionError` inside of `LazyLoaded.getAsync`, we would probably have to move the RestError family either into `tutanota-utils` or some other package.

We would want to take care of this to have a properly functioning reconnect with offline mode

**Comment by charlag** [comment]
We should not cache errors in `LazyLoaded`, that simple

**Comment by ganthern** [comment]
I'm not adding test notes yet because for some reason I can't actually reproduce the problem, which means there's no comparison for the PR

**Comment by ganthern** [comment]
## Test Notes

* [ ] trying to open a new event edit dialog in calendar view succeeds
    * [ ] without connection problems
    * [ ] when it previously failed because of connection problems
