### ISSUE TITLE
Templates lists don't reload when reconnecting

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#3996]
We only load the templates in the settings view constructor, and if none load (i.e. due to a connection error), we just assume that we don't have any. Once we reconnect, they will not reload until you refresh the app.

To reproduce 
* have a template list, with templates
* go offline
* go to settings
* select "My Templates"
* The list says that you have none
* Reconnect
* The list hasn't changed, there is no way to get your existing templates to load

also, trying to create a new template after the fact results in a bad request error

**Comment by paw-hub** [comment]
Does not occur on 3.98.16
