### ISSUE TITLE
Add list of former automated email subjects

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#4003]
We have a number of automated emails (invites, giftcard, ...) with localized subjects. These are whitelisted in the server to not be flagged as spam.
When the translation changes, the server needs an update to get the new translation whitelist.
It would be better to keep track of those in this repository so it is not necessary to do a server side release every time we do a client release that changes them.

### Acceptance Criteria:
* It is possible to update whitelisted email subjects without having to do a server release.

### Hints:
* Collaborate with the infra team to find out how to best distribute this between the mail server, web server, spam filter and other components which may not necessarily be located on the same server.

**Comment by ganthern** [comment]
closed by https://github.com/tutao/tutanota/pull/6882
