### ISSUE TITLE
Cannot open "move mail" dropdown with a shortcut twice

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4006]
1. Open an email, press "V", see dropdown with folders
2. Open another email, press "V", see no dropdown

**Comment by johnbotris** [comment]
# Test notes
- [ ] Select a mail in the mail list, type "V" -> A move mail dropdown opens up
- [ ] Select another mail in the mail list, type "V" -> A move mail dropdown opens up
- [ ] Change to a new mail list, repeat previous two steps
- [ ] Leave the mail view and return, select a mail, type "V" -> you know what should happen
- [ ] select multiple mails, type "V" -> you betcha
- [ ] after selecting multiple mails, select a single mail, type "V" -> nothing should happen (just kidding, a move mail dropdown should open up)
- [ ] In all cases, the move mail dropdown will be located at the selected mails in the mail list
