### ISSUE TITLE
Resetting second factor from 2FA prompt does not cancel login properly

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4008]
1. Have second factor for an account
2. Try to log in with that account, see 2FA prompt
3. Click on "lost account access link"
4. See that new dialog is opened, close that dialog
5. See that the progress is still ongoing. 2FA dialog was closed but the login was not cancelled.

Test Notes:
* [ ] reproduction doesn't work anymore with hardware key 
* [ ] also not with OTP

**Comment by ganthern** [comment]
Similar thing happens if you replace steps 3 and 4 with "click cancel in the 2FA prompt", but in this case the login gets eventually cancelled after the network request times out.

**Comment by charlag** [comment]
There's a slight visual glitch when switching between the dialogs (we probably should close one before opening another) but otherwise it's okay
