### ISSUE TITLE
Some alarms are still sent even after events are deleted

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4010]
Users periodically report that but there's no proven recipe to reproduce it.

>I have deleted from my calendar two recurring events for which I set a daily reminder, however, I keep on receiving the event notification with the event name on a daily basis.

>Events are daily (one at 9:00, the other at 20:00).
Event Duration was set to 30 mins each.
Only one alarm, 5 minutes before the event for both of them.
Problem occurs both in the mobile version (Android) and in the desktop client (Windows).

**Comment by letscho123** [comment]
I still receive old reminders on my Android phone since more than a year now for 3 different repeating events. Even deleting all calendars and re-installing the app (F-droid version) didn't help.

**Comment by charlag** [comment]
@letscho123 if reinstall didn't help then maybe we need to look elsewhere

**Comment by charlag** [comment]
Duplicate of  #2523
