### ISSUE TITLE
Uploading with slow connection fails on Android

### ISSUE THREAD

**Issue by ballo** [tutao/tutanota#4035]
Missing for Android, iOS and desktop.

**Original issue:**

---

- [*] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [*] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
The app I'm only works with high speed internet when trying to send emails with attachments. Even though the connection is solid and is in the process of uploading the file, it will time out and give the nonsense error that the app is offline which is a lie.

**To Reproduce**
1) Go on a slow connection
2) Attach a file which takes a minute to upload 
3) Experience fail because the app runs out of patience
**Expected behavior**
Every other email app just waits for the upload to finish instead of trying to be too smart for its own good.

**Smartphone (please complete the following information):**
 - Device: S8
 - OS: 9
 - Version latest

**Additional context**
This makes the app kinda useless

**Comment by charlag** [comment]
Hi
Normally we detect that there's *some* progress every 20s but I checked now and I think there's only read timeout and not write timeout set for upload on Android

https://github.com/tutao/tutanota/blob/26c98dd37701c1c657edec33465d52e43e4a05cb/app-android/app/src/main/java/de/tutao/tutanota/FileUtil.java#L253-L259

**Comment by ballo** [comment]
Needed to send a series of small files and tried sending them one per email to no avail. Any file larger than 260kb causes a timeout. Useless.

**Comment by ganthern** [comment]
I'm adding the test notes to the PR (https://github.com/tutao/tutanota/pull/4055) because this may need attention on IOS and desktop as well.

**Comment by charlag** [comment]
Test notes: https://github.com/tutao/tutanota/pull/4055#issuecomment-1105175789
