### ISSUE TITLE
Change attributes of components to not accept streams

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4043]
This is mostly relevant for the generic components.

The problem we are having is that we can't enable `strictFunctionTypes` for Typescript because the type of generic attributes cannot be inferred correctly from the stream that we pass in.

It is also unidiomatic and is usually a mistake to pass a stream into a component, component must not hold on to attributes for longer than one render cycle so it doesn't make sense to update such streams. In case we need a callback it's best to use a callback explicitly (unidirectional data flow and all that).

## Test notes
Just quick regressions, should be obvious if something doesn't work:

 - [ ] Calendar export works and can be imported afterwards
 - [ ] Editing calendar events works: location, number of repeats, guest password, changing calendar, repeat end, summary
 - [ ] Merging contacts
 - [ ] Editing contacts
 - [ ] Renaming folders
 - [ ] Dropdowns work and filter
 - [ ] Segment control works (e.g. Private/Business on Signup)
 - [ ] Expander works (e.g. inbox rules)
 - [ ] Date picker works (search)
 - [ ] Checkbox works (signup)
 - [ ] Templates list works
 - [ ] Time picker works (e.g. event editing)
 - [ ] Contact form editor works
 - [ ] Contact form requests work
 - [ ] Login form works
 - [ ] Saving password works
 - [ ] Password fro external encrypted emails
 - [ ] Notification language for external encrypted emails
 - [ ] Adding custom email domain
 - [ ] Whitelabel settings
 - [ ] Editing notification email
 - [ ] Editing out-of-office emails
 - [ ] Adding second factors
 - [ ] Group viewer
 - [ ] Login settings
 - [ ] Mail settings
 - [ ] Rejected senders
 - [ ] Viewing users
 - [ ] Sharing groups (e.g. calendar)
 - [ ] Redeeming gift cards
 - [ ] Paying with credit card
 - [ ] Deleting account
 - [ ] Payment settings
 - [ ] Subscription settings
 - [ ] Support dialog

**Comment by charlag** [comment]
Running into some issues with `strictFunctionTypes`: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/60123

**Comment by ganthern** [comment]
* can't type into the folder name text field when creating or editing mail folders (updates get swallowed)
