### ISSUE TITLE
First Popup Option remains highlighted despite options further down being selected

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#4048]
**Describe the bug**
When opening an options list in the mail client under "...", the first option in the list will remain highlighted despite another option being selected. It then appears as a lighter grey rather than being returned to the default color. 

**To Reproduce**
1. Select an email 
2. Click on "..."
3. Scroll down to "Print" (with the mouse, doing it with the keyboard correctly unhighlights the item)
4. See error: "Mark Unread" remains a lighter grey, rather than returning to the default color. 

**Expected behavior**
The color returns immediately to the default, there appears to be a delay and when clicking outside of the mail client, it does return to normal.

**Screenshots**
![Screenshot from 2022-04-19 10-46-56](https://user-images.githubusercontent.com/82211006/163963349-37e95eb4-8215-4741-9daa-e2657dc82f63.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu, MacOS

**Comment by rezbyte** [comment]
I cannot reproduce this anymore on `v220.240408.0`.
