### ISSUE TITLE
Android App Problems

### ISSUE THREAD

**Issue by Citizen163** [tutao/tutanota#405]
- App start-time is too long.
- No options to view inside and manipulate app from notifications (e.g. get a notification of a new email that shows the subject and sender and options to delete, archive, etc. the email from that area)
- Contacts-parsing is non-existent, and fields standard should be customizable or, at least, it should be enough to log in all necessary information (e.g., please make it so I don't have to know the year someone was born in in order to know their birthday (I'm not going to ask every woman I talk to how old they are).
- Optional dark theme always (also for website). Should be an industry standard by now.

Will think of more if necessary.

**Comment by armhub** [comment]
Thanks for the feedback. These issues will almost all be resolved with the new Tutanota app coming in a few weeks. I will close this issue and please re-test with the new app. If there are still issues in the new app, please create individual issues for them.
