### ISSUE TITLE
"Looks like you are offline" message when sending email with attachments

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#406]
> I have a problem to send emails with attachments that are over about 1-2Mb. Actually, I get this error "Could not reach server, looks like you are offline. Please try again later." quite often even when I am dealing with emails with no attachments (even when trying to read them).

> I am now on W10Pro with MS Edge as the browser. I tried it again just now, sending from Tuta to my other email and got the same error with a 2.1Mg attachment.

> I am on a slow connection, about 3.8Mbits. I wonder if this is a problem. So it happens with large emails (like 1Mb upwards) but also sometimes like now with just text.

**Comment by bedhub** [comment]
I run into the 'Could not reach server. Looks like you are offline.' error quite often when I send files over a certain size. I have attached a screenshot with the error and with the other details I have. The total size of files is about 6.5MB. I am using Firefox 61.0.1. 

The error is a regular one for me. I go to app.tutanota.com in order to send those emails, which is what I did just now too. app.tutanota.com has no such problems.

**Comment by aleksandrkl** [comment]
Attached is a speed test of my connection with the issue of 'Could not reach server. Looks like you are offline.' when sending attachments. I am using Windows 7 Professional SP1.

Like above, the error is very regular for me. 

![screenshot_2018-09-05 speedtest by ookla - the global broadband speed test](https://user-images.githubusercontent.com/13829464/45100525-eba47800-b129-11e8-89fd-11b9e216e84f.png)

**Comment by bedhub** [comment]
> 
I was able to send a lot of emails but when I send an email with an attachment it does not leave and I have an error message that tells me that the server could not be reached, that I seem to be offline and try again later, it's been 3 days that I try and it's every time there is an attachment that it does not work.

**Comment by asteintutao** [comment]
Could reproduce it with a text file of 20 mb size console gives:

error ConnectionError: Reached timeout of 20000ms  | PUT /rest/tutanota/filedataservice
    at XMLHttpRequest.xhr.onabort (https://mail.tutanota.com/worker.js:1:554072)
    at https://mail.tutanota.com/worker.js:1:553005
