### ISSUE TITLE
U2F and FIDO2 keys don't work with Linux desktop client

### ISSUE THREAD

**Issue by realpixelcode** [tutao/tutanota#4061]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When logging in, one is asked to enter the OTP code or insert one of the registered security keys. However, the latter doesn't work in the desktop client (although it works perfectly fine in the browser). 

In particular, I've got a Nitrokey U2F and a Nitrokey FIDO2 stick which are both registered with my Tutanota account and work fine in Tutanota's browser login.

**To Reproduce**
1. Open Tutanota desktop.
2. Enter user name + password
3. Click on Login
4. “Click here to use security key”
5. Insert security key.
6. Nothing happens.

**Expected behavior**
Just like the browser version, Tutanota desktop should accept the security key.

**Desktop (please complete the following information):**
 - OS: Zorin OS (Ubuntu Ubuntu 20.04 LTS, Linux 5.13.0-40-generic)
 - Desktop Environment, if applicable (on Linux): GNOME Shell
 - Version: v3.95.4

**Comment by charlag** [comment]
Question: do you *clck* on the button which says "click there to use security key" or do you *just* insert security key?

**Comment by realpixelcode** [comment]
I wasn't sure but I just tried it again with actually clicking on the button but it didn't help.

**Comment by charlag** [comment]
What does it mean "it didn't help"? What does happen when you click on a button? Do you see a popup which asks you to insert the key? Is popup empty? Does popup not react to you inserting the key?

**Comment by realpixelcode** [comment]
After clicking on the "Click here to use the security key" button, a popup appears saying "waiting for the security key" with a rotating loading icon. When inserting, nothing happens – Tutanota Desktop keeps waiting for the U2F/FIDO2 key.

**Comment by charlag** [comment]
Thanks.
Question: is this flatpak by any chance?

**Comment by realpixelcode** [comment]
Yes, it's a Flatpak, since I downloaded it from the Zorin Store.

**Comment by charlag** [comment]
Please report Flatpak issues on https://github.com/flathub/com.tutanota.Tutanota/
