### ISSUE TITLE
Android-App u2f: "Your security key is not registered for this domain."

### ISSUE THREAD

**Issue by aliceTheGrinseCatz** [tutao/tutanota#4064]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**
1. Go to 'Tutanota for Android from Play Store and try to log in'
2. Click on '"Login" when you entered user name and password'
~~3. Scroll down to '....'~~
4. See error: "Your security key s not registered for this domain. Please login at <TUTANOTA>."

**Expected behavior**
Expect that the app would start Android's WebAuthn implementation to sign the login via FIDO2.
**Screenshots**
![Screenshot_20220426-050722 cleaned](https://user-images.githubusercontent.com/66872288/165213193-c6299c74-bf57-439d-b91a-d9f07e7d0b87.jpg)

**Smartphone (please complete the following information):** , , security patch level
 - Samsung Galaxy S21 5G
 - Android 12
 - Samsung OneUI 4.1(Kernel 5.4.129)

**Additional context**
Security Keys are shown in the Login settings in the app and work in the web app on LibreWolf for Debian/Ubuntu (Firefox).

**Comment by ganthern** [comment]
Just for reference, this is currently the expected behaviour because the key is in fact not registered to the domain that's being used in the android app - the web app is packaged within it and served from the file system. We want to improve that (tracked in https://github.com/tutao/tutanota/issues/443)

Related: https://github.com/tutao/tutanota/pull/3889

**Comment by charlag** [comment]
The message is misleading, there's just no U2F in Android app atm
