### ISSUE TITLE
Unable to delete messages

### ISSUE THREAD

**Issue by demianpeeters** [tutao/tutanota#4065]
Hello, 

For 2 days now, I can no longer delete messages from my inbox. 
I have the same issue on desktop and mobile app.
I logged out of all my active sessions, but it doesn't change anything

I constantly get the following error message: 
"This action cannot be performed at the moment because another action is still in progress. Please try later."

Thanks for your help!

**Comment by charlag** [comment]
@demianpeeters hi, thanks for the report. Are you a Premium customer? It might be best to message support so that we know which mailbox it is

**Comment by demianpeeters** [comment]
@charlag Thank you for your reply. Unfortunately, I am not a premium member. But I don't understand how this leaves me in a situation where I am unable to manage my emails.

**Comment by charlag** [comment]
I just wanted to find out whether we could look at your specific case privately. E.g. I would ask you to check logs in Settings -> About -> Send logs. Do not post them here. Feel free to post any findings here or send them to hello@tutao.de

**Comment by demianpeeters** [comment]
Dear @charlag I was able to send the logs to hello@tutao.de as you suggested and that solved the problem. A big thank you to you!
