### ISSUE TITLE
Update operations (e.g. marking email unread) fail with error offline because we can't encrypt entities

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4078]
When we want to re-encrypt an instance we need to get it's previous key.
If it was already updated with symmetric key then it is stored as a field: `_ownerEncSessionKey`.
This key is encrypted with a group key. However we don't have group keys offline (to get group key stored on `GroupMembership` we need `userKey` and to get that we need `passPhraseKey` which is encrypted with the session).

session -> password -> userKey -> groupKey -> ownerEncSessionKey

From the user perspective there should be no difference for offline and online login and it should behave the same: produce an offline message.

## Implementation hint
We normally encrypt only in two places: `ServiceExecutor` and `EntityRestClient`. We should add some handling for offline there to not try to encrypt and just bail out with offline error.

Related to #3888

**Test notes**
Log in while offline and verify, that all actions result in the expected behavior:

- [x] send mail
- [x] reply or forward 
- [x]  mark read
- [x] move mail 
- [x] delete mail 
- [x] archive mail 
- [x] report 
- [x] show email headers (from top menu or shortcut)
- [ ] Add spam rule
- [ ]  add inbox rule 
- [ ] add folder 
- [ ] export

**Comment by johnbotris** [comment]
Seems like there is a regression from https://github.com/tutao/tutanota/issues/4025. The add inbox rule silently failed and closed after clicking the ok button one time, it works as expected on subsequent tries. the clicking ok in the add spam shows an empty dialog (in addition to the snackbar):

![Screenshot from 2022-05-17 14-35-29](https://user-images.githubusercontent.com/22109738/168812422-03332346-6f15-4e2f-a976-72514e2fe0a8.png)
