### ISSUE TITLE
MailBody doesn't show when loading a partially cleared list

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4079]
this is a dev bug for https://github.com/tutao/tutanota/issues/3992

* load a folder (not the inbox)
* set the time range so that part of that mail list will be cleared on login
* log out, login
* go offline, navigate to the folder
* the mail list will load partially (as expected). Clicking on any mail in the list however will cause the mailviewer to just be blank, and a connection error shows

What should happen: None of the necessary data for rendering the mail should have been cleared, so it should be displayed properly. in any case, even if some data _is_ missing the connection error snackbar should not have shown, and a banner should have shown in the mailviewer, rather than being blank

**Comment by johnbotris** [comment]
#### Test notes
- [ ] follow reproduction steps, it works as expected

**Comment by ganthern** [comment]
resolved by 7b27a959
