### ISSUE TITLE
Unable to complete forms in emails as shortcuts take over

### ISSUE THREAD

**Issue by SethFalco** [tutao/tutanota#4092]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I received an email that contains text fields and a submit button in it.

However, I'm unable to actually type most characters in that form because of the shortcuts Tutanota have.

**To Reproduce**
1. Go to an email with a text field in it.
2. Click on the text field.
3. Type a character that happens to also be a shortcut, such as `s`.
4. See that instead of typing, it activates the shortcut.

**Expected behavior**
Similar to other web apps (like GitHub) if the user is in a text field, it shouldn't catch keyboard events and trigger shortcuts.

For example, I can type `s` in this field right now. But if I unfocus on the text field (i.e. click the background) then type `s` it'll activate the search shortcut.

**Screenshots**
![image](https://user-images.githubusercontent.com/22801583/166188624-f83fd04b-d58c-40e6-8975-e6b8cb1a82cc.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.10.0-13-amd64 Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux
 - Browser: Firefox Nightly
 - Version: 98.0a1 (2022-01-12) (64-bit)

# Test notes
- [ ] Receive an email with an input field in it. You can use the developer tools in a browser or client in the mail editor to do this.
- [ ] Select the input field in the email and type something that uses the entire alphabet (e.g. "The quick brown fox jumps over the lazy dog") into the input field
- [ ] Verify that typing into the input field works and does not trigger anything
- [ ] Click outside of the input field and press S
- [ ] Verify that the settings view is opened

**Comment by charlag** [comment]
Hi, thanks for the report, unfortunately it might be hard to reproduce without an example. Is it an option for you to share it with the support team?

**Comment by SethFalco** [comment]
Yeah absolutely! This isn't a sensitive email anyway.
I've forwarded it to the premium support address with the subject "GitHub Issue #4092".

**Comment by charlag** [comment]
Thanks a lot for the example!
I think email didn't get forwarded fully for some reason (probably chopped up by the editor) but I can still reproduce it.

For context of others: having an `<input>` in mailViewer is enough to reproduce it. Typing in it doesn't capture events for whatever reason.
