### ISSUE TITLE
Email Contacts are doubled

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#4093]
**Bug in web app**

**Describe the bug**
When entering an email address while choosing a recipient, the recipients are listed twice.

**To Reproduce**
1. Create an email draft
2. Click on "To"
3. Enter a known contact.

**Expected behavior**
The contact should be displayed once. 

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: Chrome

**Comment by charlag** [comment]
duplicate of #1283
