### ISSUE TITLE
Mac desktop client often crashes soon after startup

### ISSUE THREAD

**Issue by nadesco** [tutao/tutanota#4099]
I posted a Reddit message around 6 months ago to report that Tutanota’s desktop client crashed soon after computer startup. It usually happened when I opened tutanota.app along with 1 or 2 other apps at the same time. Since then the issue hasn't been resolved in updates, but there's been a slight change in that the last 1 or 2 crashes have happened soon after clicking on a hyperlink in a new email followed by clicking tutanota’s close button (bottom left corner). When I reopen Tutanota and click the hyperlink or close button again there is no crash. 

Since my Reddit post I’ve upgraded from Catalina 10.15.7 to Big Sur and am now on Mac Monterey 12.3.1. I’ve tried reinstalling tutanota.app and even did a clean install of the OS. One thing I noticed is that the error message shows Intel Mac OS X 10_15_7. Not sure why it would show this version because I purged all Tutanota related files on my HD. Unless I missed something?

Specs: Mac mini (2014), 480GB SSD, 2.6 GHz with 8 GB memory.

Reddit post  …
https://www.reddit.com/r/tutanota/comments/qmcr2h/recent_versions_of_desktop_client_crash_when/ 

Partial details of latest crash …
```
Client: darwin
Type: FREE
Tutanota version: 3.95.4
Timestamp (UTC): Wed, 04 May 2022 22:32:55 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.95.4 Chrome/98.0.4758.141 Electron/17.3.1 Safari/537.36
Error
Error message: ERR_FAILED (-2) loading 'file:///Applications/Tutanota%20Desktop.app/Contents/Resources/app.asar/index-desktop.html?noAutoLogin=true&platformId=darwin&theme=%7B%22themeId%22%3A%22light% …
[…]
… at rejectAndCleanup (../../../../../node:electron/js2c/browser_init:161:7647)
at EventEmitter.stopLoadingListener (../../../../../node:electron/js2c/browser_init:161:8022)
at EventEmitter.emit (../../../../../node:events:390:28)
```
ps; I've sent plenty of crash reports to Tutanota. The latest one was a few days ago.

Thank you

**Comment by charlag** [comment]
Hi, thanks for the report.
Do I understand correctly that the error happens on Monterey too? Because this message here is about Catalina.

**Comment by nadesco** [comment]
Hi, thanks for your reply. Yes that’s correct, I upgraded to Monterey around the end of February. I also don’t understand why the message refers to Catalina in the 4 May 2022 report, there should be no trace of it on my HD. It was a day or two before (2-3 May) that I did a search for all tutanota related files on the HD and deleted them. I then installed a fresh version of 3.95.4 after downloading it from your site. 

I also kept a copy of a crash message from Apr 30 which has the same details as May 4, except that this crash happened before I reinstalled the app.
```
Client: darwin
Type: FREE
Tutanota version: 3.95.4
Timestamp (UTC): Sat, 30 Apr 2022 07:58:20 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.95.4 Chrome/98.0.4758.141 Electron/17.3.1 Safari/537.36
Error
Error message: ERR_FAILED (-2) loading 'file ... etc
```

**Comment by charlag** [comment]
This is indeed odd, could you try deleting `/Users/YOUR_USERNAME/Library/Application Support/Tutanota Desktop` again please?

**Comment by nadesco** [comment]
Ok, done. For the record I quit the app before deleting `Tutanota Desktop` and signed in again. 
Tutanota has been stable since the May 4 crash but will let you know if/when it plays up again.

**Comment by nadesco** [comment]
@charlag, just a note to say that it hasn’t crashed for quite a while so it was most likely a corrupted file in the tutanota-desktop folder that was causing the problem. Still don’t why OS X 10.15.7 showed up in the error messages though. Anyway, thanks for your suggestion.
