### ISSUE TITLE
The client column in Active Sessions in User Settings -> Login is very narrow and unreadable at smaller resolutions

### ISSUE THREAD

**Issue by Jlll1** [tutao/tutanota#4108]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
The Client column in **Active Sessions** table in **User Settings -> Login** is made very narrow at smaller resolutions and becomes unreadable

**To Reproduce**
1. Go to Settings -> User Settings -> Login
2. Scroll down to Active Sessions
3. Increase your zoom level to 125-150%
4. See the **Client** column being made narrower and unreadable.

**Expected behavior**
The **Client** column is readable even at lower resolutions.
The columns can be made narrower equally or the entire menu could be made wider at lower resolutions.

**Screenshots**
Screenshot at 150% zoom:
![image](https://user-images.githubusercontent.com/71319302/167116821-ae8607b8-7050-4351-9a5f-aa7660ce6c9c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Qutebrowser
 - Version 2.5.0

**Comment by rezbyte** [comment]
Fixed by #6240.
