### ISSUE TITLE
Update fail

### ISSUE THREAD

**Issue by Vy511** [tutao/tutanota#4111]
**Describe the bug**

Update install failed repeatedly.
Now won't even download

**Expected behavior**
Update would install

**Screenshots**

![Screenshot_20220506-102517](https://user-images.githubusercontent.com/105032073/167183282-084db0fd-d937-4d21-a103-a8de2b20a923.png)

![Screenshot_20220506-102455](https://user-images.githubusercontent.com/105032073/167183289-fb350622-bdcf-476d-b561-29f3db0671e5.png)

**Smartphone (please complete the following information):**
 - Device: Motorola G8 plus
 - OS: android
 - Version 10

**Additional context**

**Comment by SergejGri** [comment]
I have the same issue on Xiaomi 9T.

**Comment by Vy511** [comment]
Can't find a way to contact Tutanota...
Their contact\support doesn't support that problem and can't find a way to add it.

**Comment by charlag** [comment]
If F-Droid fails then the problem is F-Droid, sorry, not like we control how or where from they download anything

**Comment by Vy511** [comment]
F-droid, APK and playstore.
Playstore doesn't even have update apparently...
-- 
Sent with Tutanota, the secure & ad-free mailbox. 



May 9, 2022, 00:01 by ***@***.***:
