### ISSUE TITLE
Error in mail list in offline mode

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4114]
I was just clicking around the mailboxes after doing offline login. After going into one of the previously loaded mailboxes, I got this unhandled exception:

```
error TypeError: Cannot read properties of undefined (reading 'style')
    at eval (List.ts:1045:18) TypeError: Cannot read properties of undefined (reading 'style')
    at eval (nollup-int:///src/gui/base/List.ts:753:30)
```

Unsure how to reproduce it consistently

**Comment by charlag** [comment]
Duplicate of #4187
