### ISSUE TITLE
[offline] connection lost list item sometimes disappears

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4117]
When loading only part of a mail list when offline, sometimes the "connection lost" list item does not render properly:

![Screenshot from 2022-05-10 17-32-16](https://user-images.githubusercontent.com/22109738/167666654-0229b565-6069-4e76-a11f-591efab7b888.png)

in the photo, the final list item should contain the error message and retry button:

![Screenshot from 2022-05-10 17-33-16](https://user-images.githubusercontent.com/22109738/167666747-eaf03959-7b53-4ecf-8be5-8d1b998f93c1.png)

In this case it happened after offline login. I loaded part of the inbox and it rendered correctly. Then I navigated to another mail list, came back, and it was as pictured

**Comment by ganthern** [comment]
* load a folder (not the inbox)
* set the time range so that part of that mail list will be cleared on login
* log out, 
* go offline
* login
* navigate to the folder
* the mail list will load partially (as expected) and show an empty list element where the lost connection indicator should be

**Comment by johnbotris** [comment]
what should happen
- `loadMore` calls `loadAndAppendAnotherChunk`, which only returns a partial list
- `loadMore` then calls `loadMoreIfNecessary`, which tries to load the rest of the list, but gets an offline error
- because of the offline error, we show the connection lost indicator

what happens instead:

- `loadMore` is called
- `loadMore` calls `loadAndAppendAnotherChunk`, which only returns a partial list
- `loadMore` then calls `loadMoreIfNecessary`, which in turn doesn't try to do anything because this: `let lastBunchVisible = this.currentPosition > this.loadedEntities.length * this.config.rowHeight - this.visibleElementsHeight * 2` evaluates to false
- list gets confused and shows an empty list item

**Comment by johnbotris** [comment]
one solution is to make `loadMoreIfNecessary` wait until `oncreate` has finished
