### ISSUE TITLE
Invalid system keychain or unavailable device storage

### ISSUE THREAD

**Issue by Neyl-123** [tutao/tutanota#4122]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Can't login with stored credentials either due to invalid system keychain or unavailable device storage.

**To Reproduce**
The first login works, but if I close and reopen it gives the invalid system keychain error and if I also close the desktop client via the little icon in the top right corner and reopen than it gives the DeviceStorageUnavailableError.

**Expected behavior**
You should be able to login without re-entering the credentials every time.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04
 - Desktop Environment, GNOME 42.0

**Additional context**
```
Feedback v3.96.3 - DeviceStorageUnavailableError - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.96.3
 Timestamp (UTC): Wed, 11 May 2022 07:40:34 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.96.3 Chrome/98.0.4758.141 Electron/17.4.2 Safari/537.36
DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: The file was externally modified
Stacktrace: 
DeviceStorageUnavailableError: failed to resolve/generate key> Error: The file was externally modified
    at nd.fetchOrGenerateKey (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:886826)
    at async wf.decryptUsingKeychain (/app/lib/tutanota/resources/app.asar/desktop/DesktopMain.js:13:974669)
```

**Comment by Neyl-123** [comment]
Yes, it's the Flatpak version.
 Should I report it to PopOS then?

**Comment by charlag** [comment]
@ganthern might know more, he did tests w/ PopOS

Closing in favor of https://github.com/flathub/com.tutanota.Tutanota/issues/77

**Comment by kibhub** [comment]
I have a report of this issue on the Appimage. 

The Flatpak error about secret storage also looks a bit different.

**Comment by charlag** [comment]
@kibhub 

>The name org.freedesktop.secrets was not provided by any .service files

**Comment by kibhub** [comment]
This issue is irrelevant after switching to electron's safeStorage API.
