### ISSUE TITLE
Show appropiate error message when offline db is not present

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4126]
There are scenarios where the offline db is not present and we need to show an appropriate error message in that case.

Proposal: "No data stored locally. Establish internet connection and log in to your mailbox."

**Notes**
This situation might occur if you enable offline mode for the first time and try to log in offline right away.
Happens when db is purged in case OutOfSync.
Might occur when try to log in with another account.
 
Trying to login offline before your offline database has been created gives a generic message like "connection was lost". We should probably let the user know specifically that they will need to login once to create the database. Or we might consider initializing the offline db when offline mode is enabled (and also after doing out of sync handling)

related to #4067

**Comment by johnbotris** [comment]
I added it to the offline login milestone for now, but I would also suggest we don't have to fix this now or really at all - if the database has been deleted then it makes no difference if the user can log in or not

**Comment by ganthern** [comment]
we decided that this is such a rare edge case once we have offline by default that it's not worth the effort.
