### ISSUE TITLE
[offline] Database sometimes doesn't get closed when login fails

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4133]
Not able to consistently reproduce it, it happened when I tried to log in with client using credentials from a previous instance of the dev server, I got the error message "Trying to delete database that is opened 2 times" when i tried logging in again. Can't reproduce it by just deleting the session from another client. Seems like a very corner case but we should keep an eye out for it

**Comment by ganthern** [comment]
I think this is resolved by now
