### ISSUE TITLE
Wrong day formatting in Chrome for some dates

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#414]
new Intl.DateTimeFormat("en-GB", {day: 'numeric', month: 'numeric', year: 'numeric'}).format(new Date(1919, 3, 15))
Result is "14/04/1919" although it should be "15/04/1919"
This only happens for some past years and never for the current one.

**Comment by asteintutao** [comment]
Works with the latest chrome version chrome stable# 67.0.3396.99.
but can be problematic for older versions.
