### ISSUE TITLE
offline login fails for saved credentials that already have offline storage enabled

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4150]
related: #3888 

for now, observed on mac

**Test notes**
 - [ ] Upgrade from the 3.96.3 with offline enabled (might need to build locally). Should be able to log in
 - [ ] Regression testing for downloading missed events after logging in with/without offline
 - [ ] Regression testing for recovering from closed session

**Comment by charlag** [comment]
I could reproduce it locally (build for b663a57ffe7981090b8def9d4824889870a34be2, enable offline, log in, build for `master`, try to log in, `GroupInfo` is not cached)

**Comment by ganthern** [comment]
when closing the session from the browser while logged in and online with deactivated offline, the window gets booted to the login screen only after clicking something.
