### ISSUE TITLE
Remove self from shared calendar keeps entry for self

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4154]
1. Share calendar of user A with user B
2. As a user B, join the calendar
3. As a user B, remove self form calendar
4. Observe that the dialog is not closed nor the entry is removed from sharing dialog but the calendar disappears
5. As a user A, invite user B again with different permissions
6. As a user B, accept the invite
7. As a user B, open sharing dialog. Observe that own entry is displayed twice

**Comment by wrdhub** [comment]
I tried to repro this today, and this issue does not occur anymore.
