### ISSUE TITLE
Free user gets same time range for offline data as premium user when using same dektop client

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#4155]
To reproduce:

- login as premium user and change time range for offline data (e.g. 60 days)
- login as free user in same desktop client and observe that the same time range is assigned

**Comment by johnbotris** [comment]
#### test notes

Have 2 Premium users A and B, and one Free user C

- [ ] login with A, set time range to 10
- [ ] login with B, time range is set to 31. set it to 20
- [ ] login with C, time range is set to 31, and is not configurable
- [ ] A, B and C's respective time ranges are unaffected when others change
