### ISSUE TITLE
Retry button in mail list breaks if pressed before reconnect

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#4165]
To reproduce:

- log in offline an have a mail list that is loaded incompletely
- turn network back on
- press retry button in mail list (and not press reconnect in offline indicator)
- observe that retry button disappears and mail list fails to load completely 

This seems to be caused by an error being thrown due to incomplete login.

**Test notes**
 - [ ] Reproduce the issue
 - [ ] Test recover login
 - [ ] Add new login

**Comment by charlag** [comment]
For more context: this happens when we have network connection but before we have fully logged in, and the loaded part of the list must be non-empty.

We do make network request successfully (since we have access token) but since we did not log in we do not have encryption keys yet.
