### ISSUE TITLE
search does not work in offline

### ISSUE THREAD

**Issue by sarashub** [tutao/tutanota#4168]
To reproduce:

- go offline after login and search for a mail that has already been loaded and is inside the configured time ranges for search and for offline data
- observe that search yields no results

**Comment by charlag** [comment]
I think there might be some context missing, e.g. was the search index built before offline was enabled?
I couldn't reproduce it either with 3.96.5

**Comment by sarashub** [comment]
With 3.96.5 and a fresh config directory I cannot reproduce it either.
