### ISSUE TITLE
Update documentations for new WebApp and AndroidApp

### ISSUE THREAD

**Issue by Dutisto** [tutao/tutanota#417]
Hi,
I followed the README instructions for building the WebApp and the AndroidApp, but i realised that they only build the "old" version and not the version available at https://mail.tutanota.com. I couldn't find any documentations in the branches. Could someone provides some ?

Have a nice day :)

**Comment by charlag** [comment]
Hi! We definitely should do this. As you may know, we did not publish the new app yet, it is in active development but it's going to be out very soon.

Roughly instructions are the following:
 * Build JS frontend as usual. To build against the production system do `node build prod`
 * Make sure there's a symlink located in the `app-android/app/src/main/assets` named `tutanota` pointing to the `build` folder:
```
➜  assets git:(master) ✗ ls -lA
total 0
lrwxrwxrwx 1 ivk ivk 21 Jun  6 16:24 tutanota -> ../../../../../build/
➜  assets git:(master) ✗ pwd
/home/ivk/dev/repositories/tutanota-3/app-android/app/src/main/assets 

```
 * Build Android app as usual (use Android studio or do `./gradlew assembleRelease` and sign manually as described [here](https://developer.android.com/studio/publish/app-signing)). Use `debugDist` or `release` build types.

We plan to do some work in the future to make it easier to build and sign the app.

Have a nice day too!

**Comment by Dutisto** [comment]
Hi,
Thanks for your answer ! 
Does the app currently available use Google's librabries for notifications ? From what i read in the source code, and the first time I opened it in an emulator, it might but I just want to be sure. 

For the WebApp : I run ` cd tutanota && node build prod`, then `cd build && npm start`. Works fine, but it is the official way ?

For the AndroidApp : I didn't understand i needed the `node build prod` so my app never worked^^.

**Comment by charlag** [comment]
Glad to help!

The old app (available in the Play store) is based on Cordova and uses GCM/FCM. The new one is based on the Server-Sent events protocol and does not depend on Play Services.

I think all of us use node build prod to build but most of us is serving the code using backend server, although server.js can be used too for serving the code. Not sure what you mean by official way.

**Comment by Dutisto** [comment]
Hi,
I meant how you guys usually do it. `npm start` works fine. If you guys wants, i can provide a Dockerfile for the WebApp and i can also make one for building and signing the apk. So users will only need to run the Dockerfile and don't struggle with the building process. 
Let me know if you're interested :)

**Comment by charlag** [comment]
We never do npm start afaik so I'm not even sure what it does.
We do something like `node build watch` and we start a separate server.
We need to modify our gradle build script to allow easier building + signing things but I'm not sure if we really need Docker. Will it simplify something?

**Comment by Dutisto** [comment]
It depends, for the WebApp, it would simplify the building. Users will only need to do something like `cd tutanota && docker build -t tutanota/webapp . && docker run --rm -p 80:80 tutanota/webapp` for example. For the APK, I was thinking of something like `docker run --rm -v $(pwd):/output tutanota/android ` All of the building will be done in the docker, so no more building errors on that user specific computer and no more troubles installing node, android sdk etc...

You can also host your images in Docker Hub so this will be more easily accessible.

It was just an idea, i'm willing to dev the WebApp Dockerfile (was going to do it anyway for my personnal use), and also the android's one, if you guys are interested :)

**Comment by charlag** [comment]
Just to be clear (I am not so good with Docker): we are not going to distribute binary Docker images, right? It is just instructions how to build an image?

**Comment by Dutisto** [comment]
Actually you can do both.
Let me just explain the concept :
Let's say you decide to add support for Docker. Someone will write a Dockerfile. The Dockerfile is just a script for building a docker image, like `Step 1 : Copy the app folder; Step 2 : npm install`. I'm a user, I clone the repo where the Dockerfile is, I build the image `docker build -t tutanota:my-tutanota . `. Once my image is ready, i can use it whenever I want with `docker run --rm -p 80:80 tutanota:my-tutanota`. I can also change something in the Dockerfile and build again an image. The Dockerfile will just be a tool for me, and I won't bother install node or something.
So in this example, anyone can build and/or modify the Dockerfile and so the Docker image as he wants.

Second example : 
Tutanota expands his Docker support by creating a Docker repository on Docker hub (https://hub.docker.com/). Tutanota will push to this repository its already builded images. This way, users don't have to clone the repo or build the image themselves, but won't really be able to make significant change to the image (they still can, but not as easily as with the Dockerfile).

At the end of the day, you decide how you want it. You can have the two options : a prebuild image anyone can use easily and a link to the repo so if someone want to change/add something, they can. You can have only the Dockerfile in your repo, or only the image available in the Docker Hub.

I hope I was clear enough :)

**Comment by charlag** [comment]
Thanks, this was super clear! We would be glad to have such a thing to make hackability easier.

**Comment by Dutisto** [comment]
Nice, I will start my dev then :)
