### ISSUE TITLE
Unhandled PreconditionFailedError for some features during account downgrade

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4181]
For example, Precondition failed Header for downgrading a user  that has shared mailboxes:
precondition bookingservice.shared_group_active

Repro:
* create premium user with shared mailbox (or probably other sharing feature)
* try to downgrade
* see an unexpected error dialog (no report)

**Comment by wrdhub** [comment]
I don't know when this got handled (couldn't find a specific issue), but this no longer happens. For shared mailboxes or other shared things (calendar, contact lists).
