### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by whawk7** [tutao/tutanota#419]
When you are waiting for a new mail (e.g. the confirmation mail from GitHub), it appears in Inbox after a log out/log in. Sometimes the Sent folder is not refreshed as well when I choose forward or reply option for a new mail.
Used browser is Chrome 67.0.3396.99 (Official Build) (64-bit).
Used web client is the new one.

**Comment by charlag** [comment]
Hi!
We had some server side issues in the last days. Can you please tell if it happens all the time?

**Comment by whawk7** [comment]
I have just made a try and the problem still exists (eg. the Sent folder has been not refreshed after mail forward).

**Comment by charlag** [comment]
Could you please post your browser console log around such event? It is most likely a broken websocket connection

**Comment by whawk7** [comment]
The console log has been attached.
[mail.tutanota.com-1530517034175.log](https://github.com/tutao/tutanota/files/2154226/mail.tutanota.com-1530517034175.log)

**Comment by charlag** [comment]
```
system-resolve.js:15 WebSocket connection to 'wss://mail.tutanota.com/event/' failed: Error during WebSocket handshake: Unexpected response code: 400
value @ system-resolve.js:15
value @ system-resolve.js:15
(anonymous) @ system-resolve.js:15
EventBusClient.js:139 ws error:  Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
EventBusClient.js:167 ws _close:  CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: "", type: "close", …} Mon Jul 02 2018 09:37:11 GMT+0200 (Central European Summer Time)
```
it seems to be a WebSocket problem. May it be your network conditions and/or a firewall?

**Comment by whawk7** [comment]
Tell you the truth this log comes from Chrome which uses a network with proxy server. Maybe its configuration matters.

**Comment by charlag** [comment]
We think that the problem is in the proxy. Please, try it without proxy and reopen if it persists. Looks like proxy doesn't allow WebSocket connections.
