### ISSUE TITLE
Uncaught TypeError: this.mailList is undefined

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4192]
## One

```
Client: Browser
Type: FREE
Tutanota version: 3.96.6
Timestamp (UTC): Sun, 22 May 2022 21:36:10 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
TypeError
Error message: this.mailList is undefined
Stacktrace:
_moveMails@https://mail.tutanota.com/mail-view-57fc7628.js:1:65732
exec@https://mail.tutanota.com/mail-view-57fc7628.js:1:64723
_handleKeydown@https://mail.tutanota.com/app.js:1:63328
@https://mail.tutanota.com/app.js:1:63094
```
points to this: 

https://github.com/tutao/tutanota/blob/40e94dee2bcec2b63f362da283123e9df1874cc1/src/mail/view/MailView.ts#L414-L419

### Two

```
Client: Browser
Type: FREE
Tutanota version: 3.96.6
Timestamp (UTC): Sun, 22 May 2022 07:00:57 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
TypeError
Error message: this.mailList is undefined
Stacktrace:
exec@https://mail.tutanota.com/mail-view-57fc7628.js:1:64492
_handleKeydown@https://mail.tutanota.com/app.js:1:63328
@https://mail.tutanota.com/app.js:1:63094
```

points to 
https://github.com/tutao/tutanota/blob/40e94dee2bcec2b63f362da283123e9df1874cc1/src/mail/view/MailView.ts#L319-L325

may be related to #4187 

## Test notes
Regressions for mail view:
 - [ ] Selecting multiple mails
 - [ ] Actions with single/multiple mails: moving/deleting/read/unread
 - [ ] Multiselect bar in mobile view
 - [ ] Loading specific email by URL
 - [ ] Shortctuts in Mail view
 - [ ] Holding down key in mail list still throttles route changes

**Comment by charlag** [comment]
Easy workaround: make it nullable like it is and actually check if it's there
Better workaround: do not rely on `uploadURL` that much and use `attrs`

More:

https://github.com/tutao/tutanota/blob/f9c99216b7248960d022c16cc241b85706db82b7/src/app.ts#L184-L196

also has some weird code. As header is the part of basically every view there's really no point of expecting that we will load and render view sooner than we get the header. So we can actually wait for header there, call `updateURL` and only then give view to mithril.
