### ISSUE TITLE
No replies to emails, still cant access account, wtf is going on tutanota?

### ISSUE THREAD

**Issue by xetch** [tutao/tutanota#420]
I've tried emailing from two different email accounts now, tried calling your office number and still nothing for a days now. What's the point in using your service if you're just going to leave people high and dry when they're having issues? Spamming your email or posting unrelated issues on GitHub doesn't usually get anywhere but what options have you left me with?

Password hasn't changed but still can't gain access to a business critical email account and can't get a single response for days is a problem. I hope y'all can at least pull it together for a moment and let me know wtf is going on with my account.

**Comment by armhub** [comment]
You get a reply usually in 24 hours if you are a Premium user.
