### ISSUE TITLE
reify the agreed upon interface naming convention

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4210]
we decided that we want to get rid of any `IFooInterface` and `BarInterfaceImpl` by not using pre- or suffixes but instead use something like 

```
interface CacheStorage {...}
class EphemeralCacheStorage implements CacheStorage {...}
class OfflineCacheStorage implements CacheStorage {...}

interface CredentialsProvider {...} 
class DefaultCredentialsProvider implements CredentialsProvider {...}
class StubbedCredentialsProvider implements CredentialsProvider {...}
```

**Comment by johnbotris** [comment]
# testing

Just some regression testing. Some particular things to check
- [ ] load contact forms
- [ ] do group management stuff (loading, inviting, etc)
