### ISSUE TITLE
Vendor desktop libraries

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4213]
We do vendoring for web part for security reasons (libs directory). We should do the same for desktop-only libraries.

* [x] update-libs scripts needs to be updated to pull desktop deps
* [x] update debug and dist build to use the vendored files
* [x] create list of dependencies to pull
* [x] restrict dist build to only use `@tutao` dependencies from node_modules (node-resolve plugin)
* [ ] review the dependencies

## Test Notes
* [ ] auto-update works for mac, linux, windows
* [ ] offline mode works for mac, linux, windows
* [ ] saving credentials works for mac, linux, windows
* [ ] dev build of the desktop client works

**Comment by kibhub** [comment]
see #5836
