### ISSUE TITLE
remove usages of deprecated KeyboardEvent properties in KeyManager

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4221]
i.e. `which`, `keyCode`

## Test Notes
Test all of these on multiple keyboard types and keyboard layouts
- [ ] Keyboard controls for mail view work as expected
- [ ] Keyboard controls for interacting with a single mail work as expected
- [ ] Keyboard controls for writing a mail work as expected
- [ ] Keyboard controls for contact view work as expected
- [ ] Keyboard controls for calendar view work as expected

Note: ctrl + e exporting contacts even when not in the contacts view was a pre-existing bug that is fixed in a different PR (the upcoming contact lists)

**Comment by charlag** [comment]
I'm not sure if alternatives work everywhere already

**Comment by ganthern** [comment]
I'm pretty sure that this will be a medium refactoring even if everything is supported since key codes seem to be on the way out in general.
