### ISSUE TITLE
Switch from and to dates on search 

### ISSUE THREAD

**Issue by rolojf** [tutao/tutanota#423]
Runing it on firefox https://mail.tutanota.com/ 
Where it says Form date To date, the program really expects the following:
`Form date` should be the older date and it asks to be the later date.
`To date` should be the newer date and the program asks to be the older date.

I think it should be the other way around. Doesn't it?

Regards,

**Comment by charlag** [comment]
Hi! Thanks for reporting.
Some people find it confusing too, we will discuss if we should change this.
