### ISSUE TITLE
Tutanota icon looks pixelated on windows

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4235]
**Screenshots**
![tn1](https://user-images.githubusercontent.com/104761667/170994222-1253471c-fa40-4c63-a14b-fb5c1eaa4dbe.png)

# Test notes
- [ ] On Windows, verify the icon for the application does not look pixelated/aliased in these views:
    - [ ] Desktop
    - [ ] File explorer window views
        - [ ] Large icons
        - [ ] List
        - [ ] Medium-sized icons
    - [ ] Properties (right-click, show properties)
    - [ ] Taskbar

## Regression test
- [ ] Right click the application on the desktop and show properties
    - [ ] Verify the icon colors are correct (should be red/white, not red/black, black/red, etc.)

**Comment by paw-hub** [comment]
I believe this is because the Windows icon lacks a low resolution version of the icon, so it's using nearest scaling.

Generally, a proper .ico file will have versions of the icon for all needed resolutions, but we're using a .png instead which only has one resolution.
