### ISSUE TITLE
trashcan icons in settings/whitelabelaccounts list are the wrong way around

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4243]
the trash can is shown when the account is active and not shown when it's inactive

the setting to switch the status is also the wrong way around.

should probably be the other way around.

# Test notes
- [ ] Log in with an account that has a whitelabel domain and some users
- [ ] Verify active users have an activated status in their settings when selected
- [ ] Verify inactive users have a deactivated status in their settings when selected

**Comment by charlag** [comment]
It was also wrong for whitelabel children in the viewer, I guess it's the same bug

**Comment by paw-hub** [comment]
It seems the issue with whitelabel children is not the trashcan symbol but the status being wrong (should say Deactivated when it says Activated and vice versa).
