### ISSUE TITLE
counter isn't updated when deleting unread emails in trash or spam

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4251]
**Describe the bug**
When you have unread emails in the Trash or Spam folders and delete them the counter isn't updated until you open another message in another folder.

**To Reproduce**
1. Mark mail as unread and move to trash
2. Delete mail from trash without opening it (open trash and Ctrl+click the email)
3. Counter on the trash icon stays at 1

In the case of spam, the counter is updated when you open an email in another folder. But the trash counter isn't reset unless the trash is empty or is emptied afterwards.

Tested on Desktop, Web and mobile.

**Comment by Jlll1** [comment]
This seems like a duplicate of #3729

**Comment by kibhub** [comment]
closing as this is a duplicate of  https://github.com/tutao/tutanota/issues/3729
