### ISSUE TITLE
Calendar events are not being displayed correctly. 

### ISSUE THREAD

**Issue by brshub** [tutao/tutanota#4262]
**Describe the bug**
After update to 3.96.11/12 calendar events are not being displayed properly in the desktop client. They are visible in the mobile app and webmail client.

**To Reproduce**
1. Go to Calendar
2. See error (missing events)

**Expected behavior**
All calendar events should be displayed correctly. 

**Desktop (please complete the following information):**
 - Tutanota v. 3.96.11 and v. 3.96.12

**To Restore Calendar Events**
Set Offline Mode to "deactivated" and logout of the account. Log back in and the events should be displayed correctly.

Some steps given by a user to reproduce it:

- Offline mode was enabled.
- I disabled it, and checked the calendar: no events were shown (not even the one from yesterday that I added)
- I then quit the app and reopened it: all my events were shown
- I then enabled offline mode: all my events were shown
- I then quit the app and reopened it: no events were shown, except those for the default calendar

I repeated the set of the last two steps twice, with the same results each time.
I opened the developer tools to check the console (I have a background in web development), and didn't see any warning or error messages - nothing appeared out of the ordinary.

**Comment by charlag** [comment]
Checked with @ganthern 
 - my theory that the cache range is overwritten is unlikely. Range should only be one of the two states. Also some events should be visible then as it is only one half of one calendar that would be broken
 - we suspect that something might be wrong with groups if there are no calendars displayed whatsoever

**Comment by charlag** [comment]
We still need more info (we added some logging). Also a screenshot would be great.

**Comment by ganthern** [comment]
## Regression Testing

* [ ] existing calendar events are downloaded eagerly and available offline
* [ ] new calendar memberships are downloaded eagerly as well
* [ ] this also works when the client is offline, new items appear and we go online again
