### ISSUE TITLE
Don't process entity event updates for mails when offline timerange is 0

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4283]
some mailboxes receive a large volume of incoming mails, in which case it's often preferable to set the offline timerange to 0, effectively disabling offline mode (at least for mails). However, mail events are still processed, and mails are still being requested by the client even if they aren't to be cached, leading to a large number of unnecessary requests.

We should find a solution that doesn't re-implement all the logic we had for optional offline mode.

**Comment by bedhub** [comment]
not planned
