### ISSUE TITLE
Replace round action buttons

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4292]
We want to change the style of the action buttons so that they are less distracting, which means removing the circle.

**Acceptance criteria**

- Action buttons in nav columns use icon only style
- Action buttons in settings viewer use icon only style
- Action buttons in contact viewer use icon only style
- Icons inside drop downs use icon only style (e.g. folder actions)
- Existing custom theme is applied depending on the buttons location (nav column, list column, view column)
- All existing built-in themes still work for the new design

## Test notes
 - [ ] Editor toolbar is working in event edit dialog
 - [ ] External recipients & password works in event edit dialog
 - [ ] Force update checkbox works in event edit dialog
 - [ ] Whitelabel theme preview works
 - [ ] Aggregated editors work in ContactEditor
 - [ ] Buttons in contact viewer still work
 - [ ] Buttons in multi contact viewer still work
 - [ ] Knowledge base can be expanded/collapsed
 - [ ] Adding/editing/removing entries in knowledge base works
 - [ ] When opening dropdown without search field, the dropdown itself is focused
 - [ ] After opening dropdown up/down keys and tab selection still works
 - [ ] Dropdowns with and without icons have correct paddings
 - [ ] DropdownSelectors still work (e.g. contact list sort)
 - [ ] Multiselection (on mobile) works
 - [ ] Mail editor: recipient fields
 - [ ] Mail editor: attachments, does not focus the subject
 - [ ] Mail editor: editor bar
 - [ ] Mail editor: templates
 - [ ] Mail editor: downloading inline images on right click works
 - [ ] Icon button in table header works and looks ok
 - [ ] Icon buttons in table rows work and look ok
 - [ ] Text fields look okay, small label in text field behaves like before, injections are centered vertically
 - [ ] Buttons in drawer menu work (narrow leftmost column)
 - [ ] Things in the header are centered vertically
 - [ ] Progress icon in mail recipient text field is centered vertically
 - [ ] Contact form request dialog works, files can also be attached
 - [ ] Recover login dialog works
 - [ ] Custom email domain: checking DNS records
 - [ ] Activating/deactivating whitelabel, meta tags, impring & privacy, theme, logo
 - [ ] Desktop settings work
 - [ ] Aliases list works (e.g. in mail settings)
 - [ ] Edit second factors dialog
 - [ ] Global settings buttons
 - [ ] Group viewer buttons
 - [ ] Notifications identifier list
 - [ ] Login settings buttons
 - [ ] Mail settings buttons
 - [ ] Signup, in particular mail address and password fields
 - [ ] Template editor
 - [ ] User viewer buttons
 - [ ] Inviting/accepting calendar invites (not event, group ones)
 - [ ] Payment viewer
 - [ ] Subscription viewer

**Comment by bedhub** [comment]
Some notes when smoke testing on iOS 3.100.2


1. MailViewer: For some emails the shadow of the buttom toolbar is not visible. Not sure for which ones exactly but the this one is an scaled HTML email.
![IMG_6864](https://user-images.githubusercontent.com/8296817/194258402-c311e1be-335e-4423-a96b-7aa279bf828a.png)
2. MailViewer: Expanded state of the sender/recipient stays expanded when switching between emails. I would expect that the sender/recipient details are getting collapsed when selecting a new email.**
3. MailViewer: Indicator to show more available recipients wraps to multiple lines.
![IMG_6865](https://user-images.githubusercontent.com/8296817/194260759-1d6c86f4-52aa-435b-8568-d7d6862ef5b6.png)
4. MailEditor: When writing a new email and click on the expander to enter cc/bcc recipients and press again to collapse it, the button still has a grey background (i think it is the focused state). But this might be confusing as we use the darker grey as "pressed" state.
![focused-state-mail-editor](https://user-images.githubusercontent.com/8296817/194262087-64ba0141-660a-492e-9f10-e76f6e2240f2.png)
6. MailEditor: Formatting buttons are  wrapping up to second line although there is enough space to show another button
![IMG_6869](https://user-images.githubusercontent.com/8296817/194262288-6eb47a77-e9b9-4aef-876f-991ec2cfba85.png)

**Comment by brshub** [comment]
When adding a note to a calendar event the number/bullet listing can be toggled on, but not toggled off when multiple lines are selected. If cursor is left at the end of a single line w/o selecting anything the list can be toggled on and off w/ the buttons.

**Comment by ganthern** [comment]
>     3. When setting a whitelabel custom color the changes are not made and the client remains in light mode with the default red color theme.

I'm pretty sure that's only supposed to happen if you're logged in through the whitelabel domain, which works for me.
