### ISSUE TITLE
Merge button for contacts doesn't appear in search view

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4302]
**Describe the bug**
When you search your contacts and then select two of the results the merge button doesn't appear.

![contact_merge_1](https://user-images.githubusercontent.com/104761667/175024469-a6f197f1-c0c6-44d6-b14a-2929115a9e74.png)

**To Reproduce**
1. Go to Contacts
2. Type-in a search term that would give multiple results
3. Select any two contacts
4. See that merge button missing

**Expected behavior**
When you manually select any two contacts you should be able to merge them.

![contact_merge_2](https://user-images.githubusercontent.com/104761667/175024438-19d7ad0c-6f17-4813-9956-7cfdd93842a2.png)

**Comment by rezbyte** [comment]
I can't seem to reproduce this one. Maybe it's already fixed?

**Comment by kibhub** [comment]
yes it looks like this has been fixed with the updated UI. Closing as irrelevant.
