### ISSUE TITLE
15 Minute events are partially covered by subsequent events

### ISSUE THREAD

**Issue by kib42** [tutao/tutanota#4306]
When you have a 15 minute event (or shorter) and a subsequent one starting directly after it, the first event is covered partially by the latter.
This applies to the day and week view of the calendar.

### Screenshots

![calendar_2](https://user-images.githubusercontent.com/104761667/175246803-d46609d0-7499-4c40-9d8d-462c0d21c250.png)

**Expected behavior**
Such events should either be spaced or displayed adjacent to each other like with overlapping events

**Comment by wrdhub** [comment]
Looking at this now, I am not seeing this issue anymore. They are displayed adjacent like expected, looks like we have resolved this since this was opened.
