### ISSUE TITLE
Credential encryption preference doesn't show up when no credentials were stored

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4307]
This code is not true anymore

https://github.com/tutao/tutanota/blob/5dcf50581d821f345b8a54514c19b9ead30e15cb/src/settings/LoginSettingsViewer.ts#L152-L157

Repro:
 * fresh install
 * log in without saving credentials
 * go to settings -> login
 * see that the option for the "credentials encryption mode" doesn't show up

When credentials were saved before, the option will show up even when all credentials are deleted and then logging in without saving.

Expected:
just show the default setting.

**Comment by johnbotris** [comment]
# Test notes

- [ ] If going to login settings with a device where credential have never been saved, then it will show the device encryption mode selector, set to the default DEVICE_LOCK
- [ ] In the previous case, a help message also shows
- [ ] Selecting a new encryption mode from here will be persisted:
    - select BIOMETRICS
    -  log out
    - log in and save the credentials
    - the device should request your biometrics
- [ ] the help text doesn't show in the login settings if a mode has been selected previously
