### ISSUE TITLE
FileController.saveDataFile() opens file on desktop

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4313]
`saveDataFile()` should not open file (except for iOS where there's no other option)

**Comment by ganthern** [comment]
is not the case anymore since eb8ab3a8ab5e7bd87012f0eea7d576656b68170d

relevant code:
https://github.com/tutao/tutanota/blob/e5825778527fe3bd973dca36968adcc4af5359be/src/file/FileControllerNative.ts#L125-L144
