### ISSUE TITLE
update DOMPurify

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4318]

**Comment by ganthern** [comment]
### Test Notes

* [ ] test with https://www.emailprivacytester.com/
* [ ] re-test private-issues 38
* [ ] inline images are detected in mail viewer
* [ ] FAQ entries and FAQ search results are displayed correctly
* [ ] contact form editor works and is sanitized
* [ ] calendar event editor works and is sanitized
* [ ] notification email editor works and is sanitized

**Comment by vitoreiji** [comment]
> test with https://www.emailprivacytester.com/

Which tests do we expect to fail after allowing to load images?
