### ISSUE TITLE
Incorrect offline login error message for free accounts

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4326]
When trying to login offline with a free account, the error message that is shown is the same as the one shown when trying to edit the offline time range. It doesn't make sense in this context:
![Screenshot from 2022-06-28 10-36-54](https://user-images.githubusercontent.com/22109738/176134150-3faadd79-bf8d-44d8-b109-9ed41aa35afd.png)

it should say something like "You are offline. Signup for a Premium account to enable offline login"

**Comment by ganthern** [comment]
### Test Notes

* [ ] when logging in offline with a free account, we get the new message explaining that offline login is a premium feature
* [ ] when clicking to configure the offline time range (email settings) with a free account, we get the upgrade dialog that also mentions logging in offline.
