### ISSUE TITLE
Error in offline mode self-enabled for the first time (v3.98.4)

### ISSUE THREAD

**Issue by v011** [tutao/tutanota#4332]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Updated to v3.98.4 (offline mode enabled by default), then after connected to my mail box I saw a modal which mentioned a "RangeError".
After "F12" > "Console", here is a more precise error message.
`Error while initializing offline cache storage Error: CBOR decode error: found map but not enough entries (got 5 [no key], expected 19)`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Desktop Environment: GNOME
 - Version: 3.98.4

**Additional context**
Error when connecting to a heavy mail box. No errors when tested with a lighter one.
However, It seems that can send e-mails, navigate from one folder to another, see folders elements and message bodies.

**Comment by charlag** [comment]
Sounds like a race condition, not sure how to reproduce it

**Comment by v011** [comment]
Now, every time I'm logging in, the client shows me this error.

```
Feedback v3.98.4 - Error - UNKNOWN - linux

Client: linux
Type: UNKNOWN
Tutanota version: 3.98.4
Timestamp (UTC): Wed, 29 Jun 2022 10:29:59 GMT
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.4 Chrome/100.0.4896.160 Electron/18.3.0 Safari/537.36
Error
```

**Comment by v011** [comment]
Since I updated to v3.98.12, I deleted the credentials and added them again. Now, it's worse, I've an error modal which is visible only for ~1 second, then the login page refreshes automatically, so I can no longer enter in my mailbox on the desktop app (only when "Store password" is checked). It seems to be an offline mode bug.

**Comment by charlag** [comment]
@v011 any ideas how to reproduce it?
Maybe try to nuke the whole `~/.config/tutanota-desktop` directory

**Comment by v011** [comment]
1. I've emptied all the `~/.config/tutanota-desktop` directory (also deleted the hidden files).

2. Connected + start of synchronisation.

3. Sync stuck at 60% + error message.

4. The first error message :

```
Feedback v3.98.12 - RangeError - PREMIUM - linux

Client: linux
Type: PREMIUM
Tutanota version: 3.98.12
Timestamp (UTC): Thu, 31 Jul 2022 12:12:37 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.12 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
RangeError
```

5. `F12` -> "Console" :

```
error RangeError: The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at Sa (cborg.js:479:19)
    at Array.va (cborg.js:450:10)
    at yr (cborg.js:1261:26)
    at yr (cborg.js:1258:7)
    at yr (cborg.js:1258:7)
    at yr (cborg.js:1258:7)
    at yr (cborg.js:1258:7)
    at lr (cborg.js:1282:3)
    at eC (cborg.js:1287:10) RangeError: The number NaN cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at Sa (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:314239)
    at Array.va (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:313945)
    at yr (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:326214)
    at yr (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:326182)
    at yr (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:326182)
    at yr (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:326182)
    at yr (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:326182)
    at lr (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:326565)
    at eC (file:///tmp/.mount_tutanoaw4Vc7/resources/app.asar/common-34b37497.js:1:13268)
```

6. Also this message on "Console" :

```
error
  Re {name: 'ConnectionError', message: 'Reached timeout of 20000ms  | GET /rest/tutanota/calendarevent/<enc-username>', data: undefined, stack: 'ConnectionError: Reached timeout of 20000ms  | GET…tanoxxxxxx/resources/app.asar/worker.js:12:94758)'}
  data: undefined
  message: "Reached timeout of 20000ms  | GET /rest/tutanota/calendarevent/<enc-username>"
  name: "ConnectionError"
  [[Prototype]]: se
ConnectionError: Reached timeout of 20000ms  | GET /rest/tutanota/calendarevent/<enc-username>
    at u.onabort (file:///tmp/.mount_tutanoxxxxxx/resources/app.asar/worker.js:12:96883)
    at abortFunction (file:///tmp/.mount_tutanoxxxxxx/resources/app.asar/worker.js:12:94758)
```

7. Bellow, a recurrent error :

```
Uncaught EventQueue error! Error: CBOR decode error: found map but not enough entries (got 5 [no key], expected 19)
    at cborg.js:1352:13
    at Or (cborg.js:1384:12)
    at N (cborg.js:1401:19)
    at Bl.deserialize (OfflineStorage.ts:153:24)
    at Bl.get (OfflineStorage.ts:108:25)
    at async ia.processUpdateEvent (EntityRestCache.ts:679:88)
    at async ia.entityEventsReceived (EntityRestCache.ts:614:12)
    at async na.processEventBatch (EventBusClient.ts:640:10)
    at async na.eventQueueCallback (EventBusClient.ts:540:3)
```

---

Because of these errors, I can no longer save drafts, send e-mails, or receive new e-mails.

FYI, my "Inbox" has 99+ unread messages and the used storage is +300MB.

I've also tested with lighter accounts (less messages and used storage), then it seems OK, no error messages.

**Comment by v011** [comment]
Hello, any news on that ? I can't use the desktop app, please help.

**Comment by v011** [comment]
I tried to delete the saved credentials and to add them again. 
Then, I logged in again, with saved credentials enabled, and I went directly
to the "Local data" option (Settings > Email) and set the value to 0 (zero),
so the phrase is now "Keep emails from the last 0 days". Unfortunately, the
local database is still there and is growing. It seems like the option is not
taken into account, maybe because the value is set to zero and not to an
integer greater than zero.

I also tested to set it to 1 (one). Now, I can see my e-mails and my calendar.
It seems better with one, compared to zero, even if an error message is
displayed every time I'm logging in.

**Comment by charlag** [comment]
Cache is cleared upon login, there's no way to completely disable it

**Comment by v011** [comment]
Now, I can't log in. The web Console says the following...

```
failed request GET https://mail.tutanota.com/rest/sys/session/[...]/[...]
401 Unauthorized
```

I really don't understand where the problem is.

It would be really helpful if you could show again the previously removed setting which allows us to enable or disable the offline mode, cause the desktop app is what is use the most !

Does the informations I provided you [~2 weeks ago](https://github.com/tutao/tutanota/issues/4332#issuecomment-1200437036) were helpful ?

**Comment by charlag** [comment]
@v011 do you still get the same error? In different reports you said
1. you log in but you get error
2. you can't log in
3. you re-added credentials (this means you can log in)?

Do I understand correctly that after every login you get a CBOR error now?

**Comment by v011** [comment]
Hello, I described the problems as they heppended. In the beginning (when updated to v3.98.4), I was able de read/send messages, that lasted some weeks. Then, I did another update and it became impossible to log in. I found that if I clean the saved credentials I can use the app a few times until blocked again.

Yes, I always get a `CBOR decode error` and a `401 Unauthorized` (just after CBOR). [details above]

But the first error I saw, after cleaning the credentials, is `RangeError`. [details above]

**Comment by charlag** [comment]
I honestly don't know how to approach this yet.
I think some row get corrupted and we would usually fall back to ephemeral cache but it occurs so late that we don't.
The question is, how do you get a corrupted row? SIGKILL at the wrong moment? I think this is crucial here.

**Comment by v011** [comment]
FYI, this remains an issue, both on desktop and on Android, even with the latest update.

**Comment by charlag** [comment]
I did not see this occur for a long time
