### ISSUE TITLE
desktop app doesn't respect run in background setting

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4337]
**Describe the bug**
when the app is set to run in background, it will not do so and exit completely once the last window closes

**To Reproduce**

reproduced on windows, no repro for linux (didn't work) or mac (didn't try) yet :
1. start 3.98.4
2. see that there's no tray icon
3. check settings, set "run in background" to true
4. See no tray icon, still
5. optional: open a new window

**Expected behavior**
with the setting enabled, tutanota should stay in the background

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**

* the config writes get to the conf.json file just fine, it's just not used for some reason.
* ~~this may be related to https://github.com/tutao/tutanota/issues/4336~~ is not related

## Test notes
 - [ ] Test that run in background is respected on windows and linux
   - [ ] not set win
   - [ ] set win
   - [ ] not set lin
   - [ ] set lin

**Comment by nif-tutao** [comment]
Tested on Windows 10 with client v. 3.98.4:
the tray icon is not displayed even with background mode enabled, yet background itself works just fine - notifications are shown.

**Comment by bingoxo** [comment]
issue still there with 3.98.12

**Comment by jernejp21** [comment]
Can you please fix tray icon soon?
