### ISSUE TITLE
Attachment download is broken with blob store enabled

### ISSUE THREAD

**Issue by johnbotris** [tutao/tutanota#4338]
Probably from the IPC refactoring

We create a temporary decrypted file before copying it to the downloads folder. The file is created in `AndroidFileFacade.joinFiles`, which joins the decrypted blob and returns the path to the new decrypted temporary file

https://github.com/tutao/tutanota/blob/42e905c6d6b2cd902061223f9c6efe4a5d8ded1b/app-android/app/src/main/java/de/tutao/tutanota/AndroidFileFacade.kt#L59

however, the call `contentResolver.openInputStream(fileUri)` in `AndroidFileFacade.addFilesToDownloadsMediaStore` expects a file uri, not just a plain path string, i.e. the output of `joinFiles` looks like `/data/user/0/de.tutao.tutanota/...` where it should be `file:///data/user/0/de/tutao.tutanota/...`. 

The call fails with:
> java.io.FileNotFoundException: No content provider: /data/user/0/de.tutao.tutanota.debug/...

This is not a problem when the blob store is not enabled, because our temporary file path is coming from `AndroidNativeCryptoFacade.aesDecryptFile`, which does return an actual file uri.

the simple fix is to return `output.toUri().toString()` from `joinFiles`.

Unfortunately `joinFiles` is being called directly by the ipc so it can't return a Uri directly which would help to avoid this. Maybe there's something we can improve there?

**Comment by ganthern** [comment]
Test notes plz

**Comment by johnbotris** [comment]
# Test notes
- [ ] enable blob store on an account an send an email with an attachment to yourself. Check that it is possible to download and to open the attachment on android
