### ISSUE TITLE
Inline images stored withing the blob store are not displayed

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4357]
**Bug in mobile app**

**Describe the bug**
When opening an email with inline attachments that have been uploaded to the blob store the inline images are not displayed.

**To Reproduce**
1. Send inline attachment from account that has blob store enabled.
2. Open the received email on web/desktop client, verify that inline image is displayed.
3. Open same email on iOS device -> inline image is not displayed.

**Expected behavior**
Inline image should be displayed.

**Version**
iOS app 3.98.4

**Additional context**
In addition to this one https://github.com/tutao/tutanota/issues/4358 this bug only addresses inline images that are stored within the blob store. 
The error already occurs with the current release 3.98.4

Inline images must be transferred to the web view in order to add them to the dom. Previously the solution was that inline images were downloaded using the web view and not loaded from the native to not transport the data using the native bridge. Maybe we did not considered the case when integrating blobs or something went wrong when redoing ipc.

**Comment by ganthern** [comment]
@charlag and I couldn't reproduce it on production. The iOS app currently loads blob inline images through the web app (not native)

**Comment by bedhub** [comment]
I also cannot reproduce this anymore.
