### ISSUE TITLE
Download action from mail editor triggers open action

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4359]
**Describe the bug**
When downloading an attachment from a saved draft within the mail editor the attachment is downloaded to the temporary directory and opened immediately.

**To Reproduce**

1. Open new email and add an attachment
2. Click on the attachment and select "Download", should ask for download location or store the attachment in the default download directory.
3. Save the draft, so that the attachment is uploaded to the server.
4. Open the draft again, click on the attachment and select "Download" -> Application does not ask for download location. Instead it opens the attachment

**Expected behavior**
Downloading a file should ask for download location or store the file in the default download folder.

**Version**
- Desktop 3.98.6

## Test notes
* [ ] repro from above doesn't lead to unexpected behaviour
* [ ] regression web: open & download work as expected on an unsaved draft and on a saved draft
* [ ] regression mobile: open & download work as expected on an unsaved draft and on a saved draft

**Comment by charlag** [comment]
A bit of a weird behavior: if I cancel saving the file from draft it will say "failed to open attachment" which is not exactly correct. I think we can fix it later, separate issue mb?

**Comment by ganthern** [comment]
> A bit of a weird behavior: if I cancel saving the file from draft it will say "failed to open attachment" which is not exactly correct. I think we can fix it later, separate issue mb?

https://github.com/tutao/tutanota/issues/4370

**Comment by charlag** [comment]
On Android it opens file when it's unsaved draft and saved it to downloads when it's saved

**Comment by ganthern** [comment]
> On Android it opens file when it's unsaved draft and saved it to downloads when it's saved

https://github.com/tutao/tutanota/issues/4371
