### ISSUE TITLE
Cannot send logs files from an account that has blob store enabled

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4361]
**Describe the bug**
When sending log files from an iOS device with an account that has blob store enabled the offline error message appears. ("Could not reach server, looks like you are offline. Please try again later.")

**To Reproduce**
1. Log in on an iOS device with an account that has blob store enabled.
2. Go to Settings->About and try to send the log files to yourself
3. See offline error message 

**Expected behavior**
Sending the email is possible.

**Smartphone (please complete the following information):**
 - Device: iOS
 - Tutanota Version 3.86.4

### Test Notes
* [ ] attaching and sending logs from the about dialog works
* [ ] they can be opened from another mailbox

**Comment by charlag** [comment]
I could not reproduce with 10a26bfb45a064b93f4fc044a0254925037b88f1, I think it might be fixed?

**Comment by ganthern** [comment]
If working on this, try the repro with test and prod systems, since it seems inconsistent.

**Comment by paw-hub** [comment]
I'm able to reproduce this 100% consistently on my personal iPad.
<img width="1194" alt="bloblognotworking" src="https://user-images.githubusercontent.com/104824185/183437807-681290eb-e7b8-4312-8786-815569d69085.png">
