### ISSUE TITLE
tutanota freeze

### ISSUE THREAD

**Issue by JohanvdS** [tutao/tutanota#4408]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Bug in mobile app**
Yes vollaphone

**Describe the bug**
When I want to reply a mail it freeze. It start already by reply and waiting few seconds. If I want to type it hangs and even there appear a message that tutanota hangs and stopped the app.

**To Reproduce**
1. Go to '.mail..'
2. Click on 'reply....'
4. See error waiting close app

**Expected behavior**
When I want to reply a mail it freeze. It start already by reply and waiting few seconds. If I want to type it hangs and even there appear a message that tutanota hangs and stopped the app.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]  vollaphone 
 - OS: [e.g. iOS8.1] volla

**Additional context**

**Comment by JohanvdS** [comment]
Hi, 
There as an update this morning in f-droid and it seems to work again. using volla-phone It could be specific because of a support it loaded a lot of request and aswers from  deeper.network help function. It was only on a phone and not on the ubuntu desktop.
I will keep an eye on it if it is coming back again. 

thanks for reply

Johan


-- 
 Verzonden met Tutanota, de veilige en advertentievrije postbus. 



1 aug. 2022 14:13 van ***@***.***:

**Comment by ganthern** [comment]
I'm closing this since it was fixed with an app update.
