### ISSUE TITLE
Support FIDO U2F security key in Android app

### ISSUE THREAD

**Issue by EliasGabrielsson** [tutao/tutanota#443]
As a user i want to be able to use (login and register) my FIDO U2F security key as a second factor in the mobile android app so that i can use my key on all of my devices.

### AC
* Allow setting up a security key in Settings > Login 
* When security key is registered in within the app it is always registered for https://mail.tutanota.com/ 
* Authentication with security key as second factor in desktop client/mobile app is allowed
* Authentication with the same key in web client on https://mail.tutanota.com/ is allowed
* Authentication with key that has been registered on whitelabel domain is allowed

### Notes
We first need to clarify which technical approach is the best to have a uniform business logic implementation for all mobile devices.
https://github.com/tutao/tutanota/issues/4722

### Test Notes
- [ ]  Keys that have been previous registered still work, specifically for tutanota.com
- [ ]  Keys that have been previous registered still work, specifically for whitelabel domain
- [ ]  Add a key in Settings > Login
- [ ] Check that when adding new key, the user can cancel
- [ ] Check that new key works on login in android app
- [ ] Check that new key works on login for desktop and web apps
- [ ] Check that when authenticating, the user can cancel
- [ ] Check that using wrong key will not work on login

**Comment by charlag** [comment]
we will add support with one of the next releases

**Comment by lauritzt** [comment]
Adding on to this, an option to require that the security key is presented every time the app is opened (along the lines of the PIN/fingerprint option) would be nice. It would provide better protection than a fingerprint (which can be legally/physically compelled) and than a PIN (which is static).

**Comment by tormoon91** [comment]
> Adding on to this, an option to require that the security key is presented every time the app is opened (along the lines of the PIN/fingerprint option) would be nice. It would provide better protection than a fingerprint (which can be legally/physically compelled) and than a PIN (which is static).

not necessarily

Bitwarden allows you to utilize a yubikey and it only asks you to present it on your first login.
After that when you open the app, all you use is the password.

This could be potentially configurable.

**Comment by andy-lawson** [comment]
I would also like to see U2F implemented for the Android client.

**Comment by Mhowser** [comment]
Any progress on this?

**Comment by Vrbikk** [comment]
bought YubiKey with NFC, works with web UI but not directly with android app, please add this feature

**Comment by 61Mv24** [comment]
Also bought YubiKey with NFC, was super excited to use it on my Android with Tutanota. 
No joy, I get a Tutanota App message to "Accept from another device". So I have to login with the YubiKey on my computer, then Tutanota prompts me to accept the Android login into the app.

This model is broken. Either you have no app functionality on the GO, or you are forced to downgrade from a YubiKey to use the app.

This feature is becoming mainstream quickly, already adopted by Google to login in Android. Please add!

**Comment by bedhub** [comment]
I updated this description for the desktop client in this issue: #2178. We want to try the same approach for the android app.

**Comment by jrm523** [comment]
I was changing over my email to Tutanota but was shocked when I could not use my yubikey on my android app. I am glad to see this is being worked on because I believe it is vital to any secure platform.

**Comment by charlag** [comment]
I've found out that that Webauthn does *not* work in Android WebView which is bad news for our current impl for WebDialog. We will probably have to use some other communication channel.

**Comment by ganthern** [comment]
On Android, testing this in the app leaves a bunch of lingering firefox activities showing the "Waiting for second factor" screen, which was somewhat suprising. We'll track it in #4828, maybe we'll get to it soon-ish.
