### ISSUE TITLE
Uncaught PayloadTooLargeError in alarmservice

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4457]
When importing large calendars, a PayloadTooLarge Exception can be thrown. It's currently not handled in the client.

```
Feedback v3.98.17 - PayloadTooLargeError - PREMIUM - darwin


Client: darwin
Type: PREMIUM
Tutanota version: 3.98.17
Timestamp (UTC): Thu, 04 Aug 2022 10:02:14 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.98.17 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
PayloadTooLargeError
Error message: request body is too large. Path: /rest/sys/alarmservice, Method: POST, Body length: 1193538
```

One offending calendar (it's an .ics file): [big.txt](https://github.com/tutao/tutanota/files/9259010/big.txt)

## Test Notes
- [ ] Importing the above offending calendar (on an account with many notification devices) shows a message about alarms not being set up properly.
    - [ ] Events are still put into the calendar.
- [ ] Importing the above offending calendar (on an account withOUT many notification devices) does not show any message and events are imported as expected.
- [ ] Importing a smaller calendar (on an account with many notification devices) does not show any message and events are imported as expected.

**Comment by vitoreiji** [comment]
> on an account with many notification devices

How many notification devices are *many*?

**Comment by wrdhub** [comment]
> How many notification devices are _many_?

Great question! I was testing on an account with over 60. So that many?
