### ISSUE TITLE
Trash folder is not automatically emptied

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4477]
**Describe the bug**
Email in the Trash folder are not automatically deleted after 30 days.

**Comment by charlag** [comment]
It is run periodically

**Comment by pslyman** [comment]
I've used Tutanota for two years and this hasn't ever worked. I've used it across 4 Android phones, Windows, and Mac. 9 months ago I cleared my trash folder to test this, and nothing has auto deleted after 30 days or at any point up to now. My partner uses Tutanota as well and emails in trash don't delete after 30 days.
