### ISSUE TITLE
Push Notification Service continously viewable

### ISSUE THREAD

**Issue by janos-szenfner** [tutao/tutanota#449]
The Tutanota notification service is always viewable as I got new emails. 
The Tutanota icon always viewable on the notification bar. Not able to hide it.

Please hide it, because it is very annoying.

This was in the beta Android client.

--
Client: android app
Tutanota version: 3.35.4
User agent:
Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36

**Comment by charlag** [comment]
Hi! Thanks for reporting.
We're working on a solution for this. Is your Android version 7.0 or it is Oreo? We only experienced "permanent icon" problem with Oreo.

**Comment by janos-szenfner** [comment]
I have Android version 7.0. MIUI version 9.6.1.0 stable.
I have that permanent icon.

Thanks
