### ISSUE TITLE
Enable search functionality in Tutanota (not just the UI for it)

### ISSUE THREAD

**Issue by andreasmjg** [tutao/tutanota#4497]
Hi, 

Is it just me or is the search function completely useless? I've tried to tick that email download is enabled, I've tried to search for different terms, change date ranges, even folders to search in. 

The search function NEVER finds anything for me. It's completely and utterly useless. Same on Android as on the laptop app.

It's ALWAYS faster for me to scroll through my emails, even if the email is months old, than to try to use the search function. 

The UI is there and looks good, but the functionality is not there. 

Here's a wish for adding search functionality in Tutanota! 

Thanks
Andreas

**Comment by charlag** [comment]
There's a search, you can search for full words, please be more specific when something doesn't work for you

**Comment by ganthern** [comment]
> please be more specific when something doesn't work for you

To elaborate on this, It would help us greatly to accept this as a bug to work on if you could show us an example with 
* exact search terms
* how/where you're entering them
* what e-mail you would expect to be found by that search

screenshots also help, this is not something that's generally a problem for people.
