### ISSUE TITLE
improve autofill

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4499]
**Describe the bug**
When you try to log in using the Android app, the phone does not prompt you to use auto-fill with Bitwarden.

**Details**
 - Android
 - Tutanota Version > 3.98.18

## Test Notes
* [ ] clone the following repository to your machine: https://github.com/android/input-samples and install the AutofillFramework/afservice on some android test device
* [ ] open the newly installed app and follow the instructions in the app to set it as the default autofill service -> select "Basic Autofill Service"
* [ ] now open the Tutanota app and go to the login page
* [ ] click in either mail address or password field and check that autofill suggestions are shown
* [ ] login to some account and go to change password, check that suggestions are shown for the current password field and select one suggestion
* [ ] view the inserted password in "Set password" and make sure it's called something like "...new-password"
### Regressions
* [ ] login to some account
* [ ] go to settings
* [ ] click on show recovery code
* [ ] make sure that there are no password suggestions for the password field

**Comment by jomapp** [comment]
FYI: Apparently the "draw-over method" (and in general any accessibility service)  is massively slowing down the android system webview. Tested and verified with tutanota version v3.105.4.
https://bugs.chromium.org/p/chromium/issues/detail?id=1289741

**Comment by nokhub** [comment]
Thanks, good to know. Fortunately, Google's autofill service and also the one from Lastpass for example work without the draw-over-method 👍

**Comment by ganthern** [comment]
I'm going to close this since we did everything we can atm to make it easier for autofill to work correctly.
