### ISSUE TITLE
Sending the last draft redirects to a page with no navigation buttons

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4506]
**Describe the bug**
If you have one draft email and you send it, the app redirects you to an empty page with no possibility to navigate away.

**To Reproduce**
1. Have one draft message
2. Open said message
3. Send

**Expected behavior**
The user should be redirected back to the drafts folder

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - Version 3.98.21

**Screenshots**
![drafts](https://user-images.githubusercontent.com/104761667/184876087-636d201a-0f23-45d2-bcec-a42b5a45beec.png)

**Comment by rezbyte** [comment]
I cannot reproduce this on `v220.240321.0`.
