### ISSUE TITLE
Re-adding an external guest for a calendar event does not restore password field

### ISSUE THREAD

**Issue by yopfox** [tutao/tutanota#4516]
**Describe the bug**
When adding an external guest to an event, a field appears to input the password for that guest. Removing the guest from the event also removes the password-field again. However, upon adding the same guest again, the password field does not appear nor does the button to toggle whether passwords are to be used or not.

**To Reproduce**
1. Go to the calendar
2. Select any day to plan an event
3. Click on the "guests" dropdown and enter a guest with an external address
4. Observe that the password field and confidential button is shown
5. Remove the guest
6. Enter the exact same guest with the external address again
7. Observe that the password field and confidential button do not show up

**Expected behavior**
When re-adding the guest, the password field for that guest should show up again, as well as the confidential button.

**Additional context**
The rendering of the field and button can be forced by changing the attendance status of the organizer or simply adding another external guest.

**Comment by nif-tutao** [comment]
related to #578

**Comment by nif-tutao** [comment]
duplicate of #4520
