### ISSUE TITLE
Audit log is not available for free accounts

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4539]
The Audit Log is not shown for free account regardless of the client.

**Steps to reproduce**

1. Log in to a free account
2. Go to Settings > Global settings
3. See Audit log missing

## Test notes
- [ ] Log into a free account
- [ ] Go to global settings
- [ ] Check that there is an audit log
- [ ] Change the user's password
- [ ] Go back and verify that the audit log reflects this change
- [ ] the global settings for a the account don't show the "enforce password change" setting

## Regressions
- [ ] the global settings for a premium account (global admin) show a functional audit log
- [ ] the global settings for a premium account (global admin) show the "enforce password change" setting

**Comment by armhub** [comment]
If I am not mistaken this code change also displays the password reset option for Free accounts. I would not show it since it only makes sense for accounts with multiple users.
