### ISSUE TITLE
github files and website files should have the same checksums

### ISSUE THREAD

**Issue by pirate486743186** [tutao/tutanota#4541]
**Describe the bug**

The github and website files are not exactly the same. They have different checksums.

**To Reproduce**

Try to use the checksum from github to the file from the website.

**Expected behavior**

They should have been the same. That creates unnecessary confusion.

**Desktop (please complete the following information):**
 -  Linux
 -  3.98.24

**Additional context**
This is about the linux appimage. Probably the same issue exist with all the files.

**Comment by charlag** [comment]
They do, we didn't release the desktop client yet
