### ISSUE TITLE
Android notification completely useless 

### ISSUE THREAD

**Issue by ballo** [tutao/tutanota#4542]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Every single Android app that notifies a user of a change provides information so the user can determine if something needs tending to. Tutanota, on the other hand, is the guy driving down the road with his emergency blinkers on for no reason whatsoever. Instead of notifying the user what email has been received, tutanota just assumes every email received must be worth opening the app over. 99.9% of the time, it isn't, so the app is just useless as a result.

**To Reproduce**

**Expected behavior**
Useful notifications.

**Screenshots**

Sure. If the attached screenshot doesn't make the problem obvious, nothing will I guess.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] s8
 - OS: [e.g. iOS8.1] 9
 - Version [e.g. 22] 3.98.20
![Screenshot_20220826-112109_Brave](https://user-images.githubusercontent.com/631311/186958912-8644971a-fece-47fd-8219-988dfcf60dc5.jpg)

**Additional context**

**Comment by charlag** [comment]
Related to #557 but for Android

**Comment by ozturkberkay** [comment]
Are there any plans for implementing this in the foreseeable future?

**Comment by Nyxiad** [comment]
I would also like to have this fixed. I figured that this is a feature meant to preserve privacy but it would be nice to have an option to disable this.

**Comment by wmww** [comment]
ProtonMail provides archive/trash/reply buttons in the notification, which is extremely helpful for keeping the inbox clear. I want to be able to quickly identify and delete uninteresting mail without opening the app (which dismisses notifications for more important emails). This has been one of my biggest pain point when switching from proton.

**Comment by odannis** [comment]
I have the same comment for the linux desktop application!

**Comment by wrdhub** [comment]
We have added more information options (sender and/or subject) and actions (mark read, delete).
https://github.com/tutao/tutanota/issues/6579
https://github.com/tutao/tutanota/issues/7157

**Comment by ballo** [comment]
What's weird is for a time the Android app notifications were showing the email subject and now they aren't, again. They un-fixed the bug 😞

**Comment by charlag** [comment]
check your notification settings in-app

**Comment by ballo** [comment]
Sometimes it has info sometimes the notification just says you have an email.
