### ISSUE TITLE
Can't see reminders when editing calendar events

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4544]
**Description**
When editing a calendar event which has a reminder, the alarm field displays "None" until you tap on it. Then you would see the previously set  reminder and a new one is added.

**To Reproduce**
1. Create a calendar entry and set a reminder
2. Click save
3. Edit the calendar event
4. See "None" besides reminder

 - Android
 - Tutanota 3.98.20 and 3.98.24

**Comment by nokhub** [comment]
### Test notes
* [ ] login to the android app
* [ ] create a calendar event with any reminder
* [ ] close the app
* [ ] start the app again
* [ ] login to the same account
* [ ] click on edit the calendar event
* [ ] check that the selected reminder will immediately show up



![Image](https://user-images.githubusercontent.com/115003415/204852500-5436d94d-9241-4167-b698-8dbaa6afc6b4.png)
