### ISSUE TITLE
offline login on android doesn't show cached emails

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4546]
Doing offline login on android shows an empty mail list expect for unread emails. Previously cached emails are not shown.

However, any unread email that you open will appear when you do offline log in. But marking emails as unread doesn't have the same effect.

**Steps**

1. Have some (new) unread emails
2. open some of them to be cached
3. have some older read emails
4. open these older emails to be cached
5. go offline
6. do offline log in
7. see error

**Comment by charlag** [comment]
the issue was about the cached range
