### ISSUE TITLE
Desktop app won't automatically update

### ISSUE THREAD

**Issue by utaxiu** [tutao/tutanota#4547]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
After opening Tutanota and receiving infomation about new update it won't update and offers to report an error.

**To Reproduce**
Click on notification that informs about new update.

OR

Open settings and click on "Computer" and down on button "Install now"

**Expected behavior**
I would expect it to update as usual.

**Desktop (please complete the following information):**
 - OS: Fedora 36, 5.18.19-200.fc36.x86_64
 - Desktop Environment & Window Manager: Xfce 4.16 / Xfwm4
 - Version: v3.98.20

**Additional context**
[cli_log.txt](https://github.com/tutao/tutanota/files/9453266/cli_log.txt)

**Comment by charlag** [comment]
>  Error: Error: EACCES: permission denied, unlink '/usr/local/bin/tutanota-desktop-linux.AppImage'
