### ISSUE TITLE
Cannot login into android app

### ISSUE THREAD

**Issue by hertzschi** [tutao/tutanota#4553]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Cannot login, always goes back to login screen

**To Reproduce**
1. username and password
2. Click on login
3. again in login screen
Feedback v3.98.24 - SecurityError - UNKNOWN - android     Client: android  Type: UNKNOWN  Tutanota version: 3.98.24  Timestamp (UTC): Sun, 04 Sep 2022 08:41:43 GMT  User agent: Mozilla/5.0 (Linux; Android 7.1.2; SAMSUNG SM-G960U Build/NJH47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.78 Mobile Safari/537.36 SecurityError  Error message: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS. Stacktrace:  Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.     at ca.socketFactory (https://assets.tutanota.com/worker.js:17:9552)     at ca.connect (https://assets.tutanota.com/worker.js:1:9481)     at xu.initSession (https://assets.tutanota.com/worker.js:12:14172)     at async xu.createSession (https://assets.tutanota.com/worker.js:12:8925). 

**Expected behavior**
Login functioning.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charlag** [comment]
Hi, thanks for the report.
Could you please try update your WebView? It seems like it's still 95 which is pretty old

**Comment by nutpantz** [comment]
Where can someone find a good clean webview that is safe and google free. Google has a long long history of using it's apps to report gone on users activities.  Depending on Google feels wrong on a privacy and security mail app

**Comment by hertzschi** [comment]
Hi, thanks for the hint with the webview.
After some tries I managed to get bromite webview working.
I had to decompile framework-res.apk because webview manager magisk module did not work for me. Modify config_webview_packages.xml and recompile.

After modifications I put the apk file not directly to system/framework but put it in a magisk module foler e.g. mixplorer and created the framework folder under system. I have no knowledge in creating magisk modules so this was the easiest way, because mixplorer is always the first app on a new phone and never gets uninstalled.
Wipe dalvik, and now I have always uptodate bromite webview:}

Here are the strings that have to be added to the file config_webview_packages.xml in res/xml path:

<webviewprovider description="Bromite WebView" packageName="org.bromite.webview" availableByDefault="true">
		<signature>MIIDbTCCAlWgAwIBAgIEHcsmjjANBgkqhkiG9w0BAQsFADBmMQswCQYDVQQGEwJERTEQMA4GA1UECBMHVW5rbm93bjEPMA0GA1UEBxMGQmVybGluMRAwDgYDVQQKEwdCcm9taXRlMRAwDgYDVQQLEwdCcm9taXRlMRAwDgYDVQQDEwdjc2FnYW41MCAXDTE4MDExOTA3MjE1N1oYDzIwNjgwMTA3MDcyMTU3WjBmMQswCQYDVQQGEwJERTEQMA4GA1UECBMHVW5rbm93bjEPMA0GA1UEBxMGQmVybGluMRAwDgYDVQQKEwdCcm9taXRlMRAwDgYDVQQLEwdCcm9taXRlMRAwDgYDVQQDEwdjc2FnYW41MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtakjGj0eTavbBB2vWXj8KBixWn4zgXAKc+yGFu3SLEGF1VB5aJWwcMHxVI55yH/8M2eNnJP0BkSidfKgPVcm1sk/GrNEs9uk5sWod9byO5M5QWQmGP2REeTd6J0BVVVaMp2MZnqeR3Su3pwFzrSwTqIGyf8dkPSEz7ifj792+EeRNrov4oRQK7lIfqInzwc4d34wU069Lrw6m7J7HM0KbRYISsWMiYj025Qg+dTrtdWt7jbdcj7htW0eYyJoLd90+s43RWnOpENmWpcWv1EVPxUD4mCdV9idYwoHRIESpSu9IWvqDZp1VoRc43nLgsNfNBwmYdTkIaPiz1m7TBcr7QIDAQABoyEwHzAdBgNVHQ4EFgQUuWoGd7W7wMyQ1pOdjiMv10YHTR0wDQYJKoZIhvcNAQELBQADggEBAA7iw6eKz+T8HIpKDoDcX1Ywjn9JUzuCFu20LnsLzreO/Pog1xErYjdLAS7LTZokfbAnitBskO9QhV9BYkDiM0Qr5v2/HsJTtxa1mz9ywCcI36jblMyuXFj8tuwQI9/t9i+Fc3+bOFBV3t7djPo9qX1dIK0lZ6s8HcIhaCNdqm65fH+nWhC/H9djqC6qOtrkTiACKEcHQ4a/5dfROU0q0M4bS4YuiaAQWgjiGbik4LrZ8wZX1aqJCLt0Hs7MzXyyf0cRSO11FIOViHwzh6WTZGufq2J3YBFXPond8kLxkKL3LNezbi5yTcecxsbKQ6OS46CnIKcy/M8asSreLpoCDvw=</signature>
</webviewprovider>

**Comment by nutpantz** [comment]
Now if we can find a developer who can make this a project that's always compatible and always available for users
