### ISSUE TITLE
DEL shortcut doesn't work in web app (Mac)

### ISSUE THREAD

**Issue by ji0n** [tutao/tutanota#4563]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I am trying to use the DELETE key on my macbook pro 2021 keyboard to delete a mail in the MailView but can't do so. Or maybe I missed something obvious....

**To Reproduce**
1. Select Mail in List
2. Tap on Delete key on keyboard
3. Nothing happens

**Expected behavior**
Mail should be deleted on keyboard. 

**Desktop (please complete the following information):**
 - OS: Mac OSX 12.5
 - Browser: I tried newest version of Chrome and Firefox

**Smartphone (please complete the following information):**

**Additional context**
Maybe Mac doesn't register the key code 46 properly? Maybe it should be Keys.DELETE or Keys.BACKSPACE. I'm not sure. 
https://github.com/tutao/tutanota/blob/master/src/api/common/TutanotaConstants.ts#L588

## Test Notes
- [ ] Trying to delete an email using ```BACKSPACE``` or ```DEL``` works
- [ ] Trying to delete a batch of emails using ```BACKSPACE``` or ```DEL``` works
- [ ] Trying to delete a contact using ```BACKSPACE``` or ```DEL``` works
- [ ] Trying to delete a batch of contacts using ```BACKSPACE``` or ```DEL``` works
- [ ] using backspace when editing any text doesn't trigger anything to be deleted except the selected text / last character

**Comment by RadiantPunch** [comment]
This was an issue I brought up in a support email. Is it possible to get this addressed soon?

**Comment by kibhub** [comment]
depending on the keyboard you are using, you might be pressing the Backspace key instead of delete. If both are on the same key, you might need to press fn+backspace to get delete.

**Comment by charlag** [comment]
We should anyway add another shortcut for deleting mails

**Comment by wrdhub** [comment]
Since some laptop keyboards don't have a delete key, we have decided to add backspace and another shortcut for deleting emails. (This will be implemented in the future, not sure when yet.)
