### ISSUE TITLE
Can't redeem gift cards in Safari 

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4564]
**Description**
Opening a valid gift card URL in Safari displays the message "This gift card cannot be used".

**Screenshots**
![image](https://user-images.githubusercontent.com/104761667/189077702-88e17a32-a4fa-43e0-83c3-e0994ec4a40d.png)

**Details**
 - macOS 12
 - Desktop Safari 15.6.1 and Safari on iOS/iPadOS 15.6.1
 - Tutanota v3.98.24 and v3.100.0

## Test notes
Most of them should be tested with Service Worker active

 - [ ] Redeeming gift cards is possible
 - [ ] Secure external mails work
 - [ ] Logout in secure external mailbox works and shows the login page
 - [ ] Deep linking still works (`?r=` query parameter)

**Comment by charlag** [comment]
I've done some testing and it seems like it's an intersection of our odd code and odd Safari behavior.

We explicitly remove hashes in Service Worker code:

https://github.com/tutao/tutanota/blob/c4b242c73b0432a8dc67b5d122a2a22b9c480e44/src/serviceworker/sw.ts#L150-L157

which was done to fix #750 76936fdc477df957c03c9b815000ef2628e1009b

I doubt that we should actually remove the hash
