### ISSUE TITLE
Unable to reply from catch-all address

### ISSUE THREAD

**Issue by KazimirPodolski** [tutao/tutanota#4566]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
It seems it's impossible to reply from address on catch-all custom domain, only from main sender address.

**To Reproduce**
1. Configure custom domain _mydomain.com_ with Catch All set.
2. Receive an email to address _something@mydomain.com_.
3. Click reply to the email.
4. The address which received the email is missing in the Sender dropdown. Only the pre-configured senders are available.

**Expected behavior**
The address which received the email is available (and set by default). I believe this is the most intuitive and obvious way to do this.

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser chrome
 - Version 104

**Additional context**
I velieve it makes the whole feature almost useless.

**Comment by vitoreiji** [comment]
You can only send emails from your email address or one of your explicit aliases.

**Comment by dmarcoux** [comment]
It's a shame that Tutanota isn't considering implementing this. It would be a great UX improvement to anyone relying on a catch-all address. In the end, users end up doing the same when wanting to reply, it takes a few more clicks though.

**Comment by KazimirPodolski** [comment]
I went to Fastmail because of this. Their catch-all just works.

**Comment by KazimirPodolski** [comment]
This and the linked issue #5584 tells me NOT sticking with Tutanota was 100% right.

![image](https://github.com/tutao/tutanota/assets/6647438/d4828bf5-1650-4685-b761-428cc079fb37)
