### ISSUE TITLE
Enable mail body compression

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#4573]
We just noticed that mail body compression is not enabled for internal mails, while it is for mails from external.

We should enable compression of internally sent mails.

## Test notes
 - [ ] Can send internal emails, they can be read
 - [ ] Very small ones too
 - [ ] And very big ones too
 - [ ] Can send external email, they can be read
 - [ ] Very small ones too
 - [ ] And very big ones too
 - [ ] Regression test: inline images
 - [ ] Regression test: body size limit

**Comment by slandden** [comment]
What is the compression algorithm? I have a professional relationship with Yann Collet, and zstd is truly a special algorithm (although I am not promoting it, only curious).
