### ISSUE TITLE
End Time Scroll Bar isn't Visible on "New Event" View

### ISSUE THREAD

**Issue by bobmatyas** [tutao/tutanota#4593]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

When adding an event, the end time can't be selected using a scroll bar. This works for the start time on events.

**To Reproduce**
1. Go to Calendar
2. Click on 'New Event'
3. Try to adjust the end time for an event.
4. Observe that event scroll bar is either not displaying or hidden by scroll bar for entire window

**Expected behavior**

I should be able to select an end time for an event.

**Screenshots**
![tuta-screen](https://user-images.githubusercontent.com/45246438/191636658-72af1ed7-bfda-4669-8f55-56411854362c.jpeg)

**Desktop (please complete the following information):**
 - OS: macOs
 - Version: 3.100.3

**Comment by wrdhub** [comment]
I have just tested variety of devices and I am not seeing this issue anymore. The spacing looks a lot better now than in the screenshots, so it looks likes the issue has been solved in the time since this was originally created.
