### ISSUE TITLE
Registration dropouts usage tests timings

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4594]
As an operator, I want to see the times between two registration steps so that i can identify were users are spending the most time on during the signup process.

### Acceptance Criteria
- The time between pings is measured by the client
- Each ping contains the time in seconds since the last ping (except the first one)
- **to decide** The tests identifiers are changed to the new ones in the client code 
- *OR* **to decide** The tests are created in the client code alongside the old versions

### Notes
- We are going to have to recreate the tests for this, so choose new identifiers, e.g., `signup.free.timed` and `signup.paid.timed` 
- We only get the times for successful test and cannot measure the last step when the users decides to dropout.

### Tasks
- [ ] ...

**Comment by bedhub** [comment]
we will just measure times for credit card signup
