### ISSUE TITLE
iOS app does not support two factor authentication

### ISSUE THREAD

**Issue by z5Q46L6bSY1W** [tutao/tutanota#460]
The Tutanota iOS app does not support accounts with two factor authentication. When trying to login, it displays "You have enabled second factor authentication, so login in this old client is not supported any more."

**Comment by charlag** [comment]
Hi
Sorry about that, this is a limitation of an old client on which current iOS app is based. We are working hard to deliver the new iOS app as soon as possible.

**Comment by z5Q46L6bSY1W** [comment]
Is there an issue tracking this new iOS app?

**Comment by charlag** [comment]
Yes, #231
