### ISSUE TITLE
Registration dropouts for users coming from the website

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4605]
Users from the website (i.e., selecting a subscription on the website and then getting forwarded to the client) are not participating in the test currently because the tests are not initialized properly in UpgradeSubscriptionPage for this case.
selectFree() gets called before oncreate(), resulting in a race condition.

**Comment by armhub** [comment]
Test notes:

* Simulate a click on the subscription on the website with [/signup#subscription=free&type=private&interval=12](/signup#subscription=free&type=private&interval=12) and check if it is included in the signup.free test results.
