### ISSUE TITLE
Mark as phishing/not phishing is not shown immediately

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#4606]
When marking an email as phishing the phishing banner does not appear immediately. When marking an email as not phishing the phishing banner does not disappear immediately. Only when clicking on a different email and back to the marked one, the banner visibility is correct.

How to reproduce:
1. Go to the spam folder.
2. Mark an email as phishing.
-> The phishing banner does not appear.
Expected: The Phishing banner should appear

1. Select an email that is marked as phishing
2. Click on "Mark as not phishing" in the phishing banner
-> The phishing banner does not disappear
Expected: The Phishing banner should disappear

## Test notes
 - [ ] Try to repro the issue
 - [ ] Check that phishing status is still correctly determined from received markers (mail received first, markers confirmed later)
 - [ ] Check that marking as phishing updates the email as phishing directly (it will also be moved to spam)

**Comment by Umeaboy** [comment]
I have this issue as well.
Some commit must've broken the webui somehow.
