### ISSUE TITLE
Support MTA-STS (MTA Strict Transport Security)

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#461]
Check support here: https://www.hardenize.com/report/tutanota.com/1531686822#email_mta_sts
Some information here: https://www.hardenize.com/blog/mta-sts

**Comment by armhub** [comment]
Check how it can be supported for custom domains.

**Comment by ofiqfakj** [comment]
Please enable MTA-STS. Its still not enabled.

**Comment by charlag** [comment]
@ofiqfakj please stop. Your nagging won't make us faster (quite the contrary reading it will slow us down).

**Comment by ofiqfakj** [comment]
Thanks for the fast reply. I dont think its a slowdown when i show interest in a security optimization option that is not enabled now. Its just showing the opposite of what 99% of the people of the planet show - no knowledge in encryption and its relevance for privacy.

**Comment by zack-95** [comment]
Seriously @charlag? That's how you reply to your user base on a public forum? I always knew Germans were cold, but that was stone cold and rude. Also, MTA-STS is a quick, easy win that doesn't require any code changes.

**Comment by optomux** [comment]
Status update please?

**Comment by bedhub** [comment]
fixed server side

**Comment by ralexander-phi** [comment]
It looks like MTA-STS is supported for in-bound messages. Is MTA-STS supported for out-bound messages as well? As in, will Tuta check MTA-STS for recipient domains and perform TLS validation as needed? This appears to be missing.
