### ISSUE TITLE
Uncaught TypeError: One-time callback was called more than once

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4612]
Repro steps unclear

```
Client: darwin
Tutanota version: 3.100.2
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.100.2 Chrome/102.0.5005.167 Electron/19.0.17 Safari/537.36
TypeError
Error message: One-time callback was called more than once
Stacktrace:
TypeError: One-time callback was called more than once
at p (desktop/DesktopMain.js:1:46337)
at ClientRequest.<anonymous> (desktop/DesktopMain.js:1:47171)
at ClientRequest.emit (../../../../../node:events:526:28)
at TLSSocket.socketErrorListener (../../../../../node:_http_client:442:9)
at TLSSocket.emit (../../../../../node:events:526:28)
at TLSSocket._emitTLSError (../../../../../node:_tls_wrap:900:10)
at TLSWrap.onerror (../../../../../node:_tls_wrap:432:11)
```

## Test notes:
* [ ] network requests with slow/nonexistent network connection time out and give a "you're offline" message
* [ ] requests with normal internet work fine (ie you can log in)

**Comment by ganthern** [comment]
also happens on windows. One user report:

> I am getting error messages for several emails from this sender
> 
> Client: win32
> Type: PREMIUM
> Tutanota version: 3.105.9
> Timestamp (UTC): Wed, 21 Dec 2022 13:16:58 GMT
> User agent:
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.105.9 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
> TypeError
> Error message: One-time callback was called more than once
> Stacktrace:
> TypeError: One-time callback was called more than once
> at p (..\..\C:\Users\...\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:1:46656)
> at ..\..\ClientRequest.<anonymous> (C:\Users\...\AppData\Local\Programs\Tutanota Desktop\resources\app.asar\desktop\DesktopMain.js:1:47490)
> at ClientRequest.emit (..\..\node:events:513:28)
> at TLSSocket.socketOnData (..\..\node:_http_client:530:9)
> at TLSSocket.emit (..\..\node:events:513:28)
> at addChunk (..\..\node:internal/streams/readable:315:12)
> at readableAddChunk (..\..\node:internal/streams/readable:289:9)
> at Readable.push (..\..\node:internal/streams/readable:228:10)
> at TLSWrap.onStreamRead (..\..\node:internal/stream_base_commons:190:23)

asked for clarification about the exact nature of the error and the sender that seems to be affected.
