### ISSUE TITLE
Postings table is not aligned

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4618]
In Payment viewer:

![Screenshot from 2022-09-28 17-09-10](https://user-images.githubusercontent.com/29049728/192816048-ea8c5e0b-f238-45d5-973a-0efe30b18cbb.png)

The amount is not aligned to anything and because of that it looks odd next to the vertically centered button.

**Comment by JakeBamrah** [comment]
It seems like there is unnecessary padding on the price for the invoice (`pt-s`) class. I think if we remove the `pt-s` class name from the pricing it will look fine. Table spacing is fiddly :)

**Note:** Spacing will remain consistent and even across table rows, just as before. I would be happy to submit a pr.

Before:
<img width="648" alt="before" src="https://user-images.githubusercontent.com/45361366/192856916-d8d637f6-88ed-4b0f-bae8-a1e9897157a5.png">

After:
<img width="648" alt="after" src="https://user-images.githubusercontent.com/45361366/192856949-d771c8a9-b503-423a-b8d7-15c19bd68463.png">

**Comment by wrdhub** [comment]
We have revamped how this view looks, so I am closing this issue. (I still think the alignment could be better, but that is an issue for another issue)
