### ISSUE TITLE
Delete emails from trash and spam folders after 30 days automatically

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#462]

**Comment by x80486** [comment]
I guess it would be better to implement what was requested at #278. We would get this functionality, across the board for all the folder (or some of them) and with the possibility to set the time on our own.

**Comment by armhub** [comment]
Good idea, we should do that. Therefore I will close this issue.

**Comment by mpfau** [comment]
#278 would be nice for premium customers. However, spam and trash folders should be deleted automatically for free users.

**Comment by armhub** [comment]
Implemented on server side

**Comment by winduptoy** [comment]
I am still seeing messages in my trash folder older than 30 days.

**Comment by charlag** [comment]
They will be deleted fairly soon.
