### ISSUE TITLE
Feature request- Ability to set default calendar

### ISSUE THREAD

**Issue by billalbertson** [tutao/tutanota#4625]
Could someone add a checkbox to the individual calendar settings so I can set which calendar I want as the default?

Currently, the default is the first calendar that was auto-created.  However, as time has gone on, I needed another calendar, and I'm using it more often for not shared entries.  It would be very inconvenient to move a year's worth of appointments around.

**Comment by ganthern** [comment]
Please re-read the template you deleted after you clicked "new issue"

We took a note of this, until then consider exporting and then re-importing the appointments into the default calendar as a possible workaround.
