### ISSUE TITLE
Indexing indicator on mobile conflicts with menu

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#463]

**Comment by mpfau** [comment]
Screenshot?

**Comment by charlag** [comment]
![screenshot from 2018-11-02 07-30-32](https://user-images.githubusercontent.com/3099142/47897274-5abff380-de71-11e8-9024-2cd7c56934d5.png)

**Comment by wrdhub** [comment]
UI has changed since this was made, rendering this obsolete.
