### ISSUE TITLE
MailEditor: formatting buttons are  wrapping to second line although there seems to be enough space to show another button

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4642]
this is especially noticeable when the screen width is just below what's necessary to show all buttons on one line, which sadly coincides with some iPhone screen widths.

![IMG_6869](https://user-images.githubusercontent.com/8296817/194262288-6eb47a77-e9b9-4aef-876f-991ec2cfba85.png)

**Comment by wrdhub** [comment]
idk, sometimes there just isn't enough space. We want to redo formatting options on mobile anyways.
