### ISSUE TITLE
not selecting a template will still delete the keyword

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4648]
**Bug in web app**

**Describe the bug**
when closing the template popup without selecting a template, the keyword will be deleted from the mail body anyway.

**To Reproduce**
1. have templates
2. start new mail
3. type a keyword like `#mytemplate`
4. hit `Tab`
5. hit `Esc`
6. the text `#mytemplate` gets removed from the body

**Expected behavior**
the body should only be changed if a template was selected to insert.

**Comment by charlag** [comment]
Duplicate of ##3263
