### ISSUE TITLE
Client remembers scroll position and expanded state across emails

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4655]
**Describe the bug**
If you are viewing an email and scroll down to the bottom, then open a different email it will also open scrolled down.

**To Reproduce**
1. Have two long emails such that the content doesn't fit on one screen.
2. Open the first email and scroll down to the bottom
3. Open the second email

**Version**
 - All Desktop clients
 - Web clients
 - Version 3.100 and later.

**Comment by bedhub** [comment]
will be fixed with conversation view #4979
