### ISSUE TITLE
Android notifications / phone in offline mode

### ISSUE THREAD

**Issue by Ennneerrrgggyyy** [tutao/tutanota#4658]
Generally the notifications on my Android phone work fine

But if I receive an email why my phone is in offline mode I won't ever receive a notification for that email unless I receive another email while my phone is online

**Comment by ganthern** [comment]
Can you elaborate on this? It would be nice if you could use the template that you deleted when creating this issue with detailed reproduction steps. It's not clear what "phone is in offline mode" means, for example.
