### ISSUE TITLE
password generation reconfirmation

### ISSUE THREAD

**Issue by pc00per** [tutao/tutanota#4661]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in all platforms**
No passphrase confirmation while creating new password

**To Reproduce**
- Settings >
- Login Credentials >
- Password change 

**Expected behavior**
Need to ask reconfirmation, or have another text input box to retype new password.

**Screenshots**
![tutanota](https://user-images.githubusercontent.com/83843264/195247432-f6d283d0-2000-4888-b775-aded1b15ede2.png)

**Common on all platforms**

**Additional context**
This is very dangerous situation. Which online service provider doesn't ask new password twice ? If a user didn't backup recovery code, as well as mistype new password, it'll be the worst case scenario.

**Comment by charlag** [comment]
Hello
This was changed recently to remove re-confirmation. This is not a bug. Please open a discussion if you want to suggest something.

**Comment by pc00per** [comment]
There's an option in github to transfer this issue into a discussion. Wouldn't you mind doing that ?
Also why removed. Can I ask where's the explanation for this ?

**Comment by pc00per** [comment]
#4667
