### ISSUE TITLE
fix deprecation of electron-osx-sign

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4665]
after calling `npm ci`:

```
npm WARN deprecated electron-osx-sign@0.6.0: 
Please use @electron/osx-sign moving forward. Be aware the API is slightly different
```

**Comment by ganthern** [comment]
This will be resolved when https://github.com/tutao/tutanota/pull/4672 is merged and we update to electron-packager 17

**Comment by Rick-tee** [comment]
“Please use @electron/osx-sign moving forward. Be aware the API is slightly different”，how to fix this?
