### ISSUE TITLE
non-latin charachters are not displayed correctly when sending to external addresses

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4673]
When you send an email containing any non-latin characters to an external recipient, those characters are replaced by question mark characters "�" before the base64-encoding

**To Reproduce**
1. Compose an email to an external recipient 
2. add any non-latin character to the mail body: for example ä or ß
3. Send email
4. See error on the recipient's side

**Additional context**
This affects client version 3.102.3 on all platforms

**Comment by markusTraber** [comment]
Can confirm.

Client: Mac Desktop
Tutanota version: 3.102.3

**Comment by kibhub** [comment]
Issue has been fixed
