### ISSUE TITLE
ics descriptions are corrupted on import

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4685]
**Bug in web app**

**Describe the bug**
Some ical events are corrupted when being added to the calendar, destroying the formatting on the description

**To Reproduce**
Import the following ics data into any calendar:

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REPLY
BEGIN:VEVENT
DTSTART:20221026T210000Z
DTEND:20221026T220000Z
DTSTAMP:20221018T202558Z
UID:040000008200E00074C5B7101A82E00800000000B073543805E3D801000000000000000010000000EA368AA63E095848BAEEE25C239F56C6
SEQUENCE:0
SUMMARY:App Feedback Session
DESCRIPTION:\n________________________________________________________________________________\nMicrosoft Teams meeting\nJoin on your computer\, mobile app or room device\nUnited States\, Minneapolis\nPhone Conference ID: 000 000 000
LOCATION:Microsoft Teams Meeting
ORGANIZER;EMAIL=Mary.Doe@example.com:mailto:Mary.Doe@example.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;CN="Dack";EMAIL=dack@example.com:mailto:dack@example.com
END:VEVENT
END:VCALENDAR
```

And look at the description, the commas show up as `\,`.

**Expected behavior**
Description should be imported as-is and interpreted as valid ics data

**Additional context**
the problem may be a double escape 

## Test Notes
- [ ] The above ics file when imported:
  - [ ] displays the commas correctly 
  - [ ] displays the new lines correctly
- [ ] Importing various ics files work (regression test)
  - [ ] an event that has already been imported
  - [ ] an event with a start time & an end time
  - [ ] an event with a start time & a duration
  - [ ] a recurring event
  - [ ] a recurring event with an exception
  - [ ] an event with an empty body
  - [ ] an event with alarms
  - [ ] an event with attendees
  - [ ] an event with an organizer
- [ ] Special characters are escaped as per the [standard](https://icalendar.org/iCalendar-RFC-5545/3-3-11-text.html) when exporting an event as ics 
- [ ] The error reporter dialog still sends the error bodies correctly
  A test error can be made by copy & pasting `Promise.reject(new Error)` into the dev tools (open it by pressing F12) & pressing enter
- [ ] Creating an email via a `mail-to:` link still works
- [ ] Events from Microsoft Teams are imported correctly
- [ ] Editing the descriptions of existing events still works correctly (regression test)

**Comment by murilopereirame** [comment]
When I export a calendar with the imported Microsoft Team ics at the issue description and I try to import the calendar again I receive the following error:

![image](https://github.com/tutao/tutanota/assets/34790144/8b1c602a-6655-41d5-9c01-7c2c5b30da9b)

```
Object { name: "ParserError", message: "expected character : got   near Microsoft Teams me", stack: "ParserError. expected character : got   near Microsoft Teams me\n", filename: "calendar2-export.ics" }
```

---

When the title of the description of the event contains \n (as text, not new line) it exports correctly replacing \n to \\n but imports incorrectly, removing the \n text

**Comment by ganthern** [comment]
that's a clear regression, I'll take a look at it

**Comment by rezbyte** [comment]
This sounds like #5177 rather than a regression. Good there is a fix for it now.
