### ISSUE TITLE
Read/Undread keyboard shortcut doen't work in search view

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4686]
**Describe the bug**
Cannot use the keyboard shortcut "u" in search view to toggle emails between the read and unread status. 

**To Reproduce**
1. Enter a search term and hit enter
2. Select and Email
3. Press u on the keyboard

## Test Notes:
* [ ] Toggle Read/Unread shortcut "U" shows the same behavior in the search view like in the mail view

### Regressions:
* [ ] moving still works with the specific button
* [ ] all other shortcuts are still working in search view and in mail view

**Comment by ganthern** [comment]
related: https://github.com/tutao/tutanota/issues/4510
