### ISSUE TITLE
 always thinks it's offline

### ISSUE THREAD

**Issue by nutpantz** [tutao/tutanota#4693]
V31023
The app always thinks it's offline. i open the app and it thinks it's offline, i get a new mail notification and i open the app in under ten seconds and it thinks it's offline. It thinks it's offline with lte and i switch to wifi and it works, it thinks it's offline with wifi and i switch to lte and it works.

What it should do.
It should not look to see if it's offline it should just try and connect and fail to connect if it's offline.
 - Device: pixel 6
 - OS: protonaosp 12.4.1
 - Android 12

**Additional context**
if you are going to make the app think it's offline at the slightest failure during an internet access check, you are going to annoy anyone in a rural area. 
I know you are selling offline access but i seriously hope that this is not av bug caused by over eager trying to monitize access to emails stored on the device by the app while offline.

**Comment by nutpantz** [comment]
No not always offline maybe 75% of the time. Over in a while it will say connection interrupted. But mostly it just tells me I'm offline and it's a premium feature. Even if i was using to read a mail and i was going back to the main screen. 
I don't have any connection issues with any other apps. I have good service with both wifi and lte. But whatever i am on tutanota thinks there is no service 75% of the time when i do anything with the app and i have to switch to the other service before it works.

**Comment by nutpantz** [comment]
My webview is the latest. 
You should bundle your preferred webview with your app so other apps cannot cause issues. Webview is very small.

**Comment by charlag** [comment]
I am still not sure what exactly doesn't work. There are no offline messages going to the mail screen. The only time it mentions premium is when you try to log in while being offline. Does it mean you return to the login screen all the time? How would you get there after reading an email?

**Comment by nutpantz** [comment]
It says disconnected \ offline at the top of the screen

**Comment by charlag** [comment]
@stringdom websocket connection doesn't work for you for some reason
