### ISSUE TITLE
Custom domain managed by another service

### ISSUE THREAD

**Issue by polo9719** [tutao/tutanota#4694]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in all apps**

**Describe the bug**
I am managing a custom domain with my family name, and every member of the family has its own address, that he added manually in its favorite email service (Gmail, ProtonMail, etc.).

By my side, I wanted to start using Tutanota, so I added a custom domain by just setting the TXT entry in my DNS. (I don't want Tutanota to manage the domain, I just want to keep the current stack, to allow every member of the family to use its own email service).

I first thought everything was fine, but I finally realised I couldn't send messages to other addresses of the same domain.
I receive an error message from Tutanota : 

```
Subject: Email could not be delivered
---
We are sorry to let you know that the following email could not be delivered.

Date: Oct 27, 2022, 12:06:26 PM
Recipients: [***@***.fr](mailto:***@***.fr)
The recipient does not exist.
```

I think Tutanota is raising an error, even if is is useless to check the existence of the user, because it does not manage the email server.

**To Reproduce**
1. Add a custom domain with only the TXT entry of the DNS (emails managed by another service, not Tutanota)
2. Add an associated email address
3. Add an alias to the user with this email
4. Send an email to an other address of the same domain
5. Receive the error message saying that the `Recipient does not exist`

**Expected behavior**
No error message should be sent, Tutanota should not check the existence of the user, since it does not manage the emails of the domain.

Thank you in advance for your help,
Paul

**Comment by charlag** [comment]
Could you please contact support so that they can look at your exact domain/account case?

**Comment by polo9719** [comment]
> Could you please contact support so that they can look at your exact domain/account case?

Yes I will contact them

**Comment by charlag** [comment]
we'll reopen it if we find anything
