### ISSUE TITLE
Overlapping calendar events in day view

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4702]
1. Create a short event at the end of an hout e.g. 8.45 - 9.00
2. Create a second event starting from 9.00.
3.  Error -> second event overlaps first one and the text from the first is not fully visible.
![IMG_6970](https://user-images.githubusercontent.com/8296817/199233637-b87deb67-2931-4ce1-bd5a-0e21edf106fa.png)

Expected:
Events should not overlap but displayed underneath each other.

**Comment by charlag** [comment]
There is a minimum height for the event, that's why it happens

**Comment by sarashub** [comment]
To not further reduce the minimum height we decided to place the events side by side in case they would overlap.

**Comment by sarashub** [comment]
**Testnotes**

- [ ] Create following events of different lengths (e.g. 15 minutes, 30 minutes...) and check that they do not overlapp
