### ISSUE TITLE
can't copy email domain from sender

### ISSUE THREAD

**Issue by chovy** [tutao/tutanota#471]
Some other screen pops up and doesn't allow me to copy the domain of the sender.

For example if I receive an email from "sam@example.com" I am unable to copy "example.com" on chrome/desktop/mac.

**Comment by charlag** [comment]
Hi!
When you press a sender, there's a popup where you can copy the domain. Do I miss something?
![screenshot from 2018-07-19 07-59-37](https://user-images.githubusercontent.com/3099142/42924285-c3fc73e6-8b29-11e8-8f49-5ef32a40d33b.png)

**Comment by chovy** [comment]
nevermind, i didn't notice that. sorry about that :)
