### ISSUE TITLE
mail that contains both external and inline images replaces the inline with a placeholder when "show external" is pressed

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4712]
**Bug in web app**

**Describe the bug**
A mail that contains an inline QR code svg and external images replaces the QR code with the placeholder image when "show external images" is pressed. This is a problem with some newsletters.

**To Reproduce**
1. start new mail, insert an **svg** as an inline image
2. copy some HTML with an image (for example wikipedia's article of the day section) and paste that into the mail editor
3. send the mail to yourself
4. optionally click "block images" from the more menu in the viewer for the received mail
5. switch to another mail and back, the external image should now be a placeholder and the inline image should be shown
6. press "show external image" on the banner
7. the inline image is now a placeholder and the external image is shown

ping @ganthern for an example mail

**Expected behavior**
the inline image should remain when the external images are loaded

**Affected**
Tutanota Version 3.102.3

**Additional Context**
this doesn't work 100% of the time, so maybe it's a timing issue that depends on how complicated the svg is (sanitizer?)

**Comment by sarashub** [comment]
**Testnotes**

- [ ] Follow the steps to reproduce the issue using different svg files. Check that they are never replaced by a placeholder when external images are loaded.
