### ISSUE TITLE
Can't register a U2F key with a long name

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4727]
**Description**

It looks like there is a max number of characters for a U2F key depending on the environment. If I try to add a key with a 28 char. name in e.g. Chromium (for example: chaiyeb9fohngaGhapup2Xoh2Shu), the key is not triggered for confirmation. No error message is shown and the process doesn't fail. The client is stuck at waiting for the key. 

 - Browser: Chrome, and Chromium based browsers, and the Desktop client.
 - Version  v3.102.3 but possibly older versions as well
 - All operating systems

fails with more than:
 - 28 chars on Ubuntu Desktop
 - 20 chars on Ubuntu Chromium/ Chrome
 - 27 chars on Windows Desktop
 - 27 chars on Windows Chrome

**Note**
If you register a key with a name that would not work in chrome in firefox and then attempt to log in with it in chromium,
the login will fail with a "invalid credentials" error.

## Test Notes:
* [ ] test the following on:  [Ubuntu Firefox], [Ubuntu Chrome], [Windows Desktop Client], [Windows Chrome]
* [ ] go to settings, login
* [ ] click on register second factor
* [ ] select TOTP and check that "TOTP" is the default name
* [ ] select U2F and check that "U2F" is the default name
* [ ] try to register both second factors with a whitespace only name -> should use the default name
* [ ] for U2F: type in a name longer than 64 chars -> should display that the entered name is too long and clicking save will fail with an error dialog
* [ ] for TOTP: registering a second factor with a name longer than 64 chars works

### Regressions
* [ ] any newly registered second factors work for login
* [ ] any old second factors can still be used (use old desktop client to create some)

**Comment by ganthern** [comment]
I can't reproduce this on Ubuntu with Chromium 108 or the desktop client (electron 19.1.8 with chromium 102). Will test other platforms.
