### ISSUE TITLE
Connection lost message at the bottom of the mail list does not reliably follow the alternating list color scheme

### ISSUE THREAD

**Issue by nokhub** [tutao/tutanota#4749]
Sometimes the Connection lost message at the bottom of the mail list, which is displayed while offline, does not have the correct alternating color. But there are also cases when it works.

**To Reproduce**
1. Log in to some account with a lot of emails in the inbox
2. turn of internet
3. Scroll down to see the "Connection lost" message / "Try again" button
4. the list entry with this message might have the wrong color

**Expected behavior**
Message element should be gray if the previous mail is white and white if the previous mail is gray.

**Screenshots**
![image](https://user-images.githubusercontent.com/115003415/202496586-2cbfc3db-c798-49d2-a19b-546a33e22041.png)

Occurs on any client (web, desktop and mobile)

**Comment by bedhub** [comment]
we do not have alternating colors anymore
