### ISSUE TITLE
Extension not supported 

### ISSUE THREAD

**Issue by macbernal** [tutao/tutanota#4750]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vitoreiji** [comment]
I think you forgot to put in some information. Can you please give us some context?
