### ISSUE TITLE
Enable swipe to open the drawer menu on android devices with system (back) gestures activated

### ISSUE THREAD

**Issue by jomapp** [tutao/tutanota#4758]
As a user I want to be able to open the drawer menu within the app with a swipe from the left, even if I have system (back) gestures enabled on my device, so that I can access the drawer menu more quickly.

**Comment by charlag** [comment]
## Test notes:

- [ ] Make sure swipe from the left is working on the devices without gesture navigation activated
- [ ] Make sure back button system gesture is working on other screen areas (i.e. everywhere except bottom left)
