### ISSUE TITLE
Features don't wrap or ellipsize

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4773]
![image](https://user-images.githubusercontent.com/3099142/204316135-188b4bd9-2773-4eff-a67d-7493bd1c3efe.png)

compare to the website

![image](https://user-images.githubusercontent.com/3099142/204316739-cdac98ae-65a2-4a87-adcf-6367e33bf4c0.png)

## Test Notes
* [ ]  check that the issue above is resolved during signup & in the upgrade/switch dialog
* [ ] check that the text in the tooltip boxes also wraps correctly

**Comment by vitoreiji** [comment]
Wrapping is happening, but long strings are squished vertically:
![image](https://user-images.githubusercontent.com/197261/204531573-4cfd19d7-b4a4-47e7-b412-fc15abe8bebc.png)
We could fix this particular case by shortening the translation, but a general solution is probably preferable.

**Comment by charlag** [comment]
I think we designed it with 2 lines in mind :thinking:
