### ISSUE TITLE
Recovery code usage test is sometimes not loaded correctly

### ISSUE THREAD

**Issue by nowhub** [tutao/tutanota#4784]
Only happens if the user has not opted in to usage data, opts in, and then immediately participates in the recovery code usage test.
This is because we are caching the test instance in the news item's constructor and, due to a race condition, it may not be loaded in time after fetching the user's assignments.

**Comment by charlag** [comment]
This will be in 3.105.3

**Comment by charlag** [comment]
If websocket message takes a while to arrive we might still miss some of the user interactions. We should load assignments proactively right after we make an opt-in decision.
