### ISSUE TITLE
Campaign discount not shown at signup

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#4796]
When reaching the website with a link of a campaign with discount, this discount is not shown in the prices in the subscription overview when signing up in the client.

1. Create campaign with any discount
2. Use campaign link to open website
3. Open signup in client
-> The prices do not contain the discount.

Expected: The prices contain the discount.

The discount is however applied when the paid account is created, so it is just the UpgradePriceService which does not apply the campaign discount.

**Hints**
- When testing locally it only works with a dist build of the website
- This is fixed on the server side on branch 4796-fix-campaign-discount-not-shown

**Test notes**

- [x] Follow reproduction steps and see that discount is shown at signup and applied to the account.
- [x] Regression test: Use a signup link with discount and check that the discount is shown at signup and applied to the account.

**Comment by ganthern** [comment]
I can't get this to work locally, the discount is applied for registration links but not for campaigns from the website.
