### ISSUE TITLE
Progress is not shown for Save All

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4811]
1. Open an email with multiple attachments on Android 
2. Click on "save all"
3. See no indication of anything happening

We could show progressDialog even if it's slow. Ideally it would be non-blocking progress indicator.

## Test Notes
* [ ] It is best to test all of:
Chrome,
Firefox,
Safari,
Desktop Ubuntu and Windows,
iOS App,
Android App,
Chrome and Firefox on Android
and Safari on iOS
* [ ] iOS App won't show the "Save all" download option
* [ ] download a single file
  * [ ] make sure that the default download location is respected in case it is set (should be download folder on android) -> file appears in this folder
  * [ ] if the setting to ask for the destination before downloading is enabled in a browser, you should be prompted to choose a location
  * [ ] make sure that a spinning progress dialog is visible for the whole time downloading (even when selecting the downloaded files destination folder)
  * [ ] downloading without internet connection will give an error message
* [ ] download multiple files with the "Save all" option
  * [ ] make sure that the default download location is respected in case it is set (should be download folder on android) -> file appears in this folder (on Desktop and Browser the files should be saved as a single zip file)
  * [ ] if the setting to ask for the destination before downloading is enabled in a browser, you should be prompted to choose a location
  * [ ] make sure that a progress dialog (indicating the completeness) is visible for the whole time downloading (even when selecting the downloaded files destination folder)
  * [ ] downloading without internet connection will give an error message for each file, mentioning the file name

### Regressions
* [ ] Opening single files works on all above mentioned platforms (there shouldn't be such an option in browsers)

**Comment by bedhub** [comment]
We discussed non blocking options but there was no obvious solution so we decided that we want to implement the blocking  solution for "save all" similar to single attachment download for now. 
We will add a non blocking variant later.
