### ISSUE TITLE
latest fdroid 3.105.3 not connecting on wifi

### ISSUE THREAD

**Issue by nutpantz** [tutao/tutanota#4813]
**Bug in mobile app**

**Describe the bug**
4 devices in the house, 3 on wifi only. All 3 wifi Android phones no longer connect on wifi. Logging in hangs and never logs in. Internet connection works fine. Switching mobile connected device to wifi only and it stops connecting exactly the same way 
Notification service runs for 10+ minutes and never finishes. should be a way to stop it.

Android 9, 12. 11 oem rom, lineageos x2 and pixel 6
Can't log in anymore from desktop either.
So maybe tutanota is blocking the ip address
There are 4 people who use tutanota in the house, is there a new limit? these accounts have been working for over a year. Stopped right after last update

**Comment by charlag** [comment]
Please contact support with your IP address
