### ISSUE TITLE
contact comment field not update v3.35.8

### ISSUE THREAD

**Issue by bzdzz** [tutao/tutanota#482]
Hi, in beta v 3.35.8, I open existing contacts, made change to comment field, hit save.  I can see new comment on desktop web login immediately, but inside the app, when I return to contact the new comment was not updated. Only by log out and log back into app does the new comment changes became visible.

**Comment by charlag** [comment]
Hi! Thanks for reporting, we will have a look

**Comment by asteintutao** [comment]
i could not reproduce it on 3.37.1  android 5.1.1
try updating it might solve this issue.
