### ISSUE TITLE
Sign all unsigned dll files within the Windows desktop app

### ISSUE THREAD

**Issue by hj-collab** [tutao/tutanota#4830]
3rd party libraries used in the Windows Desktop App is unsigned. Tutanota desktop client cannot be used in environments which make use of WDAC. https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/wdac-and-applocker-overview

Please sign these unsigned libraries with Tutanota signature.

**Comment by charlag** [comment]
Hi, thanks for the report!
Could you provide more info on how can we check that or which libraries are those? Thanks!

**Comment by ganthern** [comment]
## Test Notes
* [ ]  the update & installation worked correctly 
* [ ] above reproduction shows the signature for the bundled DLLs

**Comment by ganthern** [comment]
We're not signing our debug builds, all test and production releases will have `sign` set to true.

**Comment by charlag** [comment]
@hj-collab thank you for letting us know!
