### ISSUE TITLE
It's not possible to change the sender name on shared mailboxes

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4845]
currently, it'll use the name of the mail box and then hold on to it forever because it gets copied to the MailAddressProperties.

need to add an edit button to the mail address.

## Test Notes
create a premium account with a global admin, and two non-admin users; all three with different names.
General Note: test that the new sender name can be used in the mail editor each time it's changed.
 
* [ ] create a shared mail group with a name different from any of the user names
* [ ] add one of the non-admin users to the group.
* [ ] the mail group's sender name is initially set to the chosen mail group name
* [ ] the global admin can change the sender name if they're **not** a member of the mail group
* [ ] the global admin can change the sender name if they're a member of the mail group

now create a local admin group and add the other non-admin user to it.

* [ ] the local admin can't change the sender name of the mail group.
* [ ] it's possible to set the shared mail group to be administrated by the admin group and afterwards:
* [ ] the local admin user can change the mail groups sender name if they're **not** a member of the mail group
* [ ] the local admin user can change the mail groups sender name if they're a member of the mail group
* [ ] the global admin can still change the mail groups sender name if they're **not** a member of the mail group
* [ ] the global admin can still change the mail groups sender name if they're a member of the mail group

### Regression Tests
* [ ] all settings for local admin groups can be changed and are applied
  * name
  * members
  * administrated by
  * active/inactive
  * administrated groups
* [ ] all settings for shared mailboxes are changed and applied
  * name
  * members
  * administrated by
  * active/inactive
* [ ] retest #516

**Comment by charlag** [comment]
Allow defining it like for other mail addresses.


Do not have to use MailAddressTable yet but add display and action to the existing view in group viewer.
