### ISSUE TITLE
Scrolling bugs in calendar

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#4846]
In desktop:

 - in month view the whole screen sometimes scrolls
 - in day/week view it doesn't scroll

## Test notes
Check on Desktop, Chrome, Firefox, Safari:
 - [ ] Month view never scrolls vertically.
   - [ ] Month view does not scroll and fully fits without gaps when events on a day a folded and the indicator is shown
 - [ ] Month view never shows the vertical scrollbar, not even while resizing vertically
 - [ ] Day, Week, Agenda views can be scrolled vertically normally
 
In mobile apps(check both):
 - [ ] Can still scroll between pages and the page preview is shown while panning horizontally
 - [ ] There isn't any vertical scroll for the month view
 - [ ] Day, Agenda can be scrolled vertically normally

**Comment by nokhub** [comment]
Only happens in Chromium, seem to be related to overflow changes in Chromium 108
