### ISSUE TITLE
Some calendar items are not visible in month view

### ISSUE THREAD

**Issue by jomapp** [tutao/tutanota#4847]
With Tutanota version 3.105.9 some calendar items are not visible in the month view anymore.

Steps to reproduce:

- Create two calendars
- Create Appointments on two consecutive days (e.g. 5 each day) while each day only has calendar entries of one calendar
- The second day is missing some calendar entries in the month view, even though there is still space to display them

See the following screenshots

Calendar event is missing even there is space:
![Image](https://user-images.githubusercontent.com/17314077/207278802-20090088-2960-4e8e-85ed-2333494bf2d6.svg)
Calendar event is showing in week view:
![Image](https://user-images.githubusercontent.com/17314077/207279079-b353e83f-b1c7-4840-82ac-cc487ce3803d.svg)

## Test notes
 - [ ] Make sure two events in the month view are on the consecutive days and would be on the same row (e.g. at the same time). They should be displayed on the same row.
 - [ ] Check that all the expected events are displayed in the month view. Single-day events fill up the day at any empty spots:
not like this:
![image](https://user-images.githubusercontent.com/115003415/207370945-277c9758-b543-43ac-87b1-45beb5af13a0.png)
should look like this:
![image](https://user-images.githubusercontent.com/115003415/207371094-e6f39bc6-88a7-470c-bb55-32af50f7c683.png)
 - [ ] Regression:  Create following events of different lengths (e.g. 10 minutes, 15 minutes, 30 minutes...) and check that they do not overlap. Check in day view and week view.
 - [ ] Check that in day/week view events that would overlap are correctly split into multiple columns, including multi-day events
 - [ ] Check that all-day events are still correctly displayed at the top of day/week views

**Comment by pappasadrian** [comment]
I have a similar issue (not sure if it is exactly the same). The calendar insists on leaving gaps above some events. They become visible only if the window is expanded vertically (the different screenshots are of different window height size). There is space for 3 events, yet the only one in the current day remains hidden.
![Screenshot from 2022-12-13 13-49-55](https://user-images.githubusercontent.com/2352509/207311263-c4d9b049-5af8-4d15-8050-a1341398684f.png)
![Screenshot from 2022-12-13 13-50-11](https://user-images.githubusercontent.com/2352509/207311275-3d7e28a1-4877-4db8-a729-b838c999ba74.png)
![Screenshot from 2022-12-13 13-50-04](https://user-images.githubusercontent.com/2352509/207311276-6d75798b-2076-4fb3-8713-fc04dff133cd.png)
![Screenshot from 2022-12-13 13-49-48](https://user-images.githubusercontent.com/2352509/207311278-52e3006d-73af-4c30-a2e5-c8428e1250b7.png)

**Comment by jomapp** [comment]
Thank you for your input and the screenshots @pappasadrian. We already fixed the bug and it will be in the next release.
