### ISSUE TITLE
Images not showing in support section

### ISSUE THREAD

**Issue by jomapp** [tutao/tutanota#4855]
**Bug in web/mobile/desktop app**

**Describe the bug**
Images are not showing in support section. Please see screenshots. 

**To Reproduce**
1. Click on question mark on the left
3. Click on support
4. Search for e.g. "mail"
5. See that no images are shown, but image alt is shown instead.

**Expected behavior**
All images are correctly displayed

**Screenshots**
![Screenshot from 2022-12-14 14-29-34](https://user-images.githubusercontent.com/17314077/207609629-bffa410c-329f-4cf7-8cd7-184cc9b4b210.png)
![Screenshot from 2022-12-14 14-31-24](https://user-images.githubusercontent.com/17314077/207609540-3b8f15f4-2281-4699-b333-1db577c6c5ba.png)

**Comment by charlag** [comment]
Fixed in translation project by generating absolute scrset links
