### ISSUE TITLE
System tray icon does not show up in some environments

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#4856]
Since the release of v3.105.9 Tutanota doesn't show up in the system tray of some desktop environments and window managers in linux.

Tested on:

- Mate desktop environment, tested with Ubuntu Mate 22.04
- dwm
- AwesomeWM

**Comment by hedylogos** [comment]
System configuration specifics:

On Linux Mint 21 Vanessa (Ubuntu 22.04 fork) with MATE v1.26.0 desktop environment. Display manager is Light Display Manager (lightdm) v1.30.0, and the windows manager is Metacity (Marco).


Dell Inspiron laptop has the Ryzen 7 5850U APU with integrated Radeon Barcelo GPU, with kernel 5.15.0-*-generic. Driver: amdgpu from kernel.

Asus Zenbook laptop has the Ryzen 5 5500U APU with integrated Radeon Lucienne GPU, with kernel 5.17.0-*-oem. Driver: amdgpu from kernel.

In both laptops there's Mesa v22.0.5; X.Org v1.21.1.3; and Picom v9 compositor. In the MATE Tweak utility, the WM is set to Marco (picom: GLX), but I've also tried picom:Xpresent, picom:Xrender, picom:GLX, and picom:Hybrid.


I confirm the Metacity (Marco) windows manager with either of these Terminal commands:

	wmctrl -m
	neofetch

The inxi utility reports WM v1.26.0.

I confirm the lightdm display manager with either of these Terminal commands:

	systemctl status display-manager
	cat /etc/X11/default-display-manager

The new version v3.106.4 of Tutanota AppImage does not fix the "missing system-tray icon" issue that v3.105.9 introduced.

GV

**Comment by hedylogos** [comment]
Version 3.109.4 appears to have resolved the issue. The icon again appears and remains in the task bar.

**Comment by kibhub** [comment]
update to electron v22.2.1 fixes the issue
