### ISSUE TITLE
Move subfolders

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4858]
As a user I want to be able to move custom folders to every possible level in the folder hierarchy of other custom folders.

## AC

*  a specific folder can be moved by selecting "Edit" action next to the custom folder
*  "Edit" action opens a dialog containing a drop down menu to select parent and a name input to modify the name of the selected folder
* Clicking the drop down menu opens a list will all possible hierarchy levels (including the top level)
* An "apply" button closes the newly opened window and applies the changes
* A "cancel" button closes the newly opened move window and leaves the folder in the way it was before
* If the new parent contains a conflicting subfolder already, the name input is marked as an error and suggests to change the name before moving.
* All emails and subfolders in the moved folder will be moved to the new location
* Collapsed state is tracked for each individual folder and doesn't change on move or depend on parents/children collapsed state
* Create folder loops is not possible

**Test Notes**
- [ ] When editing folder, Cancel button does not apply any changes
- [ ] You can change only the name
- [ ] You can change only the parent folder
- [ ] You can change the name and the parent folder at the same time
- [ ] A folder with this name already exists appears if there is already a folder with that name in that parent folder
- [ ] move folder works
- [ ] moving folder with subfolders moves all subfolders
- [ ] moving folder to spam triggers spam dialog or popup
- [ ] moving folder to trash triggers trash dialog

**Comment by wrdhub** [comment]
Note: Don't merge this PR, these changes are rolled into the delete folder structure PR.
