### ISSUE TITLE
Uncaught Error: Command failed: powershell.exe

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4884]
**Describe the bug**
Uncaught errors from native in the reports mailbox:

```
Client: win32
Type: PREMIUM
Tutanota version: 3.103.3
Timestamp (UTC): Tue, 15 Nov 2022 11:35:29 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.103.3 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
Error
Error message: Command failed: powershell.exe -NoProfile -NonInteractive -InputFormat None -Command Get-AuthenticodeSignature -LiteralPath 'C:\Users\...\AppData\Local\tutanota-desktop-updater\pending\temp-tutanota-desktop-win.exe' | ConvertTo-Json -Compress | ForEach-Object { [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($_)) }

Stacktrace:
Error: Command failed: powershell.exe -NoProfile -NonInteractive -InputFormat None -Command Get-AuthenticodeSignature -LiteralPath 'C:\Users\...\AppData\Local\tutanota-desktop-updater\pending\temp-tutanota-desktop-win.exe' | ConvertTo-Json -Compress | ForEach-Object { [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($_)) }

at ChildProcess.exithandler (..\..\node:child_process:408:12)
at ChildProcess.emit (..\..\node:events:526:28)
at maybeClose (..\..\node:internal/child_process:1092:16)
at ChildProcess._handle.onexit (..\..\node:internal/child_process:302:5)
```

They suggest that it happens during update installation, which makes sense considering the command that's failing is part of the updater/installer.

**Desktop (please complete the following information):**
* windows only
* happens every desktop release
* first reports came from v3.103.3, so it's probably something we introduced with that version or the one following (with the failing signature extraction)
* we had about ~160 reports of this since November 15

### Test Notes
* [ ] update from affected version to fixed version worked on mac, windows, linux
* [ ] update from fixed version to fixed version worked on mac, windows, linux

**Comment by nokhub** [comment]
updating from 3.108.x to 3.108.6 does not work on ubuntu
