### ISSUE TITLE
No tooltip on email folders after dragging email

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#4889]
After dragging an email or attempting to drag an email, hovering over an email folder with the mouse does not show the email folder name tooltip. After clicking on an email or folder, the tooltips are shown again.

How to reproduce
1. Drag and drop an email to an email folder.
2. Hover over an email folder.
-> The email folder name is not shown as tooltip.

Expected:
The email folder name is shown as tooltip.

Reproduced in Linux desktop client.

**Comment by nokhub** [comment]
Works in firefox but not in chromium. Also tried with a minimal mithril app -> same behavior
