### ISSUE TITLE
Account login by feeding a local keyfile (it provides a password without typing anything)

### ISSUE THREAD

**Issue by serrq** [tutao/tutanota#4897]
I already use this method with KeePassDX.
Just open the app, select the right keyfile, press "open" and I am inside.
No keylogger or clipboard can be involved. Ultra safe.

**Comment by charlag** [comment]
Hi!
As stated in README and issue templates, we don't accept feature requests here in order to keep the repository manageable. Please see the [forum](https://www.reddit.com/r/tutanota/) or [contact](https://tutanota.com/contact/) pages.
Thanks for understanding.
