### ISSUE TITLE
Please update installation guide

### ISSUE THREAD

**Issue by ioakimov** [tutao/tutanota#49]
I was able to install local **Tutanota** web app.
When I opened `build/index.html` I was redirected to the `#login` page
But, unfortunately,, I don't know default login/password for Admin account.
Could you suggest default `login/password` for Admin account?

**Comment by ioakimov** [comment]
Also I have found similar request on Tutanota forum:
https://tutanota.uservoice.com/forums/237921-general/suggestions/31122481-update-building-and-running-your-own-tutanota-web
Could you please help?

**Comment by ioakimov** [comment]
I have tried to build project in `distLocal` mode, instead of `dist` mode.
Now `login` page always show infinite loader.
Is there any place where I can find log with detailed error?
In browser console I see only warnings that I am trying to show form with credantials on unsecure HTTP page.
Please note that I am using Python HTTPS server(port 9000). After opening `https://localhost:9000`, I was redirected to `http://MY_IP:9000`.

**Comment by armhub** [comment]
Thanks for this request, we will update the instructions for the new client.

**Comment by charlag** [comment]
We've updated build steps in 3594054ed97051d8db98a72d20635f9ae580db30 and we're going to add Docker instructions when we merge #442

**Comment by SuperPauly** [comment]
Hi, I'm just checking out the GUI see if it's good for my use case.

I have just built the latest release. I have launched the python server but what is the username and password?
