### ISSUE TITLE
Samsung keyboard: Android app is unusable to reply with existing text in the last couple weeks

### ISSUE THREAD

**Issue by finagolfin** [tutao/tutanota#4904]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When responding to email, the focus keeps changing as it automatically adds empty lines at the bottom. Also, my response is merged into the text that I'm responding to, so you can't tell what I wrote versus what I'm responding to.

**To Reproduce**
1. Reply to an email with their text included.
2. Start typing.

**Expected behavior**
No change of focus or merging of the original text I received and my reply, as it used to work a month prior.

**Smartphone (please complete the following information):**
 - Device: Samsung S phone
 - OS: Android
 - Version 13

**Additional context**
Could be related to a recent Android 13 or webview 108.0.5359.128 update, as I'm seeing similar changing of focus now when filing this bug in Opera 72.5.3767.69342 for Android. I don't see this issue when using the Tutanota web interface from this same browser though, so unsure what's causing it.

**Comment by charlag** [comment]
Hi
This is most likely related to the stock Samsung keyboard based on the previous reports. Could you try with any other keyboard?

**Comment by buttaface** [comment]
You may be right, as I cannot reproduce with the Hacker's keyboard in a couple minutes of trying. Is this a recent regression? I think I was using Tutanota fine with the stock Samsung keyboard before, I have version 5.6.00.40 installed now.

**Comment by charlag** [comment]
Thanks for trying it out. There were no significant changes to mail editor in a while but there were some changes to the global event handling, maybe we should try and reproduce it.

Does it happen only when replying?

**Comment by buttaface** [comment]
Mostly, something about having that existing text that I'm responding to at the bottom appears to trigger it. Let me know if anyone else runs into this issue too.

**Comment by finagolfin** [comment]
I'm not seeing this issue anymore, appears to be fixed.
