### ISSUE TITLE
Improve folder editing options

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#4909]
Options are: 
* Show three dots on desktop layout (three column layout) on hover and when folder is selected 
* Special edit mode which the user activates and then the three dots are visible for each folder. 
(works on mobile and desktop, requires more clicks on desktop to change folder name and move a folder)
* Add a button at the bottom/top of the folder list [Add folder +] and remove + and the "Your folders" line and the dots?

**Comment by charlag** [comment]
Already implemented
