### ISSUE TITLE
Uncaught PayloadTooLargeError in /rest/sys/alarmservice POST

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4915]
Some people are uploading megabytes of data to the alarm service and get errors because of that.

> We've had this before, too many push identifiers. We need to limit them pretty soon or we'll be in trouble.

```
Client: Browser
Type: FREE
Tutanota version: 3.105.9
Timestamp (UTC): Tue, 20 Dec 2022 20:14:56 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
PayloadTooLargeError
Error message: request body is too large. Path: /rest/sys/alarmservice, Method: POST, Body length: 4914313
Stacktrace:
o@https://mail.tutanota.com/common-min-021d8546.js:1:12210
et@https://mail.tutanota.com/common-min-021d8546.js:1:29973
checkRequestSizeLimit@https://mail.tutanota.com/worker.js:12:102247
request@https://mail.tutanota.com/worker.js:12:98369
@https://mail.tutanota.com/worker.js:12:142998
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

## Test Notes
- [x] Do tests on #4457

**Comment by bedhub** [comment]
Catch PayloadTooLargeError error when making request to /rest/sys/alarmservice and show error message to the user that push identifers must be removed.

**Comment by ganthern** [comment]
We actually have something similar that happens from time to time just by importing a big calendar:

https://github.com/tutao/tutanota/issues/4457
