### ISSUE TITLE
Month view straddling new year's shows confusing time range

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4924]
![image](https://user-images.githubusercontent.com/29049728/210534038-56909598-ee46-4b72-9e76-97db50492391.png)

Should probably say December 2022 - January 2023

## Test Notes
- [ ]  Look at a week that spans over two different years, it should show the year for each month
- [ ] Look at a week that spans over two different months in the same year, it should show the year only once

**Comment by charlag** [comment]
I feel like we already had an issue about this
