### ISSUE TITLE
Uncaught Error: no range exists for tutanota/CalendarEventUpdate and list listId

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4935]
Happens on all native platforms since at least 3.100.0 (~10 reports):

```
Client: android
Type: FREE
Tutanota version: 3.106.4
Timestamp (UTC): Fri, 30 Dec 2022 22:40:48 GMT
User agent:
Mozilla/5.0 (Linux; Android 11; moto g(9) plus Build/RPAS31.Q2-59-17-4-3-9; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
Error
Error message: no range exists for tutanota/CalendarEventUpdate and list MUTpwRc--c-2
Stacktrace:
Error: no range exists for tutanota/CalendarEventUpdate and list MUTpwRc--c-2
at Zl.getIdsInRange (https://assets.tutanota.com/worker.js:12:155934)
at async Ia.recalculateRangeRequest (https://assets.tutanota.com/worker.js:1:21421)
at async Ia.extendFromWithinRange (https://assets.tutanota.com/worker.js:1:20230)
at async Ia.loadRange (https://assets.tutanota.com/worker.js:1:19836)
```

affected Instances don't really show a pattern:
* CalendarEventUpdate
* PushIdentifier
* Contact
* Mail
* MailFolder
* GroupInfo
* UserAlarmInfo

One user on ios 3.103.3 and later ios 3.104.5 added some info:

> Local data is out of sync due to system clock?

> I can’t use my account because it keeps saying my clock is not synced with your server clock. Please help!

There's no message that references the system clock in tutanota, so I assume that's a system error message?

**Comment by charlag** [comment]
Is not reported anymore (probably fixed by locking/queuing the range modification)
