### ISSUE TITLE
Uncaught Error: No application in the Launch Services database matches the input criteria (kLSApplicationNotFoundErr) when clicking custom protocol URLs in emails

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#4952]
**Describe the bug**
On MacOs desktop:

> clicked URL in email body

```
Client: darwin
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Fri, 06 Jan 2023 21:36:24 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.5 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
Error
Error message: No application in the Launch Services database matches the input criteria.
Stacktrace:
Error: No application in the Launch Services database matches the input criteria.
```

This may be an Error of type https://developer.apple.com/documentation/coreservices/klsapplicationnotfounderr

**Notes:**
* If this is just about no app being available that opens the given file type, this should be handled like other failures to open files (show a dialog).
* when we add a url like `sin://ful` to a mail body and click it, this error is thrown.

## Test Notes 
(try this on win/linux/mac)
* [ ] test that links in mail can still be opened in the browser
* [ ] create a mail with a custom protocol link by opening the inspector and changing the scheme of the URL of a link to something like "cheese"... `cheese://on/pizza.com` click the link and verify that the error dialog pops up.

**Comment by nmaxcom** [comment]
I have the same issue:
UnhandledPromiseRejectionWarning: Error: No application in the Launch Services database matches the input criteria.

Shown when clicking a URL. It used to work flawlessly, then it showed for the first time. I changed the default mac browser to Firefox, and it opens there, good.
Changed back to Chrome, opens there, good.
A rerun the electron app again, having changed nothing, same UnhandledPromiseRejectionWarning: Error: No application in the Launch Services database matches the input criteria...
