### ISSUE TITLE
pc  encryption？

### ISSUE THREAD

**Issue by BigEgret** [tutao/tutanota#496]
Is the encryption on PC secure, and is it encrypted with Rsa? How do you interact between a PC and an app?

**Comment by charlag** [comment]
Please don't use GH issues for general questions.
In web client we do encryption in browser. For improving random number generator we collect entropy from user actions and  sensors.

**Comment by charlag** [comment]
Asymmetric cryptography is used to secure the symmetric key with which the email itself is encrypted. It is decrypted from RSA only once after receiving (because it is slow) and re-encrypted using your symmetric key. See https://tutanota.com/blog/posts/innovative-encryption

**Comment by BigEgret** [comment]
Hello, thank you for your answer, but I am still a little confused: how to guarantee the security of private key encryption in the browser?

**Comment by charlag** [comment]
@BigEgret please, be more specific. Algorithm implemented in browser does not differ from the one implemented in C. The only significant different is random number generator.

**Comment by BigEgret** [comment]
@charlag  When you send a message, you encrypt the message with the private key but you encrypt the private key on the web side and someone else can still crack it, after all the web side is very easy to crack, the code is available to everyone else how do you secure the private key on the web side?

**Comment by charlag** [comment]
@BigEgret you can use apps instead or one of the unofficial desktop wrappers if you're worried about the browser but your claims are not supported with anything
