### ISSUE TITLE
UI Changes for Subfolders

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#4980]
We have a few UI changes that need to be made in regards to subfolders.

Changes to Make:
- [ ] Have hover area cover whole row
- [ ] Have padding around icon be even (have space between the edge and the icon match the space between the icon and the text)
- [ ] When in edit mode, icon button and folder button should be disabled (meaning, they should not show hover state since you cannot interact with them)

Changes to Try (some of these individually might cancel out others if implemented, so find the best combination):
- [ ] Have icons be large, but use their outlined version
- [ ] Align icon vertically to the base line of the folder name
- [ ] Move hierarchy line coming down from icon to the right a bit
- [ ] Make the + part of the clickable area to expand the folder
- [ ] Move the + to the lower left corner
- [ ] Use ionicon 5 Trash icon for trash folder
- [ ] Use ionicon 5 shield icon for the spam folder

**Comment by nokhub** [comment]
When dragging an email to a folder the cover area does not cover the whole row. Is that something we should fix?

**Comment by wrdhub** [comment]
I noticed this too, and I am not sure. The dragging logic is in the nav button, which usually also drives the bg color on hover. But to cover the other elements on the row, the hover logic there is done by a wrapper. Having the drag also cover the whole row would mean passing that dragged state back up, which isn't possible right now.

All that to say, I think it would be better if it could but I don't think it is worth it. Do you think that it's bad enough that it has to or is it okay as is?

**Comment by nokhub** [comment]
I don't think that this is really necessary, at least not at this stage. I will mark this issue as tested.
