### ISSUE TITLE
save password is not persistent PopOs 22.04 LTS

### ISSUE THREAD

**Issue by imlinstress** [tutao/tutanota#4982]
After installing Tutanota Client and login in, i 'm asked to enter password everytime i check my E-mails. Ticking the box "save password" is not persistent.

**Comment by a7x-bit** [comment]
Have you tried appImage? I had similar issues, just reverted back to appImage. No issues with passwords.

**Comment by imlinstress** [comment]
It works! Thank you for the suggestion!

I was using the  flatpak version from the Pop-Shop.
