### ISSUE TITLE
Attachments not possible to open, download or upload

### ISSUE THREAD

**Issue by andreasmjg** [tutao/tutanota#4985]
- [ x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x ] I've searched and did not find a similar issue.

**Describe the bug**
I cannot attach any file, download any attachment, or open any attachment in the Tutanota Desktop app. Everytime I need to handle attachments, I must log in via the web interface. 

**To Reproduce**
Steps to reproduce the behavior: Try to download/upload/open an attachment. ==> If I upload it loads until I restart the application, or the download window will close but no file is saved anywhere. 

**Expected behavior**
Download file into expected folder, upload atachment

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubunto 20 LTS
 - Desktop Environment, if applicable (on Linux): Default / Gnome
 - Version: default

Client: linux
Type: PREMIUM
Tutanota version: 3.106.4
Timestamp (UTC): Sun, 15 Jan 2023 14:45:01 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.4 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36

**Additional context**

Perhaps related to https://github.com/tutao/tutanota/issues/1923 ?

**Comment by ganthern** [comment]
Hey andreasmjg,

if you didn't yet, it may be helpful if you could get your device logs after trying to open or upload an attachment to us. You can either attach them here or send them to the support mailbox. It also helps us determine if there's a specific problem with your account that we can do something about.

Thank you!

**Comment by ganthern** [comment]
We had some problems with the desktop client and attachments, but those should be resolved now. 

Feel free to comment if you experience this.
