### ISSUE TITLE
Mailbox to select as receiving mailbox in contact form can be hard to select

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5014]
When I select the receiving mailbox in a contact form we only show the sender name of the main address of that mailbox. If that name is used for multiple users you can not know which one to select.

How to reproduce:
1. Create multiple users with the same name.
2. Create a contact form and open the receiving mailbox selection.
-> We only see entries with the same name
Expected: It is possible do distinguish the mailboxes, e.g. by email address. Could be at least in the tooltip.

**Comment by vaf-hub** [comment]
We do not support contact forms anymore.
