### ISSUE TITLE
External login view is broken

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5031]
* send an external mail
* click on the link in the notification
* see various errors before and after login

![image](https://user-images.githubusercontent.com/29049728/214046657-1ec1f645-fadc-4301-a361-eb58faef13f2.png)

## Test notes
 - [ ] Make sure external mailbox can be logged into and it shows no errors after selecting an email
 - [ ] Make sure you can switch between folders with 1-6 keys, in both external and internal mailboxes
 - [ ] Make sure delete/archive actions via buttons and shortcuts still work
 - [ ] Make sure back button on android works correctly: returns from other views to mailbox, from mail to folder and then inbox, from inbox it quits
 - [ ] On Android clicking on a notification should take you to the relevant mailbox

**Comment by nokhub** [comment]
Neither when the app is opened in the background nor when it is closed the notification will take you to the relevant inbox
