### ISSUE TITLE
Calendar events reserve too much space in month view

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5041]
In the screenshot below there are three events in one day. They should all be displayed but only displayed with bigger screen size:

![Screenshot from 2023-01-25 15-15-21](https://user-images.githubusercontent.com/3099142/214586652-4a71b146-a8ba-4bca-adcf-8673a608a843.png)

![Screenshot from 2023-01-25 15-17-00](https://user-images.githubusercontent.com/3099142/214587065-130e99dc-dcfc-44a4-8d02-fc670eb67dc2.png)

**Comment by clemisch** [comment]
Please don't switch to "dot view"! My phone is easily large enough to sensibly display the event with its title. 

I would like to advocate for a more compact presentation of the current implementation. The font and overall size of an event is quite large and only a few letters are visible. In contrast, e.g. [Google Calender](https://thesweetsetup.com/wp-content/uploads/2020/01/iphone-calendar-picks-google-calendar.png) looks a lot more useful IMHO.

**Comment by rezbyte** [comment]
It seems to be alright in the current version of the calendar.
