### ISSUE TITLE
Delete key stops working after clicking on a link

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5050]
> If I read a list of emails, I use the Delete button on the keyboard to go to next one. However if I click a link (or, right click - open in background) in the email, the keyboard Delete function is deactivated and I have to go back to the mouse to click to the Delete icon on the screen.

## Test Notes:
- [ ] open a link in a new tab (ctrl + click) -> make sure that shortcuts still work
- [ ] login to repetitivecalendar@tutanota.com -> go to folder 1 -> open mail with subject "all forms"
  - [ ] click each input field and make sure, that shortcuts don't work
  - [ ] tab to the button at the bottom and make sure that shortcuts work when it's focused

### Regressions:
- [ ] click around without interacting with any HTML elements of an email body and make sure that the shortcuts work

**Comment by charlag** [comment]
* Binding another key works
* Dispatching the event via devtools also works

**Comment by nokhub** [comment]
For me no shortcut at all works if I open a link in the background or open it normally and go back to tutanota again. After clicking somewhere on the website it seems like that it gains focus again and the shortcuts are working.

Also `document.addEventListener('keydown'...` will not get called after a link was clicked, no matter which key you press.
When clicking a link on Github, pressing "/" afterwards works fine and leads you to github's searchbar. The "/" shortcut is hijacked from the browser and I'm not sure yet whether this makes the difference.
