### ISSUE TITLE
Clarification for conversation view part 2

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5052]
* This step is possibly optional. Do we want to do this?
* Can individual emails in conversation be moved to a folder, or does whole conversation need to be moved together?
same for trashing and deleting
* Conversation item shows latest or received entry? Should be the lastest received entry
* Forwarding?
* List: what data to display? Subject? Participants?
* Number of emails in conversation is displayed?
* maybe unread ones?
* What to display in the list of mails/converastions in the sent folder?
* Trash folder?
* Viewer: which actions apply to the whole conversation?
* Viewer: where does the scroll point start?
* VIewer: which emails are expanded
* Viewer: when and what do we mark as read?
* Viewer: do we display unread status for mails? How?
* Search: when opening conversation in search which email do we scroll to/expand?
* Scroll to the first matching one?
* Should we show how many emails match
* Should move between matches?

**Comment by MasterInQuestion** [comment]
[ Q:
    Can individual emails in conversation be moved to a folder, or does whole conversation need to be moved together? Same for trashing and deleting. ]

    [ A:
    Save location of the email shouldn't affect the generation of Conversation.

    Simple explanation on the parsing of Conversation:
    .
    All emails:
    |1| with title matching the specific pattern /<a href="https://regex101.com/?regex=^(?:(?i:Re):%20)?%24{Title}%24&flags=">^(?:(?i:Re): )?${Title}$</a>/ [1], and
    |2| from the identical sender
    ; could be considered a Conversation.
[1] "Re" in other languages may be also considered.

    Trashed are still accessible, thus may be displayed (potentially differently).
    Deleted emails no longer exist. ]

**Comment by AlbertoFabbri93** [comment]
I like the conversation feature of Tuta but I find weird and unintuitive that deleted emails are still shown inside a conversation, at least until they are deleted forever. Can we have an option to change this behavior?

**Comment by MasterInQuestion** [comment]
Trashed emails in Conversation should be displayed differently:
    Border/Background color distinction of the conversation box should suffice.
    And trashed ones should be default folded (collapsed).

**Comment by AlbertoFabbri93** [comment]
I didn't realize it right away so for me it wasn't that obvious, but I can live with it

**Comment by wrdhub** [comment]
We've answered these questions, ready to do work on it
