### ISSUE TITLE
Uncaught Error: EBUSY: resource busy or locked, unlink offline.sqlite

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5063]
~~Started in 3.108.10:~~ No, has been a thing for longer, but is probably amplified by our more aggressive odb deletion policy.

```
Client: win32
Type: FREE
Tutanota version: 3.108.10
Timestamp (UTC): Mon, 30 Jan 2023 14:02:10 GMT
User agent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.108.10 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
Error
Error message: EBUSY: resource busy or locked, unlink 'C:\Users\pfft\AppData\Roaming\tutanota-desktop\offline_NEm-M6k----9.sqlite'
Stacktrace:
Error: EBUSY: resource busy or locked, unlink 'C:\Users\pfft\AppData\Roaming\tutanota-desktop\offline_NEm-M6k----9.sqlite'
```

* Probably has something to do with our "lifecycle improvements" to the offline db.
* https://github.com/tutao/tutanota/pull/4916 specifically ce8df5d304a5ae6def2e0f7d4f2ff8b739482895
* this is distinct from #2113 

## Workaround
Delete saved credentials & log back in.

**Comment by ganthern** [comment]
We've decided to fix the issue that causes the client to repeatedly recreate the db ([#5044](https://github.com/tutao/tutanota/issues/5044)) and attach logs to the error reports to get insight into this one, because we can't figure out why we're still (or again) holding a handle to the sqlite file when we try to delete it.

**Comment by ganthern** [comment]
Still happens a lot, I expect that it has something to do with 
* having a single-user installation and updating to all-users or the other way around.
* having two instances of the app running (maybe compounded by the above). Some user that had this several times assures us there's only one running though.

**Comment by bedhub** [comment]
User comment that might be helpful to reproduce the case:

"Error occurred when changing the password within Desktop client from"

**Comment by charlag** [comment]
We should try reproducing the scenario with both user & global versions running at the same time.

1. Install app as a user-only
2. Receive an update  and select global install
3. See if the error is shown on login
