### ISSUE TITLE
It's not possible to move any drafts into subfolders of the Drafts folder.

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5067]
Apparently, we forgot to extend the check for subfolders of the allowed location.

## Test Notes
- [ ] Draft mail can be moved into the draft folder or any of its descendant folders
- [ ] Draft mail can be moved into the trash folder or any of its descendant folders
- [ ] Draft mail cannot be moved into any other folder or descendants of those folders
- [ ] Other mail cannot be moved into the draft folder or its descendant folders
- [ ] Other mail can be moved into any other folder or descendants of those folders

**Comment by nokhub** [comment]
too me it seems like every mail/ draft can moved be everywhere

**Comment by wrdhub** [comment]
Yes, sorry. We changed what we wanted to do after I wrote those Test notes. I will update them
