### ISSUE TITLE
Make the name/sender name settings more clear

### ISSUE THREAD

**Issue by mrx23dot** [tutao/tutanota#5080]
- [ x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x ] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
set 'Name' is not displayed on email receiving side

**To Reproduce**
1. Go to https://mail.tutanota.com
2. set settings/email/Name  to XY
3. send an email to e.g. gmail 

**Expected behavior**
in gmail I would expect the email to show up as 
**XY <email_addr>**

but it shows up as:
**email_addr <email_addr>**

thus tutanota doesn't fill name from settings in email meta data.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser firefox
 - Version latest

## Test Notes
* [ ] The Folder column in the mail view shows the currently selected sender mail address when it is rendered
* [ ] the default sender can still be changed and affects the mail editor
* [ ] the default sender selector shows the current sender name and sender address
* [ ] the default sender dropdown shows only addresses
* [ ] there is no "Name" field in the mail settings

**Comment by charlag** [comment]
"Name" is user name, sender name is not configured per email address.
Will keep it as a usability bug.
