### ISSUE TITLE
Pasting images into mail editor does not work

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5083]
1. Right click some image in the web and copy image (the image itself)
2. Open mail editor and try to paste the image
3. Nothing happens

## Test Notes
* [ ] check that pasting works in chrome, firefox, safari and in ios (if possible, not sure if we can even copy image data there)
* [ ] test all editing/formatting functions of the mail editor
* [ ] check that autolinking still works
* [ ] also test external images
* [ ] check that the autoresponder editor and custom signature editor work as expected

we should keep an eye on https://github.com/tutao/tutanota/issues/4960 and see if it still occurs with the new squire

**Comment by ganthern** [comment]
did this work before? what's the expected behaviour? I guess attaching it as an inline image?

**Comment by charlag** [comment]
Depends on how OS gives us to us inline image might be an option. It is just very confusing from the user perspective. I don't think it worked before but I doubt it's fully intentional either and is at least usability bug.

**Comment by ganthern** [comment]
> is at least usability bug.

definitely, if it's possible at all we should look into it

**Comment by bravedave** [comment]
is this just a documentation issue

the code has a pasteImage event and a insertImage function which supports a base64 string as source

pasteImage is not mentioned and insertImage says the string must be a path - but the code supports a base64 string as source

so ... if you want to paste an image from the clipboard...

```javascript
let editor = new Squire(node);
editor
   .addEventListener('pasteImage', function(e) {

      let payload = [...e.detail.clipboardData.items];
      payload = payload.filter(i => /image/.test(i.type));
      if (!payload.length || payload.length === 0) return false;

      let reader = new FileReader();

      // use squire's insertImage on data load
      reader.onload = e => this.insertImage(e.target.result);

      // read image as Base64
      reader.readAsDataURL(payload[0].getAsFile());
   });
```

**Comment by Rubber-Duckie** [comment]
Still does not work. This works in every other email service I use. This needs top priority. Basic JavaScript skills required.

Firefox 113.0.1 (64-bit) + windows 10

Attempt to paste an image from clipboard. It shows the image in the email. But on send, the image is lost.

All it does is result in bazaar placeholders but no image is embedded. Funny, even git hub manages this just fine.

Example below;
![image](https://github.com/tutao/tutanota/assets/81572091/4b8d4b49-e5b9-4e63-80ab-f3daba6d01dc)

**Comment by bravedave** [comment]
What do you use for sending the email ? (E.g PHPMailer)

**Comment by ganthern** [comment]
@Rubber-Duckie works fine for me on the desktop client and firefox, tested linux and windows 10 with internal and external mail. please check your setup, and cut the passive aggression.

@bravedave how is this relevant to the issue?

**Comment by bravedave** [comment]
I picked up on the comment _It shows the image in the email. But on send, the image is lost._

Images, I believe, need to be converted to cid attachments - so that's a server side process, I use PHPMailer and have to do a save to disk, attach and cid replace (I think bit rough, working from memory there)

**Comment by fraschm1998** [comment]
Why was this issue closed? I'm encountering this issue with the latest tutanota desktop client on macos
