### ISSUE TITLE
Invalid DB state after unsuccessful login

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5094]
For 3.108.12 we have a number of reports like

```
ProgrammingError
Error message: Already opened database for user [USERID] when trying to open db for [USERID]
```

In the attached logs we always see either of

```
 Error message: Trying to do a network request with encrypted entity but is not fully logged in yet, type: GroupInfo,"LoginIncompleteError: Trying to do a network request with encrypted entity but is not fully logged in yet, type: GroupInfo\n    at Ka._validateAndPrepareRestRequest (asset://app/worker.js:1:29814)\n    at async Ka.load (asset://app/worker.js:1:25084)\n    at async Na.load (asset://app/worker.js:1:17451)"
```

```
 Error message: Trying to do a network request with encrypted entity but is not fully logged in yet, type: MailFolder,"LoginIncompleteError: Trying to do a network request with encrypted entity but is not fully logged in yet, type: MailFolder\n    at Ka._validateAndPrepareRestRequest (asset://app/worker.js:1:29814)\n    at async Ka.loadRange (asset://app/worker.js:1:25702)\n    at async Na.populateNewListWithRange (asset://app/worker.js:1:19941)\n    at async Na.loadRange (asset://app/worker.js:1:19504)"
```

It seems like database is in the odd state where we have enough information to think we can do an offline login but it fails at a certain point, probably `PostLoginActions` (seems like it might be `MailModel#init()` in some cases). If `PostLoginActions` fail we won't move past the login screen but we won't reset the login state on the worker side. Next time we try to log in we will get an error that offline db is already opened and probably will proceed with ephemeral database.

At the very least we should treat an error during `PostLoginActions#onPartialLoginSuccess()` as a login failure and reset the login state. Ideally we would also find out why the database is only partially populated and how to reproduce it.

A workaround for now is to tell users to delete their credentials but this issue can happen again and we should prevent it.

## Test notes
 - [ ] Check login in browser
 - [ ] Check login with new credentials in desktop client
 - [ ] Check login with existing credentials with free account in desktop client
 - [ ] Check login with existing credentials with free account in desktop client failing due to offline and then succeeding when the network is there
 - [ ] Check login with existing credentials with premium account
 - [ ] Check login with existing credentials with premium account being offline and then coming online
 - [ ] Check going offline in browser after login but before mail model is initialized (slow down network) and that the mail model is re-initilized correctly with network if we switch to calendar and back to mail

**Comment by charlag** [comment]
Another approach to partial login reset could be using `LoginListener#onPartialLoginSuccess()` to initialize `LoginController` but it creates circular dependency between the two unless we add a listener dynamically somehow.

**Comment by ganthern** [comment]
after clicking the "refresh" banner in chrome when going from 3.109.0 -> 3.109.2:

```
Feedback v3.109.2 - TypeError - UNKNOWN - Browser

 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.109.2
 Timestamp (UTC): Mon, 13 Feb 2023 08:49:58 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
TypeError
 Error message: Cannot read properties of undefined (reading 'indexState')
Stacktrace: 
TypeError: Cannot read properties of undefined (reading 'indexState')
    at new SearchBar (https://test.tutanota.com/search-c88bbd1f.js:1:26268)
    at https://test.tutanota.com/main-0151844f.js:1:112080
```

**Comment by charlag** [comment]
@ganthern we get this error reported a bunch! I could not reproduce it so far woo

**Comment by ganthern** [comment]
made a thing for it, I think we did not have one before: https://github.com/tutao/tutanota/issues/5121

**Comment by ganthern** [comment]
* Cut Network 
* log in with saved free credentials 
* wait a bit
* re-engage network
* get error:

```
Feedback v3.109.2 - ProgrammingError - UNKNOWN - linux

 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.109.2
 Timestamp (UTC): Mon, 13 Feb 2023 10:59:30 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.109.2 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
ProgrammingError
 Error message: Already opened database for user NMT8y0s----0 when trying to open db for NMT8y0s----0!
Stacktrace: 
ProgrammingError: Already opened database for user NMT8y0s----0 when trying to open db for NMT8y0s----0!
    at My.openDb (/tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:13:119010)
    at zl.dispatch (/tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:1:533860)
    at Jl.dispatch (/tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:1:536378)
    at ipc (/tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:1:526872)
    at yn.handleMessage (/tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:1:45258)
    at /tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:1:44373
    at /tmp/.mount_tutanoAZBjVZ/resources/app.asar/desktop/DesktopMain.js:1:519408
    at node:electron/js2c/browser_init:2:97569
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81082)
    at EventEmitter.emit (node:events:513:28)
```

**Comment by charlag** [comment]
@ganthern should we open a dev bug about this?
