### ISSUE TITLE
Edit folders done button hidden

### ISSUE THREAD

**Issue by lunaaisdead** [tutao/tutanota#5118]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

When editing the folders on the iPhone 14 pro max the done button is hidden behind the dynamic island.

**To Reproduce**
1. Click on the hamburger menu.
2. Click on the pen next to ‘your folders’

**Expected behavior**

The done button should be visible, probably fixable by putting it further down.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro max
 - OS: IOS 16.3
 - Version 3.108.12

**Additional context**

**Comment by ganthern** [comment]
https://github.com/tutao/tutanota/issues/5048
