### ISSUE TITLE
Adding inline images does not work

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5157]
1. Open mail editor
2. Expand editing bar
3. Click on inline image button and select an image
4. See that the image is added as an attachment but is not inserted into the mail body 

# Test Notes
* [ ] inline images in desktop client work now
* [ ] still work in browser
* [ ] removing them also works
* [ ] sending & downloading them also works

**Comment by Rubber-Duckie** [comment]
Still does not work. This works in every other email service I use. This needs top priority. Basic JavaScript skills required.
