### ISSUE TITLE
Stored credentials are not updated after changing password

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5166]
When you change the password on one client, stored credentials on all other clients are not updated after the first login. The user is prompted for a password each time. 

This affects all platforms.

## Test Notes:
* [ ] Premium Account
  * [ ] login on two devices, both with stored credentials
    * [ ] change credentials on one of the two devices
    * [ ] you should get logged out of the second device
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] you are prompted to type in the new password and can use the mailbox afterwards
    * [ ] log out
    * [ ] when you log in again you are not asked for credentials again and everything works fine
  * [ ] have stored credentials on two devices but only be logged in on one device
    * [ ] change password on the device where you're logged in
    * [ ] shows same behavior like above
  * [ ] use an account that has a second factor registered and store credentials on two devices
    * [ ] you can change the password without being prompted to use the second factor
    * [ ] on the other you are prompted to use the second factor FIXME
  * [ ] login on two devices, both with stored credentials
    * [ ] change credentials on one of the two devices
    * [ ] you should get logged out of the second device
    * [ ] deactivate internet connection
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] offline login works fine
    * [ ] activate internet again
    * [ ] try to reconnect and you are prompted for the password again FIXME
* [ ] Free Account
  * [ ] login on two devices, both with stored credentials
    * [ ] change credentials on one of the two devices
    * [ ] you should get logged out of the second device
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] the credentials are deleted completely
    * [ ] the mailbox works after you have logged in again
  * [ ] have stored credentials on two devices but only be logged in on one device
    * [ ] change password on the device where you're logged in
    * [ ] shows same behavior like above
  * [ ] use an account that has a second factor registered and store credentials on two devices
    * [ ] you can change the password without being prompted to use the second factor
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] the credentials are deleted completely
    * [ ] the mailbox works after you have logged in again and were prompted for the second factor
 * [ ] External Login
   * [ ] when the tutanota sender changes the shared password and sends a new mail, the old external login link does not work anymore (no login attempt possible)
   * [ ] if the password is changed (and new mail is sent) while logged in, the external user can keep using the mailbox until they log out, then the outdated link message is shown

## Regressions
* [ ] the phishing/spam banner still works
* [ ] the phishing/spam banner does not show tutanota.com links for non-admin whitelabel users
* [ ] creating more calendars works for premium only
* [ ] sending calendar invite still works
* [ ] calendar event popup still shows the bell icon for alarms
* [ ] creating users works
* [ ] creating aliases works
* [ ] creating contacts works
* [ ] in single-column mode, the bottom nav only shows the calendar/contact/search buttons for internal users
* [ ] the progress bar in the header works as expected when syncing
* [ ] header shortcuts (contact/calendar etc) work, but only while logged in
* [ ] contact form requests and login work
* [ ] recovering a login works with recovery dialog and for resetting the 2nd factor
* [ ] editing the custom external notification mail for whitelabel still works
* [ ] inbox rules are still applied and can be edited
* [ ] password strength indicator still works (try using the user's name, mail address, ....)
* [ ] out of office notifications work as expected
* [ ] trying to use a business feature (like adding a template group) shows the business upgrade dialog on plain premium
* [ ] we can open the mailbox from a mailto link or a notification in desktop
* [ ] calendar opens from an alarm notification
* [ ] search for longer than the 30 days (?) still requires premium
* [ ] the search overlay only shows the "change time period" text to premium
* [ ] adding groups works
* [ ] displaying the recover code works
* [ ] appearance settings are applied from the users account info
* [ ] signature can be edited and is applied
* [ ] global settings view loads fine
* [ ] sending/accepting calendar share works
* [ ] purchasing / redeeming gift cards works
* [ ] premium/free/business signup works
* [ ] deleting an account works, with takeover
* [ ] templates can be edited and applied

**Comment by wrdhub** [comment]
During testing: When you change the password on an ipad, the entire app closes and when opened again the credentials are not saved and it brings you to the login screen.
