### ISSUE TITLE
Unable to add security key U2F - Chrome 68.0.3440.106

### ISSUE THREAD

**Issue by xyxzxyz** [tutao/tutanota#517]
Unable to add security key e.g. Yubikey Nano, Yubikey Neo on website. First it will say it has been recognized but then when I try to save the key, it will say "Your security key has not been recognized". Tested with Yubikey Nano and Neo. both gave same error.

<img width="303" alt="2018-08-11 15_51_10" 
src="https://user-images.githubusercontent.com/22533296/43996753-7fc2a2d8-9d7e-11e8-9537-b324c1e13ec7.png">

**Comment by mpfau** [comment]
Can't reproduce this on Linux with Chrome 68.0.3440.75 and Yubikey Neo.

Which Yubikey, operating system and version are you using?

**Comment by xyxzxyz** [comment]
Windows 10 Pro v1803, Build 17134.165, Yubikey Neo and Yubikey Nano.

**Comment by xyxzxyz** [comment]
I reset Chrome, still no go.

**Comment by xyxzxyz** [comment]
I do not think this has anything to do with Chrome version. I downgraded Chrome to 67, problem persists. Tried a different machine, still same error. Tested my keys on other Yubikey supported websites such as Google, Fastmail, Github, Dropbox, they have no problem adding my Yubikeys, so far only Tutanota couldn't add them. I will try to add them on my Linux box and see if it works.

**Comment by charlag** [comment]
@xyxzxyz thanks for testing, I don't know how tech savvy you are regarding programming but maybe you could build the app and debug it? It would be really hard for us to solve this without being able to reproduce it. Even symptoms or logs could help
