### ISSUE TITLE
Owner name of shared calendar shown instead of calendar name

### ISSUE THREAD

**Issue by starsep** [tutao/tutanota#5172]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I have shared calendars. The person used to see names of shared calendars. Now they see my name instead.

**To Reproduce**
1. Go to calendar
2. Add event
3. Click calendar select
4. See calendar labels

**Screenshots**
![image](https://user-images.githubusercontent.com/2798728/221058469-494b0ff4-dd79-4cd4-8d91-ead991d49382.png)

**Comment by ganthern** [comment]
This looks like https://github.com/tutao/tutanota/issues/4977 

Can you confirm which client version the person seeing this is using?

**Comment by starsep** [comment]
It works now. Perhaps app has been updated in the meantime
