### ISSUE TITLE
Templates appear multiple times in list view

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5173]
Template items appear multiple times in the list after loading more entries.

To reproduce

 * Have a template list with more then 200 entries
 * Go to settings and open the template list
 * Scroll to the end of the list to load them all
 * -> error templates show up multiple times and when one item is select all of them are selected.
 

![Screenshot from 2023-02-24 10-46-13](https://user-images.githubusercontent.com/8296817/221146940-6b2e1460-9cda-4044-bbc4-0a7b246b5ca3.png)

## Test Notes:
* [ ] knowledgebase
  * [ ] check in freecookies that the lists in the two Knowledgebases are rendered correctly
  * [ ] check in repetitivecalendar that the knowledgebase list shows approximately 210 entries
    * [ ] there are no duplicates
    * [ ] all elements seem to be present
    * [ ] they are sorted in alphabetical order
    * [ ] scrolling through the list works without lagging
  * [ ] it is possible to add new entries to the knowledgebase
    * [ ] they are rendered correctly after adding and also appear after new login
  * [ ] it is possbile to delete entries
    * [ ] they are removed after deleting and also don't appear after new login
  * [ ] it is possible to edit entries
    * [ ] they are rendered correctly after editing and also after new login
  * [ ] the knowledgebase can be accessed from the mail editor
* [ ] templates
  * [ ] check in repetitivecalendar that the template list show approximately 250 entries
    * [ ] there are no duplicates
    * [ ] all elements seem to be present
    * [ ] they are sorted in alphabetical order
    * [ ] scrolling through the list works without lagging
  * [ ] it is possible to add new entries to the templates
    * [ ] they are rendered correctly after adding and also appear after new login
  * [ ] it is possbile to delete entries
    * [ ] they are removed after deleting and also don't appear after new login
  * [ ] it is possible to edit entries
  * [ ] they are rendered correctly after editing and also after new login
  * [ ] the templates can be accessed from the mail editor

**Comment by kibhub** [comment]
The issue persists. 

Scrolling down keeps loading more duplicates of the templates.

**Comment by nokhub** [comment]
my bad, I have confused the knowledgebase with templates. So it was actually also an issue for the knowledgebase and not only for templates. But I will also fix that for templates.
