### ISSUE TITLE
Adapt material you (android app)

### ISSUE THREAD

**Issue by ViktorKahu** [tutao/tutanota#5183]
Perhaps it's time to start listening to your users (especially the paying ones) and implement changes to UI colours.

Everyone understands that the first and foremost purpose of tutanota is secure and private email services and this has been discussed previously, however, looking at a white screen during dark hours, is hard on the eyes. Likewise, looking at a dark screen during daylight is also not great. Manually switching the theme two times per 24 hours is an extremely inconvenient way to live life.

Best case scenario would be if Tutanota implements material you principles. Material you is here to stay and the sooner Tutanota gets with the times, the better. Otherwise, you are at a risk of being left behind and the longer you leave it, the harder it will be to catch up.

If you guys are hell-bent against material you, at the very least give us an option to follow the system theme with your own implementation of a light and a dark mode.

Regards,

Tutanota user.

**Comment by ganthern** [comment]
I'm not sure if this is about more than #3006

**Comment by ViktorKahu** [comment]
It is about more because I mention Material You support as a best case scenario, and the issue you mentioned as a fall-back.

Also, I do understand that  the developers are busy and everything, but the issue that you mentioned is from 2021. It is already 2023 and we are not even slightly closer!

I assume the issue is open but it's in the "ignore basket".

This saddens me deeply.

**Comment by ViktorKahu** [comment]
Developers, 

Unfortunately, based on previous experience and fear that this will get ignored AGAIN for years to come, can you please set a milestone and commit to resolving this issue within a reasonable time frame?

**Comment by ganthern** [comment]
Viktor,

we've been reordering the roadmap picking up issues and features that got a lot of reactions from our users, as well as actively including recommendations and observations from our support team.
#3006 has several reactions and bothers our developers (who are also users) as well, but at the moment it can't compete with some other things, including conversation view.

I'd also like to remind you that this is not a forum for feature requests, which the template you deleted when creating this issue informed you of. 

Respectfully,
N

**Comment by mannp** [comment]
Its a shame in 2023 to see that basic functionality for people with accessibility issues have to compete with nice to haves of the majority.

**Comment by ViktorKahu** [comment]
> Viktor,
> 
> we've been reordering the roadmap picking up issues and features that got a lot of reactions from our users, as well as actively including recommendations and observations from our support team. #3006 has several reactions and bothers our developers (who are also users) as well, but at the moment it can't compete with some other things, including conversation view.
> 
> I'd also like to remind you that this is not a forum for feature requests, which the template you deleted when creating this issue informed you of.
> 
> Respectfully, N

Well, that sort of attitude is disappointing to say the least.

Considering that we are asking for the very basic functionality here that even the most amature apps have, and it's been 2 YEARS of excuses so far, for you to turn around and say that it isn't planned is very surprising.

Why don't we just go all the way back to basics and use command prompt, that way you won't need to deal with any kind of UI at all. It will be secure, cheap and easy to develop...

In every single youtube review, your ui/useability/user experience is a negative point against your otherwise great app.

Are you guys honestly too blind and ignorant to see that greater useability = more paying customers...?

Unfortunately, you just lost another one.
