### ISSUE TITLE
Search field does not exist

### ISSUE THREAD

**Issue by prog-amateur** [tutao/tutanota#519]
Hello, I know that you have done a good job on app and web mail by adding a seach bar. 
On the android app, everything is fine, however, on desktop mail, I have used it for a while, but the field does not display anymore. I has disappeared. 

I am on a free account, and I use https://mail.tutanota.com 

Do you know why this happens ? 
Thank you

**Comment by charlag** [comment]
@prog-amateur hi! We don't display search bar when we cannot search - and we cannot do that if we cannot access IndexedDB. Which browser do you use? Is it incognito mode? Could some addon be the cause? If nothing of that, please, try resetting the website info and tell us if it helps.

**Comment by prog-amateur** [comment]
Hello, my OS is Linux, I am on Firefox, with Incognito Mode enabled, cookies from official websites are enabled. 
I have some addons  but I still reproduce the issue when they are disabled. 

Do you think Incognito Mode is the issue ? 
Maybe I don't use the good url (https://mail.tutanota.com/) ? 

Thank you

**Comment by charlag** [comment]
@prog-amateur yes, incognito mode is an issue. As I said, we cannot search when we don't have access to IndexedDB and FF with Incognito does not give access to IndexedDB
