### ISSUE TITLE
Emails not displayed when offline in browser

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5204]
How to reproduce:
1. Log in into an account in the browser.
2. Go offline
3. Select an email from the email list
-> The email is not displayed at all (not even sender, recipeint, subject etc.) but it shows "1 email selected." like in multi selection mode.
As soon as you view one email when online, this behavior can not be reproduced any more. Going offline again and selecting emails will successfully show the email in the email view (apart from the body if it was not loaded yet). When logging out and in again, then the behavior can be reproduced again when offline.

This only happens in the browser but not in the desktop client.

Reproduced in v3.109.11 in Firefox and Chromium on Ubuntu

**Comment by murilopereirame** [comment]
Seem to not happen anymore
