### ISSUE TITLE
There is no email contents.

### ISSUE THREAD

**Issue by seazzon** [tutao/tutanota#5214]
Support for old browser versions is stopped? 
Chromium v86 does not disclose the contents of all email.

Tutanota v3.109.13 web
Windows 7 32-bit, 10 64-bit
Chromium v86.0.4240.198 32-bit

![TT-02](https://user-images.githubusercontent.com/1830079/222391745-e2404e74-8a6a-4874-9e22-f37105b7029a.png)

**Comment by ganthern** [comment]
According to our browser support policy, Chromium v86 has not been supported for a while (https://tutanota.com/blog/posts/browser-support)

**Comment by charlag** [comment]
Duplicate of #5221
