### ISSUE TITLE
Splited architecture

### ISSUE THREAD

**Issue by nightznero** [tutao/tutanota#5220]
Helloz Guys,
Could You please share app like a split architecture?
v8 is 8mb,maybe it's not much but in proportion in this case it's half of size. After cleaning resources even less than 5mb.
Best regards!
![Screenshot_20230302_161705_MT Manager](https://user-images.githubusercontent.com/61750641/222470610-f320b569-2216-4722-bed2-8927bad4cfa8.jpg)

**Comment by charlag** [comment]
It will be covered by https://github.com/tutao/tutanota/issues/3243
