### ISSUE TITLE
Email Body Missing

### ISSUE THREAD

**Issue by Optomod** [tutao/tutanota#5221]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Message body does not load, tries to but then show three dots as of two releases "refreshs" ago.

**To Reproduce**
Load web version of Tutanota

**Expected behavior**
Message body does not load, tries to but then show three dots as of two releases "refreshs" ago.

**Screenshots**
![Screen Shot 2023-03-03 at 5 32 17 pm](https://user-images.githubusercontent.com/94802055/222631989-13ec11c7-dc27-4279-bf1f-8ed98bb897b7.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version [78.15

**Comment by ganthern** [comment]
Hey, Firefox v78 is quite outdated and outside of our Browser support policy. Please try updating your browser and let us know if the issue persists.

**Comment by kibhub** [comment]
Unfortunately I think that the issue affects modern browsers on moderns systems. However I was not able to reproduce it. 

There also have been reports of this happening on Android

**Comment by charlag** [comment]
@Optomod could you please send us logs via settings -> about to hello@tutao.de after it happens? We are struggling to reproduce it. Thank you!

**Comment by charlag** [comment]
We've checked the code and it can't really happen in normal circumstances that `click` event handler fails. We suspect there is an uncaught error during the rendering pass and lifecycle methods are not actually called but we haven't seen any uncaught errors in the logs.

So far from the error reports we've noticed few cases:
 - it is an old browser
 - it is in multi search viewer or after it
 - it is iOS 16.3

**Comment by charlag** [comment]
judging by #5214 this is what happens:
 - some error in a lifecycle hook, most likely `onupdate`
 - all errors are caught by mithril and logged, we don't get them in the error handler: https://github.com/MithrilJS/mithril.js/blob/88da9e56f92a4ee076a6a63ab7759fecb487e340/api/mount-redraw.js#L13
 - except mithiril bind `console` super early, before we replace it

so the end result is that the whole class of issues is invisible to us

**Comment by nikoPLP** [comment]
see my comment in a related issue https://github.com/tutao/tutanota/issues/5246#issuecomment-1464862970

**Comment by FlavioMala** [comment]
Now it is no longer possible to log in from my phone with SO UBports (Ubuntu touch)...
(I also opened an issue here, if helpful  :https://gitlab.com/ubports/development/core/morph-browser/-/issues/549 )

And there are no alternative browsers: I tried Onion browsers and others available on OpenStore... and also those that can be installed with Libertine (Midori, Firefox, etc.)

So it seems that now all those who have "UBports" phones can no longer access Tutanota!

Will it be when 20.04 (now UBports based on Ubuntu 16.04) is available Who knows? And it will take months…years… ?
Isn't an exception possible for UBorts?

Alternatively the only workaround that comes to my mind is to evaluate another email and leave Tutanota...

**Comment by xaur** [comment]
The fix in #5230 added CSS test `document.querySelector("blockquote:not(blockquote blockquote)")` which requires Selectors Level 4 implemented by the browser (according to [this article](https://developer.mozilla.org/en-US/blog/css-not-pseudo-multiple-selectors/))

> This is [supported in browser versions](https://developer.mozilla.org/en-US/docs/Web/CSS/:not#browser_compatibility) starting from Chrome 88, Firefox 84, and Safari 9.

It is fair to unsupport old browsers and not let them use the app. The only problem is it prevents login, and if you don't login for 6 months you lose the account. Ideally the more advanced compatibility checks would run after login to at least let older clients keep the account alive.
