### ISSUE TITLE
creating contact from email view doesn't work

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5232]
1. open an email
2. expand addresses
3. click on sender's address > create contact
4. save
5. go to Contacts
6. see contact missing

## Test Notes
* [ ] above reproduction results in a saved contact
* [ ] creating contacts from contact view still works
* [ ] creating contacts from mail editor still works
* [ ] creating contacts automatically when sending mail still works

**Comment by charlag** [comment]
Could not reproduce on 3.110.1, could you please confirm @kibhub ?

**Comment by kibhub** [comment]
> Could not reproduce on 3.110.1, could you please confirm @kibhub ?

I confirm. Also updated the description above. No error is shown but the contact isn't created.
