### ISSUE TITLE
Graphic bug in Chat View (mobile)

### ISSUE THREAD

**Issue by serrq** [tutao/tutanota#5235]
Two images, one above the other, are in conflict.

Determine which of the two bothers the other and eliminate the excess.

At first glance it would seem that the upper image was not supposed to be there. I personally think it’s too much.

Android 12 
OnePlus CPH2399 
Tutanota 3.109.13 (f-droid) 

![44927](https://user-images.githubusercontent.com/113377431/223667706-e1430253-6ad1-476c-8481-f66e5ae68d7a.jpg)

**Comment by charlag** [comment]
Will be irrelevant with [#5251](https://github.com/tutao/tutanota/issues/5251)
