### ISSUE TITLE
"New Template" button doesn't work on mobile

### ISSUE THREAD

**Issue by serrq** [tutao/tutanota#5236]
When clicked it doesn't do nothing.

Android 12
OnePlus CPH2399
Tutanota 3.109.13 (f-droid)

**Comment by charlag** [comment]
The button is covered by "no templates" message because it fills the list

**Comment by wrdhub** [comment]
## Test Notes
- [ ] Can click "New Template" on any platform (web, mobile, desktop) when there are no templates
- [ ] Can click "New Template" on any platform (web, mobile, desktop) when there are existing templates
- [ ] Can click on the corresponding button in other setting views (such as "Add User" in User management and "Create contact form" in Contact forms).
