### ISSUE TITLE
Cloned emails in conversation view when sending an email to myself.

### ISSUE THREAD

**Issue by seramm** [tutao/tutanota#5248]
This bug applies for the mobile version(Android), web version and Desktop.

**To Reproduce**
1. Send an email to yourself. E.g.: from `email1@tutanota.com` to `email1@tutanota.com`
2. In the inbox, when selecting the email, if you scroll up the same email appears in conversation view.

**Expected behavior**
Only one mail should be shown. A clone of the email is unexpected.

**Screenshots**
![image](https://user-images.githubusercontent.com/93453498/224306114-b8931c7e-d826-4a8c-b22f-cade4b440b8f.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Version: 3.110.0 (tutanota-desktop from AUR Repository)

**Comment by MasterInQuestion** [comment]
Perhaps related with [ [https://github<i>.</i>com/tutao/tutanota/issues/5052#issuecomment-1496373991](https://github.com/tutao/tutanota/issues/5052#issuecomment-1496373991) ]:
    |1| What should be considered a Conversation?
    |2| Is not which indeed 2 separate emails?
