### ISSUE TITLE
3.110.1 breaks Win7/8/8.1 compatibility

### ISSUE THREAD

**Issue by ask2018** [tutao/tutanota#5255]
Updating Electron to version 23 https://github.com/tutao/tutanota/issues/5238 breaks breaks Win7/8/8.1 compatibility
https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support

At the moment there is no workaround for this and 7/8/8.1 users cannot start application at all. It is possible to provide compatibility build with Electron 22 as temporary solution?

**Comment by charlag** [comment]
We haven't been supporting Win7/8/8.1 for a long time (if ever?)
