### ISSUE TITLE
wrong message when entering wrong TOTP code

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5258]
when I try to register a new TOTP authenticator and enter the wrong six digit code, I get the message: "Please enter the six digit code from your authenticator to finish setup"

## Test Notes
* [ ] the totp setup dialog now always shows the current status as a help label under the authenticator code field
* [ ] if the dialog is attempted to be confirmed while not having confirmed the correct code, the error is shown in a dialog
  * "please enter code" if the code is not there / not 6 digits
  * "code is wrong" if the code is there and 6 digits, but wrong.
  * nothing if the code is correct.

**Comment by ganthern** [comment]
the issue should be somewhere around here:

https://github.com/tutao/tutanota/blob/c7420e94fec20fc385682d144bd604778d715691/src/settings/login/secondfactor/SecondFactorEditDialog.ts#L217-L229

maybe we're not setting the failed status correctly
