### ISSUE TITLE
IOS Password clearing requiring relogin after closing application

### ISSUE THREAD

**Issue by anotheruserwhowantstohelp** [tutao/tutanota#5268]
**If this was written incorrectly, I do aplogize as it is my first time reporting a bug with GitHub, I tried my best to follow the rules stated bellow**

- [This is not a feature request] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [Yes, it seems that I have been the only one] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

When using Tutanota for IOS, everytime I close the app or remove it from my background task; password is cleared and requires login. Having setup BioMetrics as requested by the Tutanota team, without changing phone password nor updating facial ID, the password is still requested. 

My understanding (and non programmer guess) is that it could be a bug related to using the newst most stable version of IOS when paired with Tutanota. 

After reinstalling the program multiple times, restarting phone, no changes to how the app requests the password every single time. 

**To Reproduce**
1. Go to Tutanota IOS
2. Close application and remove it from background task
3. Open Tutanota once again
4. Requires password and 2fa login 

**Expected behavior**

When closing Tutanota or clearing from background tasks; once the application is reopened it should not request password and 2fa.

**Screenshots**

N/A just IOS login page.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone14ProMax]
 - OS: [e.g. iOS16.3.1]
 - Version [IOS v3.110.0]

**Additional context**

As mentioned at the first line, if this was a mistake of a report please let me know, I do aplogize once again if it was.

**Comment by kibhub** [comment]
Please make sure that you check the "Store password" box when you login. Otherwise, what you describe is the default intended behavior.

Please feel free to reopen the issue if this happens even with stored credentials.

**Comment by charlag** [comment]
Could this be a "new password" bug?

**Comment by anotheruserwhowantstohelp** [comment]
> Please make sure that you check the "Store password" box when you login. Otherwise, what you describe is the default intended behavior.
> 
> Please feel free to reopen the issue if this happens even with stored credentials.

Thank you, after reinstalling application, deleting creditnals and making sure store password was enabled the problem seems to have fixed. User error cited by me. Thank you!

**Comment by anotheruserwhowantstohelp** [comment]
> Could this be a "new password" bug?

Existing account since sept 22, password is changed every two weeks. No new password bug thankfully

**Comment by anotheruserwhowantstohelp** [comment]
Problem solved, no need for futher replies thank you!
