### ISSUE TITLE
day name wrong when exporting sent emails

### ISSUE THREAD

**Issue by vacantmood** [tutao/tutanota#5282]
- [ *] This is not a feature request (existing functionality does not work, **not** missing functionality).

- [ *] I've searched and did not find a similar issue.

exporter.ts line 170 daynames array starts with "mon", it should start with "sun"
**Bug in all versions

**Describe the bug**
see title

**To Reproduce**
export a sent email
examine the .eml file
the "date:" line has the wrong day name though the rest of the date is correct

## Test Notes
- [ ] Exported `.eml`s with a sent day of Monday appear as 'Mon' in the Date field.
- [ ] Exported `.eml`s with a sent day of Sunday appear as 'Sun' in the Date field.

**Comment by kibhub** [comment]
Was able to reproduce. The date is correct expect for the day name. It looks like it's always the name of the next day.
