### ISSUE TITLE
Tutanota Desktop has stopped working

### ISSUE THREAD

**Issue by macexpertsusa** [tutao/tutanota#5327]
- [yes ] I've searched and did not find a similar issue.

**Describe the bug**

a few weeks ago an update came through and since then the program crashes 'a problem has caused the program to stop working correctly. please close the program'

**To Reproduce**
launch the program 

**Expected behavior**
program runs

**Desktop (please complete the following information):**
 - OS: win 8.1

**Additional context**
i have uninstalled and reinstalled a few updates since and it still crashes on launch 
presently 3.111.0 (latest) crashes as well
have tried compatibility mode as an off chance it might help but no luck 
deleted the appdata as well in case of corruption but it still crashes after a fresh reinstall

the program has been running fine for the past year plus (from the beta time frame) until a recent update several weeks ago

**Comment by charlag** [comment]
Windows 8.1 is not supported by Microsoft and is not supported by us either
