### ISSUE TITLE
Uncaught Error: net::ERR_NETWORK_IO_SUSPENDED (and other node:net errors)

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5338]
**These only happen on linux**

> woke computer from suspend mode, error message was present on screen

```
Client: linux
Type: FREE
Tutanota version: 3.111.0
Timestamp (UTC): Mon, 03 Apr 2023 18:19:19 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.111.0 Chrome/110.0.5481.179 Electron/23.1.3 Safari/537.36
Error
Error message: net::ERR_NETWORK_IO_SUSPENDED
Stacktrace:
Error: net::ERR_NETWORK_IO_SUSPENDED
at SimpleURLLoaderWrapper.<anonymous> (../../../../home/rab/node:electron/js2c/browser_init:2:49386)
at SimpleURLLoaderWrapper.emit (../../../../home/rab/node:events:513:28)
```

this one should probably be safe to let the request fail and try again, similar to https://github.com/tutao/tutanota/issues/5336

---

```
Client: linux
Type: PREMIUM
Tutanota version: 3.111.0
Timestamp (UTC): Tue, 04 Apr 2023 16:18:26 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.111.0 Chrome/110.0.5481.179 Electron/23.1.3 Safari/537.36
Error
Error message: connect EHOSTUNREACH 2a10:e000:1::16:443
Stacktrace:
Error: connect EHOSTUNREACH 2a10:e000:1::16:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
```

## Test Notes
it should be enough to test this on linux.

* you will need a fixed test version of the desktop client that already has an update it can download
* you will also need an affected version of the desktop client ( =<  3.112.7)
* before each test, copy the executables (they overwrite themselves with the update)
* use the affected version to find a setup that causes the error while the terminal is showing the differential update download (slow down network to 0, pull cable, switch from wired to wifi, turn off VPN, reset router...)
* do the same with the fixed version

* [ ] no uncaught errors are visible and the update eventually succeeds

### Regressions
* [ ] update still works on windows
* [ ] update still works on mac

**Comment by charlag** [comment]
I'd say convert to offline error

**Comment by ganthern** [comment]
These are probably caused by this: https://github.com/electron-userland/electron-builder/issues/2398
