### ISSUE TITLE
Mobile layout used in Desktop app

### ISSUE THREAD

**Issue by ctrlvd** [tutao/tutanota#5349]
**Screenshots**
![Wire 2023-04-03 at 1_47 PM](https://user-images.githubusercontent.com/124799622/230360667-3e595f5d-624a-4c83-b5af-bf7acf4bf8d0.png)

**Desktop (please complete the following information):**
 - Version 3.112.6

## Test Notes
* [ ] the bug does not reproduce anymore (is there a way to slow locator.init() down reliably?)
* [ ] resizing is correctly applied in mail, calendar, settings, with a minimized editor
* [ ] rotating the app on mobile devices still changes the layout correctly

**Comment by kibhub** [comment]
I'm able to reproduce this issue but not 100% of the time, as I'm not exactly sure what causes it. Try the following to reproduce:

- have stored credentials
- open Tutanota > Login > see error or continue
- close Tutanota without any change to window size, location or zoom level
- close background process
- open Tutanota > Login > see error or repeat.
- error happens in 1 in 3 times at the most. It is often more frequent than this. 

Here's what I've found:

- happens on a fresh launch of Tutanota
- not related to window size
- not related to zoom level
- not related to `conf.json`

**Comment by charlag** [comment]
I think it is indeed a timing issue.

It seems like `WindowFacade` is only initialized after the locator & logins and if resize happens between creating the window and locator initialization we will miss the resize event.

I am not sure at all why `styles` even cached window size but we should at least call resize listeners once `WindowFacade` is initialized.
