### ISSUE TITLE
Dropdown filter issues

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5353]
* When a dropdown with filter is opened in the desktop layout (move mail with more than 10 folders), it's not possible to navigate down to the filtered list with the arrow keys, only with tab
* The same dropdown on mobile (at least android) does not open the keyboard, you have to tap the input before being able to type.
* for folders, it's also searching/matching the dots we use to show the nesting.

## Related:
https://github.com/tutao/tutanota/issues/4007

## Test notes
Try the move folder button for the mail for an example of a dropdown. There must but around 10 folders on the account to work.
- [ ] On Desktop/Web App
  - [ ] Pressing the down arrow after opening the dropdown causes the first item to be focused
  - [ ] Pressing the up arrow after opening the dropdown causes the last item to be focused
  - [ ] Pressing the up and down arrows after already having focused an item moves the focus to the previous and next item respectively.
- [ ] On Android and iOS:
  - [ ] The filter input is focused when opening the dropdown.
- [ ] On any:
  - [ ] Searching for a subfolder by name works
  - [ ] Searching for '.' with subfolders on the account returns nothing
  - [ ] Searching for '.' with subfolders on the account that include '.' in their names returns the subfolders

**Comment by charlag** [comment]
The description is not populated correctly, I'll submit a fix
