### ISSUE TITLE
Cannot open message with keyboard shortcut

### ISSUE THREAD

**Issue by krstp** [tutao/tutanota#5361]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
I can use other keyboard shortcuts (such as M), but when on-message I cannot open it even with ENTER. Provide keyboard shortcut to open messages.

**To Reproduce**
1. Go to 'Inbox' using `M` shortcut (for example from calendar `O`)
2. Center on message (UP/DOWN etc.)
4. Try to open with ENTER

**Expected behavior**
The message should open, but this is not what is happening. Other keyboard shortcuts work as expected.

**Screenshots**
Working in resized window:
![Resized_window](https://user-images.githubusercontent.com/4711498/231241762-57f82d0c-ecf6-4870-8701-3ed236515dea.png)

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Version 3.111.0 (3.111.0.374)

**Additional context**
I am not working in full window, but resized one to a smaller size for compactness.

## Test notes
Test on Firefox and Chromium in a window small enough to display the single-column view.
- [ ] Pressing the down arrow highlights the next row.
- [ ] Pressing `j` highlights the next row.
- [ ] Pressing the up arrow highlights the previous row.
- [ ] Pressing `k` highlights the previous row.
- [ ] Pressing enter opens the conversation view.
- [ ] Tabbing over a row highlights it.
- [ ] It is not possible to tab into the conversation view from the mail list.
- [ ] The transition animation between the mail list and the conversation view looks the same.
- [ ] In the contacts view, pressing tab on a row focuses the next row.

**Comment by murilopereirame** [comment]
Works fine! The only point that I found is:

If you use the arrows to navigate, take the focus out of the list, enter again using tab and start tabbing, if you use the arrows again, it'll do the move from the latest item before losing focus for the first time.
