### ISSUE TITLE
Display dates in ISO 8601 date/time format

### ISSUE THREAD

**Issue by gmejzej** [tutao/tutanota#5372]
**Describe the bug**
Clear presentation of date/time is an important factor for any messaging/communication platform, especially when communicating across diverse cultures. ISO 8601 is a standard for date/time presentation and Tutanota should adhere to this standard or at a minimum give users a setting that allows its enabling.

**To Reproduce**
1. The lack of standardized date is everywhere throughout Tutanota.
2. Contact birthdays are displayed MM/DD/YYYY (the disorganized USA presentation of putting the year after the day)
3. Calendar events display as MM/DD/YYYY as well
4. In email, Tutanota takes lots of space and it makes for sloppy presentation aesthetic to write "Fri, Apr 14 17:49." For shorter presentation during the week of, you could display "Today 15:29" or "Fri 13:45." After the current week, displaying the date as "2023-04-08 17:49" adds display of the year with minimal spacing and neatly lines up date/time presentation for all emails in a descending fashion leading to a professional look that intelligently organizes the display in a way that clearly and effectively communicates the date/time. It's much easier for a human to scan "2023-04-14 17:49" than scanning through "Mon, Apr 10 13:23", "Fri, Apr 7 00:20", "Wed, Apr 5, 05:10" and so on, especially when the content is presented in a chronological list like email is.

**Expected behavior**
I expect standardized date/time display that facilitates clear presentation and communication across multiple cultures for a professional, business quality communications service.

**Comment by charlag** [comment]
> My system locale is set to "en_DK.UTF-8" which uses ISO 8601 (e.g., 2023-12-08). But Tuta's app is not displaying my system locale. Should this accordingly be filed as a bug report on this issue?

feel free to open an issue but please specify which app, in which environment and where exactly in the app this happens

**Comment by MasterInQuestion** [comment]
I believe some new setting is needed:
    |1| Datetime preference of ISO 8601.
    [ ^ Reference: [https://github.com/orgs/community/discussions/5972#discussioncomment-10731225](https://github.com/orgs/community/discussions/5972#discussioncomment-10731225) ]
    |2| Explicit time zone preference. (just need to be UTC+/-Offset)

    Currently |1| seems to be directly binded to language settings. (changing not possible without affecting interface language? and probably no ISO 8601 specifically)
    |2| seems to just follow system.
