### ISSUE TITLE
External images are not preserved in the draft when not loaded

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5405]
**To Reproduce**
1. Open email with external images, do not load them
2. Reply
3. Change something, save the draft
4. Reopen the draft, external images are broken (not loaded, nor replaced)

## Test Notes
- [ ] The user see a banner in email view when the email contains external images and isn't allowed to load
- [ ] The user can show the images
   - [ ] If the user replies to the email after clicking in show, the mail editor prompt show the images
   - [ ] If the user saves the draft, when editing again, the image is there, if the user refresh the page they will be asked again to show the image
- [ ] The user can always show the images
   - [ ] If the user replies to the email after clicking in always show, the mail editor shows the image
   - [ ] If the user saves the draft, when editing again, the image will be there
- [ ] The user can always block the images
   - [ ] If the user replies to the email after clicking in always block, the mail editor doesn't show the image
- [ ] If the user doesn't select any option, a message is displayed at the mail editor asking to load external images
   - [ ] The user can load the images by clicking in show
   - [ ] The next time the draft is opened, the user is prompted again to load the images

### Regression test
- [ ] Sending a mail from scratch still working
- [ ] Replying emails with/without images still working
- [ ] Inline images works normally

**Comment by ganthern** [comment]
has been broken for a while, we'll fix it in one of the next releases. inline/external/cid handling is a bit of a mess atm and this should not hold up the release.

**Comment by murilopereirame** [comment]
Maybe we can store the image URL in a custom data property instead of just discard it and ask if the user wants to load the blocked content while editing the draft

**Comment by rezbyte** [comment]
The external images are not shown in the mail editor if you click show then create a draft reply to a forwarded email.

**Comment by rezbyte** [comment]
When opening a draft reply via the more button in the mail view, the images are displayed without prompting the user even if a show choice was not selected in the original mail.

**Comment by rezbyte** [comment]
When reading a draft reply in the mail view (conversation view) to an email with an always trusted sender, the images are not displayed.

**Comment by rezbyte** [comment]
> The external images are not shown in the mail editor if you click show then create a draft reply to a forwarded email.

This only occurs when forwarding an email to oneself & is not considered an issue.
