### ISSUE TITLE
Incorrect selection after moving emails

### ISSUE THREAD

**Issue by ctrlvd** [tutao/tutanota#5421]
**To Reproduce**
1. Select multiple emails
2. Press A button to Archive
3. See the next email selected

**Expected behavior**
Expect no emails to be selected

 - Version 1.112.9

**Comment by wrdhub** [comment]
This happens when you drag multiple emails to any folder too.

**Comment by wrdhub** [comment]
## Test notes
- [ ] When looking at a single mail, moving the selected mail (by pressing a, hitting delete butting, using move button, etc...) selects and shows the next mail in the list.
- [ ] When moving mails (any number) in Multi-select mode, no other mails are shown or selected
- [ ] When looking at a single contact, deleting the contact selects and shows the next mail in the list
- [ ] When deleting multiple contacts in Multi-select mode, no other contacts are shown or selected
