### ISSUE TITLE
Gnome crashes when updating Tutanota

### ISSUE THREAD

**Issue by AvercromXD** [tutao/tutanota#5422]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
If I click on the update notification to update the AppImage client the whole desktop environment crashes and I end up on the log in screen. However the client itself is updated after that.

**To Reproduce**
1. Download an older version of the AppImage client
2. Wait for the Update Notification to appear and click on it
3. See error

**Expected behavior**
Only the client should restart on the new version instead of my whole Desktop Environment

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Desktop Environment: Gnome 44
 - Version: I've experienced this bug on versions since version 90

**Comment by charlag** [comment]
We don't observe it and it also sounds like a bug in GNOME
