### ISSUE TITLE
Swiping an email from archive to inbox leaves it in the archive

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5449]
On mobile when I am in the archive folder and swipe an email to the inbox, the email disappears but is not moved to the inbox. When switch to a different email folder and back to the archive the email is visible in the archive again.

How to reproduce:
1. Open the archive folder.
2. Swipe an email to the inbox.
3. Go to the inbox -> the email is not there
4. Go back to the archive -> the email is visible in the archive again

Expected: The email is moved to the inbox.

Reproduced on Android in Tutanota v3.112.6.

## Test notes
* [ ] Swipe from left -> right in inbox moves the email to archive
* [ ] Swipe from right -> left in inbox moves the email to trash
* [ ] Swipe from left -> right in archive moves the email to inbox
* [ ] Swipe from right -> left in archive moves the email to trash
* [ ] Swipe from right -> left in a subfolder from archive moves the email to inbox

**Comment by kibhub** [comment]
Reproduced on iOS v.3.112.6

**Comment by ganthern** [comment]
when in a subfolder of archive, swiping left -> right puts them in the main archive.

**Comment by wrdhub** [comment]
> when in a subfolder of archive, swiping left -> right puts them in the main archive.

We created a bug for this: #6086
