### ISSUE TITLE
[Feature Request] Add support for Android Oreo Autofill API

### ISSUE THREAD

**Issue by IOI-655321** [tutao/tutanota#546]
Add support for Android Oreo autofill API into the app for easy login with password managers such as Bitwarden, LastPass, Dashlane etc.

https://developer.android.com/guide/topics/text/autofill

**Comment by IOI-655321** [comment]
Any update on this as for mobile its quite an annoyance?

**Comment by charlag** [comment]
We receive a lot of reports about autofill and we'll have a look at it soon
I'm not sure yet if we need anything special for Autofill from Android

**Comment by charlag** [comment]
Google made a sample:
https://github.com/googlesamples/android-AutofillFramework/blob/master/Application/src/main/res/raw/sample_form.html
