### ISSUE TITLE
Clicking on a link from a template crashes the client

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5484]
If I open the templates menu when composing an email, and click on a link in one of the templates, the desktop client crashes. On web, it opens the link in the same browser tab, and the draft is not saved. 

**Steps**:

1. have an account with templates
2. create a template which contains a URL
3. open desktop client > compose new email
4. open templates menu Ctrl + Space
5. search for the template with the link
6. click on link
7. see error

Tested on Linux Desktop client, all recent versions and on web. 

## Test Notes
desktop:
* [ ] when viewing a template in the popup, clicking a link opens the destination in the browser without closing dialogs and without errors
  * this works for autolinks and explicitly linked text
* [ ] when viewing it through the list view, it also does not throw errors and opens the link in the browser

web:
* [ ] when viewing a template in the popup, clicking a link opens the destination in a new browser tab without closing dialogs and without errors
  * this works for autolinks and explicitly linked text
* [ ] when viewing it through the list view, it also does not throw errors and opens the link in a new tab

**Comment by charlag** [comment]
still doesn't work in popup
