### ISSUE TITLE
"..." button on email folder disappears

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5517]
When selecting an email folder or clicking on the "..." button next to an email folder (desktop) the "..." button disappears. It appears again when hovering back over the email folder. This issue only applies to the desktop version, not mobile.

Expected: The "..." button is always visible as long as hovering over the mail folder.

## Test Notes
- [ ] The more button ("..." button) remains visible when the dialog menu opens
- [ ] The more button becomes invisible when the dialog menu closes
- [ ] The more button becomes visible when the row is hovered over
- [ ] The more button becomes invisible when the row is hovered out of
- [ ] The more button remains visible when a row is clicked on
- [ ] All of the more buttons are visible when editing the folder list
  - [ ] The more buttons remains visible when hovering over a row
  - [ ] The more buttons remains visible when hovering out of a row
  - [ ] The more buttons remains visible when the dialog menu opens
  - [ ] The more buttons remains visible when the dialog menu closes
 - [ ] Except when editing the folder list, only one row is displaying its more button

**Comment by jalhubb** [comment]
"The more button remains visible when a row is clicked on" - true unless clicking the same row again

**Comment by rezbyte** [comment]
> "The more button remains visible when a row is clicked on" - true unless clicking the same row again

See the PR #6216 for the fix.
