### ISSUE TITLE
Unable to use search within iOS app

### ISSUE THREAD

**Issue by l9i** [tutao/tutanota#5523]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I am unable to search through my emails using the iOS app. 

**To Reproduce**
1. On the main screen click the 'Search' button located on the bottom bar.
2. A tab with "No results. You can switch search type in the menu" text appears.
3. Click on the search bar above (with the "Search emails" placeholder text).
4. An error popup appears saying "Search has been disable due to a system error, and will be re-enabled if you restart the app."

**Expected behavior**
Restarting the app doesn't help, the error still appears. Rebooting the phone or reinstalling the app didn't help either.

**Screenshots**
![error message](https://github.com/tutao/tutanota/assets/10261967/c2301ca9-3e38-4701-8a57-095cafdc950a)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 16.5 (20F66)
 - Version 3.113.3

**Additional context**
The iOS device is running in a lockdown mode.

**Comment by charlag** [comment]
ah thanks for the info. I think we already run into this with iOS 16 despite what the changelog says. You could also try it yourself.

Hopefully in the future we won't need to rely on IndexedDB and tbh the toggle in settings also says that some functions won't work but you are right, we could try to adjust the message, thank you for the idea!
