### ISSUE TITLE
Android app crashes when put in the background

### ISSUE THREAD

**Issue by SkypLabs** [tutao/tutanota#5529]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

The Android application crashes when put in the background and then reopened. I don't even need to log into an account to make the application crash.

**To Reproduce**

1. Open the Tutanota Android application.
2. Go back to the launcher.
3. Reopen the Tutanota application.
4. The application crashes and is relaunched automatically by the OS, which means that I end up on the home screen, logged out.

**Expected behavior**

Not to crash :slightly_smiling_face: 

**Screenshots**

N/A

**Smartphone (please complete the following information):**

 - Device: Pixel 3a
 - OS: GrapheneOS (Android)
 - Version: Android 12

**Additional context**

The logs related to the crash:

```
06-08 21:07:11.794  4858  4858 D MainActivity: onStop                                                                                                                                         
06-08 21:07:11.844  4858  4858 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 719284)                                                                                        
06-08 21:07:11.846  4858  4858 W ActivityStopInfo: Bundle stats:                                                                                                                              
06-08 21:07:11.848  4858  4858 W ActivityStopInfo:   WEBVIEW_CHROMIUM_STATE [size=717132]                                                                                                     
06-08 21:07:11.848  4858  4858 W ActivityStopInfo: PersistableBundle stats:                                                                                                                   
06-08 21:07:11.848  4858  4858 W ActivityStopInfo:   [null]                                                                                                                                   
06-08 21:07:11.849  4858  4858 D AndroidRuntime: Shutting down VM                                                                                                                             
06-08 21:07:11.850  4858  4858 E AndroidRuntime: FATAL EXCEPTION: main                                                                                                                        
06-08 21:07:11.850  4858  4858 E AndroidRuntime: Process: de.tutao.tutanota, PID: 4858                                                                                                        
06-08 21:07:11.850  4858  4858 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 719284 bytes                                           
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.app.ActivityClient.activityStopped(ActivityClient.java:87)                                                                 
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)                           
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)                                                                                
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)                                                                                
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)                                                                                        
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)                                                                                            
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7876)                                                                          
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                                     
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)                                                  
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:49)                                                                            
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)                                                                
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)                                                                     
06-08 21:07:11.850  4858  4858 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 719284 bytes                                                            
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)                                                                               
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:571)
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1315)
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        at android.app.ActivityClient.activityStopped(ActivityClient.java:84)
06-08 21:07:11.850  4858  4858 E AndroidRuntime:        ... 11 more
06-08 21:07:11.864  1158  1878 W ActivityTaskManager:   Force finishing activity de.tutao.tutanota/.MainActivity
```

We can see that the application crashes when the `onStop` Android method is called.

**Comment by charlag** [comment]
Hi, thank you for the report!

Any ideas how we could reproduce it? It seems like it has something to do with big `Intent` payloads

**Comment by SkypLabs** [comment]
Hi,

Indeed, the problem seems to happen because of a too big saved state. I can run some tests but your insights about your codebase would be very helpful.

First, what sorts of data are bundled and passed to the Android activity lifecycle methods (e.g. `onStart`, `onStop`)? Can you point me to the related code implementation?

I was actually wondering if the local search index is part of the saved state, as it seems to be something which can easily grow fast.

**Comment by charlag** [comment]
we don't really pass too many things via Intents. all the relevant code should be in `MainActivity` so I wonder if it's some intent coming from the outside

**Comment by SkypLabs** [comment]
I've managed to narrow down the root cause of the problem and I'm now able to reproduce the bug from scratch while using the latest Android version available on F-Droid to this day (3.115.2). To do so, I removed my saved credentials and I cleared both user and cache data on my phone, then:

1. Open the Tutanota Android app.
2. Enter the credentials of account A, check "Store password" and proceed with login.
3. Go back to the home screen by logging out.
4. Select "Different account".
5. Enter the credentials of account B, check "Store password" and proceed with login.
6. Account B having whitelabel enabled, I'm invited to apply the related custom theme, which I do.
7. Close the application and remove it from [the recents screen](https://developer.android.com/guide/components/activities/recents).
8. Open the Tutanota application once again.
9. Log into any account.
10. Put the application in the background.
11. Reopen the application (which crashes).

So it seems that the root cause is somewhat linked to custom themes. If I change it back to a built-in theme (e.g. "Dark"), close the application, remove it from the recents screen and then reopen the Tutanota application, the bug is there no more.

Also, I noticed that if I enable the custom theme from account B, it will also be enabled when I log in account A. Is this the expected behaviour?

**Comment by charlag** [comment]
Thank you for the detail instructions, we will try it out!

**Comment by ganthern** [comment]
So this happens because we call `webView.saveState` in `MainActivity.onSaveInstanceState` and the webView seems to put the whole browser history into the Bundle (which we're not using, we never call `webView.restoreState` as far as I can tell).

That's not too bad, but each history entry contains 
* the original URL
* the current URL
* the favicon (which is 192 * 192 * 4 bytes)

That's also not too bad - but for whitelabel, we actually encode the theme in the url so it's available when we first create the webView. That includes a B64-encoded version of the custom logo, which can be up to 100kB. That way it's very easy to reach the apparent max of 1MB bundle size.

Since we don't seem to use the saved state, we should be able to just remove this and be fine:

https://github.com/tutao/tutanota/blob/5e19c8ee8852bd19535edcaf4bae4b35efecd4ca/app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt#L421-L424

If it turns out that we're still using it somewhere that I can't find right now, we should pare down the bundle after calling `webView.saveState`

**Comment by vitoreiji** [comment]
Doing the repro steps on the testing version did not crash, but I wasn't able to make it crash on prod either. Marking as tested anyway.
