### ISSUE TITLE
I can't login for many times.

### ISSUE THREAD

**Issue by zelihole** [tutao/tutanota#5539]
I can't login, 
![搜狗截图20230617235115](https://i2.100024.xyz/2023/06/18/1eaqr.webp)
![搜狗截图20230617235134](https://i2.100024.xyz/2023/06/18/1ejft.webp)
here are some information↓
# My computer
Microsoft Surface Pro 6
Windows 11
Google Chrome Brouser
# The Internet
Provider：China Mobile[（中国移动）](http://www.10086.cn/)of Jiangsu
Support the 5G

**Comment by zelihole** [comment]
> 

I can't login the mail, it ALWAYS says "the conection was lost", now I can't read & reply emails to my classmate.
:(

**Comment by charlag** [comment]
Please contact support
