### ISSUE TITLE
Signup UI button misplacement

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5552]
In the business plan selection if you use specific languages (like German) the monthly/yearly buttons overlap the select button. This is because the text "per user/month - paid yearly Excludes taxes." will become three lines instead of two depending on the UI language.

This bug also applies to the website pricing page.

How to reproduce:
1. Select German as the UI language.
2. Open the signup in the app or the pricing page on the website.
3. Switch to the business plans.
-> The monthly/yearly buttons overlap the select button.
Expected: all margins are fine in any language.

### Personal looks OK

![image](https://github.com/tutao/tutanota/assets/197261/0b8d7635-340f-431f-b6da-31e7db6b91b4)

### Business does not

![image](https://github.com/tutao/tutanota/assets/197261/7cd98da5-ac06-4114-b660-2cc0071a225b)

## Test Notes
* [ ] Overlap doesn't happen during plan select in sign up page
* [ ] Overlap doesn't during plan select on settings page
* [ ] Overlap doesn't happen in the desktop client during plan select
* [ ] Overlap doesn't happen in mobile apps
* [ ] All the select buttons are in the same baseline
* [ ] check greek as well

**Comment by ganthern** [comment]
![image](https://github.com/tutao/tutanota/assets/29049728/be8395cc-c802-41fc-951d-847de38f89d2)

doesn't seem to be working for greek still
