### ISSUE TITLE
Inconsistent abbreviation of event names in monthly view

### ISSUE THREAD

**Issue by clemisch** [tutao/tutanota#5569]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

Inconsistent abbreviation of event names in monthly view. 

1. If event does not have a reminder, three dots (`...`) are used to indicate a long name, but take a lot of space themselves!
2. If the event does have a reminder, the event name is simply clipped such that as much letters as possible are rendered.

I would much prefer (2) to be the default, i.e. to always render as much of the event name as possible. 

**To Reproduce**

1. Create an event with a long name
2. View in monthly view: dots `...` are used and take up lots of space.
3. Add reminder to the event.
4. View in monthly view: no dots are used

**Expected behavior**

Dots are never used. 

**Screenshots**

![image](https://github.com/tutao/tutanota/assets/5190547/32dadc50-9b98-4542-9bd0-a42e01438442)

**Smartphone (please complete the following information):**

 - Device: iPhone 11
 - OS: iOS 16.5.1
 - Version 3.114.1

**Test Notes**
- [ ] When an event's summary doesn't have space to have more than one line, the overflowing content will be clipped
- [ ] When an event's summary has space to have more than one line, the overflowing content will be displayed with ...
- [ ] There's no overlapping between event summary and event time

**Comment by clemisch** [comment]
Sorry, I just noticed on the enlarged screenshots that the ellipsis `...` is still present even with the alarm symbol `🔔`, but only one dot is visible (on my device). 

Then this is rather a _request_ than a _bug report_ to remove the ellipsis `...` altogether.

**Comment by charlag** [comment]
yes we should just cut the off, that's a good proposal
