### ISSUE TITLE
Opening an email undoes multiselect in use

### ISSUE THREAD

**Issue by ctrlvd** [tutao/tutanota#5570]
When user selects emails and misses a checkbox by opening an email instead, all previously selected checkboxes are unchecked.

1. Multiselect emails
2. Select an email to open
3. Have the previously selected emails unselected

**Comment by charlag** [comment]
@ctrlvd that's by design?

**Comment by ganthern** [comment]
@ctrlvd it would be good to use the template you deleted when creating the issue and actually describe what the expected behaviour is in your opinion.
