### ISSUE TITLE
Issue for DHL clients: Shipping notices cannot be displayed; notice about unsupported email format appears in the spam folder

### ISSUE THREAD

**Issue by sundayLOOKplants** [tutao/tutanota#5578]
The format that DHL uses to notify for its parcels is not supported by Tutanota. I'm unsure whether this is due to missing features or privacy requirements.

Tutanota's own notices about unsupported messages were placed in the spam folder (therefore I missed the parcel entirely).

Since I do not use the desktop app, I'm unsure whether it's related to Tutanota's back-end, or the web client.

**Comment by charlag** [comment]
Hi, if you are a premium customer please contact support via in-app help function. If you are not please contact hello@tutao.de.
