### ISSUE TITLE
changes in the email list cause ui issues

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5579]
**v3.114.4**

best to describe with have examples:

1. have multiple emails
2. archive one
3. use "u" to mark next one as unread
4. email is marked actually marked as unread but the email in the list doesn't change.
5. click on the email
6. use "u"
7. works as expected

another example:
1. have multiple emails
2. archive one
3. use up/down arrows
4. first press is ineffective
5. press again
6. works as expected

**Comment by charlag** [comment]
@kibhub which version was that?

**Comment by kibhub** [comment]
> @kibhub which version was that?

sorry, v3.114.4. description updated as well.
