### ISSUE TITLE
Renderer process inLinux desktop client dies because of OOM

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5586]
The desktop client randomly dies and we see a blank Tutanota window.

System logs:
Jun 30 15:06:27 kernel: [20659.316208] traps: tutanota-deskto[3214] trap int3 ip:55b48f1bd24f sp:7ffd1ed75f70 error:0 in tutanota-desktop[55b48b8f6000+7870000]
Jun 30 15:06:27 tutanota.desktop[3214]: [1:0x3d380080c000] 20614889 ms: Scavenge 3849.4 (4087.3) -> 3843.6 (4087.6) MB, 7.09 / 0.00 ms  (average mu = 0.948, current mu = 0.944) task;
Jun 30 15:06:27 tutanota.desktop[3214]: [1:0x3d380080c000] 20615138 ms: Scavenge 3850.0 (4087.6) -> 3844.2 (4087.6) MB, 5.42 / 0.02 ms  (average mu = 0.948, current mu = 0.944) task;
Jun 30 15:06:27 tutanota.desktop[3214]: [1:0x3d380080c000] 20615439 ms: Scavenge 3850.5 (4087.6) -> 3844.6 (4087.8) MB, 8.54 / 0.01 ms  (average mu = 0.948, current mu = 0.944) task;
Jun 30 15:06:27 tutanota.desktop[3214]: <--- JS stacktrace --->
Jun 30 15:06:27 tutanota.desktop[3214]: [3214:0630/150627.236752:ERROR:v8_initializer.cc(753)] V8 javascript OOM (MarkCompactCollector: young object promotion failed).

**Comment by charlag** [comment]
main thread eats up to 1437MB for me

**Comment by charlag** [comment]
it seems like the problem is continuous redraw here: https://github.com/tutao/tutanota/blob/c2dbe21be16b41b9e340b7c99eba03a0c4162048/src/mail/view/MailView.ts#L270
(it will schedule a redraw on every render)
