### ISSUE TITLE
Attachment popup is not displayed on some systems

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5587]
When clicking an attachment bubble on some systems, the modal gets created and the background dims, but the size is (probably) calculated incorrectly, leading to an invisible popup.

## Test Notes
test for short (1 line) and very long (> 3 lines) file names, with multiple attachments per mail. "works" means that it's visible, appropriately sized and at least one button has been tested and works.
* [ ] the panel works on desktop
* [ ] the panel works on android
* [ ] the panel works on ios
* [ ] the panel works in edge, chrom(ium|e), firefox, safari
* [ ] the panel works in chromium with throttled cpu while profiling on a very slow machine/VM (sorry)

## Post release notes
* [ ] notify support that from now on, users affected by wonky attachment popups should send logs after trying to open the panel.

**Comment by kibhub** [comment]
Most reports are from the Windows Desktop client v3.112.15 or later or the Chrome browser versions 112 or later.
Will update with more details as we get them.

**Comment by kibhub** [comment]
A new report of the same issue on iPhone 13, iOS 16.5.1
