### ISSUE TITLE
Plans are not shown next to each other

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5598]
**Describe the bug**
The new plans are not shown next to each other in desktop layout.

**To Reproduce**
1. Open Tutanota in desktop layout and open the signup or switch subscription dialog
2. See that the third plan is shown in a second row.

**Expected behavior**
All plans should be shown next to each other so that i can compare features. 

**Screenshots**
![Screenshot from 2023-07-06 09-10-15](https://github.com/tutao/tutanota/assets/8296817/de930aca-0ad2-4a1a-ad25-f13341d24156)

**Comment by charlag** [comment]
it's Chrome-only, probably because of scrollbars
