### ISSUE TITLE
Account approval message keeps appearing after approval

### ISSUE THREAD

**Issue by justincardoza** [tutao/tutanota#5600]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
It's possible for the desktop and mobile apps to keep showing the "marked for approval" message after the account seems to be approved. In my case, I am pretty sure support was able to approve my account after I reached out, because the web interface does not show the approval message anymore. I was able to fix it in the Android app by clearing all app data and signing back in, which makes me think it's likely a caching issue. The same is probably true for the desktop client, but I haven't tried yet in case we end up needing data from it.

Running this JavaScript snippet in the developer tools console will show the current Customer object:

```js
window.tutao.locator.logins.getUserController().loadCustomer().then(customer => console.log(customer))
```

**To Reproduce**
1. Create a Tutanota account that is marked for approval (no idea how this ended up being the case for me since I didn't use a VPN or anything like that)
2. Sign in to the new account in the Android app and desktop client
3. Wait for the 48 hours indicated by the initial approval message
4. The "contact us" approval message appears. Contact Tutanota support as instructed.
5. When the approval message stops appearing in the web UI, check the desktop client and Android app again.
6. The "contact us" approval message should still appear.

**Expected behavior**
Once a new account is approved, messages indicating it is not approved should no longer appear in any of the clients.

**Screenshots**
The approval message still appearing in the desktop client:
![desktop-app-error](https://github.com/tutao/tutanota/assets/1139831/b7279039-d241-4c13-b40a-3241f019a7d6)

The value of `approvalStatus` in the desktop app, with "6" corresponding to `ApprovalStatus.DELAYED_AND_INITIALLY_ACCESSED`:
![desktop-app-approval-status](https://github.com/tutao/tutanota/assets/1139831/8087a6e0-cd88-40af-82dd-6e06938cc9da)

The value of `approvalStatus` in the web interface, with "0" corresponding to `ApprovalStatus.REGISTRATION_APPROVED`:
![web-approval-status](https://github.com/tutao/tutanota/assets/1139831/90966a26-2ce0-4b56-9e4c-995131d56c9c)

**Desktop (please complete the following information):**
 - OS: Fedora 38 (for the Android app, I use LineageOS 19 based on Android 12)
 - Desktop Environment: KDE Plasma 5.27.5

**Additional context**
The message in the screenshot is `requestApproval_msg` and it's being shown by `checkApprovalStatus()` in `src/misc/LoginUtils.ts`. I suspect the issue is occurring somewhere in `UserController.loadCustomer()` since that's returning a `Customer` object with the wrong `approvalStatus` in the desktop client, but I haven't been able to track it down in more detail than that.

## Test notes
- [ ] The approval message is displayed when:
  - [ ] Sign into an unapproved account for the first time
  - [ ] Sign into an unapproved account for the first time online, sign out, go offline then sign in
  - [ ] Sign into an approved account, sign out, unapprove the account then sign in
- [ ] The approval message is not displayed when:
  - [ ] Sign into an unapproved account for the first time, sign out, approve the account then sign back in
  - [ ] Sign into an approved account
  - [ ] Sign into an approved account for online, sign out, go offline then sign in

**Comment by charlag** [comment]
Hi, thanks for the report and detailed investigation!
It is probably the case that the desktop/android app did not fully sync yet when we show this message and what we check is an outdated version of customer

**Comment by charlag** [comment]
We checked it and it is indeed using cached customer so it's not shown when it should be and is shown when it shouldn't

**Comment by charlag** [comment]
"Sign into an unapproved account for the first time online, sign out, go offline then sign in" the status will only be checked after full login so need to go online for that but I think this is anyway expected and everything works!
