### ISSUE TITLE
Update default email signature

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5616]
We want to update the default signature to include a link to https://tutanota.com. 
- [x] The exact text needs to be defined.
- [x] The code to replace the link in the translation is already there but we should check if it still works.
- [x] Check if outgoing spam filter checks for the signature.

The exact text should be:
```
Sent with Tutanota; enjoy secure & ad-free emails:
{1}

Versendet mit Tutanota. Hol dir sichere und werbefreie E-Mails:
{1}
```

**Comment by wrdhub** [comment]
Updated in Phrase

**Comment by kibhub** [comment]
current build does not have new translation key values.
