### ISSUE TITLE
double tap to zoom in landscape mode not zooming

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#5621]
no zooming when double tapping to increase readability (landscape mode)

1. Open Tutanota mobile App
2. turn mobile phone sideways (with screen unlocked)
3. open html formatted email
4. Double Tap to try to zoom
5. Nothing happens

 - iPhone 12 Pro Max
 - OS: 16.5.1
 - Version: 3.114.1

**Comment by charlag** [comment]
double tap switches between scaled and unscaled mode, if email wasn't initially scaled it won't do anything.
It will change with #1997
