### ISSUE TITLE
Usage test cleanup

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#5622]
* [x] Calculate significance for credit card 2 test
* [x]  Calculate significance for password test. 
* [x] Use 80% password strength. Min password strength is reached when bar is at 80%. There is a text indication if that is the case.
* [x] Remove credit card test and old form implementation
* [x] Remove the unavailableemails usage test

The usage test results are stored here: 
*<wiki>/pages/viewpageattachments.action?pageId=64029383
* gitlab/tuta/usage-test-evaluation

**Comment by armhub** [comment]
**Test notes**

- [ ] The new minimum password strength is applied at signup
- [ ] The new minimum password strength is applied for external recipient
- [ ] The paypal usage test still works
- [ ] The admin client does not show default usage test configurations for password strength, credit card and unavailable emails

**Comment by armhub** [comment]
The changes are on the branch usage-test-cleanup for tutanota and admin
