### ISSUE TITLE
DBError  'MetaData' is not a known object store name

### ISSUE THREAD

**Issue by i1caro** [tutao/tutanota#5643]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in web app**
Feedback v3.115.2 - DbError - UNKNOWN - Browser

 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.115.2
 Timestamp (UTC): Wed, 19 Jul 2023 16:11:15 GMT
 User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
DbError
 Error message: could not create transaction: NotFoundError, IDBDatabase.transaction: 'MetaData' is not a known object store name> createTransaction/<@https://mail.tutanota.com/worker-search-8521843e.js:1:2802

Stacktrace: 
DbError. could not create transaction: NotFoundError, IDBDatabase.transaction: 'MetaData' is not a known object store name> createTransaction/<@https://mail.tutanota.com/worker-search-8521843e.js:1:2802

**Describe the bug**
At login, and at search this happens.

**To Reproduce**
1. Go to mail.tutanota.com
2. Click on login
3. See error

Using firefox on ubuntu, always had this error have no idea since I didn't change anything

**Expected behavior**
No error, able to search

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser firefox 115.0.2 (64-bit)
 - Version 115.0.2 (64-bit)

**Comment by i1caro** [comment]
I think it's working, I run the following script and got an `OK`
```
  var db = indexedDB.open("test");
  db.onerror = () => console.log('error');
  db.onsuccess = () => console.log('ok');
```

**Comment by charlag** [comment]
could you try clearing data for Tutanota then? It seems like you half only part of the database created (somehow)

**Comment by i1caro** [comment]
It's working now thanks. And sorry I didn't even think of that :(

**Comment by charlag** [comment]
No worries, it should ideally be able to handle this.
