### ISSUE TITLE
Ctrl+Shift+A conflicting with Chrome Tab Switcher Shortcut

### ISSUE THREAD

**Issue by hj-collab** [tutao/tutanota#5652]
**Bug in web app**

**Describe the bug**
Pressing Ctrl+Shift+A in the web app selects all emails in Tutanota instead of opening Chrome Tab Switcher.

**To Reproduce**
1. Go to 'Tutanota Web App
2. Press Ctrl+Shift+A

**Expected behavior**
It should open Chrome Tab Switcher.

**Additional context**
Please don't hijack Chrome or any major shortcuts which are used from years.

**Comment by ganthern** [comment]
context:
https://github.com/tutao/tutanota/pull/5363

this shortcut should only be enabled in the desktop client.

**Comment by ganthern** [comment]
@hj-collab great! thank you for the report.
