### ISSUE TITLE
Showing Blank Screen

### ISSUE THREAD

**Issue by ProfessorCode212** [tutao/tutanota#5653]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Tutanota appears to be able to load and log in to my account, but the app only shows a blank white screen. It seems to have occurred after I updated Fedora because it was working fine earlier.

**To Reproduce**
1. Open Tutanota.
2. Title bar will indicate that the app has logged in.
3. Nothing shows up.

**Expected behavior**
I should be able to see my mailbox.

**Screenshots**

![Screenshot from 2023-07-22 11-12-34](https://github.com/tutao/tutanota/assets/78950242/6e1dc967-4472-4463-8f7e-a2f90ebcb16c)

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Desktop Environment, if applicable (on Linux): GNOME
 - Tutanota Version: 3.115.2.493 (AppImage)

**Additional context**

**Comment by charlag** [comment]
it seems like one of the Chromium bugs, could you please try deleting `~/.config/tutanota-desktop/GPUCache`?

**Comment by HenryGR-oficial** [comment]
Deleting the GPUcache did the charm!

**Comment by charlag** [comment]
if anyone had/has this, please record the command line output, I think there should be some errors

**Comment by charlag** [comment]
Fedora + Chromium discussion
https://discussion.fedoraproject.org/t/chromium-based-browsers-display-garbled-web-pages-after-mesa-is-updated/83438

**Comment by charlag** [comment]
Chromium bug (linked from the Fedora discussion). Seems like updating mesa screws up Chromium-based things

**Comment by DynAggelos** [comment]
In my case I was not logged in when opening Tutanota, but I was also seeing a blank white/gray screen. Deleting the folder `~/.config/tutanota-desktop` did the trick. Deleting the entire folder is probably overkill, and will erase your settings, but at least it worked.

**Comment by daniellasalle** [comment]
Another alternative to this bug is:
1. login desktop tutanota app with credidentials;
2. browse your emails as you would normally;
3. hold CTRL and use the scroll of the mouse to decrease the character size and it will break.

**Comment by daniellasalle** [comment]
Perhaps this also will help:

[1165368.712571] dconf worker[2728942]: segfault at 7f4768004198 ip 00007f4776e9ec4a sp 00007f476d5fca70 error 6 likely on CPU 2 (core 2, socket 0)
[1165368.712587] Code: 8d 34 19 48 39 d5 48 89 75 60 0f 95 c2 48 29 d8 48 83 c1 10 0f b6 d2 48 83 c8 01 48 c1 e2 02 48 09 da 48 83 ca 01 48 89 51 f8 <48> 89 46 08 8b 05 68 e8 15 00 85 c0 0f 84 c6 f7 ff ff e9 90 fd ff
[1165902.002632] traps: tutanota-deskto[2731850] trap int3 ip:561a051f1f05 sp:7ffed2553700 error:0 in tutanota-desktop[561a04c8a000+7846000]

**Comment by daniellasalle** [comment]
1 final comment: when contacting your support I was told that
"Hi there,
Thank you for your email. This rendering issue is related to Electron/Chromium. You can currently work around it by deleting the GPUCache directory in ~/.config/tutanota-desktop/
Here's the command for the terminal if you'd like:

rm -r ~/.config/tutanota-desktop/GPUCache"

But this is a lie.

After I deleted the ~/.config/tutanota-desktop/GPUCache entries, I restarted Tutanota, did as previously mentioned with the mouse scroll and it did the same error.

**Comment by ganthern** [comment]
@daniellasalle sorry the workaround doesn't work for you. can you give us some more details about your setup? Are you using the flatpak or appimage? Distribution? I'm currently on the AppImage on Ubuntu 22.04 and can scroll just fine.

**Comment by daniellasalle** [comment]
@ganthern am using AppImage and Ubuntu MATE 23.04.

But it worked fine using either 22.04 or 22.10.
