### ISSUE TITLE
Enable log in for external users

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#566]
- log in with password
- log in with sms

**Comment by mpfau** [comment]
Login with password is already implemented but buggy: 
* Store password in browser (preshared) and login with notification link again, receive second mail with new preshared password -> auto login should not be possible. However, an error dialog is triggered.

**Comment by bedhub** [comment]
* ensure that attachments can be displayed on iOS. Currently displaying images for externals is not possible in the old and new client.

**Comment by mpfau** [comment]
Error message when reloading page after login (with saved credentials).
