### ISSUE TITLE
Cancelled payment and locked out

### ISSUE THREAD

**Issue by Rikki1408** [tutao/tutanota#5660]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I've found myself in quite the pickle. I'm reinforcing my online presence and am starting by signing up at Tutanota. I have, however, messed up in a really stupid way. Last night I created an account and would wait until today to start migrating to Tutanota. I purposefully chose not to save the password in the browser *just in case* any cookie would be compromised. The email address was randomly generated, and so was the password. I created a new entry in my password manager and saved both the email, password and recovery keys there, but when I went to log in today it said the login credentials were wrong. I tried resetting it with almost every recovery code as well as the two most recent randomly generated email addresses, but nothing is working. Last night I connected my Paypal to the old Tutanota account, so when I gave up trying today and created a new account, I was unable to buy the revolutionary plan on my new account. I tried contacting you on LinkedIn, but your messages are only open if you're a Gold subscriber. I tried messaging you on your Twitter support account (@TutanotaSupport) and your messages were also blocked there (see attachment A and B).

**To Reproduce**
1. Create account [A] with a randomly generated email address and screw up saving it in your password manager
2. Connect your PayPal account to Tutanota account [A]
3. Attempt to recover account [A] by using your saved recovery keys together with the most recent randomly generated addresses
4. Create a new account [B] with another randomly generated email address
5. Attempt to connect your PayPal account to Tutanota account [B]
6. You're now unable to subscribe to any plans on account [B] as your PayPal account was already connected to account [A] (see attachment C)
7. You're unable to message the support team because they can only be contacted as a paying customer

**Expected behavior**
By maybe implementing a free tier support "depositum" to avoid free users trying to upgrade to a paid tier from being locked out completely.

**Screenshots**
A: ![image](https://github.com/tutao/tutanota/assets/59708634/462cf33c-5968-4be7-9b77-c0369a021aa0)
B: ![image](https://github.com/tutao/tutanota/assets/59708634/64fc9612-d9f4-40a1-a4de-e79b771f3017)
C: ![image](https://github.com/tutao/tutanota/assets/59708634/5a12dd6a-71fb-4e93-bdae-fc30db8953c5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 115.0.2 (64-bit)

**Additional context**
I'm aware this might not belong here as a bug report, but if you see it, could you then please refer me to the correct place to get help?

**Comment by charlag** [comment]
please contact hello@tutao.de
