### ISSUE TITLE
Missing ResizeObserver is not handled

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5661]
When `ResizeObserver` is missing the app just breaks. This can happen when users mess with their Safari settings.

We need to either handle it gracefully or add it to the required features check.

## Test notes
 - [ ] Regression: list looks correct after resizing the app. Swipe items also look correct after resizing the app.
 - [ ] Disable ResizeObserver in Safari on iOS. See that the app still shows list items.

**Comment by wrdhub** [comment]
Still some oddness with how swipe items are displayed with ResizeObserver disabled, but everything still works and you can interact with things. Are some display issues okay (when things are disabled) as long as the app mostly works?

**Comment by ganthern** [comment]
we're just trying to recover from what's basically a misconfiguration, if it's possible to use everything then that's as much as can be expected
