### ISSUE TITLE
Bug in desktop and mobile app regarding notifications from removed account

### ISSUE THREAD

**Issue by nomentuum** [tutao/tutanota#5667]
Someone else logged in on their account from my desktop and phone and, after I removed their account credentials, I still receive a notification each time they receive a new email, even if I no longer can access their account. 

 This happens on my phone and on my desktop.

I have a free subscription plan and my friend also.

Windows 11
Tutanota 3.115.2
Android 13
Tutanota 3.114.1

**Comment by charlag** [comment]
Hi, currently this is expected behavior because you can log in without saving credentials.
We will change this at some point but for now the owner of the account should remove the notifications device is Settings -> Mail -> Notifications
