### ISSUE TITLE
Label overflows icon

### ISSUE THREAD

**Issue by trikaphundo** [tutao/tutanota#5685]
# Bug in mobile app

## Bug description
In the **Catalan translation** of the mobile app, there is a label that overflows its icon.

## Reproducing the bug
Steps to reproduce the problem:
 1. Set your phone's language to Catalan.
 2. Log in to your Tutanota email account with the mobile app.
 3. Look at the bottom of the screen.
 4. The leftmost icon does not show its label completely, it is too long, it overflows.

## Expected behavior
The icon's label should be shown completely, not partially.

## Screenshots
Here are a pair of screenshots I have taken; the first shows the problem (vertical screen), while the second shows no problem at all (horizontal screen). Both images are retouched to make clear what to look at.
![Screenshot_20230725-010131](https://github.com/tutao/tutanota/assets/24832650/6e334194-78a2-495d-ad07-baa58d107f04)
![Screenshot_20230729-192352](https://github.com/tutao/tutanota/assets/24832650/5e408568-32b5-4344-a8f5-324c288d246f)

## Smartphone
 - Device: realme C11 2021, model RMX3231
 - OS: Android 11
 - Version of Tutanota: 3.115.2

## Fixing suggestion
Given the context which the text lives in, the [label](https://github.com/tutao/tutanota/blob/67e3476064ef8480248d4716637976fe3e2bc3f9/src/translations/ca.ts#L360C8-L360C8) `correus electrònics` can be **safely shortened** to just `correus`, without risk of misunderstanding or confusion, while fitting correctly in the space.
The [Spanish translation](https://github.com/tutao/tutanota/blob/67e3476064ef8480248d4716637976fe3e2bc3f9/src/translations/es.ts#L454) does exactly that, it reads `correos`.

**Comment by rezbyte** [comment]
I have updated the Catalan translation to just 'Correus'.
