### ISSUE TITLE
multiple emails are selected when using long press

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#5696]
**Describe the bug**
When you select an email in the mobile app by using a long press, two emails are marked as selected.

**To Reproduce**
1. Have multiple emails in the mobile app
2. Open any email
3. Go back
4. Long press on a different email
5. See error

**versions**
 - iOS, Android
 - Tutanota v3.115.2

## Test notes
* [ ] Multi select still working
* [ ] In single column layout and not in multi select mode, when long press an email/contact, 
        it enters in multi select with only the pressed email/contact
* [ ] In multi column layout and not in multi select mode, if an email/contact is open and start 
        multi select with another email/contact holding CTRL, both emails are selected
* [ ] Multi select with SHIFT still working as expected
* [ ] Selecting multiple emails/contacts holding CTRL still working as expected

**Comment by BoerniBenwulf** [comment]
> **Describe the bug** When you select an email in the mobile app by using a long press, two emails are marked as selected.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Have multiple emails in the mobile app
> 
>     2. Open any email
> 
>     3. Go back
> 
>     4. Long press on a different email
> 
>     5. See error
> 
> 
> **versions**
> 
>     * iOS, Android
> 
>     * Tutanota v3.115.2

It seems that last opened email has been marked together with long pressed mail.  The last opened mail seems to have a remaining selection focus, so it is really difficult to mark the long pressed mail only. As a result I deleted the two mails instead of justcthe long pressed one
