### ISSUE TITLE
Update is sent twice when changing single occurrence of event

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#5699]
1. Create repeating event with at least one guest
2. Edit a single occurrence and choose to send updates
3. Invitee gets two emails about the update

**Expected behavior**
Invitee gets a single update notification

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/197261/096e19b6-97d8-4ac9-a7b3-af9884d83c54)

**Comment by ganthern** [comment]
working as intended. 
the first mail is the update to the event series (it now has an exclusion) and the second is the update to the actual edited instance. 

if you edit a second occurrence and then change the title on the whole series, you should even get three e-mails, one for the series and one for each altered instance.
