### ISSUE TITLE
Accepting event invitation with an altered occurrence "unalters" occurrences

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#5731]
1. On an external provider, create recurring event with an altered occurrence
2. Invite Tutanota user, choosing "all occurrences" when asked
3. Accept invitation for the main event
5. The occurrence that was altered in the original is not altered or excluded on Tutanota Calendar
6. Accept invitation for the altered occurrence
7. Altered occurrence is added and coexists with unaltered one

Expected behavior
Altered occurrences are not treated as normal occurrences.

## Test Notes 
* [ ] re-test the bug with thunderbird and with google. the event should be in the same state on the provider and on tutanota after accepting all invitations. note that thunderbird will not add attendees that were added to "all events" to altered instances.
* [ ] when using thunderbird, it's possible to accept simultaneous invites to the series and to altered instances from one mail if it's sent that way.
* [ ] simultaneous updates are also applied

**Comment by charlag** [comment]
okay Thunderbird is the only one which actually does put all parts of the event  in one .ics file.

I tried it with Google and could not reproduce it.

**Comment by ganthern** [comment]
It's so funny to me how ad-hoc this whole calendaring app industry is despite there being hundreds of pages of RFCs.

Anyway, I could also not reproduce with google, but that thunderbird thing seems like a problem.
