### ISSUE TITLE
Event cancellation notifications do not remove events

### ISSUE THREAD

**Issue by vitoreiji** [tutao/tutanota#5732]
1. From an external provider, create an event and invite a Tutanota user
2. Accept invitation to event 
3. The event is added to the calendar
4. Delete the event on the external provider and send notifications to guests
5. The notification is received, but the event is not removed

**Expected behavior**
The cancelled event is removed from the calendar.

**Additional notes**

Update notifications are not applied either.

**Comment by ganthern** [comment]
holy f*ck, google

```
[CalendarModel] processing request for existing event instance CalendarModel.ts:384:10
[CalendarModel] got update for outdated event version, ignoring. CalendarModel.ts:387:11
```

and looking at the icals... first the original:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230815
DTEND;VALUE=DATE:20230816
DTSTAMP:20230803T152209Z
ORGANIZER;CN=nigfortest@gmail.com:mailto:nigfortest@gmail.com
UID:265fviin4lrrros3n4ocb8mu99@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;CN=nigfortest@gmail.com;X-NUM-GUESTS=0:mailto:nigfortest@gmail.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=premiumpancakes@tutanota.com;X-NUM-GUESTS=0:mailto:premiumpancakes@tutanota.com
X-MICROSOFT-CDO-OWNERAPPTID:-1817621318
CREATED:20230803T142847Z
DESCRIPTION:
LAST-MODIFIED:20230803T152208Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:nig
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

then the update - after changing the summary:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230815
DTEND;VALUE=DATE:20230816
DTSTAMP:20230803T152242Z
ORGANIZER;CN=nigfortest@gmail.com:mailto:nigfortest@gmail.com
UID:265fviin4lrrros3n4ocb8mu99@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE;CN=nigfortest@gmail.com;X-NUM-GUESTS=0:mailto:nigfortest@gmail.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=premiumpancakes@tutanota.com;X-NUM-GUESTS=0:mailto:premiumpancakes@tutanota.com
X-MICROSOFT-CDO-OWNERAPPTID:-1817621318
CREATED:20230803T142847Z
DESCRIPTION:
LAST-MODIFIED:20230803T152241Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:nig2
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

that `SEQUENCE:0` should be literally any other natural number. cancellation worked, though.

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:CANCEL
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230815
DTEND;VALUE=DATE:20230816
DTSTAMP:20230803T152615Z
ORGANIZER;CN=nigfortest@gmail.com:mailto:nigfortest@gmail.com
UID:265fviin4lrrros3n4ocb8mu99@google.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;CN=nigfortest@gmail.com;X-NUM-GUESTS=0:mailto:nigfortest@gmail.com
ATTENDEE;CUTYPE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;CN=premiumpancakes@tutanota.com;X-NUM-GUESTS=0:mailto:premiumpancakes@tutanota.com
CREATED:20230803T142847Z
DESCRIPTION:
LAST-MODIFIED:20230803T152614Z
LOCATION:
SEQUENCE:1
STATUS:CANCELLED
SUMMARY:nig2
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

I guess they're taking the RFC very literally. Incrementing SEQUENCE is only required if the change may jeopardize the participation status of the attendees, and changing the summary doesn't.

**Comment by ganthern** [comment]
can you try to reproduce it again and see what the calendar model says in the console?

**Comment by ganthern** [comment]
Google is sending a different organizer in the ical file than the sender of the invitation mail suggests. We ignore updates/cancellations that do not come in a mail that has the organizer as a sender.
 
Further investigations shows that google calendar will use the calendar ID which can be found by going to the settings
of the calendar and scrolling down to "Integrate calendar". It is the accounts gmail address for the first calendar, but some randomly generated mail address like `9bf766f5ee7fe7c2aa6b273d7892d55065e5506aec491fce354bce03f6b01ee2@group.calendar.google.com` for any additional calendars on the account.


We should maybe apply updates if they come in a mail that was sent by the address that sent the initial invitation.

**Comment by ganthern** [comment]
upgrading to a bug for now.
