### ISSUE TITLE
Sender and recipient names of email can not be copied

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5748]
It is not possible to copy the sender or recipient name of an email since they are neither selectable nor is there an action to copy them. If you do the copy action an a sender or recipient only the email address is copied.

Expected: It should be possible to copy the sender and recipient names in some way.

the parts in the red circles are not copyable (the dropdown copy option when clicking the address only copies the address, not the name)
![image](https://github.com/tutao/tutanota/assets/29049728/bc2ac80d-5664-4661-a92f-352f7a86143e)

## Test Notes
- [ ] The sender names are able to be highlighted
  - [ ] on Desktop
  - [ ] on Mobile
- [ ] The recipient names are able to be highlighted
  - [ ] on Desktop
  - [ ] on Mobile

**Comment by charlag** [comment]
@armhub do you refer to the mail editor? It is possible to select things in mail viewer
