### ISSUE TITLE
Deleted calendar entry in a series gets restored when editing all entries

### ISSUE THREAD

**Issue by Backspaze** [tutao/tutanota#5764]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
If you create a repeating event and delete one or multiple entries and then edit the entire series, the deleted event(s) gets restored.

**To Reproduce**
1. Go to 'Calendar'.
2. Create a repeating event.
3. Delete one or more of the entries.
4. Click on the 'Edit' icon and choose to edit all events.
5. Save the changes.
6. The previously deleted events are restored.

**Expected behavior**
When choosing the edit all events in a repeating series, previously deleted events should not be restored.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2 (but the bug is the same on all platforms)
 - Desktop Environment: N/A
 - Version: 3.116.8

**Additional context**
This was tested after installing [3.116.8](https://github.com/tutao/tutanota/releases/tag/tutanota-release-3.116.8) which included https://github.com/tutao/tutanota/issues/4860.

**Comment by ganthern** [comment]
This is specifically intended when the repeat rule or the start time of the whole event series changes because in those cases it's not possible to maintain the relation between the changed/altered instances of the series and the original time they occurred in.

Did you experience this with any edit operation that does not involve the start time or repeat rule?

We'll probably add a warning in cases where they are restored because of that.

**Comment by Backspaze** [comment]
@ganthern 

I could've sworn that this issue didn't exist in Microsoft 365, but when I tried to repeat it just now I noticed that it behaves the same as Tutanota, but it does display a warning as shown in the screenshot below, just as you suggested adding to Tutanota.

![bild](https://github.com/tutao/tutanota/assets/12255362/d6a0226b-fdf6-46c5-b085-f42acca02991)
**Screenshot translated to English**: Edit series. If you've changed certain events in the series, those changes will be deleted so the events matches the series again.

However, I'd like to add that Microsoft has three options for editing or deleting an event:
- This event
- This and all following events
- All events

I think that the option "This and all following events" is as must to add to Tutanota. With that option, the issue I brought up here wouldn't be an issue since you don't need to mess up all of the past events when bulk editing. I've added this as a [feature request on Reddit](https://www.reddit.com/r/tutanota/comments/15nhw6o/option_to_reschedule_or_delete_future_events_in_a/).

**Comment by ganthern** [comment]
Thank you! I'll close this one for now then. We're aware of the need for the "This and following" option, but it could take a bit - it's another paradigm shift and requires some improvements to the calendar in general.

The warning issue is tracked here: https://github.com/tutao/tutanota/issues/5775
