### ISSUE TITLE
android app to run get error on actual device

### ISSUE THREAD

**Issue by IRSHADKHAN11** [tutao/tutanota#5769]

**Comment by ganthern** [comment]
Hey, can you add a bit of context to this? You used the desktop template, but are talking about android? What is the error message?

**Comment by IRSHADKHAN11** [comment]
we have run the android app of tutanota on emulator without bug and when it's debugging through usb cable and run on actual device gets error.

**Comment by ganthern** [comment]
This is not actionable for us because we don't even have an error message or clear reproduction steps, I'll close this for now.
