### ISSUE TITLE
Improve display of passwords for confidential emails to external addresses

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#578]
Make the user explicitly click/tap an icon to reveal the password in the new mail dialog if there are some external recipients.

# Test Notes
- [x] ensure that "save password" feature of the browser is active
   - [x] log-in to an account and save the password when offered by the browser
   - [x] log-out and reload the page
   - [x] Ensure that the browser automatically fills in the credentials
- [x] log-in and open the dialog to send a new mail
- [x] add one external recipient and enable encrypted email sending
  - [x] see that password field with a password reveal button appears
  - [x] see that the browser did not fill in the field automatically with a previously saved password
  - [x] type in some password and check that the password is censored by default
  - [x] click the reveal password button and see the entered password in the plain text
  - [x] click the button again to censor the password
- [x] add another external recipient
  - [x] see that another password field with a password reveal button appears
  - [x] type in some password and check that the password is censored by default
  - [x] click the reveal password button and see the entered password in the plain text
  - [x] click the button again to censor the password
- [x] check that password reveal button only changes the text condition on the line the button is on and not in any other line
- [x] delete one of the recipients you added a password for
  - [x] see that the password field for that recipient disappears
- [x] add the same recipient again
  - [x] see that password field with already typed password appears
- [x] log-in with a premium account if not done already 
- [x] navigate to the calendar
   - [x] click on any day to plan an event
   - [x] expand the "guests" option to the right of the "title" field
- [x] add an external address to the guests
  - [x] see that password field with a password reveal button appears
  - [x] see that the browser did not fill in the field automatically with a previously saved password
  - [x] type in some password and check that the password is censored by default
  - [x] click the reveal password button and see the entered password in the plain text
  - [x] click the button again to censor the password
- [x] add another external address to the guests
  - [x] see that another password field with a password reveal button appears
  - [x] type in some password and check that the password is censored by default
  - [x] click the reveal password button and see the entered password in the plain text
  - [x] click the button again to censor the password
- [x] check that password reveal button only changes the text condition on the line the button is on and not in any other line
- [x] delete one of the recipients you added a password for
  - [x] see that the password field for that recipient disappears
- [x] add the same recipient again
  - [ ] see that password field with already typed password appears

**Comment by nif-tutao** [comment]
This issue fails testing as the password field for an external guest doesn't appear again after deleting and re-adding the same external guest in the calendar event.

**Comment by nif-tutao** [comment]
A new issue was opened 
#4520
