### ISSUE TITLE
Uncaught NotAuthorizedError when updating calendar

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#5793]
This happened to one user and I could reproduce it.

Setup:
* Account A has a calendar that is readonly-shared with account B
* Account A sends an invititation to account B to an event that is created in that shared calendar
* Account B receives the invitation and clicks on "yes"
* The response is sent, but the local update is attempted to be applied to the event in the shared calendar, which throws the error.

It's possible that this depends on the order the calendars are created / checked in.

## Test Notes
- [ ] shared calendar with read only access, can be invited and respond to invite without error (Setup above does not create error)
- [ ]  Add event to shared calendar, event shows up as expected
- [ ] Invite to normal (non-shared calendar) event, invitee can respond and response works without error (and event is added to calendar if applicable)
- [ ] On a shared calendar with read write access, can be invited and respond to invite without error (event should be added to calendar if applicable)
- [ ]  Can respond to calendar invites from other providers (event should be added to calendar if applicable)

```
Feedback v3.116.6 - NotAuthorizedError - PAID - linux
Client: linux
Type: PAID
Tutanota version: 3.116.6
Timestamp (UTC): Fri, 18 Aug 2023 08:32:04 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.116.6 Chrome/114.0.5735.248 Electron/25.3.2 Safari/537.36
NotAuthorizedError
Error message: 403: Nc6lTAw----0 | PUT /rest/tutanota/calendarevent/NTESuKA--B-0/MTY5MjQ0MjIxNTA5NA
Stacktrace:
NotAuthorizedError: 403: Nc6lTAw----0 | PUT /rest/tutanota/calendarevent/NTESuKA--B-0/MTY5MjQ0MjIxNTA5NA
at db (asset://app/common-min-905556a0.js:1:9871)
at p.onload (asset://app/worker.js:12:23418)
```

Console of the recipient:
```
[RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/NRh5Qaf----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/NTmt4Zm----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/NZQdjla----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/N5AAg0I----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/NRh5Qaf----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/NTmt4Zm----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/NZQdjla----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [RestClient] failed request GET https://test.tutanota.com/rest/tutanota/calendareventuidindex/N5AAg0I----0/G9datrBHVzP3aUWVmi4Brufe6yT2Md-7avk3mX7dTr8 404 Not Found 
(4) ['accessToken', 'v', 'cv', 'Accept']
 no body
Logger.ts:89 [CalendarModel] processing request for existing event instance
Logger.ts:89 [RestClient] failed request PUT https://test.tutanota.com/rest/tutanota/calendarevent/NTESuKA--B-0/MTY5MTgzNzcyNjA2Mg 403 Forbidden 
(5) ['accessToken', 'v', 'cv', 'Content-Type', 'Accept']
 [2138 characters]
Logger.ts:89 removed topmost modal component
Logger.ts:89 error 
Ke {name: 'NotAuthorizedError', message: '403: Nc6nY-O----0 | PUT /rest/tutanota/calendarevent/NTESuKA--B-0/MTY5MTgzNzcyNjA2Mg', data: undefined, stack: 'NotAuthorizedError: 403: Nc6nY-O----0 | PUT /rest/…\n    at p.onload (asset://app/worker.js:12:23418)'}
 NotAuthorizedError: 403: Nc6nY-O----0 | PUT /rest/tutanota/calendarevent/NTESuKA--B-0/MTY5MTgzNzcyNjA2Mg
    at db (asset://app/common-min-905556a0.js:1:9871)
    at p.onload (asset://app/worker.js:12:23418)
```

**Comment by charlag** [comment]
Reported again

> I can't accept an invite from my colleague

**Comment by wrdhub** [comment]
> I can't invite guests if I'm creating the event in a shared calendar that is shared with me and I have read/write permissions

Ah I didn't realize, but yeah that's the way it works for now. Because when you invite guests, only the organizer can send updates. This would cause issues with other users with write access being able to change that event (see also #5785). So we just don't allow adding guests for now.

**Comment by SkypLabs** [comment]
I am the user who originally reported this issue, and I can confirm that the problem is now fixed. Thanks!

**Comment by SkypLabs** [comment]
Hi,

The unauthorised error has been fixed, but the patch introduced a new behaviour which is far from being optimal.

I have read-only access to the personal calendar of my partner and she has read-only access to mine:

- Before the patch:
    - When I was invited to an event by my partner, once accepted, I could see the event in both my calendar and in hers.
    - I could hide my partner's calendar and still see the events I was supposed to attend.
    - I could add a reminder to the events we had in common as they were in my personal calendar for which I have write access.
- After the patch:
    - When I am invited to an event by my partner, once accepted, it only appears in her calendar, not mine.
    - It is hard to distinguish events we both need to attend from her personal events as they both appear in her calendar which has a different colour than mine. If I hide her calendar, I cannot see the events for which she invited me any more.
    - I cannot set reminders to events for which she invited me.

As you can see, the new behaviour introduced a rather problematic workflow.
