### ISSUE TITLE
Add Icon to open F1-Help

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#580]
Maybe a "help"-option in the main menu.

**Comment by antomor** [comment]
I could work on it, but is there some guideline for the icon to use?

**Comment by ganthern** [comment]
Hi @antomor, great that you're interested to contribute.  We use a combination of [ionicons](https://ionicons.com/) and custom icons and generate a number of [icon scripts](https://github.com/tutao/tutanota/tree/master/src/gui/base/icons).

You could just use the question mark icon ("Help"). The current plan for this F1-Help button is to convert the current support button in the drawer menu to a dropdown with the premium support option and an option to open the F1-Help. That's what the code for that button looks like now:
 https://github.com/tutao/tutanota/blob/eb04ae65f9ac31c017cc19da891e98ea7f2afe49/src/gui/nav/DrawerMenu.js#L46-L53

Creation of a Dropdown with buttons can be seen here, for example:
https://github.com/tutao/tutanota/blob/eb04ae65f9ac31c017cc19da891e98ea7f2afe49/src/gui/base/RichTextToolbar.js#L142-L161

The third argument to `attachDropdown()` makes it relatively easy to only show the dropdown for premium users and go directly to the F1 Help for free users, since they don't have the support mail option.

Thanks again for your offer!

**Comment by antomor** [comment]
Hi @ganthern , first of all thank you for the detailed suggestion. I have finally found the time to work on it, but I am trying to figure out how to run the app locally.
In particular, I have read the documentation guides, both [BUILDING](https://github.com/tutao/tutanota/blob/master/doc/BUILDING.md) and [HACKING](https://github.com/tutao/tutanota/blob/master/doc/HACKING.md), but I am not able to login locally, so I can't debug the main view.
Am I missing something? When I try to login I get the error "An unexpected error occurred. Please try again later."
Is there some way to test the protected views without logging in? 
Thank you in advance

**Comment by charlag** [comment]
@antomor first, you need to build for prod but until the release is made the server will lag behind the client model versions. I recommend you to branch off from the commit before model update and later rebase it.
