### ISSUE TITLE
Storage capacity Bug

### ISSUE THREAD

**Issue by Grkrz** [tutao/tutanota#5803]
I do not have any emails, files or any data besides contacts on my tutanota account but the Storage capacity show 46.1 MB used of 1 GB.

**Comment by charlag** [comment]
Please contact the support if you are a paying customer or hello@tutao.de if you are not

**Comment by Grkrz** [comment]
> Please contact the support if you are a paying customer or [hello@tutao.de](mailto:hello@tutao.de) if you are not

Thank you, I have been looking for that contact
