### ISSUE TITLE
Email address is not put into the login field after signup

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#5810]
How to reproduce:
1. Sign up for a new account.
-> When switching to the login form after signup the email address field is empty.
Expected: The email address selected at signup is put into the field.

This bug exists since 3.118.1. Locally the bug could not be reproduced with 3.118.1. The URL is the same in both cases (/login?noAutoLogin=true&loginWith=<email address>". Additional observation: In the error case the "saved credentials" button is visible in the login form. In the other case it is not.

## Test Notes:
* [ ] try the following in Firefox, Chrome, Safari, Linux Desktop, Windows Desktop, Max, Desktop, Apps
* [ ] without stored accounts
  * [ ] if you previously stored accounts make sure to reload the page after deleting all of them
  * [ ] create a new account and make sure that the email address is put into the login field
* [ ] with stored accounts
  * [ ] switch to the loginForm with "Different account"
  * [ ] create a new account and make sure that the email address is put into the login field
  * [ ] delete all accounts which should automatically redirect you to the loginForm
  * [ ] create a new account and make sure that the email address is put into the login field

**Comment by wrdhub** [comment]
Looking into this I saw that the email address would be filled in consistently when using firefox, but not when using chrome. I tested this with a local build on versions 3.118.1, 3.117.0, 3.116.8, so I do not believe this is related to the latest release.
In the LoginView the loginWith argument would always be filled in, even when it wasn't displayed. So the data is there, and something else is going wrong.

**Comment by ganthern** [comment]
probably related commit 4f3bd9b41a8b87b3a32b91dd3571fea613de50a4

and therefore also https://github.com/tutao/tutanota/issues/4630

**Comment by armhub** [comment]
Reproducing and debugging this issue is not easy and it is not consistent. This could be a timing issue. It seems like this.loginForm.promise.then is not resolved in LoginView.handleLoginArguments() and therefore the email address is not set.
We should observe it after releasing 3.118.1.

**Comment by kibhub** [comment]
The issue **is** reproducible where there are saved accounts in the client. Here are some notes:

- The URL is correct but the address does not appear in the field. 
- Refreshing the page fills the field with the correct address
- The issue is not reproducible if there are no saved accounts in the client.
- tested both cases on Firefox and Chromium
- v3.118.5

**Comment by kibhub** [comment]
More notes for native Apps. Tested signups with both stored accounts and no stored accounts. All on version 3.118.5

-  iOS:
    - inconsistent results.
    - Address does not appear most of the time
    - sometimes an incomplete address appears like `example@`
- Android:
    - address does not appear in both cases
- Desktop Linux:
    - address does not appear in both cases

**Comment by armhub** [comment]
On production system:
* Firefox: works
* Chromium: works
* Linux desktop client: does not work
* Android app: does not work

**Comment by nokhub** [comment]
The note with the saved accounts was very helpful! Since the loginForm is not recreated when switching from saved accounts to loginForm and signup, the loginForm promise is not resolved again and thus the url args are not read.
