### ISSUE TITLE
Cannot edit error msg on calendar event is misleading 

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5816]
We have the case where a user imported an event that they are not the organizer of, resulting in an event that they cannot edit. The message they get is "You can only edit parts of this event because it is part of an event series." This event is not a part of a series. A better error message should be displayed.

Implementation idea:
In the getReadonlyReason function on the CalendarEventModel, ReadonlyReason.SINGLE_INSTANCE is the fallback return type. It should probably be checked if the event is part of a series before returning that reason and a more generic fallback ReadonlyReason be created.

## Test Notes
- [x] The correct warning banner appears when editing an event
  - [x] that is part of a series
  - [x] that is organized by someone else
- [x] No banner is displayed outside of these conditions
- [x] The German translations are correct.

**Comment by rezbyte** [comment]
I noticed nothing can be edited when the user is not the organizer. Maybe the banner should display 'This event cannot be edited because you are not its organizer' instead?
