### ISSUE TITLE
Changing paid plans while having a contact list should be possible

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5817]
Currently, when a user tries to change between paid plans while a contact list is on their account, it throws a warning and prevents them from doing so. The only restriction should be going from a paid plan to a free account (since contact lists are a paid feature that are included with any new paid plan).

## Test notes
- [ ] A user with a contact list can switch between any new paid plan
- [ ] A user with a contact list cannot switch to a free plan

**Comment by wrdhub** [comment]
The server handles this check, fixed there.

**Comment by charlag** [comment]
opening until it's merged tutadb!484

**Comment by charlag** [comment]
closed by tutadb!484, tutadb!498
