### ISSUE TITLE
"System" color theme not selected in settings even when it is actually the selected theme

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5832]
After you select "System" for the color theme the app will change theme as expected, but if you close are reopen the app the color theme selection will say "dark" or "light" (depending on what the system is set to). If you change the system color (while the app is closed or open), the app will still switch color as expected.

To be clear, the app acts as expected, just that the selection in settings isn't right. 

Seen on ios, android, linux desktop.

Note: Unless there is an active whitelabel custom color theme. In that case, the text stays at "System", like it should

**Comment by ganthern** [comment]
> Test that when "system" preference is set dark/light is changed together with the system

this does not seem to work on ios. I have to re-select "system" or restart the app completely to assign the new theme after changing it on the system menu.
