### ISSUE TITLE
Allow selecting subscription (Free, Premium, Pro) at signup

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#584]

**Comment by armhub** [comment]
Payment with PayPal does not work. After selecting the PayPal account the "Click on button" text stays and you can not continue.

**Comment by mpfau** [comment]
fixed with 276f066

**Comment by bedhub** [comment]
276f066f994ab0d1605d387b264e0e6e5eb9f2f0

**Comment by armhub** [comment]
Whitelabel child signup must not show the subscription selection because it is anyway Premium.

**Comment by bedhub** [comment]
Whitelabel signup fix: 9d53368
