### ISSUE TITLE
MAPI does not attach files unless already logged in

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5850]
v3.117.0
v3.118.3

## How to Reproduce
On Windows:
1. In Desktop settings of the app make sure that the app is registered as default mail app
2. In Windows settings make sure that the app is indeed default app and is set as `mailto:` protocol handler
3. Close the app
4. Open Libreoffice
5. Do file -> send -> email
6. See that after the app has been opened and login has been completed the editor opens but no files are attached

## Test Notes
- Windows
   - [x] You can send a file through email through MAPI api
   - [x] The reproduce steps results in an attached file instead of a email without attachments

- All platforms
  - [ ] The temp folder is empty after starting the app
  - [x] Attach files works
  - [x] Download files works
  - [ ] After exiting the application, the temp folder is empty

**Comment by rezbyte** [comment]
The temp folder is not being cleared during startup nor exit on Windows. It seems to create a new random directory inside temp while leaving the previously created folders be. The temp folder is being cleared on Linux.

**Comment by murilopereirame** [comment]
> The temp folder is not being cleared during startup nor exit on Windows. It seems to create a new random directory inside temp while leaving the previously created folders be. The temp folder is being cleared on macOS & Linux.

On Windows fs can't delete files if they still open in some application. I tested and seems that if we close the open file before closing the app, it deletes de folders correctly, and if the file is open, fs throws an uncaught error leading in this message visible for a couple of milliseconds

![image](https://github.com/tutao/tutanota/assets/34790144/2019a037-8805-459e-9b4f-913fb8821922)

**Comment by ganthern** [comment]
Which application has the file open? We could do something about this if it's tuta, but otherwise we can't know if the files are still being used and I don't think it's useful to inform the user about this.

Catching that error would be a good idea though

**Comment by murilopereirame** [comment]
> Which application has the file open? We could do something about this if it's tuta, but otherwise we can't know if the files are still being used and I don't think it's useful to inform the user about this.
> 
> Catching that error would be a good idea though

External applications, so we can't control if they still with the file open

**Comment by charlag** [comment]
Don't we show the progress dialog until the other app is done with the file?
