### ISSUE TITLE
CancelledError: stop retry processing

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#5866]
This has come up quite a bit since version 3.116.8.

Many users complain about it happening after bringing computer out of sleep mode.

CancelledError
Error message: stop retry processing after service unavailable due to reconnect
Stacktrace:
CancelledError: stop retry processing after service unavailable due to reconnect
at asset://app/worker.js:1:15708
at async vs.eventQueueCallback (asset://app/worker.js:1:13838)

**Comment by charlag** [comment]
This bug has another part, one issue was that ProtocolProxy changes introduced `ServiceUnavailableErrors` where there should be none but there's also a part where `EventBusClient` is doing something wrong since the `CancelledError` leaked  to UI thread
