### ISSUE TITLE
Tutanota not following system theme on linux

### ISSUE THREAD

**Issue by jeremiah-miller** [tutao/tutanota#5886]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
I have the tutanota app set to follow the system theme, however when I switch to a dark theme it doesn't update to the dark theme. Other electron apps like Signal do follow it. Here's the commands I run to switch to dark theme, I believe the gsettings are the main relevant ones:

```
#switch to dark theme for gtk and qt
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark

sed -i 's/style=Adwaita.*/style=Adwaita-Dark/g' .config/qt5ct/qt5ct.conf

#change terminal theme to dark
set -U GAMMASTEP_TIME 'night'
pkill -USR2 fish # fish sets the dark theme when it receives SIGUSR2
```
I'm using sway/wayland on Arch Linux. I have tutanota installed via the AUR package tutanota-desktop-bin. Also relevant are the environment variables I set before launching sway:
```
MOZ_ENABLE_WAYLAND=1
MOZ_DBUS_REMOTE=1
QT_QPA_PLATFORM=wayland
QT_QPA_PLATFORMTHEME=qt5ct
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
_JAVA_AWT_WM_NONREPARENTING=1
CLUTTER_BACKEND=wayland
SDL_VIDEODRIVER=wayland
GTK_OVERLAY_SCROLLING=1
GTKM_INSERT_EMOJI=1
GTK_CSD=0
GTK_BACKEND=wayland
GDK_DPI_SCALE=1.25
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=GNOME
SYSTEMD_COLORS=256
XAUTHORITY=$HOME/.Xauthority
```

**To Reproduce**
1. Launch Tutanota
2. Go to settings, confirm theme is set to "System". Tutanota is in light mode for me since I have light mode active while the sun is up.
3. Run the script shown above (probably only need the gsettings commands)
4. Tutanota is still in light mode, other electron apps have switched

**Expected behavior**
Tutanota should switch to a dark theme along with all the other apps

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Sway 1:1.8.1-1
 - Tutanota v3.118.7

**Comment by charlag** [comment]
just FYI It works under GNOME and using GNOME setting.

**Comment by ganthern** [comment]
I assume that there's another place we could check that Signal covers but that we're ignoring

**Comment by charlag** [comment]
I just tried with gsettings and it didn't work so I assume that's not enough?
We are just reacting to the signal from Electron which I'd imagine Signal also be doing

**Comment by jeremiah-miller** [comment]
A quick search through signal desktop, it looks like they use nativeThemeListener to get the system theme

If the setting from gnome setting works, maybe there's another setting i need to set as well that i missed when i made my script?

**Comment by jeremiah-miller** [comment]
It's especially weird that https://github.com/signalapp/Signal-Desktop/issues/5091 exists and i don't see the issue with signal, but they also reference some upstream issues in electron that might be the culprit?

**Comment by slagiewka** [comment]
Try bumping the Electron by two fix versions: https://releases.electronjs.org/release/v26.2.4

**Comment by rezbyte** [comment]
Is this issue still occurring with the latest version (3.118.25) @jeremiah-miller?

**Comment by jeremiah-miller** [comment]
Yes, and 3.118.27

**Comment by charlag** [comment]
I think it will be fixed with an Electron update

**Comment by charlag** [comment]
Will be fixed with Electron 27

**Comment by slagiewka** [comment]
> Will be fixed with Electron 27

With which change exactly?

**Comment by charlag** [comment]
https://github.com/electron/electron/pull/40010

**Comment by slagiewka** [comment]
> [electron/electron#40010](https://github.com/electron/electron/pull/40010)

This was backported to v26 with https://github.com/electron/electron/pull/40011 and released in Electron that's apparently already in this codebase (and releases) with 3c3aa607f56ffcb7d87f96ae30f569075d0b49a4.

If this is still not working, updating to v27 most likely won't yield any changes here.

**Comment by jeremiah-miller** [comment]
Ohhh, I just realized why this wasn't working. It's cause I wasn't starting tutanota with `tutanota-desktop --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland`, so it was running in xwayland and couldn't see my settings on the wayland side :upside_down_face:
