### ISSUE TITLE
Trash unread emails count

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#5892]
**Bug in mobile app**

**Describe the bug**
When I click "Clear Folder" in either "Trash" or "Spam" the items will get deleted but the unread count will not get updated.

**To Reproduce**
1. Have unread mail in either "Trash" or "Spam"
2.Go to that folder
3.Click "Clear Folder".
4. see the unread count does not change

**Expected behavior**
I would expect the count to be removed since all mail has been removed.

**Screenshots**

![Screenshot_20230917-195528.png](https://github.com/tutao/tutanota/assets/143354470/afc436fe-85b9-4047-a3a6-548c5a43b5dc)

![Screenshot_20230917-195507.png](https://github.com/tutao/tutanota/assets/143354470/3d2d753c-1d1e-4209-b0d3-ac928cb0a6f3)

**Smartphone (please complete the following information):**
 - Device: (Realme C21Y)
 - OS: (Android 11)
 - Version (3.118.6)

**Comment by jan1577** [comment]
Also occurs in the web app quite frequently

**Comment by rezbyte** [comment]
I have confirmed this in the web app & the Linux desktop. Although the icon disappears after a short time.
