### ISSUE TITLE
event sometimes not displaying properly at month end

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#5896]
Events between February and March 2024 are not displayed properly

**To Reproduce**
1. Go to Calendar
2. Create Event between February and March (for example 26th February - 06th March 2024)
4. The event will only display until 03rd of March 

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/139225084/19d4eaf3-4dea-4808-9b3f-60b2892fb832)

**Additional context**
I could not identify the clear edges as if the event is longer or adjusting the start/end date sometimes does not reproduce.
The issue was reproduce-able on Desktop & Mobile

## Test Notes
* [ ] re-test this bug
* [ ] retest #5839 
* [ ] test https://github.com/tutao/tutanota/issues/5920
* [ ] try other configurations with short events (non-repeating, shorter than 15 days)
* [ ] the events are also still displayed correctly after reloading the page
* [ ] this also works in situation with multiple clients working on the same calendar (shared calendar, just multiple tabs on the same calendar)
* [ ] the events are also displayed correctly when switching betweeen months

**Comment by ganthern** [comment]
possibly related to https://github.com/tutao/tutanota/issues/5839

**Comment by ganthern** [comment]
this only happens right after adding the event, correct? reloading the calendar page fixes the display for me.
