### ISSUE TITLE
< becomes &lt in event title

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#5897]
**Describe the bug**
Issue with "<" and HTML escaping in event title

**To Reproduce**
1. Go to Calendar
2. Create event
3. Put "<" in title
4. See &lt instead

**Additional context**
This does not occur with any other characters or other places as far as tested

**Comment by paw-hub** [comment]
## Test notes
- [ ] Create a calendar event. Type `<b>Title</b>` into the title, and `<i>Location</i>` into the location of a calendar event.
- [ ] Verify that <> isn't replaced with any HTML entities, and that `<b>Title</b>` is displayed on the title of the editor
- [ ] Save and quickly view the event. Verify that the title and location still show up as `<b>Title</b>` and `<i>Location</i>` respectively, and verify that this still holds true when editing the event.
