### ISSUE TITLE
Adding external image rule fails when IndexedDB is disabled

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#5915]
> When "always block the sender" is used: it doesn't work

```
Client: Browser
Type: PAID
Tutanota version: 3.118.8
Timestamp (UTC): Thu, 21 Sep 2023 07:46:42 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
DbError
Error message: could not create transaction: NotFoundError, IDBDatabase.transaction: 'MetaDataOS' is not a known object store name> createTransaction/<@https://mail.tutanota.com/worker-search-6cb23f77.js:1:2797

Stacktrace:
DbError. could not create transaction: NotFoundError, IDBDatabase.transaction: 'MetaDataOS' is not a known object store name> createTransaction/<@https://mail.tutanota.com/worker-search-6cb23f77.js:1:2797
```

Strawman repro:
1. Open the app
2. Delete IndexedDB
3. Open an email and try to "always allow"/"always block" the sender

Another possible repro:
1. Disable indexedDB
2. Open the app
3. Open an email and try to "always allow"/"always block" the sender

## Context
The error originates here:

https://github.com/tutao/tutanota/blob/3c07380f96ec735391ffcfea47504ed7a323543e/src/api/worker/search/DbFacade.ts#L166

We could probably silently catch and ignore errors when adding image rules fails.

## Test Notes
Regression Tests only because we can't reproduce this
* [ ] receive some mail with external image links
* [ ] click "show" in the external content banner 
  * confirm that the images show up
  * navigate away from the mail, and back - the images are not shown anymore
* [ ] click "always trust" on the banner
  * images are shown, and it is persistent over navigation and app restarts
* [ ] click "always block" on the banner
  * banner goes away, images are not shown and don't reappear
* [ ] on a conversation with blocked images, the more menu contains "show images" and resets any previous block decision
* [ ] on a not-blocked mail, the option is "block external content" and resets the previous decision

**Comment by ganthern** [comment]
Turns out it's surprisingly hard to disable idb. It could be that the best way to reproduce is to manually deleting the config table.
