### ISSUE TITLE
File attachment popup does not fit the screen

### ISSUE THREAD

**Issue by madzisko** [tutao/tutanota#5919]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
If you receive an email with two attachments where files have short names - they are displayed in the same line. While trying to download the second attachment the popup does not fit the window and therefore it is impossible to download it.

**To Reproduce**
1. Get/send email with two attachment which have short names e.g. 'file1.jpg' and 'file2.jpg'.
2. The attachments will be displayed in the same line due to its short names.
3. Try to download the second attachment.
4. Option to download is not visible, because part of the  popup is outside the screen.

**Expected behavior**
Names of attachments can be displayed one per line.
OR
The popup will be aligned to the left of the window.

**Screenshots**
![IMG_20230921_191846](https://github.com/tutao/tutanota/assets/18243556/bcc235b6-e65b-4246-a3d6-8297b0558777)
![IMG_20230921_191949](https://github.com/tutao/tutanota/assets/18243556/ff1041ce-87c5-4401-9924-6b52af68a5cc)
![IMG_20230921_191922](https://github.com/tutao/tutanota/assets/18243556/0247b4ea-d08d-43da-a0c9-85f78f853847)

**Smartphone:**
 - Device: OnePlus Nord2 5G
 - OS: Android
 - Version 13

## Test notes
test this for android, ios and on the desktop:

* [ ] The file attachment bubble still working
* [ ] When you click and attachment it shows the open/download popup
* [ ] If the attachment is close to the edge of the screen, the popup should have a margin
* [ ] The popup doesn't overflow the screen

**Comment by charlag** [comment]
Thank you for the report!
