### ISSUE TITLE
failed connection attempts when searching… block my IP from accessing Tutanota services

### ISSUE THREAD

**Issue by thob** [tutao/tutanota#5947]
**Describe the bug**
I guess this is a bug. If I initiate a search which needs to index first – on Linux Desktop – the connection to the server fails after the TLS handshake. This results in Tutanota blocking my IP. I can reproduce this.

**To Reproduce**
1. Go to Search
2. Search/index into the past
3. desktop client goes offline and my IP is blocked from accessing any tutanota IPs (support confirmed this)

**Expected behavior**
Search fully indexed and connectd

**Desktop:**
 Pop!_OS 22.4
 
**Additional context**
Talked to support already. That's why I tried to reproduce it, and I can confirm I can reproduce it here.

**Comment by charlag** [comment]
Please stay in contact with support, we can't discuss the details of your connection publicly anyway

**Comment by thob** [comment]
I will. Just seems like a bug to me.

**Comment by thob** [comment]
Just happened again. Each time it takes a working day to remedy, this is not really acceptable for a paid service which used for business!
