### ISSUE TITLE
allow deleting credentials when offline

### ISSUE THREAD

**Issue by kib42** [tutao/tutanota#5954]
When offline, I cannot delete stored credentials. The client shows a connection error when clicking on delete.

As a user, I would like to be able to delete local credentials and see a notification that the session cannot be invalidated without an internet connection.

Tested on all native apps, v3.118.12

**screenshot**

![image](https://github.com/tutao/tutanota/assets/104761667/849f7b9f-98be-4db2-bb3e-8f5d07210ee0)

## Test notes
- [ ] You can remove an account when online like normal
- [ ] You can remove an account when offline

**Comment by charlag** [comment]
I don't like labeling things that work as designed as bugs, it's very misleading.
If we want to change this we should bring it up to refinement or open it as "idea" or something like that.

**Comment by ganthern** [comment]
it was not labeled as a bug though?

**Comment by charlag** [comment]
oh I misread that my bad

**Comment by kibhub** [comment]
@charlag the title was also a bit misleading. I think it is clearer now.
