### ISSUE TITLE
Firefox specific execCommand no longer needed

### ISSUE THREAD

**Issue by johanneswilm** [tutao/tutanota#5987]
Hey,
Firefox stopped requiring disabling controls five years ago [1]. So you are now able to remove your last usages of `document.execCommand` for things like "enableInlineTableEditing" or "enableObjectResizing".

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1490641

**Comment by charlag** [comment]
Our own only usage of it is for copying text, the ones you mentioned are from Squire

**Comment by johanneswilm** [comment]
@charlag OK, but I found them in your repository: https://github.com/tutao/tutanota/blob/7f0f09197b69b9e729e4da3b4002db12eccf6054/libs/squire-raw.mjs#L2103

Should I be reporting this somewhere else then?

**Comment by johanneswilm** [comment]
ok @charlag I already had them remove it in squire: https://github.com/fastmail/Squire/issues/439 . So you should get that when you update your dependency.

I believe you are right about the clipboard flag in Firefox.

Thanks for looking at this.

**Comment by johanneswilm** [comment]
ok @charlag I already had them remove it in squire: https://github.com/fastmail/Squire/issues/439 . So you should get that when you update your dependency.

I believe you are right about the clipboard flag in Firefox.

Thanks for looking at this.

**Comment by charlag** [comment]
Thank you for reporting this!  We'll update Squire soon
