### ISSUE TITLE
losing email when choosing attachment on android 

### ISSUE THREAD

**Issue by njamescouk** [tutao/tutanota#5992]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
compose email, click paperclip to choose file to attach, get asked to log in again and the drafted email has disappeared.

**To Reproduce**
as above 

**Expected behavior**
on returning from selecting attachment i see the email just drafted.

**Screenshots**
na

**Desktop (please complete the following information):**
Firefox on android

**Smartphone (please complete the following information):**
 - Device: nokia 5.1
 - OS: android
 - Browser Firefox 

**Additional context**

**Comment by charlag** [comment]
Hi
It seems like your browser is getting evicted due to memory pressure. There's not so much we can do about it expect auto-saving the draft and this is tracked separately already.
We recommend that you use Android app instead.
