### ISSUE TITLE
Tutanota crashes very often - Linux

### ISSUE THREAD

**Issue by LaPeste** [tutao/tutanota#5998]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
- [x] I've searched and did not find a similar issue.

**Describe the bug**
The desktop application crashes from time to time. Nothing specifically is done, I receive a desktop notification (email received or calendar event) and when either clicking on the notification or on the application in the taskbar **sometimes** the application just closes. 

**To Reproduce**
Just focus on the application when there is a notification that needs to be checked.

**Expected behavior**
It should not crash.

**Screenshots**
Nothing to show.

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - Desktop Environment: Gnome on Wayland
 - Version: `GNOME Shell 44.5`

**Additional context**
Tutanota is installed as a flatpak application. I tried to launch the app from the terminal, hoping to come back to you with a clear error. Unfortunately there seems to be a lot of noise, so I can't really tell if my logs show anything useful (but I doubt).
I have attached them here as they don't contain anything sensitive.
[tutanotaLogs.log](https://github.com/tutao/tutanota/files/12929371/tutanotaLogs.log)

**Comment by LaPeste** [comment]
The logs shown always appear at the startup of the application. What I'm trying to say is that those errors aren't what make the application crash. In fact, as said already, when the application crashes no new log line is reported on top of what is shown.
So I'm not sure the GPU errors have anything to do with the crash.

**Comment by kibhub** [comment]
I have received one other report which described Tutanota behaving weirdly on the current Debian testing and Gnome.

**Comment by LaPeste** [comment]
If there's anything I can help you with (e.g. get some more logs etc) let me know.

**Comment by charlag** [comment]
I strongly feel that this is a Flatpak+Wayland problem, did you have a chance to test other configurations?

**Comment by LaPeste** [comment]
I'll give it a go on X.org then. I'll report back when I have info.

**Comment by pq2** [comment]
I have the same problem with the Flatpak version.
OS: KDE neon 5.27
DE: Plasma 5.27.9 on Wayland

**Comment by charlag** [comment]
Okay please file an issue under https://github.com/flathub/com.tutanota.Tutanota/

we switched Flatpak to use Wayland but apparently this isn't very stable yet
