### ISSUE TITLE
Outlook appointment response does not set the participant's status.

### ISSUE THREAD

**Issue by r-alto** [tutao/tutanota#6006]
- [X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X ] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I create an Outlook appointment and invite a participant using Tutanota Email. The participant receives the appointment invitation and responds, for example. B. with yes. The appointment is entered in Tutanota's calendar and a reply is sent to Outlook. However, the participant status is not updated in Outlook.
I have no control whether the participant has accepted or declined.

**To Reproduce**
1. Go to Outlook plan a appointment with a participant with tutanota email 
2. Click on yes to accept the appointment'
3. Go to Outlook, open the appointment and click to status
4. You see no changed state

**Expected behavior**
I expect, that the state is set, accept or not accept the appointment.

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/63064300/eb5fd386-88cc-4a3f-b26e-e28c3bc8d523)

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser Microsoft Edge
 - Version Version 118.0.2088.46 (Offizielles Build) (64-Bit)

**Comment by ganthern** [comment]
Hi @r-alto,

Is there a way to manually import the .ics attachment from the tutanota users response? If yes, it would be useful to know if there are any error messages when trying it or on the mail that the response came with.

**Comment by r-alto** [comment]
If I try to import this file an error occurs.
![image](https://github.com/tutao/tutanota/assets/63064300/a4e30cf8-705d-4cbc-a12c-c36ba50ffe73)
Microsoft Outlook 2016 MSO (Version 2309 Build 16.0.16827.20130) 64 Bit

**Comment by r-alto** [comment]
If I delete an appointment in Outlook, this has no effect on the appointment in tutanota, i.e. H. the appointment will be e.g. B. not deleted.

**Comment by wrdhub** [comment]
We have are going to look into this issue (not just on outlook, but other places too) more deeply soon. I am going to close this issue and link it to the other one that was created.

https://github.com/tutao/tutanota/issues/7564
