### ISSUE TITLE
the desktop client does not receive notifications

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#6010]
currently the desktop client has problems connecting to sse

## Test Notes 
on all desktop platforms and ios/android:
* [ ] sending mail & uploading attachments still works
* [ ] calendar notifications are triggered even if created on another client
* [ ] mail notifications are shown correctly

**Comment by charlag** [comment]
Didn't test on mobile yet oops sorry

**Comment by charlag** [comment]
Now all tested
