### ISSUE TITLE
u2f keys registered on the new domain do not cause the dialog when used on the old domain

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#6015]
* register a u2f key through the desktop client (or new domain web app)
* try to use it on the old domain login page in the web app
* see that the dialog just says "auth failed"

it should say that it can't use the key here and show a link to a valid login domain.

affects 3.118.15

**Comment by charlag** [comment]
It does not work at all on the test system (yet) because of invalid URL handling bug  and I could not reproduce it locally but there are other issues where it does not open the login url correctly. I'll address that.
