### ISSUE TITLE
Tutanota in Firefox always shows 'Offline Reconnecting' if Firefox is using proxy

### ISSUE THREAD

**Issue by Refutable4890** [tutao/tutanota#6020]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Tutanota in Firefox always shows 'Offline Reconnecting' if Firefox is using proxy.

**To Reproduce**
1. In Firefox, visit `about:preferences#general` -> Network Settings -> Settings… -> make Firefox use proxy
2. Log in Tutanota
3. See 'Offline Reconnecting'

**Expected behavior**
Tutanota shows 'Online All up to date'.

**Desktop:**
 - OS: Windows
 - Browser: Firefox
 - Version 118.0.2

**Comment by charlag** [comment]
It seems like Websocket does not work over this proxy. Do you see any errors in the devtools console/logs?

**Comment by charlag** [comment]
Then the problem is between Firefox and the proxy, we have no influence there, I'm sorry.
