### ISSUE TITLE
redeeming gift card process while having a registered U2F key gets stuck

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6022]
When I try to redeem a gift card and confirm my U2F key, the 2FA dialogue does not go away unless I click cancel. 

**Note** that clicking cancel allows me to redeem the card.

See screenshot:

![image](https://github.com/tutao/tutanota/assets/104761667/c64529df-26a7-4b58-90c3-3b5a5a544d16)

## Test Notes
- [ ] Try to redeem a gift card on an account that has 2fa (not logged in), after confirming key the 2fa dialog will close and proceed to next gift card step
- [ ] Try to redeem a gift card on an account that does not have 2fa (not logged in), after logging it will proceed to next gift card step

**Comment by charlag** [comment]
@kibhub  is it webapp or desktop

**Comment by kibhub** [comment]
Cannot do this on desktop. This happens when you redeem a gift card via URL on the web client and choose "Use existing account".
