### ISSUE TITLE
Update alarm permissions

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6045]
> [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM), the permission introduced in Android 12 for apps to schedule exact alarms, is no longer being pre-granted to most newly installed apps targeting Android 13 and higher (will be set to denied by default)

However I think we should instead of asking for alarms just ask for `USE_EXACT_ALARM` permission:

>  [Calendar or alarm clock apps](https://support.google.com/googleplay/android-developer/answer/12253906#exact_alarm_preview) need to send calendar reminders, wake-up alarms, or alerts when the app is no longer running. These apps can request the [USE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#USE_EXACT_ALARM) normal permission. The USE_EXACT_ALARM permission will be granted on install, and apps holding this permission will be able to schedule exact alarms just like apps with the [SCHEDULE_EXACT_ALARM](https://developer.android.com/reference/android/Manifest.permission#SCHEDULE_EXACT_ALARM) permission.

But as far as I understand Google will manually approve the apps that request this

more info: https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

## Test Notes
* [ ] Setting an alarm on a device with API >= 33 works
* [ ] Setting an alarm on a device with API < 33 still working
* [ ] The alarm notification is displayed in both cases

**Comment by wrdhub** [comment]
We are going to roll this one back and commit at another time.
