### ISSUE TITLE
Tor Browser being denied any connection to mail.tutanota.com

### ISSUE THREAD

**Issue by cthulhubuddha** [tutao/tutanota#6047]
Yes, Tor Browser is not on the list of supported browsers, but as a firefox variant it has always worked until yesterday. Using the latest Tor Browser version 13.0.1, mail.tutanota.com now effectively denies the connection from TB. I'm confused why a very reputable and secure email solution would not allow privacy as well.

**Comment by charlag** [comment]
Probably the gateway you are using is blocked due to abuse. Please try to change the circuit or contact support. There's absolutely nothing in the code that should make Tor Browser not work.

**Comment by Gitchick57** [comment]
It would be nice if Tutanota had an onion site like Proton does.



Oct 27, 2023, 8:23 AM by ***@***.***:

**Comment by cthulhubuddha** [comment]
Nope. Multiple circuits, all giving the same browser not supported error:

![image](https://github.com/tutao/tutanota/assets/43973651/9a0266f1-0bb9-441d-a151-5c2e88416992)

**Comment by charlag** [comment]
Oh I see

We require WebAssembly since the last release:
https://github.com/tutao/tutanota/pull/5979

which should work depending on the security level in the browser
