### ISSUE TITLE
SecurityError on iOS < 15.5

### ISSUE THREAD

**Issue by nateworks** [tutao/tutanota#6056]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Error while logging in

**To Reproduce**
(First email check after update version 3.118.22)
-go to any browser or to the tutanota mobile app
-on open/login page you will receive this error message

**Expected behavior**
You should just be able to login and access the email

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/101207974/17edfa38-0980-4fd4-87c8-189298bee157)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: ios 15.4.1
 - Version 3.118.22

**Additional context**
Pasted is the error message copied:

Feedback v3.118.22 - SecurityError - UNKNOWN - ios

 Client: ios
 Type: UNKNOWN
 Tutanota version: 3.118.22
 Timestamp (UTC): Mon, 30 Oct 2023 18:48:32 GMT
 User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
SecurityError
 Error message: The operation is insecure.
Stacktrace: 
Worker@[native code]
@asset://app/main-8d12a609.js:1:15117
asyncFunctionResume@[native code]
@asset://app/main-8d12a609.js:1:95273
@asset://app/main-8d12a609.js:1:95342
asyncFunctionResume@[native code]
@asset://app/app.js:1:77839
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]

**Comment by nateworks** [comment]
I was able to downgrade the app and the issue has been fixed for the mobile app only. All other places like browsers still give the same issue...

**Comment by charlag** [comment]
this is where the error occurs:
https://github.com/tutao/tutanota/blob/3c3aa607f56ffcb7d87f96ae30f569075d0b49a4/src/api/main/WorkerClient.ts#L52

did our CSP changes break it?

**Comment by nateworks** [comment]
Possible, not entirely sure what caused it if i’m being honest. It would make sense tho since even though the app is working the sites don’t. But what confuses is me is on any other machine like my laptop web and app login works fine no issues. Just on mobile where the issue occurs.

Nov 2, 2023, 04:28 by ***@***.***:

**Comment by charlag** [comment]
The issue occurs due to `worker-src`  CSP directive which is supported since iOS 15.5 to which all devices that are on iOS 15 can upgrade to. We do not support older OSes than 15.

We should try to handle the support gracefully but we will not support outdated browsers.

and, btw, your device supports iOS 17 (!).

**Comment by Lololore** [comment]
Could somebody explain how to downgrade the app? I have no idea how to continue using the mobile app. Thanks a lot!

**Comment by nateworks** [comment]
> Could somebody explain how to downgrade the app? I have no idea how to continue using the mobile app. Thanks a lot!

I used Appstore++ which is something only available to jailbroken devices (iirc). I could be wrong but you could also probably figure out a way to downgrade using an IPA file. If you need more instructions to downgrade via jailbreak i'd be happy to explain further.

**Comment by Lololore** [comment]
> > Could somebody explain how to downgrade the app? I have no idea how to continue using the mobile app. Thanks a lot!
> 
> I used Appstore++ which is something only available to jailbroken devices (iirc). I could be wrong but you could also probably figure out a way to downgrade using an IPA file. If you need more instructions to downgrade via jailbreak i'd be happy to explain further.


I would actually be thankful for more instructions to downgrade via jailbreak. My device is not jailbroken, would you explain me how to proceed?

**Comment by nateworks** [comment]
> > > Could somebody explain how to downgrade the app? I have no idea how to continue using the mobile app. Thanks a lot!
> 
> > 
> 
> > I used Appstore++ which is something only available to jailbroken devices (iirc). I could be wrong but you could also probably figure out a way to downgrade using an IPA file. If you need more instructions to downgrade via jailbreak i'd be happy to explain further.
> 
> 
> 
> 
> 
> I would actually be thankful for more instructions to downgrade via jailbreak. My device is not jailbroken, would you explain me how to proceed?
> 
> 
> 
> 

reply with your discord it'll be easier that way

**Comment by Lololore** [comment]
> > > > Could somebody explain how to downgrade the app? I have no idea how to continue using the mobile app. Thanks a lot!
> > 
> > 
> > > 
> > 
> > 
> > > I used Appstore++ which is something only available to jailbroken devices (iirc). I could be wrong but you could also probably figure out a way to downgrade using an IPA file. If you need more instructions to downgrade via jailbreak i'd be happy to explain further.
> > 
> > 
> > I would actually be thankful for more instructions to downgrade via jailbreak. My device is not jailbroken, would you explain me how to proceed?
> 
> reply with your discord it'll be easier that way

I don’t have one 😅 do you think we can communicate through github or through another way? If not, I’ll create an account

**Comment by Ectalite** [comment]
So for the people under iOS 15.5, is there a way to access the webmail ?
I think I should just consider going to ProtonMail...

**Comment by nateworks** [comment]
Tbh, don’t think so. It looks like it’s just an unsupported version. I’ve been told skiff mail is also a good alternative. Am considering it tbh… 

Nov 13, 2023, 14:39 by ***@***.***:

**Comment by ganthern** [comment]
Hello :wave:

Is your iOS version up-to-date? If this occurs on a device with iOS >= 15 and Safari >= 15.5 this would be very interesting information.

Otherwise, please update your Phones software - we cannot implement fixes for versions older than iOS 15.

**Comment by Cybercountry** [comment]
Hello,

I'm having problems on IOS 15.0.2, Iphone 6s.
The last available update would be 15.8. If I update to this version, is it guaranteed that the application will work again?

I have avoided updating to the latest version due to battery problems, but if this is the solution I will do it.

**Comment by nateworks** [comment]
> Hello,
> 
> 
> 
> I'm having problems on IOS 15.0.2, Iphone 6s.
> 
> The last available update would be 15.8. If I update to this version, is it guaranteed that the application will work again?
> 
> 
> 
> I have avoided updating to the latest version due to battery problems, but if this is the solution I will do it.

Most likely would do the trick. Honestly i don't think risking the health of ur battery is worth it. It's probably better to either downgrade the app in whatever way you can (what i'm doing), getting a new phone, or just switching mail apps. The problem is just support for later versions.

**Comment by Cybercountry** [comment]
> > Hello,
> > I'm having problems on IOS 15.0.2, Iphone 6s.
> > The last available update would be 15.8. If I update to this version, is it guaranteed that the application will work again?
> > I have avoided updating to the latest version due to battery problems, but if this is the solution I will do it.
> 
> Most likely would do the trick. Honestly i don't think risking the health of ur battery is worth it. It's probably better to either downgrade the app in whatever way you can (what i'm doing), getting a new phone, or just switching mail apps. The problem is just support for later versions.

I understand. I'll see what I can do but most likely I won't be using tuta mail on my cell phone anymore.
I wish it was possible to use a web version, but I have the same problem in all the browsers I've tested.
