### ISSUE TITLE
Issues with Trash category

### ISSUE THREAD

**Issue by MarcusPy** [tutao/tutanota#6057]
Sometimes emails are moved to trash automatically and they don't appear there, despite the marker for unread emails being shown.

 - OS: Windows 10, KB5031445
 - Tutanota desktop app: 3.118.22
![1](https://github.com/tutao/tutanota/assets/107936046/e557f49d-592a-4d51-85fa-0e93fe026130)
![2](https://github.com/tutao/tutanota/assets/107936046/11159ccf-2134-40cb-b443-c0c069567031)

**Comment by ganthern** [comment]
What do you mean they're moved there automatically? Do you mean they do this in an unexplained way or do you use inbox rules?

**Comment by charlag** [comment]
In the screenshot you have subfolders of trash, I suspect they have something in them

**Comment by realpixelcode** [comment]
> In the screenshot you have subfolders of trash, I suspect they have something in them

Probably not the best UI design then 😬
