### ISSUE TITLE
Update text for the U2F migration

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6061]
We want to adapt the current text to make sure our users know exactly which steps they have to do to move a U2F second factor to the new domain.

"Please accept this login from another tab or via app."
"Then login here again and accept the login from the other tab."

After logging in the user will be asked to set a U2F second factor.

This is related to https://github.com/tutao/tutanota/issues/5638

**Comment by charlag** [comment]
superseded by #6070
