### ISSUE TITLE
Event reminders use old event name

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6075]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
The name in the event reminders do not update when the event is changed.

**To Reproduce**
1. Create an event with reminder(s).
2. Edit the name of the event.
3. Wait for the reminder(s) to appear.
4. The reminder(s) will use the name before the edit.

**Expected behavior**
The name in the event reminder should change after the edit.

## Test Notes
Should be tested on the web client (Firefox, Chrome)
- [ ] The reminders use the new name after their event is renamed
- [ ] Any functionality that posts/puts & gets via the REST API still works

**Comment by charlag** [comment]
It is  probably not something that was introduced in this release.
On which platform did you expect to see the reminder? How much time did pass between editing it and it firing?

**Comment by rezbyte** [comment]
I was testing the web app, if that is what you mean. As for the passed time between editing it and it firing, less than a minute.
