### ISSUE TITLE
Desktop client doesn't start in ubuntu 23.04

### ISSUE THREAD

**Issue by uvemas** [tutao/tutanota#6095]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Describe the bug**
Tutanota desktop client doesn't start. Trying to start it from the GNOME desktop does just nothing. From the command line, trying to run the AppImage returns the error: 

`dlopen(): error loading libfuse.so.2`

**To Reproduce**
1. Go to Ubuntu Applications Launcher
2. Click on the Tutanota icon.
4. See error: nothing happens

or 

1. Open a terminal and go to the folder where the AppImage lives.
2. Try to launch the AppImage
3. See error: 
```
 $ ./tutanota-desktop-linux.AppImage 
dlopen(): error loading libfuse.so.2

```

**Expected behavior**
Application should just start as it does with previous Ubuntu versions

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Desktop Environment: Gnome 45.0

**Additional context**
Other users have reported similar problems, for example [here](https://github.com/OpenShot/openshot-qt/issues/4789).

**Comment by rezbyte** [comment]
Hi uvemas,
Thanks for your bug report.

Which version of the Tutanota desktop client are you trying to run?

**Comment by charlag** [comment]
`sudo apt install libfuse2`

**Comment by jomapp** [comment]
I just checked and I can verify that the latest tuatnota desktop appimage (v3.118.22) runs on Ubuntu 23.10, with both `libfuse2` and `fuse3` installed, without any problems.

**Comment by uvemas** [comment]
And now it works. I  really don't understand anything. Anyway, thanks a lot for yor help.
