### ISSUE TITLE
Pulling down should update on mobile

### ISSUE THREAD

**Issue by picsi** [tutao/tutanota#610]
Currently you need to trigger an update by clicking on other folders and going back, for instance.

A pull-to-refresh thing would be handy.

**Comment by charlag** [comment]
@picsi hi!
You shouldn't need to invoke update manually. We keep WebSocket connection and replay all missed events on connection.
It may make sense on mobile with bad connectivity but in case WS doesn't work other parts of the app would not work correctly either.

**Comment by asteintutao** [comment]
it is common in most apps to refresh by swiping down but it is not necessary in our case.
