### ISSUE TITLE
Blockquotes and images not displayed after send (replaced by annoying placeholders)

### ISSUE THREAD

**Issue by poshest** [tutao/tutanota#6104]
- [ X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ X ] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I composed a long email. It had two blockquote blocks with text in them. I sent it on the desktop app. Later I went to check the email (on desktop web and mobile app), and discovered the text I wrote had been replaced by ellipses. I believe the recipient got the original text because it appeared below their reply to me.

Later, I pasted images into another email and sent it. Upon viewing my email again, my image was replaced with a placeholder image.

**Expected behavior**
Display the text and images I added after sending, and don't swap it for something else.

**Screenshots**
Blockquote:
![image](https://github.com/tutao/tutanota/assets/6979221/3b216b98-2dad-4056-890e-3c762809be85)

Image:
![image](https://github.com/tutao/tutanota/assets/6979221/904de517-54f8-455c-bd8c-39bf20f15c67)

**Desktop (please complete the following information):**
Web App vType: FREE
Tutanota version: 3.118.22
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Chrome 118.0.5993.120 (Official Build) (64-bit) on Win10

**Comment by charlag** [comment]
Hi, could you please confirm that you see three-dot button in the bottom of the email? They should expand all blockquotes.

This is done for email threads but the detection whether it is really a thread or not could be improved

**Comment by poshest** [comment]
@charlag I see this on the bottom of my email

![image](https://github.com/tutao/tutanota/assets/6979221/8813d560-8498-4d3c-af11-8e63e4e51351)

The three dots on the left does nothing when clicked, like the ones I reported. 

The three dots center-bottom show the rest of the email, and yes, suddenly the blockquotes from my email now show. That's very weird UX, and I would never know that I need to expand the email to see the blockquotes text.

On the other hand, my pasted images are still not showing after clicking the center-bottom three dots.

**Comment by charlag** [comment]
About blockquotes: it is non-perfect UI but we wanted to make sure that it's clear where UI elements of the app are and where the parts of email are for security reasons. We will try to improve it in the future.

About images, I am afraid copy-pasting images from other mails won't always work. There are 2 ways to attach images that work:

1. Inline image (will be added as an inline attachment)
2. External image (will be added as a link to an external resource which must be accessible)

(sometimes it's also possible to base64 encode images inline)

Depending on the email you copied the image from it might or might not work. We would need to look at a specific case. You should contact support about it so that they can look at your case in detail.

**Comment by poshest** [comment]
It is completely not clear to me what hiding my content from me has to do with security.  That is just terrible UX. If you're somehow protecting me by doing it, then you should tell me how in-app.

And if "copy-pasting images from other mails won't always work" raise an error which makes it clear to the user in the cases that it doesn't BEFORE they attempt to send it. Don't just lose it.  FYI, I simply pasted the image from clipboard into the compose body. Nothing more "specific" than that.

Finally, your support (where you told me to go) says I should report bugs here.  I'm working here for free to help your company become more profitable, and you send me in bureaucratic circles?

If you are a junior dev, I recommend you go talk about this thread your manager so s/he has a chance to coach you. I want to have faith in Tuta.
