### ISSUE TITLE
I have to change the dark mode to light mode every time I access my mail

### ISSUE THREAD

**Issue by movementoutside** [tutao/tutanota#6112]
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**

Each time I access the email page is in dark mode, then each time that I access and want to use the light mode, I have to change this and there isn't a solution to permanent change the dark mode in light mode. Please contact me to solution this.

**To Reproduce**
1. Go to 'tuta.com'
2. Click on 'login' > 'log in'

**Expected behavior**

I want to permanent switch the dark mode or light mode when I switch between them

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. WIN10 X64]
 - Browser [e.g. BRAVE]
 - Version [e.g. 1.60.114]

**Comment by charlag** [comment]
Hi, do you clear your local storage or use incognito mode? What do you see in system settings after you log in (without changing the theme)?

**Comment by movementoutside** [comment]
Hi. I clear my local storage every time when I close my browser (including cookies).
In the system settings I see that the them is in dark (generally), and that "obligates" me to change it to white each time I open tuta.

**Comment by ganthern** [comment]
The intended behavior is for it to default to the system theme. 

> I want to permanent switch the dark mode or light mode when I switch between them

currently impossible if the local storage is always cleared and unlikely to change because we don't really plan on changing the theme setting to be account-wide. Users use different themes on different devices and this is an edge case.

**Comment by charlag** [comment]
if you want settings to persist but want to clear all browser data:

1. use some more granular clearing/different browser profiles/etc
2. or just use desktop client

**Comment by movementoutside** [comment]
Thank you very much for your attention. Greetings.
