### ISSUE TITLE
[bug] Antispam not always works

### ISSUE THREAD

**Issue by teod0r** [tutao/tutanota#612]
"Discard" rule never works.
"Always spam" not always works.

**Comment by teod0r** [comment]
I add pinbot@reply.pinterest.com to Discard antispam rule. And the rule didn't work -- I recieved mails from pinbot@reply.pinterest.com.
Then I tryed Always spam rule, and it worked, mails from pinbot@reply.pinterest.com stopped appearing in inbox, they were in spam folder.
But once I found a mail from that sender in inbox.

**Comment by charlag** [comment]
@teod0r thanks!
Just one more question: you don't forward it from some other mailbox to Tutanota? (because sender would be technically different then)

**Comment by charlag** [comment]
I believe this is resolved
