### ISSUE TITLE
Incorrect mail counter in empty trash

### ISSUE THREAD

**Issue by edems** [tutao/tutanota#6127]
Hi for weeks i have been noticing that the deleted emails continue to show the notification that the trash emails are there after i empty the trash.
![Unbenannt](https://github.com/tutao/tutanota/assets/14167466/27060e6c-b8b1-464f-b7c9-bafd812c1936)

**Comment by charlag** [comment]
Hi, could you please confirm whether you see "online" in the app header?

**Comment by edems** [comment]
Yes i was "online"

**Comment by edems** [comment]
> Hi, could you please confirm whether you see "online" in the app header?

> Yes i was "online"

Hi, you have probably already changed something, because now it doesn't show a number.

![Unbenannt2](https://github.com/tutao/tutanota/assets/14167466/a6132230-cd53-4672-afd0-fc536de675fc)

You probably have a problem with an event handler

**Comment by Umeaboy** [comment]
I have this problem as well and it says I have over 2000 emails in the trash bin even though I clicked to Empty the trash bin.

**Comment by Umeaboy** [comment]
![Screenshot_20240827_105355_Tuta](https://github.com/user-attachments/assets/c31c68a7-e7d4-499f-a42c-e8ac8568f3d2)

**Comment by jomapp** [comment]
> ![361727938-c31c68a7-e7d4-499f-a42c-e8ac8568f3d2](https://private-user-images.githubusercontent.com/17314077/361730966-ab92b020-46ad-42ac-ac73-ee746f9f076d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NDk3NTMsIm5iZiI6MTcyNDc0OTQ1MywicGF0aCI6Ii8xNzMxNDA3Ny8zNjE3MzA5NjYtYWI5MmIwMjAtNDZhZC00MmFjLWFjNzMtZWU3NDZmOWYwNzZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDA5MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDc4NWJhNGMwZWYzMTNjYjIxMWU2YjQ4NTM2YmU1MDRiMDY5NzY0NjE5NjFkMGE1MTgyNmQ0ZmRlZDkzZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AlQpIlqbdyRO2-7moyUU48HlJUoD-kq_cb4jmyuIGd8) (Update: removed personal information)

@Umeaboy Thank you for your report! Could you please try to empty the trash again.

**Comment by Umeaboy** [comment]
Did that and it still shows over 2000 even though it's empty.

27 aug. 2024 11:11 av ***@***.***:

**Comment by Umeaboy** [comment]
Any news on this?

**Comment by charlag** [comment]
Oh your screenshot it's visible that there are subfolders of trash folder. Please double check that they are also empty.
If it doesn't help please contact support so that they can check with you directly.

**Comment by Umeaboy** [comment]
Problem solved. Thanks. Have a good weekend.


6 sep. 2024 10:49 av ***@***.***:
