### ISSUE TITLE
Adding a template with non-admin user throws an error

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#6128]
When a non-admin user tries to add a template while the current plan doesn't allow templates results in an error

```
 Client: Browser
Type: PAID
Tutanota version: 3.118.27
Timestamp (UTC): Fri, 10 Nov 2023 10:57:09 GMT
User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
NotAuthorizedError
Error message: 403: NissDd5----0 | GET /rest/sys/upgradepriceservice
Stacktrace:
NotAuthorizedError. 403: NissDd5----0 | GET /rest/sys/upgradepriceservice
```

## Test notes
- [ ] Doing this does not result in an error, just a message telling to contact admin
- [ ] An admin can try to add a template, will show upgrade dialog
- [ ] When on right plan admin or non-admin can add template with no issue

**Comment by charlag** [comment]
Found a vaguely related issue: https://github.com/tutao/tutanota/issues/6205
