### ISSUE TITLE
Mail clinent dos not launch after clicked ' quit Tutanota icon in system tray '

### ISSUE THREAD

**Issue by MisterCcobD** [tutao/tutanota#6134]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**
Fore some reason i wanted to stop the mail client and i did a right click on the Tutanota icon in sysem tray on Manjaro. All fine till some time later after booting Manjaro, Tutanota mail client did not started so i tried to open it from applist...it tried but didn't started, i tried again and again and after restarts no luck...eventually i reinstalled the app and worked afterwards.

**To Reproduce**
1. Hover Tutanota client app icon from system tray
3. Click on quit
4. Relaunch

**Expected behavior**
Tries to launch the app for a second but dos not actually launch it and no tray icon seen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro [13.2.1]
 - Desktop KDE - Version [5.27.9]

**Additional context**

**Comment by charlag** [comment]
Hi, does it happen every time you close the app via system tray?
if yes, could you please try to run it from the terminal and see if there's something in the output?
Otherwise, could you please make sure that the .desktop entry (should be `~/.local/share/applications`, unless you install a build from AUR) is pointing to the correct location?

**Comment by MisterCcobD** [comment]
> Hi, does it happen every time you close the app via system tray? if yes, could you please try to run it from the terminal and see if there's something in the output? Otherwise, could you please make sure that the .desktop entry (should be `~/.local/share/applications`, unless you install a build from AUR) is pointing to the correct location?

Actually, now starts just fine... that's strange, i better close this one now
