### ISSUE TITLE
Paymentprocess

### ISSUE THREAD

**Issue by scharfet** [tutao/tutanota#6136]
I was in the process of buying a tuta-account. I got interrupted after completing step 3 of 4 (Payment).

 I entered successfully all PayPal details and accepted the payment (No 3). 
After that I got Interrupted and I could not go further to complete the last step (No 4)
And I cannot repeat the registration, because I am told, that the email I chose is already assigned.

How can I resolve the problem?
The address is    c o v t r u @ t u t a .....

Thank you.

Johann

MacOS (latest version)
Firefox (latest version)

**Comment by charlag** [comment]
Hi, please contact hello@tutao.de about your problem.

You should also be able to log in into your account, even if the payment was not successful.

**Comment by scharfet** [comment]
Hi, thank you for your answer.
I could solve the problem.

In order to change my accountemail in odysee.com from ...@tutanota.com to ...@tuta.com, odysee sends the verification email to tutanota.com. But unfortunately I cannot receive emails to ...@tutanota.com anymore. 
I do not know how to solve this problem. Is there any solution?
Thank you.
