### ISSUE TITLE
Mobile app on Lineage OS (Murena)

### ISSUE THREAD

**Issue by 0lie** [tutao/tutanota#6178]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Can't launch the app. Error message: got to tuta.com/faq/webview.
Android Web view system was downloaded but didn't change behavior of the app.

**
**Smartphone (please complete the following information):**
 - Device: [Samsung s8
 - OS: Lineage OS (e.foundation os).

**Comment by charlag** [comment]
make sure the right WebView is actually used. Since you are using Lineage your ROM is probably not configured to use Chrome WebView by default and you need to change it in developer settings.
