### ISSUE TITLE
URIError in stringToUtf8Uint8Array

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#618]
> Stacktrace: 
> stringToUtf8Uint8Array@https://mail.tutanota.com/common.js:1:192171
> value/r@https://mail.tutanota.com/libs.js:32:9002
> [22][22][22][22][2][2]r/this.drainQueues@https://mail.tutanota.com/libs.js:30:1236

`encodeURIComponent` is used in `stringToUtf8Uint8Array`

> Note that a URIError will be thrown if one attempts to encode a surrogate which is not part of a high-low pair
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

we should consider not using `encodeURIComponent` here. Is is tricky because it is used in many places (e.g. encryption & indexing). Maybe we should detect such surrogates and transform them. It should be safe because `encodeURIComponent` was failing for them anyway.

**Comment by armhub** [comment]
We could not reproduce this bug, so the fix was just regression tested.
