### ISSUE TITLE
Autofill does not work on Android

### ISSUE THREAD

**Issue by frozen905** [tutao/tutanota#6183]
Latest Android version is all kinds of screwed up

Had to immediately uninstall it because I can't even login due to Bitwarden autofill being suddenly crippled

Simply the worst app I've ever used, because I can't even log in

**Comment by murilopereirame** [comment]
Seems to be a bug with Bitwarden, not Tuta app. 
Other password managers, as Firefox, still able to find and auto fill the login/email on mobile app.
