### ISSUE TITLE
Notifications are not working on GNOME

### ISSUE THREAD

**Issue by warusadura** [tutao/tutanota#6206]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Notification popups or any kind of notifications are not working/showing on GNOME desktop environment.

**Expected behavior**
When a new email is received a notification popup should appear.

**Desktop:**
 - Desktop Environment: GNOME
 - Version: 44.5
 - Tutanota Desktop app version: tutanota-desktop-linux.AppImage: 3.118.30
 - Desktop integration: Activated
 - GNOME notification settings:  Tutanota Desktop: On

**Comment by charlag** [comment]
I use GNOME both at home and at work, with two different distributions and GNOME versions and it works for me so there must be some detail that's missing.
Do you see any error messages if you start it from the terminal?
Could you please double-check that notifications for Tuta are enabled in GNOME settings?
