### ISSUE TITLE
Germany appears as 'Deutschland' in the English version of the 'Country' drop-down

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6214]
**Bug in web app**

**Describe the bug**
When redeeming a gift card the 'Country' drop-down uses 'Deutschland' for Germany in the English version. Searching for 'Germany' in the drop-down does not bring anything up.

**To Reproduce**
1. Redeem a gift card
2. Go to the last stage (number 3)
3. Enter 'Germany' into the country drop-down
4. Germany does not appear

**Expected behavior**
Germany appears as 'Germany' in the drop-down list.

**Screenshots**
![Screenshot from 2023-11-28 11-44-21](https://github.com/tutao/tutanota/assets/48037381/68dce913-5901-46a1-a582-4351469ec7e5)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 120

**Additional context**
Was testing #6022

**Comment by charlag** [comment]
That's by design at the moment.
