### ISSUE TITLE
global menu on macOS does not respect client/system language settings

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6221]
The file, edit, etc. menus for Tuta Mail do not respect the display language set for the macOS.

In the screenshot below, the both system's language and the language in Tuta Mail are set to German

![image](https://github.com/tutao/tutanota/assets/104761667/b5e6375e-0df3-423b-8e51-c6e93696ea16)

**Comment by rezbyte** [comment]
This is an [issue with electron](https://github.com/electron/electron/issues/26231). Electron does not provide localization when using the `role` attribute in `MenuItem`, we could work around it by reimplementing the roles ourselves. But it's easier & cleaner just to submit a patch to Electron.
