### ISSUE TITLE
cannot create addresses during custom domain setup

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6222]
After adding the t-verify record, the second step, where users should be able to create email aliases is stuck at "verifying email address". Skipping this step and creating the alias later from Settings > Email works fine. 

### Test Notes
* [ ] in the places where it's possible to select tuta.com as a domain for a new address, it's only available for paid users even when changing back and forth (signup, add user, add address)
* email validation succeeds and fails as expected (2-letter usernames only available for custom domains, taken, invalid characters, available address)
  * [ ] during signup
  * [ ] during custom domain setup
  * [ ] during add email address
  * [ ] during add user

**Comment by murilopereirame** [comment]
Everything works, just one question, I can add a 2-digit email when using a custom domain, is it correct?

**Comment by ganthern** [comment]
> Everything works, just one question, I can add a 2-digit email when using a custom domain, is it correct? @ganthern

updated the test notes. they're allowed for custom domains, but not for tutanota domains.
