### ISSUE TITLE
Images displayed in mail editor without prompt

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6227]
**Describe the bug**
When opening a draft reply via the more button in the mail view, the images are displayed without prompting the user even if a show choice was not selected in the original mail.

**To Reproduce**
1. Open an email with external images, do not choice a show option ('Show', 'Trust' etc.) in the prompt.
2. Write a draft reply to the email
3. Close the draft and the minimized draft
4. Go to the drafts folder
5. Open the draft in the conversation view
6. Click on the more button (`...`) in the header then press edit
7. The external images are displayed

**Expected behavior**
The external images are not displayed in the mail editor & the user is prompted again whether to show the images. 

**Additional context**
Originally mentioned in a [comment inside #5405](https://github.com/tutao/tutanota/issues/5405#issuecomment-1831390025).

**Comment by nokhub** [comment]
There are two ways to fix this issue:

1.
when replying to an email with external images without giving permission to display the images, a draft is created with `draft-src` for the inline images. The sanitizer does not count this tag towards external content. The result is, that `this.contentBlockingStatus === ContentBlockingStatus.NoExternalContent` in the `MailViewerViewModel`. Changing how the sanitizer is handling `draft-src` tags would solve the issue

2.
also returning `true` from `isBlockingExternalImages()` in `MailViewerViewModel` when `this.contentBlockingStatus === ContentBlockingStatus.NoExternalContent` would fix the issue. Making blocking external images the default value, which is only false if  `this.contentBlockingStatus === ContentBlockingStatus.Show || this.contentBlockingStatus === ContentBlockingStatus.AlwaysShow`

Not sure whether 2 is unintuitive but for reasons of simplicity I decided to implement this option
