### ISSUE TITLE
folder name tooltip can be cut off 

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#6228]
https://github.com/tutao/tutanota/issues/6162

   * open a mail and show the tooltip by hovering over the folder icon in the mail viewer header: everything's fine
   * change the name of the folder to something shorter or longer: the tooltips left edge is still aligned where the old one would have been
       * therefore, it's either too far left or cut off at the right.

This is fixed by switching the mail and/or folder and back, so there's some stale data somewhere.

**Comment by murilopereirame** [comment]
Sometimes the tooltip still overflowing. Should we break the text if it overflows?

![Screenshot 2023-12-14 at 9 08 09 AM](https://github.com/tutao/tutanota/assets/34790144/7738f5e5-a117-4fc0-8bf6-6fcdac8a9749)
![Screenshot_20231214-085538](https://github.com/tutao/tutanota/assets/34790144/28e2fa06-d986-4098-ad65-3e5b2a90edb7)

**Comment by ganthern** [comment]
okay that's kinda sad TT

I think breaking would be good, but it's an even rarer edge case that's not going to hold up the release.

https://github.com/tutao/tutanota/issues/6302
