### ISSUE TITLE
You are going to be blocked! Please take action immediately!

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#6251]
Hi!

On this thread https://github.com/7c/fakefilter/issues/73 some random user asks to block your email domains.

This is really popular filter, so please, take measures!

@ganthern @charlag

**Comment by charlag** [comment]
thanks for letting us know we'll look into this!

**Comment by ganthern** [comment]
I hope this is the right place for the PR, I can't find our domains on the fakefilter repository 

https://github.com/wesbos/burner-email-providers/pull/425

**Comment by Nothing4You** [comment]
> I can't find our domains on the fakefilter repository

they're not currently included, it's the PR suggesting to add them
