### ISSUE TITLE
wesbos/burner-email-providers has tutanota domains on their list

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#6256]
Hi!

On this PR https://github.com/emailhippo/burner-email-providers/commit/6a270d4eaee76cb0804f5b359a0e62064a3c4d55 you got blocked

This is really popular filter, so please, take measures!

@ganthern @charlag

**Comment by ganthern** [comment]
We're still not in the data files on that repo as far as I can see

**Comment by ganthern** [comment]
https://raw.githubusercontent.com/wesbos/burner-email-providers/master/emails.txt

we're on that list now

**Comment by ganthern** [comment]
Made a PR: 

https://github.com/wesbos/burner-email-providers/pull/425

**Comment by ganthern** [comment]
the second PR was merged, we seem to be removed now.
