### ISSUE TITLE
[iOS] Going back from mail with the swipe-from-edge gesture

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#626]
> Please add right-swipe from left edge (to go back or show inboxes/folders) in the tutanota iPhone app
> its in iPhone nature

It is a very common gesture on iOS and we should follow it. We should implement this when applying design changes.

**Comment by mpfau** [comment]
tested android and ios

**Comment by bedhub** [comment]
There is a bug on iPad in horizontal layout. If a mail is selected and you use the swipe gesture mail list and mail body is moved to the right.
