### ISSUE TITLE
"always trust sender" option no longer available in web browser or android

### ISSUE THREAD

**Issue by blankscreengithub** [tutao/tutanota#6262]
I've searched and did not find a similar issue.

**Describe the bug**

![tuta](https://github.com/tutao/tutanota/assets/66571264/545e0095-8f13-424a-a7c7-b41bff305813)

![always](https://github.com/tutao/tutanota/assets/66571264/ee8011d4-1fd6-43e3-a1b9-a4094b82d357)

Starting November 29, the "always trust sender" option for loading images is gone.

**Expected behavior**
Shoe the "always trust sender" option like it used to.

 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.119.3

android version: 3.118.27

**Comment by ganthern** [comment]
Hey, thanks for the report! And thanks also for taking the time to research before posting an issue.

This will be fixed once https://github.com/tutao/tutanota/pull/6255 lands.

Best regards!
