### ISSUE TITLE
Did not pass session key when decrypting encrypted instance of type

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6275]
```
Client: Browser
Tutanota version: 3.119.3
User agent:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
ProgrammingError
Error message: Did not pass session key when decrypting encrypted instance of type tutanota/Mail
Stacktrace:
ProgrammingError. Did not pass session key when decrypting encrypted instance of type tutanota/Mail
```

```
Client: android
Tutanota version: 3.118.27
User agent:
Mozilla/5.0 (Linux; Android 13; SM-G781W Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36
ProgrammingError
Error message: Did not pass session key when decrypting encrypted instance of type tutanota/Mail
Stacktrace:
ProgrammingError: Did not pass session key when decrypting encrypted instance of type tutanota/Mail
at ga.decryptAndMapToInstance (https://assets.tutanota.com/worker.js:12:29673)
at Ls._decryptMapAndMigrate (https://assets.tutanota.com/worker.js:1:26974)
at async https://assets.tutanota.com/common-min-160da492.js:1:18587
```

```
Client: Browser
Tutanota version: 3.118.30
User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
ProgrammingError
Error message: Did not pass session key when decrypting encrypted instance of type tutanota/File
Stacktrace:
ProgrammingError. Did not pass session key when decrypting encrypted instance of type tutanota/File
```

**Comment by charlag** [comment]
here:

https://github.com/tutao/tutanota/blob/ce7bc4172d3d70c590d4ef150b5a9c340251c087/src/api/worker/rest/EntityRestClient.ts#L269-L287

the comment is wrong, we will just fail

**Comment by mpfau** [comment]
This is not a MailDetails problem, it also occurs for non MailDetails customers. 

If it was a MailDetails customer, I could only find errors regarding decryption of the `Mail` instance. 

I will add some more log output so that we have a better chance of diagnosing when no session key is found.

**Comment by mpfau** [comment]
We still have around ten of those cases per day. One thing that is remarkable is that all customers that I looked up never invoked UpdateSessionKeysService for those mails (ownerEncSK is null for all mails and also the file instances).

We found that we store instances with `_errors` in our cache and will fix this in a first step.

Other ideas for improvement if this does not help:
1. Invoke UpdateSessionKeysService from non leader clients. It is weird that it is never invoked for the mails mentioned above.
2. Pass the mail with the `BucketKey` to `BlobFacade#downloadAndDecrypt`.

**Comment by mpfau** [comment]
## Test notes
Can only be tested locally by disabling `OwnerEncSessionKeysUpdateQueue`

- [x] receive a mail with an attachment and download the attachment
- [x] receive a mail with multiple attachments and download the attachments by pressing 'save all'
- [x] receive a mail with an attachment and forward the mail
- [x] receive a mail with an attachment and export the mail
- [x] receive a mail with an attachment and export multiple mails at once

- [x] receive a mail with an inline image and reply to that mail
- [x] receive a mail with multiple inline images and forward that mail
- [x] receive a mail with an inline attachment and export the mail
- [x] receive a mail with an inline attachment and export multiple mails at once
