### ISSUE TITLE
adding an event in agenda view does not respect selected day

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6294]
When adding an event in the new agenda view on mobile devices, the day of the event is always set to today, regardless of the currently selected day.

v3.119.3, Android, iOS, Web.

![image](https://github.com/tutao/tutanota/assets/104761667/c3433c9c-f281-465b-a570-1d9102929c26)
![image](https://github.com/tutao/tutanota/assets/104761667/d7d0da1f-b1c1-4c45-abb0-c9bf4d85fe9d)

## Test Notes
* [ ] Adding an event on Agenda View still working
* [ ] Adding an event on Agenda View respect the selected Date
* [ ] Adding an event on other views still working normally without changes

**Comment by ganthern** [comment]
* go to agenda/day view
* select a day different from today 
* go to week/month view
* optionally go to any other time range on one of these views
* click "new event" or the N shortcut
* the event will be initialized on the day that has been selected in agenda/day view and may have nothing to do with 
  what's currently on the screen
