### ISSUE TITLE
Mail Folder Tooltip Obscures Full Name in Certain Cases

### ISSUE THREAD

**Issue by ganthern** [tutao/tutanota#6302]
mail folder tooltips don't overflow the window on the right now, but can still collide with stuff on the left and are clipped by their parent on the right: 

![Screenshot 2023-12-14 at 9 08 09 AM](https://github.com/tutao/tutanota/assets/34790144/7738f5e5-a117-4fc0-8bf6-6fcdac8a9749)
![Screenshot_20231214-085538](https://github.com/tutao/tutanota/assets/34790144/28e2fa06-d986-4098-ad65-3e5b2a90edb7)

And for the clipping on the right:
![image](https://github.com/tutao/tutanota/assets/29049728/41d7d1fa-f062-4782-ac89-63c645dab170)

the folder name is "shoreshoretshoret", so just one letter is overflowing. the tooltip is not colliding with the window edge but with its parents edge, so isn't repositioned.

possible fixes:
* make the tooltip float above everything
* break the line if it's wider than the mail viewer and/or screen

https://github.com/tutao/tutanota/issues/6228

## Test Notes
- [ ] Long Name wraps 
- [ ] short name is not cut off on the right
- [ ] Middle length folder names display as expected

**Comment by murilopereirame** [comment]
There's a scrollbar now even when the whole mailbody is already displayed. I don't think this should hold the release but should be addressed later
![image](https://github.com/tutao/tutanota/assets/34790144/57c6f4e9-02e7-41cd-b57e-250129324238)
