### ISSUE TITLE
v3.119.8 - DeviceStorageUnavailableError - UNKNOWN - linux (Including when passing --password-store="gnome-libsecret" )

### ISSUE THREAD

**Issue by BRUrban** [tutao/tutanota#6312]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Tuta desktop app logged in successfully and prompted for an update. After updating to the latest version, I am met with a SafeStorage decryption issue. 

```
Feedback v3.119.8 - DeviceStorageUnavailableError - UNKNOWN - linux



 Client: linux
 Type: UNKNOWN
 Tutanota version: 3.119.8
 Timestamp (UTC): Mon, 18 Dec 2023 12:31:46 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.119.8 Chrome/116.0.5845.228 Electron/26.6.2 Safari/537.36
DeviceStorageUnavailableError
 Error message: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:211097)
    at async tR.fetchOrGenerateKey (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:210825)
    at async Sb.decryptUsingKeychain (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:287120)
    at async ipc (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:297338)
Stacktrace: 
DeviceStorageUnavailableError: failed to resolve/generate key> Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at Nw.getPassword (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:192988)
    at async tR.fetchKey (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:211097)
    at async tR.fetchOrGenerateKey (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:210825)
    at async Sb.decryptUsingKeychain (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:287120)
    at async ipc (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:297338)
    at tR.fetchOrGenerateKey (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:210998)
    at async Sb.decryptUsingKeychain (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:287120)
    at async ipc (/tmp/.mount_tutanozyS4uz/resources/app.asar/desktop/DesktopMain.js:5:297338)
```

**To Reproduce**
1. Attempt Login on version v3.119.8

**Expected behavior**
Login succeeds

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Desktop Environment, if applicable (on Linux): KDE
 - Version 3.119.8

**Additional context**
This continued to occur both after performing an update of all packages on my machine (`sudo pacman -Syu`), and deleting and re-downloading the latest version of the Tutanota AppImage in case something had gone wrong during the actual update process on my machine. Prior to updating to 3.119.8, Tutanota was successfully accessing SecretStorage.

Manually adding `--password-store="gnome-libsecret"` or `kwallet` or `kwallet5` or `kwallet6` when running from the terminal encountered the same behavior.

**Comment by ganthern** [comment]
Just to confirm, this worked with tuta mail 3.119.3 and the `gnome_libsecret` switch?

**Comment by gaestur** [comment]
The same issue with KDE wallet, though before the update it worked fine.

**Comment by BRUrban** [comment]
> Just to confirm, this worked with tuta mail 3.119.3 and the `gnome_libsecret` switch?

I never had to manually tweak secret configuration prior to this update, 3.119.3 worked fine for me with no arguments passed to the AppImage. 

I do have libsecret installed because some electron apps require it instead of playing nicely w/ kwallet, but in general things should be using kwallet5 on my machine, which I also have installed, and tried passing as the `--password-store` value (See my "Additional context" notes).

**Comment by bkmo** [comment]
Also broken on my KDE 5.27.10 aon Arch. Cannot access secret service. Downgrading to 3.119.3 fixes the issue.

**Comment by kibhub** [comment]
KDE Wallet has only recently introduced support for the freedesktop secrests API which, which makes kwallet usable by libsecret. On KDE Framworks 5.97.0 you do not need to add any cli flag to start Tuta. It should work out of the box the recognize kwallet. See [arch wiki](https://wiki.archlinux.org/title/KDE_Wallet)

On older version, please use the `--password-store="kwallet5"` for the time being until your distro ships the mentioned KDE frameworks version. 

**If you encounter any issues**, please remove the ~/.config/tutanota-desktop folder, which removes all locally stored data for the client and try again, regardless of whether you need to use the cli flag or not.

**Comment by bkmo** [comment]
I'm on framework 5.113.0 and the secret service has worked fine until the update to 3.119.8. Going back to 3.119.3 works fine. I have never needed a cli flag. So it seems to me there is some sort of regression in 3.119.8. Are you saying if I remove the .config for tuta it will work for 3.119.8? Or was that just a generic answer?

**Comment by pgeyfman** [comment]
Just updated to 5.113.10 and now it's not working no matter what I do. Tried without CLI parameter, with --password-store=libsecret, --password-store=kwallet5 .  Always get the secret storage error.

**Comment by pgeyfman** [comment]
> Removing the ~/.config/tutanota-desktop folder worked for me on 3.119.10. No need for the CLI parameters.

Worked for me as well, although that's not ideal, because you then have to re-index all mail to enable search function.

**Comment by bkmo** [comment]
Correct, if this happens with every new update it will truly suck. AFAIK it is a regression and the Issue should not be closed.

**Comment by bkmo** [comment]
I am curious though if anyone with Framework earlier than 5.113.0 had any issues upgrading.

**Comment by kroltan** [comment]
Hi, I'm on framework 5.112.0 and I had this issue starting a couple days ago, so my bet is this is the same issue. Passing the `--password-store="kwallet5"` parameter works.

Please let me know if there is any way I can be of assistance, I don't mind going in the weeds in testing.

Haven't deleted the config folder yet.

**Comment by kibhub** [comment]
version 3.119.3 used KDE Wallet directly without going through libsecret, and now we use libsecret by default, which in turn talks to kwallet5. If you have used both versions or if you have tried out the parameter `--password-store="kwallet5"` then your credentials are stored in the wrong place from libsecret's point of view.

You can either delete the config folder ~/.config/tutanota-desktop or manually transfer the stored password from Passwords under Chromium Keys  to Passwords under Secret Service.

If you have any other credentials stored, I would recommend just deleting the config folder.

![image](https://github.com/tutao/tutanota/assets/104761667/0e8ee8ca-955b-4ad7-af59-3a4226c2b1af)

![image](https://github.com/tutao/tutanota/assets/104761667/2e2960ed-4a7a-4dd9-b3ec-e1fd1f0bb557)

**Comment by kibhub** [comment]
Versions 3.119.8 and newer would also use Gnome's Keyring if KDE framworks is older than 5.97, but again, you might need to delete the local data.
