### ISSUE TITLE
Default text color in web client

### ISSUE THREAD

**Issue by guoyunhe** [tutao/tutanota#632]
Firefox for Linux with a dark desktop theme:

![img](https://screenshotscdn.firefoxusercontent.com/images/90a4aba0-524b-467d-aabb-bc82e61e1e8b.png)

Default color is light gray and it is not readable in a white background. Need to add this simple CSS:

```css
body {
  color: #000000;
}
```

**Comment by charlag** [comment]
Please use new mail client at https://mail.tutanota.com
We will release it by default soon
