### ISSUE TITLE
Opening the Android app somtimes does auto login with multiple saved credentials

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6322]
Sometimes when you open the Android app and you have multiple credentials saved it just logs in into any of them automatically. If you had selected to share a file as attachment in Tuta previously it even logs in and opens a new email with that attachment again.

No reproduction known yet, just occurs sporadically.

## Test Notes
- [ ] User still receiving notifications
- [ ] Tapping on one notification redirects the user to the corresponding mailbox
- [ ] Auto login still working with just one account
- [ ] There's no auto-login when multiples account are stored, except if the user has taped on a notification

**Comment by rezbyte** [comment]
Perhaps I am doing something wrong but it seems that notifications are not working.
