### ISSUE TITLE
Agenda Items do not scroll in desktop mode

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#6326]
Repro:
- Have enough events in a day that there are more than fit onto the screen.
- You are not able to scroll to see the ones below.

Expected:
- Can scroll to see all events

We aren't using our own List component to display these, maybe use that here too?

## Test Notes
- [x] Event view popup is styled correctly
  - [x] Description icon & body are aligned
  - [x] Participants icon & body are aligned
  - [x] Invitation buttons look correct
  - [x] Stays correct at various view-port sizes
- [x] Event list in the agenda view scrolls
- [x] Details in the agenda view scrolls

**Comment by paw-hub** [comment]
This works, but there is also now a horizontal scrollbar if the window is not wide enough.

![image](https://github.com/tutao/tutanota/assets/104824185/8e41317f-6941-4cec-909c-1158b5d0be13)

**Comment by murilopereirame** [comment]
The scroll works on three columns layout but not on one/two columns layout.
Also, not working on mobile devices.

And the invitation button seems to be without hover effect, that isn't a big problem and shouldn't hold the release
![Screenshot from 2024-01-19 09-06-41](https://github.com/tutao/tutanota/assets/34790144/2a5f5f72-2a56-4dc8-8296-e1d7b1a96d93)

![Screenshot from 2024-01-19 09-06-46](https://github.com/tutao/tutanota/assets/34790144/f0a5a51c-77f2-499f-b976-af9e8b1398c5)

**Comment by charlag** [comment]
Invitation button was like that, it's fixed in #6334
