### ISSUE TITLE
Can't login to webmail - Error message: Worker is not a constructor

### ISSUE THREAD

**Issue by Schweber** [tutao/tutanota#6332]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
Error popup appears on login page. Login not possible.

**To Reproduce**
1. Go to (https://app.tuta.com/login)
2. Error Popup will appear

**Expected behavior**
Normal login like before the switch to tuta.com

**Desktop (please complete the following information):**
 - OS: Nixos unstable
 - Browser librewolf
 - Version 120.0.1

**Additional context**
Feedback v3.119.10 - TypeError - UNKNOWN - Browser

 Client: Browser
 Type: UNKNOWN
 Tutanota version: 3.119.10
 Timestamp (UTC): Tue, 26 Dec 2023 16:04:30 GMT
 User agent:
Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0
TypeError
 Error message: Worker is not a constructor
Stacktrace: 
init@https://app.tuta.com/main-25bd3066.js:1:15065
execute/init/this.worker<@https://app.tuta.com/main-25bd3066.js:1:95505
init@https://app.tuta.com/main-25bd3066.js:1:95578
execute/<@https://app.tuta.com/app.js:1:78661

**Comment by Schweber** [comment]
Caused by jshelter extension, worked before

**Comment by ganthern** [comment]
> librewolf
> Caused by jshelter extension, worked before

we can't support that setup
