### ISSUE TITLE
time picker for creating events does not respect time format setting

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6339]
setting the time format to 24-hour format does not change the time picker.  This happens on **Android** only since **v3.119.3**

![image](https://github.com/tutao/tutanota/assets/104761667/7bb86945-8b00-4642-a19e-d007df42369a)
![image](https://github.com/tutao/tutanota/assets/104761667/4e3b19ff-dda3-4f19-a9eb-dd507fe7ebb8)

**Comment by rezbyte** [comment]
I have reproduced this on the latest testing android build. However, it also reproduces on versions before v3.119.3 and on iOS. From reading the codebase, the native time picker should not have been able to display the right time format to begin with. [The `<input type="time">` chooses between time formats solely on system locale as seen in `navigator.language`.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#chrome_and_opera) The time format drop-down in settings does not change the system locale at all. It is possible on Android 13 but no version of iOS to set the locale by app, but this does not fix it for the oldest supported version of Android (Android 12) and iOS users.

To fix this, I can think of two options:
1. Disable the time format settings on Mobile and get the time format to display times from the OS settings.
2. Program manual calls to open a native time picker so we can use its time format parameter, and to get the selected time back.
