### ISSUE TITLE
Event editor inputs do not visually appear disabled

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6356]
**Describe the bug**
When trying to edit a read only event (such as one in a series), the event editors inputs will be disabled but are not styled to make that clear.

**To Reproduce**
1. Create a repeating event in the calendar.
2. Click on it in the event list then the edit button.
3. Click 'this event only'
4. Attempt to change either the calendar or the repeating fields.
5. See that the input is actually disabled.

**Expected behavior**
When an input is disabled, they should appear darkened like the Checkbox does.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 120

## Test Notes
- [ ] When creating a new event
  - [ ] with only one calendar on the account only the calendar combo box is disabled
  - [ ] with multiple calendars on the account, nothing is disabled
- [ ] When editing an event
  - [ ] that is organized by another user, everything except the reminders is disabled
  - [ ] that is a part of a reoccurring event, the calendar & repeating fields are disabled
- [ ] Disabled fields do not respond to 
  - [ ] click
  - [ ] tap
  - [ ] enter & space
- [ ] Enabled fields respond to
  - [ ] click
  - [ ] tap
  - [ ] enter & space
- [ ] The cursor is appropriate when hovering over
  - [ ] an enabled field (displays `text` cursor)
  - [ ] a disabled field (displays `default` cursor)
- [ ] Bubble text field still works fine
- [ ] Whitelabel domain dialog still works

**Comment by murilopereirame** [comment]
Disabled field still showing the text cursor
![image](https://github.com/tutao/tutanota/assets/34790144/e34305ee-2b79-4b77-886f-bf68dd67bdd8)

I'm able to change event's date even with disabled field
[output.webm](https://github.com/tutao/tutanota/assets/34790144/fa9a094a-df21-4274-9f94-ab8284f21921)
