### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by barbiehunter** [tutao/tutanota#6373]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
I'm only able to Login via "Please acept this login from another tab or via the app"

**To Reproduce**
Simply Login

**Expected behavior**
Giving me other choices to Login, and not  only "Lost account access"

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/38357837/87266738-8c0f-47e6-9461-b0c4fee0bb6d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave & Mullvad Browser
 - Version 1.61.116

**Additional context**
I have 2 Yubikeys on my account so i think i could just insert them Login. I don't have any Login with any other tab or app so i'm unable to Login into my mails for at the moment.
Edit: After alot of struggle i was randomly able to Login with my Yubikey, but still very weird i was not able to simply Login (with yubikey on it)

**Comment by charlag** [comment]
It seems like it was not detecting the key? Have you been logging in on the same domain you have the keys on?
