### ISSUE TITLE
[Android] Synch problem with server when using Web interf. in parallel

### ISSUE THREAD

**Issue by philippeFernandez** [tutao/tutanota#638]
Scenario : 
A mail is received on the server. 
Android signals the notification (while app closed)
User read the mail **from web interface and sort it in another folder**
Then, clicking on notification will search the mail in inbox, (and find it in inbox). 
Error occure 'sometime' when displaying the content
**Mail is still displayed in inbox by Android app** (not in synch with server)

**Comment by charlag** [comment]
Thanks for the report, we will check that!
Could you add if the app was running or not when opening notification?

**Comment by philippeFernandez** [comment]
np : top post is updated

**Comment by charlag** [comment]
@philippeFernandez can you confirm that this is still the case? It should connect and update after few seconds

**Comment by philippeFernandez** [comment]
@charlag : I just made a basic test and it is fixed now.

Issue can be closed.
