### ISSUE TITLE
No deleting

### ISSUE THREAD

**Issue by annimhere** [tutao/tutanota#6387]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by annimhere** [comment]
I cannot delete any emails.  I've had this happen before and its a pain.  Cannot delete emails in inbox or in spam.

**Comment by charlag** [comment]
The information you've provided is insufficient. Please contact support.
