### ISSUE TITLE
Problems with importing VCF file

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#641]
>  What:  Wrong conversion from VCF-file. Certain fields gibberish, non-understandable. 
> 
> - When: If I go in Windows 10 machine with Firefox to Tutanota --> Contacts --> Import and try to import a VCF-file.
> 
> - Example: First names and family names come in odd format. However, telephone numbers and e-mail addresses convert properly. 
> 
> - A detail: This VCF-list originally is saved from a Samsung Android mobile phone to Windows 10 64-bit computer and it's directory. Windows programs show that Vcalendar file properly. 
> 
> Ich bin dankbar für alle Änderungen ;-)

Need more info on versions.

**Comment by asteintutao** [comment]
Looks like the names are hexadecimal encoded. This is not the standard way to format vcard file names according to RFC vcard specs.  Might be that your android version is an older one. This can happen there. 
We'll have a look at it and see how to fix it.
