### ISSUE TITLE
Cannot search online

### ISSUE THREAD

**Issue by vhscom** [tutao/tutanota#6410]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
Cannot search online with Android app

**To Reproduce**
1. Open Android application
2. Click on hourglass
3. Attempt to search
4. See screenshot

**Expected behavior**
Ability to search without paying

**Screenshots**

![Screenshot_20240119_140643.jpg](https://github.com/tutao/tutanota/assets/97140109/2a62ba9f-8bd9-4e8c-9bbb-ad56121d2c82)

**Smartphone (please complete the following information):**
 - Device: Huawei P40 Pro+
 - OS: EMUI (Android)
 - Version 12.0.0

**Additional context**
n/a

**Comment by vhscom** [comment]
Between us I was about to bail on Proton after 6 years until I saw this.

**Comment by charlag** [comment]
Hey, could you please check logs (Settings -> About -> Send Logs) for any error messages that you get after you try to search?

**Comment by vhscom** [comment]
Since posting an upgrade became available and I have not seen this issue since. Thanks for the quick resolution!

**Comment by vhscom** [comment]
Continued in https://github.com/tutao/tutanota/issues/6703
