### ISSUE TITLE
unable to login after updating to MacOS Sonoma 14.2.1 when using Firefox 12.0.1

### ISSUE THREAD

**Issue by cstnerd** [tutao/tutanota#6411]
- [ X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X ] I've searched and did not find a similar issue.

**Describe the bug**
unable to log into account after updating to MacOS Sonoma 14.2.1 using Firefox 121.0.1. I can get into account using Chrome

**To Reproduce**
1. Go to https://app.tuta.com/login - enter user name and password
2. Click on log in
4. See error - no error message, just refreshes login screen.  cannot pass log in screen using firefox but can using chrome.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Sonoma 14.2.1 using Firefox 121.0.1. 
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by charlag** [comment]
Hey, do you see any messages in dev tools? Did you tweak any about:config things in Firefox?

**Comment by charlag** [comment]
https://firefox-source-docs.mozilla.org/devtools-user/

you need console tab.

if the page reloads you might need to enable persisting logs in dev tools so that you can see what was printed before the reload.

normally we can get relevant logs via the app but since it reloads for you it is harder

**Comment by cstnerd** [comment]
Well, I cleared the cache and now the login page won't even load.
The dev tool error is NS_ERROR_FAILURE.

The filter header shows:Accept
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding
gzip, deflate, br
Accept-Language
en-US,en;q=0.5
Connection
keep-alive
DNT
1
Host
app.tuta.com
Sec-Fetch-Dest
document
Sec-Fetch-Mode
navigate
Sec-Fetch-Site
none
Sec-Fetch-User
?1
Sec-GPC
1
Upgrade-Insecure-Requests
1
User-Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0

I'll also ask Firefox for assistance.
Thanks,
Doris-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


Jan 23, 2024, 00:23 by ***@***.***:

**Comment by cstnerd** [comment]
here's the error message in the dev tool

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://img-getpocket.cdn.mozilla.net/592x296/filters:format(jpeg):quality(60):no_upscale():strip_exif()/https%3A%2F%2Fs.zkcdn.net%2FAdvertisers%2F3568e077921d42159384869052d4127f.jpg. (Reason: CORS request did not succeed). Status code: (null).
-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


Jan 23, 2024, 22:20 by ***@***.***:

**Comment by charlag** [comment]
Is issue still relevant?

**Comment by cstnerd** [comment]
Issue is resolved.
Thank you.

-- 
 Sent with Tuta; enjoy secure & ad-free emails: 
 https://tuta.com


Feb 26, 2024, 09:16 by ***@***.***:
