### ISSUE TITLE
Agenda view is overlapping events on mobile

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#6413]
**Bug in mobile app**

**Describe the bug**
Agenda view is overlapping events from the day before with events from selected date

**To Reproduce**
**On Android with release v3.121.2 **
1. Go to Calendar
2. Click open the months view
3. Change to Agenda view,
4. Load the day before,
5. Go back to months view
6. Go to agenda view again
7. See error

Sometimes, the steps 4,5 and 6 aren't needed.

**Expected behavior**
The event list doesn't overlap and the agenda view show just events for the selected date

**Screenshots**
![Screenshot_20240122-091050](https://github.com/tutao/tutanota/assets/34790144/f4d48a52-0726-4424-a8b4-3363d917e184)

## Test Notes
- [ ] Try to reproduce the error and the error doesn't happen anymore
- [ ] There's no redraw loop
- [ ] Other places that use the PageView still working (Day, Week and Month View)

**Comment by paw-hub** [comment]
Also able to reproduce on Chromium devtools

![image](https://github.com/tutao/tutanota/assets/104824185/60bd45b8-e5e1-4289-94d3-6146bf1b4159)
