### ISSUE TITLE
Add translations for right-to-left languages

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#643]
* Arabic (ar)
* Persian (fa-IR)
* Hebrew (he)

**Comment by Raamyy** [comment]
Hey @armhub 
I can help in translation into Arabic.. but please clarify the specific files that needs to be translated.

**Comment by armhub** [comment]
@Raamyy Thanks for the offer. We already have translations for those languages, Arabic is even complete. We just have to include them in the Tutanota client and handle displaying them right-to-left. When they are released and you find some translations missing or wrong, please let us know, then we can add you to the translation project.

**Comment by tynuk85** [comment]
Hi guys. I can help out with Portuguese (PT and BR).

Keep up the good work!

**Comment by charlag** [comment]
Added Arabic and Persian, as they're well translated, will add other languages as translations improve.
