### ISSUE TITLE
Screen readers do not follow app language

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6438]
**Describe the bug**
Screen readers do not change language if the apps language is changed in the settings menu. Screen readers will always use the system language.

**To Reproduce**
1. Enable the screen reader on GNOME.
2. Switch the language of the app into Japanese.
3. Focus any text in the app.
4. The text is always read as 'Japanese letter, Japanese letter, ...'.

**Expected behavior**
The screen reader reads the language displayed by the app.

**Desktop (please complete the following information):**
 - OS: Linux
 - Desktop Environment: GNOME

**Additional context**
I was testing the calendar with Lighthouse & it suggested adding the `lang` attribute to the `<HTML>` tag to solve this problem.

**Comment by charlag** [comment]
on new Android we can even switch the whole system language per app, I don't remember if it can be done only by the user though

**Comment by charlag** [comment]
This doesn't seem to be possible as other apps also don't do this, closing it for the time.
