### ISSUE TITLE
Unable to access mail webapp from Mull Browser

### ISSUE THREAD

**Issue by XaviDCR92** [tutao/tutanota#6445]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue. -> https://github.com/tutao/tutanota/issues/6391 is similar, but was closed.

**Bug in web app**

**Describe the bug**
I am unable to enter https://app.tuta.com from [upstream Mull Browser](https://f-droid.org/en/packages/us.spotco.fennec_dos):

```
Tuta Mail

Seems like your browser is not supported or outdated. Please see FAQ entry for more information
https://tuta.com/faq/#browser-support

Mozilla/5.0 (Android 10; Mobile; rv:121.0) Gecko/121.0 Firefox/121.0
Error: Unsupported
execute@https://app.tuta.com/app.js:1:75530
i@https://app.tuta.com/polyfill.js:1:4214
P@https://app.tuta.com/polyfill.js:1:4183
x.import/</</t.C<@https://app.tuta.com/polyfill.js:1:3651
```

However, as opposed to https://github.com/tutao/tutanota/issues/6391, adjusting `javascript.options.baselinejit = true` did not solve the issue.

**To Reproduce**
1. Get Mull Browser.
2. Access https://app.tuta.com.

**Expected behavior**
I should be able to access the mail webapp.

**Screenshots**
N/A.

**Smartphone (please complete the following information):**
- Device: N/A
 - OS: Android
 - Browser Mull Browser
 - Version `121.1.0 (Build #21211020), 62d5117f79+`

**Comment by rezbyte** [comment]
Hi @XaviDCR92,
Sorry to hear you are having issues with accessing the web app.

Does your browser have WASM enabled? Unfortunately, we require WASM for the web app to function.

**Comment by XaviDCR92** [comment]
Enabling `javascript.options.wasm` from `about:config` solved the issue. Thank you very much!

**Comment by Sami32** [comment]
@rezbyte My suggestion is to add this Mull setting requirement into your documentation:
https://tuta.com/support/#browser-support

Firefox is not documented as supporting your Tuta web application on Android but it does.

As a side note your web application also support Waterfox browser and probably others Firefox fork without any issue.

**Comment by rezbyte** [comment]
Hi @Sami32,
Thank you for your suggestion.

We could list the requirement however, having WASM enabled will soon not be required. We have implemented an automatic JavaScript fallback for our WASM components (#6814) which work the same albeit slower. This fallback will be released in the coming months.

**Comment by charlag** [comment]
> @rezbyte My suggestion is to add this Mull setting requirement into your documentation: https://tuta.com/support/#browser-support
> 
> Firefox is not documented as supporting your Tuta web application on Android but it does.
> 
> As a side note your web application also support Waterfox browser and probably others Firefox fork without any issue.

please note there's a difference between "the app works on browser X" and "we are making sure the app works on browser X". We are trying to support as many platforms and browsers as possible but we can only test on a certain number of them

**Comment by kkcarlc** [comment]
> Hi @Sami32, Thank you for your suggestion.
> 
> We could list the requirement however, having WASM enabled will soon not be required. We have implemented an automatic JavaScript fallback for our WASM components (#6814) which work the same albeit slower. This fallback will be released in the coming months.

Thank you for adding this support. I am hitting the same issue with Mullvad Browser and was going to open a ticket to support Firefox ESR. I can confirm the above wasm setting in `about:config` works and look forward to the upcoming JavaScript fallback allowing the default browser settings.
