### ISSUE TITLE
Finish MailDetails migration (renew offline storage)

### ISSUE THREAD

**Issue by jomapp** [tutao/tutanota#6449]
In order to finish the MailDetails migration we need to delete cached mail entries from the offline storage that where stored in the old format (MailBody stored directly on Mail). Therefore we need to:

- [ ] Delete all Mails and MailBodies from the offline storage
- [ ] Trigger a recreation of the offline storage

We need to do this, as we store range information on available data in the offline cache, and these ranges currently do not support deleting only certain ranges from the range database.

**Comment by charlag** [comment]
Fixed by #6459
