### ISSUE TITLE
Unable to move events I'm invited to to other calendars when I am not the organizer

### ISSUE THREAD

**Issue by pappasadrian** [tutao/tutanota#6454]
- [X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X ] I've searched and did not find a similar issue.

**Describe the bug**
When being invited to an event and accepting the invitation, the event gets added to the first/top calendar. Because I am not the organizer, the app doesn't allow me to move it to another calendar of mine (which I want to do for organization / color coding purposes).

**To Reproduce**
0. Have multiple calendars
![image](https://github.com/tutao/tutanota/assets/2352509/2cee783a-cdfd-4f2e-aa7f-50eda70324a0)
1. Receive an invitation to an event, which can be added to the calendar (in my case via google calendar, but I am not sure if this is important in this bug report)
2. Click on "yes" on the dialog that appears on the top of the invitation email
![image](https://github.com/tutao/tutanota/assets/2352509/786abe27-8965-40c5-a641-34b252ad8c86)
3. Attempt to edit the event in the calendar.
4. The dropdown that normally allows you to move the event to another calendar is disabled / does not appear.
![image](https://github.com/tutao/tutanota/assets/2352509/c6387fa9-c7c2-4439-9b2a-7f77027ba95c)

**Expected behavior**
I want to be able to move events that I am not the organizer of to other calendars, primarily so that I can have a color coded overview of my schedule. Notably, I can still add reminders for events that I am not the organizer of, so the functionality of editing some aspects of such events isn't entirely disabled. 

**Screenshots**
(included inline above)

**Desktop (please complete the following information):**
 - OS: ubuntu 23.10
 - Desktop Environment, gnome
 - Version 3.121.4

This also happens in the Android app.

**Comment by theLastOneWhichIsAvailable** [comment]
Exactly what i want too.
