### ISSUE TITLE
Doesn't work with web proxy

### ISSUE THREAD

**Issue by ballo** [tutao/tutanota#6464]
Unlike every other https web site, tutanota cannot use a http proxy.

**Comment by charlag** [comment]
Hi you would probably need to be a bit more specific. Is it because of websocket? We are not really doing anything special.

**Comment by ballo** [comment]
> Hi you would probably need to be a bit more specific. Is it because of websocket? We are not really doing anything special.

For some reason the connection which was provided my a Pixel 7 was blocking tutanota.com which was resolved by rebooting the phone. I don't know why or how this happened, but I had assumed it was due to the web proxy because it seemed to be the only difference and it was only affecting one web site. I'll close the issue. Sorry I don't know why this happened.
