### ISSUE TITLE
Delete message

### ISSUE THREAD

**Issue by uerapa** [tutao/tutanota#6466]
Cant delete message

- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.![cant delete asus message Näyttökuva 2024-02-02 094810](https://github.com/tutao/tutanota/assets/158554998/c55275d9-eb0a-4ebd-9077-c738a80674c0)
**Bug in web app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by charlag** [comment]
Most likely your offline cache if out of sync. Please try to remove your account and add it again. If it doesn't work please contact support so they can analyze your case.
