### ISSUE TITLE
Tuta mobile app doesn't open email content anymore on Huawei phone

### ISSUE THREAD

**Issue by gemart1234** [tutao/tutanota#6474]
Tutanota mobile app doesn't open email content anymore on Huawei Android phone.
The notification and receiving emails works, but when try to open any email it doesn't.
It says ''Some parts of the email failed to load due to a lost connection''. 
The model of the phone is Huawei P40 lite. Tuta app is the latest version. Huawei WebView is the latest version, and it is used by the system.

**Comment by charlag** [comment]
See https://github.com/tutao/tutanota/issues/6474

**Comment by charlag** [comment]
sorry I meant https://github.com/tutao/tutanota/discussions/6490
