### ISSUE TITLE
No "Log in" button, now there is only "Add account"

### ISSUE THREAD

**Issue by marines1** [tutao/tutanota#6477]
There has been a problem with the login form for 2 days.
There is no "Log in" button, now there is only "Add account". The "remember password" button has also disappeared.
Now I have to be logged in all the time, previously I could enter my login and password every time. It was safer.

System: Android 14.

**Comment by paw-hub** [comment]
Thanks for your issue!

This is a recent change we did to the apps. Presently we offer the "Store password" checkbox only when signing on the webapp at https://app.tuta.com.

If you are concerned about someone accessing your phone potentially going into your email account, you can go to Settings -> Login, then go to Unlock method. In your case, I recommend selecting "System password or biometrics" to require your device's PIN to be entered or "Biometrics only" to require a fingerprint from your device.

**Comment by paw-hub** [comment]
Also, you can delete the credentials from the login screen if you do not want your account login information stored on the device. Simply select "Remove account", then "Delete" next to the account you wish to remove.

**Comment by marines1** [comment]
> Thanks for your issue!
> 
> This is a recent change we did to the apps. Presently we offer the "Store password" checkbox only when signing on the webapp at https://app.tuta.com.
> 
> If you are concerned about someone accessing your phone potentially going into your email account, you can go to Settings -> Login, then go to Unlock method. In your case, I recommend selecting "System password or biometrics" to require your device's PIN to be entered or "Biometrics only" to require a fingerprint from your device.

This is a very bad change. This affects the security of user data because when someone gains access to your phone, they can steal your login details because they will be stored on the phone.  Someone can perform an FFS (Full file system) extract and decrypt the password file.  This can be done using many tools, e.g. Celebrite UFED or Oxygen Forensic Detective.  Each user should be able to remember the login password or enter the login every time.  Storing your login details on your phone is dangerous.  I don't understand why you made such a change.  It looks a bit like you want to support the police or other services.

**Comment by marines1** [comment]
> Also, you can delete the credentials from the login screen if you do not want your account login information stored on the device. Simply select "Remove account", then "Delete" next to the account you wish to remove.

If I delete my account, I will not receive notifications about new messages.

**Comment by charlag** [comment]
All the data and credentials are encrypted with a keychain, is is much harder to extract than you think.

You will not receive notifications. It is what most users expect, a lot of people been caught off-guard by this and wasn't good security-wise in its own right
