### ISSUE TITLE
 Switching from contact to mail search when there are no result leads to an error

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6497]
v3.121.4 at least until 3.112.1

 * search for some contact, query that only yields contact results but no mail results
 * select a contact
 * switch to mail, see error:

```
TypeError: Cannot read properties of undefined (reading '_id')
at MailViewerViewModel.showFolder (asset://app/mail-view-SUg5ZMxK.js:1:83095)
at new MailViewerViewModel (asset://app/mail-view-SUg5ZMxK.js:1:82460)
```

## Test Notes
- [ ] Try to repro, see no error
- [ ] When there are no results, "No results" is shown
- [ ] Search works as expected (mail, contacts, and calendar)
- [ ] switching between search types works as expected

**Comment by paw-hub** [comment]
> switching between search types works as expected
Switching always results in "No results" even when switching back. Is this intentional? It isn't what I expected, at least.
