### ISSUE TITLE
Cannot open any mail.

### ISSUE THREAD

**Issue by madijason** [tutao/tutanota#6506]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I can't open any mail on any devices. I've got the app in the last version on my tablet (HarmonyOS) and my phone (Android under EMUI 13) and on both, mail won't open.
It says "No internet connection".

**To Reproduce**
Just open any mail.

**Expected behavior**
Open the mail and show content.

**Smartphone (please complete the following information):**
 - Device: HUAWEI Nova 9 & HUAWEI Matepad 10.4
 - OS: HOS2 & EMUI 13 (Android 12)

**Comment by charlag** [comment]
Please check if your WebView if up-to-date: https://tuta.com/support/#web

**Comment by madijason** [comment]
Hi! Huawei WebView is up-to-date. Don't have any update awaiting.

**Comment by charlag** [comment]
Do you see the WebView version/User Agent is Settings -> About -> Send logs?

**Comment by madijason** [comment]
Mozilla/5.0 (Linux; Android 12; NAM-LX9 Build/HUAWEINAM-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36

**Comment by charlag** [comment]
Chrome 92 is quite old, please see if you can switch to another WebView
https://tuta.com/support/#web

**Comment by xmgz** [comment]
I'm also affected by this issue, I can not read emails on android 9 in the last few weeks. This app, in my device, currently is just a _notifier_ for new incoming emails.

I've contacted Tuta's support and instructed to **upgrade** webview. It will not be as easy as it looks like :/ but I will try.

Yes, it's a 4 years old device, but I never thought Tuta would be the first app I could not use in it (eventually I knew some would fail in a old rom without system updates).

Please consider bring back compatibility for older android versions. Thank you.
