### ISSUE TITLE
The Desktop client crash when new mail is received

### ISSUE THREAD

**Issue by BugProg** [tutao/tutanota#6508]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Each time I received a new mail, the client crash.

**To Reproduce**
1. Open Tuta client
2. Do something else (Active other windows in another app, don't stay on Tutanota)
3. Wait for a new email
4. Click on the Tuta App to enable user interaction

**Expected behavior**
Read the mail without to have reopened the app.

**Screenshots**
[Screencast from 2024-02-08 10-55-29.webm](https://github.com/tutao/tutanota/assets/54059521/dabd1f99-58b9-4fe2-9d94-f838414bed7b)
The app crash when I received the notification and **I clicked on the tuta App.**

**Desktop:**
 - OS: Linux Fedora 39
 - Desktop Environment: Gnome, app installed with Flatpak
 - Version v3.121.4

**Comment by charlag** [comment]
Hi, could you please check if it happens to AppImage version as well?

**Comment by BugProg** [comment]
Yes, it seems to be an issue with Flatpak only...😥

**Comment by charlag** [comment]
Please reopen it under https://github.com/flathub/com.tutanota.Tutanota/

There are many issues with the Flatpak app at the moment
