### ISSUE TITLE
Disabled text field issues

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6512]
v3.112.3

 * The opacity is too small. Material 3 recommends 0.38 for text fields but even that is probably too little for us (current is 0.3). I suggest something like 0.6.
 * Some text fields are used to display information and should have readonly instead of disabled parameter. e.g. whitelabel settings when whitelabel is already active

## Test notes
- [ ] Go to a disabled field (e.g. a field for an event you can read but not modify), and verify that it's 60% opaque, not 30% (should be quite readable but slightly faded).
- [ ] Go to these fields and verify they are not disabled (i.e. full opacity), but they are still read-only:
  - [ ] Contact merge dialogue
  - [ ] Calendar event description
  - [ ] Email signature if using a non-custom signature
  - [ ] Whitelabel domain settings when whitelabel is enabled
  - [ ] Invoice address in payment viewer
  - [ ] Session info (client, IP address, date) in login settings
  - [ ] Search date when searching emails (note: this should be editable with the pencil button, but you shouldn't be able to edit the text in the text field itself with your keyboard)

**Comment by charlag** [comment]
> Email signature if using a non-custom signature

Default signature is disabled, custom is enabled. What is meant here?

**Comment by paw-hub** [comment]
> > Email signature if using a non-custom signature
> 
> Default signature is disabled, custom is enabled. What is meant here?

Nah, that behavior's actually correct. I may have listed this one by mistake in the test notes.

**Comment by paw-hub** [comment]
> > Email signature if using a non-custom signature
> 
> Default signature is disabled, custom is enabled. What is meant here?

Actually, no, I went and tested it, and I'm pretty sure it was intended for this text field to be read-only if you pick Default, but disabled if you pick None.

Seems it's just always disabled? This could be fixed trivially, but it's probably fine.

**Comment by paw-hub** [comment]
So I was wrong - it's not really trivial and would probably take more time than it's worth right now to actually fix.

That said, it's a fairly minor design nitpick. It doesn't look broken, and there is otherwise nothing functionally wrong with the signature editor/preview.
