### ISSUE TITLE
Cannot paste multi-line from android clipboard

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#6525]
**Bug in mobile app**

**Describe the bug**
When copying text, when I try to paste multi-line text from the clipboard it fails. (press-holding and then selecting "paste" does work)

First brought to attention by Github user trizen in #6450 

**To Reproduce**
1. Copy multi-line text
2. Press text at top of keyboard (or from the keyboard's clipboard manager)
3. no text is pasted

**Expected behavior**
text is pasted

**Smartphone (please complete the following information):**
 - Device: android (paste works as expected on iphone)

## Test notes
- [ ] Paste on desktop/web still works
- [ ] paste on ios still works
- [ ] paste on android works
   - [ ] long hold and then paste
   - [ ] pasting from clipboard
- [ ] pasting single line and multi-line text works
- [ ] pasting images works

**Comment by rezbyte** [comment]
Pasting images does not work but is likely due to #6091.

**Comment by rezbyte** [comment]
I am not sure whether this is correct behavior but any formatting is lost when pasting from the clipboard on Android.
