### ISSUE TITLE
Feedback v3.122.4 - Error - UNKNOWN - win32

### ISSUE THREAD

**Issue by user7901** [tutao/tutanota#6528]
(Windows 11 Pro 64 bits updated)
Tutanota 3.122.4
After update this afternoon:

"
Feedback v3.122.4 - Error - UNKNOWN - win32

 Client: win32
 Type: UNKNOWN
 Tutanota version: 3.122.4
 Timestamp (UTC): Fri, 09 Feb 2024 15:47:45 GMT
 User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.122.4 Chrome/120.0.6099.268 Electron/28.2.1 Safari/537.36
Error
 Error message: EBUSY: resource busy or locked, unlink 'C:\Users\frajo\AppData\Roaming\tutanota-desktop\offline_MtOLMij----2.sqlite'
Stacktrace: 
Error: EBUSY: resource busy or locked, unlink 'C:\Users\frajo\AppData\Roaming\tutanota-desktop\offline_MtOLMij----2.sqlite'
"
I can use Tutanota, but each time I open it this error message persists.

**Comment by Onair-santa** [comment]
error too

**Comment by anotheruserwhowantstohelp** [comment]
#6524 same issue
