### ISSUE TITLE
Send emails non-confidential to external recipients by default

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6532]
We noticed that for some new users it is confusing that you have to enter a password when sending an email to an external recipient. In order to have a smooth onboarding for a new customer we want to send non-confidential by default.

Nevertheless, by clicking the lock symbol the email draft can be switched to confidential. Similarly in the settings the default can be changed.

## Test notes

- [ ] Create a new account
  - [ ] Verify that external emails are sent non-confidentially by default in the settings (Settings -> Email -> Default delivery -> Not confidential)
  - [ ] Verify that, when drafting an email to be sent externally, it is also not confidential
- [ ] Verify that any existing user is not affected by this change

**Comment by murilopereirame** [comment]
Closed by MR 584
