### ISSUE TITLE
Update Squrie to 2.2.6

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6534]
## Regression Test
- When creating a new reply the text direction is:
     - [ ] LTR when writing in an LTR language
     - [ ] RTL when writing in an RTL language

- When writing a new email, the text direction is:
  - [ ] LTR when writing in an LTR language
  - [ ] RTL when writing in an RTL language

- When adding a description to an event, the text direction is:
  - [ ] LTR when writing in an LTR language
  - [ ] RTL when writing in an RTL language

- When creating a custom signature, the text direction is:
  - [ ] LTR when writing in an LTR language
  - [ ] RTL when writing in an RTL language

- All places that use the MailEditor:
  - [ ]  Formatting still working
  - [ ] The Undo/Redo works
  - [ ] Creating lists works
  - [ ] Inserting inline images works
  - [ ] Copy/Paste still working

**Comment by rezbyte** [comment]
We will need to either make a PR to Squire or reapply the fix for #6220 to avoid regressing it.
