### ISSUE TITLE
cannot toggle full screen from title bar on macOS

### ISSUE THREAD

**Issue by kibhub** [tutao/tutanota#6543]
on macOS, after maximizing the client, the title bar buttons to minimize or toggle full screen are disabled. 
Using the View menu > Toggle fullscreen works.

See screenshot:

![image](https://github.com/tutao/tutanota/assets/104761667/45dc32e9-e75b-4bcd-b3ee-49f39ebbe8d6)

**Comment by jalhubb** [comment]
reportedly works again after updating macOS version.
suspected to be an electron related issue.
