### ISSUE TITLE
App crashes if a file with an unknown extension is downloaded

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#6552]
We throw errors that lead to crashing apps in `CustomSchemeHandlers.swift` and `MainActivity.kt` in case we try to download an unknown file extension.

Expected behaviour:
* The app should not crash
* The error report dialog is not shown

**Comment by charlag** [comment]
This is not "downloaded" as in normal user action, this happens if we bypass native functions for downloading files and try to request an asset via asset URL. We should not deliver unknown assets.
