### ISSUE TITLE
[iOS] Blank screen after app was in background

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#656]
> I notice that several times each day the app screen goes completely white, and I can’t do anything with it. Rebooting my phone is the only way to resolve it. This is happening several times a day, so it’s quite inconvenient having to restart the device, sometimes at quite important moments, eg when looking in my email to show tickets to someone at an event.

**Comment by charlag** [comment]
It does seem like a WebView bug to me, let's see if we continue to get reports like this

**Comment by charlag** [comment]
Havent's heard about this since then, must be fixed

**Comment by bedhub** [comment]
An user has reported that the blank screen appears sometimes if the app is in background for a long time. If the app is then moved to foreground again the whitescreen appears. A reboot was not necessary for him he just killed the app and restarted again. He was only able to reproduce it when search was enabled.

**Comment by armhub** [comment]
Occurred on iOS 12.2, even after re-installing the app.

**Comment by charlag** [comment]
It does not depend on re-installing but on mere restarting.

13 May 2019, 09:35 by notifications@github.com:

**Comment by Isvvc** [comment]
I am running the iOS 13 public beta on an iPhone X and I can't get anything but a blank screen after logging in. The login screen shows up fine, but once I press the "Log in" button, with correct or incorrect credentials, I get a blank screen. Closing the app and reopening it brings me back to the login screen. Reinstalling the app and rebooting the device does not make a difference.

**Comment by Isvvc** [comment]
I'm not sure if it was the iOS Beta update, the Tutanota app update, or something else, but with app version 3.55.5 and iOS Public Beta 3, I no longer have this issue.

**Comment by bedhub** [comment]
Problems regarding iOS 13 are covered here:

https://github.com/tutao/tutanota/issues/1297

We keep this issue for now to check if the problem still exists on iOS 12.

**Comment by bedhub** [comment]
Reported again for iOS 13 (beta 8) after app was in background. Seems like the lates iOS 13 beta behaves now like iOS 12.
