### ISSUE TITLE
Calendar view UI issues on small desktop layout

### ISSUE THREAD

**Issue by marcosdiasalves** [tutao/tutanota#6562]
Calendar view issues on small desktop layout

![image](https://github.com/tutao/tutanota/assets/3099142/e43b0b48-bb95-4ebc-9a70-5d7af08a8543)

 * [x] Use short names for months when there are 2 months, we already use them elsewhere
 * [x] Week number in the column above time. If the time column not displayed (desktop agenda), do not show it
 * [x] Today indicator: try to use darker gray (like icon buttons) and make text inside of it light (see "today" button)
 * [x] Increase minimum size for the nav column so that mini calendar fits into it
 * [x] Mini calendar selected week indicator looks off, margins on the size should not be proportional to the width, they should be fixed, corner radius could be smaller
 * [x] Make sure that "new event" button is aligned with mini calendar, even when nav column has a scrollbar (reserve space for the scrollbar?)

## Original issue

Calendar Weekly view - when the month changes, the week number overrides other information. Language set to Brazilian-Portuguese.
![Captura de Tela 2024-02-15 às 16 40 01](https://github.com/tutao/tutanota/assets/39956843/bc5343ce-6592-484f-8954-2ae8d6d7c9bf)

## Test notes
- [ ] When there are two months, the short names for months are used.
- [ ] The week number is displayed in the same column as time.
- [ ] The circle highlight for the day is white on dark gray.
- [ ] The mini calendar looks fine at all widths
- [ ] The week highlight in the mini calendar looks good.
- [ ] The "new event" button stays aligned when a scrollbar is present.

**Comment by marcosdiasalves** [comment]
I would like to remove this Week # information; it should be optional.

**Comment by jan1577** [comment]
Related to this, but not sure if this will be handled with this issue already:

The buttons to switch to the next/ previous week diappear below 900px width. Makes it impossible to switch weeks in split screen on a 12" device.
