### ISSUE TITLE
Calendar entry text may overflow with time

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6582]
Please see the screenshot:
![screenshot-appointments](https://github.com/tutao/tutanota/assets/7211155/9651b8ef-e88c-4e54-ad5a-64894690a62d)

The calendar entry title ("Meeting 1 with much more text here") overflows the time indicator.

## Test notes
- [ ] The event title does not overflow:
  - [ ] at various viewport sizes
  - [ ] when multiple events are stacked with the same start times
  - [ ] when the event duration is short such as 10 minutes

**Comment by marcosdiasalves** [comment]
I am able to reproduce this.
v218.240219.0

**Comment by marcosdiasalves** [comment]
Not fixed for me. 

![WhatsApp Image 2024-04-12 at 17 14 00](https://github.com/tutao/tutanota/assets/39956843/3e9cb919-52ca-40cc-bc13-9a15dbf282a7)

Tuta V220.240411.0.
Samsung Galaxy A30 - Android 11 - One UI 3.1

**Comment by rezbyte** [comment]
> Not fixed for me.

Hi @marcosdiasalves,
Sorry to hear that you are still experiencing issues.

I will mention this to our team and see what we can do.

**Comment by marcosdiasalves** [comment]
Not yet fixed @rodrigopereirame ! Do not bring this bug to the new standalone calendar app, please.

**Comment by wrdhub** [comment]
@marcosdiasalves I'm sorry that this still happens for you. I was hoping that the solution for other issue might help with it, but it seems like it has not. We have tested on multiple devices, and we simply cannot reproduce this. I am also not aware of other users still having this issue. I saw the reddit post, if more people say they are seeing this too maybe we can find the underlying issue. Updating your webview may help (https://tuta.com/support#web), an old webview has caused some issues in the past.

**Comment by marcosdiasalves** [comment]
Hi Wren,

Webview installed was 127.0.6533.103. Removed and reinstalled from Play
Store, version remains the same.

Removed and reinstalled Tuta. v244.240903.0. Same error.

Problem is observed on both Samsung A25 and A30. On Samsung Tablet A7
(larger screen) there is no issue.

Thanks for your contact.

--------------------------------------
Marcos D. Alves
***@***.***



Em qua., 4 de set. de 2024 às 08:59, Wren ***@***.***>
escreveu:

**Comment by marcosdiasalves** [comment]
Any news about this?
