### ISSUE TITLE
Deleting search terms is not possible with "x" button

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#6604]
How to reproduce:
1. Enter any search terms in the email search field
2. Click the "x" button to delete the search terms.
-> The search terms are not removed from the search field.

Reproduced in Linux desktop client v218.240219.0

## Test notes:
On any platform
- [ ] Pressing the 'X' button that appears after entering text into the email search text field clears the text field

**Comment by rezbyte** [comment]
There is a fix for this inside #6631.
