### ISSUE TITLE
Restricted battery usage is enabled, but application runs in background

### ISSUE THREAD

**Issue by marek141017** [tutao/tutanota#6635]
**Bug in mobile app**

**Describe the bug**
Application continues to work in background even if restricted battery usage is enabled

**To Reproduce**
Set restricted battery usage for tuta application
1. Go to battery usage per app and see that background usage time will increment

**Expected behavior**
In restricted battery usage mode application must not run in background and consume battery

**Screenshots**
not necessary

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 14
 - Tuta app Version 218.240227.0

**Comment by charlag** [comment]
Hi
We ask Android to run the app periodically to sync notifications. Until better notification settings get implemented you can disable push identifier in Settings -> Mail. Battery optimization just gives us more time to run in background, it does not disable anything.
