### ISSUE TITLE
Click on notification should open the email

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6658]
When clicking on a notification i expect that the tuta app opens so that i can read the content of the email that i have received the notification for.

### AC

* Click on notification opens the app and selects the corresponding mail in the list.
* Mail can be displayed before synchronization is done
* Works on Web, iOS, Android and Desktop app
* Mail instance is not loaded again.
* In case the mail has been deleted we show a info message (SnackBar) that the mail has been deleted.

### Notes
What should happen if the mail has not been loaded yet?

 Option1: Wait for synchronization and then select the mail
 Option2: Load the mail before synchronization, event if it is not in the list.

→ Try option 2

What happens if the mail has been moved to different folder or deleted?

Option1: In case the email cannot be loaded show a non blocking snackbar.
Option2: We have the mail already available in the notification, we could reuse the loaded entity and use that to load MailDetails.

→ Try option 2

### Tasks
 - [x] #7371 
 - [x] #7372 
 - [x] #7373 
 - [x] #7374

**Comment by rezbyte** [comment]
We have decided to use `6658-notification-click` as an integration branch to store the common elements like the deleted mail info message. This way each platform's branch can fork off from it and reuse the same commits.
