### ISSUE TITLE
SecurityError on PushState

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#666]
> AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15

```
Stacktrace: 
pushState@[native code]
setPath@https://mail.tutanota.com/main-boot.js:1:262633
set@https://mail.tutanota.com/main-boot.js:1:263932
value@https://mail.tutanota.com/main.js:1:175966
value@https://mail.tutanota.com/main.js:1:180057
value@https://mail.tutanota.com/main.js:1:639214
onclick@https://mail.tutanota.com/main.js:1:636380
```

**Comment by mpfau** [comment]
We need to wait for an error message on the current client. Might be that this happens only for mailto handling or is triggered from mithril.

**Comment by armhub** [comment]
Only reported up to version 3.38.1
Asked users for more information.

**Comment by charlag** [comment]
This one is good. Maybe we should just catch and ignore it.

```
Client: ios app
Tutanota version: 3.40.4
User agent: 
Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B92

Error message: 
Attempt to use history.pushState() more than 100 times per 30.000000 seconds

Stacktrace: 
pushState@[native code]
setPath@file:///var/containers/Bundle/Application/DBAE5DCA-9536-4B63-AB08-E1893E00FA6F/tutanota.app/build/dist/main-boot.js:1:246817
set@file:///var/containers/Bundle/Application/DBAE5DCA-9536-4B63-AB08-E1893E00FA6F/tutanota.app/build/dist/main-boot.js:1:249014
value@file:///var/containers/Bundle/Application/DBAE5DCA-9536-4B63-AB08-E1893E00FA6F/tutanota.app/build/dist/main-boot.js:1:151539
```

**Comment by charlag** [comment]
We tried to call `replaceState()` instead but it didn't help. We need to skip any actions during this time (maybe only in Safari)

**Comment by armhub** [comment]
This is a specific problem in Safari in the way they handle URL updates, therefore we consider this as browser bug.

**Comment by charlag** [comment]
Now Chrome does similar thing:
>Throttling history state changes to prevent the browser from hanging.

scrolling with keys is hard this way
we need to decouple URL and selection mechanism somehow
