### ISSUE TITLE
Legacy account gets error when adding email addresses

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#6667]
Legacy accounts are getting errors when trying to add another email address

**To Reproduce**
1. Have a legacy account
2. add another email address under Settings > mail > Email addresses
3. The "Add email address" dialog appears
4. Type in address and press "okay"
5. error appears: BadRequestError 400 for mailaddressaliasservice

**Expected behavior**
This happens both when the account has more than the allowed amount of email addresses and unused email addresses available.
In the first case, an upgrade dialog should appear.
In the latter, the address should be added.

## Test Notes
- [ ] Legacy Paid Account
     - [ ]  When adding another email address, @tutamail.com is the default domain
     - [ ]  trying to select the tuta.com domain shows a popup explaining that tuta is only for new subscriptions
     - [ ] when trying to add another email address with no slots left, an upgrade dialog is shown
- [ ] New Paid Account
     - [ ]  when adding another email address @tuta.com is the default domain
          - [ ] Unless the account has a custom domain, then that domain is shown
     - [ ] Adding another email address with any domain works
     - [ ] when trying to add another email address with no slots left:
        - [ ] On the Revolutionary or Essential plan: an upgrade dialog is shown
        - [ ] on advanced, unlimited, or legend: a "max # of aliases" message is shown
- [ ] Custom email domain
  - [ ] can add another email address with custom email domain even when number of address slots is full
  - [ ] cannot add another email address with non-custom email domain when number of address slots is full

**Comment by charlag** [comment]
I feel like we already have an error for this somewhere

**Comment by wrdhub** [comment]
I have found this only happens when trying to add a tuta.com address, if a legacy user tries to add an address with another domain it will work (given they have available addresses).
