### ISSUE TITLE
storage is not cleared

### ISSUE THREAD

**Issue by kargo123456** [tutao/tutanota#6674]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kargo123456** [comment]
I use the free plan.
Permanently deleted letters with a volume of 150 megabytes
But the storage is still not cleared.

**Comment by kargo123456** [comment]
I use the free plan.
Permanently deleted letters with a volume of 150 megabytes
But the storage is still not cleared.

**Comment by rezbyte** [comment]
Hi @kargo123456,
Please reply inside the conversation #6673.
