### ISSUE TITLE
Unable to display any email on Android under EMUI

### ISSUE THREAD

**Issue by vhscom** [tutao/tutanota#6703]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
I'm unable to view the content of any email using the Android native client. I have been using this app for three years.

**To Reproduce**
1. Go to email
2. Click on an email
3. See error

**Expected behavior**
Emails with email bodies

**Screenshots**
![Screenshot_20240313_152011.jpg](https://github.com/tutao/tutanota/assets/97140109/f181d8fa-4376-474a-aac2-566a1f39b3db)

**Smartphone (please complete the following information):**
 - Device: Huawei P40 Pro+
 - OS: EMUI
 - Version: 12.0.0
 - WebView Version: 12.1.2.323
 - Container: Huawei WebView
 - Tuta: v218.240311.0

**Additional context**
Issue started about 2 months ago. I've been running this version of EMUI for over a year and using Tuta daily without any problems until recently. Issue also affects Search but not Sending.

**Comment by charlag** [comment]
What is your WebView version?

**Comment by vhscom** [comment]
> What is your WebView version?

Huawei WebView 12.1.2.323

Been using Tuta reliably on a Huawei phone without Google for 3 years.

**Comment by vhscom** [comment]
> What is your WebView version?

Good question! I have updated the issue details to reflect my OS and WebView versions.

**Comment by vhscom** [comment]
> What is your WebView version?

Good question! Updated the issue details to reflect my OS and WebView versions.

**Comment by charlag** [comment]
@vhscom I'm sorry but this is not a version. Could you go to Settings -> About -> Send logs? It should create an email draft and should put your user-agent in the mail body. Could you paste it here?

**Comment by vhscom** [comment]
> Settings -> About -> Send

This is not an option under EMUI. I've updated the issue title to be more specific as to the runtime. I can also provide Linux kernel info if needed. The UA string I'm happy to provide though it's not clear to me how to access it.

**Comment by charlag** [comment]
This is an option *in the app*

**Comment by vhscom** [comment]
Hey look at that. Thanks, until I trained my attention very carefully on the Settings drawer in the app, and not Advanced Settings, I never noticed About was a hyperlink. An underline to decorate the link would make it more discoverable.

```
Client: android

Type: FREE

Tutanota version: 218.240311.0

Timestamp (UTC): Tue, 26 Mar 2024 13:04:37 GMT

User agent:

Mozilla/5.0 (Linux; Android 10; ELS-N39 Build/HUAWEIELS-N39; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36
```

Please let me know if logs would be useful now that the UA string is known. I saw the files created in a draft email after clicking the About link in the drawer after clicking the gear icon in the navigation rail but have not yet had a chance to scrub them for security.

**Comment by charlag** [comment]
Thank you. It does seem the WebView might be the cause, Chrome 92 is quite old and it probably has some CSP issues.

Please follow the instructions here:

https://tuta.com/support/#web

**Comment by vhscom** [comment]
That makes sense given the recent adjustments to email security. I found a workaround time being until I get my HOTA to just run the web app in a browser. I may actually just stick with this though it could use a branded icon. 
![Screenshot_20240329_195437.jpg](https://github.com/tutao/tutanota/assets/97140109/7a3ceae1-b33f-4568-84c2-6fdbe1739739)

**Comment by vhscom** [comment]
That makes sense given the recent adjustments to email security. I found a workaround time being until I get my HOTA to just run the web app in a browser. I may actually just stick with this. Thanks for the help! ☺️
![Screenshot_20240329_195437.jpg](https://github.com/tutao/tutanota/assets/97140109/7a3ceae1-b33f-4568-84c2-6fdbe1739739)

**Comment by vhscom** [comment]
That makes sense given the recent adjustments to email security. I found a workaround time being until I get my HOTA to just run the web app in a browser. I may actually just stick with this.

Thanks for the help! ☺️
![Screenshot_20240329_195437.jpg](https://github.com/tutao/tutanota/assets/97140109/7a3ceae1-b33f-4568-84c2-6fdbe1739739)
