### ISSUE TITLE
German text overflows on last screen in new onboarding flow. 

### ISSUE THREAD

**Issue by jomapp** [tutao/tutanota#6713]
See screenshot below.

![devbug_onboarding](https://github.com/tutao/tutanota/assets/17314077/25d48e72-dd60-4da7-a347-a38ef74f3117)

## Test Notes
- [ ] Each page has a good layout in portrait view
- [ ] Each page has a good layout in landscape view

**Comment by rezbyte** [comment]
It looks good, the radio button does not overflow anymore. However, I did notice the contacts page scrolls in portrait view.
![Screenshot_20240318-103214](https://github.com/tutao/tutanota/assets/48037381/949cfb8d-9aae-4d92-8525-b8d85b89875a)
