### ISSUE TITLE
Parents are not imported when importing a vcard

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6723]
**Bug in mobile app**

**Describe the bug**

**To Reproduce**
1. Create a contact with a 'parent' relation in Android's included contact app
2. Export the contact as a vcard
3. Import the vcard into Tuta Mail's contacts
4. See the parent is missing

**Expected behavior**
The imported contact has a relation 'Parent'.

**Smartphone (please complete the following information):**
 - OS: Android

**Comment by murilopereirame** [comment]
Google uses a custom field to export relations on vCards and it doesn't comply with the RFC so we should close this issue as we do not support custom fields for now.
