### ISSUE TITLE
Android: month title does not fit to calendar days

### ISSUE THREAD

**Issue by Casimir1965** [tutao/tutanota#6734]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in mobile app for Android**

**Describe the bug**
In der Android APP zeigt der Kalender falsche Beschriftungen an. Es steht zwar März 2024 als Text aber die Monatsübersicht zeigt den Februar 2024. Das macht die Terminplanung schwer.

**To Reproduce**
1. Go to 'calendar'
2. Select 'Agenda' form the Agenda/Day/Week/Month selector (near the plus sign)
3. Click on 'the small arrow beside month name'

**Expected behavior**
Month Name in title fits not (!) to the shown calendar days

**Screenshots**
![Screenshot_20240317-211917](https://github.com/tutao/tutanota/assets/136707767/3dbe4cae-8ea6-465f-a167-3f6af270f8c6)

**Smartphone (please complete the following information):**
 - Device: Pixel 7a
 - OS: GrapheneOS - Android v14
 - Version 

**Additional context**
Looks strange

## Test Notes
Test on Android, GrapheneOS, iOS, Chromium and Firefox.
- [ ] The first day of the month in the day selector matches the actual first day of the month
- [ ] Pressing on a day in the day selector when not expanded takes you to that day
- [ ] Pressing on a day in the day selector when expanded takes you to that day
- [ ] Swiping left on the day selector shows the previous week/month
- [ ] Swiping right on the day selector shows the next week/month

**Comment by charlag** [comment]
I can't reproduce it. For some reason it also does not show your currently selected date?

**Comment by Casimir1965** [comment]
Sorry, I missed in the description one step: 
1. Go to 'calendar'
2. Select 'Agenda' form the Agenda/Day/Week/Month selector (near the plus sign)
3. Click on 'the small arrow beside month name'
4. See error

If you've choosen the month view it fits perfectly together., I prefer the agenda or list view because it provides me a good overview about the upcoming days.

**Comment by charlag** [comment]
here's me attempting to reproduce it (unsuccessfully):

https://github.com/tutao/tutanota/assets/3099142/cb9f2414-f16f-462f-9f4f-ebef7b30912d

**Comment by Casimir1965** [comment]
@jomapp @charlag
Thank you for your feedback. One question remains: did you reproduce it with an browser (like vanadium or any other) or while using the Tuta App? On my device the issue is within the Tuta App directly. 

Is there something I can do on my side to avoid this?

**Comment by aclifton314** [comment]
I have this issue as well in the Tuta app:
Device: Pixel 7a
OS: GrapheneOS - Android v14
Tuta App: 218.240227.0

- I installed the app from Droidify and logged in.
- Tapping "Calendar" launches the monthly view and I see the correct number of days (31) and the correct day is encircled (March 20) on the monthly view. I also see the number next to the view selector is correct (March 20).
![Screenshot_20240320-192005](https://github.com/tutao/tutanota/assets/53267795/4193fd69-c629-4b11-a199-446a8b54f3f0)

- I logged into my Tuta account on my laptop and accessed the account from the web, creating two test calendar events, one on 20 March and one on 15 March.

- Going back to the Android app, I selected the Week view. I noticed the following:
     - The displayed week dates at the top were from the previous week.
     - The indicator of an event (the green dot) on the 15th is correct.
     - A test event shows up, but it is out of sync with the displayed week dates at the top. Namely, it is showing the March 20 event occurring on March 13.

![Screenshot_20240320-192658](https://github.com/tutao/tutanota/assets/53267795/35e099f5-17b0-4db9-ac37-f361e54a6a0c)

![Screenshot_20240320-192711](https://github.com/tutao/tutanota/assets/53267795/bcc1d4c8-e360-4fba-999a-b80ffc4c1232)

- I swipe forward at the top to progress the week dates forward. I notice the green indicator at the top is correct for the March 20 test event, the current day indicator circling March 20 is correct, but the test event itself does not show up:
![Screenshot_20240320-192729](https://github.com/tutao/tutanota/assets/53267795/091a0667-92ea-4959-96bd-baa7aa94685e)

- I then swipe back two weeks and notice that the March 15 event is showing up on March 8. As well, the event indicator is not shown (which is expected) and the current date gray circle is not present (which is also expected):
![Screenshot_20240320-192743](https://github.com/tutao/tutanota/assets/53267795/51806f5d-e95b-47c9-9b8f-8c472cbd0d44)

![Screenshot_20240320-192751](https://github.com/tutao/tutanota/assets/53267795/12f2c0f2-81c9-41d6-ac42-ddb8aa776890)

- I then uninstalled the Tuta App and downloaded the most recent release from the github (220.240319.1). I ensured that the app was completely removed to the best of my ability. However, the attempt to install the most recent version results in the following error:
![IMG_20240320_194934](https://github.com/tutao/tutanota/assets/53267795/d071d474-b516-4798-8fb4-11a8641eae95)

**Comment by jomapp** [comment]
> @jomapp @charlag Thank you for your feedback. One question remains: did you reproduce it with an browser (like vanadium or any other) or while using the Tuta App? On my device the issue is within the Tuta App directly.
> 
> Does it matter if I'm a free user or having a paid plan?
> 
> Is there something I can do on my side to avoid this?

@Casimir1965 I did reproduce it both in Vanadium (Chromium based default browser in GrapheneOS), and the Tuta app on GrapheneOS. The Tuta app uses the default WebView / browser of your Android system to display content. As Vandium is the default WebView / browser on GrapheneOS this happens both, directly in the browser and in the Tuta app.

No, it does not matter if you are on a free or paid plan.

You can not do anything yourself currently. If this is an issue related to the newest Chrome / Chromium version 123.0.6312.40 (what is likely) we need to wait for a fix by Google or GrapheneOS. Currently only GrahpeneOS users are affected.

I will further investigate.

**Comment by jomapp** [comment]
@aclifton314 Thank you for your detailed report! We could already reproduce the issue. 

The issue seems unrelated to our app though, as it only happens on GrapheneOS, which is now already using a **beta** (not yet fully released) version of Chromium (123.0.6312.40), which the default browser Vandium is based on.

**Comment by glidingthrough** [comment]
Another GrapheneOS user here also suffering from this. Hopefully gets sorted soon.

Additionally, clicking on a date in Agenda view takes you to the previous month.

**Comment by Au2mater** [comment]
I am experiencing the same issue in both week view and agenda view.
Aditionaly in week view, when I press the today calendar icon it takes me to th repvious week, instead of going to todays date current week.

Android App 
Tutanota version 220.240321.0
