### ISSUE TITLE
iOS: DATALOSS! 2-way sync kills ALL comment fields!

### ISSUE THREAD

**Issue by MustachedMario** [tutao/tutanota#6767]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
iOS: Introduced 2-way contact sync kills ALL contact comments!
Lost ALL my imported comments all my contacts
THANK YOU FOR PUSING OUT NON-TESTET APPS!
DONE WITH TUTA!

**To Reproduce**
1. add a comment to a tuta contact
2. activate contact sync in the settings
3. close tuta app, close iOS contacts
4. open tuta app to sync contacts to iOS
5. open iOS contacts
6. look at the specific contact that should have a comment, iOS "notes" field is empty
7. wait iOS triggers a contact sync or "pull" the screen in the contacts
8. go to tuta app, previous added comment are GONE!

**Expected behavior**
Sync the tuta contact comment to iOS and back, or ignore the iOS notes fields

**Smartphone (please complete the following information):**
 - Device: [iPhone13Pro]
 - OS: [iOS 17.4.1]
 - Version [220.240321.0]

**Additional context**
Please add a option to disable 2-way sync to force a kind of "write protection" on it, like the first introduced contact sync!

Edit: Typos

## Test Notes
- [ ] Tuta Comment isn't overwritten
- [ ] All other fields are synchronized as expected, except notes

**Comment by wrdhub** [comment]
Thank you for the report, and sorry for your data loss. This is a high priority issue and we hope to quickly have a fix for this.

**Comment by MustachedMario** [comment]
FYI:
According to this reddid post [Link](https://www.reddit.com/r/tutanota/comments/1bkvq43/let_us_disable_2way_contact_sync_prevent_data_loss/) (that also is pointing to this issue here), there seems to be also issues with non matching fieldnames like `homepage` (iOS) / `._$homepage$_.` (tuta).

I can confirm that at least the `homepage` fieldname issue, others files didn't testet.
Maybe the `comments` fieldnames mismatching also and causes the issue...
