### ISSUE TITLE
Cannot import native iOS contacts that are not in the list

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6769]
The import action on my iOS device does not show me any address book. I maintain a local address book and gmail contacts like in the image below, but none of them is showing up in the import dialog.

 I also find it hard to understand what this dialog is good for. There should be an explaining text.

**To reproduce**
* Start import either from contact section or from the onboarding wizard
*  -> Empty import dialog appears.

**Expected**
Have information in the dialog what i need to do and I can select the address book i want to import my contacts from.

![Image](https://github.com/tutao/tutanota/assets/8296817/81bfbbe7-53e7-4945-bdd7-bc9c216c8f38)

![Image](https://github.com/tutao/tutanota/assets/8296817/d65798a5-bb55-457f-8068-347f61af1a9b)

## Test Notes
On iOS:
- Without Contact Sync enabled:
  - [ ] Allow contact permission
  - [ ] Try to import contacts
  - [ ] There's no dialog to pick a list or account
  - [ ] All contacts from the phone are listed
  - [ ] After clicking to import, all contacts are imported
- With Contact Sync enabled:
  - [ ] Allow contact permission
  - [ ] Try to import contacts
  - [ ] There's no dialog to pick a list or account
  - [ ] All contacts from the phone are listed except the ones belonging to the Tuta list
  - [ ] After clicking to import, all contacts are imported except the ones belonging to the Tuta list

On Android:
- [ ] The contact synchronization still working
- [ ] If there's more than one account, a dialog is shown to pick the source of contacts
- [ ] With just one account, no dialog is presented

**Comment by rezbyte** [comment]
If we revoke the contacts permission, the contacts import fails with an `PermissionError`.
