### ISSUE TITLE
Custom theme as an option in onboarding wizard

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6770]
When there is a custom theme configured for my account i want that  it should appear in the theme selector of the onboarding dialog so that my custom theme applies.

## AC
* In case there is a custom theme available the onboarding page should containing an additional entry for that theme displaying the whitelabel domain.
* There is no dialog asking to apply the detected custom theme

## Test Notes
Test on Android & iOS.
- [ ] When not using a whitelabel account, no custom themes are displayed.
- [ ] When using a whitelabel account, custom themes are displayed as domain names.
- [ ] The dialog does not break even with a large number of themes.
- [ ] Changing the colours in the whitelabel theme causes the theme in the whitelabel accounts to be updated on log in.

**Comment by murilopereirame** [comment]
On Android one of the whitelabel themes is missing and to show the first one, I had to trigger the wizard several times through the about dialog
![Screenshot_20240327_174005_Tuta-Test](https://github.com/tutao/tutanota/assets/34790144/a7291c10-01e7-40e4-a2b2-0c43e9d02023)
![Screenshot_20240327_174012_Tuta-Test](https://github.com/tutao/tutanota/assets/34790144/479e19a3-23c6-43ed-98e8-aa9bdd95a06f)
