### ISSUE TITLE
Notification permission pop up is shown together with onboarding wizard

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6771]
After installing the app and adding the account for the first time the app immediately asks me to enable push notification.

**To reproduce**
* Remove TutaMai app and install it again.
* Add an account
* Error -> See request to enable push notification

**Expected**
I expect that the request for system permission appears after clicking "enable notification" from the onboarding dialog.

## Test Notes
- [ ] When login in for the first time after install, no dialog asking for permission is presented
  - [ ] There's a page in the wizard asking for notifications permission
  - [ ] When clicking to authorize, a system prompt appears to allow notifications
- [ ] If the wizard is dismissed without giving permissions, the user will be prompted by system dialog during the next login
### Extended test:
  - Do a fresh install
  - Close the wizard without allowing notifications
  - Close the app and open again
  - Deny notifications after login
  - Close the app and allow notification on settings
  - Open the app again
  - [ ] Try to receive a notification and receive it with success

**Comment by rezbyte** [comment]
If the onboarding wizard is dismissed, the app asks for the notification permission right away.
