### ISSUE TITLE
IOS update 220.240321.0 will not connect to server

### ISSUE THREAD

**Issue by newvpn** [tutao/tutanota#6772]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rezbyte** [comment]
Hi @newvpn,
I am sorry to hear you are having issues with connecting online.

If you have a paid plan, please email customer support by using the support dialog inside the Tuta Mail client.

To use the support dialog, press 'Show Help' button (![SupportIcon](https://github.com/tutao/tutanota/assets/48037381/e54cb186-8512-4116-9ef3-7a0d3176f23e)) on the toolbar on the bottom left corner of the screen, then select 'Support'. The support dialog should appear and then you must write your problem into the text box. After some articles appear, scroll to the very bottom of the list & click the button labelled 'Contact support'.
