### ISSUE TITLE
iOS Contact Synchronisation creates duplicates each time Tuta Mail gets launched

### ISSUE THREAD

**Issue by cbaulesch** [tutao/tutanota#6776]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**
Yes

**Describe the bug**
I have created one contact in the Tuta Mail Adressbook called "Test Contact".
On the iPhone, when I launch Tuta Mail and login, the contact gets added to the iPhone Contact App.
But it does so every time Tuta Mail gets launched. Instead of maybe overwriting the old "Test Contact" it creates a duplicate.
This happens each time I launch the App. Meaning that after 10 launches I have 10 "Test Contact" contacts.

If I leave Tuta Mail running in the background and switch back to it, no duplicates get created.
It only happens when closing and reopening the app.

I have only one iOS device with contact synchronisation. No other devices.

**To Reproduce**
1. Create contact in Tuta Mail (does not matter if on phone, desktop or web)
2. Open iOS Tuta Mail App
3. Check Contacts App -> 1 Contact created
4. Close Tuta Mail
5. Launch Tuta Mail
6. Check Contacts App -> Second entry with same name got created

**Expected behavior**
The contact should only be created once.
Per description in the Tuta Mail App Settings page, the "old" contact should get overwritten.

**Screenshots**
![image1](https://github.com/tutao/tutanota/assets/153819818/bf47e508-d8a3-473f-a714-d7f61a2ced40)
![image0](https://github.com/tutao/tutanota/assets/153819818/afcf9950-9726-4299-94e6-dd06b6b57689)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro
 - OS: iOS 17.4.1
 - Tuta Mail Version: 218.240307.1

**Comment by cbaulesch** [comment]
The error is also present in App Version 220.240321.0

**Comment by cbaulesch** [comment]
I just updates to version v220.240326.0
The problem still persists.
The ticket needs to be reopened.
Did you test the change?

**Comment by charlag** [comment]
We did test the change and the only case when we observed duplciated contacts was when we manually deleted the contact group via Contacts app. We are unable to reproduce it.

If you are willing to share a part of your native log (settings -> about -> send logs) it could help us.

**Comment by cbaulesch** [comment]
Hi @charlag ,

Thank you for your reply.
I did some further testing and can give you more information.

With the current email provider I use, I synchronise all the accounts via caldav (using the native iOS Mail/Accounts option).
So in the iOS Contacts App, when I check the "Lists" I only had "caldav.myprovider.com".
There is/was no other local list.

For testing purposes I now deactivated the caldav account.
In the Contacts App, the Lists were empty - no list present.

I opened Tuta Mail, it synchronized the test account.
Meaning it now created a "iPhone Lists" with name "Tuta myaccount@tutamail.com" containing the test account.
Restarting the Tuta Mail App does not create duplicate entries.

I reactivated the caldav synchronisation.
The problem does not reappear!!
The Contacts App has two lists now - 1 caldav, 1 tuta.
Restarting Tuta Mail does not create duplicates anymore.

I guess this solves my issue but it's a strange behaviour.
For good measure I still include here the log files. They were takes shortly after creating 3 duplicates.
This was before the discovery of the above workaround.
I just edited out my tutamail address.
[1712048635940_device_tutanota.log](https://github.com/tutao/tutanota/files/14841238/1712048635940_device_tutanota.log)
[1712048635940_main_tutanota.log](https://github.com/tutao/tutanota/files/14841239/1712048635940_main_tutanota.log)
[1712048635940_worker_tutanota.log](https://github.com/tutao/tutanota/files/14841241/1712048635940_worker_tutanota.log)

**Comment by charlag** [comment]
@cbaulesch thank you for the detailed info and I am glad you have resolved the issue! We will keep an eye on it.

**Comment by denispol** [comment]
Happening to me too, Tuta app installed on brand new iPhone, ios 18.1. I have multiple CalDAV providers too, but only contacts from tuta are deduplicated each time Tuta is opened.

**Comment by charlag** [comment]
We are now warning that you should disable other contact sync integrations before enabling sync with Tuta
