### ISSUE TITLE
Allow to delete (unused or accidentally created) e-mail address(es) categorized as "alias"

### ISSUE THREAD

**Issue by x80486** [tutao/tutanota#679]
It would be nice if we have the possibility to delete e-mail addresses – so far they can be disabled only.

I'm aware there is a whole history behind this, but it also makes no sense not to allow users to delete what belong to them – regardless of the outcome. For instance, you can have a disclaimer/message stating that "if you delete this alias someone can reuse it and receive a confidential email that was meant for you", and things like that. At that point is really up to the consumer.

Moreover, a _safe default_ should be to recycle e-mails automatically after `X` amount of time when deleted (so no one can take over right away after that action occurs); also there can be an option to charge some amount in case users really want to permanently lock the e-mail and not recycle it for any reasons.

But in the end, having options is better than not having those.

**Comment by charlag** [comment]
Thanks for the detailed suggestion!
We will discuss it later when new client is ready.
