### ISSUE TITLE
If the onboarding wizard is dismissed, the app asks for the notification permission right away.

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6793]
220.240326.0 

Reproduced on iOS

1. Start with a new app install
2. See onboarding wizard
3. Dismiss the wizard
4. See that notification permission dialog is shown. Expected that no dialog is shown until the next login.

**Comment by murilopereirame** [comment]
Seems to have been fixed. I tried to reproduce w/ test version but the behavior is correct, asking for the notification permission on next login
