### ISSUE TITLE
Missing whitelabel themes in wizard

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#6804]
On Android one of the whitelabel themes is missing and to show the first one, I had to trigger the wizard several times through the about dialog.

Steps to reproduce:
On Android:
1. Add an account with whitelabel theme
2. Trigger the wizard
3. On theme step, see that there's no whitelabel theme

![Screenshot_20240327_174005_Tuta-Test](https://github.com/tutao/tutanota/assets/34790144/a7291c10-01e7-40e4-a2b2-0c43e9d02023)
![Screenshot_20240327_174012_Tuta-Test](https://github.com/tutao/tutanota/assets/34790144/479e19a3-23c6-43ed-98e8-aa9bdd95a06f)

_Originally posted by @murilopereirame in https://github.com/tutao/tutanota/issues/6770#issuecomment-2023265193_
            
## Test Notes
- [ ] Whitelabel themes are displayed during the onboard wizard

**Comment by rezbyte** [comment]
I cannot seem to reproduce this. In the second screenshot, it seems that the custom colors are disabled.

**Comment by charlag** [comment]
Also on the first screenshot there clearly is a whitelabel theme, I will try to repro it as well but if not then I'd say it's okay

**Comment by murilopereirame** [comment]
> I cannot seem to reproduce this. In the second screenshot, it seems that the custom colors are disabled.

Good catch, but the color was enabled on the web. Could be just a server delay?

> Also on the first screenshot there clearly is a whitelabel theme, I will try to repro it as well but if not then I'd say it's okay

Yes, but should have two of them, one for mup4test and one for vaf

**Comment by rezbyte** [comment]
> Good catch, but the color was enabled on the web. Could be just a server delay?

So if I am correct, you had the both the web and Android clients open at the same time. The web client with the custom colors and the Android without. Is that right?

If that is the case, I do not think it is related to the onboarding wizard. The Android client was respecting the settings it had. This might be an issue about syncing user settings.


> Yes, but should have two of them, one for mup4test and one for vaf

If the custom colors were disabled on the Android client, the `vaf` theme would not appear.

**Comment by murilopereirame** [comment]
> So if I am correct, you had the both the web and Android clients open at the same time. The web client with the custom colors and the Android without. Is that right?
> 
> If that is the case, I do not think it is related to the onboarding wizard. The Android client was respecting the settings it had. This might be an issue about syncing user settings.

No, I setup the whitelabel on the web, put a nice color on it and after that I added the account to the android device and the theme wasn't shown up.

> If the custom colors were disabled on the Android client, the `vaf` theme would not appear.

Yes, probably is related to the last question. Also the vaf theme took a while to appears into the wizard, I had to trigger the wizard 2/3 times

**Comment by charlag** [comment]
I mentioned it but maybe only in person but the wizard page grabs only what is already loaded:
https://github.com/tutao/tutanota/pull/6785/files#diff-9bb05348e2e34585caf2fecc84648f110a3d340be0bc1f5b26c7cbe2e9a167dfR14

so it's probably a timing issue, whether `PostLoginActions` will add a theme first or not. We should probably make sure we do run `maybeSetCustomTheme()` (or some alternative) when showing the wizard
