### ISSUE TITLE
Typing in the recipient field causes the app to ask for the contacts permission

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#6805]
**Bug in mobile app**

**Describe the bug**
When entering a recipient when writing a new email, the app asks for the contacts permission.

**To Reproduce**
1. Press the new mail button in the mail view.
2. Focus the 'To' field.
3. Begin typing inside the field.
4. See that a system dialog appears to ask for the contacts permission.

**Expected behavior**
The app does not ask for the contacts permission upon entering a recipient. When contact synchronization is not enabled, it should search the Tuta contacts only.

**Screenshots**
![recipient-field-contacts-permission](https://github.com/tutao/tutanota/assets/48037381/a9a063a5-30c4-4786-ac39-f93fe503c446)

**Smartphone (please complete the following information):**
 - Device: Galaxy A14
 - OS: 14
 - Version 220.240327.1

**Additional context**
Contact synchronization is disabled. Create contacts is enabled.

**Comment by charlag** [comment]
this is old behavior

**Comment by murilopereirame** [comment]
Isn't that the expected behavior? If the user has contacts from other accounts and doesn't want to import them to Tuta, they can use this to search their contacts

**Comment by rezbyte** [comment]
> Isn't that the expected behavior? If the user has contacts from other accounts and doesn't want to import them to Tuta, they can use this to search their contacts
> 
> It's also informed to users when asking for this permission on iOS:
> 
> https://github.com/tutao/tutanota/blob/8974aad9b2c9c92fdf3efa1a4c137e60439eeb79/app-ios/tutanota/en.lproj/InfoPlist.strings#L4

Personally, I did not expect it. I expect the recipient field to only search the Tuta contacts and not the device's contacts if the contacts permission is not granted yet. You could remedy this by adding a 'Search device contacts' button to the dropdown for example.

**Comment by charlag** [comment]
We will discuss what we should do in this case instead as this is a usability bug

**Comment by charlag** [comment]
Closed by #7901
