### ISSUE TITLE
Settings, email, Behavior after moving an email

### ISSUE THREAD

**Issue by winded1** [tutao/tutanota#6810]
Android app, the setting.to move to next oldest email does not persist once changed. I have attempted on 2 phones and 2 accounts. 

- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by murilopereirame** [comment]
Duplicated #6781
