### ISSUE TITLE
Typo in Sharing dialog fo calendars

### ISSUE THREAD

**Issue by 5eti8** [tutao/tutanota#6823]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
I found a typo, if I want to share a calendar for other users (language: German).

**To Reproduce**
1. Go to 'Calendar/Kalender'
2. Click on '...' next to the calendar do you want to share.
3. Click on 'Share/Freigeben'
4. See the typo 'Teilnemer' what should 'Teilnehmer'

**Expected behavior**
No typo ;)

**Screenshots**
![Bildschirmfoto vom 2024-04-04 10-24-45](https://github.com/tutao/tutanota/assets/165998186/d5d3dfb7-b049-4049-aa20-e16c22b5a51f)

**Desktop (please complete the following information):**
Client: Linux Desktop
Tutanota version: 220.240321.0
Time zone: Europe/Berlin
User agent:
 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/220.240321.0 Chrome/122.0.6261.112 Electron/29.1.2 Safari/537.36

**Additional context**
Also found in the Android app [https://github.com/tutao/tutanota/issues/6824#issue-2224832147](https://github.com/tutao/tutanota/issues/6824#issue-2224832147)

**Comment by rezbyte** [comment]
Hi @5eti8,
Thank you for reporting this issue.

I have corrected the typo in the German translation you reported now. You should see it fixed soon in a future update, so stay tuned!
