### ISSUE TITLE
Typo in Sharing dialog fo calendars

### ISSUE THREAD

**Issue by 5eti8** [tutao/tutanota#6824]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**
Android (F-Droid verion)

**Describe the bug**
I found a typo, if I want to share a calendar for other users (language: German).

**To Reproduce**
1. Go to 'Calendar/Kalender'
2. Click on '...' next to the calendar do you want to share.
3. Click on 'Share/Freigeben'
4. See the typo 'Teilnemer' what should 'Teilnehmer'

**Expected behavior**
No typo ;)

**Screenshots**
![Screenshot_20240403-231211](https://github.com/tutao/tutanota/assets/165998186/47080129-3ae5-4416-9d77-881f24a50c63)

**Desktop (please complete the following information):**
Client: Android App
Tutanota version: 220.240321.0
Time zone: Europe/Berlin
User agent:
Mozilla/5.0 (Linux; Android 14; Pixel 7a Build/AP1A.240305.019.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.120 Mobile Safari/537.36

**Additional context**
Also found in the Desktop app for Linux [https://github.com/tutao/tutanota/issues/6823#issue-2224826906](https://github.com/tutao/tutanota/issues/6823#issue-2224826906)

**Comment by rezbyte** [comment]
Hi @5eti8,
Thank you for reporting this issue.

I have corrected the typo in the German translation you reported now. You should see it fixed soon in a future update, so stay tuned!
