### ISSUE TITLE
In calendar navigation to next month via month picker only navigates to previous month

### ISSUE THREAD

**Issue by traceyfedora** [tutao/tutanota#6860]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
In the calendar view with the month selector open (not available in month view) the right pointing chevron icon (›) does not progress into the next month but rather navigates to the previous month. So in effect you can not navigate to the next month with the month selector but only to the previous month with both the left (‹) and the right pointing chevron icon (›).

**To Reproduce**
1. Go to 'https://app.tuta.com/calendar/week/'
2. Click on the current month and year in the top left, i.e. currently 'April 2024'
3. Click on the right pointing chevron icon (›)
4. See that the current month changed from April to March

**Expected behavior**
After step 3 the expected behavior would be that the current month changed to May.

**Screenshots**
![calendar](https://github.com/tutao/tutanota/assets/166944639/514d72c1-afed-41c7-9476-d3de4693745a)

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [123]

## Test notes
- [ ] Pressing the forwards arrow in the day selector pop up changes the month to the next month
- [ ] Pressing the backwards arrow in the day selector pop up changes the month to the previous month

**Comment by MiragonMx** [comment]
I just wanted to bump this, as I ran into the same issue on desktop as well! 
- Desktop (linux)
- Version [229.240517.0]

**Comment by rezbyte** [comment]
Hi @traceyfedora and @MiragonMx,
I am sorry to hear you are having issues with pop-up day selector.

We have created a fix for this and will include it in the coming update(s).

**Comment by MiragonMx** [comment]
LGTM! Thanks for the reply as well :) easy fix but would have taken me ages to navigate the project to the right place without any prior knowledge...
