### ISSUE TITLE
Keyboard Shortcuts being shown for iOS

### ISSUE THREAD

**Issue by jgoedde** [tutao/tutanota#6871]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

When opening the sidebar-menu on Tuta Mail iOS app and clicking on the question mark menu item, there is a button for keyboard shortcuts

**To Reproduce**
1. Open Tuta Mail app on iOS 
2. Open Sidebar Menu
3. Click on Question Mark item
4. See "Keyboard shortcuts"

**Expected behavior**
There should be no keyboard shortcuts visible on a mobile app.

**Screenshots**
![image](https://github.com/tutao/tutanota/assets/129423545/178beb64-5365-4996-bde9-e7143bcdd7c2)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 14 Pro]
 - OS: [e.g. iOS 17.4.1]

**Comment by charlag** [comment]
You can connect keyboard to your iOS device and use shortcuts this way. It is uncommon but valid use case.
