### ISSUE TITLE
Allow selecting contacts in import dialog

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#6876]
As an user, I want to be able to select which contacts will be imported on the final dialog inside contacts import and vCard import

### AC

* There's a checkbox on the Import Contact Dialog to select or unselect a contact from being imported
* All contacts are selected by default

## Test Notes
- [ ] On web and desktop:
  - [ ] All contacts start selected
  - [ ] Importing a single vcard file from the file picker works:
    - [ ] with all contacts selected 
    - [ ] with some contacts selected
    - [ ] with no contacts shows an error and prevents the user from proceeding 
  - [ ] Importing multiple vcard files from the file picker works:
    - [ ] with all contacts selected
    - [ ] with some contacts selected
    - [ ] with no contacts shows an error and prevents the user from proceeding 
- [ ] On mobile:
  - [ ] All contacts start selected
  - [ ] Importing the contacts from the device works:
    - [ ] with all contacts selected
    - [ ] with some contacts selected
    - [ ] with no contacts shows an error and prevents the user from proceeding

**Comment by murilopereirame** [comment]
There's no checkbox on Mobile

![Screenshot_20240527-112445](https://github.com/tutao/tutanota/assets/34790144/8776a2cc-7575-49ff-a72e-b5e6912a1d04)
