### ISSUE TITLE
failling to download with curl

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#6878]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**

downloading the app with curl keeps failing, it works fine with wget though 
I'm reporting this because curl is an important downloader, even if it's a bug in curl.

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10  118M   10 11.8M    0     0   572k      0  0:03:31  0:00:21  0:03:10  474k
curl: (92) HTTP/2 stream 1 was not closed cleanly: CANCEL (err 8)
```

**To Reproduce**

Just try to download with curl

> curl --retry 3 --output "tutanota-desktop-linux.AppImage" https://app.tuta.com/desktop/tutanota-desktop-linux.AppImage

**Expected behavior**
it should have worked

**Desktop (please complete the following information):**
 - OS: Debian 12

**Comment by charlag** [comment]
Hey, sorry I can't reproduce it so far, could you run it with `-vv`?
