### ISSUE TITLE
own address is added as recipient in Firefox

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#6904]
**Bug in web app**

**Describe the bug**
The issue is not reproduceable but multiple users are reporting this behavior and it seems to be Firefox related.

Might be similar to #296 

Edit: Still no repro but apparently this only happens when sending to external

**Comment by rezbyte** [comment]
This has been reported has happening on iOS too. #7364.

**Comment by charlag** [comment]
Have not been reported since I believe?

**Comment by kibibytium** [comment]
Issue is still happening. Still not repro.

**Comment by mpfau** [comment]
We did not yet disable autocomplete for text fields.
