### ISSUE TITLE
Calendar event does not expand the whole width

### ISSUE THREAD

**Issue by marsch1975** [tutao/tutanota#6908]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Describe the bug**
I'm not sure if I can discribe the problem in english, could do it in german much better but here we go...
Before version 417 I had the text of my long notifications seen in full length in the field of notification when the field was long enough.
With version 417 and  further on I can make the length of my notification field as long as I want, say from 9am to 6pm, the field and color is there but the text is always cut of after an hour or 75 mins and the rest of the field is blank. Why did you changed that?

**To Reproduce**
1. Go to '...' calender
2. Click on '....' new note make a long note like 8 to 12 and write a long text whic his longer than 90 mins of space, click ok abd see a long note filed with half filled up with text and the rest is blank even when there is enough spave to display the rest of the text.

**Expected behavior**
As explained above. The full field of the note which is coulored anyway shouzld include text and not only blank space.

**Screenshots**
I can do it later in case noone understands what I'm talking about...

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 latest updates.
 - Desktop Environment, if applicable (on Linux)
 - Version [e.g. 22] v227.240429.0

**Additional context**

### Test Notes
- [ ] CalendarEventBubble should display as much of an event title as possible, expanding vertically.
- [ ] Title should **not** overflow to the date and hour text.

**Comment by charlag** [comment]
Hey! thank you for your report, the screenshots would actually help a lot.

**Comment by marsch1975** [comment]
![TutaBugReport](https://github.com/tutao/tutanota/assets/116442584/4cc26b36-865c-46ec-abad-e73856c0a771)

**Comment by charlag** [comment]
Thank you for your screenshot, now I understand what you mean. We will check it

**Comment by marsch1975** [comment]
Hi,

why was this closed as completed?

Cheers
Markus

**Comment by wrdhub** [comment]
We have worked on it, found a solution, and merged it into our dev-calendar branch. This means the fix will get released in a future release (I unfortunately cannot tell you how long that will be, it depends).

**Comment by marsch1975** [comment]
OK, thanks, good to know that you have a solution..
I thought closing the case means it's already released and I have to tell you that it doesn't work on my phone...
