### ISSUE TITLE
Incorrect HTML email rendering

### ISSUE THREAD

**Issue by senchden** [tutao/tutanota#6930]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.
There is a similar issue https://github.com/tutao/tutanota/issues/6581 , but it was closed by adding a source viewer. As far as I understand it did not actually fix the issue.

**Bug in web app, desktop and Android app**

**Describe the bug**
Rendering of some HTML emails is broken - no readable text is visible.
I am enclosing a text file with the pseudonymized message source.

**To Reproduce**
1. Attempt to render the html code in the enclosed file in any app - web, android or desktop.
[tuta-incorrect-display.txt](https://github.com/tutao/tutanota/files/15287963/tuta-incorrect-display.txt)

**Expected behavior**
The message is rendered correctly.

**Screenshots**
Example of incorrectly rendered email:
![image](https://github.com/tutao/tutanota/assets/31250983/ab614ccf-36a2-4fe2-8604-19cd966400cb)
Example of expected rendering:
![image](https://github.com/tutao/tutanota/assets/31250983/67cb8c97-45c9-4f81-b662-b57232b59ec2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser firefox 125

Desktop app version v227.240502.0

**Comment by wrdhub** [comment]
Thanks for your report. Like I mentioned in the other one we decided to add a source viewer to help us figure out what is going on here, we should have properly updated the other issue to reflect that. We are still looking into this!

**Comment by wrdhub** [comment]
## Test Notes
- [ ] Check various plain text and html emails, make sure they display
