### ISSUE TITLE
Linux desktop version will not start or send logs after latest update.

### ISSUE THREAD

**Issue by ianp5uk** [tutao/tutanota#6935]
Linux desktop version will not start or send logs after latest update. App launches to error, blank screen just inviting error report which it can't send. Today is Tuesday, 14th May.
Ubuntu 22.04.4

**Comment by charlag** [comment]
Hi, thank you for the report. Do you see any output in the terminal?

**Comment by bedhub** [comment]
Stack trace of the initial error
```
Feedback v229.240513.0 - CryptoError - PAID - linux
Client: linux
Type: PAID
Tutanota version: 229.240513.0
Timestamp (UTC): Tue, 14 May 2024 08:51:16 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/229.240513.0 Chrome/122.0.6261.156 Electron/29.3.2 Safari/537.36
CryptoError
Error message: mac expected but not present
Stacktrace:
CryptoError: mac expected but not present
at Gs (asset://app/worker.js:1:55216)
at Us (asset://app/worker.js:1:55039)
at Ba (asset://app/worker.js:7:46224)
at Lo.unlockUserGroupKey (asset://app/worker.js:18:51556)
at Ya.initSession (asset://app/worker.js:18:23348)
at async Ya.finishResumeSession (asset://app/worker.js:18:22625)
at async Ya.asyncResumeSession (asset://app/worker.js:18:21818)
```

**Comment by bedhub** [comment]
Stack trace when trying to send the error
```
Feedback v229.240513.0 - Error - PAID - linux
Client: linux
Type: PAID
Tutanota version: 229.240513.0
Timestamp (UTC): Tue, 14 May 2024 08:52:26 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/229.240513.0 Chrome/122.0.6261.156 Electron/29.3.2 Safari/537.36
Error
Error message: AssertNotNull failed : null
Stacktrace:
Error: AssertNotNull failed : null
at q (asset://app/common-min--qHbzLJQ.js:1:13440)
at Lo.getLoggedInUser (asset://app/worker.js:18:52947)
at MailFacade.createDraft (asset://app/worker-lazy-oMVeY3qv.js:1:31714)
at asset://app/common-zoyYDbsu.js:1:4441
```

**Comment by synthgab** [comment]
Hi, it's the exact same behavior and error stack trace on Android. Maybe worth also labeling this issue 'android' ?
Thank you !

**Comment by bedhub** [comment]
Ah, all clients with offline support are affected Android, iOS and Desktop client.

To reproduce.
1. Precondition: Have a paid account with KDF type Bcrypt and and offline database with client version 227.x
2. Login in with other client version 229.x to do the argon2 migration (while the offline database client is closed).
3. Login with offline client and see that the error appears.

**Comment by synthgab** [comment]
Oh, I see, thank you for finding this.

And Indeed, I confirm that delete application data on Android solved the issue (after logging in again), the drawback being the need to re-initiate a search with a date 10+ years ago to populate the database ...
