### ISSUE TITLE
unable to send email (while I already did before)

### ISSUE THREAD

**Issue by Portalus** [tutao/tutanota#6944]
I'm unable to send email to this domain: **@usk.poznan.pl**
Previously I had already correspondency with them and suddenly I didn't get message, which I was waiting for and I can't send them anything as well; I'm receiving deamon info:

![obraz](https://github.com/tutao/tutanota/assets/90559619/7d9aa4b9-96d1-4363-8f24-aae61ca1e801)

**I was able to send email from gmail, so domain and receiver is OK.**
I think this might be a piece of something greater.

**Comment by wrdhub** [comment]
It looks like your Tuta mail address was rejected by the receiver as they viewed it as spam. This unfortunately happens some times, as we are a smaller provider and not as known. We of course, work to get ourselves off spam lists, but it happens. It would be good for you to reach out and let them know to unblock.
