### ISSUE TITLE
tuta.com banned my ISP; no way to report this

### ISSUE THREAD

**Issue by ballo** [tutao/tutanota#6945]
- [*] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [*] I've searched and did not find a similar issue.

**Describe the bug**
There is no way to resolve issues like tuta.com banning my ISP

**To Reproduce**
1. Go to tuta.com or tutanota.com
2. No connect

**Expected behavior**
being able to use webmail or the app

**Additional context**
I was without email for two days until I could connect to a wifi hotspot. I cannot depend on this service and am looking for alternatives.

**Comment by wrdhub** [comment]
I'm sorry we did not respond earlier. If you have an issue with the connection, please reach out to our support at hello@tutao.de They can get information from you to see if your IP has been blocked.
Closing because the way to solve this is to reach out to support.
