### ISSUE TITLE
Task: Mutations via EntityClient in Rust

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#6958]
<ul>
    <li>All <code>EntityClient</code> s support additional methods:
        <ul>
            <li>update</li>
            <li>erase</li>
        </ul>
    </li>
    <li>Encryption and serialization preserve fields marked as <code>final</code> in the
        model
    </li>
</ul>
<p><strong>Notes</strong></p>
<ul>
    <li>We need to implement encryption</li>
    <li>We need serialization implementation
    </li>
</ul>

**Comment by wrdhub** [comment]
Postponed
