### ISSUE TITLE
 Login fails on Android 6.0.1

### ISSUE THREAD

**Issue by pi3ab4** [tutao/tutanota#6961]
@jomapp Thanks for looking into #6939.

But as I replied in #6939, the bug is still not fixed in the latest version 229.240514.1.

_Originally posted by @pi3ab4 in https://github.com/tutao/tutanota/issues/6939#issuecomment-2113310606_
            
Same behavior as described above (Android 6.0.1).

Please set status to "open".

**Comment by mtbu** [comment]
I think I have this same issue, on v227.240502.0 from F-Droid, on Android 11 (waydroid running on ubports).

I haven't tested v229 as the F-Droid build is out of date (v227.240502.0 is the latest) - I don't know if Tuta or F-Droid is responsible for keeping the builds up to date?

**Comment by kib42** [comment]
Unfortunately we are dropping support for both Android 6 and 7.

@jomapp Let's Encrypt recently stopped issued certificates that are cross-signed and Android 6 and 7 cannot verify the chain of trust anymore. See https://letsencrypt.org/2023/07/10/cross-sign-expiration.html

**Comment by mtbu** [comment]
Upgrading to v229.240514.1 from F-Droid this morning seems to have fixed things for me.

**Comment by licaon-kter** [comment]
@pi3ab4 for Android 6 or older do this: https://www.stoutner.com/lets-encrypt-isrg-root-x1-and-privacy-browser/
