### ISSUE TITLE
Sharing a video on iOS triggers vCard import pop-up

### ISSUE THREAD

**Issue by kib42** [tutao/tutanota#6966]
iOS only. tested with videos made with iPhon/iPad only. Other file types might be affected.

**steps**

1. have a video less than 25MB in size
2. open share menu and choose Tuta
3. see `vcardInSharingFiles_msg`

## Test Notes
- [ ] Sharing videos with Tuta mail works as expected
- [ ] Sharing images with Tuta Mail works as expected
- [ ] Sharing vCard files will trigger the dialog asking to import or attach them

**Comment by wrdhub** [comment]
This sometimes happens with images sometimes.
