### ISSUE TITLE
search function keyboard does not disappear

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#6971]
**Bug in mobile app**

**Describe the bug**
Tapping on Return after submitting search entry does not hide keyboard

**To Reproduce**
1. Go to Search
2. Enter your query
3. Tap Return

**Expected behavior**
The keyboard should be hidden to see the full list of results

**Additional context**
A workaround is to tap on an empty space or the filter to make the keyboard disappear

**Comment by wrdhub** [comment]
Works well, but some keyboards have a "go" button and it does not work for those. Created a dev-bug issue: #7898
