### ISSUE TITLE
Old tuta logo is shown on braintree payment verification page

### ISSUE THREAD

**Issue by nif-tutao** [tutao/tutanota#6982]
### Actual:
If a user changes their payment method to a credit card or updates the existing card data, 
the old **Tutanota** logo is still shown.

### Expected:
New **Tuta** logo is displayed during the braintree payment verification process.

## Test notes:
* Go to settings -> payment
* Update payment method and select method credit card
* Use any test credit card number
* See braintree payment verification page
- [ ] Verify that new **Tuta** logo is displayed on verification page on all platforms (web, desktop, app, iOS)

**Comment by wrdhub** [comment]
Fixes included in pr #6990
