### ISSUE TITLE
No navigation buttons in calendar view

### ISSUE THREAD

**Issue by murilopereirame** [tutao/tutanota#7005]
When using the Single Column Layout on desktop/web there's no navigation icons to change the displayed month
![image](https://github.com/tutao/tutanota/assets/34790144/05317686-8450-40e5-a99b-56a4019e8299)

### Test Notes
- [ ] Previous and Next buttons does not appear in mobile app.
- [ ] Buttons only appear in single column and two columns layouts.

### Working example:
![Group 1](https://github.com/tutao/tutanota/assets/44059355/0d9db815-6f93-421e-ae4b-4b094e3707a2)

**Comment by MiragonMx** [comment]
additional info: this happens exactly at the 900px width mark
