### ISSUE TITLE
No checkbox on Import Contacts in Single Column layout

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7007]
There's no checkbox when the layout is Single Column

![Screenshot_20240527-112445](https://github.com/tutao/tutanota/assets/34790144/8776a2cc-7575-49ff-a72e-b5e6912a1d04)

_Originally posted by @murilopereirame in https://github.com/tutao/tutanota/issues/6876#issuecomment-2133066496_
            

## Test notes
Test in single column view.
- [ ] Tapping and holding a contact row in the contacts tabs starts a multi-select with the checkbox visible
- [ ] Opening the import contacts dialog starts with all rows' checkboxes visible

**Comment by murilopereirame** [comment]
On android it's perfect!
On iOS it's working but the rows are a bit weird - iPhone 12 Mini
![IMG_0002](https://github.com/tutao/tutanota/assets/34790144/900f065e-5b4e-4284-a1a0-7f78ee86be86)

**Comment by murilopereirame** [comment]
On Android it's perfect!
On iOS the contact rows are a bit weird - iPhone 12 Mini
![IMG_0003](https://github.com/tutao/tutanota/assets/34790144/ba95c7f8-b212-43f0-95c4-30f3695a9c21)
