### ISSUE TITLE
There shows always a ( 1 ) as notification on the inbox label.

### ISSUE THREAD

**Issue by VolXAyd** [tutao/tutanota#7008]
- [ X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ X ] I've searched and did not find a similar issue.

**Describe the bug**
There shows always a ( 1 ) as notification on the inbox label. If i get a new mail, it counts up ( 2 ). The counting for unread Mails starts at 1 and not at 0. For 0 unread Mails it shows me 1.

**To Reproduce**
1. Start the Tuta Desktop App (this problem you can find it in the mobile app too)
2. Stay at the normal View
3. You will see a " ( 1 ) " for thats you have a new Mail

**Expected behavior**
The zero for, that i haven't any unread Mails.

**Screenshots**
<img width="252" alt="Bildschirmfoto 2024-05-27 um 12 48 56" src="https://github.com/tutao/tutanota/assets/100293065/c48a4695-b904-4dc4-977c-a658875eee5a">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma Version 14.5 (23F79), iOS 17.5.1 (21F90)
 - Desktop Environment, if applicable (on Linux)
 - Version: v229.240517.0 (Desktop App M1), v229.240521.0 (iOS iPhone 11 Pro Max App)

**Comment by charlag** [comment]
Hi
If you scroll to the end of mail list and wait a few seconds it should fix the counter. Does this happen for you?

**Comment by VolXAyd** [comment]
Yes, the ( 1  ) is gone. Thanks.

**Comment by VolXAyd** [comment]
Yes, the ( 1 ) is gone. Thanks.
