### ISSUE TITLE
Login frontpage too slow

### ISSUE THREAD

**Issue by gthzee** [tutao/tutanota#7012]
Months ago, I can login even with 48kbps connection.. now you will able to login with very high stable connection.. even with over 3mbps connection, login frontpage cant even loaded.. wtf.

**Comment by charlag** [comment]
hey
could you elaborate on what you are seeing?

**Comment by gthzee** [comment]
I can access tuta.com without a problem.. only mail have that problem.

**Comment by gthzee** [comment]
![Screenshot_2](https://github.com/tutao/tutanota/assets/168825306/621e0fc3-84db-4b0c-b49d-1d46144b8583)

**Comment by gthzee** [comment]
Feedback v229.240517.0 - TypeError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 229.240517.0
 Timestamp (UTC): Fri, 31 May 2024 22:36:46 GMT
 User agent:
 Firefox/113.0
TypeError
 Error message: ServiceWorker script at https://app.tuta.com/sw.js for scope https://app.tuta.com/ encountered an error during installation.

**Comment by Oxidela** [comment]
Specifically, this relates to retrieving the script "gui-base-TfJ0d3Pr.js".

Fresh installs of Firefox [latest] (and Firefox forks) returns the error "NS_ERROR_NET_PARTIAL_TRANSFER" when attempting to load the script from the login page:

https://mail.tutanota.com/gui-base-TfJ0d3Pr.js
https://app.tuta.com/gui-base-TfJ0d3Pr.js

Browser tools show the script finally returns a status of "Blocked" after 22,285 ms of loading.

The login pages loads just fine in other browsers and even directly typed into the url bar.
![script_blocked](https://github.com/tutao/tutanota/assets/93446756/f4965785-8a13-4d3e-a9b6-d1a323b7ace5)

**Comment by charlag** [comment]
I am not sure what the error is with service worker installation but it shouldn't affect the normal app loading.

Does it happen e.g. in private browser window too? It seems really odd and not something that the client could do (unless SW cache is *really* broken but I don't know how)

**Comment by gthzee** [comment]
I tested, like @Oxidela said.. not really clean install.. I just use another profile that I never visit tuta.com before.. and voila.. no problem.. 
it seems @charlag also right about cache being broken.. so I "forget" the page.. and revisit a link that I copied before... and yup also no problem..

many thanks.. you can close this issue now..

**Comment by charlag** [comment]
Found an issue: https://github.com/tutao/tutanota/issues/7060

**Comment by Oxidela** [comment]
Leaving an update for anyone that runs into the "NS_ERROR_NET_PARTIAL_TRANSFER" error. If you use cloudflared (tunnel), try updating it to the latest release.
