### ISSUE TITLE
Calendar Keyboard Navigation Bugs

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#7013]
Web/Desktop:
- 3 Columns - Day/Week and Month views the tabbing starts on the past day/week/month
- 1 Column layout - Month view start on the past month
- To use the arrows left/right, I need to do an extra tab, probably is focusing on past day/week/month first

_Originally posted by @murilopereirame in https://github.com/tutao/tutanota/issues/6870#issuecomment-2133680226_

## Test notes
- [ ] The focus does not get stuck on invisible views.
- [ ] Pressing any of the calendar view's shortcuts (`<-`, `->` etc.) work while focused on an event.

**Comment by murilopereirame** [comment]
Tabbing still starting on the previous day/week/month, but it doesn't focus the events, so, 1 more tab moves the focus to current day/week/month.

![image](https://github.com/tutao/tutanota/assets/34790144/f029ae2f-92aa-4f86-8513-9e9112b1b622)
