### ISSUE TITLE
Unable to receive mail

### ISSUE THREAD

**Issue by Barrocas** [tutao/tutanota#702]
Hi,
I'm using release 3.37.2 apk for Android.

I sent a normal text mail to a friend, with attachement, he received, and replied, also with a small zip attachement.
I didnt receive it.
He re-sent it again, same result.
Not receiving mail. 
Also verified in the browser tutanota website mail login access, no mail received. 
Any ideas?

**Comment by charlag** [comment]
Please provide details to hello@tutao.de, could be that it's some misconfiguration or spam block of their provider.

**Comment by Barrocas** [comment]
Will do, Thank you.
