### ISSUE TITLE
Task: Better debugging with SDK

### ISSUE THREAD

**Issue by wec43** [tutao/tutanota#7020]
When using the SDK, I would like to have an better way to debug running Rust codes.

**AC**
- It is possible to attach a debugger for the native code to a running Android/iOS application.
- It is possible to trigger breakpoints and see stack trace from the debugger

**Notes**
 - Debugging should work, we need to check why not. We should check how other projects deal with this problem.

**Comment by rezbyte** [comment]
The logging part was split into #7151.

**Comment by charlag** [comment]
Postponed
