### ISSUE TITLE
Icons in mail actions bar do not have tooltip on hover

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7031]
When I hover over an icon in the mail action tool bar it used to have a pop up with what that action is ("Delete" on the trash can, "Move" on the folder, etc...). Nothing is there anymore, making it unclear what they do.

## Test notes
- [ ] Icon buttons show text when hovered over
- [ ] Screen readers only read the name of a folder once when using the move folder dropdown

**Comment by andrehgdias** [comment]
#7125
