### ISSUE TITLE
Can't log into or remove a saved account on macOS. (Error message: can't remove app pass wrapper without salt)

### ISSUE THREAD

**Issue by ghost** [tutao/tutanota#7037]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**
Can't log into or remove a saved account on macOS. 

**To Reproduce**
1. Go to 'Tuta Mail desktop app'
2. Click on 'my email (saved credentials) in order to log in and receive no prompt to enter password'
3. See error 'An unexpected error occurred. Please try again later.'
4. Click on 'show more'

------------------------------------------------------------------

Feedback v229.240517.0 - Error - UNKNOWN - darwin

 Client: darwin
 Type: UNKNOWN
 Tutanota version: 229.240517.0
 Timestamp (UTC): Wed, 29 May 2024 17:52:41 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/229.240517.0 Chrome/122.0.6261.156 Electron/29.3.2 Safari/537.36
Error
 Error message: can't remove app pass wrapper without salt
Stacktrace: 
Error: can't remove app pass wrapper without salt
    at WO.removeAppPassWrapper (/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:11:283980)
    at async WO.decryptUsingKeychain (/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:11:283514)
    at async ipc (/Applications/Tuta Mail.app/Contents/Resources/app.asar/desktop/DesktopMain.js:11:293940)

-------------------------------------------------------------------------------------------------------------

**Expected behavior**
To be able to enter password and log in.

**Screenshots**
<img width="339" alt="Screenshot 2024-05-29 at 10 58 50" src="https://github.com/tutao/tutanota/assets/171180033/23bdd9a0-8064-47ba-a091-b719d1b0326a">

**Desktop (please complete the following information):**
 - macOS
 - Version 229.240517.0 (Desktop)

**Additional context**
I was trying to figure out why my screensaver wouldn't start. I went to Activity Monitor and filtered processes to show "Preventing Sleep". I killed 2 processes that had "Yes" under "Preventing Sleep". These were "powerd" and "WindowServer". After I killed "WindowServer" my Mac restarted. Everything on computer works fine except I can't login to Tuta. I completely uninstalled Tuta. And reinstalled latest version. And restarted Mac again. I am still getting the same error. I even went into the mobile app and X'd out my Mac session. I even try to just remove the account and get the same error. So I can't remove account and can't login. It doesn't prompt to enter password but just keeps giving this error.

Found similar bug on reddit. 

https://www.reddit.com/r/tutanota/comments/1agb9co/error_could_not_log_in_via_app/

And followed the instructions...

"Thanks for reporting. It looks like there is an issue with the locally cached data for Tuta. Please delete the directory: ~/.config/tutanota-desktop and then launch the desktop client and try to log in again.

You can also run this command to delete this directory:

rm -r ~/.config/tutanota-desktop"

However there is no tutanota file in that directory.

**Comment by charlag** [comment]
Hi, sorry that we didn't reply earlier!
Is this still something that happens to you?
