### ISSUE TITLE
iOS: No sender and recipient preview when screen is locked

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#7049]
When my device locked and i receive a tuta notification there is no sender/recipient information even if i have the notifications setting set to "Only sender". It seems that this new functionality only works if my device is unlocked.

**To Reproduce**
1. Enable Sender notification in Settings - Notifications - Only sender
2. Lock the device
3. Receive new email notification
4. Error: Notification only contains "New email received.

**Expected behavior**
That sender and recipient information is available in the notification.

**Smartphone (please complete the following information):**
 - Version: 230.240529.0

## Test notes
 - [ ] Upgrade from 229.240521.0 with automatic app lock, see that you can log in and that extended notifications when the screen is locked work after changing the preference
 - [ ] Upgrade from 229.240521.0 with system password app lock, see that you can log in and that extended notifications when the screen is locked work after changing the preference
 - [ ] Upgrade from 230.240529.0 with automatic app lock, see that you can log in and that extended notifications when the screen is locked
 - [ ] Upgrade from 230.240529.0 with system password app lock, see that you can log in and that extended notifications when the screen is locked

**Comment by charlag** [comment]
We are using [kSecAttrAccessibleWhenUnlockedThisDeviceOnly](https://developer.apple.com/documentation/security/ksecattraccessiblewhenunlockedthisdeviceonly)  and we should be using [kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly](kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly).

We need to add another mirgation

**Comment by rezbyte** [comment]
I am not sure if this is an issue but the system keychain becomes invalidated after upgrading from 230.240529.0 to latest. Also when the screen is locked and the app is open, a notification is not sent.  Everything else seems to work fine.

**Comment by charlag** [comment]
@rezbyte I assume the keychain issue is because the key is not being deleted on app uninstall but it's hard to prove. I think @bedhub upgraded from 230.240531.0 without an issue though.

We should check about the locked screen, it is probably not new though
