### ISSUE TITLE
Implement KeyLoaderFacade

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7051]
In order to implement key resolution fully SDK needs to be able to access group keys and private keys of the user.

**AC**
 - SDK has an internal ability to get symmetric group keys
 - SDK has an internal ability to get user's keypairs

**Tasks**
- [ ] Implement `KeyLoaderFacade` with aforementioned functions

**Comment by wec43** [comment]
Ducpliate of #7071.
