### ISSUE TITLE
Can tab into another `ViewColumn` while in single-column layout

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#7054]
**Describe the bug**
While in the single-column layout (mobile etc.), the off-screen `ViewColumn` can still be tabbed into.

**To Reproduce**
1. Go to the mail list while in single-column layout
2. Tab until the back button of the conversation view is focused

**Expected behavior**
Only the elements that are visible can be tabbed to.

**Additional context**
This problem was deliberately reintroduced by #7053 in order to fix to #7050. We (ivk & jat) considered the tabbing issue to be a lesser problem comparatively. 

**Estimated: 2h**
**Time spent: 0.5h**

## Test notes
- [ ] On desktop
  - [ ] Switch to single-column layout
  - [ ] Open a mail conversation and tab until the end
  - [ ] Only the elements that are visible can be tabbed to
- [ ] Works with mobile screen readers

**Comment by charlag** [comment]
Could be addressed together with [#7998](https://github.com/tutao/tutanota/issues/7998)
