### ISSUE TITLE
App Crashes on startup

### ISSUE THREAD

**Issue by SigmaEnterprise** [tutao/tutanota#7096]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
With the new update to IoS the app has been crashing on startup one week now. Locking me out of account

**To Reproduce**
Open app

**Expected behavior**
Emails too load

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: IPhone XS Max
 - OS: IoS
 - Version 17.5.1

**Additional context**

**Comment by wrdhub** [comment]
@SigmaEnterprise I'm sorry we did not respond when this was first reported. Is this still happening?

**Comment by SigmaEnterprise** [comment]
No upgrade of IoS, fixed it. App is working excellent

**Comment by SigmaEnterprise** [comment]
thanks
