### ISSUE TITLE
native android dialogue for time selection does not have set/ok button

### ISSUE THREAD

**Issue by kib42** [tutao/tutanota#7099]
This happens on smaller screens at least on Android versions 13, 14. See screenshot:

![image](https://github.com/tutao/tutanota/assets/104761667/a4e3e7f9-cf26-4f71-914c-6645040486d3)

**Comment by murilopereirame** [comment]
> This happens on smaller screens at least on Android versions 13, 14. See screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/104761667/340247164-a4e3e7f9-cf26-4f71-914c-6645040486d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4Njc2ODAsIm5iZiI6MTcxODg2NzM4MCwicGF0aCI6Ii8xMDQ3NjE2NjcvMzQwMjQ3MTY0LWE0ZTNlN2Y5LWNmMjYtNGY3MS05MTRjLTY2NDUwNDA0ODZkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwNzA5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWQxYjc5MTU0NWE0YjgzMjQ4YjE2ZTc2ZTQ1MTlkMmY4ZmEwNDVhNDZlZmJlMzIyNWE1OTAyZWQ1ZTE3MmVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qmciR4Y9zxQSUdlAF6rARqEZhhJq0gEZ1CCnMAH32HI)

~I couldn't reproduce, tried with physical Pixel 4a (5.8" 1080x2340 xhdpi) and w/ Android Studio emulator (4.65" 720x1080 xhdpi)~. 

Webview issue.

**More details:**

I realized that the language is also mixed (German + English) this seems to be a bug with webview and there's already a Chromium bug being tracked [here](https://issues.chromium.org/issues/40945090). The missing button is probably related with the language problem, as the old behavior was correct language + column layout.

**Webview 113**
![Screenshot_20240620_101954](https://github.com/tutao/tutanota/assets/34790144/c5ea9c40-ac79-48cc-bd9c-3aae5bedf5b9)

**Webview Canary (128)**
![Screenshot_20240620_101752](https://github.com/tutao/tutanota/assets/34790144/dd4baa09-bb3b-45bb-85ec-6f8669f4d0fe)
