### ISSUE TITLE
Chrome: Password label overlaps password input in login view

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#71]
If the password has been stored with Firefox the password input from the browser is not recognized by the password input field. The label does not move to the top.

**Comment by bedhub** [comment]
cannot reproduce this error with latest Firefox version 56

**Comment by mpfau** [comment]
Could reproduce this in chrome.

**Comment by mpfau** [comment]
There is still a bug in latest chrome versions: The autofill is expected to update the the value of the password field after user interaction and before the click event is dispatched. However, this does currently not work in new windows or after refreshing the page with the refresh button. If you press F5, everything works as expected.

See https://bugs.chromium.org/p/chromium/issues/detail?id=775417

**Comment by mpfau** [comment]
Further analyzed the chrome behavior.
The chrome autofill does not work on password fields if the value has been set before. The textfield should be adapted to this.
