### ISSUE TITLE
mail.w14.tutanota.de is saying HELO but doesn't have a forward DNS record

### ISSUE THREAD

**Issue by alanesmizi** [tutao/tutanota#7114]
- Existing functionality does fully work
- I've searched and did not find a similar issue.

**Describe the bug**
The mail server saying HELO with a hostname that doesn't have a forward DNS record Jun 20 07:51:34 smtp2 postfix/smtpd[601797]: warning: hostname mail.w14.tutanota.de does not resolve to address 185.205.69.214: No address associated with hostname Jun 20 07:51:34 smtp2 postfix/smtpd[601797]: connect from unknown[185.205.69.214] Jun 20 07:51:35 smtp2 postfix/smtpd[601797]: NOQUEUE: reject: RCPT from unknown[185.205.69.214]: 450 4.7.1 <mail.w14.tutanota.de>: Helo command rejected: Host not found; from=<MY TUTANOTA EMAIL ADDRESS> to=<AN EMAIL ADDRESS GOES HERE> proto=ESMTP helo=<mail.w14.tutanota.de>

**Expected behavior**
hostname should have a forward DNS record

**Comment by ganthern** [comment]
should be fixed now, thank you.
