### ISSUE TITLE
[Linux] AppImage from the Tuta website stays offline until VPN is connected. Same PC/Connection works on windows 

### ISSUE THREAD

**Issue by nabeelmoeen** [tutao/tutanota#7124]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
My tuta desktop app on Fedora 40 is unable to connect, with an error that the application is offline/servers unreachable. the only way for me to connect is to switch the VPN connection on. once the vpn is on the app connects to the servers and works fine.
I have a dual boot machine, and on Windows the tuta desktop app works fine on the same connection.

**Expected behavior**
I expect the app to connect to the mail servers on both the vpn and non-vpn connections.

**Desktop (please complete the following information):**
 - OS: [Ultramarine Fedora 40]
 - Desktop Environment, if applicable (on Linux) 
 KDE Plasma 6.0.5

**Comment by charlag** [comment]
Hi, please contact the support about this issue, we need to ask for additional info

**Comment by nabeelmoeen** [comment]
Can you share how to contact support?
