### ISSUE TITLE
Improve CSP

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#713]
- `frame-ancestors 'none'`
- CSP should start with `default-src 'none'; script-src 'self';`
- Add `base-uri 'none'`

**Comment by asteintutao** [comment]
CSP14312: Die Direktive default-src 'none' in Content-Security-Policy wurde durch eine Ressource verletzt: https://test.tutanota.com/sw.js. Die Ressource wird blockiert.
default-src 'none' prevents initialising of worker and service worker.


 CSP14312: Die Direktive default-src 'none' in Content-Security-Policy wurde durch eine Ressource verletzt: https://test.tutanota.com/WorkerBootstrap.js. Die Ressource wird blockiert.

 SCRIPT5022: SCRIPT5022: CryptoError: could not setup worker> undefined
main.js (1,1288054)

 error CryptoError. could not setup worker> undefined
   at CryptoError (https://test.tutanota.com/common.js:1:193370)
   at _worker.onerror (https://test.tutanota.com/main.js:1:1288054)

 Unknown error CryptoError: could not setup worker> undefined

**Comment by asteintutao** [comment]
happens probably for older firefoxes aswell
at least same error happend in waterfox see below   


![grafik](https://user-images.githubusercontent.com/31402512/47509369-429b1380-d876-11e8-8cc0-5157daa0c80e.png)

**Comment by mpfau** [comment]
Edge bug report: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17415478/

=> added a worker-src directive on the server side

**Comment by mpfau** [comment]
Switched again to child-src as worker-src is not yet supported by safari
