### ISSUE TITLE
Calendar Notifications not working on iOS

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7165]
Repro:
- Create a calendar event, add a "Reminder before event"

Expect:
- Notification about the event at that time.

What happens:
- No notification

Additional info:
started with version 230.240621.0

**Comment by rih-tutao** [comment]
Can reproduce on ios, even on earlier versions (230.240521.0 was the earliest tested version).
Several "Reminder before event" options have been tried.

Notifications are working as expected on android and the desktop client.

**Comment by antonlydell** [comment]
I have the same issue. I am running v232.240621.0. The notifications for email work correctly.

**Comment by antonlydell** [comment]
I tested the calendar notifications on the Tuta app on iOS v235.240709.0 and it still does not work.
