### ISSUE TITLE
Cannot print process order agreement in Firefox and Edge

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#720]
If you try to print the order process agreement in Firefox and Edge it only prints the first page and not the complete agreement. Chrome can print the hole page. I haven't checked other browsers like Safari or Opera.

**Comment by bedhub** [comment]
In the current version it is also not possible to print the agreement in Chrome

**Comment by olivermg** [comment]
Hi,

> In the current version it is also not possible to print the agreement in Chrome

I suppose this statement has been made due to my bug report via email to tutanota yesterday.

Please note that I've observed this bug in **Chromium**, not Chrome. Maybe this doesn't make any difference, but I didn't want to leave this unmentioned.

**Comment by olivermg** [comment]
...I've just tested it on Chrome (a rather old build 71.0.3578.98 though, as I'm usually not using Chrome anymore) under Linux and it indeed shows the erroneous behaviour as well.

**Comment by mpfau** [comment]
CTRL+P does not work. You have to click on the "Print" button.

**Comment by olivermg** [comment]
Thanks for the hint, but I've not used CTRL+P. I was experiencing the issue when using the "Print" button in the upper right hand corner when showing the Order Processing Agreement - to my understanding just like you're suggesting.

Please note that the issue still exists for me (I've just checked it). However, I'm not sure if you've deployed any changes/fixes yet to your production system so this might be expected.

**Comment by mpfau** [comment]
@olivermg The issue has been fixed but the release has not been published yet...

**Comment by mpfau** [comment]
attachment buttons are not visible on mails anymore
