### ISSUE TITLE
downloading an invoice crashes mobile app

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#7235]
**Bug in mobile app**

**Describe the bug**
When downloading an invoice, the app shuts down

**To Reproduce**
1. Go to Settings > Payment > Invoices & payments
2. Try to download an invoice
3. App crashes

## Test notes

- [ ] On Android, download an invoice and verify that the application does not crash. Check the device's files, and you should find the invoice present there.

**Comment by rezbyte** [comment]
Hi,
Thanks for the report.

This might be related to #7160 or maybe "Expected a dict object"?

**Comment by rezbyte** [comment]
This still happens on iOS.
