### ISSUE TITLE
Application crashes when being maximized or fullscreened (Wayland)

### ISSUE THREAD

**Issue by pm4rcin** [tutao/tutanota#7248]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
When application is maximized it crashes.

**To Reproduce**
1. Open App
2. Maximize app
3. Crash

**Expected behavior**
It should not crash

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora Sway Atomic 40
 - Desktop Environment, if applicable (on Linux) Hyprland 0.39.1
 - Version [e.g. 22] v235.240718.0

**Additional context**
It's because electron < 31.1.0 inherited chromium bug. The same problem was present in https://github.com/FreeTubeApp/FreeTube/issues/5304 but it was since fixed.

**Comment by charlag** [comment]
thank you!

does 31.1.0 fix this?

**Comment by pm4rcin** [comment]
> thank you!
> 
> does 31.1.0 fix this?

From FreeTube perspective that had the exact same problem I think so. But it was most probably chromium bug that was fixed rather than electron specific.

**Comment by pm4rcin** [comment]
With today's update it was fixed.
