### ISSUE TITLE
linux appimage fails to start

### ISSUE THREAD

**Issue by nutpantz** [tutao/tutanota#7249]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
start the appimage and the key is requested , app opens and nothing appears in the window
**To Reproduce**
download appimage
start app image
**Expected behavior**
app should load and show something
**Screenshots**

**Desktop (please complete the following information):**
 Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**Additional context**
no idea what version the appimage is, downloaded it today.
it should really have a version number and a way to download the last version

**Comment by nutpantz** [comment]
i dont get the login screen i do see anything but an empty window 

SSE] established SSE connection with code 200
[SSE] state: connected
[SSE] heartbeat
[SSE] state: connected
[SSEFacade] heartbeatTimeout 240
[SSE] heartbeat
[SSE] state: connected
[SSEFacade] notification
[SSE] heartbeat
[SSE] state: connected
[SSEFacade] last missed notification check: { lastMissedNotificationCheckTime: 1721617524318 }
[SSEFacade] downloading missed notification
[SSE] state: connected
[SSEFacade] downloaded missed notification

(tutanota-desktop:14328): GLib-GIO-CRITICAL **: 18:47:37.904: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

hope that helps

**Comment by charlag** [comment]
thank you for the logs. if this assertion is the only thing I think that's the source of the problems;

Quick search brings up results about `fcitx` and uninstalling it allegedly helps?

**Comment by nutpantz** [comment]
That appears to be a required file for the lubuntu desktop. So uninstalling that would be a no go.

**Comment by nutpantz** [comment]
the monkey has been patched pid: 3115
(node:3115) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)
retrying to create credentials db
deleting credentials db
version:   235.240718.0
(node:3115) UnhandledPromiseRejectionWarning: Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /tmp/.mount_tutano2FVFsI/resources/app.asar.unpacked/desktop/better-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at new Fe (/tmp/.mount_tutano2FVFsI/resources/app.asar/desktop/better-sqlite3-Bu0ZH0B8.js:1:18578)
    at _P.openDb (/tmp/.mount_tutano2FVFsI/resources/app.asar/desktop/DesktopMain.js:23:124316)
(node:3115) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
resolving key... tutanota-vault
config up to date
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2024-07-24T21:21:55.882Z] using safeStorage with backend gnome_libsecret
[DesktopMain] getting dictionaries from: https://app.tuta.com/desktop/dictionaries/
[2024-07-24T21:21:56.036Z] Create tray:true
[SSEFacade] last missed notification check: { lastMissedNotificationCheckTime: 1721852131675 }
[ApplicationWindow] webAssetsPath:  /tmp/.mount_tutano2FVFsI/resources/app.asar
default mailto handler: false
Webapp ready
[2024-07-24T21:21:56.134Z] [ElectronUpdater] INFO: Checking for update
[2024-07-24T21:21:56.134Z] [ElectronUpdater] INFO: checking-for-update
[SSE] connect
[SSE] state: connecting
[DesktopMain] spellcheck-dictionary-initialized en-GB
desktop file exists, checking version...
[SSE] lookup
[SSE] lookup
[DesktopMain] getting dictionaries from: https://app.tuta.com/desktop/dictionaries/
[DesktopMain] spellcheck-dictionary-initialized en-GB
[SSE] established SSE connection with code 200
[SSE] state: connected
[SSE] heartbeat
[SSE] state: connected
[SSEFacade] heartbeatTimeout 240
[SSE] heartbeat
[SSE] state: connected
[SSEFacade] notification
[SSE] heartbeat
[SSE] state: connected
[SSEFacade] last missed notification check: { lastMissedNotificationCheckTime: 1721852131675 }
[SSEFacade] downloading missed notification
[SSE] state: connected
[2024-07-24T21:21:57.188Z] [ElectronUpdater] INFO: Update for version 235.240718.0 is not available (latest version: 235.240718.0, downgrade is disallowed).
[2024-07-24T21:21:57.188Z] [ElectronUpdater] INFO: update not available: {
  version: '235.240718.0',
  files: [
    {
      url: 'tutanota-desktop-linux.AppImage',
      sha512: 'qrP0BCDJJMr9NJSCC9zdmAEomW4TXLooftxJOpPCbmnI/N6pehsFYbaqh7OQOGq4d9/U5fj5pyO4MZS7rOsUwg==',                                                 
      size: 127302353,
      blockMapSize: 133861
    }
  ],
  path: 'tutanota-desktop-linux.AppImage',
  sha512: 'qrP0BCDJJMr9NJSCC9zdmAEomW4TXLooftxJOpPCbmnI/N6pehsFYbaqh7OQOGq4d9/U5fj5pyO4MZS7rOsUwg==',                                                     
  releaseDate: '2024-07-19T11:46:10.394Z',
  signature: 'McW8KnxVUVuua2UMt4ZPYyLw0l0c7tmBZknHBIyqbs/EmBeQE8H0mY1+DKfdiKiolUYQL6M+w6TzNkawmiuIxRJ/gvJWLj52R2RmhRUrxzqkqBQL1VK1DJV6RfrbvD/1SKcaUih6cnKuDligPLgtUmj79XbP1uX25B4DpfnHl2hwBdN7uD8wbpv7Mwys+GlmOhJ10hUgurHjw6a5Ci9j0Mg1ejO9XvwCPQ2EcKMIoQ2q4JmzMqBfUjKb4LDBpKy2MxWS6s1qgKVG+jNh5gug5UDLBYljS0iX9PmgJYOJgu4vcqnfiF0uPoSm0qQKbo0cnBhm2gnuVIfrEgaFbUiOMQ=='                          
}
[SSEFacade] downloaded missed notification

(tutanota-desktop:3115): GLib-GIO-CRITICAL **: 14:22:01.433: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed


i removed it, no difference.
