### ISSUE TITLE
Large email bodies take very long until displayed

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#725]

**Comment by vitoreiji** [comment]
How large? How long?

For reference, I just tested 500 paragraphs (371Kb) of lorem ipsum and it loaded as fast as a short one paragraph email.

**Comment by armhub** [comment]
Maybe it was related to a high number of links in the email. The autolinker library still needs much time to create links, but in absolute time it does not seem to be a problem (any more), so closing this issue.
