### ISSUE TITLE
Minor string inconsistency in English UI

### ISSUE THREAD

**Issue by dmlls** [tutao/tutanota#7268]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in web app**

**Describe the bug**
There is a minor inconsistency in folders with no messages in the "No email selected" string. Notice that it does _not_ end with a period while the "No messages." does:

![english](https://github.com/user-attachments/assets/53cf095e-4f62-40c8-b5d9-7568ec886bc0)

This issue is not present in other languages. E.g., for Spanish:

![spanish](https://github.com/user-attachments/assets/599d8064-e982-4e65-a6c6-90d9cb06d808)

**To Reproduce**
1. Go to an empty folder (e.g. a newly created folder).

**Expected behavior**
Both the "No messages." and "No email selected." strings end with a period.

**Screenshots**
See above.

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by charlag** [comment]
thank you, this should be fixed!
