### ISSUE TITLE
Secret storage issue on Windows 11

### ISSUE THREAD

**Issue by njmulsqb** [tutao/tutanota#7270]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x ] I've searched and did not find a similar issue.

**Describe the bug**
I am facing https://tuta.com/support/#secretstorage issue on Windows 11, tried reinstalling the client but the issue persist.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by charlag** [comment]
Duplicate of #7247
