### ISSUE TITLE
Run the iOS Tests in the `Swift CI` workflow

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#7314]
The `Swift CI` GitHub Action workflow (`.github/workflows/swift-test.yml`) should also run the tests under `app-ios/tutanotaTests` and `https://github.com/tutao/tutanota/tree/master/app-ios/TutanotaSharedTests`. That way, we can be sure these tests pass on any given PR without manually running them.

**Comment by charlag** [comment]
I think this was done as part of #7285

**Comment by rezbyte** [comment]
> I think this was done as part of #7285

Ah, it seems so. I will close this issue then.
