### ISSUE TITLE
Tuta app on the watch

### ISSUE THREAD

**Issue by georg122** [tutao/tutanota#7329]
I tried to sideload the tuta apk file on my watch, the installation was successful but when I clicked to open the app on the watch, it wouldn't open. The only thing I notice was that on notifications tab of the watch would say “notification service, syncing notification”
The watch doesn't have a webview component, so any app that uses that component, won't work/open

Not a bug probably. Other apps I sideloaded work fine

**Comment by rezbyte** [comment]
Hi @georg122,
Thank you for your report.

Unfortunately, we do not have any plans to add smart watches as a supported platform.

**Comment by georg122** [comment]
> Hi @georg122, Thank you for your report.
> 
> Unfortunately, we do not have any plans to add smart watches as a supported platform.

Hi @rezbyte 
Thank you for your reply.
I actually was curious if the app uses webview and they told me yes. That's why it doesn't work on the watch.
