### ISSUE TITLE
Autocomplete domain name during login

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#733]

**Comment by NicoCG** [comment]
@charlag is that necessary why not just let users login with there username example `bob@tutanota.com` becomes just `bob`?

**Comment by charlag** [comment]
@NicoCG because we offer multiple domains and `bob@tutanota.com` and `bob@tutanota.de` may be two different accounts.

**Comment by NicoCG** [comment]
@charlag, okay that makes sense I’m so use to protonmail where you can login with domain or username and they have a protonmail.ch and protonmail.com but I think it’s one account which is why you can login with username.

**Comment by charlag** [comment]
Duplicate of #192
