### ISSUE TITLE
App does not load mail

### ISSUE THREAD

**Issue by RJDan** [tutao/tutanota#7334]
- [x ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
The app does not load the contents of mail. I can see that new mail has arrived and I can see the subject line but when I tap to read the message I get the following error message:

```
Some parts of the email failed to load due to a lost connection. 
Try again.
```
I have had this problem for more than 4 months and for several app updates. I have tried removing the app and reinstalling it. This did not help. 

**To Reproduce**
1. Use the app.

**Expected behavior**
Message should load when I tap on the message.

**Smartphone (please complete the following information):**
 - Device: Huawei nova 8i
 - OS: EMUI 11.01.1  
 - Android 10

**Comment by rezbyte** [comment]
Hi @RJDan,
Thank you for your report.

This might be related to #6490. Have you tried [updating your webview](https://tuta.com/support/#web)?

Kind regards
\- rezbyte

**Comment by charlag** [comment]
It is *very* likely that this is a WebView issue

**Comment by wrdhub** [comment]
@RJDan Have you tried what was suggested? Does this continue to happen?

**Comment by RJDan** [comment]
Sorry for the delay. I am using a Huawei phone so I don't have google play services. I tried to install WebView from ApkPure and the available apps failed due to missing libraries so I stopped there.
