### ISSUE TITLE
[ios] Cannot login with autofill in mobile apps using 1Password

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#734]

**Comment by charlag** [comment]
Reported for v3.41.7
Happens both in FF on Windows 10 and in iOS app.

**Comment by Jacalz** [comment]
Same issue for me when using Bitwarden, please fix this 😬

**Comment by charlag** [comment]
The fact that you see the hint is just a symptom of the problem: autofill is propogated somehow differently than typing in password so we don't receive the same event and don't react.
Would be nice if we knew which event is sent (if any) during autofill.

**Comment by mpfau** [comment]
The autofill problem also occurs with the 1password password generator (the generated password must be copied manually).
