### ISSUE TITLE
Tuta Webpage linking to tuta-crypt-spec.pdf is missing - doesn't exist! 

### ISSUE THREAD

**Issue by taylor-p-mason** [tutao/tutanota#7354]
The webpage at:
https://tuta.com/blog/post-quantum-cryptography

For the section: The complete protocol specification is available on our website: TutaCrypt

Which links to: 
 https://tuta.com/resources/documents/tuta-crypt-spec.pdf

but this resource doesn't exist as of 2024-08-08 11:52

![2024-08-08 001962](https://github.com/user-attachments/assets/247ca0fc-634c-4019-a319-bb0ad386feef)

**Comment by charlag** [comment]
thank you, it's fixed now!
