### ISSUE TITLE
No spellcheck in Linux flatpack 235.240718.0

### ISSUE THREAD

**Issue by drew585** [tutao/tutanota#7360]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Spell check does not work in linux flatpack 235.240718.0.
Works in appimage

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linux mint 22
 - Desktop Environment, if applicable (on Linux) Cinnamon.

**Additional context**

**Comment by charlag** [comment]
Please report to https://github.com/flathub/com.tutanota.Tutanota/
