### ISSUE TITLE
My email address is automatically added as a recipient when I add a recipient.

### ISSUE THREAD

**Issue by jjustins** [tutao/tutanota#7364]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
My email address is automatically added as a recipient when I add a recipient. So for example if I want to send an email to my mom, i type her address, press "enter", then her address and mine are added in the "send to" field. This leads me to send more mails than I want, it pollutes my mailbox and also impacts my spam box somehow.
At first I thought it was a parameter but I cannot change it, and I did not see the bug in your github.

**To Reproduce**
(Forgive me if I don't have the good terminology my tuta is in French so I'm translating.
1. Go to 'New message'
2. Click on 'Send to'
3. Type someone's adress
4. Press enter
5. See error

**Expected behavior**
Only one email address is added, not mine, the other one.

**Screenshots**
<img width="786" alt="Screenshot 2024-08-09 at 11 36 42" src="https://github.com/user-attachments/assets/b7cbdc4d-2f78-4756-83ed-b6a8f2dcee99">

**Desktop (please complete the following information):**
 - OS: iOS
 - Version v235.240712.0

**Comment by rezbyte** [comment]
Hi @jjustins,
Thank you for your report.

This appears to be the same issue as #6904 just on iOS, both are likely a regression of #296. I will add a note on #6904 so we can track this easier.  We will keep an eye out for this one!

Kind regards,
- rezbyte
