### ISSUE TITLE
Payment verification is broken - Braintree API call always fails due to disallowed characters in `amount` parameter

### ISSUE THREAD

**Issue by pastiche** [tutao/tutanota#7370]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

### **Describe the bug**
New paying customers (and existing users upgrading their plan) are unable to pay for their accounts, as credit card verification always fails. **Tuta is currently unable to onboard new paying customers unless they use PayPal to complete their order**, so this should probably be considered high-priority.

After some testing I have determined that this error occurs due to an invalid API call being made to your payment processor (Braintree) on the card verification page, meaning that the attempted verification is never actually processed. The Braintree API call ending in `/three_d_secure/lookup` always returns HTTP 422 (Unprocessable Content) and the following error message:

> Amount can be any number of digits optionally followed by a decimal point `.` and up to two decimal places following the decimal point. Commas `,` are not allowed.

It appears that the value for `amount` passed from the payment form to the card verification page contains a currency symbol (e.g. "€3.60"), which is not allowed per [Braintree's documentation](https://braintree.github.io/braintree-web/current/ThreeDSecure.html#verifyCard:~:text=The%20amount%20of%20the%20transaction%20in%20the%20current%20merchant%20account%27s%20currency.%20This%20must%20be%20expressed%20in%20numbers%20with%20an%20optional%20decimal%20(using%20.)%20and%20precision%20up%20to%20the%20hundredths%20place.%20For%20example%2C%20if%20you%27re%20processing%20a%20transaction%20for%201.234%2C56%20%E2%82%AC%20then%20amount%20should%20be%201234.56.). In my testing I was able to get a payment to proceed simply by modifying the offending API call to remove the currency symbol (i.e. changing the `amount` variable from "€3.60" to "3.60"), so fortunately the fix should be simple.

### **To Reproduce**
1. Create a new paid account or attempt to upgrade an existing free account to a paid plan.
2. Go through the payment steps and enter your card details.
3. After entering the card details, you should receive the message "Your credit card needs to be verified with your bank. A new window will be opened for this purpose".
4. Once you click "OK", the payment verification page ([Braintree.html](https://github.com/tutao/tutanota/blob/master/src/braintree.html)) opens to verify the card. This process always fails due to the API error described above. Returning to the payment page displays the message "The verification of your credit card has not been completed yet. Please try to verify your card at a later time if this problem persists". 
5. The user is unable to proceed and cannot pay for their account.

### **Expected behavior**
The user's card should be verified, allowing them to complete their order.

### **Additional context**
Multiple users have posted about this bug on the support subreddit over the past few weeks, and it has likely existed for at least a month, possibly longer:
https://old.reddit.com/r/tutanota/comments/1eoum9g/problem_upgrading_account/
https://old.reddit.com/r/tutanota/comments/1ekiipc/card_verification/
https://old.reddit.com/r/tutanota/comments/1ehppye/no_way_to_pay_upgrading_account/
https://old.reddit.com/r/tutanota/comments/1edyak6/trying_to_give_you_my_money_but_your_website_wont/
https://old.reddit.com/r/tutanota/comments/1e35xi9/cant_pay_for_subscribtion_and_lost_mail/
https://old.reddit.com/r/tutanota/comments/1d3gyez/does_this_company_want_my_money_or_not/
https://old.reddit.com/r/tutanota/comments/1c37m8d/tutanota_mail_cannot_verify_my_credit_card_to/

**Comment by rezbyte** [comment]
Hi @pastiche,

Thank you for such a thorough investigation into this issue! We will certainly look into the faulty Braintree call and resolve it soon.

Kind regards
\- rezbyte
