### ISSUE TITLE
Click on notification should open the email on iOS

### ISSUE THREAD

**Issue by wec43** [tutao/tutanota#7372]
## AC
* [x] Click on notification opens the app and selects the corresponding mail in the list.
* [ ] Mail can be displayed before synchronization is done
* [ ] Mail instance is not loaded again.
* [ ] In case the mail has been deleted we show a info message (SnackBar) that the mail has been deleted.

**Comment by charlag** [comment]
Closed by #7498

**Comment by jalhubb** [comment]
> Clicking on notification while offline should be handled gracefully (message & retry action)

No email selected, does not seem very graceful
