### ISSUE TITLE
Click on notification should open the email on Desktop

### ISSUE THREAD

**Issue by wec43** [tutao/tutanota#7373]
## AC
* [x] Click on notification opens the app and selects the corresponding mail in the list.
* [ ] Mail can be displayed before synchronization is done
* [x] Mail instance is not loaded again.
* [x] In case the mail has been deleted we show a info message (SnackBar) that the mail has been deleted.

Try using `Neon` to generate the TutaSDK as a Node module for Electron.

**Comment by charlag** [comment]
Closed by #7438

**Comment by charlag** [comment]
this is https://github.com/tutao/tutanota/issues/7524
