### ISSUE TITLE
Plan prices not loading on iOS in debug/staging builds

### ISSUE THREAD

**Issue by rezbyte** [tutao/tutanota#7381]
**Bug in mobile app**

**Describe the bug**
The plan prices are not displayed in the sign up/upgrade dialog.

**To Reproduce**
1. Sign up
2. See the plan prices are empty

**Expected behavior**
The plan prices from the app store are displayed.

**Additional context**
This likely due to the store kit file not being included in the xcodegen build.

## Test notes
Test on ios.
- [ ] The plan prices appear in the sign up/upgrade wizard in the:
  - [ ] local build
  - [ ] staging/test build
  - [ ] production build

**Comment by jalhubb** [comment]
prices are displaying on prod but not on test build
