### ISSUE TITLE
Chrome login infinite loop

### ISSUE THREAD

**Issue by samengineermyworld** [tutao/tutanota#7383]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Describe the bug**
When logging in using Chrome browser having stored credentials, the login at https://app.tuta.com/ attempts to login and refreshes infinitely. Cleared all browsing data and tired again and login credentials do not work in Chrome. They do work in Firefox.

**To Reproduce**
1. Go to 'https://app.tuta.com/' in Chrome having already stored password
2. Login infinite loop occurs.

**Expected behavior**
Login successful.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Desktop Environment, if applicable (on Linux)
 - Version: 11 Home
 - Browser: Chrome Version 127.0.6533.119 (Official Build) (64-bit)

**Additional context**
Below is the feedback from the page I received, but can no longer reproduce because username, password, and authentication code is not logging in: after entering the code the page refreshes.

Feedback v240.240731.0 - TypeError - UNKNOWN - Browser

 Client: Browser
 Type: UNKNOWN
 Tutanota version: 240.240731.0
 Timestamp (UTC): Wed, 14 Aug 2024 07:28:47 GMT
 User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
TypeError
 Error message: console.debug is not a function
Stacktrace: 
TypeError: console.debug is not a function
    at chrome-extension://ihcjicgdanjaechkgeegckofjjedodee/injection-tss.js?nonce=9kiwx3j9j0unfq0uakuudri3l2z46hfco6w55z7sate:1:39
    at chrome-extension://ihcjicgdanjaechkgeegckofjjedodee/injection-tss.js?nonce=9kiwx3j9j0unfq0uakuudri3l2z46hfco6w55z7sate:1:1910
    at chrome-extension://ihcjicgdanjaechkgeegckofjjedodee/injection-tss.js?nonce=9kiwx3j9j0unfq0uakuudri3l2z46hfco6w55z7sate:1:2318

--------- Thanks.

**Comment by charlag** [comment]
Hi, judging by the stacktrace the issue is in one of the browser extensions you have

**Comment by samengineermyworld** [comment]
> Hi, judging by the stacktrace the issue is in one of the browser extensions you have

I do have a new extension on Chrome and I don't get the same error on Edge or Firefox, so that makes sense. It's Nordpass, a password manager. Any thoughts on if devs would even work on this?
