### ISSUE TITLE
Please change the blacklist

### ISSUE THREAD

**Issue by Zuzia-Sweetheart** [tutao/tutanota#7388]
could dignitas@dignitas.ch be unblocked? i tried to contact them and my message was rejected, and i know its a tutatona issue because on other mails it works, and i got this message from tuta instead:

<dignitas@dignitas.ch>: host dignitas1.cleanmail.ch[91.208.173.98] said: 554
5.7.1 Service unavailable; Client host [185.205.69.213] blocked using
policy.cleanmail.ch (in reply to RCPT TO command)

**Comment by charlag** [comment]
Please contact support about the issue

**Comment by Zuzia-Sweetheart** [comment]
where do i contact them tho, im not a premium user

**Comment by charlag** [comment]
hello@tutao.de
