### ISSUE TITLE
Android Doze Question

### ISSUE THREAD

**Issue by mudlee** [tutao/tutanota#739]
Hey guys. Just a question. How did you solve that without Firebase, Tutanota app still instantly wakes up if I send an email to my Tutanota address? I deep dived into the code and saw that a job is scheduled and used, and I used the exact same code, but Doze just puts my application to sleep, I cannot avoid it. So for eg. if I'm connected to a http service, it will timeout after a while.
What is your secret here?

**Comment by charlag** [comment]
Hey. We would prefer to keep Github for issues.
Short answer: asking users to disable battery optimizations allows us to use network during doze. Otherwise we would be able to use it only during the job.
