### ISSUE TITLE
No option to choose "Subject" from the dropdown menu in the Enable rich notifications

### ISSUE THREAD

**Issue by shobeira** [tutao/tutanota#7401]
![Screenshot from 2024-08-16 00-17-40](https://github.com/user-attachments/assets/96babde6-e021-40f2-935f-2833fdfbd2b1)

**Desktop (please complete the following information):**
 - OS: Linux
 - Desktop Environment, if applicable (on Linux): Gnome Desktop
 - Version [Ubuntu 22.04 LTS]

It is supposed to have 4 options to choose from (2^2).

**Comment by charlag** [comment]
hi, this option is not available on the desktop client yet.
see #7392

**Comment by shobeira** [comment]
The point is: It is mentioned that it is capable of showing Subject as well as Sender and you are saying it is not planned yet. I am thinking if it has not been planned yet, why it is mentioned in the app NEWS dialog (Screenshot attached already).

**Comment by charlag** [comment]
This dialog should not have been shown in the app, it is a bug (the issue I linked). We apologize for the confusion
