### ISSUE TITLE
login problem on Windows desktop

### ISSUE THREAD

**Issue by Tambel1979** [tutao/tutanota#7416]
When I go to tuta.com or to the tuta link that is my email, the login screen flashes over and over, reloading instead of loading. Sometimes, after a minute or two, it opens, but sometimes it just keeps flashing and doesn't load. I have no problem with my tuta account on android, so it's s Windows problem.

Go to tuta.com
Click on Login
screen flashes and doesn't log me in

Desktop Aorus Elite
Windows 11 Pro
Version 22H2

- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by Tambel1979** [comment]
Feedback v240.240816.0 - TypeError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 240.240816.0
 Timestamp (UTC): Fri, 23 Aug 2024 15:41:28 GMT
 User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
TypeError
 Error message: console.debug is not a function
Stacktrace: 
TypeError: console.debug is not a function
    at chrome-extension://ihcjicgdanjaechkgeegckofjjedodee/injection-tss.js?nonce=ytonkm6ftj8xkpb99uexdr48q661yc42a4qpavnak4:1:39
    at chrome-extension://ihcjicgdanjaechkgeegckofjjedodee/injection-tss.js?nonce=ytonkm6ftj8xkpb99uexdr48q661yc42a4qpavnak4:1:1910
    at chrome-extension://ihcjicgdanjaechkgeegckofjjedodee/injection-tss.js?nonce=ytonkm6ftj8xkpb99uexdr48q661yc42a4qpavnak4:1:2318

**Comment by charlag** [comment]
Hi, this is a problem in the browser extension it seems judging by the stacktrace you provided
