### ISSUE TITLE
Unable to access account after updating to new version of app on Ios.

### ISSUE THREAD

**Issue by calvinomni** [tutao/tutanota#7422]
Hi, I can't access either of my accounts after I updated to the latest version (v240.240816.0) of the app, no matter how well I entered my password, I can't access it, and I tried sending my gmail to my tuta mail but it won't send because the email address was not found, I don't know what happened but it's hurting me, I would like you to look into this problem, thanks.
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app & Web app**

**Describe the bug**

**To Reproduce**

**Expected behavior**
- -

**Screenshots**
![Uploading Screen Shot 2024-08-17 at 09.25.59.png…]()

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11 & Web app]
 - OS: [e.g. iOS18.0]
 - Version [e.g. --]

**Additional context**

**Comment by calvinomni** [comment]
Feedback v240.240816.0 - TypeError - UNKNOWN - Browser



 Client: Browser
 Type: UNKNOWN
 Tutanota version: 240.240816.0
 Timestamp (UTC): Sat, 17 Aug 2024 02:11:40 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
TypeError
 Error message: window.ethereum.doSend is not a function
Stacktrace: 
TypeError: window.ethereum.doSend is not a function
    at Object.getChainId (<anonymous>:1:16914)
    at <anonymous>:1:17307

**Comment by charlag** [comment]
Hi, please contact support about the account access.
The second issue looks like some browser extension problem
