### ISSUE TITLE
The feedback system provided by the Tuta team is super hostile

### ISSUE THREAD

**Issue by castarco** [tutao/tutanota#7443]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in how Tuta manages feedback**

**Describe the bug**

1. We have to use Reddit to send "feature requests". This presents several problems:
   - We are forced to give some of our personal data to a third party company if we are in need of new features and we want to communicate it to the Tuta team. It is true that we could say the same about Github, but we were already here, there was no need to force us to create another account.
   - Reddit is a very hostile environment to share feedback in a polite, constructive and productive way. I won't go into much details, but suffice to say that it is full of bigots, racists, sexists, jerks and all sorts of spiteful people who are there just to raise our levels of cortisol while feeling above everyone else.
   - Reddit is not made to keep track of issues. One cannot easily follow the state of an issue and its resolution process, we just have to hope for the best, and assume that someone gave some importance to our words (even if just a bit).
   - The Tuta team can hardly know when the feedback comes from a paying user or from a free user, that makes it much harder to prioritise the resolution of issues.
   - There are no automatic mechanisms to "connect" the state of "issues" with PRs.
   - There is no good system to tag issues (Reddit is usually configured to accept one single flair per post)
   - It is more difficult to find relevant posts/issues (compared to Github)
   - The general tone of Reddit can easily derail conversations about technical topics (and it does).

**To Reproduce**
1. Go to Reddit and see how bad of a platform it is to share feedback about a software application.
2. Put yourself in the shoes of a paying user who wants to have a good and effective communication channel with one of their providers.

**Expected behavior**
- Either have an in-app feedback feature for paying users, or allow them to just use Github for all communication, not forcing them to rely on Reddit.

**Comment by rezbyte** [comment]
Hi @castarco,

\We also offer our [GitHub discussions](https://github.com/tutao/tutanota/discussions/categories/ideas) as a method to provide feedback. Feel free to suggest new ideas and other feedback there.

**Comment by castarco** [comment]
@rezbyte that's fine, but the links in your issue templates don't point there, they point to Reddit.
