### ISSUE TITLE
Review strings and fix typos on the app and the website if confirmed

### ISSUE THREAD

**Issue by luixxiul** [tutao/tutanota#7499]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in web app and website**

**Describe the bug**
Since I am not really supposed to create [a PR](https://github.com/tutao/tutanota/pull/7495) to address ones directly, I want to ask the team to have a look at the typos and fix them by yourself.

- [ ] Fix "can not" to "cannot"
- [ ] Fix "paidEmailDomainSignup_msg": remove a redundant whitespace character
- [x] Fix "businessFaq.store_markdown": the string "on or own" should be "on our own" instead
- [x] Fix "landing.faq_where_msg": the string "on or own" should be "on our own" instead
- [x] Fix "businessShowcase.invite_msg": the string "one tab" should be "one tap" instead
- [ ] Review "calendarFeature.multiUser_msg": the string "few tabs" should be "few taps" instead ? Note there has been a comment on it since one month.
- [ ] Fix "metaTags.protonmailTitle_msg": "tutanota"
- [ ] Fix "zoho.differences_markdown": "tutanota"
- [ ] Fix "gmail.summary_title": "tutanota"
- [ ] Fix "protonmail.comp_title": "tutanota"
- [ ] Fix "proton.summary_title": "tutanota"
- [ ] Fix "faq.login_markdown", "faq.nav_markdown", "faq.2factor_markdown", "faq.reset_markdown": `clicking on *More*` is not correct since it is no longer available on the actual UI
- [ ] Remove strings related to Secure Connect
- [ ] Review "faq.whitelabeling_markdown": "login.tutanota.com" should be "login.tuta.com" ?
- [ ] Review "faq.uninstall-desktop_markdown": "tutanota" ?
- [ ] Review "faq.install-desktop_markdown":  "tutanota" ?
- [ ] Update "yahoo.differences_markdown": `In addition, Tuta Mail is already exploring ways to update its encryption with [post-quantum cryptography]` -> the cryptography has been implemented according to the home page
- [ ] Update "faq.how-to-forward_markdown": remove anchor links to https://tuta.com/best-fastmail-alternative#switch
- [x] Update "faq.how-to-forward_markdown": remove anchor links to https://tuta.com/posteo#switch, https://tuta.com/riseup#switch, and https://tuta.com/web#switch
- [ ] Remove a bunch strings for mail service comparisons, which we no longer have on https://tuta.com/email-comparison, such as "web.differences_markdown", "web.comp_title", "web.comparison_title", "web.forward_markdown", "skiff.differences_markdown", "skiff.comp_title", "skiff.comparison_title", "skiff.us_markdown", "skiff.us_title", "skiff.summary_title", "metaTags.skiffTitle_msg", "skiff.differences_title", "posteo.comp_title", "posteo.comparison_title", "posteo.forward_markdown", "fastmail.comp_title", "fastmail.comparison_title", "fastmail.comparisonEmailPic_msg", "fastmail.comparisonEmailPic_title", "fastmail.forward_markdown", "fastmail.summary_markdown", "metaTags.fastmailDescription_msg", "hushmail.comp_title", "startmail.comp_title", "riseup.comparison_title",  "riseup.forward_markdown", etc (please look up for others). To be honest, it is annoying to finish translations of them only to find that many of them have been removed from there.

**Expected behavior**

They should be fixed or at least you would need to appoint someone to Phrase for replying to comments in a prompt and timely manner, please.

**Screenshots**: irrelevant

**Desktop (please complete the following information):** irrelevant

**Smartphone (please complete the following information):** irrelevant

**Additional context**

**Comment by luixxiul** [comment]
`zoho.differences_markdown` is also outdated in that it mentions Secure Connect and whistleblower features, which no longer are available.

Fix: `plus an exclusive feature  that lacks from Zoho’s offer, Secure Connect, an end-to-end encrypted contact form for your website or intranet, which doubles as a whistleblower system`.

**Comment by luixxiul** [comment]
Edited the first post to add a checkbox to each item.

**Comment by charlag** [comment]
Thank you for the report, the changes will go live soon!
