### ISSUE TITLE
Duplicate paragraphs on https://tuta.com/open-source

### ISSUE THREAD

**Issue by luixxiul** [tutao/tutanota#7500]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in web ~~app~~ page**

**Describe the bug**
There are duplicated paragraphs on https://tuta.com/open-source under headings "Build-your-own customized version of Tuta" and "Thriving Community".

**To Reproduce**
1. Go to https://tuta.com/open-source
2. Scroll down

**Expected behavior**: there should not be duplicate paragraphs there.

**Screenshots**

**Desktop (please complete the following information):** irrelevant

**Smartphone (please complete the following information):** irrelevant

**Additional context**

**Comment by YohYamasaki** [comment]
Thank you for the report, it is fixed now!
