### ISSUE TITLE
Invalid login credential

### ISSUE THREAD

**Issue by thinakaran2000** [tutao/tutanota#7514]
OS : Windows
Browser : Chrome
Issue : My email, password is already saved in chrome. when I login to Tutamail it shows "Invalid login credential"
![Screenshot (13)](https://github.com/user-attachments/assets/4d43ed5f-2b8c-42d9-a36b-98f2cf414f5c)

**Comment by charlag** [comment]
Hi, please contact support about login issues.

**Comment by kdyyy33** [comment]
Hi, 
I have the same problem on safari. I asked the support but i never got any answer from them. By the way, I thought about creating another account and then merge it with the 1st one : is this possible ?
