### ISSUE TITLE
Buy dialog is not shown when upgrading from Premium to Pro

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#754]

**Comment by mpfau** [comment]
Can't reproduce. Payment wizard page is shown for private and business customers when clicking on pro upgrade.

**Comment by armhub** [comment]
I have improved the issue heading to be more accurate. This is how to reproduce:
1. Upgrade to premium
2. Upgrade to Pro -> no pay dialog is shown

**Comment by yopfox** [comment]
With the new prices and the many changes to the subscription implementation this issue is no longer relevant / reproducible.
