### ISSUE TITLE
Reply does not use the correct email address as sender

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#756]
If you reply to an email which has been sent to one of the email addresses which is not the default sender the reply should use the recipients email address as sender and not the default sender email address. 

This does not work if email address contains uppercase letters, e.g.:
email address = "something@tutao.de" and the recipient is SomThing@tutao.de. When replying to such an email the default sender of the mailbox is used.

**Comment by armhub** [comment]
Also check inbox and spam rules
