### ISSUE TITLE
Move time fields in search view out of dialog

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7565]
The "Period of Time" field in the search opens a dialog. This is especially not nice in the calendar app where the filter fields are in a dialog, so it opens a dialog on a dialog. 

Move these fields out so it just has the "From" and "To" fields, no needs to open another dialog

## AC
- From and To fields are directly editable in the first column 
- Search still acts as expected
- Clicking on either field asks a free user to update
- Invalid date selections to not result in an error, but a warning is displayed to the user

## Test notes
- [ ] The date selection is done when date picker loses focus
  - [ ] Mail app search
  - [ ] Calendar app search
  - [ ] Event editor dialog
- [ ] There's a warning when the start date is after the end date
  - [ ] Mail app search
  - [ ] Calendar app search
- [ ] There is a warning when the time period is very long (over 1 year)
  - [ ] Mail app search
  - [ ] Calendar app search
- [ ] Search updates when you change search restrictions
  - [ ] Mail app search
  - [ ] Calendar app search
- [ ] Upgrade dialog is shown when trying to change date or restriction with free account
- [ ] Contact search still works
- [ ] Default date range is:
    - [ ] For Calendar: Start of current month to end of two months in the future
    - [ ] For Mail: Two weeks ago to today

**Comment by hrb-hub** [comment]
No warning when the time period is very long (over 1 year). Popup alerting user of downloading emails still shows
![image](https://github.com/user-attachments/assets/f4774c4a-a640-44f2-8ea0-02d65b23d19e)

**Comment by hrb-hub** [comment]
In event editor, typing date and then clicking outside date input causes input to revert to previously selected date.
Typing date and hitting the Enter key before clicking away work though
