### ISSUE TITLE
TUTANOTA Free Storage not working

### ISSUE THREAD

**Issue by MarySo84** [tutao/tutanota#757]
Hi,
I have a free account of 1 Giga, but I used way below that amount and I am getting the storage limit message.
Even deleting emails, I am always near 1 giga (currently at 0.950). I deleted all my emails.
I would appreciate advise.
Thanks!
Best regards,
User

**Comment by charlag** [comment]
Please don't use Github for support requests.
Check if you cleared your trash and if not please contact hello@tutao.de
