### ISSUE TITLE
The recipient email displayed in notifications isn't always the user's

### ISSUE THREAD

**Issue by paw-hub** [tutao/tutanota#7573]
We rely on firstRecipient to determine which email address to display as the recipient in notifications. However, if you receive an email that has multiple recipients, someone else's email address might be displayed in the notification instead of your own.

On our end, this behavior is expected - firstRecipient was intended to show the first recipient in To>CC>BCC. However, if the recipient address displayed on the notification isn't the user's address, then the user won't know which inbox or alias received it and may be confused.

We do not want to retrieve MailDetails from the blob store on every notification, and changing it to the user's login address isn't particularly useful because this doesn't indicate which mailbox/alias received the email. Instead, we should have the firstRecipient on the received Mail instance (i.e. the instance that is stored in the recipient's inbox) be set to what the recipient would expect.

## AC

- [ ] When a Mail instance is stored in a user's inbox, firstRecipient is set to the address that received it for that inbox. For example, if Alice sends an email to Bob using Bob's alias, then that alias will be displayed here.

## Test notes

- [ ] Send an email with some unique addresses in To, CC, and BCC, all of whom having notifications enabled.
    - [ ] Verify that, for each recipient, their address was shown in their own notification.
- [ ] Send and receive external, secure email and verify that the address shown in the notification is correct.
- [ ] Send and receive external, insecure email and verify that the address shown in the notification is correct.

**Comment by charlag** [comment]
Merged to tutadb (d3c69cf668db24905a2154ce6283fda989f2f4d9)

**Comment by hrb-hub** [comment]
- IOS: Haven't tested it yet for lack of a charged test iphone
- Android: Correct recipient is shown in notification
- Desktop: Incorrect recipient shown in notification (first recipient is shown instead of logged in user)

In the provided screenshot the logged-in user was "free-hrb@tutamail.com"

![Image](https://github.com/user-attachments/assets/60c17baf-691a-4344-8110-279698cf3413)
