### ISSUE TITLE
desktop appimage has difficulties to install in kubuntu

### ISSUE THREAD

**Issue by JohanvdS** [tutao/tutanota#7574]
I am using kubuntu and try to install the appimage.  This are the text during installation below the first lines in Red 

**(node:746892) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tutanota-desktop --trace-deprecation ...` to show where the warning was created)**

what happends and what can I do ?

**Comment by charlag** [comment]
This is not an error, this is a deprecation warning caused by some of our dependencies.
