### ISSUE TITLE
Opening a mail from the notification does not highlight mail in list

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7585]
**Describe the bug**
When clicking on a notification, it opens the relevant mail. This mail is not highlighted in the mail list, so if I click on that mail (the mail that is open and should be highlighted) it reopens the mail I had previously opened. 

**To Reproduce**
1. Have desktop client open and have a mail selected (mail 1).
2. Get a notification for a new mail (mail 2) and click on it.
3. It goes to the desktop client and opens mail 2.
4. Mail 2 is not highlighted in the mail list. <- First Issue
5. Click on mail 2 in the mail list, mail 1 is opened. <- Second issue
6. If a mail other than mail 2 is clicked, that mail is opened as normal.

**Expected behavior**
When the mail is opened, it should be highlighted in the mail list. 

## Test notes

- [ ] Log in on desktop and make sure notifications are enabled
  - [ ] Receive an email while viewing the Inbox and click on the notification. The email should now be visibly selected in the inbox.
  - [ ] Receive an email while viewing the Archive folder and click on the notification. The email should be visible, but you are still in the Archive folder and nothing is selected.
- [ ] On mobile, if not logged in and a notification is selected, the following behavior is true:
  - [ ] Your inbox is loaded (no missing list) with no items selected
  - [ ] The mail preview still shows the mail

**Comment by charlag** [comment]
This works as intended for now as email preview is detached from the list. We should discuss it again.
