### ISSUE TITLE
Cannot set app to Run on Startup on Windows 11

### ISSUE THREAD

**Issue by thetrashcanhero** [tutao/tutanota#7609]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
I'm unable to set the Tuta app to "run on start up" on both my laptop and desktop running Windows 11. When trying to enable the setting I get "an error occurred".

**To Reproduce**
1. Open the Tuta app
2. Click on "settings", click on "desktop"
3. Under "Run on startup" enable to "yes"
4. I receive a "An error occurred" pop up.

**Expected behavior**
To be able to set the Tuta app to run on start up of my laptop and desktop.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: v244.240913.1

**Additional context**
Other users on Reddit report the same problem.

**Test Notes**
- [ ] Try setting run on startup
- [ ] Try setting as default mail handler both
  - [ ] Per user install
  - [ ] Per device install

**Comment by wrdhub** [comment]
Thanks for reporting this, could you get this to happen again and when you see that error pop up, click on Send Report -> then "Details" and copy that? That would be very helpful.

Also, you mentioned Reddit so I tried to find these reports and couldn't, maybe I'm looking in the wrong place?

**Comment by thetrashcanhero** [comment]
> Thanks for reporting this, could you get this to happen again and when you see that error pop up, click on Send Report -> then "Details" and copy that? That would be very helpful.
> 
> Also, you mentioned Reddit so I tried to find these reports and couldn't find any about this issue, maybe I'm looking in the wrong place?

Here are the "details"

Feedback v244.240913.1 - g - PAID - win32
Client: win32
Type: PAID
Tutanota version: 244.240913.1
Timestamp (UTC): Wed, 25 Sep 2024 16:27:41 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/244.240913.1 Chrome/126.0.6478.234 Electron/31.4.0 Safari/537.36
g
Error message: ADD command exited with code 1:
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
Stacktrace:
g: ADD command exited with code 1:
ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
at D (C:\Program Files\Tuta Mail\resources\app.asar\desktop\winreg-DXjUpF_m.js:1:6473)
at ChildProcess.<anonymous> (C:\Program Files\Tuta Mail\resources\app.asar\desktop\winreg-DXjUpF_m.js:1:10912)
at ChildProcess.emit (node:events:519:28)
at maybeClose (node:internal/child_process:1105:16)
at ChildProcess._handle.onexit (node:internal/child_process:305:5)


[Link to reddit post](https://www.reddit.com/r/tutanota/comments/1fn96ma/unable_to_set_tuta_app_to_run_on_start_up/), only 2 people reported this issue so far.

**Comment by wrdhub** [comment]
Thank you for the error and the link to the reddit post, don't know why I didn't find it before.

I was also able to test this on windows 10 and it happens there too, so we should look into this soon. Thanks for the report!

**Comment by charlag** [comment]
This might be related to https://github.com/tutao/tutanota/pull/7189
