### ISSUE TITLE
Undeletable Email Header

I have received an email that I deleted. However, the header of this email is still there and undeletable. How can I help you to help me?

Device: Huawei P20
OS: Android 10

Naturally, this issue isn't reproducible without that specific email. Is there an address I can try to send it to (although that might not work either)?

### ISSUE THREAD

**Issue by Geestbewohner** [tutao/tutanota#7616]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by beatgammit** [comment]
I had a similar issue when I deleted an email on one device while it was open on another, or something like that (or maybe my device was offline).

My "fix" was to reset the app (clear user data) and re-login, which was a pain, but it did work.

I haven't had the issue for some weeks now, so I thought it was fixed, but perhaps not. I'll see if I can reproduce it.

**Comment by Gitchick57** [comment]
Installing / reinstalling also worked for me when I had the same issue.  

Now, I just get numerous miscellaneous error messages when I open my app is all.



Sep 24, 2024, 8:58 PM by ***@***.***:

**Comment by wrdhub** [comment]
Yes, for now the workaround is like what @beatgammit said. Delete credentials (or delete and reinstall the app) and log in again. We're still trying to figure out what exactly causes this.

**Comment by wrdhub** [comment]
@Geestbewohner does what beatgammit suggest help? I'm trying to determine if this is related to that issue or is a different issue.
