### ISSUE TITLE
Latest Android app is unable to show the inbox

### ISSUE THREAD

**Issue by ngrigoriev** [tutao/tutanota#7645]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When starting the app, it seems to be trying to fetch the inbox contents. After a few seconds, it shows "And error occured" popup with the option "Ignore the error for this session" and two options: "Close" or "Send report".

Trying to ignore the issue and close results in empty inbox shown. I have sent the report using "Send report" button.

I can select another mailbox and they do all seem to load, except the inbox. If I switch from, for example, "Sent" to "Inbox", I get the error again. Forcing the app to restart changes nothing. Clearing the app cache does not help either.

**To Reproduce**
1. Start the app'
2. See error

**Expected behavior**
Inbox is shown

**Smartphone (please complete the following information):**
 - Device: Nokia 8.3 5G latest
 - OS: Android 12
 - Version: 244.240912.0

**Additional context**
It is quite obvious that the problem has started to occur after updating to the most recent version of the app.

**Comment by Gitchick57** [comment]
I am having the same problem.  Glad it's not just me.



Oct 1, 2024, 11:49 AM by ***@***.***:

**Comment by charlag** [comment]
Could you please paste the error that you see here as well? it should be accessible from the error dialog.

**Comment by ngrigoriev** [comment]
@charlag 

Yes, found it. 

```
Nikolai Grigoriev <nikolai@grigr.xyz>



--
Nikolai Grigoriev
Feedback v244.240912.0 - Error - PAID - android
Client: android
Type: PAID
Tutanota version: 244.240912.0
Timestamp (UTC): Tue, 01 Oct 2024 15:54:22 GMT
User agent:
Mozilla/5.0 (Linux; Android 12; Nokia 8.3 5G Build/SKQ1.210821.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.125 Mobile Safari/537.36
Error
Error message: CBOR decode error: data to decode must be a Uint8Array
Stacktrace:
Error: CBOR decode error: data to decode must be a Uint8Array
at https://assets.tutanota.com/common-DEqpHnyW.js:1:6216
at bH (https://assets.tutanota.com/common-DEqpHnyW.js:1:6495)
at Ds.decodeCborEntity (https://assets.tutanota.com/worker.js:6:9286)
at Ds.deserialize (https://assets.tutanota.com/worker.js:6:9188)
at Ds.deserializeList (https://assets.tutanota.com/worker.js:6:9749)
at Ds.provideFromRange (https://assets.tutanota.com/worker.js:6:870)
```

**Comment by charlag** [comment]
This issue is "fixed" in 246.240923.0

**Comment by OliverGeneser** [comment]
@charlag When will that build be published to fdroid? 😊

**Comment by ngrigoriev** [comment]
I second this request. I am paying for the email service and the app is broken for two weeks, this is not so great...
