### ISSUE TITLE
Add Calendar to F-Droid

### ISSUE THREAD

**Issue by licaon-kter** [tutao/tutanota#7646]

**Comment by beatgammit** [comment]
I would also like a Tuta F-Droid repo for faster updates.

This could certainly be a separate issue, just figured I'd post here for visibility.

**Comment by rih-tutao** [comment]
A merge request is up!

**Comment by licaon-kter** [comment]
you meant https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15934 ?
