### ISSUE TITLE
Add buttons to copy and print recovery code

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#765]
We should make it as easy as possible to store the recovery code. Printing must be fixed, too (only the recovery-code should be printed, not the currently displayed mail).

**Comment by ganthern** [comment]
Closed with 97fbea13ee20a4d4e68269662ad101ca3fe22182

**Comment by charlag** [comment]
:heavy_check_mark:  Firefox on Ubuntu
:heavy_check_mark:  Chrome on Ubuntu
:x: Firefox on Android throws an error on print, copies successfully
:heavy_check_mark: : DuckDuckGo on Android doesn't do anything on print but it's proabably their fault
:heavy_check_mark: Chrome on Android
:heavy_check_mark: Chrome on Windows
:heavy_check_mark: Firefox on Windows
:heavy_check_mark: Edge on Windows
:heavy_check_mark: Safari on iOS
:heavy_check_mark: Chrome on iOS
:heavy_check_mark: Firefox on iOS
:heavy_check_mark: Chrome on macOS
:heavy_check_mark: Safari on macOS
:heavy_check_mark: Firefox on macOS
