### ISSUE TITLE
Double notification on calendar events 

### ISSUE THREAD

**Issue by serrq** [tutao/tutanota#7668]
Android 14
Tuta Mail
Tua Calendar
OnePlus CPH2399

When I set a reminder within Calendar app event, the alarm performs two time, one time in Tuta Mail and one time in Tuta Calendar.

I want just one notification, from Tuta Calendar.

Please fix it.

**Comment by charlag** [comment]
In the next app version it is possible to disable calendar notifications in the mail app

**Comment by MellieDee** [comment]
Same...

Android 14
Tuta Mail
Tuta Calendar
Pixel 8 pro -
