### ISSUE TITLE
Flatpak application is not verified on Flathub

### ISSUE THREAD

**Issue by pm4rcin** [tutao/tutanota#7678]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**

As described in https://github.com/flathub/com.tutanota.Tutanota/issues/174 I'll copy the text from the author:
```
Flathub has a mechanism for verification, which assures users the package is official and not community maintained. Some users wish to exclusively install verified apps, especially for security critical apps such as this one.

Would Tuta be interested in verifying this package? It appears to be a straightforward process, and won't remove the "experimental" disclaimer from the app page.

https://docs.flathub.org/docs/for-app-authors/verification
```
**To Reproduce**

1. Visit the https://flathub.org/apps/com.tutanota.Tutanota
2. Observe unverified warning 

**Expected behavior**

Desktop client should be verified as an additional guarantee of packaging being done by Tuta.

**Screenshots**
![obraz](https://github.com/user-attachments/assets/0f6bd63d-c0d6-4dc0-a17b-beab498c797e)

**Desktop (please complete the following information):**
 - OS: Linux flatpak
 - Desktop Environment: any
 - Version: any

**Comment by charlag** [comment]
We'll keep track of it in Flathub repo
