### ISSUE TITLE
no he podido crear un correo en Tutanota

### ISSUE THREAD

**Issue by Glorias24** [tutao/tutanota#7685]
he pagado la suscripción por un año para crear un correo en la aplicacion tutanota, intente crear mi cuenta pero no pude seguir porque realmente no entendí el procedimiento.
ahora quiero poder crear mi cuenta pero no encuentro opciones.
le agradezco su colaboración.
cordial saludo

Gloria Stella Barreioe

**Comment by charlag** [comment]
Hi,
please contact support https://tuta.com/support
