### ISSUE TITLE
Emails hang forever and do not send. Drafts to not save either

### ISSUE THREAD

**Issue by enlightenedferret** [tutao/tutanota#7686]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
I cannot send emails. I have internet and other mail services work fine. When I click send I get a status windows saying 'Your Message is Being Sent', which never resolves. I have to quit the application to unfreeze it. When this happens the draft does not save

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by ganthern** [comment]
Hey there :wave:

could you test if v246.241008.0 solves your issues?
