### ISSUE TITLE
New updates not published to F-Droid

### ISSUE THREAD

**Issue by OliverGeneser** [tutao/tutanota#7688]
- [X] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
For 16 days there hasn't been a new update for Tuta Mail in F-droid.
For instance, update 246.240923.0 that fixes #7645 hasn't arrived, and now there is 246.241002.0...

**To Reproduce**
1. Go to Tuta Mail F-droid

**Expected behavior**
I would expect that one of the new updates would have arrived in F-droid within 16 days...

**Smartphone (please complete the following information):**
 - Device: Oneplus 7T

**Additional context**
Maybe it would be a good idea to provide a Tutao f-droid repo, so we don't have to wait for any future updates or critical security patches.

**Comment by charlag** [comment]
The previous release was not tagged properly but 246.241002.0 will be picked up for F-Droid.

**Comment by ngrigoriev** [comment]
@charlag What is the typical delay for F-Droid publishing? 10/02 release, 10/09 now, one week later, still not available there. Without email on my phone for 2+ weeks now due to the CBOR decoded bug.

**Comment by charlag** [comment]
@ngrigoriev we are not responsible nor have any influence on how often F-Droid builds and publishes the apps. Please ask F-Droid team directly.

Deleting credentials and adding them again is still a possible workaround.
