### ISSUE TITLE
[android] Cannot scroll email message vertically

### ISSUE THREAD

**Issue by ff0255** [tutao/tutanota#769]
Android app de.tutao.tutanota v3.37.2 from f-droid. Samsung galaxy note3 SM-N9005, stock firmware, android 5.0.
Wide email messages, that don't fit the screen and can be scrolled horizontally, cannot be scrolled vertically.
Narrow messages, that fit the screen can be scrolled vertically.
So horizontal scrolling prevents vertical.
Let me know, if more info is needed.

**Comment by charlag** [comment]
Hi, thanks for reporting
That's odd, we don't implement any scrolling by ourselves, at least yet.
Could you also try to check which WebView is used (the version is the most important).
Thanks.

**Comment by ff0255** [comment]
Yes, it was a bug in WebView.
I had installed Android System WebView 43.0.2357.121
After upgrade to 70.0.3538.80 scrolling works fine.
Thank you very much.

**Comment by charlag** [comment]
No problem, glad that it's solved
