### ISSUE TITLE
Sync with external calendar via URL fails

### ISSUE THREAD

**Issue by 0utl4w** [tutao/tutanota#7695]
I try to add a public calendar via an URL with the calendar app. Error message asks if I'm sure the calendar is public. It is. When I download the ics-file and import it into a calendar it works, but that's not the solution since the calendar behind the URL is updated regularly. E.g. URL: http://i.cal.to/ical/4437/fiba/team-deutschland-basketball/424997c0.f42b7eb1-1af6cb2e.ics

**Expected behavior**
A new calendar is created and the events are imported and updated regularly.

 - Device: Pixel 6a
 - OS: GrapheneOS
 - Version: 14

Tasks
- [ ] Adjust android manifest (if possible)
- [ ] Adjust validation to https only

**Comment by 0utl4w** [comment]
Hi, it happens with any URL I am trying. But with the app ISCx5 it is no problem to sync these adresses.

Am 9. Oktober 2024 08:14:52 UTC schrieb "André Dias" ***@***.***>:

**Comment by andrehgdias** [comment]
> Hi, it happens with any URL I am trying. But with the app ISCx5 it is no problem to sync these adresses. Am 9. Oktober 2024 08:14:52 UTC schrieb "André Dias" ***@***.***>:
> […](#)
> Hi, thanks for the report. It's probably something with GrapheneOS, but we will investigate further. Does it happen to any URSs or just from the provider you mentioned? -- Reply to this email directly or view it on GitHub: [#7695 (comment)](https://github.com/tutao/tutanota/issues/7695#issuecomment-2401648191) You are receiving this because you authored the thread. Message ID: ***@***.***>

Hi, please try with https.

**Comment by 0utl4w** [comment]
> > Hi, it happens with any URL I am trying. But with the app ISCx5 it is no problem to sync these adresses. Am 9. Oktober 2024 08:14:52 UTC schrieb "André Dias" ***@***.***>:
> > […](#)
> > Hi, thanks for the report. It's probably something with GrapheneOS, but we will investigate further. Does it happen to any URSs or just from the provider you mentioned? -- Reply to this email directly or view it on GitHub: [#7695 (comment)](https://github.com/tutao/tutanota/issues/7695#issuecomment-2401648191) You are receiving this because you authored the thread. Message ID: ***@***.***>
> 
> Hi, please try with https.

Great, that solved it! Thank you!
