### ISSUE TITLE
Mail-daemon

### ISSUE THREAD

**Issue by Nosikmov** [tutao/tutanota#7713]
I created a new mailbox and linked a steam account to it. Two days later I try to log in, the login does not work and no other mail server can send an email to it. What happened to my mailbox and how do I access it?
"Mail Delivery Subsystem <mailer-daemon@googlemail.com>":
The response from the remote server was:
550 5.7.1 : Recipient address rejected: Recipient not found

My Mail: ensorin6@tutamail.com

**Comment by charlag** [comment]
Please contact support about your issue

**Comment by Nosikmov** [comment]
Where me get support contact?

**Comment by Gitchick57** [comment]
***@***.***



Oct 11, 2024, 6:12 AM by ***@***.***:
