### ISSUE TITLE
Tuta app will not open in Ubuntu Linux

### ISSUE THREAD

**Issue by Acerwood** [tutao/tutanota#7743]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by wrdhub** [comment]
Closing since there is no follow up information
