### ISSUE TITLE
Cursor theme is not respected (Linux, Flatpak)

### ISSUE THREAD

**Issue by Odi-3** [tutao/tutanota#7749]
**Describe the bug**
Cursor theme is not respected (the Adwaita cursor theme is replaced by another one whose name I don't know when the cursor is over the window).

**To Reproduce**
1. Open Tuta Mail (Linux, Flatpak)
2. Hover your cursor over the window.

**Expected behavior**
The system cursor theme should be respected.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40 (Workstation Edition)
 - Desktop Environment: GNOME 46

**Comment by charlag** [comment]
Please report Flatpak issues to https://github.com/flathub/com.tutanota.Tutanota/
