### ISSUE TITLE
Label selection dropdown

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7757]
part of #318 
**estimated: 20h**

**AC**
 - [ ] Lists all labels
 - [ ] Unassigned labels have an outlined label icon, assigned ones have a filled one
 - [ ] Label icon is colored like the label
 - [ ] It has a confirmation icon
 - [ ] Items have checkbox semantics for screen readers,  selection status is reflected in accessibility tree

## Test notes:
see #7756

**Comment by hrb-hub** [comment]
Label's selection status (checked or not) is not available on screen readers
