### ISSUE TITLE
Updating via Obtainium - Error: Package ID does not match existing App ID

### ISSUE THREAD

**Issue by EntropicNinja** [tutao/tutanota#7787]
Please see error raised on Obtainium's Github [here](https://github.com/ImranR98/Obtainium/issues/1455#issuecomment-2427883713)

**Smartphone (please complete the following information):**
 - Device: [Pixel 7a]
 - OS: [Android]
 - Version [14]

**Additional context**
Creating this post as it could be a change you have made to the apk as this can indicate a security vulnerability (according @imranr98).

**Comment by ImranR98** [comment]
Resolved at that link. No security issue.

**Comment by ImranR98** [comment]
This issue should be closed iiuc the rest of the discussion at that link.

**Comment by charlag** [comment]
We do not have anything to do with Obtanium
