### ISSUE TITLE
New date does not apply when clicking out of date fields in event editor

### ISSUE THREAD

**Issue by wrdhub** [tutao/tutanota#7789]
When using the event editor on the web/desktop, if you type in a new date and click out of the field the date reverts to the previous date. If you use the date picker or type the date and then tab out of the field or hit enter, the date is changed

## Test notes
- [ ] Changing the dates (start and end) works in the search view
    - [ ] When changing a date by clicking a date from the date picker
    - [ ] When changing the date by typing a new date and navigating away
        - [ ] by clicking out of input box
        - [ ] with the keyboard (such as tab)
    - [ ] The search is updated when changing the date by any of the above methods
- [ ] Changing the dates (to and from) works in the event editor view
   - [ ] When changing a date by clicking a date from the date picker
   - [ ] When changing the date by typing a new date and navigating away
       - [ ] by clicking out of input box
       - [ ] with the keyboard (such as tab)

**Comment by hrb-hub** [comment]
Tabbing away from date input seem to work the first time, but re-editing the field and tabbing away a second time seem to revert the field to the previous date.
To reproduce:
- Change date with keyboard and tab away.
- Go back to the same field and edit again with keybord.
- Tab away and see date reverts to previous one.
