### ISSUE TITLE
external sharing opens only calendar app

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#7803]
**Bug in mobile app**

**Describe the bug**
When sharing from an external application (e.g. Reddit/Youtube/etc.), selecting the Tuta Mail app opens the Tuta calendar app.

**To Reproduce**
1. Use any app with sharing
2. Select Share via Tuta Mail app
3. Tuta Calendar app opens

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 18.0.1

**Additional context**
When the calendar app is not installed, it will state that sharing was successful but nothing happens
According to user report this previously working for sharing via email

**Comment by charlag** [comment]
Duplicate of #7705
