### ISSUE TITLE
Body mail text in black color over dark mode bg

### ISSUE THREAD

**Issue by dgrafhub** [tutao/tutanota#7820]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
As I'm in Tuta Mail dark mode and reply to some external email with bright mode, I can't read the previous messages properly by scrolling down, cause the texts colors of the sender are in black over my dark bg.  

**To Reproduce**
1. Go to 'some hotmail account and write a message to a Tuta mail.
2. To see error, you need to be in Tuta dark mode.
3. Click "Reply" for hotmail mail.
4. Scroll down to see the previous messages, the texts from hotmail are all black over dark mode bg. 

**Expected behavior**
I would expect that the texts would be cleaned up of styling and get the color theme color references. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung A54]
 - OS: [Android]
 - Version [14]

**Comment by ngrigoriev** [comment]
This issue has appeared for me some time ago, and it is very annoying. It seems to be happening only for some emails. The email itself is displayed correctly, but when replying, the original email shows black on black! Or, to be very precise, black on very dark grey.

**Comment by zvfcs** [comment]
I've basically had this issue since I started using Tuta (which is a few years before this issue was created). Not for all emails, but many. So I'm not exactly sure what was fixed in this issue?
