### ISSUE TITLE
Https certificate is not secure

### ISSUE THREAD

**Issue by openwebkey** [tutao/tutanota#7844]
- Bu bir özellik talebi değildir (mevcut işlevsellik çalışmıyor, **eksik işlevsellik değil). Özellikleri [forum](https://www.reddit.com/r/tutanota/) veya destek aracılığıyla talep edeceğim. - [ ] Araştırdım ve benzer bir sorun bulamadım. **Mobil uygulamadaki hata** Android 6.1 **Hatayı açıklayın** Hatanın ne olduğuna dair açık ve kısa bir açıklama. Https sertifikası güvenli değil. bağlantı güvenli değil **Çoğaltmak için** Davranışı çoğaltmak için adımlar: 1. ' '...' adresine gidin 2. '....' üzerine tıklayın 3. '....' adresine gidin 4. Hatayı görün **Beklenen davranış** Ne olmasını beklediğinize dair açık ve öz bir açıklama **Ekran görüntüleri** 
![Screenshot_20241031-102320](https://github.com/user-attachments/assets/8c64b654-fc5d-4206-9715-97a91494c988)
Varsa, sorununuzu açıklamaya yardımcı olması için ekran görüntüleri ekleyin **Akıllı telefon (lütfen aşağıdaki bilgileri doldurun):** - Cihaz: [örn. iPhone6] - İşletim sistemi: [örn. iOS8.1] - Sürüm [örn. 22] **Ek bağlam** Sorunla ilgili diğer bağlamları buraya ekleyin.

**Comment by charlag** [comment]
Hi, your OS/Browser are very old and they don't have new root certificates.
