### ISSUE TITLE
Latest Tuta Calendar update doesn't accept login

### ISSUE THREAD

**Issue by serrq** [tutao/tutanota#7855]
Android 14
OnePlus CPH2399
Tuta Calendar (fdroid) 250.241025.0

Impossible login. I am locked out (only calendar app).

**Comment by thetrashcanhero** [comment]
Same issue here

**Comment by murilopereirame** [comment]
Hello @serrq and thanks for reporting this!
You should now be able to login again with the latest version available on F-Droid.

I'll keep this open for some time for possible reports.
