### ISSUE TITLE
Linux flatpak desktop app not resizable (on Fedora 41 / Gnome 47)

### ISSUE THREAD

**Issue by ecky-l** [tutao/tutanota#7856]
**Describe the bug**

The app opens a window with a standard size and the window cannot be resized by the usual way (point the mouse to a corner and drag the window larger is not possible)

**To Reproduce**

* install Fedora 41 and the tuta flatpak
* open tuta and try to resize the window

**Expected behavior**

Window should be resizable

**Desktop (please complete the following information):**
 - OS: Fedora 41
 - Desktop `Environment,` : Gnome 47
 - flatpak Version: 1.15.10
 - Tuta version: v250.241025.0

**Additional context**
I have recently upgraded from Fedora 40 to 41 and had the tuta flatpak installed before.

**Comment by charlag** [comment]
Please report to https://github.com/flathub/com.tutanota.Tutanota/

**Comment by charlag** [comment]
We do manage it but it's easier to keep track of flatpak-specific bugs there as they are numerous and mostly don't have much to do with the main codebase. thank you for opening it there.
