### ISSUE TITLE
The email is sent with the displayed color sometimes

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7857]
from https://github.com/tutao/tutanota/issues/1992#issuecomment-1216306357

> 
> To add to this - the text colour that the RECIPIENT sees is ALSO impacted by the dark/light themes. :|
> 
> So if I send an email in dark theme, the recipient will get text that is shaded light-gray, making it very hard to see.
> 
> to reproduce:
> 
> Open desktop app (I used on Linux, i think it's the same on Android)
> turn on dark theme
> send an email to an outlook/exchange inbox
> open the email in outlook/exchange
> 
> text colour for RECIPIENT depends on whether dark/light theme was enabled.. :|
> 
> Expected: Dark/light theme should ONLY impact how it appears for ME as the user, not the formatting of the email that is sent to the recipient....

**Comment by BijinDev** [comment]
Does not seem to happen anymore
