### ISSUE TITLE
HTML mail don't show correctly

### ISSUE THREAD

**Issue by unruhe73** [tutao/tutanota#7860]
- [ x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ x] I've searched and did not find a similar issue.

**Describe the bug**
HTML email presents white background and are not fully readable, some pieces got lost in the view. This happened for some mail I received but also from some mail I send by tutamail Android app to myself.

**To Reproduce**
1. Send an HTML to yourself

**Expected behavior**
A correct complete email with no with background and all the text shown correctly and clickable links.

**Smartphone (please complete the following information):**
 - Device: Umidigi
 - OS: Android
 - Version 10

**Additional context**
It happens also on Linux Desktop app.

**Comment by unruhe73** [comment]
I forgot to say that I'm using dark theme.

**Comment by unruhe73** [comment]
Well, this happen also with light theme.

**Comment by wrdhub** [comment]
Thank you for specifying that this happens both on android and desktop versions. Since the behavior seems to be the same in both places, I don't think we need two issues open. Let's just track it on the first one (#7859).
