### ISSUE TITLE
Feedback v251.241112.0 - ProgrammingError - UNKNOWN - darwin

### ISSUE THREAD

**Issue by flowaespe** [tutao/tutanota#7945]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Seit Tagen erscheint bei der OS WebApp bei Login der einen Mailadresse eine mühsame Programmierfehler-Meldung.

**To Reproduce**
- Tuta Desktop App auf Mac OS (Sonoma 14.2.1) geöffnet. Sehe dann meine zwei Mailadressen.
- Account angeklickt (öffnet normalerweise, weil schon eingeloggt)
- Fehlermeldungen
    - links unten: Server konnte nicht erreicht werden, ich sei offline (was nicht sein kann, weil andere TutaMail funktioniert)
    - in der Mitte: ein unerwarteter Fehler ist aufgetreten. Bitte versuche es später erneut. (hab ich schon seit Tagen versucht)

**Expected behavior**

**Screenshots**
<img width="894" alt="Bildschirmfoto 2024-11-15 um 08 25 05" src="https://github.com/user-attachments/assets/28beec00-6dea-43f9-8f18-f94180ef11ab">

**Desktop (please complete the following information):**
 - OS: MAC OS Sonoma 14.2.1

**Additional context**
Feedback v251.241112.0 - ProgrammingError - UNKNOWN - darwin

 Client: darwin
 Type: UNKNOWN
 Tutanota version: 251.241112.0
 Timestamp (UTC): Fri, 15 Nov 2024 07:08:41 GMT
 User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/251.241112.0 Chrome/128.0.6613.186 Electron/32.2.2 Safari/537.36
ProgrammingError
 Error message: Trying to resume the session for user L_M7fxI----1 while already logged in for L_M7fxI----1
Stacktrace: 
ProgrammingError: Trying to resume the session for user L_M7fxI----1 while already logged in for L_M7fxI----1
    at qo.resumeSession (asset://app/mail-worker.js:23:6993)
    at asset://app/common-C_spbC6L.js:1:6315

**Comment by pintert3** [comment]
I'm getting this too. I'm on Arch Linux, and I started seeing it about last week. After the last update, it first failed to log in with an unknown error. And when I dismissed the error and tried logging in again it brought this. When I closed the app, and restarted it, it logged me in straight away this time.

**Comment by flowaespe** [comment]
I did and it works now. Thanks!
