### ISSUE TITLE
Cannot send mail with attached file

### ISSUE THREAD

**Issue by vilddyr** [tutao/tutanota#7947]
- [ X ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ X ] I've searched and did not find a similar issue.

**Describe the bug**
I start a new mail and add the recipient a subject and attach a file (I tried both an image and a text file) and click send. Then I get an error message (see attached screenshots).

**To Reproduce**
1. Open Tuta desktop app (I'm using Windows 11)
2. Click on the "New email" button (left hand side just below the "tuta" logo.
3. Add recipient, subject and attach a file (in the screenshots you will I see I added a simple *.txt file)
4. Click "Send"
5. You will see a spinner for 1-2 seconds.
6. ---Up to this point everything is working as usual/expected
7. An error message appears (see screenshots below)
8. I try to send/submit the error report, and the error reappears

**Expected behavior**
I expect that the mail gets send.

**Screenshots**
![Tuta1 2024-11-15 095034](https://github.com/user-attachments/assets/b77bce3c-b774-4394-bc46-812c79a44ac5)
![Tuta2 2024-11-15 095120](https://github.com/user-attachments/assets/b7bf5500-2b02-4f97-a336-208885750081)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro x64
 - Version 10.0.22631
 - Tuta version: v251.241112.0

**Comment by BijinDev** [comment]
Hello, Is this issue still open? I tried to reproduce this issue but not able to find any error.

**Comment by vilddyr** [comment]
Hello,
Thank you for reaching out.
I have just tested this again, but now everything is working as expected.
