### ISSUE TITLE
Unrecognisable characters in "from" and "to" fields

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#796]
Error about unreadable characters was reported by a user. This only occurs for emails received from external.

> Some mail have some of the unrecognisable characters which you can see from the attachment. This happens in both desktop and mobile versions. I notice this when another account sends me an email from external mail address
![unrecognised_characters](https://user-images.githubusercontent.com/8296817/48623013-cabd9600-e9a8-11e8-8532-28129c4f348b.png)

**Comment by charlag** [comment]
Happened to me as well with certain Cyrillic subjects

**Comment by armhub** [comment]
Probably related to #978

**Comment by vitoreiji** [comment]
@charlag I cannot reproduce this currently, can you?

**Comment by charlag** [comment]
I think this is fixed
