### ISSUE TITLE
Modals do not trap focus for mobile screen readers

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#7998]
With either VoiceOver or TalkBack:

1. Open a dialog
2. Keep selecting next item until you reach the end
3. See that the focus moved out of modal instead of looping over

## Context
native `<dialog>`, `inert` attribute or `aria:hidden` can be used to hide the inactive part of the app

**Estimated: 3h**
**Spent: 3.5h**

## Test notes
- [ ] The topmost modal traps focus
  - [ ] When there's only one modal open
    - [ ] Opening a modal traps focus in modal
    - [ ] Closing modal returns focus to the main view
  - [ ] When there are two or more modals open
    - [ ] Opening a modal traps focus in opened modal
    - [ ] Closing topmost modal returns focus to its parent modal

**Comment by BijinDev** [comment]
In android closing models after opening multiple models leads to focus issue. ( Scenario: Open Nav Drawer-> Add Folder-> Select a parent folder-> try to get focus back to the nav drawer by closing models. Which results in getting focus back to mail list though nav drawer is open.)

Same issue : #7118
