### ISSUE TITLE
Keyboard shortcut for applying labels

### ISSUE THREAD

**Issue by charlag** [tutao/tutanota#8007]
**Time taken: 1.5h**

**Test Notes**
- [ ] Open the email, select one or more mails
- [ ] Click L in keyboard to add or remove labels. Able to add labels
- [ ] Not able to add labels when no emails where selected

**Comment by charlag** [comment]
It is possible to open it even when there are no labels

**Comment by diosk7** [comment]
With the new update I'm able to add a label with the shortcut "L" in the web. Is this supposed to be already enabled? Otherwise I have no ability to see or manage labels.
