### ISSUE TITLE
Javascrip JIT

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [tutao/tutanota#8012]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**

When I want to login in Tutanota or Ente Photos, I can't, because in my Browser Javascript JIT is disabled by default and the Problem is, that I always need to enable it, that I can login. And that bothers me a bit.

**To Reproduce**
1. Go to Tutanota Login
2. Click on Login after filling out everything.
3. And then it freezes with this sentences like if it would open.
4. I need to enable it, that it works.

**Expected behavior**

That you fix it or change it somehow.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Xiaomi Poco X3 NFC]
 - OS: [Android 14]
 - Version [LineageOS 21]

**Additional context**

**Comment by charlag** [comment]
Hi. This might be expected, especially on mobile device. The app has to do Argon2 key derivation and it is a very slow operation without WASM or JIT. On Android you are better served by the mobile app.

**Comment by please-knock** [comment]
I am experiencing a similar problem. When JIT is disabled, it takes about 100 seconds to successfully access the inbox, while enabling JIT shortens the loading time to about 5 seconds. I understand that Argon2 key derivation is a very slow operation, but this doesn't mean that users should weaken their security to access a 'secure mail'. I think Proton had a similar issue in the past but it somehow fixed it nowadays. Please don't close this issue.
