### ISSUE TITLE
Cannot save event in Birthday Calendar or delete Birthday Calendar

### ISSUE THREAD

**Issue by ronseger** [tutao/tutanota#8045]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
The calendar folders contains a folder names Birthday that cannot be used to create an event and the folder cannot be deleted. The only modification possible is to change the name of the folder or to change the color.
**To Reproduce**

**Expected behavior**
I expect to be able to use the folder to store birthdays or be able to delete the folder.
**Screenshots**

**Desktop (please complete the following information):**
 - Desktop Environment, if applicable (on Linux)

**Additional context**

**Comment by charlag** [comment]
Hi, you can hide the birthdays calendar but you can't delete it.
