### ISSUE TITLE
calendar selector in event editor has no scrolling option

### ISSUE THREAD

**Issue by jalhubb** [tutao/tutanota#8050]
**Describe the bug**
When having a lot of calendars, there is no scroll-option in the event editor. This can be worked around using the filter to manually look for it but this is user unfriendly as it is not clear there are more to select from.

**Screenshots**

![image](https://github.com/user-attachments/assets/3c1def52-aa7c-43dc-a87a-babb84984662)

**Time Taken: 1.5h**

**Test Notes**
- [ ] Add more than 10 calendars
- [ ] Edit or create an event, select the calendar from scroldown options
- [ ] Able to see the whole list of calendars and the list is scrolable.
- [ ] Able to scroll dropdown in small screens also

**Comment by charlag** [comment]
@jalhubb hi, could you please specify an app version? We might have fixed (or broke) it in one of the latest releases

**Comment by jalhubb** [comment]
The report was on web client "252.241122.0" and reproduced on web & desktop client version "253.241126.2"

**Comment by jalhubb** [comment]
reportedly did work properly in Version 251.241113.0
