### ISSUE TITLE
Desktop app for macOS version 253.241126.2 not starting on macOS 10.15.7

### ISSUE THREAD

**Issue by jackwilliams79** [tutao/tutanota#8054]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**Describe the bug**
Yesterday I updated the Tuta Desktop App for macOS to the latest version 253.241126.2. After the update, the app was no longer able to start. macOS shows a pop up window with message that at least macOS 15 must be installed to run this app.

Before updating, I believe the Tuta Desktop App was on version 251.241108.0 and it worked just fine.

A few questions:
- Will older macOS versions no longer be supported?
- What is the best option to return to a functioning app in macOS 10.15.7?

**To Reproduce**
See description above.

**Expected behavior**
The Tuta Desktop App for macOS should function normally on macOS 10.15.7.

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.15.7

**Additional context**
No additional context

**Comment by charlag** [comment]
macOS 10.15 is not supported by Electron anymore:
https://www.electronjs.org/blog/electron-33-0#breaking-changes

Apple also did not release any updates for it since 2022.

I'm afraid there's not much we can do at this point.

**Comment by jackwilliams79** [comment]
@charlag Thanks for your answer. I suppose there will be no support for older electron versions? What is the best option to return to a functioning app in macOS 10.15.7? Reinstall the older Tuta Desktop App version?

**Comment by charlag** [comment]
I think your best bet is using the browser, if it is still updated on 10.15
