### ISSUE TITLE
"Search index was aborted" no search feature on fresh install

### ISSUE THREAD

**Issue by llbstr** [tutao/tutanota#8068]
- [x] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [x] I've searched and did not find a similar issue.

**"Search index was aborted": no search feature at all on fresh install, macos 15.1.1.**

**To Reproduce:**
1. Start tuta desktop for macos
2. Click on 'search'
3. See error

**Expected behavior:**
See some search results.

**Screenshots:**
![Capture d’écran 2024-12-02 à 16 54 13](https://github.com/user-attachments/assets/12210634-a5bc-41cb-b90f-2ee4d33a0f25)

**Desktop:**
 - OS: macos 15.1.1 (sequoia)
 - mac mini

**Additional context**
Fresh install, then got the same error after I installed it again after a clean uninstall.

**Comment by hrb-hub** [comment]
Thank you for reporting the issue. Unfortunately we were not able to reproduce it based solely on the information provided. If you don't mind, could you please send us your client logs. You can do so by going to Settings -> About (lower left) -> Send Logs, this will open a mail editor with some attachments where you can inspect it and reference this issue before sending it.

You can send the logs to hello[at]tutao.de if you're on the free plan. Alternatively, please contact support via the help icon in the app if you are a paying customer.

Cheers :)

**Comment by llbstr** [comment]
It has been fixed since a one week or so, without making changes.

**Comment by llbstr** [comment]
closing issue
