### ISSUE TITLE
253.241126.2 App cannot be closed

### ISSUE THREAD

**Issue by Chungaa** [tutao/tutanota#8082]
253.241126.2 App cannot be closed 

I noticed something with version 
253.241126.2 cannot be closed. When I swipe the app from right to left it doesn't work.
My smartphone is a Realme GT Neo2 
Android 13.

https://github.com/user-attachments/assets/e281c853-f5e7-4e1b-9544-89719b82b628

**Estimated: 1h**
**Spent: 1h**

## Test notes
 - [ ] Be in inbox in Mail app. Press back button. The app should be closed
 - [ ] Be in another folder in Mail app. Press back button. The app should switch to Inbox
 - [ ] Have side menu open. Press back. The app should close side menu
 - [ ] Open email, press back button, the app should go back to the list
 - [ ] Going back from calendar/settings/contacts should go back to mail in mail app

**Comment by charlag** [comment]
Thank you for the report, we will look at it right away
