### ISSUE TITLE
Logging out while opening an email causes an error.

### ISSUE THREAD

**Issue by YukariTea** [tutao/tutanota#81]
Exact message: "An unexpected error occurred. Please try again later."

This occurs when pressing the logout button immediately after opening an email, or immediately after automatically opening an email (such as from deleting an email and jumping onto the next one).

**Comment by mpfau** [comment]
- Implement a state on the global error handler: All errors should be discarded if it is set to "logging out"
- Show a progress dialog during logout to prevent other actions after clicking on the logout button
