### ISSUE TITLE
Latest Android github release "not a public release"

### ISSUE THREAD

**Issue by beautiful-orca** [tutao/tutanota#8108]
The [Github release of Tutanota App 253.241203.1 (Android)](https://github.com/tutao/tutanota/releases/tag/tutanota-android-release-253.241203.1) states:
"not a public release; this can be deleted."

It is not clear if users can update to this version or if it was published by mistake.

Please clarify in release notes or delete the release.

**Comment by jgoedde** [comment]
Thanks you for pointing that out. I deleted the release since it was an automatically created one that had no effect on the Android platform.
