### ISSUE TITLE
pretty Easy privacy (pEp) support

### ISSUE THREAD

**Issue by BuZZ-dEE** [tutao/tutanota#812]
https://www.pep.security/
https://en.wikipedia.org/wiki/Pretty_Easy_privacy
https://tools.ietf.org/html/draft-birk-pep-02

**Comment by charlag** [comment]
Closing for now due to inactivity

**Comment by 4jNsY6fCVqZv** [comment]
> Does it have any benefits over Autocrypt? How client support compares?

Maybe @fdik can answer that well?
