### ISSUE TITLE
Not receiving emails.  PLEASE HELP.

### ISSUE THREAD

**Issue by Bailuca** [tutao/tutanota#8135]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [X] I've searched and did not find a similar issue.

**Bug in web app**
This is occurring in the mobile app, desktop app, and when I sign in to Tuta online.

**Describe the bug**
I am not receiving emails from at least one specific person. That person does not get a bounceback or any indication that the email has not gone through.  I get no indication that an email was sent--it does not appear in the inbox, spam, trash, archive, or any of the folders.  I created a filter that any email from this email address is to go to my inbox and that is not working.  I am able to send emails to this person who receives them.  Who knows if there are other emails that I am not receiving.  I have contacted Tuta support for help and they are not responding.

**To Reproduce**

**Expected behavior**
I would like Tuta to actually provide some support since I am paying for this email service.  I want to know why I am not receiving emails and how to fix the problem.  It is no use having an email service if emails are not received and I do not even know that I am not receiving them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. Sonoma 14.2.1
 - Browser [e.g. chrome, safari]. Firefox

**Smartphone (please complete the following information):**
 - OS: [e.g. iOS8.1]. iOS 18.1.1

**Additional context**

**Comment by charlag** [comment]
Hi, please discuss the issue with support. Generally we do not discard any emails and you can see rejections in Settings -> Global -> Rejected emails

**Comment by Bailuca** [comment]
I have contacted support multiple times and they have not responded.  According to Settings -> Global -> Rejected emails, none have been rejected.  However, I still am not receiving them
