### ISSUE TITLE
iOS error: File to encrypt does not exists

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#814]
Tutanota version: 3.40.3
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B92

Error message: 
code: -101 message: {"message":"file to encrypt does not exists: \/private\/var\/mobile\/Containers\/Data\/Application\/...decrypted/....jpg"}

**Comment by charlag** [comment]
Does not occur anymore
