### ISSUE TITLE
BadRequestError on updating payment data

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#817]
Error on server: "missing billing agreement"

Tutanota version: 3.39.2
Timestamp (UTC): Wed, 07 Nov 2018 15:30:47 GMT
User agent: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

Stacktrace: 
BadRequestError: 400: LQin1AM----1 | PUT /rest/sys/paymentdataservice
at handleRestError (https://mail.tutanota.com/main-boot.js:1:257018)
at XMLHttpRequest.xhr.onload (https://mail.tutanota.com/worker.js:1:560552)

**Comment by charlag** [comment]
Another report:

> Ich kan nicht mehr auf jährliche Verlängerung stellen. Sowohl App als auch web-browser

**Comment by charlag** [comment]
> Switching from yearly to monthly this error camp up
