### ISSUE TITLE
Read emails

### ISSUE THREAD

**Issue by FloatingLizard** [tutao/tutanota#8181]
- [ ] This is not a feature request (existing functionality does not work, **not** missing functionality).
 I will request features on [forum](https://www.reddit.com/r/tutanota/) or via support.
- [ ] I've searched and did not find a similar issue.

**Bug in mobile app**

**Describe the bug**
When I read an email on Android, or desktop app Linux  and then open the app on IOS the email that was previously read on the other devices appears as unread causing confusion.
**To Reproduce**
reoccurring

**Expected behavior**
If I read an email it should reflect the changes to all the devices
**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: [14]
 - OS: [18.2]
 - Version [TUTA V253.241203.1]

**Comment by marsch1975** [comment]
It's the same when you read a mail with the Windows Desktop App and then open the Andrpoid App, the Android App shows the messages as unread even after days... The Android App just doesn't update what has happend on the other Apps...

**Comment by hrb-hub** [comment]
Tracked in #8041
