### ISSUE TITLE
If we click on “Remember account password” it automatically logs into the account. If we refresh the page, it logs out and logs back in automatically.

### ISSUE THREAD

**Issue by universish** [tutao/tutanota#8188]
If we click “Remember account password” and log into the account once, when we close the tab and then reopen the web page, it logs directly into the account without asking for the password on the account login screen. When we refresh the page, it logs back into the account. 
If we click on “Remember account password” it automatically logs into the account. If we refresh the page, it logs out and logs back in automatically.
I don't want to click on “remember password”. It's a security issue for me. If my computer is hacked, they can easily access my email. 
If I don't click on “remember password”, I have to deal with logging into the account every time I refresh the page or the first time I open the browser because it logs me out of the account. 
There is only one solution to this problem. Put an additional login PIN on the account. Click on “Remember password”. Let's log in to the account. If we close and open the browser, it will open the account because it remembers the password. But it will ask for a PIN code. If we enter the PIN correctly, we will be able to access our emails. 
PIN code feature should also be available in progressive web app and desktop app. 

This is not a feature request. This is a problem. This feature needs to be added to solve the Vo problem.

**Desktop and P.Web App and Web page:**
 - OS: Windows 11 pro 24H2 and fedora 41
 - Browser: firefox, zen, brave
 - Version : current version

**Comment by charlag** [comment]
Hi, there is an "App Password" feature exactly for this use case.

**Comment by universish** [comment]
@paw-hub I also opened issue number 8189. They are two different problems.

@charlag How to activate the feature you mentioned? Where can I set this feature?

**Comment by charlag** [comment]
Settings -> Login -> Unlock method

**Comment by universish** [comment]
> Settings -> Login -> Unlock method

![Ekran görüntüsü 2024-12-24 171141](https://github.com/user-attachments/assets/6b19f137-20e8-432a-be7a-bdcfa2e7b9ce)
No "unlock method"

**Comment by universish** [comment]
Was there a progressive web app in the past? I remember it existed. It seems like it doesn't exist now. is it true?
