### ISSUE TITLE
NotAuthorizedError when trying to load EntityEventBatch for GroupMember of Free/Premium group

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#819]
* owner of the EntityEventBatch is system, but user tries to download it
* we store it in the _lastEntityEventIds although this is not necessary or even an error
* we receive "create" EntityEventBatches from the server althought this is not necessary or even an error
* not tried to reproduced so far

Error message: 
403: LRkPUa-----1 | GET /rest/sys/entityeventbatch/.../...

Stacktrace: 
NotAuthorizedError. 403: LRkPUa-----1 | GET /rest/sys/entityeventbatch/.../...

**Comment by charlag** [comment]
> I came back to the app after upgrading to Premium on the website. It showed it was reloading my inbox. I was about to try to refresh the inbox and this "Oh no!" error prompt came up.
