### ISSUE TITLE
259.241223.2 freezes on quit

### ISSUE THREAD

**Issue by nadesco** [tutao/tutanota#8199]
**Describe the bug**
Version 259.241223.2 of Mac desktop client hangs on quit. The spinning ball appears for a short time and I need to force-quit. I deleted ALL tuta-related files, restarted and reinstalled an earlier version (259....220.0) from a dmg file. It was okay until I updated to the latest version again. I tried ver259....223.0 as well. It also seemed okay but then updated itself (I thought I postponed it) and the problem reappeared.

**To Reproduce**
1. Update to the latest version via the Install option in the app, or install it from a dmg file. The app works fine until Cmd-Q is pressed.
2. It then hangs until I force quit it.

**Expected behavior**
Version 259.241223.2 should quit normally as it did with previous versions. 

**Desktop**
 - Mac OS 14.7.2

Have added a log file
[Tuta Mail_2024-12-25-224516_Mac-mini.txt](https://github.com/user-attachments/files/18246271/Tuta.Mail_2024-12-25-224516_Mac-mini.txt)

**Comment by pentool** [comment]
Yup. Same issue here.

macOS 12.7.6

**Comment by x3003** [comment]
> this is a duplicate of https://github.com/tutao/tutanota/issues/8198

For me, on windows, it doesn't freeze. So maybe mac only ?

**Comment by reset131** [comment]
> Yup. Same issue here.
> 
> macOS 12.7.6

Same issue here. 12.7.6

**Comment by hrb-hub** [comment]
@nadesco , Thank you for the logs. Like @pirate486743186 said, the process seem to not terminate on all platforms. When trying to reproduce it locally on our Mac, the client didn't hang like it did for you, but the process kept running and trying to relaunch without killing the process resulted in the client not responding.

I'm closing this issue as it will be tracked in #8198
