### ISSUE TITLE
vnode._state is undefined

### ISSUE THREAD

**Issue by bedhub** [tutao/tutanota#835]
This error only occurs in older Firefox browsers. see  https://github.com/MithrilJS/mithril.js/issues/2067

Client: Browser
Type: FREE
Tutanota version: 3.41.4
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/40.0

**Comment by charlag** [comment]
Was reported for 
```
Tutanota version: 3.42.1
User agent: 
Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
```

**Comment by charlag** [comment]
Did not see the error for quite some time
