### ISSUE TITLE
Subscription selector layout issues

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#878]
- Firefox: Title in dialog not centered
- Firefox: Third subscription box is line wrapped if scrollbar is shown

**Comment by asteintutao** [comment]
"Title in dialog not centered" also in edge browser
in addition: A "X" is included maybe as a multiplication symbol. Disappears if the field is not selected.
![grafik](https://user-images.githubusercontent.com/31402512/49374755-9cf38380-f702-11e8-8e99-4cc8c7f8911a.png)

**Comment by charlag** [comment]
> "Title in dialog not centered" also in edge browser
> in addition: A "X" is included, can be used to erase the input of the text field if clicked. Disappears if the field is not selected.
> ![grafik](https://user-images.githubusercontent.com/31402512/49374755-9cf38380-f702-11e8-8e99-4cc8c7f8911a.png)

this is some edge weirdness and may not be fixable.
