### ISSUE TITLE
Support CAA (DNS Certification Authority Authorization)

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#898]
We currently do not support it because we support DANE which is even stronger. But as DANE is not really checked in browsers by default, we should probably also support CAA soon.

**Comment by ofiqfakj** [comment]
Yes, please enable DNS-CAA support.

**Comment by zack-95** [comment]
I think it's a super quick win that doesn't require any code changes. Just list the CA's you use and publish the record with your DNS provider.

**Comment by optomux** [comment]
Status update please?

**Comment by armhub** [comment]
Done
