### ISSUE TITLE
Email subfolders

### ISSUE THREAD

**Issue by armhub** [tutao/tutanota#927]
As a user I want to be able to create mail folders inside other folders so that i can organize my mailbox hierarchically.

### Acceptance criteria
- [x] #4829 
- [x] #4858 
- [x] #4861 
- [x] #4888

**Comment by portstrom** [comment]
I believe that having a hierarchy of subfolders will make things significantly more complicated, both in terms of implementation and in terms of UX. I would recommend canceling this feature and instead implementing tags (#318), which are both simpler and more versatile. I would go as far as to recommend removing the folders feature altogether to replace it with tags.

**Comment by 4jNsY6fCVqZv** [comment]
@portstrom Exciting idea with the tags, I like well!
@armhub And somehow I am curious to understand why there is no possibility for subfolders yet. That must have been a conscious decision on your part, right? Cause folders are so standard classic feature, aren't they?
I also think that with tags and a good search it becomes easier to think/organize than in folders, because tags can express more connections than a single folder.

**Comment by armhub** [comment]
As @portstrom already pointed out, the UI would be much more complex with subfolders, therefore we decided to just allow a set of custom folders which is shown below the system folders.
But when implementing email import (https://github.com/tutao/tutanota/issues/630) we will have to rethink this because imported mailboxes may have subfolders and we will have to decide how to handle them in Tutanota.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you for your explanation! Do you already have any ideas how such a mixed design could look like? Or does that mean that the tag solution can't be focused?

**Comment by MystifyBFC** [comment]
Personally I prefer folders and once implemented I'll be signing up.

**Comment by OtsoHelenius** [comment]
Gmail tags allow grouping and folder-like structuring, which allows imported mailbox structures to be implemented. My guess is that not aiming for Gmail UX feature parity (or a lacking focus on the UX flexibility) will be a big detriment to the wider adoption of Tutanota.

**Comment by Feuizl** [comment]
Tags could work well for me although I would prefer folders.

Just use tags for Friends/VIP, Unread, etc.

**Comment by reenko** [comment]
In the current version, I can't order my custom folders by myself, getSortedCustomFolders sorting by names. Will it be possible for sub-folders or tags? Should I create a separate request?

**Comment by charlag** [comment]
@reenko we don't accept feature requests here, please use support or Reddit

**Comment by akg83** [comment]
@portstrom As a developer my self, I do not understand what is so complicated in adding one additional level to the top level folders?

@armhub I guess that multiple levels of sub folders will be unnecessary complicated or irritating to the UI, but adding at least one additional level to the top level custom folders is  IMHO very basic, especially when Tutanota is offering people email aliases that might be used for multiple (and many) different usages. if it was possible to add to the top level custom folders just one more level of child sub-folders that could be perfect, and I am not the only person who think like that.

Adding tags is cute, but too many tags are a terrible idea for a practical UI, tags will be a great addition to assist with searching (e.g. searching by tags), but not as a replacement for the parent -> child custom folder feature.

Do what you think is right, but discarding such an essential (and pretty standard) feature will be pity.

**Comment by deeprasmith** [comment]
It is very odd developer couldn't elaborate what so difficult about UI. Every email providers that I tried have subfolders and tags almost on day 1. Subfolder is a feature customers wanted and expected to be already in there since day 1. If I've known Tutanota lacks the technical skills to implement it, I won't consider paying. Imagine developers of Linux and Windows OS tell everyone, 

...implementing folders are hard. It is hard on our UI/UX team. Just jumble up all your files in these seas of first level folder is good enough.

If a user only intents to use Tutanota for a limited usage, then fine. If a user wants to make Tutanota to handle bulks of email volumes like paid users on Outlook, Gmail, Yahoo, etc, then it is "hard on UI". Go else way? Providing a service like Tutanota is hard too. You don't see many for-profit email providers want to do it. And yet, we have Tutanota.

**Comment by Fesothe** [comment]
If you can't do subfolders which I would love to have to organise things better from incoming alias emails/domains (I point all mail from each alias email on a separate domain into a named folder) at least allow a focus switch so we can click/switch into an alias email addresses, so they can have their own top level folders show up.

**Comment by Obi96Sy** [comment]
Can you please provide an update on the progress of this feature implementation? This should be a priority as it will greatly help with the organisation of emails as we are using Tutanota as our main email provider.

**Comment by charlag** [comment]
It is not being worked on yet but it's on roadmap https://github.com/tutao/tutanota/milestone/8

**Comment by sasoriza** [comment]
This is such an essential feature to keeping emails organized - how is this still not implemented?

**Comment by deeprasmith** [comment]
> This is such an essential feature to keeping emails organized - how is this still not implemented?

There are 2 possibilities that I can think of this is not implemented. #1 Tutanota programmers likely not competent to implement it due to legacy codings in place. #2 Customers don't matter, like Firefox, only what Tutanota thinks it is good matters even if totally detached from what customers want just like Firefox-way.

**Comment by vExpertSystems** [comment]
If this works is not implemented, I will never renew the payment! It is an essential feature.

**Comment by eisGeist** [comment]
> I believe that having a hierarchy of subfolders will make things significantly more complicated, both in terms of implementation and in terms of UX. I would recommend canceling this feature and instead implementing tags (#318), which are both simpler and more versatile. I would go as far as to recommend removing the folders feature altogether to replace it with tags.

Subfolders and labels/tags are NOT MUTUALLY EXCLUSIVE, having both of them in place would help a lot in dealing with projects, teams and customers.

**Comment by namoninja** [comment]
Guys... this has been in the pipeline for 4 years now...

I appreciate that _Tutanota_ is focused on the more (quantum) finer aspects of the app, but even as a person willing to sacrifice comforts for the fundamental needs of the services you provide, there is an underlying annoyance & friction behind using your services.

We are in 2022, and whether you are privacy focused or the general user looking for "something else", UI/UX is a fundamental psychological aspect of billions of people using tech to enrich their lives.

Therefore, may I recommend, spending some time (aka investing) in the general usability of your app for the common public. Your current competitor is Proton (in the privacy/security dept.) and ultimately (for the general public) Google, Microsoft, etc...

While I absolutely love folders to keep thing organized, and sub-folders would keep things even more organized, I have often been frustrated with the ability to organize my mail. I have to point out the comment made by Ghost:

> I believe that having a hierarchy of subfolders will make things significantly more complicated, both in terms of implementation and in terms of UX. I would recommend canceling this feature and instead implementing tags (#318), which are both simpler and more versatile. I would go as far as to recommend removing the folders feature altogether to replace it with tags.

Google knows people... and while initially I hated the tags and lack of folder functionality, I have learned to use it well and realized the overall superiority over folders. Technically/Visually, they ARE folders anyways.

I would REALLY appreciate having the ability to tag emails & decide whether to move them away from inbox/perform other actions AND in general... to simplify the "filter" process in emails by not using regex (for the average user)) to organize emails (but PLS keep regex!).

The UI/UX aspect is severely limiting your user base/market influence and simultaneously affecting those die hard fans by limiting what we are able to do by the other providers. Learn from the market/what works, and channel 25% of your resources there (UI/UX). I am sure that you will reach a wider audience, gain the financial support to hire more developers, and maker everyone happier.

If you can implement the tagging system that Google has (with the colors/sub-tags)... man... that is some next level stuff right there ;)

**Comment by Pixdigit** [comment]
As noted [here](https://www.reddit.com/r/tutanota/comments/k5zrln/still_no_unread_filter/) this feature is planned in tandem with filtering options for read/unread status. I think it might be beneficial to also include this information in this ticket. Though if you prefer I can also open a separate feature request.
