### ISSUE TITLE
Getting loged in after canceling lost account access dialog from log in view

### ISSUE THREAD

**Issue by asteintutao** [tutao/tutanota#931]
Need stored credentials 
click "more" dropdown on log in page get into Lost account access dialog then cancel it
expected: not being logged in 
practical: getting logged in automaticaly

**Comment by asteintutao** [comment]
other dialogs, like canceling the sign up process, behave the same

**Comment by yopfox** [comment]
Closed as duplicate of #2549 which has been fixed
