### ISSUE TITLE
Not focus "type to filter" when moving to folder in message view (mobile)

### ISSUE THREAD

**Issue by matsest** [tutao/tutanota#955]
# Description

From: https://github.com/tutao/tutanota/issues/761#issuecomment-447502467

> 
> For me, the keyboard always pops up when pressing the folder icon in a e-mail on Android, as the focus is immediately set on the type field.
> 
> Would it be possible if the focus was only put on the type field if it was actually pressed after the list of folders have been displayed?

Current behavior: Keyboard pops up and hides part of the list of folders. In most cases it's faster to scroll down and find the folder directly. To do this now, you have to manually minimize the keyboard or scroll down in a very small view. 

Wanted behavior: focus set on type field if pressed after list is displayed

# Screenshot

![screenshot_2018-12-17-12-06-07](https://user-images.githubusercontent.com/10927304/50083478-d8567d80-01eb-11e9-89d2-97109915ef41.png)

**Comment by charlag** [comment]
Would you be interested in trying to fix that? I can point you to the place.

**Comment by charlag** [comment]
There are two components which does the same thing (we migrate from one of them): `Dropdown` & `DropdownN` (located in the `src/gui/base`).
They both have a `show()` function which calls `focus()`.
All you need to do is to make a condition using `client.isMobileDevice()`.
Feel free to ask questions!
