### ISSUE TITLE
Bring back old version as an option.

### ISSUE THREAD

**Issue by ryanpcmcquen** [tutao/tutanota#966]
Some of us have old devices or old browsers that work better with the old version of Tutanota. You certainly wouldn't have to support it (and you could put a huge warning around using it), but completely blocking the old version is detrimental to some users.

**Comment by charlag** [comment]
Please don't use GitHub for requests.

We would maybe like to do that but some server side stuff which is required only for the old client (see #156) affects all users and we would like to get rid of that as soon as possible. We have no plans to allow for purely technical reasons.

I would say that industry standard is two major browser versions + Firefox ESR.
We support browsers as old as Chrome 44, Firefox 52 and even IE11 with the next version (maybe even lower but needs checking). Even with these browsers you're under a great security risk.

If you think that some browser version could work well but we mistakenly block it, please let us know.
