### ISSUE TITLE
Authentication popup dismisses when switching to authentication app

### ISSUE THREAD

**Issue by Jacalz** [tutao/tutanota#982]
On my IPhone, the authentication pop up dismisses when switching to Authy for copying the authentication code. Theirs leads to a connection failure and it provents me from logging in. This is driving me insane to be quite honest...

**Comment by charlag** [comment]
Dialog dismissing should be fixed in the latest version, it's on the review by Apple

**Comment by Jacalz** [comment]
Wonderful, thank you 😊
