### ISSUE TITLE
Relax the update checks on Desktop application

### ISSUE THREAD

**Issue by cstackpole** [tutao/tutanota#985]
Testing out the Desktop Application on Lubuntu 18.04. One issue that I've noticed is it checks for an update roughly every 30 seconds. I can't figure out how to get it to check on a different frequency (like once a day maybe?).

```
autoUpdater info: Checking for update
autoUpdater info: Update for version 3.44.9 is not available (latest version: 3.44.9, downgrade is disallowed).
```

There's no reason for that many checks. Maybe once one startup and then every 24 hours after? That seems more reasonable to me.

Thanks.

**Comment by andy5995** [comment]
I've experienced the same on Debian 9. I think checking once at startup would be sufficient, then after that, another check after 24 hours has passed if the app has not been restarted.
