### ISSUE TITLE
fsevents@1.2.4 Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by Kwaskoff** [tutao/tutanota#990]
![image](https://user-images.githubusercontent.com/15308024/50528921-537c3580-0b02-11e9-97ad-11c7a22782c4.png)
AWS t2.micro 
Ubuntu 18.04

**Comment by charlag** [comment]
This just says that the optional dependency won't be installed because it's not compatible with the system (fsevents is a MacOS specific thing afaik)
