### ISSUE TITLE
Do not disclose email address in browser history

### ISSUE THREAD

**Issue by mpfau** [tutao/tutanota#991]
We should not create history events when we change routes (see `options.replace` param on https://mithril.js.org/route.html#mrouteset).

Should fix #367.

**Comment by charlag** [comment]
related to #666

**Comment by charlag** [comment]
`history. pushState()` has a title argument but it is ignored by all browsers.

I have an idea on how to do this:
history events are recorded as `document.title`. Also, they're recorded *while* the page is open.
What we could do is this:
* before pushing the new URL to the stack, set `document.title` to neutral one (this will change current one, not the next one!)
* after pushing it, set `document.title` to normal
* in `beforeunload` listener also set `document.title` to neutral value

This seems to be working (at least in Firefox) but we need to test if the title will be flickering.

**Comment by mpfau** [comment]
The only viable workaround is to use incognito mode for now.
