### ISSUE TITLE
Recipient bubble is not created when pressing on "send" button directly

### ISSUE THREAD

**Issue by andy5995** [tutao/tutanota#995]
## How to reproduce
- use the "invite" feature
- paste the email address in to the "to" field
- click send

A dialog box pops up stating:

`Please correct the invalid email address(es) in the recipient fields.`

## work-around
Immediately following the steps above:
- click ok on the dialog box
- left-click once in the "to" field (the email address pasted in is still there)
- click send

## Bug Trivia
- reproduces every time
- when logged in through my web browser
- when using Linux desktop app

## OS
Debian 9 (64)

## Web browser
Firefox 64.0

**Comment by charlag** [comment]
Thanks for reporting! Will check this out

**Comment by charlag** [comment]
I just checked it and it seems to be working.
It may be that it's related to the email address. Need to investigate a little bit more.

**Comment by andy5995** [comment]
I just tried it again. I noticed it will not reproduce if you use an email address that already exists in your tutanota address book.

Otherwise, I've tried it with 7 different email addresses (none were in my address book) and it reproduces every time.

**Comment by charlag** [comment]
I can try it again, thanks for clarification!

**Comment by bedhub** [comment]
i was able to reproduce this on my ios device when the address is an exernal email address and not stored in the Tutanota contacts.
